= 外經微言
清·陳士鐸
:doctype: book

= 卷一

== 陰陽颠倒篇

黃帝聞廣成子窈窈冥冥之旨，歎廣成子之謂天矣。退而夜思，尚有未穫。

遣鬼臾區問于岐伯天師曰：帝問至道于廣成子，廣成子曰：至道之精，窈窈冥冥；至道之極，
昏昏默默。無視無聽，抱神以靜，形將自正。必靜必清，無勞汝形，無搖汝精，無思慮營營，
乃可以長生。目無所見，耳無所聞，心無所知，汝神將守汝形，形乃長生。慎汝内，閉汝外，
多知爲敗。我爲汝遂于大明之上矣，至彼至陽之原也。爲汝入于窈冥之門矣，至彼至陰之原
也。天地有官，陰陽有藏，慎守汝身，物將自壯。我守其一，以處其和，故身可以不老也。
天師必知厥義，幸明晰之。

岐伯稽首奏曰：大哉言乎，非吾聖帝安克聞至道哉。帝明知故問，豈欲傳旨于萬祀乎，何心
之仁也！臣愚，何足知之。然仁聖明問，敢備述以聞。窈冥者，陰陽之謂也。昏默者，内外
之詞也。視聽者，耳目之語也。至道無形而有形，有形而實無形。無形藏于有形之中，有形
化于無形之内，始能形與神全，精與神合乎。

鬼臾區曰：諾，雖然，師言微矣，未及其妙也。

岐伯曰：乾坤之道，不外男女。男女之道，不外陰陽。陰陽之道，不外順逆。順則生，逆則
死也。陰陽之原，即颠倒之术也。世人皆順生，不知順之有死；皆逆死，不知逆之有生，故
未老先衰矣。廣成子之教示帝行颠倒之术也。

鬼臾區贊曰：何言之神乎。雖然，請示其原。

岐伯曰：颠倒之术，即探陰陽之原乎。窈冥之中有神也，昏默之中有神也，視聽之中有神也。
探其原而守神，精不搖矣。探其原而保精，神不馳矣。精固神全，形安能敝乎。鬼臾區覆奏
帝前。帝曰：俞哉，載之《外經》，傳示臣工，使共聞至道，同遊于無極之野也。

陳士铎曰：此篇帝問而天師答之，乃首篇之論也。問不止黃帝，而答止天師者，帝引天師之
論也。帝非不知陰陽颠倒之术，明知故問，亦欲盡人皆知廣成子之教也。

（淩波按：陳士铎受金丹訣，故能發揚此種至道，若在他人看來當然等于空談。惟受道者且
能切實行于己身者，能語斯言。諸位學醫的同誌，如果沒有學過仙，不管你醫經背得如何流
利，總于此等道理不可能弄懂。于是知世上之事，有可書傳，有可口傳，有隻可心傳，于是
不再拘于書本，進入無我境界，方可謂善讀書者。）

== 順逆探原篇

伯高太師問于岐伯曰：天師言颠倒之术，即探陰陽之原也，其旨奈何？岐伯不答，再問曰，
唯唯三問。

岐伯歎曰：吾不敢隱矣。夫陰陽之原者，即生克之道也。颠倒之术者，即順逆之理也。知颠
倒之术，即可知陰陽之原矣。

伯高曰：陰陽不同也。天之陰陽，地之陰陽，人身之陰陽，男女之陰陽，何以探之哉？

岐伯曰：知其原亦何異哉！

伯高曰：請顯言其原。

岐伯曰：五行順生不生，逆死不死。生而不生者，金生水而克水，水生木而克木；，木生火
而克火，火生土而克土，土生金而克金，此害生于恩也。死而不死者，金克木而生木，木克
土而生土，土克水而生水，水克火而生火，火克金而生金，此仁生于義也。夫五行之順相生
而相克，五行之逆不克而不生。逆之至者，順之至也。

伯高曰：美哉言乎。然何以逆而順之也？

岐伯曰：五行之順，得土而化。五行之逆，得土而神。土以合之，土以成之也。

伯高曰：余知之矣。陰中有陽，殺之内以求生乎。陽中有陰，生之内以出死乎。余與帝同遊
乾無極之野也。

岐伯曰：逆而順之，必先順而逆之。絕欲而毋爲邪所侵也，守神而毋爲境所移也，練氣而毋
爲物所誘也，保精而毋爲妖所耗也。服藥餌以生其津，慎吐納以添其液，慎勞逸以安其髓，
節飲食以益其氣，其庶幾乎。

伯高曰：天師教我以原者全矣。

岐伯曰：未也，心死則身生，死心之道，即逆之之功也。心過死則身亦不生，生心之道又順
之之功也。順而不順，始成逆而不逆乎。伯高曰：誌之矣，敢誌秘誨哉。

陳士铎曰；伯高之問，亦有爲之問也。順中求逆，逆處求順，亦死克之門也。今奈何求生于
順乎。于順處求生，不若于逆處求生之爲得也。

（此一逆字，知者自知，迷者自迷，諸君自扪其心。知否？）

== 回天生育篇

雷公問曰：人生子嗣，天命也。豈盡非人事乎？

岐伯曰：天命居半，人事居半也。

雷公曰：天可回乎？

岐伯曰：天不可回，人事則可盡也。

雷公曰：請言人事。

岐伯曰：男子不能生子者，病有九；女子不能生子者，病有十也。

雷公曰：請晰言之。

岐伯曰：男子九病者：精寒也，精薄也，氣餒也，痰盛也，精澀也，相火過旺也，精不能射
也，氣郁也，天厭也。

女子十病者：胞胎寒也，脾胃冷也，帶脈急也，肝氣郁也，痰氣盛也，相火旺也，腎水衰也，
任督病也，膀胱氣化不行也，氣血虛而不能攝也。

雷公曰：然則治之奈何？

岐伯曰：精寒者，溫其火乎。精薄者，益其髓乎。氣餒者，壯其氣乎。痰盛者，消其涎乎。
精澀者，順其水乎。火旺者，補其精乎。精不能射者，助其氣乎。氣郁者，舒其氣乎。天厭
者，增其勢乎，則男子無子而可以有子矣。不可徒益其相火也。

胞胎冷者，溫其胞胎乎。脾胃冷者，暖其脾胃乎。帶脈急者，緩其帶脈乎。肝氣郁者，開其
肝氣乎。痰氣盛者，消其痰氣乎，相火旺者，平其相火乎。腎水衰者，滋其腎水乎。任督病
者，理其任督乎。膀胱氣化不行者，助其腎氣以益膀胱乎。氣血不能攝胎者，益其氣血以攝
胎乎，則女子無子而可以有子矣。不可徒治其胞胎也。

雷公曰：天師之言，真回天之法也。然用天師法男女仍不生子奈何？

岐伯曰：必夫婦德行交虧也。脩德以宜男，豈虛語哉。

陳士铎曰；男無子有九，女無子有十，似乎女多于男也。誰知男女皆一乎，知不一而一者，
大約健其脾胃爲主，脾胃健而腎亦健矣，何必分男女哉。

== 天人夀夭篇

伯高太師問岐伯曰：余聞形有緩急，氣有盛衰，骨有大小，肉有堅脆，皮有厚薄，可分夀天
然乎？

岐伯曰：人有形則有氣，有氣則有骨，有骨則有肉，有肉則有皮。形必與氣相合也，皮必與
肉相稱也，氣血經絡必與形相配也。

形充而皮膚緩者夀，形充而皮膚急者夭。

形充而脈堅大者，氣血之順也，順則夀。形充而脈小弱者，氣血之衰也，衰則危。

形充而顴不起者，肉勝于骨也，骨大則夀，骨小則夭。

形充而大，肉䐃堅有分理者，皮勝于肉也，肉疏則天，肉堅則夀。形充而大肉無分理者，皮
僅包乎肉也，肉厚夀，肉脆夭。

此天生，人不可強也，故見則定人夀夭，即可測人生死矣。

少師問曰：誠若師言，人之夀天天定之矣，無豫于人乎？

岐伯曰：夀夭定于天，挽回天命者人也。夀夭聽于天；戕賊其形骸，瀉洩其精髓，耗散其氣
血，不必至天數而先天者，天不任咎也。

少師曰：天可回乎？

岐伯曰：天不可回，而天可節也。節天之有余，補人之不足，不亦善全其天命乎。

伯高太師聞之曰：岐天師真善言天也。世人賊夭之不足，烏能留人之有余哉。

少師曰：伯高非知在人之天者乎。在天之夭，難回也。在人之夭，易延也。吾亦脩吾之天，
以全天命乎。

陳遠公曰：天之天難延，人之天易延。亦訓世延人之夭也。伯高之論，因天師之教而推廣之，
不可輕天師而重伯高也。

== 命根養生篇

伯高太師復問岐伯曰：養生之道，可得聞乎？

岐伯曰：愚何足以知之。

伯高再問岐伯曰：人生天地之中，不能與天地并久者，不體天地之道也。天錫人以長生之命，
地錫人以長生之根。天地錫人以命根者，父母子之也。合父母之精，以生人之身，則精即人
之命根也。魂魄藏于精之中，魂屬陽，魄屬陰，魂趨生，魄趨死。夫魂魄皆神也。凡人皆有
神，内存則生，外遊則死。魂最善遊，由于心之不寂也。廣成子謂：抱神以靜者，正抱心而
同寂也。

伯高曰：夫精者，非腎中之水乎？水性主動，心之不寂者，不由于腎之不靜乎？

岐伯曰：腎水之中，有真火在焉。水欲下而火欲升，此精之所以不靜也。精一動而心搖搖矣。
然而制精之不動，仍在心之寂也。

伯高曰：吾心寂矣，腎之精欲動奈何？

岐伯曰：水火原相須也，無火則水不安，無水則火亦不安。制心而精動者，由于腎水之涸也。
補先天之水以濟心，則精不動而心易寂矣。

陳遠公曰：精出于水，亦出于水中之火也。 精動由于火動，火不動則精安能搖乎？！可見
精動由于心動也，心動之極則水火俱動矣。故安心爲利精之法也。

（此段亦精妙，可惜爲誓所拘，不能盡洩）

== 救母篇

容成問于岐伯曰：天癸之水，男女皆有之，何以婦人經水謂之天癸乎？

岐伯曰：天癸水，壬癸之水也。壬水屬陽，癸水屬陰，二水者先天之水也。男爲陽，女爲陰，
故婦人經水以天癸名之。其實壬癸未嘗不合也。

容成曰：男子之精，不以天癸名者，又何故歟？

岐伯曰：精者，合水火名之。水中有火，始成其精。呼精而壬癸之義已包于内，故不以天癸
名之。

容成曰：精與經同一水也，何必兩名之？

岐伯曰：同中有異也。男之精，守而不溢；女之經，滿而必洩也。癸水者，海水也，上應月，
下應潮，月有盈虧，潮有往來，女子之經水應之，故潮汐月有信，經水亦月有期也。以天癸
名之，别其水爲癸水，随天運爲轉移耳。

容成曰：其色赤者何也？

岐伯曰：男之精，陽中之陰也，其色白。女之經，陰中之陽也，其色赤。況流于任脈，通于
血海，血與經合而成濁流矣。

容成曰：男之精虧而不溢者，又何也？

岐伯曰：女子陰有余陽不足，故滿而必洩。男子陽有余陰不足，故守而不溢也。

容成曰：味鹹者何也？

岐伯曰：壬癸之水，海水也。海水味鹹，故天癸之味應之。

容成曰：女子二七經行，稚女不行經何也？

岐伯曰：女未二七則任衝未盛，陰氣未動，女猶純陽也，故不行經耳。

容成曰：女過二七，不行經而懷孕者，又何也？

岐伯曰：女之變者也，名爲暗經，非無經也。無不足，無有余，乃女中最貴者。終身不字，
行調息之功，必長生也。

容成問曰：婦女經水，上應月，下應潮，宜月無愆期矣。何以有至有不至乎？

岐伯曰：人事之乖違也。天癸之水，生于先天，亦長于後天也。婦女縱欲傷任督之脈，則經
水不應月矣。懷抱憂郁以傷肝膽，則經水閉而不流矣。

容成曰：其故何也？

岐伯曰：人非水火不生，火乃腎中之真火，水乃腎中之真水也。水火盛則經盛，水火衰則經
衰。任督脈通于腎，傷任督未有不傷腎者。交接時，縱欲洩精，精傷任督之脈亦傷矣。任督
脈傷，不能行其氣于腰臍，則帶脈亦傷，經水有至有不至矣。夫經水者，火中之水也。水衰
不能制火，則火炎水降，經水必先期至矣。火衰不能生水，則水寒火冷，經水必後期至矣。
經水之愆期，因水火之盛衰也。

容成曰：肝膽傷而經閉者，謂何？

岐伯曰：肝藏血者也，然又最喜疏洩。膽與肝爲表裏也，膽木氣郁，肝木之氣亦郁矣。木郁
不達，任衝血海皆抑塞不通，久則血枯矣。

容成曰：木郁何以使水之閉也？

岐伯曰：心腎無咎不交者也。心腎之交接，責在胞胎，亦責在肝膽也。肝膽氣郁，胞胎上交
肝膽，不上交于心，則腎之氣亦不交于心矣。心腎之氣不交，各臟腑之氣抑塞不通，肝克脾，
膽克胃，脾胃受克，失其生化之司，何能資于心腎乎？水火未濟，肝膽之氣癒郁矣。肝膽久
郁，反現假旺之象，外若盛内實虛。腎因子虛轉去相濟涸水，而郁火焚之，木安有余波以下
洩乎？此木郁所以水閉也。

鬼臾區間曰：氣郁則血閉，血即經乎？

岐伯曰：經水，非血也。

鬼臾區曰：經水非血，何以血閉而經即斷乎？

岐伯曰：經水者，天一之水也，出于腎經，故以經水名之。

鬼臾區曰：水出于腎，色宜白矣，何赤乎？

岐伯曰：經水者，至陰之精，有至陽之氣存焉，故色赤耳，非色赤即血也。

鬼臾區曰：人之腎有補無瀉，安有余血乎？

岐伯曰：經水者，腎氣所化，非腎精所洩也。女子腎氣有余，故變化無窮耳。

鬼臾區曰：氣能化血，各經之血不從之而洩乎？

岐伯曰：腎化爲經，經化爲血，各經氣血無不随之而各化矣。是以腎氣通則血通，腎氣閉則
血閉也。

鬼臾區曰：然則氣閉宜責在腎矣，何以心肝脾之氣郁而經亦閉也？

岐伯曰：腎水之生，不由于三經。腎水之化，實關于三經也。

鬼臾區曰：何也？

岐伯曰：腎不通肝之氣，則腎氣不能開。腎不交心之氣，則腎氣不能上。腎不取脾之氣，則
腎氣不能成。蓋交相合而交相化也。苟一經氣郁，氣即不入于腎，而腎氣即閉矣。況三經同
郁，腎無所資，何能化氣而成經乎？是以經閉者，乃腎氣之郁，非止肝血之枯也。倘徒補其
血，則郁不宣反生火矣。徒散其瘀，則氣益微反耗精矣。非惟無益，而轉害之也。

鬼臾區曰：大哉言乎！請勒之金石，以救萬世之母乎。

陳遠公曰：一篇救母之文，真有益于母者也。講天癸無余義，由于講水火無余義也。水火之
不通，半成于人氣之郁。解郁之法，在于通肝膽也，肝膽通則血何閉哉！正不必又去益腎也。
誰知肝膽不郁而腎受益乎，郁之害亦大矣。

（淩波按：天癸之義大抵相當于“道生一，一生二，二生三，三生萬物”之一，一就是無極，
無極而太極，太極就是有對立統一。中華哲學較諸老馬之學爲高即在此處。說遠了，再說醫
道，天癸相當于腦垂體的內分泌物質。由腦而帶動全身，可謂無極而太極，此不過讓初學有
所把握，說到底還是有所區别）

== 紅鉛損益篇

容成問曰：方士採紅鉛接命，可爲訓乎？

岐天師曰：慎欲者採之，服食延夀；縱欲者釆之，服食喪軀。

容成曰：人能慎欲，命自可延，何藉紅鉛乎？

岐伯曰：紅鉛延景丹也。

容成曰：紅鉛者，天癸水也。雖包陰陽之水火，溢滿于外則水火之氣盡消矣，何以接命乎？

岐伯曰：公之言，論天癸則可，非論首經之紅鉛也。經水甫出戶輒色變，獨首經之色不遽變
者，全其陰陽之氣也。男子陽在外，陰在内；女子陰在外，陽在内。首經者，坎中之陽也。
以坎中之陽補離中之陰，益乎不益乎。獨補男有益，補女有損。補男者，陽以濟陰也；補女
者，陽以亢陽也。

容成曰：善。

陳遠公曰：紅鉛何益于人，講無益而成有益者，辨其既濟之理也。誰謂方士非恃之以接命哉。

（大抵不懂行的人說到紅鉛無不說其無用，痛駡方士誤人。其實世上之事有真必有假落入後
天，本是有兩極的。方法是死的，全在人之運用。紅鉛之友人房中术亦是如此。）

== 初生微論篇

容成問曰：人之初生，目不能睹，口不能餐，足不能履，舌不能語，三月而後見，八月而後
食，期歲而後行，三年而後言，其故何也？

岐伯曰：人之初生，兩腎水火未旺也。三月而火乃盛，故兩目有光也。八月而水乃充，故兩
龈有力也。期歲則髓旺而膑生矣。三年則精長而囟合矣。男十六天癸通，女十四天癸化。

容成曰：男以八爲數，女以七爲數，子知之矣。天師于二八、二七之前，《内經》何未言也？

岐伯曰：《内經》首論天癸者，歎天癸難生易喪也。男必至十六而天癸滿，年末十六皆未滿
之日也。女必至十四而天癸盈，年未十四皆未滿之日也。既滿既盈，又随年俱耗，示人宜守
此天癸也。

容成曰：男八八之後猶存，女七七之後仍在，似乎天癸之未盡也。天師何以七七、八八之後
不再言之歟？

岐伯曰：予淪常數耳，常之數可定，變之數不可定也。予所以論常不論變耳。

陳遠公曰：人生以天癸爲主，有則生，無則死也。常變之說，惜此天癸也。二七、二八之論，
亦可言而言之，非不可言而不言也。

== 骨陰篇

鳥師問于岐伯曰：嬰兒初生，無膝蓋骨，何也？

岐伯曰：嬰兒初生，不止無膝蓋骨也，囟骨、耳後完骨皆無之。

鳥師曰：何故也？

岐伯曰：陰氣不足也。陰氣者，真陰之氣也。嬰兒純陽無陰，食母乳而陰乃生，陰生而囟骨，
耳後完骨、膝蓋骨生矣。生則兒夀，不生則天。

鳥師曰：其不生何也？

岐伯曰：三骨屬陰，得陰則生，然亦必陽旺而長也。嬰兒陽氣不足，食母乳而三骨不生，其
先天之陽氣虧也。陽氣先漓，先天已居于缺陷，食母之乳補後天而無余，此三骨之所以不生
也。三骨不生又焉能延齡乎！

鳥師曰：三骨缺一，亦能生乎？

岐伯曰：缺一則不全乎其人矣。

鳥師曰：請悉言之。

岐伯曰：囟門不合則腦髓空也；完骨不長則腎宮虛也；膝蓋不生則雙足軟也。腦髓空則風易
入矣；腎宮虛則聽失聰矣；雙足軟則颠仆多矣。

鳥師曰：吾見三骨不全亦有延齡者，又何故歟？

岐伯曰：三者之中，惟耳無完骨者亦有延齡，然而疾病不能無也。若囟門不合、膝蓋不生，
吾未見有生者。蓋孤陽無陰也。

陳遠公曰：孤陽無陰，人則不生，則陰爲陽之天也。無陰者，無陽也。陽生于陰之中，陰長
于陽之外，有三骨者，得陰陽之全也。

（學者于此段不必盡信，得其理，忘其詞，斯爲善學。）

= 卷二

== 媾精受妊篇

雷公問曰：男女媾精而受妊者，何也？

岐伯曰：腎爲作強之官，故受妊而生人也。

雷公曰：作強而何以生人也？

岐伯曰：生人者，即腎之技巧也。

雷公曰：技巧屬腎之水乎，火乎？

岐伯曰：水火無技巧也。

雷公曰：離水火又何以出技巧乎？

岐伯曰：技巧成于水火之氣也。

雷公曰：同是水火之氣，何生人有男女之别乎？

岐伯曰：水火氣弱則生女，水火氣強則生男。

雷公曰：古云：女先洩精則成男，男先洩精則成女。

今曰：水火氣弱則生女，水火氣強則生男。何也？

岐伯曰：男女俱有水火之氣也，氣同至則技巧出焉，一有先後不成胎矣。男洩精，女洩氣，
女子洩精則氣脫矣，男子洩氣則精脫矣，烏能成胎？！

雷公曰：女不洩精，男不洩氣，何以受妊乎？

岐伯曰：女氣中有精，男精中有氣，女洩氣而交男子之精，男洩精而合女子之氣，此技巧之
所以出也。

雷公曰：所生男女，有強有弱，自分于父母之氣矣。但有清濁夀夭之異，何也？

岐伯曰：氣清則清，氣濁則濁，氣長則夀，氣促則夭。皆本子父母之氣也。

雷公曰：生育本于腎中之氣，余已知之矣。但此氣也，豫于五臟七腑之氣乎？

岐伯曰：五臟七腑之氣，一經不至皆不成胎。

雷公曰：媾精者，動腎中之氣也。與五臟七腑何豫乎？

岐伯曰：腎藏精，亦藏氣。藏精者，藏五臟七腑之精也。藏氣者，藏五臟七腑之氣也。藏則
俱藏，洩則俱洩。

雷公曰：洩氣者，亦洩血乎？

岐伯曰：精即血也。氣無形？ 血有形，無形化有形，有形不能化無形也。

雷公曰：精非有形乎？

岐伯曰：精雖有形，而精中之氣正無形也。無形隱于有形，故能靜能動。動則化耳，化則技
巧出矣。

雷公曰：微哉言乎，請傳之奕祀，以彰化育焉。

陳士铎曰：男女不媾精，斷不成胎。胎成于水火之氣，此氣即男女之氣也。氣藏于精中，精
雖有形而實無形也。形非氣乎，故成胎即成氣之謂。

（此段最要緊處爲有形不能化無形，故有形之精欲化爲無形之炁，不亦惑乎？學南派栽接之
法，于此段正宜反復閱讀）

== 社生篇

少師問曰：人生而白頭，何也？

岐伯曰：社日生人，皮毛皆、白，非止鬓發之白也。

少師曰：何故乎？

岐伯曰：社日者，金日也。皮毛須鬓皆白者，得金之氣也。

少師曰：社日非金也，天師謂之金日，此余之未明也。

岐伯曰：社本土也，氣屬金，社日生人犯金之氣。金氣者，殺氣也。

少師曰：人犯殺氣，宜天矣，何又長年乎？

岐伯曰：金中有土，土乃生氣也。人肺屬金，皮毛亦屬金，金之殺氣得土則生，逢金則鬭。
社之金氣伐人皮毛，不入人臟腑，故得長年耳。

少師曰：社日生人皮毛鬓發不盡白者，又何故歟？

岐伯曰：生時不同也。

少師曰：何時乎？

岐伯曰：非己午時，必辰戌丑未時也。

少師曰：己午火也，火能制金之氣，宜矣。辰戌丑未土也，不助金之氣乎？

岐伯曰：社本土也，喜生惡洩，得土則生，生則不克矣。

少師曰：同是日也，何社日之兇如是乎？

岐伯曰：歲月日時俱有神司之，社日之神與人最親，其性最喜潔也，生産則穢矣。兩氣相感，
兒身受之，非其煞之暴也。

少師曰：人生有記，赤如朱，青如靛，黑如鍋，白如雪，終身不散，何也？豈亦社日之故乎？
岐伯曰：父母交媾，偶犯遊神，爲神所指，誌父母之’過也。

少師曰：色不同者，何歟？

岐伯曰：随神之氣異也。

少師曰：記無黃色者，何也？

岐伯曰：黃乃正色，人犯正神，不相校也，故亦不相指，不相指，故罔所記耳。

陳遠公曰：社日生人，說來有源有委，非孟浪成文者可比。

== 天厭火衰篇

容成問曰：世有天生男子音聲如女子，外勢如嬰兒，此何故歟？

岐伯曰：天厭之也。

容成曰：天何以厭之乎？

岐伯曰：天地有缺陷，安得人盡皆全乎？

容成曰：天未嘗厭人，奈何以天厭名之。

岐伯曰：天不厭而人必厭也，天人一道，人厭即天厭矣。

容成曰：人何不幸成天厭也了岐伯曰：父母之咎也。人道交感，先火動而後水濟之，火盛者
生子必強，火衰者生子必弱，水盛者生子必肥，水衰者生子必瘦。天厭之人，乃先天之火微
也。

容成曰：水火衰盛分強弱肥瘦，宜也，不宜外陽之細小。

岐伯曰：腎中之火，先天之火，無形之火也。腎中之水，先天之水，無形之水也。火得水而
生，水得火而長，言腎内之陰陽也。水長火，則水爲火之母；火生水，則火爲水之母也。人
得水火之氣以生身，則水火即人之父母也。天下有形不能生無形也，無形實生有形。外陽之
生，實内陽之長也。内陽旺而外陽必伸，内陽旺者得火氣之全也。内陽衰矣，外陽亦何得壯
大哉？

容成曰：火既不全，何以生身乎？

岐伯曰：孤陰不生，孤陽不長。天厭之人，但火不全耳，未嘗無陰陽也；偏于火者，陽有余
而陰不足，偏于水者，陰有余而陽不足也。陽既不足，即不能生厥陰之宗筋，此外陽之所以
屈而不伸也，毋論剛大矣。

容成曰：善。

陳遠公曰：外陽之大小，視水火之偏全，不視陰陽之有無耳。說來可聽。

== 經脈相行篇

雷公問曰：帝問脈行之逆順若何，余無以奏也。願天師明教以聞。

岐伯曰：十二經脈有自上行下者，有自下行上者，各不同也。

雷公曰：請悉言之。

岐伯曰：手之三陰從臟走手，手之三陽從手走頭，足之三陽從頭走足，足之三陰從足走腹，
此上下相行之數也。

雷公曰：尚未明也。

岐伯曰：手之三陰：太陰肺，少陰心，厥陰包絡也。手太陰從中府走大指之少商，手少陰從
極泉走小指之少衝，手厥陰從天池走中指之中衝。皆從臟走手也。

手之三陽：陽明大腸，太陽小腸，少陽三焦也。手陽明從次指商陽走頭之迎香，手太陰從小
指少澤走頭之聽宮，手少陽從四指關衝走頭之絲竹空，皆從手走頭也。

足之三陽：太陽膀胱，陽明胃，少陽膽也。足太陽從頭睛明走足小指之至陰，足陽明從頭頭
維走足次指之厲兌，足少陽從頭前關走四指之竅陰，皆從頭走足也。

足之三陰；太陰脾，少陰腎，厥陰肝也。足太陰從足大指内側隱白走腹之大包，足少陰從足
心湧泉走腹之俞府，足厥陰從足大指外側大敦走腹之期門，皆從足走腹也。

雷公曰：逆順若何？

岐伯曰：手之陰經，走手爲順，走臟爲逆也；手之陽經，走頭爲順，走手爲逆也；足之陰經，
走腹爲順，走足爲逆也；足之陽經，走足爲順，走頭爲逆也。

雷公曰：足之三陰，皆走于腹，獨少陰之脈下行，何也？豈少陰經易逆難順乎？

岐伯曰：不然，天衝脈者，五藏六腑之海也。五藏六腑皆禀焉。其上者，出于颃颡，滲諸陽，
灌諸精，下注少陰之大絡，出于氣衝，循陰陽内廉入胭中，伏行（骨行）骨内，下至内踝之
後，屬而别其下者，并由少陰經滲三陰，其在前者，伏行出跗屬下，循跗入大指間，滲諸絡
而溫肌肉，故别絡邪結則跗上脈不動，不動則厥，厥則足寒矣。此足少陰之脈少異于三陰而
走腹則一也。

雷公曰：其少異于三陰者爲何？

岐伯曰：少陰腎經中藏水火，不可不曲折以行，其脈不若肝脾之可直行于腹也。

雷公曰：其走腹則一者何？

岐伯曰：腎之性喜逆行，故由下而上，蓋以逆爲順也。

雷公曰；逆行宜病矣。

岐伯曰：逆而順故不病，若順走是違其性矣，反生病也。

雷公曰：當盡奏之，

岐伯曰：帝問何以明之？

公奏曰：以言導之，切而驗之，其髁必動。乃可以驗逆順之行也。

雷公曰：謹奉教以聞。

陳遠公曰：十二經脈有走手、走足、走頭、走腹之異，各講得鑿鑿。其講順逆不同處，何人
敢措一辭。

== 經脈終始篇

雷公問于岐伯曰：十二經之脈既有終始，《靈》《素》詳言之。而走頭、走腹、走足、走手
之義，尚未明也，願畢其辭。

岐伯曰：手三陽從手走頭，足三陽從頭走足，乃高之接下也。足三陰從足走腹，手三陰從腹
走手，乃卑之趨上也。陰陽無間，故上下相迎，高卑相迓，與晝夜循環同流而不定耳。夫陰
陽者，人身’之夫婦也；氣血者，人身之陰陽也。夫倡則婦随，氣行則血赴，氣主煦之，血
主濡之。乾作天門，大腸司其事也。巽作地戶，膽持其權也。泰居艮，小腸之昌也。否居坤，
胃之殃也。

雷公曰；善，請言順逆之别。

岐伯曰：足三陰自足走腹，順也；自腹走足，逆也。足三陽自頭走足，順也；自足走頭，逆
也。手三陰自藏走手，順也；自手走藏，逆也。手三陽白手走頭，順也；自頭走手，逆也。
夫足之三陰從足走腹，惟足少陰腎脈繞而下行，與肝脾直行者，以衝脈與之并行也，是以逆
爲順也。

陳遠公曰：十二經有頭腹手足之殊，有順中之逆，有逆中之順，說得更爲明白。

== 經氣本标篇

雷公問于岐伯曰：十二經氣有标本乎？

岐伯曰：有之。

雷公曰：請言标本之所在。

岐伯曰：足太陽之本在跟以上五寸中，标在兩絡命門。足少陽之本在竅陰之間，标在窗籠之
前。足少陰之本在内踝下三寸中，标在背腧。足厥陰之奉在行間上五寸所，标在背腧。足陽
明之本在厲兌，标在人迎，頰挾颃颡。足太陰之本在中封前上四寸中，标在舌本乎。太陽之
本在外踝之後，标在命門之上一寸。手少陽之本在小指次指之間上二寸，标在耳後上角下外
眦。手陽明之本在肘骨中上至别陽，标在顔下合鉗上。手太陰之本在寸口中，标在腋内動脈。
手少陰之本在銳骨之端，标在背腧。手心主之本在掌後兩筋之間二寸中，标在腋下三寸。此
标本之所在也。

雷公曰：标本皆可刺乎？

岐伯曰：氣之标本皆不可刺也。

雷公曰；其不可剌，何也？

岐伯曰；氣各有衝，衝不可刺也，

雷公曰：請言氣衝。

岐伯曰：胃氣有衝，腹氣有衝，頭氣有衝，胫氣有衝，皆不可剌也。

雷公曰：頭之衝何所乎？

岐伯曰：頭之衝，腦也。

雷公曰：胸之衝何所乎？

岐伯曰：胸之衝，膺與背腧也。喻亦不可剌也。

雷公曰：腹之衝何所乎？

岐伯曰：腹之衝，背腧與衝脈及左右之動脈也。

雷公曰：胫之衝何所乎？

岐伯曰：胫之衝，即臍之氣街及承山踝上以下。此皆不可刺也。

雷公曰：不可刺止此乎？

岐伯曰：大氣之摶而不行者，積于胸中，藏于氣海，出于肺，循咽喉，呼吸而出入也。是氣
海猶氣街也，應天地之大數，出三入一，皆不可剌也。

陳遠公曰：十二經氣各有标本，各不可剌。不可刺者，以衝脈之不可剌也。不知衝脈即不知
刺法也。

== 臟腑闡微篇

雷公問于岐伯曰：臟止五乎？腑止六乎？

岐伯曰：臟六腑七也。

雷公曰：臟六何以名五也？

岐伯曰：心肝脾肺腎五行之正也，故名五臟。胞胎非五行之正也，雖臟不以臟名之。

雷公曰：胞胎何以非五臟之正也？

岐伯曰：心火也，肝木也，脾土也，肺金也，腎水也，一臟各屬一行。胞胎處水火之歧；非
正也，故不可稱六臟也。

雷公曰：腎中有火亦水火之歧也，何腎稱臟乎？

岐伯曰：腎中之火先天火也，居兩腎中而腎專司水也。胞胎上繫心，下連腎，往來心腎，接
續于水火之際，可名爲火，亦可名爲水，非水火之正也。

雷公曰：然則胞胎何以爲臟乎？

岐伯曰：胞胎處水火之兩歧，心腎之交，非胞胎之繫不能通達上下，寧獨婦人有之，男子未
嘗無也。吾因其兩歧，置于五臟之外，非胞胎之不爲臟也。

雷公曰：男女各有之，亦有異乎？

岐伯曰：繫同而口異也。男女無此繫，則水火不交，受病同也。女繫無口，則不能受妊，是
胞胎者，生生之機，屬陰而藏于陽，非臟而何。

雷公曰：胞胎之口又何以異？

岐伯曰：胞胎之繫，上出于心之膜膈，下連兩腎，此男女之同也。惟女下大而上細，上無口
而下有口，故能納精以受妊。

雷公曰：腑七而名六何也？

岐伯曰：大小腸、膀胱、膽、胃、三焦、包絡，此七腑也。遺包絡不稱腑者，尊帝耳。

雷公曰；包絡可遺乎？

岐伯曰：不可遺也。包絡爲脾胃之母，土非火不生。五臟六腑之氣鹹仰于心君，心火無爲，
必藉包絡有爲，往來宣布胃氣，能入脾氣，能出各臟腑之氣，始能變化也。

雷公曰：包絡既爲一腑，奈何尊帝遺之。尊心爲君火，稱包絡爲相火，可乎？請登之《外經》
鹹以爲則。

陳遠公曰：臟六而言五者，言臟之正也。腑七而言六者，言腑之偏也。舉五而略六，非不知
胞胎也；舉六而略七，非不知包絡也。有雷公之間，而胞胎包絡昭于古今矣。

== 考訂經脈篇

雷公問于岐伯曰：十二經脈天師詳之，而所以往來相通之故，尚來盡也。幸宣明奧義，傳諸奕祀可乎？

岐伯曰：可，肺屬手太陰，太陰者，月之象也，月屬金，肺亦屬金。肺之脈走于手，故曰手
太陰也。起于中焦胃脘之上，胃屬土，土能生金，是胃乃肺之母也。下絡大腸者，以大腸亦
屬金，爲胃之庶于，而肺爲大腸之兄，兄能包弟，足以網羅之也。絡即網羅包舉之義。循于
胃口者，以胃爲肺之母，自必遊熙于母家，省受胃土之氣也。肺脈又上于膈，胃之氣多，必
分氣以給其子，肺得胃母之氣，上歸肺宮，必由膈而升肺。受胃之氣肺自成家，于是由中焦
而脈乃行，橫出腋下，畏心而不敢犯也。然而肺之繫實通于心，以心爲肺之君，而肺乃臣也，
臣必朝于君，此述職之路也。下循臑内，行少陰心主之前者，又谒相之門也。心主即心包絡，
爲心君之相，包絡代君以行事。心克肺金，必借心主之氣以相刑。呼吸相通，全在此繫之相
聯也。肺禀天玉之尊，必奉宰輔之令，所以行于少陰心主之前而不敢緩也。自此而下，乾肘
中乃走于臂，由臂而走于寸口魚際，皆肺脈相通之道。循魚際出大指之端，爲肺脈之盡。經
脈盡，復行，從腕後直出次指内廉，乃旁出之脈也。

雷公曰：脾經若何了

岐伯曰：脾乃土臟，其性濕，以足太陰名之。太陰之月，夜照于土，月乃陰象，脾屬土，得
月之陰氣，故以太陰名之。其脈起于足之大指端，故又曰足太陰也。脾脈既起于足下，下必
升上，由足大指内側肉際，過橫骨後，上内踝前廉，上踹内，循胫骨後，交出厥陰之前，乃
入肝經之路也。夫肝木克脾，宜爲脾之所畏，何故脈反通于肝，不知肝雖克土，而木亦能成
土，土無木氣之通，則土少發生之氣，所以畏肝而又未嘗不喜肝也。交出足厥陰之前，圖合
于肝木耳。上膝肢内前廉入腹者，歸于睥經之本臟也。蓋腹，脾之正宮，睥厲土居于中州，
中州爲天下之腹，脾乃人一身之腹也。脾與胃爲表裏，脾内而胃外，脾爲胃所包，故絡于胃。
脾得胃氣則脾之氣始能上升，故脈亦随之上鬲，趨喉嚨而至舌本，以舌本爲心之苗，而脾爲
心之子，子母之氣自相通而不隔也。然而舌爲心之外竅，非心之内廷也，脾之脈雖至于舌，
而終未至于心，故其支又行，借胃之氣從胃中中脘之外上鬲，而脈通于膻中之分，上交于手
少陰心經，子親母之象也。

雷公曰：心經若何？

岐伯曰：心爲火臟，以手少陰名之者，蓋心火乃後天也。後天者，有形之火也。星應熒惑，
雖屬火而實屬陰，且脈走于手，故以手少陰名之。他臟腑之脈皆起于手足，心脈獨起于心，
不與眾脈同者，以心爲君主，總攬權綱，不寄其任于四末也。心之繫，五臟七腑無不相通，
尤通者小腸也。小腸爲心之表，而心實絡于小腸，下通任脈，故任脈即借小腸之氣以上通于
心，爲朝君之象也。心之繫又上與肺相通，挾咽喉而入于目，以發其文明之彩也。復從心繫
上肺，下出腋下，循臑内後廉，行手厥陰經心主之後，下肘，循臂至小指之内出其端，此心
脈繫之直行也。又由肺曲折而後，并脊直下，與腎相貫串，當命門之中，此心腎既濟之路也。
夫心爲火臟，懼畏水克，何故繫通于腎，使腎有路以相犯乎？不知心火與命門之火原不可一
日不相通也，心得命門之火則心火有根，心非腎水之滋則心火不旺。蓋心火必得腎中水火以
相養，是以克爲生也。既有腎火腎水之相生，而後心之繫各通臟腑，無擀格之憂矣。由是而
左通于肝，肝本屬木，爲生心之母也。心火雖生于命門先天之火，而非後天肝木培之則先天
之火氣亦不旺，故心之繫通于肝者，亦欲得肝木相生之氣也。肝氣既通，而膽在肝之旁，通
肝即通于膽，又勢之甚便者，況膽又爲心之父，同本之親尤無阻隔也。由是而通于脾，脾乃
心之子也，雖脾土不藉心火之生，然胃爲心之愛子，胃土非心火不生，心既生胃，生胃必生
脾，此脾胃之繫所以相接而無間也。由是而通于肺，火性炎上，而肺葉當之，得母有傷，然
而頑金非火不柔，克中亦有生之象，倘肺金無火則金寒水冷，胃與膀胱之化源絕矣，何以溫
腎而傳化于大腸乎。由是而通于心主，心主即膻中包絡也，爲心君之相臣，奉心君以司化，
其出入之經，較五臟六腑更近，真有心喜亦喜，心憂亦憂之象，呼吸相通，代君司化以使令
夫三焦，俾上中下之氣無不畢達，實心之繫通之也。

雷公曰：腎經若何？

岐伯曰：腎屬水，少陰正水之象。海水者，少陰水也，随月爲盈虛，而腎應之。名之爲足少
陰者，脈起于足少陰之下也，由足心而上，循内踝之後，别入跟中，上膊出腘上股貫脊，乃
河車之路，即任督之路也。然俱屬于腎，有腎水而河車之路通，無腎水而河車之路塞，有腎
水而督脈之路行，無腎水而督脈之路斷，是二經之相通相行，全責于腎，故河車之路、督脈
之路，即腎經之路也。由是而行于肝，母入于子捨之義也。由是而行于脾，水行于地中之義
也。過肝脾二經而絡于膀胱者，以腎爲膀胱之裏，而膀胱爲腎之表，膀胱得腎氣而始化，正
同此路之相通，氣得以往來之耳。其絡于膀胱也，貫脊會督而還出于臍之前，通任脈始得達
于膀胱，雖氣化可至，實有經可通而通之也。其直行者，又由肝以入肺，子歸母之家也。由
肺而上循喉嚨，挾舌本而終，是欲朝君先通于喉舌也。夫腎與心雖若相克而實相生，故其繫
别出而繞于心，又未敢遽朝于心君，注胸之膻中包絡而後，腎經之精上奉，化爲心之液矣，
此君王下取于民之義，亦草野上貢于國之誼也。各臟止有一而腎有二者，兩儀之象也。兩儀
者，日月也。月主陰，日主陽，似腎乃水臟宜應月不宜應日，然而月之中未嘗無陽之氣，日
之中未嘗無陰之氣，腎配日月正以其中之有陰陽也。陰藏于陽之中，陽隱于陰之内，疊相爲
用，不啻日月之照臨也。蓋五臟七腑各有水火，獨腎臟之水火處于無形，乃先天之水火，非
若各臟腑之水火俱屬後天也。夫同是水火，腎獨屬之先天，實有主以存乎兩腎之間也。主者，
命門也。命門爲小心，若太極之象能生先天之水火，因以生後天之水火也。于是裁成夫五臟
七腑，各安于諸宮，享其奠定之福，化生于無窮耳。

雷公曰：肝經若何？

岐伯曰：肝屬足厥陰。厥陰者，逆陰也，上應雷火。脈起足大指叢毛之際，故以足厥陰名之。
雷火皆從地起，騰于天之上，其性急，不可制抑，肝之性亦急，乃陰經中之最逆者，少拂其
意，則厥逆而不可止。循跗上上踝，交出太陰脾土之後，上胭内廉，循腹入陰毛中，過陰器，
以抵于小腹，雖趨肝之路，亦趨脾之路也。既趨于脾，必趨于胃矣。肝之繫既通于脾胃，凡
有所逆，必先犯于脾胃矣，亦其途路之熟也。雖然，肝之繫通于脾胃，而肝之氣必歸于本宮，
故其繫又走于肝葉之中，肝葉之旁有膽附焉，膽爲肝之兄，肝爲膽之弟，膽不絡肝而肝反絡
膽者，弟強于兄之義也。上貫膈者，趨心之路也。肝性急，宜直走于心之宮矣，乃不直走于
心，反走膜鬲，布于脅肋之間者，母慈之義也。慈母憐子必爲子多方曲折，以厚其藏，脅肋
正心宮之倉庫也，然而其性正急，不能久安于脅肋之間，循喉嚨之後，上入颃颡，連于目繫，
上出額間而會督脈于巅項，乃木火升上之路也。其支者，從目繫下頰環唇，欲随口舌之竅以
洩肝木之郁火也。其支者，又從肝别貫膈，上注肺中，畏肺金之克木，通此經爲偵探之途也。

雷公曰：五臟已知其旨矣。請詳言七腑。

岐伯曰：胃經亦稱陽明者，以其脈接大腸手陽明之脈，由鼻額而下走于足也。然而胃經屬陽
明者，又非同大腸之謂。胃乃多氣多血之腑，實有日月并明之象，乃純陽之腑，主受而又主
化也。陽主上升，由額而遊行于齒口唇吻，循頤頰耳前而會于額顱，以顯其陽之無不到也。
其支别者，從頤後下人迎，循喉嚨入缺盆，行足少陰之外，下隔通腎與心包之氣。蓋胃爲腎
之關，又爲心包之用，得氣于二經，胃始能蒸腐水谷以化精微也。胃既得二經之氣，必歸于
胃中，故仍屬胃也。胃之旁絡于脾，胃爲脾之夫，脾爲胃之婦，脾聽胃使，以行其運化者也。
其直行者，從缺盆下乳内廉，挾臍而入氣街。氣街者，氣衝之穴也，乃生氣之源，探源而後，
氣充于乳房，始能散布各經絡也。其支者，起于胃口，循腹過足少陰腎經之外，本經之裏下
至氣街而合，仍是取氣于腎，以助其生氣之源也。由是而胃既得氣之本，乃可下行，以達于
足。從氣街而下髀關，抵伏兔，下膝膑，循胫下跗，入中指之内庭而終者，皆胃下達之路也。
其支者，從膝之下廉三寸，别入中指之外間，復是旁行之路，正見其多氣多血，無往不周也。
其支者，别跗上，入大指問，出足厥陰，交于足太陰，避肝木之克，近脾土之氣也。

雷公曰：請言三焦之經。

岐伯曰；三焦屬之手少陽者，以三焦無形，得膽木少陽之氣，以生其火而脈起于手之小指次
指之端，故以手少陽名之。循手腕出臂貫肘，循層之外，行手太陽之裏，手陽明之外，火氣
欲通于大小腸也。上肩循臂臑，交出足少陽之後，正倚附于膽木以取其木中之火也。下缺盆，
由足陽明之外面交會于膻中；之上焦，散布其氣而絡繞于心包絡；之中焦，又下膈入絡膀胱
以約下焦。若胃若心包絡若膀胱，皆三焦之氣往？來于上中下之際，故不分屬于三經而仍專
屬于三焦也。然而三焦之氣雖往來于上中下之際，使無根以爲主，則氣亦時聚時散，不可久
矣。讵知三焦雖得膽木之氣以生，而非命門之火則不長。三焦有命門以爲根而後，布氣于胃，
則胃始有運用之機；布氣于心包絡，則心包絡始有運行之權；布氣于膀胱，則膀胱始有運化
之柄也。其支者，從膻中而上，出缺盆之外，土項繫耳後，直上出耳上角至颛，無非随腎之
火氣而上行也。其支者，又從耳後入耳中，出耳前，過客主人之穴，交頰至目銳眦，亦火性
上炎，随心包之氣上行。然目銳眦實繫膽經之穴，仍欲依附木氣以生火氣耳。

雷公曰：請言心主之經。

岐伯曰：心主之經即包絡之府也，又名膻中。屬手厥陰者，以其代君出治，爲心君之相臣，
臣乃陰象，故屬陰。然奉君令以出治，有不敢少安于頃刻，故其性又急，與肝木之性正相同，
亦以厥陰名之，因其難順而易逆也。夫心之脈出于心之本宮，心包絡之脈出于胸中，包絡在
心之外，正在胸之中，是脈出于胸中者，正其脈屬于包絡之本宮也。各臟腑脈出于外，心與
包絡脈出于中，是二經較各臟腑最尊也。夫腎繫交于心包絡，實與腎相接，蓋心主之氣與腎
宮命門之氣同氣相合，故相親而不相離也。由是下于膈，歷絡三焦，以三焦之腑氣與命門心
主之氣彼此實未嘗異，所以籠絡而相合爲一，有表裏之名，實無表裏也。其支者，循胸中出
脅抵腋，循屬内行于太陰肺脾少陰心腎之中，取肺腎之氣以生心液也。入脈下臂，入掌内，
又循中指以出其端。其支者，又由掌中循無名指以出其端，與少陽三焦之脈相交會，正顯其
同氣相親，表裏如一也。夫心主與三焦兩經也，必統言其相合者，蓋三焦無形。借心主之氣
相通于上中下之間，故離心主無以見三焦之用，所以必合而言之也。

雷公曰：請言膽經。

岐伯曰：膽經屬足少陽者，以膽之脈得春木初陽之氣，而又下趨于足，故以足少陽名之。然
膽之脈雖趨于足，而實起目之銳眦，接手少陽三焦之經也。由目銳眦上抵頭角，下耳循頸，
行手少陽之脈前，至肩上，交出手少陽之後，以入缺盆之外，無非助三焦之火氣也。其支者，
從耳後入耳中，出走耳前，至目銳眦之後，雖旁出其支，實亦仍顧三焦之脈也。其支者，别
自目外而下大迎，合手少陽三焦，抵于䪼，下頸，復合缺盆，以下胸中，貫膜、膈、心包絡，
以絡于肝，蓋心包絡乃膽之子，而肝乃膽之弟，故相親而相近也。第膽雖肝之兄，而附于肝，
實爲肝之表，而屬于膽。肝膽兄弟之分，即表裏之别也。膽分肝之氣，則膽之汁始旺，膽之
氣始張，而後可以分氣于兩脅，出氣街，統毛際而橫入髀厭之中也。其直者，從缺盆下腋，
循胸過季脅，與前之入髀厭者相合，乃下循髀外，行太陽陽明之間，欲竊水土之氣以自養也。
出膝外廉，下肋骨以直抵絕骨之端，下出外踝，循跗上入小指次指之間，乃其直行之路也。
其支者，又别跗上，入大指歧骨内出其端，還貫入爪甲，出三毛，以交于足厥陰之脈，親肝
木之氣以自旺，蓋陽得陰而生也。

雷公曰：請言膀胱之經。

岐伯曰：膀胱之經屬足太陽者，蓋太陽爲巨陽，上應于日，膀胱得日之火氣，下走于足，猶
太陽火光普照于地也。其脈起目内眦，交手太陽小腸之經，受其火氣也。上額交巅，至耳上
角，皆火性之炎上也。其直行者，從巅入絡腦，還出别下項，循肩膊内挾脊兩旁下行，抵于
腰，入循膂絡腎，蓋膀胱爲腎之表，故繫連于腎，通腎中命門之氣，取其氣以歸膀胱之中，
始能氣化而出小便也。雖氣出于腎經，而其繫要不可不屬之膀胱也。其支者，從腰中下挾脊
以貫臀，入胭中而止，亦借腎氣下達之也。其支者，從膊内别行下貫脾膂，下歷尻臀，化小
便通陰之器而下出也。過髀樞，循髀外下合胭中，下貫于兩踹内，出外踝之後，循京骨，至
小指外側，交于足少陰之腎經，亦取腎之氣可由下面升，以上化其水也。

雷公曰：請言小腸之經。

岐伯曰：小腸之經屬手太陽者，以脈起于手之小指，又得心火之氣而名之也。夫心火屬少陰，
得心火之氣，宜稱陰矣。然而心火居于内者爲陰，發于外者爲陽，小腸爲心之表也，故稱陽
而不稱陰，且其性原眉陽，得太陽之日氣，故亦以太陽名之。其脈上腕出踝，循臂出肘，循
履行手陽明少陽之外，與太陽膽氣相通，欲得金氣自寒，欲得木氣自生也。交肩上，入缺盆，
循肩向腋下行，當膻中而絡于心，合君相二火之氣也。循咽下膈以抵于胃，雖火能生胃，而
小腸主出不主生，何以抵胃，蓋受胃之氣，運化精微而生糟粕，猶之生胃也。故接胃之氣，
下行任脈之外，以自歸于小腸之正宮，非小腸之屬而誰屬乎。其支者，從缺盆循頸頰上至目
銳眦，入于耳中，此亦火性炎上，欲趨竅而出也。其支者，别循頰上䪼，抵鼻至目内眦，斜
絡于顴，以交足太陽膀胱之經，蓋陽以趨陽之應也。

雷公曰：請言大腸之經。

岐伯曰：大腸之經名爲手陽明者，以大腸職司傳化，有顯明昭著之意，陽之象也。夫大腸屬
金，宜爲陰象，不屬陰而屬陽者，因其主出而不主藏也。起于手大指次指之端，故亦以手名
之。循指而入于臂，入肘上臑，上肩下入缺盆而絡于肺，以肺之氣能包舉大腸，而大腸之繫
亦上絡于肺也。大腸得肺氣而易于傳化，故其氣不能久留于膈中，而繫亦下膈，直趨大腸以
安其傳化之職。夫大腸之能開能阖，腎主之，是大腸之氣化宜通于腎，何以大腸之繫絕，不
與腎會乎。不知肺金之氣即腎中水火之氣也，腎之氣必來于肺中，而肺中之氣既降于大腸之
内，則腎之氣安有不入于大腸之中者乎。不必更有繫通腎，而後得其水火之氣，始能傳化而
開合之也。其支者，從缺盆上頸貫頰，入下齒縫中，還出夾兩口吻，交于唇中之左右，上挾
鼻孔，正顯其得肺腎之氣，随肺腎之脈而上升之征也。

陳遠公曰：十二經脈各說得詳盡，不必逐段論之。

== 包絡配腑篇

天老問于岐伯曰：天有六氣，化生地之五行，地有五行，化生人之五臟。有五臟之陰，即宜
有五腑之陽矣，何以臟止五，腑有七也？

岐伯曰：心包絡，腑也，性屬陰，故與臟氣相同，所以分配六腑也。

天老曰：心包絡既分配腑矣，是心包絡即臟也，何不名臟而必别之爲腑耶？

岐伯曰：心包絡，非臟也。

天老曰：非臟列于臟中，毋乃不可乎？

岐伯曰：臟稱五不稱六，是不以臟予包絡也。腑稱六，不稱七，是不以腑名包絡也，

天老曰：心包絡，非臟非腑何以與三焦相合乎？

岐伯曰：包絡與三焦爲表裏，二經皆有名無形，五臟有形與形相合，包絡無形，故與無形相
合也。

天老曰：三焦爲孤臟，既名爲臟，豈合于包絡乎？

岐伯曰：三焦雖亦稱臟，然孤而寡合，仍是腑非臟也，捨包絡之氣，實無可依，天然配合，
非勉強附會也。

天老曰：善。

雷公曰：肺合大腸，心合小腸，肝合膽，脾合胃，腎合膀胱，此天合也。三焦與心包絡相合，
恐非天合矣。

岐伯曰：包絡非臟而與三焦合者，包絡裏三焦表也。

雷公曰：三焦腑也，何分表裏乎？

岐伯曰：三焦之氣，本與腎親，親腎不合腎者，以腎有水氣也。故不合腎而合于包絡耳。雷
公曰：包絡之火氣出于腎，三焦取火于腎，不勝取火于包絡乎。岐伯曰：膀胱與腎爲表裏，
則腎之火氣必親膀胱而疏三焦矣。包絡得腎之火氣，自成其腑，代心宣化，雖腑猶臟也。包
絡無他腑之附，得三焦之依而更親，是以三焦樂爲表，包絡亦自安于裏，孤者不孤，自合者
永合也。

雷公曰：善。

應龍問曰：包絡腑也，三焦亦自成腑，何以爲包絡之使乎？

岐伯曰：包絡即膻中也，爲心膜鬲，近于心宮，遮護君主，其位最親，其權最重，故三焦奉
令不敢後也。

應龍曰：包絡代心宣化，宜各臟腑皆奉令矣，何獨使三焦乎了岐伯曰：各腑皆有表裏，故不
聽包絡之使，惟三焦無臟爲表裏，故包絡可以使之。

應龍曰：三焦何樂爲包絡使乎？

岐伯曰：包絡代心出治，腑與臟同，三焦聽使于包絡，猶聽使于心，故包絡爲裏，三焦爲表，
豈勉強附會哉。

應龍曰：善。

陳士铎曰：包絡之合三焦，非無因之合也。包絡之使三焦，因其合而使；之也，然合者，仍
合于心耳，非包絡之司爲合也。

= 卷三

== 膽腑命名篇

胡孔甲問于岐伯曰：大腸者，白腸也，小腸者，赤腸也，膽非腸，何謂青腸乎？

歧伯曰：膽貯青汁，有入無出，然非腸何能通而貯之乎，故亦以腸名之。青者，木之色，膽
屬木，其色青，故又名青腸也。

胡孔甲曰：十一臟取決于膽，是腑亦有臟名矣，何臟分五而腑分七也？

岐伯曰：十一臟取決于膽，乃省文耳，非腑可名臟也。

孔甲曰：膽既名爲臟，而十一臟取決之，固何所取之乎？

岐天師曰：膽司滲，凡十一臟之氣得膽氣滲之，則分清化濁，有奇功焉。

孔甲曰：膽有入無出，是滲主入而不主出也，何能化濁乎？

岐伯曰：清滲入則濁自化，濁自化而清亦化矣。

孔甲曰：清滲入而能化，是滲入而仍滲出矣。

岐伯曰：膽爲清淨之府。滲入者，清氣也，遇清氣之臟腑亦以清氣應之，應即滲之機矣，然
終非滲也。

孔甲曰：臟腑皆取決于膽，何臟腑受膽之滲乎？

岐伯曰：大小腸膀胱皆受之，而膀胱獨多焉，雖然膀胱分膽之滲，而膽之氣虛矣。膽虛則膽
得滲之禍矣，故膽旺則滲益，膽虛則滲損。

孔甲曰：膽滲何氣則受損乎？

岐伯曰：酒熱之氣，膽之所畏也，過多則滲失所司，膽受損矣，非毒結于腦則涕流于鼻也。

孔甲曰：何以治之？

岐伯曰：剌膽絡之穴，則病可已也。

孔甲曰：善。

陳士铎曰：膽主滲，十二臟皆取決于膽者，正決于滲也。膽不能滲又何取決乎。

== 任督死生篇

雷公問曰：十二經脈之外，有任督二脈，何略而不言也？

岐伯曰：二經之脈不可略也。以二經散見于各經，故言十二經脈而二經已統會于中矣。

雷公曰：試分言之。

岐伯曰：任脈行胸之前，督脈行背之後也。

任脈起于中極之下，以上毛際，循腹裏，上關元，至咽嚨上頤，循面入目眦，此任脈之經絡
也。

督脈起于少腹，以下骨中央，女子入繫廷孔，在溺孔之際，其絡循陰器合纂間，統纂後，即
前後二陰之間也，别繞臀至少陰，與巨陽中絡者合少陰，上股内後廉，貫脊屬腎與太陽。起
于目内眦，上額交巅上，入絡腦，至鼻柱，還出别下項，循肩膊挾脊抵腰中，入循膂絡腎。
其男子循莖下至纂，與女子等，其少腹直上者，貫臍中央，上貫心，入喉上頤環唇，上繫兩
目之下中央，此督脈之經絡也。

雖督脈止于龈交，任脈止于承漿，其實二脈同起于會陰。止于龈交者未嘗不過承漿，止于承
漿者未嘗不過龈交，行于前者亦行于後，行于後者亦行于前，循環周流彼此無間，故任督分
之爲二，合之仍一也。

夫會陰者，至陰之所也。任脈由陽行于陰，故脈名陰海。督脈由陰行于陽，故脈名陽海。非
龈交穴爲陽海，承漿穴爲陰海也。陰交陽而陰氣生，陽交陰而陽氣生，任督交而陰陽自長，
不如海之難量乎，故以海名之。

雷公曰：二經之脈絡予已知之矣。請問其受病何如？

岐伯曰：二經氣行則十二經之氣通，二經氣閉則十二經之氣塞，男則成疝，女則成瘕，非遺
溺即脊強也。

雷公曰：病止此乎？

岐伯曰：腎之氣必假道、于任督二經，氣閉則腎氣塞矣。女不受妊，男不射精，人道絕矣。
然則任督二經之脈絡，即人死生之道路也。

雷公曰：神哉論也。請載《外經》，以補《内經》未備。

陳士铎曰：任督之路，實人生死之途。說得精好入神。

== 陰陽二跷篇

司馬問曰：奇經八脈中有陰跷陽跷之脈，可得聞乎？

岐伯曰：《内經》言之矣。

司馬曰：《内經》言之，治病未驗或有未全歟。

岐伯曰：《内經》約言之，實未全也。

陰跷脈足少陰腎經之别脈也，起于然骨之照海穴，出内踝上，又直上之，循陰股以入于陰，
上循胸裏，入于缺盆，上出入迎之前，入于目下鸠，屬于目眦之睛明穴，合足太陽膀胱之陽
跷而上行，此陰跷之脈也。

陽跷脈足太陽膀胱之别脈也，亦起于然骨之下申脈穴，出外踝下，循仆參，郄于附陽，與足
少陽會于居髎，又與手陽明會于肩髃及巨骨，又與手太陽陽維會于臑俞，與手足陽明會于地
倉及巨髎，與任脈足陽明會于承泣，合足少陰腎經之陰跷下行，此陽跷之脈也。

然而跷脈之起止，陽始于膀胱而止于腎，陰始于腎而止于膀胱，此男子同然也，若女子微有
異。男之陰跷起于然骨，女之陰跷起于陰股；男之陽跷起于申脈，女之陽跷起于仆參。知同
而治同，知異而療異，則陽跷之病不至陰緩陽急，陰跷之病不至陽緩陰急，何不驗乎。

司馬公曰：今而後，陰陽二跷之脈昭然矣。

陳士铎曰：二跷之脈，分諸男女。《内經》微别，人宜知之，不可草草看過。

== 奇恆篇

奢龍問于岐伯曰：奇恆之腑，與五臟并主藏精，皆可名臟乎？

岐伯曰：然。

奢龍曰：腦髓骨脈膽女子胞，既謂奇恆之腑，不宜又名臟矣。

岐伯曰：腑謂臟者，以其能藏陰也。陰者，即腎中之真水也。真水者，腎精也。精中有氣，
而腦髓骨脈膽女子胞皆能藏之，故可名腑，亦可名臟也。

奢龍曰：脩真之士，何必留心于此乎？

岐伯曰：人欲長生，必知斯六義，而後可以養精氣，結聖胎者也。

奢龍曰：女子有胞以結胎，男子無胞何以結之？

岐伯曰：女孕男不妊，故胞屬之女子，而男子未嘗無胞也，男子有胞而後可以養胎息，故脩
真之士必知。斯六者至要者則胞與腦也，腦爲泥丸，即上丹田也；胞爲神室，即下丹田也。
骨藏髓，脈藏血，髓藏氣，腦藏精，氣血精髓盡升泥丸，下降于舌，由舌下華池，由華池下
廉泉玉英，通于膽，下貫神室。世人多欲，故血耗氣散，髓竭精亡也。苟知藏而不瀉，即返
還之道也。

奢龍曰：六者宜藏，何道而使之藏乎？

岐伯曰：廣成子有言，毋搖精，毋勞形，毋思慮營營，非不瀉之謂乎。

奢龍曰：命之矣。

陳士铎曰：腦、髓、骨、脈、膽、女子胞，非臟也，非臟而以臟名之，以其能藏也，能藏故
以臟名之，人可失諸藏乎。

== 小絡篇

應龍問于岐伯曰：膜原與肌腠有分乎？

岐伯曰：二者不同也。

應龍曰：請問不同？

岐伯曰：肌腠在膜原之外也。

應龍曰：肌腠有脈乎？

岐伯曰：肌腠膜原皆有脈也，其所以分者，正分于其脈耳。肌腠之脈，外連于膜原，膜原之
脈，内連于肌腠。

應龍曰：二脈乃表裏也，有病何以分之？

岐伯曰：外引小絡痛者，邪在肌腠也。内引小絡痛者，邪在膜原也。

應龍曰：小絡又在何所？

岐伯曰：小絡在膜原之間也。

陳士铎曰：小絡一篇，本無深文，備載諸此。以小絡異于膜原耳，知膜原之異，即知肌腠之
異也。

== 肺金篇

少師問曰：肺金也，脾胃土也，土宜生金，有時不能生金者謂何了

岐伯曰：脾胃土旺而肺金強，脾胃土衰而肺金弱，又何疑乎。然而脾胃之氣太旺，反非肺金
所喜者，由于土中火氣之過盛也。土爲肺金之母，火爲肺金之賊，生變爲克，烏乎宜乎。

少師曰：金畏火克，宜避火矣，何又親火乎？

岐伯曰：肺近火，則金氣之柔者必銷矣。然肺離火，則金氣之頑者必折矣。所貴微火以通熏
肺也。故土中無火，不能生肺金之氣。而土中多火，亦不能生肺金之氣也。所以烈火爲肺之
所畏，微火爲肺之所喜。

少師公曰：善。請問金木之生克？

岐伯曰：肺金制肝木之旺，理也。而肝中火盛，則金受火炎肺，失清肅之令矣。避火不暇，
敢制肝木乎了即木氣空虛，已不畏肺金之刑，況金受火制，則肺金之氣必衰，肝木之火癒旺，
勢必橫行無忌，侵伐脾胃之土，所謂欺子弱而淩母強也。肺之母家受敵，禦木賊之強橫，奚
能顧金子之困窮，肺失化源，益加弱矣。肺弱欲其下生腎水難矣，水無金生則水不能制火，
毋論上焦之火焚燒，而中焦之火亦随之更熾甚，且下焦之火亦挾水沸騰矣。

少師曰：何肺金之召火也？

岐伯曰：肺金，嬌臟也，位居各臟腑之上，火性上炎，不發則已，發則諸火應之。此肺金之
所以獨受厥害也。

少師曰：肺爲嬌臟，曷禁諸火之威逼乎，金破不鳴斷難免矣。何以自免于禍乎？

岐伯曰：仍賴腎子之水以救之。是以肺腎相親更倍于土金之相愛。以土生金，而金難生土。
肺生腎，而腎能生肺，晝夜之間，肺腎之氣實彼此往來兩相通，而兩相益也。

少師曰：金得水以解火，敬聞命矣。然金有時而不畏火者，何謂乎？

岐伯曰：此論其變也。

少師曰：請盡言之。

岐伯曰：火爍金者，烈火也。火氣自微何以爍。金非惟不畏火，且侮火矣。火難制金，則金
氣日旺。肺成頑金過剛而不可犯，于是肅殺之氣必來伐木。肝受金刑力難生火，火勢轉衰，
變爲寒火奚。足畏乎。然而火過寒無溫氣以生土，土又何以生金。久之火寒而金亦寒矣。

少師曰：善。請問金化爲水，而水不生木者，又何謂乎？

岐伯曰：水不生木，豈金反生木乎。水不生木者，金受火融之水也。真水生木而融化之，水
克木矣。

少師曰：善。

陳士铎曰：肺不燥不成頑金，肺過濕不成柔金，以肺中有火也。肺得火則金益，肺失火則金
損。故金中不可無火，亦不可有火也。水火不旺，金反得其宜也。總不可使金之過旺耳。

== 肝木篇

少師曰：肝屬木，木非水不養，故腎爲肝之母也。腎衰則木不旺矣，是肝木之虛，皆腎水之
涸也。然而肝木之虛，不全責腎水之衰者何故？

岐伯曰：此肝木自郁也。木喜疏洩，遇風寒之邪，拂抑之事，肝輒氣郁不舒。肝郁必下克脾
胃，制土有力，則木氣自傷，勢必求濟腎水，水生木而郁氣未解，反助克土之橫。土怒水助
轉來克水。肝不受腎之益，腎且得土之損，未有不受病者也。腎既病矣，自難滋肝木之枯，
肝無水養，其郁更甚。郁甚而克土癒力。脾胃受傷氣難轉輸，必求救于心火，心火因肝木之
郁全不顧心，心失化源，何能生脾胃之土乎。于是憐土予之受傷，不敢咎肝母之過，逆反嗔
肺金不制肝木，乃出其火而克肺，肺無土氣之生，復有心火之克則肺金難以自存。聽肝木之
逆，無能相制矣。

少師曰：木無金制宜木氣之舒矣，何以仍郁也？

岐伯曰：木性曲直，必得金制有成。今金弱木強，則肝寡于畏，任郁之性以自肆，土無可克
水，無可養火，無可助，于是木空受焚矣。此木無金制而癒郁也。所以治肝必解郁爲先，郁
解而肝氣自平。何至克土，土無木克則脾胃之氣自易升騰，自必忘克，腎水轉生肺金矣。肺
金得脾胃二土之氣，則金氣自旺，令行清肅。腎水無匱乏之憂，且金強制木，木無過旺肝氣
平矣。

少師曰：肝氣不平可以直折之乎？

岐伯曰：肝氣最惡者郁也。其次則惡不平，不平之極即郁之極也。故平肝尤尚解郁。

少師曰：其故何也？

岐伯曰：肝氣不平，肝中之火過旺也。肝火過旺，由肝木之塞也。外閉内焚，非爍土之氣即
耗心之血矣。夫火旺宜爲心之所喜，然溫火生心，烈火逼心，所以火盛之極，可暫用寒涼以
瀉。肝火郁之極，宜兼用舒洩以平肝也。

少師曰：善。

陳士铎曰：木不郁則不損，肝木之郁即逆之之謂也。人能解郁，則木得其平矣。何郁之有。

== 腎水篇

少師曰；請問腎水之義。

岐伯曰：腎屬水，先天真水也。水生于金，故肺金爲腎母。然而肺不能竟生腎水也，必得睥
土之氣熏蒸，肺始有生化之源，

少師曰：土克水者也，何以生水？

岐伯曰：土貪生金，全忘克水矣。

少師曰；金生水而水養于金，何也？

岐伯曰：腎水非肺金不生，肺金非腎水不潤。蓋肺居上焦，諸臟腑之火，鹹來相逼，苟非腎
水灌注，則肺金立化矣。所以二經子母最爲關切。無時不交相生，亦無時不交相養也。是以
補腎者必須益肺，補肺者必須潤腎，始既濟而成功也。

少師曰：腎得肺之生即得肺之損，又何以養各臟腑乎？

岐伯曰：腎交肺而肺益生腎，則腎有生化之源。山下出泉涓涓正不竭也。腎既優渥，乃分其
水以生肝。肝木之中本自藏火，有水則木且生心，無水則火且焚木，木得水之濟，則木能自
養矣。木養于水，木有和平之氣，自不克土。而脾胃得遂其升發之性，則心火何至躁動乎。
自然水不畏火之炎，乃上潤而濟心矣。少師曰：水潤心固是水火之既濟，但恐火炎而水不來
濟也。

岐伯曰：水不潤心，故木無水養也。木無水養肝必乾燥，火發木焚，爍盡脾胃之液，肺金救
土之不能，何暇生腎中之水。水涸而肝益加燥，腎無瀝以養肝，安得余波以灌心乎！肝木癒
橫，心火癒炎，腎水畏焚，因不上濟于心，此腎衰之故，非所謂腎旺之時也。

少師曰：腎衰不能濟心，獨心受其損乎？

岐伯曰：心無水養，則心君不安，乃遷其怒于肺金，遂移其。火以逼肺矣。肺金最畏火炎，
随移其熱于腎，而腎因水竭，水中之火正無所依，得心火之相會，翕然升木變出龍雷，由下
焦而騰中焦，由中焦而騰上焦，有不可止遏之機矣。是五臟七腑均受其害，寧獨心受損乎！

少師曰：何火禍之酷乎？

岐伯曰：非火多爲害，乃水少爲炎也。五臟有臟火，七腑有腑火，火到之所，同氣相親，故
其勢易旺，所異者，水以濟之也。而水止腎臟之獨有，且水中又有火也。水之不足，安敵火
之有余。此腎臟所以有補無瀉也。

少師曰；各臟腑皆取資于水，宜愛水而畏火矣。何以多助火以增焰乎？

岐伯曰：水少火多，一見火發，惟恐火之耗水，竟來顧水，誰知反害水乎。此禍生于愛，非
惡水而愛火也。

少師曰：火多水少，瀉南方之火，非即補北方之水乎？

岐伯曰：水火又相根也。無水則火烈，無火則水寒，火烈則陰虧也，水寒則陽消也。陰陽兩
平，必水火既濟矣。

少師曰：火水既濟獨不畏土之侵犯乎？

岐伯曰：土能克水，而土亦能生水也。水得土以相生，則土中出水，始足以養肝木而潤各臟
腑也。第不宜過于生之，則水勢汪洋亦能衝決堤岸，水無土制，變成洪水之逆流，故水不畏
土之克也。

少師曰：善。

陳士铎曰：五行得水則潤，失水則損。況取資多而分散少乎。 故水爲五行之所窈，不可不
多也。說得水之有益，有此可悟永矣。

== 心火篇

少師曰：心火，君火也。何故宜靜不宜動？

岐伯曰：君主無爲，心爲君火，安可有爲乎！君主有力，非生民之福也。所以心靜則火息，
心動則火炎。息則脾胃之土受其益，炎則脾胃之土受其災。

少師曰：何謂也？

岐伯曰：脾胃之土喜溫火之養，惡烈火之逼也。溫火養則土有生氣而成活土，烈火逼則土有
死氣而成焦土矣。焦火何以生金，肺金乾燥，必求濟于腎水，而水不足以濟之也。少師曰：
腎水本濟心火者也，何以救之無裨乎？

岐伯曰：人身之腎水原非有余。況見心火之太旺，雖濟火甚切，獨不畏火氣之爍乎。故避火
之炎，不敢上升于心中也。心無水濟則心火更烈，其克肺益甚。肺畏火刑，必求援于腎子，
而腎子欲救援而無水，又不忍肺母之淩爍，不得不出其腎中所有，傾國以相助。于是水火兩
騰，升于上焦，而與心相戦。心因無水以克肺，今見水不濟心火來助肺，欲取其水而轉與火，
相合則火勢更旺。于是肺不受腎水之益，反得腎火之虐矣。斯時肝經之木，見肺金太弱，亦
出火以焚心明助腎母，以稱于實報肺仇而加刃也，。

少師曰：何以解氛乎？

岐伯曰：心火動極矣，安其心而火可息也。

少師曰：可用寒涼直折其火乎？

岐伯曰：寒涼可暫用，不可久用也。暫用則火化爲水，久用則水變爲火也。

少師曰：斯又何故歟？

岐伯曰：心火必得腎水以濟之也。滋腎安心則心火永靜，捨腎安心則心火仍動矣。

少師曰：凡水火未有不相克也，而心腎水火何相交而相濟乎？

岐伯曰：水不同耳。腎中邪水最克心火，腎中真水最養心火，心中之液即腎内真水也。腎之
真水旺，而心火安。腎之真水衰，而心火沸。是以心腎交而水火既濟，心腎開而水火未濟也。

少師曰：心在上，腎在下，地位懸殊，何彼此樂交無間乎？

岐伯曰：心腎之交，雖胞胎導之，實肝木介之也。肝木氣通，腎無阻隔，肝木氣郁，心腎即
閉塞也。

少師曰：然則肝木又何以養之？

岐伯曰：腎水爲肝木之母，補腎即所以通肝木。非水不旺火，非木不生欲，心液之不枯，必
肝血之常足。欲肝血之不乏，必腎水之常盈，補肝木要不外補腎水也。少師曰：善。

陳士铎曰：心火，君火也。君心爲有形之火，可以水折。不若腎中之火，爲無形之火也。無
形之火，可以水養。知火之有形、無形，而虛火，實火可明矣。

= 卷四

== 脾土篇

少師問曰：脾爲濕土，土生于火，是火爲脾土之父母乎？

岐伯曰：脾土之父母，不止一火也。心經之君火，包絡、三焦、命門之相火，皆生之。然而
君火之生，脾土甚疏；相火之生，脾土甚切，而相火之中命門之火，尤爲最親。

少師曰：其故何歟？

岐伯曰：命門盛衰，即脾土盛衰。命門生絕即脾土生絕也。蓋命門爲脾土之父母，實關死生。
非若他火之可旺、可微、可有、可無也。

少師曰：命門火過旺，多非脾土之宜，又何故乎？

岐伯曰：火少則土濕，無發生之機；火多則土乾，有燥裂之害。蓋脾爲濕土，土中有水。命
門者，水中之火也。火藏水中則火爲既濟之火。自無亢焚之禍，與脾土相宜，故火盛亦盛，
火衰亦衰，火生則生，火絕則絕也。若火過于旺，是火勝于水矣。水不足以濟火，乃未濟之
火也。火似旺，而實衰，假旺而非真旺也。與脾土不相宜耳。非惟不能生脾，轉能耗土之生
氣，脾土無生氣則赤地乾枯，欲化精微以潤各臟腑難矣。且火氣上炎與三焦包絡之火直衝而
上與心火相合。火癒旺而土癒耗，不成爲焦火得乎。

少師曰：焦土能生肺金乎？

岐伯曰：肺金非土不生。今土成焦土，中鮮潤澤之氣，何以生金哉。且不特不生金也，更且
嫁禍于肺矣，蓋肺乏土氣之生，又多火氣之逼，金弱木強，必至之勢也。木強淩土而土敗更
難生金，肺金絕而腎水亦絕也，水絕則木無以養，木枯自焚益添火焰，土癒加燥矣。

少師曰：治何經以救之？

岐伯曰：火之有余水之不足也，補水則火自息。然而徒補水則水不易生，補肺金火氣則水有
化源，不患乎無本也。腎得水以制火，則水火相濟，火無偏旺之害。此治法之必先補水也。

少師曰：善。

陳士铎日：脾土與胃土不同。生脾土與胃土生不同，雖生土在于火也，然火各異。生脾土必
須于心，生胃土必須于包絡。心爲君火，包絡爲相火也。二火斷須補腎，以水能生火耳。

== 胃土篇

少師問曰：脾胃皆土也，有所分乎？

岐伯曰：脾，陰土也；胃，陽土也。陰土逢火則生，陽土必生于君火。君火者，心火也。少
師曰：土生于火，火來生土，兩相親也，豈胃土遇三焦命門之相火，辭之不受乎？

岐伯曰：相火與胃不相合也，故相火得之而燔，不若君火得之而樂也。

少師曰：心包亦是相火，何與胃親乎？

岐伯曰：心包絡代君火以司令者也，故心包相火即與君火無異，此胃上之所以相親也。

少師曰：心包代心之職，胃土取資心包，無異取資心火矣。但二火生胃，土則受益；二火助
胃，火則受禍者，何也？

岐伯曰：胃土衰則喜火之生，胃火盛則惡火之助也。

少師曰：此又何故歟？

岐伯曰：胃陽土宜弱不宜強。

少師曰：何以不宜強也？

岐伯曰：胃多氣多血之府，其火易動，動則燎原而不可制，不特爍肺以殺子，且焚心以害母
矣，且火之盛者，水之涸也。火沸上騰必至有焚林竭澤之虞，爍腎水燒肝木，其能免乎了

少師曰：治之奈何？

岐伯曰：火盛必濟之水，然水非外水也，外水可暫救以止炎，非常治之法也。必大滋其内水
之匱。内水者，腎水也。然而火盛之時，滋腎之水不能瀉胃之火，以火旺不易滅，水衰難驟
生也。

少師曰：又將奈何？

岐伯曰：救焚之法，先瀉胃火，後以水濟之。

少師曰：五臟六腑皆藉胃氣爲生，瀉胃火不損各臟腑乎？吾恐水未生，腎先絕矣。

岐伯曰：火不息則土不安，先息火後濟水，則甘霖優渥，土氣升騰，自易發生萬物。此瀉胃
正所以救胃，是瀉火非瀉土也。胃土有生機，各臟腑豈有死法乎。此救胃又所以救腎，并救
各臟腑也。

少師曰：胃氣安寧，肝木來克奈何？

岐伯曰：肝來克胃，亦因肝木之燥也，木燥則肝氣不平矣，不平則木郁不伸，上克胃土，土
氣自無生發之機，故調胃之法以平肝爲重。肝氣平矣又以補水爲急，水旺而木不再郁也，惟
是水不易旺仍須補肺金，旺則生水，水可養木，金旺則制木，木不克土，胃有不得其生發之
性者乎。

少師曰：善。

陳士铎曰：胃土以養永爲主，養水者助胃也。胃中有水，則冒火不沸。故補腎正所以益；胃
也。可見胃火之盛由于腎永之衰，朴腎水正補胃土也。故胃火可殺，胃火宜培，不可紊也。

== 包絡火篇

少師曰：心包之火無異心火，其生克同乎？

岐伯曰：言同則同，言異則異。心火生胃，心包之火不止生胃也。心火克肺，心包之火不止
克肺也。

少師曰：何謂也？

岐伯曰：心包之火生胃，亦能死胃。胃土衰得心包之火而土生，胃火盛得心包之火而土敗。
土母既敗，肺金之子何能生乎！

少師曰：同一火也，何生克之異？

岐伯曰：心火，陽火也。其勢急而可避，心包之火，陰火也。其勢緩而可親。故心火之克肺
一時之刑，心包之克肺，實久遠之害。害生于刑者，勢急而患未大害。生于思者，勢緩而患
漸深也。

少師曰：可救乎？

岐伯曰：亦在制火之有余而已。

少師曰：制之奈何？

岐伯曰：心包陰火竊心之陽氣以自養之，必得腎之陰氣以自存。心欲溫腎，腎欲潤心，皆先
交心包以通之，使腎水少衰，心又分其水氣，腎且供心火之不足，安能分余惠以慰心包。心
包乾涸，毋怪其害胃土也。補腎水之枯，則水足灌心而化液，即足注心包而化津，此不救胃，
正所以救胃也。

少師曰：包絡之火可瀉乎？

岐伯曰：胃土過旺，必瀉心包之火。然心包之火可暫瀉而不可久瀉也。心包逼近于心，瀉包
絡則心火不寧矣。

少師曰：然則奈何？

岐天師曰：肝經之木，包絡之母也。瀉肝則心包絡之火必衰矣。

少師曰：肝亦心之母也，瀉肝而心火不寒乎？

岐天師曰：暫瀉肝則包絡損其焰，而不至于害心。即久瀉肝則心君減其炎，亦不至于害包絡，
猶勝于直瀉包絡也。

少師曰：誠若師言，瀉肝經之木，可救急而不可圖緩，請問善後之法？

岐伯曰：水旺則火衰，既濟之道也。安能捨補腎水别求瀉火哉。

少師曰：善。

陳士铎曰：包絡之火爲相火，相火宜補不宜瀉也。宜補而用瀉必害心包矣。

== 三焦火篇

少師曰：三焦無形，其火安生乎？

岐伯曰：三焦稱腑，虛腑也。無腑而稱腑，有随寓爲家之義。故逢木則生、逢火則旺。即逢
金，逢土亦不相仇而相得。總欲竊各臟腑之氣以自旺也。

少師曰：三焦耗臟腑之氣，宜爲各臟腑之所絕矣，何以反親之也？

岐伯曰：各臟腑之氣非三焦不能通達上下，故樂其來親而益之以氣，即有偷竊亦安焉而不問
也。

少師曰：各臟腑樂與三焦相親，然三焦樂與何臟腑爲更親乎？

岐伯曰：最親者，膽木也。膽與肝爲表裏，是肝膽爲三焦之母，即三焦之家也。無家而寄生
于母家，不無府而有府乎。然而三焦之性喜動惡靜，上下同流，不樂安居于母宅，又不可謂
肝膽之宮竟是三焦之府也。

少師曰：三焦火也，火必畏水，何故與水親乎？

岐伯曰：三焦之火最善制水，非親水而喜入于水也，蓋水無火氣之溫則水成寒水矣。寒水何
以化物。故腎中之水，得三焦之火而生；膀胱之水，得三焦之火而化。火與水合實有既濟之
歡也。但恐火過于熱，制水太甚，水不得益而得損，必有乾燥之苦也。

少師曰：然則何以治之？

岐伯曰：瀉火而水自流也。

少師曰：三焦無腑，瀉三焦之火，何從而瀉之？

岐伯曰：視助火之臟腑以瀉之，即所以瀉三焦也。

少師曰：善。

陳士铎曰：三焦之火附于臟腑，臟腑旺而三焦旺，臟腑衰而三焦衰，故助三焦在于助各臟腑
也，瀉三焦火可置臟腑于不問乎。然則三焦盛衰全在視腑也。

== 膽木篇

少師曰：膽寄于肝，而木必生于水。腎水之生肝即是生膽矣，豈另來生膽乎？

岐伯曰：腎水生木必先生肝，肝即分其水以生膽。然肝與膽皆腎子也，腎豈有疏于膽者乎。
惟膽與肝爲表裏，實手足相親，無彼此之分也。故腎水旺而肝膽同旺，腎水衰而肝膽同衰。
非僅肝血旺而膽汁盈，肝血衰而膽汁衰也。

少師曰：然亦有腎水不衰，膽氣自病者何也？

岐伯曰：膽之汁主藏，膽之氣主洩，故喜通不喜塞也。而膽氣又最易塞，一遇外寒，膽氣不
通矣；一遇内郁，膽氣不通矣。單補腎水不舒膽木，則木中之火不能外洩，勢必下克脾胃之
土，木土交戦多致膽氣不平，非助火以刑肺，必耗水以虧肝，于是膽郁肝亦郁矣。肝膽交郁，
其塞益甚。故必以解郁爲先，不可徒補腎水也。

少師曰：肝膽同郁，將獨鮮膽木之塞乎？

岐伯曰：郁同而解郁，烏可異哉。膽郁而肝亦郁，肝舒而膽亦舒。舒膽之後濟之補水，則水
蔭木以敷榮，木得水而調達，既不絕肝之血，有不生心之液者乎。自此三焦得木氣以爲根，
即包絡亦得膽氣以爲助，十二經無不取決于膽也。何憂匱乏哉！

少師曰：善。

陳士铎曰：肝膽同爲表裏，肝盛則膽盛，肝衰則膽衰，所以治膽以治肝爲先。肝易于郁，而
膽之易郁，又寧與肝膽殊乎，故治膽必治肝也。

== 膀胱水篇

少師曰：水屬陰，膀胱之水謂之陽水，何也？

岐伯曰：膀胱之水，水中藏火也。膀胱無火，水不化，故以陽水名之。膀胱腑中本無火也。
恃心腎二臟之火相通化水，水始可藏而亦可洩。夫火屬陽，膀胱既通火氣，則陰變爲陽矣。

少師曰：膀胱通心腎之火，然親于腎而疏于心也。心火眉陽，膀胱亦屬陽，陽不與陽親，何
也？

岐伯曰：膀胱與腎爲表裏最爲關切，故腎親于膀胱。而膀胱亦不能疏于腎也。心不與膀胱相
合，毋怪膀胱之疏心矣。然心雖不合于膀胱，而心實與小腸爲表裏，小腸與膀胱正相通也。
心合小腸，不得不合膀胱矣。是心與膀胱其迹若遠而實近也。

少師曰：然則膀胱親于心而疏于腎乎？

岐伯曰：膀胱陽水也，喜通陰火而不喜通陽火，似心火來親未必得之化水。然而腎火不通心
火，則陰陽不交，膀胱之陽火正難化也。

少師曰：此又何故歟？

岐伯曰：心火下交于腎，則心包三焦之火齊來相濟，助胃以化膀胱之水。倘心不交腎，心包
三焦之火各奉心火以上炎，何敢下降以私通于腎。既不下降，敢代君以化水乎。

少師曰：君火無爲，相火有爲，君火不下降，包絡相火正可代君出治。何以心火不交，相火
亦不降乎？

岐伯曰：君臣一德而天下治。君火交而相火降，則膀胱得火而水化。君火離而相火降，則膀
胱得火而水乾。雖君火恃相火而行，亦相火必藉君火而治。腎得心火之交，又得包絡之降，
陰陽台爲一性，竟不能分腎爲陰、心爲陽矣。

少師曰：心腎之離合，膀胱之得失如此乎？

岐伯曰：膀胱，可寒而不可過寒，可熱而不可過熱。過寒則遺，過熱則閉，皆心腎不交之故
也。此水火所以重既濟耳。

少師曰：善。

陳士铎曰：膀胱本爲水腑。然水中藏火，無水不交，無火亦不交也。故心腎二臟皆通于膀胱
之腑。膀胱不通，又何交乎！交心腎，正藏水火也。

== 大腸金篇

少師曰：金能生水，大腸屬金，亦能生水乎？

岐伯曰：大腸之金，陽金也。不能生水，且藉水以相生。

少師曰：水何能生金哉？

岐伯曰：水不生金而能養金，養即生也。

少師曰：人身火多于水，安得水以養大腸乎？

岐伯曰：大腸離水實無以養，而水苦無多。所異者，脾土生金，轉輸精液庶無乾燥之虞。而
後以腎水潤之，便慶濡澤耳。是水土俱爲大腸之父母也。

少師曰：土生金，而大腸益燥何也？

岐伯曰：土柔而大腸潤，土剛而大腸燥矣。

少師曰：土剛何以燥也？

岐伯曰：土剛者，因火旺而剛也。土剛而生金更甚，然未免同火俱生，金喜土而畏火，雖生
而實克矣。安得不燥哉。

少師曰：水潤金也，又善蕩金者，何故歟？

岐伯曰：大腸得真水而養，得邪水而蕩也。邪正不兩立，勢必相遇而相爭。邪旺而正不能敵，
則衝激澎湃傾腸而瀉矣。故大腸尤宜防水。防水者，防外來之水非防内存之水也。

少師曰：人非水火不生，人日飲水何，以防之？

岐伯曰：防水何若培土乎。土旺足以制水，土旺自能生金。制水，不害邪水之侵。生金，無
愁真水之涸，自必火靜而金安可傳導而變化也。

少師曰：大腸無火，往往有傳導變化而不能者，又何故歟？

岐伯曰：大腸惡火又最喜火也。惡火者，惡陽火也。喜火者，喜陰火也。陰火不同，而腎中
之陰火尤其所喜。喜火者，喜其火中之有水也。

少師曰：腎火雖水中之火，然而克金，何以喜之？

岐伯曰：肺腎子母也。氣無時不通，肺與大腸爲表裏，腎氣生肺，即生大腸也。大腸得腎中
水火之氣，始得司其開阖也。倘水火不入于大腸，開阖無權，何以傳導變化乎！

少師曰：善。

陳士铎曰：大腸無水火何以開阖。開阖既難以傳導變化乎。可悟大腸必須于水火也。大腸無
水火之真，即邪來犯之，故防邪仍宜潤正耳。

== 小腸火篇

少師曰：小腸屬火乎？屬水乎？

岐伯曰：小腸與心爲表裏，與心同氣，屬火無疑。其體則爲水之路，故小腸又屬水也。

少師曰：然則小腸居水火之間，乃不陰不陽之腑乎。

岐伯曰：小腸屬陽，不屬陰也。兼屬之水者，以其能導水也。水無火不化，小腸有火，故能
化水。水不化火，而火且化水，是小腸屬火明矣。惟小腸之火代心君以變化，心即分其火氣
以與小腸，始得導水以滲入于膀胱。然有心之火氣、無腎之水氣則心腎不交水火不合，水不
能遽滲于膀胱矣。

少師曰：斯又何故乎？

岐伯曰：膀胱，水腑也，得火而化，亦必得水而親。小腸之火欲。通膀胱，必得腎中真水之
氣以相引，而後心腎會而水火濟，可滲入亦可傳出也。

少師曰：腸爲受盛之官，既容水谷，安在腸内無水，必藉腎水之通膀胱乎？

岐伯曰：真水則存而不洩，邪水則走而不守也。小腸得腎之真水，故能化水谷而分清濁，不
随水谷俱出也。此小腸所以必資于腎氣耳。

少師曰：善。

陳士铎曰：小腸之火，有水以濟之。故火不上焚，而水始下降也。火不上焚者，有水以引之
也，水不下降者，有火以升之也，有升有引，皆既濟之道也。

== 命門真火篇

少師曰：命門居水火中，屬水乎？屬火乎？

岐伯曰：命門，火也。無形有氣，居兩腎之間，能生水而亦藏于水也。

少師曰：藏于水以生水，何也？

岐伯曰：火非水不藏，無水則火沸矣。；水非火不生，無火則水絕矣。水與火蓋兩相生而兩
相藏也。

少師曰：命門之火，既與兩腎相親宜與各臟腑疏矣。

岐伯曰：命門爲十二經之主。不止腎恃之爲根，各臟腑無不相合也。

少師曰：十二經皆有火也，何藉命門之生乎？

岐伯曰：十二經之火，皆後天之火也。後天之火非先天之火不化。十二經之火得命門先天之
火則生生不息，而後可轉輸運動變化于無窮，此十二經所以皆仰望于命門，各倚之爲根也。

少師曰：命門之火氣甚微，十二經皆來取資，盡爲分給，不虞匱乏乎？

岐伯曰：命門居水火中，水火相濟，取之正無窮也。

少師曰：水火非出于腎乎？

岐伯曰：命門水火雖不全屬于腎，亦不全離乎腎也。蓋各經之水火均屬後天，獨腎中水火則
屬先天也。後天火易旺，先天火易衰。故命門火微，必須補火，而補火必須補腎，又必兼水
火。補之正，以命門之火可旺，而不可過旺也。火之過旺，水之過衰也。水衰不能濟火，則
火無所制，必焚沸于十二經，不受益而受損矣。故補火必須于水中補之。水中補火則命門與
兩腎有既濟之歡，分布于十二經亦無未濟之害也。

少師曰，命門之繫人生死甚重，《内經》何以遺之？

岐伯曰：未嘗遺也。主不明則十二官危。所謂主者，正指命門也。七節之旁有小心。小心者，
亦指命門也。人特未悟耳。

少師曰：命門爲主，前人未言何也，

岐伯曰：廣成子云：竊窈冥冥，其中有神。恍恍惚惚，其中有氣。亦指命門也。誰謂前人勿
道哉。且命門居于腎，通于任督，更與丹田神室相接。存神于丹田，所以溫命門也。守氣于
神室，所以養命門也。脩仙之道無非溫養命門耳。命門旺而十二經皆旺，命門衰而十二經皆
衰也。命門生而氣生，命門絕而氣絕矣。

少師曰：善。

陳士铎曰：命門爲十二經之主。《素問》不明言者，以主之難識耳。然不明言者，未嘗不顯
言之也。無如世人不悟耳。經天師指示而命門絕而不絕矣。秦火未焚之前，何故脩命門者少，
總由于不善讀《内經》也。

淩波按：以何處爲命門，是頗值得研究的，有說此有說彼，其實命門一處本無定處。在人與
天地同其德時，自可見命門，其他一切都是空談。若隻說長生，則立鼎之處即是命門，即在
臍後腎前。

= 卷五

== 命門經主篇

雷公問于岐伯曰：十二經各有一主，主在何經？

岐伯曰：腎中之命門爲十二經之主也。

雷公曰：十二經最神者，心也。宜心爲主，不宜以腎中之命門爲主也。

岐伯曰：以心爲主，此主之所以不明也。主在腎之中，不在心之内。然而離心非主，離腎亦
非主也。命門殆通心腎以爲主乎。豈惟通心腎哉。五臟七腑無不共相貫通也。

雷公曰：其共相貫通者，何也？

岐伯曰：人非火不生，命門屬火，先天之火也。十二經得命門之火始能生化，雖十二經來通
于命門，亦命門之火原能通之也。

雷公曰：命門屬火，宜與火相親，何偏居于腎以親水氣耶？

岐伯曰：腎火，無形之火也；腎水，無形之水也。有形之火，水能克之，無形之火，水能生之。火克于水者，有形之水也。火生于水者，無形之水也。然而無形之火偏能生無形之水，故火不藏于火，轉藏于水。所謂一陽陷于二陰之間也。

人身先生命門而後生心。心生肺，肺生脾，脾生肝，肝生腎，相合而相生，亦相克而相生也。
十二經非命門不生，正不可以生克而拘視之也。故心得命門，而神明應物也；肝得命門，而
謀慮也；膽得命門，而決斷也；胃得命門，而受納也；脾得命門，而轉輸也；肺得命門，而
治節也；大腸得命門，而傳導也；小腸得命門，而布化也；腎得命門，而作強也；三焦得命
門，而決瀆也；膀胱得命門，而畜洩也。是十二經爲主之官，而命門爲十二官之主。有此主
則十二官治。無此主則十二官亡矣。

命門爲主，供十二官之取資。其火易衰，其火亦易旺，然衰乃真衰，旺乃假旺。先天之火非
先天之水不生，水中補火，則真衰者不衰矣。火中補水，則假旺者不旺矣。見其衰，補火而
不濟之以水則火益微；見其旺，瀉火而不濟之以水則火益熾。

雷公曰：何遭之渺乎，非天師又孰能知之。

陳士铎曰：命門在心腎之中，又何說之有無。如世人隸知也。此篇講得暢快，非無主之文。

== 五行生克篇

雷公問于岐伯曰：余讀《内經》載五行甚詳，其旨盡之乎？

岐伯曰：五行之理，又何易窮哉。

雷公曰：盍不盡言之？

岐伯曰；談天乎，談地乎，談人乎。

雷公曰，請言人之五行。

岐伯曰：心、肝。脾，肺、腎配火、木，土、金、水，非人身之五行乎。

雷公曰；請言其變。

吱伯曰：變則又何能盡哉。試言其生克。生克之變者，生中克也，克中生也。生不全生也，
克不全克也，生畏克而不敢生也，克畏生而不敢克也。

雷公曰：何以見生中之克乎？

岐伯曰：腎生肝，腎中無水，水涸而火騰矣，肝木受焚，腎何生乎？肝生心，肝中無水，水
燥而木焦矣，心火無煙，肝何生乎？心君火也，包絡相火也，二火無水將自炎也，土不得火
之生，反得火之害矣。脾生肺金也，土中無水，于土何以生物，铄石流金，不生金反克金矣。
肺生腎水也，金中無水，死金何以出泉。崩垆飛汞，不生水反克水矣。蓋五行多水則不生，
五行無水亦不生也。

雷公曰：何以見克中之生乎？

岐伯曰：肝克土，土得木以疏通則土有生氣矣。脾克水，水得土而畜積則土有生基矣。腎克
火，火得水以相濟，則火有神光矣。心克金，然肺金必得心火以煅煉也。肺克木，然肝术必
得肺金以斫削也。非皆克以生之乎。

雷公曰：請言生不全生。

岐伯曰；生不全生者，專言腎水也。各臟腑無不取資于腎。心得腎水而神明煥發也；脾得腎
水而精微化導也；肺得腎水而清肅下行也；肝得腎水而謀慮決斷也。七腑亦無不得腎水而布
化也。然而取資多者分給必少矣。親于此者疏于彼，厚于上者薄于下。此生之所以難全也。

雷公曰：請言克不全克。

岐伯曰：克不全克者，專言腎火也。腎火易動難靜，易逆難順，易上難下，故一動則無不動
矣，一逆則無不逆矣，一上則無不上矣。騰于心躁煩矣。入于脾乾涸矣，于肺喘嗽矣，流于
肝焚燒矣，衝擊于七腑燥渴矣。雖然腎火乃雷火也，亦龍火也。龍雷之火其性雖猛，然聚則
力專，分則勢散，無乎不克反無乎全克矣。

雷公曰：生畏克而不敢生者若何？

岐伯曰；肝木生心火也，而肺金太旺，肝畏肺克不敢生心則心氣轉弱，金克肝木矣。心火生
胃土也，而腎火太旺不敢生胃則胃氣更虛，水侵胃土矣。心包之火生脾土也，而腎水過泛不
敢生脾，則脾氣加困，水欺脾土矣。脾胃之土生肺金也，而肝木過剛，脾胃畏肝不敢生肺，
則肺氣癒損，木侮脾胃矣。肺金生腎水也，而心火過炎，肺畏心克，不敢生腎，則腎氣益枯，
火刑肺金矣。腎水生肝木也，而脾胃過燥，腎畏脾胃之土，不敢生肝，則肝氣更凋，土制腎
水矣。

雷公曰：何法以制之乎？

岐伯曰：制克以遂其生，則生不畏克。助生而忘其克，則克即爲生，

雷公曰：善。克畏生而不敢克者，又若何？

岐伯曰：肝木之盛由于腎水之旺也，木旺而肺氣自衰，柔金安能克剛木乎。脾胃土盛由于心
火之旺也，土旺而肝氣自弱，僵木能克焦土乎。腎水之盛由肺金之旺也，水旺而脾土自微淺，
土能克湍水乎。心火之盛由于肝木乏旺也，火旺而腎氣必虛，勻水能克烈火乎。肺金之盛由
于脾土之旺也，金盛而心氣自怯，寒火能克頑金乎。

雷公曰：何法以制之？

岐伯曰：救其生不必制其克，則弱多爲強。因其克反更培其生則衰轉爲盛。

雷公曰：善。

陳士铎曰：五行生克本不可颠倒。不可颠倒而颠倒者，言生克之變也。篇中專言其變，而變
不可窮矣。 當細細觀之。

== 小心真主篇

爲當問于岐伯曰：物之生也，生于陽。物之成也，成于陰。陽，火也；陰，水也。二者在身
藏乾何物乎？

岐伯曰：大哉，問也。陰陽有先後天之殊也，後天之陰陽藏于各臟腑。先天之陰陽藏于命門。

爲當日：命門何物也？

岐伯曰：命門者，水火之源。水者，陰中之水也；火者，陰中之火也。

爲當曰：水火均屬陰，是命門藏陰不藏陽也。其藏陽又何所乎？

岐伯曰：命門，藏陰即藏陽也。

爲當曰：其藏陰即藏陽之義何居？

岐伯曰：陰中之水者，真水也；陰中之火者，真火也。真火者，真水之所生；真水者，真火
之所生也。水生于火者，火中有陽也。火生于水者，水中有陽也。故命門之火，謂之原氣。
命門之水，謂之原精。精旺則體強，氣旺則形壯。命門水火實藏陰陽，所以爲十二經之主也。
主者，即十二官之化源也。命門之精氣盡，則水火兩亡，陰陽間隔，真息不調，人病輒死矣。

爲當日：陰陽有偏勝，何也？

岐伯曰：陰勝者，非陰盛也，命門火微也。陽勝者，非陽盛也，命門水竭也。

爲當日：陰勝在下陽勝在上者，何也？

岐伯曰：陰勝于下者，水竭其源則陰不歸陽矣。陽勝于上者，火衰其本則陽不歸陰矣。陽不
歸陰，則火炎于上而不降。陰不歸陽，則水沉于下而不升。可見命門爲水火之府也，陰陽之
宅也，精氣之根也，死生之竇也。

爲當曰：命門爲十二官之主寄于何臟？

岐伯曰：七節之旁中有小心，小心即命門也。

爲當曰：鬲肓之上，中有父母，非小心之謂歟。

岐伯曰：鬲肓之上，中有父母者，言三焦包絡也，非言小心也。小心在心之下，腎之中。

陳士铎曰：小心在心腎之中，乃陰陽之中也。陰無陽氣則火不生，陽無陰氣則水不長。世人
錯認小心在鬲肓之上，此命門。真主不明也，誰知小心即命門哉。

== 水不克火篇

大封司馬問于岐伯曰；水克火者也，人有飲水而火不解者，豈火不能制水乎？

岐伯曰：人生于火，養于水。水養火者，先天之真水也。水克火者，後天之邪水也。飲水而
火熱不解者，外水不能救内火也。

大封司馬曰：余終不解其義，幸明示之。

岐伯曰：天開于子，地闢于丑，人生于寅，寅實有火也。天地以陽氣爲生，以陰氣爲殺。陽
即火，陰即水也。然而火不同，有形之火，離火也。無形之火，乾火也。有形之火，水之所
克。無形之火，水之所生。飲水而火不解者，無形之火得有形之水而不相入也。豈惟不能解，
且有激之而火熾者。

大封司馬曰：然則水不可飲乎？

岐伯曰：水可少飲以解燥。不可暢飲以解氛。

大封司馬曰：此何故乎？

岐伯曰：無形之火旺，則有形之火微。無形之火衰則有形之火盛。火得水反熾，必多飲水也，
水多則無形之火因之益微矣。無形之火微，而有形之火癒增酷烈之勢，此外水之所以不能救
内火，非水之不克火也。

大封司馬曰：何以治之？

岐伯曰：補先天無形之水，則無形之火自息矣，不可見其火熱飲水不解，勸多飲以速亡也。

陳士铎曰：水分有形無形，何疑于水哉。水克有形之火，難克無形之火，故水不可飲也。說
得端然實理，非泛然而論也。

== 三關升降篇

巫鹹問曰：人身三關在何經乎？

岐伯曰：三關者，河車之關也。上玉枕，中腎脊、下尾間。

巫鹹曰：三關何故關人生死乎？

岐伯曰：關人生死，故名曰關。

巫鹹曰：請問生死之義。

岐伯曰：命門者，水中火也。水火之中實藏先天之氣，脾胃之氣後天之氣也。先天之氣不交
于後天，則先天之氣不長。後天之氣不交于先天，則後天之氣不化。二氣必晝夜交，而後生
生不息也。然而後天之氣必得先天之氣先交而後生。而先天之氣必由下而上，升降諸脾胃，
以分散于各臟腑。三關者，先天之氣所行之徑道也。氣旺則升降無礙，氣衰則阻，阻則人病
矣。

巫鹹曰：氣衰安旺乎？

岐伯曰；助命門之火，益腎陰之水，則氣自旺矣。

巫鹹曰：善。

陳士铎曰：人有三關，故可生可死。然生死實在先天，不在後天也。篇中講後天者返死而生，
非愛生而惡死。人能長守先天，何惡先天之能死乎。

== 表微篇

奚仲問于岐伯曰：天師《陰陽别論》中有陰結，陽結之言。結在臟乎？抑結在腑乎？

岐伯曰：合臟腑言之也。

奚仲曰：臟陰腑陽，陰結在臟，陽結在腑乎？

岐伯曰：陰結陽結者，言陰陽之氣結也。合臟腑言之，非陽結而陰不結，陰結而陽不結也。
陰陽之道，彼此相根，獨陽不結，獨陰亦不結也。

奚仲曰：《陰陽别論》中，又有剛與剛之言。言臟乎？言腑乎？

岐伯曰：專言臟腑也，陽陰氣不和，臟腑有過剛之失，兩剛相遇，陽過旺陰不相接也。

奚仲曰：臟之剛乎？抑腑之剛乎？

岐伯曰：臟剛傳腑，則剛在臟也。腑剛傳臟，則剛在腑也。

奚仲曰：《陰陽别論》中又有陰摶陽摶之言，亦言臟腑乎？

岐伯曰：陰摶陽摶者言十二經之脈，非言臟腑也。雖然十二臟腑之陰陽不和，而後十二經脈
始現陰陽之摶，否則摶之象不現于脈也。然則陰摶陽摶言脈面即言臟腑也。

奚仲曰：善。

陳士铎曰：陽結、陰結、陰摶、陽摶、俱講得微妙。

== 呼吸篇

雷公問于岐伯曰：人氣之呼吸應天地之呼吸乎？

岐伯曰：天地人同之。

雷公曰：心肺主呼，腎肝主吸，是呼出乃心肺也，吸入乃腎肝也。何有時呼出不屬心肺而屬
腎肝，吸入不屬腎肝而屬心肺乎？

岐伯曰：一呼不再呼，一吸不再吸，故呼中有吸，吸中有呼也。

雷公曰：請悉言之。

岐伯曰：呼出者，陽氣之出也。吸入者，陰氣之入也。故呼應天，而吸應地。呼不再呼，呼
中有吸也。吸不再吸，吸中有呼也。故呼應天而亦應地，吸應地而亦應天。所以呼出心也、
肺也，從天言之也；吸入腎也、肝也，從地言之也。呼出腎也、肝也，從地言之也；吸入心
也、肺也，從天言之也。

蓋獨陽不生，呼中有吸者，陽中有陰也；獨陰不長，吸中有呼者，陰中有陽也。天之氣不降
則地之氣不升。地之氣不升則天之氣不降。天之氣下降者，即天之氣呼出也。地之氣上升者，
即地之氣吸入也。故呼出心肺，陽氣也，而腎肝陰氣輒随陽而俱出矣。吸入腎肝，陰氣也，
而心肺陽氣輒随陰而俱入矣。所以陰陽之氣，雖有呼吸而陰陽之根無間隔也。呼吸之間雖有
出入而陰陽之本無兩歧也。

雷公曰：善。

陳士铎曰：呼中有吸，吸中有呼，是一是二，人可參天地也。

== 脈動篇

雷公問于岐伯曰：手太陰肺、足陽明胃、足少陰腎，三經之脈常動不休者何也？

岐伯曰：脈之常動不休者，不止肺、胃、腎也。

雷公曰：何以見之？

岐伯曰：四末陰陽之會者，氣之大絡也。四街者，氣之曲徑也。周流一身，晝夜環轉，氣無
一息之止，脈無一晷之停也。肺、胃、腎脈獨動者，勝于各臟腑耳。非三經之氣獨動不休也。
夫氣之在脈也，邪氣中之也，有清氣中之，有濁氣中之。邪氣中之也，清氣中在上，濁氣中
在下，此皆客氣也。見于脈中，決于氣口。氣口虛，補而實之，氣口盛，瀉而洩之。

雷公曰：十二經動脈之穴可悉舉之乎？

岐伯曰：手厥陰心包經，動脈在手之勞宮也。手太陰肺經，動脈在手之太淵也。手少陰心經，
動脈在手之陰郄也。足太陰脾經，動脈在腹衝門也。足厥陰肝經，動脈在足之太衝也。足少
陰腎經，動脈在足之太溪也。手少陽三焦經，動脈在面之和髎也。手太陽小腸經，動脈在項
之天窗也。手陽明大腸經，動脈在手之陽溪也。足太陽膀胱經，動脈在足之委中也。足少陽
膽經，動脈在足之懸鍾也。足陽明胃經，動脈在足之衝陽也。各經時動時止，不若胃爲六腑
之原，肺爲五臟之主，腎爲十二經之海，各常動不休也。

陳士铎曰：講脈之動處，俱有條理，非無因之文也。

== 瞳子散大篇

云師問于岐伯曰：目病，瞳子散大者伺也？

岐伯曰：必得之内熱多飲也。

云師曰：世人好飲亦常耳，未見瞳子皆散大也。

岐伯白：内熱者，氣血之虛也。氣血虛，則精耗矣。五臟六腑之精皆上注于目，瞳子尤精之
所注也。精注瞳子，而目明，精不注瞳子，而目暗。今瞳子散大則視物必無準矣，

云師曰：然往往視小爲大也。

歧伯曰：瞳子之繫通于腦。腦熱則瞳子亦熱，熱極而瞳子散大矣。夫瞳子之精，神水也。得
腦氣之熱，則水中無非火氣，火欲爆而光不收，安得不散大乎。

云師曰：何火之虐乎？

岐伯曰：必飲火酒兼食辛熱之味也。火酒大熱，得辛熱之味以助之則益熱矣。且辛之氣散，
而火酒者，氣酒也，亦主散。況火酒至陽之味，陽之昧必升于頭面，火熱之毒真歸于腦中矣。
腦中之精，最惡散而最易散也。得火酒辛熱之氣，有随入随散者腦氣既散于中，而瞳子散大
應于外矣。彼氣血未虛者，腦氣尚不至盡散也，故瞳子亦無散大之象。然目則未有不昏者也。
云師曰：善。

陳士铎曰：瞳子散大，不止于酒。大約腎水不足，亦能散大。然水之不足，乃火之有余也。
益其陰而火降，火降而散大者不散大也。不可悟火之虐乎。必認作火酒之一者，尚非至理。

= 卷六

== 診原篇

雷公曰問于岐伯曰：五臟六腑各有原穴，診之可以知病，何也？

岐伯曰：診脈不若診原也。

雷公曰：何謂也？

岐伯曰：原者，脈氣之所注也。切脈之法繁而難知，切腧之法約而易識。

雷公曰：請言切腧之法。

岐伯曰：切腧之法，不外陰陽。氣來清者，陽也。氣來濁者，陰也。氣來浮者，陽也。氣來
沉者，陰也，浮而無者，陽將絕也。沉而無者，陰將絕也。浮而清者，陽氣之生也。沉而清
者，陰氣之生也。浮而濁者，陰血之長也。浮而清者，陽血之長也。以此診腧，則生死淺深
如見矣。

陳士铎曰：診原法，不傳久矣。天師之論，真得其要也。

== 精氣引血篇

力牧問于岐伯曰：九竅出血何也？

岐伯曰：血不歸經耳。

力牧曰：病可療乎？

岐伯曰：療非難也，引其血之歸經，則瘥安。

力牧曰：九竅出血，臟腑之血皆出矣。難療而曰易療者，何也？

岐伯曰：血失一經者重，血失眾經者輕。失一經者，傷臟腑也。失眾經者，傷經絡也。

力牧曰：血已出矣，何引而歸之？

岐伯曰：補氣以引之，補精以引之也。

力牧曰：氣虛則血難攝，補氣攝血則余已知之矣。補精引血余實未知也。

岐伯曰：血之妄行，由腎；火之亂動也。腎火亂動，由腎水之大衰也。血得腎火而有所歸，
亦必得腎水以濟之也。夫腎水、腎火如夫婦之不可離也。腎水旺而腎火自歸。腎火安，而各
經之血自息。猶婦在家而招其夫，夫既歸宅，外侮輒散。此補精之能引血也。

力牧曰：兼治之乎抑單治之乎？

岐伯曰：先補氣後補精。氣虛不能攝血，血攝而精可生也。精虛不能藏血，血藏而氣益旺也。
故補氣必須補精耳。

力牧曰：善。雖然血之妄出，疑火之祟耳。不清火而補氣，母乃助火乎。

岐伯曰：血至九竅之出：是火盡外洩矣，熱變爲寒，烏可再洩火乎。清火則血癒多矣。

力牧曰：善。

陳士铎曰：失血，補氣本是妙理。誰知補精即補氣乎。補氣寓于補精之中，補精富于補血之
内，豈是泛然作論者。寒變熱，熱變寒，參得個中趣，纔是大羅仙。

== 天人一氣篇

大撓問于岐伯曰：天有轉移，人氣随天而轉移，其故何也？

岐伯曰：天之轉移，陰陽之氣也。人之氣亦陰陽之氣也。安得不随天氣爲轉移乎。

大撓曰：天之氣分春夏秋冬，人之氣惡能分四序哉？天之氣配日月支乾，人之氣惡能配兩曜
一旬十二時哉？

岐伯曰：公泥于甲子以論天也。天不可測，而可測。人亦不可測，而可測也。天之氣有春、
夏、秋、冬，人之氣有喜、怒、哀、樂，未嘗無四序也。天之氣有日、月，人之氣有水、火，
未嘗無兩曜也。天之氣，有甲、乙、丙、丁、戊、己、庚、辛、壬、癸。人之氣，有陽；跷、
陰跷、帶、衝、任、督、陽維、陰維、命門、胞絡、未嘗無一旬也。天之氣有子、丑、寅、
卯、辰、巳、午、未、申、酉、戌、亥。人之氣，有心、肝、脾、肺、腎、心包、膽、胃、
膀胱、三焦、大小腸，未嘗無十二時也。天有氣，人即有氣以應之。天人何殊乎。

大撓曰：天之氣萬古如斯，人之氣何故多變動乎？

岐伯曰：人氣之變動，因乎人，亦因乎天也。春宜溫而寒，則春行冬令矣。春宜溫而熱，則
春行夏令矣。春宜溫而涼，則春行秋令矣。夏宜熱而溫，則夏行春令也。夏宜熱而涼，則夏
行秋令也。夏宜熱而寒，則夏行冬令也。秋宜涼而熱，非秋行夏令乎？秋宜涼而溫，非秋行
春令乎？秋宜涼而寒，非秋行冬令乎？冬宜寒而溫，是冬行春令矣。冬宜寒而熱，是冬行夏
令矣。冬宜寒而涼，是冬行秋令矣。倒行逆施，在天既變動若此，欲人臟腑中不随天變動必
不得之數矣。

大撓曰：天氣變動人氣随天而轉移，宜盡人皆如是矣。何以有變，有不變也？

岐伯曰：人氣随天而變者，常也。人氣不随天而變者，非常也。

大撓曰：人氣不随天氣而變，此正人守其常也。天師謂非常者，予不得其旨，請言其變。

岐伯曰：宜變而不變，常也。而余謂非常者，以其異于常人也。斯人也必平日固守元陽，未
喪其真陰者也。陰陽不調，随天氣之變動，彼自行其陰陽之正令，故能不變耳。

大撓曰：彼變動者何以治之？

岐伯曰：有余者瀉之，不足者補之，郁則達之，熱則寒之，寒則溫之，如此而已。

陳士铎曰：天人合一，安能變乎。說得合一之旨。

== 地氣合人篇

大撓問曰：天人同氣，不識地氣亦同于人乎？

岐伯曰：地氣之合于人氣，《素問》、《靈樞》已詳哉言之。何公又問也？

大桡曰：《内經》言地氣統天氣而并論也，未嘗分言地氣。

岐伯曰：三纔并立，天氣即合于地氣，地氣即合于人氣，原不必分言之也，大撓曰：地氣有
獨合于人氣之時，請言其所以合也？

岐伯曰：言其合則合，言其分則分。

大撓曰：請言人之獨合于地氣。

岐伯曰：地有九州島島島島，入有九竅，此人之獨合于地也。

大撓曰：《内經》言之矣。

岐伯曰：雖言之未嘗分晰之也。

大撓曰：請言其分。

岐伯曰：左目合冀，右目合雍，鼻合豫，左耳合揚，右耳合兖，口合徐，臍合荊，前陰合營，
後陰合幽也。

大撓曰：其病何以應之？

岐伯曰：冀之地氣逆，而人之左目病焉。雍之地氣逆，而，人之右目病焉。豫之地氣逆，而
人之鼻病焉。揚之地氣逆，而人之左耳病焉。兖之地氣逆，而入之右耳病焉。徐之地氣逆，
而人之口病焉。荊之地氣逆，而人之臍病焉。營之地氣逆，而人之前陰病焉。幽之地氣逆，
而人之後陰病焉。此地氣之合病氣也。

大撓曰：有驗，有不驗何也？

岐伯曰：驗者，人氣之漓也。不驗者，人氣之固也。固者多，漓者少，故驗者亦少。似地氣
之不盡合人氣也，然而合者理也。

大撓曰：既有不驗，恐非定理。

岐伯曰：醫統天地人以言道，烏可缺而不全乎。寧言地氣聽其驗不驗也。

大撓曰：善。

陳士铎曰：地氣實合于天，何分于人乎。地氣有驗不驗者，非分于地氣已，說其合，胡必求
其合哉。

== 三纔并論篇

鬼臾區間曰：五運之會，以司六氣。六氣之變，以害五臟。是五運之陰陽，即萬物之綱紀，
變化之父母，生殺之本始也。夫子何以教區乎？

岐伯曰：子言是也。臾區退而作《天元紀》各論，以廣五運六氣之義。

岐伯曰：臾區之言大而肆乎，雖然執臾區之論，概治五臟之病，是得一而矣一也。

臾區曰；何謂乎？

岐伯曰：五運者，五行也。談五運即闡五行也。然五行止有五，五運變成六，明者視六猶五
也。昧者眩六爲千矣。

臾區曰：弟子之言非歟？

岐伯曰：子言是也，

臾區曰：弟子言是夫子有後言，請亟焚之。

岐伯曰：醫道之大也，得子言大乃顯然。而醫道又微也，執子言微乃隱。余所以有後言也。
雖然余之後言，正顯子言之大也。

臾區曰；請悉言之。

岐伯曰：五運乘陰陽而變遷，五臟因陰陽而變動。執五運以治病未必有合也，捨五運以治病
未必相離也。遺五運以立言，則醫理缺其半。統五運以立言，則醫道該其全。予故稱子言之
大而肆也。

鬼臾區曰：請言缺半之理。

岐伯曰：陰陽之氣，有盈有虛。男女之形，有強有弱，盈者，虛之兆。虛者，盈之機。蓋兩
相伏也。強者弱之媒，弱者強之福。蓋兩相倚也。合天地人以治邪，不可止執五運以治邪也。
合天地人以扶正，不可止執五運以扶正也。

鬼臾區曰：醫道合天地人者，始無弊乎？

岐伯曰：人之陰陽與天地相合也。陽極生陰，陰極生陽，未嘗異也。世疑陰多于陽，陰有羣
陰，陽無二陽。誰知陽有二陽乎。有陽之陽，有陰之陽，君火爲陽之陽，相火爲陰之陽，人
有君火、相火而天地亦有之，始成其爲天，成其爲地也，使天地無君火萬物何以昭蘇，天地
無相火萬物何以震動。天地之君火，日之氣也。天地之相火，雷之氣也。雷出于地而轟于天，
日臨于。天而照于地。蓋上下相合，人亦何獨不然。合天地人以治病則得其全，執五運以治
病則缺其半矣。

鬼臾區稽首而歎曰：大哉！聖人之言乎，區無以測師矣。

陳士铎曰：六氣即五行之論，知五行即知六氣矣。世不知五運即不知五行也。不知五行，即
不知六氣矣。

== 五運六氣離合篇

鬼臾區間曰：五運與六氣并講，人以爲異，奈何？

岐伯曰：五運非六氣，則陰陽難化。六氣非五運，則疾病不成。二者合而不離也，夫寒、暑、
濕、燥、風、火，此六氣也。金、木、水、火、土，此五運也。六氣分爲六、五運分爲五，
何不可者，讵知六氣可分，而五運不可分也。蓋病成于六氣，可指爲寒、暑、濕、燥、風、
火，病成于五運，不可指爲金、木、水、火、土。以金病必兼水，水病必兼木，木病必兼火，
火病必兼土，土病必兼金也。且有金病而木亦病，木病而土亦病，土病而水亦病，水病而火
亦病，火病而金亦病也。故六氣可分門以論症，五運終難拘歲以分門。誠以六氣随五運以爲
轉移，五臟因六氣爲變亂，此分之不可分也。

鬼臾區曰：然則何以治六氣乎？

岐伯曰：五運之盛衰随五臟之盛衰爲強弱，五臟盛麗六氣不能衰，五臟強而六氣不能弱。逢
司天、在泉之年寒、暑，濕、燥、燥、風、火有病、有不病者，正五臟強而不弱也。所以五
臟盛者，何畏運氣之侵哉。

鬼臾區曰：善。

陳士铎曰：六氣之病，因五臟之不調也。五臟之不調即五行之不正也，調五行即調六氣矣。

== 六氣分門第

雷公問于岐伯曰：五運六氣合而不離，統言之可也。何鬼臾區分言之多乎？

岐伯曰：五運不可分，六氣不可合。

雷公曰：其不可合者，何也？

岐伯曰：六氣之中有暑火之異也。

雷公曰：暑火皆火也，何分乎？

岐伯曰；火，不一也。暑外火，火内火也。

雷公曰：等火耳。火與火相合，而相應也。奈何異視之？

岐伯曰：内火之動，必得外火之引。外火之侵，必得内火之召也。似可合以立論，而終不可
合。以分門者，内火與外火異也。蓋外火，君火也。内火，相火也。君火即暑，相火即火，
暑乃陽火，火乃陰火。火性不同烏可不區而别乎。六氣分陰陽，分三陰三陽也，三陰三陽中
分陽火陰火者，分君相之二火也。五行概言火，而不分君相。六氣分言火，而各配支乾。二
火分配，而暑與火各司其權，各成其病矣。故必宜分言之也。臾區之說，非私言也。實聞予
論，而推廣之。

雷公曰：予昧矣，請示世之不知二火者。

陳士铎曰：五行止有一火，六氣乃有二火。有二火乃分配支乾矣，支乾雖分，而君相二火實
因六氣而異。言之于不可異而異者，異之于陰陽之二火也。

== 六氣獨勝篇

雍父問曰：天地之氣，陰陽盡之乎？

岐伯曰：陰陽足以包天地之氣也。雖然，陰陽之中，變化錯雜，未可以一言盡也。

雍父曰：請言其變。

岐伯曰：六氣盡之矣。

雍父曰：六氣是公之已言也，請言所未言。

岐伯曰：六氣之中有余不足，勝復去留，臾區言之矣。尚有一端未言也。遇司天在泉之年，
不随天地之氣轉移，實有其故，不可不論也。

雍父曰：請悉論之。

岐伯曰：辰戌之歲，太陽司天而天柱不能窒抑之，此肝氣之勝也。己亥之歲，厥陰司天而天
蓬不能窒抑之，此心氣之勝也。丑未之歲，太陰司天而天蓬不能窒抑之，此包絡之氣勝也。
子午之歲，少陰司天而天衝不能窒抑之，此脾氣之勝也。寅申之歲，少陽司天而天英不能窒
抑之，此肺氣之勝也。卯酉之歲，陽明司天而天内不能窒抑之，此腎氣之勝也。

雍父曰：司天之勝，予知之矣。請言在泉之勝。

岐伯曰：丑未之歲，太陽在泉而地晶不能窒抑之，此肝膽之氣勝也。寅申之歲，厥陰在泉而
地玄不能窒抑之，此心與小腸之氣勝也。辰戌之歲，太陰在泉而地玄不能窒抑之，此包絡三
焦之氣勝也。卯酉之歲，少陰在泉而地蒼不能窒抑之，此脾胃之氣勝也。己亥之歲，少陽在
泉而地彤不能窒抑之，此肺與大腸之氣勝也。子午之歲，陽明在泉而地阜不能窒抑之，此腎
與膀胱之氣勝也。

雍父曰：子聞順天地之氣者昌，逆天地之氣者亡。今不爲天地所窒抑，是逆天地矣，不天而
獨存何也？

岐伯曰：順之昌者，順天地之正氣也。逆之亡者，逆天地之邪氣也。順可逆而逆可順乎。

雍父曰：同是人也，何以能獨勝乎？

岐伯曰：人之強弱不同，縱欲與節欲異也。

雍父曰：善。

陳士铎曰：天蓬地玄，獨有二者，正分其陰陽也。 陰陽同而神亦同者，正顯其順逆也。可
見宜順不宜逆矣。

== 三合篇

雷公問曰：寒暑燥濕風火，此六氣也。天地之運化何合于人而生病？

岐伯曰：五行之生化也。

雷公曰：人之五臟，分金木水火土，彼此有勝負而人病，此臟腑之自病也，何關于六氣乎？

岐伯曰：臟腑之五行，即天之五行，地之五行也。天地人三合而生化出矣。

雷公曰：請問三合之生化。

岐伯曰：東方生風，風生木，木生酸，酸生肝，肝生筋，筋生心，在天爲風，在地爲木，在
體爲筋，在氣爲柔，在臟爲肝，其性爲瞚，其德爲和，其用爲動，其色爲蒼，其化爲榮，其
蟲毛，其政爲散，其令宣發，其變摧拉，其眚隕落，其味爲酸，其誌爲怒，怒傷肝，悲勝怒，
風傷肝，燥勝風，酸傷筋，辛勝酸，此天地之合人肝也。

南方生熱，熱生火，火生苦，苦生心，心生血，血生脾，在天爲熱，在地爲火，在體爲脈，
在氣爲炎，在臟爲心，其性爲暑，其德爲顯，其用爲燥，其色爲赤，其化爲茂，其蟲羽，其
政爲明，其令郁蒸，其變炎爍，其眚燔（火+瞞-目），其味爲苦，其誌爲喜，喜傷心，恐勝
喜，熱傷氣，寒勝熱，苦傷氣，鹹勝苦，此天地之合人心也。

中央生濕，濕生土，土生甘，甘生脾，脾生肉，肉生肺，在天爲濕，在地爲土，在體爲肉，
在氣爲克，在臟爲脾，其性靜堅，其德爲濡，其用爲化，其色爲黃，其化爲盈，其蟲倮，其
政爲謐，其令云雨，其變動注，其眚淫潰，其味爲甘，其誌爲思，思傷脾，怒勝思，濕傷肉，
風勝濕，甘傷脾，酸勝甘，此天地之合人脾也。

西方生燥，燥主金，金生卒，辛生肺，肺生皮毛，在天爲燥，在地爲金，在體爲皮毛，在氣
爲成，在臟爲肺，其性爲涼，其德爲清，其用爲固，其色爲白，其化爲斂，其蟲介，其政爲
勁，其令霧露，其變肅殺，其眚蒼落，其味爲辛，其誌爲憂，憂傷肺，喜勝憂，熱傷皮毛，
寒勝熱，辛傷皮毛，苦勝辛，此天地之合人肺也。

北方生寒，寒生水，水生鹹，鹹生腎，腎生骨髓，髓生肝，在天爲寒，在地爲水，在體爲骨，
在氣爲堅，在臟爲腎，其性爲凜，其德爲寒，其用爲藏，其色爲黑，其化爲肅，其蟲鱗，其
政爲靜，其令爲寒，其變凝冽，其眚冰雹，其、味爲鹹，其誌爲恐；恐傷腎，思勝恐，寒傷
血，燥勝寒，鹹傷血，甘勝鹹，此天地之合人腎也，五臟合金木水火土，斯化生之所以出也。

天地不外五行，安得不合哉。

雷公曰：五行止五，不應與六氣合也。

岐伯曰：六氣即五行也。

雷公曰：五行五而六氣六，何以相合乎？

岐伯曰：使五行止五，則五行不奇矣。五行得六氣，則五行之變化無窮。余所以授六氣之論，
而臾區乃肆言之也。

雷公曰：六氣之中，各配五行，獨火有二，此又何故？

岐伯曰：火有君相之分耳：人身火多于水，五臟之中，無臟非火也，是以天地之火亦多于金
木水土也，正顯天地之合于入耳，

雷公曰；大哉盲乎，釋蒙解惑，非天師之謂歟。請載登六氣之篇。

陳士铎曰：五行不外五臟，五臟即六氣之論也。因五行止有五，惟火爲二，故六氣合二火而
論之，其實合五臟而言之也。

= 卷七

== 四時六氣異同篇

問曰：五臟合五時，六經應六氣，然《診要經終篇》以六氣應五臟而終于六經，《四時剌逆
從論》以六經應四時而終于五臟，《診要篇》以經脈之生于五臟而外合于六經，《四時剌逆
從論》以經脈本于六氣而外連于五臟何也？

岐伯曰：人身之脈氣，上通天，下合地，未可一言盡也，故彼此錯言之耳。

天老曰：章句同而意旨異，不善讀之，吾恐執而不通也。

岐伯曰：醫統天地人以立論，不知天何知地，不知地何知人。脈氣循于皮肉筋骨之間，内合
五行，外合六氣，安得一言而盡乎。不得不分之以歸于一也。

天老曰：請問歸一之旨。

岐伯曰：五時之合五臟也，即六氣之合五臟也。六氣之應六經也即五時之應六經也。知其同
何難知異哉。

天老曰：善。

陳士铎曰：何嘗異，何必求同；何嘗同，不妨言異。人惟善求之可耳。

== 司天在泉分合篇

問曰：司天在泉，二氣相合，主歲何分？

岐伯曰：歲半以上，天氣主之。歲半以下，地氣主之。

天老曰：司天之氣主上半歲乎？在泉之氣主下半歲乎？

岐伯曰：然。

天老曰：司天之氣何以主上半歲也？

岐伯曰：春夏者，天之陰陽也，陽生陰長，天之氣也，故上半歲主之。

天老曰：在泉之氣何以主下歲也？

岐伯曰：秋冬者，地之陰陽也。陰殺陽藏，地之氣也，故下半歲主之。

天老曰：一歲之中，天地之氣截然分乎？

岐伯曰：天地之氣，無日不交。司天之氣始于地之左，在泉之氣奉乎天之右。一歲之中，互
相感召，雖分而實不分也。

天老曰：然則司天在泉，何必分之乎？

岐伯曰：不分言之則陰陽不明，奚以得陰中有陽，陽中有陰之義乎。司天之氣始于地而終于
天，在泉之氣始于天而終于地。天地升降，環轉不息，實有如此，所以可合而亦可分之也。

天老曰：司天之氣何以始于地？在泉之氣何以始于天乎？

岐伯曰：司天之氣始于地之左，地中有天也；在泉之氣始于天之右，天中有地也。

天老曰：善。

陳士铎曰：司天在泉，合天地以論之，纔是善言天地者。

== 從化篇

天老問曰：燥從熱發，風從燥起，埃從風生，雨從濕注，熱從寒來，其故何歟？

岐伯曰：五行各有勝，亦各有制也。制之太過則受制者應之，反從其化也。所以熱之極者，
燥必随之，此金之從火也。燥之極者，風必随之，此木之從金也。風之極者，塵霾随之，此
土之從木也。濕蒸之極者，霖雨随之，此水之從土也。陰寒之極者，雷電随之，此火之從水
也。乃承制相從之理，何足異乎。

天老曰：何道而使之不從乎？

岐伯曰：從火者潤其金乎；從金者抒其木乎；從木者培其土乎；從土者導其水乎；從水者助
其火乎。毋不足、毋有余，得其平而不從矣。

天老曰：潤其金而金仍從火，抒其木而木仍從金，培其土而土仍從木，導其水而水仍從土，
助其火而火仍從水，奈何？

歧伯曰：此陰陽之己變，水火之已漓，非藥石針灸之可療也。

陳士铎曰：言淺而論深。

== 冬夏火熱篇

胡孔甲問于岐伯曰：冬令嚴冷凜冽之氣，逼人肌膚，人宜畏寒，反生熱症，何也？

岐伯曰：外寒則内益熱也。

胡孔甲曰：外寒内熱，人宜同病，何故獨熱？

岐伯曰：腎中水虛，不能制火，因外寒相激而火發也，人生五臟非火，無腑非火也，無不藉
腎水相養。腎水盛則火藏，腎水涸則火動，内無水養則内熱已極，又得外寒束之，則火之郁
氣一發，多不可救。

胡孔甲曰：火必有所助而後盛，火發于外，外無火助，宜火之少衰，乃熱病發于夏轉輕，發
于冬反重，何也？

岐伯曰：此正顯火郁之氣也。暑日氣散而火難居，冬日氣藏而火難洩，難洩而洩之，則郁怒
之氣所以難犯而轉重也。

胡孔甲曰：可以治夏者治冬乎？

岐伯曰：辨其火熱之真假耳，毋論冬夏也。胡孔甲曰：善。

陳士铎曰：治郁無他治之法，人亦治郁而已矣。

== 暑火二氣篇

祝融問于岐伯曰：暑與火皆熱症也，何六氣分爲二乎？

岐伯曰：暑病成于夏，火病四時皆有，故分爲二也。

祝融問曰：火病雖四時有之，然多成于夏，熱蘊于夏而發于四時，宜暑包之矣。

岐伯曰：火不止成于夏，四時可成也，火宜藏不宜發，火發于夏日者，火以引火也，其在四
時，雖無火之可發，而火蘊結于臟腑之中，每能自發，其酷烈之勢較外火引之者更橫，安可
談暑而不談火乎。

祝融曰：火不可發也，發則多不可救。與暑熱之相犯有異乎？

岐伯曰：暑與火熱同而實異也。惟其不同，故夏日之火不可與春秋冬之火共論。惟其各異，
即夏日之暑不可與夏日之火并舉也。蓋火病乃臟腑自生之熱，非夏令暑熱所成之火。故火症
生于夏，仍是火症，不可謂火是暑、暑即是火也。

祝融曰：暑火非一也，分二氣宜矣。

陳士铎曰：暑與火不可并論，獨吐至理。

== 陰陽上下篇

常伯問于岐伯曰：陽在上、陰在下，陽氣亦下行乎？

岐伯曰：陰陽之氣，上下相同。陽之氣未嘗不行于下也，常伯曰，寒厥到膝不到巅，頭痛到
巅不到膝，非陰氣在下，陽氣在上之明驗乎？

岐伯曰：陰氣生于陽，陽氣生于陰。蓋上下相通，無彼此之離也。陽氣從陰，出于經脈之外；
陰氣從陽，入于經脈之中，始得氣血貫通而五臟七腑無不周遍也。寒厥到膝，陽不能達也，
非陽氣專在上而不在下也。頭痛到巅，陰不能降也，非陰氣專在下而不在上也。天地不外陰
陽，天地之陰陽不交，則寒暑往來，收藏生長，鹹無準實，人何獨異哉。

陳士铎日：陽宜達，陰宜降也。二者相反，則達者不達，降者不降矣。論理陽之達有降之勢，
陰之降有達之機，總貴陰陽之不可反也。

== 營衛交重篇

雷公曰：陽氣出于衛氣，陰氣出于營氣。陰主死，陽主生，陽氣重于陰氣，宜衛氣重于營氣
矣。

岐伯曰：營衛交重也。

雷公曰：請問交重之旨。

岐伯曰：宗氣積于上焦，營氣出于中焦，衛氣出于下焦。蓋有天，有陽氣，有陰氣。人禀天
地之二氣，亦有陰陽，衛氣即陽也。由下焦至中焦以升于上焦，從陰出陽也。營氣即陰也，
由中焦至上焦以降于下焦，從陽入陰也。二氣并重，交相上下，交相出入，交相升降，而後
能生氣于無窮也。

雷公曰：陰陽不可離，予既已知之矣。但陰氣難升者謂何？

岐伯曰：陰氣精專，必随宗氣以同行于經隧之中，始于手太陰肺經太淵穴，而行于手陽明大
腸經、足陽明胃經、足太陰脾經、手少陰心經、手太陽小腸經、足太陽膀胱經、足少陰腎經、
手厥陰心包經、手少陽三焦經、足少陽膽經、足厥陰肝經，而又始于手太陰肺經。蓋陰在内
不在外，陰主守内不主衛外，纖折而若雖升實無晷之不升也，故營衛二氣人身并重，未可重
衛輕營也。

雷公曰：善。

陳士铎曰：營衛原并重也，世重衛而輕營者，不知營衛也。

== 五臟互根篇

雷公問于岐伯曰：陽中有陰，陰中有陽，余既知之矣；然論陰陽之變遷也，未知陰中有陽，
陽中有陰，亦有定位乎？

岐伯曰：陰陽互相根也，原無定位。然求其位，亦有定也，肺開竅于鼻、心開竅于舌、脾開
竅于口、肝開竅于目、腎開竅于耳，厥陰與督脈會于巅，此陽中有陰，陰居陽位也。肝與膽
爲表裏，心與小腸爲表裏，腎與膀胱爲表裏，脾與胃爲表裏，肺與大腸爲表裏，包絡與三焦
爲表裏，此陰中有陽，陽居陰位也。

雷公曰：請言互根之位。

岐伯曰：耳屬腎而聽聲，聲屬金，是耳中有肺之陰也。鼻屬肺而聞臭，臭屬火，是鼻中有心
之陰也。舌屈心而知味，味屬土，是舌中有脾之陰也。目有五輪，通貫五臟，腦屬腎，各會
諸體，是耳與腦有五臟之陰也。大腸俞在脊十六椎旁，胃俞在脊十二椎旁，小腸俞在背第十
八椎，膽俞在脊十椎旁，膀胱俞在中膂第二十椎，三焦俞在腎俞之上脊第十三椎之旁，包絡
無俞，寄于膈俞，在上七椎之旁，是七腑陽中有陰之位也。惟各有位，故其根生生不息也。
否則虛器耳，何根之有哉。

雷公曰：善。

陳士铎曰：陰中有陽，陽中有陰，無位而有位者，以陰陽之有根也。

== 八風固本篇

雷公問于岐伯曰：八風出于天乎，出于地乎，抑出于人乎？

岐伯曰：八風出于天地，人身之五風合而成病，人無五風，天地之風不能犯也。

雷公曰：請問八風之分天地也。

岐伯曰：八風者，春夏秋冬，東西南北之風也。春夏秋冬之風，特令之風也，屬于天。東西
南北之風，方隅之風也，屬于地。然而地得天之氣，風乃長。天得地之氣，風乃大。是八風
屬于天地，可分而不可分也。

雷公曰：人之五風，何以合天地乎？

岐伯曰：五風者，心肝脾肺腎之風也。五臟虛而風生矣。以内風召外風，天地之風始翕然相
合。五臟不虛，内既無風，外風何能入乎。

雷公曰：風既入矣，祛外風乎，抑消内風乎？

岐伯曰：風由内召，不治内將何治乎。

雷公曰：治内風而外風不散奈何？

岐伯曰：内風不治，外風益入，安得散乎。治臟固其本，治風衛其标，善治八風者也。

雷公曰：何言之善乎。請誌之，傳示來者。

陳士铎曰：小風之來，皆外感也。外感因于内招，故單治内不可也，單治外亦不可也。要在
分之中宜合，合之中宜分也。

= 卷八

== 八風命名篇

少俞問岐伯曰；八風分春夏秋冬，東西南北乎？

岐伯曰：然，少俞曰：東西南北，不止四風，合之四時則八風，不足以概之也。

岐伯曰：風不止八，而八風實足概之，

少俞曰：何謂也？

岐伯曰：風從東方來，得春氣也。風從東南來，得春氣而兼夏氣矣。風從南方來，得夏氣也。
風從西南來，得夏氣而兼秋氣矣。風從西方來，得秋氣也。風從西北宋，得秋氣而兼冬氣矣。
風從北方來，得冬氣也，風從東北來，得冬氣而兼春氣矣。此方隅時令合而成八也。

少俞曰：八風有名乎？

岐伯曰：東風名和風也，東南風名熏風也，南風名熱風也，西南風名溫風也，西風名商風也，
西北風名涼風也，北風名寒風也，東北風名陰風也。又方隅時令合而名之也。

少俞曰：其應病何如乎？

岐伯曰：和風傷在肝也，外病在筋。薰風傷在胃也，外病在肌。熱風傷在心也，外病在脈。
溫風傷在脾也，外病在腹。商風傷在肺也，外病在皮。涼風傷在膀胱也，外病在營衛。寒風
傷在腎也，外病在骨。陰風傷在大腸也，外病在胸脅。此方隅時令與臟腑相合而相感也。然
而臟腑内虛，八風因得而中之，邪之所湊，其氣必虛，非空言也。

少俞曰：人有臟腑不虛而八風中之者，又是何謂？

岐伯曰：此暴風猝中，不治而自癒也。

陳士铎曰：八風之來皆外感也。外感因于内召，故治内而外邪自散，若自外病者不必治之。

== 太乙篇

風後問于岐伯曰：八風可以占疾病之吉兇乎？

岐伯曰：天人一理也，可預占以斷之。

風後曰：占之不驗何也？

岐伯曰：有驗有不驗者，人事之不同耳。天未嘗不可占也。

風後曰：請悉言之。

岐伯曰：八風休咎，無日無時不可占也。如風從東方來，寅卯辰時則順，否則逆矣，逆則病。
風從北方來，申酉戌時則順，否則逆矣，逆則病。風從南方來，巳午未時則順，否則逆矣，
逆則病。風從北方來，亥子丑時則順，否則逆矣，逆則病。

風後曰：予聞古之占風也，多以太乙之日爲主。

天師臼：無日無時不可占也，恐不可爲訓乎。

岐伯曰：占風以太乙日，決病所以驗不驗也。

風後曰：捨太乙以占吉兇，恐不驗更多耳。

岐伯曰：公何以信太乙之深也。

風後曰：太乙移日，天必應之風雨。風雨和則民安而病少，風雨暴則民勞而病多。太乙在冬
至日有變，占在君。太乙在春分日有變，占在相。太乙在中宮日有變，占在相吏。太乙在秋
分日有變，占在將。太乙在夏至日有變，占在民。所謂有變者，太乙居五宮之日，得非常之
風也。各以其所主占之，生吉克兇多不爽也。

岐伯曰：請言風雨之暴。

風後曰：暴風南方來，其傷入也，内捨于心，外在脈，其氣主熱。暴風西南方來，其傷人也，
内捨于脾，外在肌，其氣主弱。暴風西方來，其傷人也，内捨于肺，外在皮膚，其氣主燥。
暴風西北方來，其傷人也，内捨于小腸，外在手太陽脈，脈絕則溢，脈閉則結不通，善暴死，
其氣主清。暴風從北方來，其傷人也，内捨于腎，外在骨，與肩背之膂筋，其氣主寒。暴風
東北方來，其傷人也，内捨于大腸，外在兩脅腋骨下及肢節，其氣主溫。暴風東方來，其傷
人也，内捨于肝，外在筋紐，其氣主濕。暴風東南方來，其傷人也，内捨于胃，外在肌肉，
其氣主重着。言風而雨概之矣。

岐伯曰；人見風輒病者，豈皆太乙之移日乎。執，太乙以占風，執八風以治病，是泥于論風
也。夫百病皆始于風，人之氣血虛餒，風乘虛輒入矣。何待太乙居宮哉。

陳士铎曰：人病全不在太乙，說得澹而有味。

== 親陽親陰篇

風後問于歧伯曰：風與寒異乎？

岐伯曰：異也。

曰：何異乎？

岐伯曰：風者八風也，寒者寒氣也，雖鳳未有不寒者，要之風各異也。

風後曰：風與寒有異，入人臟腑亦有異乎？

岐伯曰：風入風府，寒不入風府也。

風後曰：其義何居？

岐伯曰：風，陽邪；寒，陰邪。陽邪主降，陰邪主升。主降者由風府之穴而入，自上而下也。
主升者不由風府，由臍之穴而入，自下而上也。

風後曰：陰邪不從風府入，從何穴而入乎？

岐伯曰；風府之穴，陽經之穴也。臍之穴，陰經之穴也。陽邪從陽而入，故風入風門也，陰
邪從陰而入，故寒入臍也。陽親陽，陰親陰，此天地自然之道也。

風後曰：風穴招風，寒穴招寒，風門，風穴也，宜風之入矣，臍非寒穴也，何寒從臍入乎？

岐伯曰：臍非寒穴，通于命門，命門火旺，則寒不能入，命門火衰，則腹内陰寒，臍有不寒
者乎。陰寒之邪，遂乘虛寒之隙，奪臍而入矣，奚論寒穴哉。

風後曰：善。

陳士铎曰：陽邪入風府，陰邪入臍，各有道路也。

== 異傳篇

雷公問曰：各臟腑之病皆有死期，有一日即死者，有二三日死者，有四五日死者，有五六日
至十余日死者，可晰言之乎？

岐伯曰：病有傳經不傳經之異，故死有先後也。

雷公曰：請問傳經。

岐伯曰：邪自外來，内入臟腑，必傳經也。

雷公曰：請問不傳經。

岐伯曰：正氣虛自病，則不傳經也。

雷公曰：移寒移熱，即傳經之謂乎？

岐伯曰；移即傳之義，然移緩傳急。

雷公曰：何謂乎？

岐伯曰：移者臟腑自移。傳者邪不欲在此腑而傳之彼臟也。故移之勢緩而兇傳之勢急而暴，
其能殺人則一也。

雷公曰：其傳經殺人若伺？

岐伯曰：邪入于心，一日死，

邪入于肺三日，傳于肝四日，傳于脾五日，傳于胃十日死，

邪入于肝三日，傳于脾五日，傳于胃十日，傳于腎又三日，邪散而癒，否則死。

邪入于脾一日，傳于胃二日，傳于腎三日，傳于膀胱十四日，邪散而癒，否則死。

邪入于胃五日，傳于腎八日，傳于膀胱又五日，傳于小腸又二日，傳于心則死。

邪入于腎三日，傳于膀胱又三日，傳于小腸又三日，傳于心則死。

邪入苎膀胱五日，傳于腎又一日，傳于小腸又一日，傳于心則死。

邪入于膽五日，傳于肺又五日，傳于腎又五日，傳于心則死。

邪入于三焦一日，傳于肝三日，傳于心則死。

邪入于胞絡一日，傳于胃二日，傳于膽三日，傳于脾四日，傳于腎五日，傳于肝不癒，則再
傳，再傳不癒則死。

邪入于小腸一日，傳于膀胱二日，傳于腎三日，傳于包絡四日，傳于胃五日，傳于脾六日，
傳于肺七日，傳于肝八日，傳于膽九日，傳于三焦十日，傳于大腸十一日，復傳于腎，如此
再傳不已則死。

邪入于大腸一日，傳于小腸二日，傳于三焦三日，傳于肺四日，傳于脾五日，傳于肝六日，
傳于腎七日，傳于心則死。不傳心仍傳小腸，則生也。

邪入于膽，往往不傳，故無死期可定。然邪入于膽，往往如見鬼神，有三四日即死者，此熱
極自焚也，

雷公曰：善。

陳士铎曰；移緩傳急，确有死期可定，最說得妙。

== 傷寒知變篇

雷公問曰：傷寒一日，巨陽受之，何以頭項痛，腰脊強也？

岐伯曰：巨陽者，足太陽也。其脈起于目内眦，上額，交巅入絡腦，還出别下項，循肩膊内，
挾脊，抵腰中，寒邪必先入于足太陽之經，邪入足太陽，則太陽之經脈不通，爲寒邪所據，
故頭項痛，腰脊強也。

雷公曰：二日陽明受之，宜身熱、目疼，鼻乾、不得卧矣。而頭項痛，腰脊強又何故歟？

岐伯曰：此巨陽之余邪未散也。

雷公曰：太陽之邪未散宜不入陽明矣。

岐伯曰：二日則陽明受之矣。因邪留戀太陽，未全入陽明，故頭項尚痛，腰脊尚強，非二日
陽明之邪全不受也。

雷公曰：三日少陽受之，宜胸脅痛、耳聾矣。邪宜出陽明矣。既不入少陽，而頭項、腰脊之
痛與強，仍未除者又何故歟？

岐伯曰：此邪不欲傳少陽，轉回于太陽也。

雷公曰：邪傳少陽矣，宜傳入于三陰之經，何以三日之後，太陽之症仍未除也？

岐伯曰：陽經善變，且太陽之邪與各經之邪不同。各經之邪循經而入。太陽之邪出入自如，
有入有不盡入也。惟不盡入，故雖六七日而其症未除耳。甚至七日之後，猶然頭項痛、腰脊
強，此太陽之邪乃原留之邪，非從厥陰復出，傳之足太陽也。

雷公曰：四日太陰受之，腹滿嗌乾。五日，少陰受之，口乾舌燥。六日厥陰受之，煩滿囊縮。
亦有不盡驗者何也？

岐伯曰：陰經不變，不變而變者，邪過盛也。

雷公曰：然則三陽三陰之經皆善變也。變則不可以日數拘矣。

岐伯曰：日數者盲其常也。公問者言其變也。變而不失其常則變則可生，否則死矣。

雷公曰：兩感于寒者變乎？

岐伯曰：兩感者，越經之傳也，非變也。

陳士铎曰：傷寒之文，世人不知，讀此論人能悟否，無奈治傷寒者不能悟也。

== 傷寒同異篇

雷公問于岐伯曰：傷寒之病多矣，可悉言之乎？

岐伯曰：傷寒有六，非冬傷于寒者，舉不得謂傷寒也。

雷公曰：請言其異。

岐伯曰：有中風，有中暑，有中熱，有中寒，有中濕，有中疫，其病皆與傷寒異。傷寒者，
冬月感寒，邪入營衛，由腑而傳于臟也。

雷公曰：暑熱之症，感于夏，不感于三時，似非傷寒矣。風寒濕疫，多感于冬日也，何以非
傷寒乎？

岐伯曰：百病皆起于風。四時之風，每直中于臟腑，非若傳經之寒，由淺而深入也。寒之中
人，自在嚴寒，不由營衛直入臟腑，是不從皮膚漸進，非傳經之傷寒也。水王于冬，而冬日
之濕，反不深入，以冬令收藏也，他時則易感矣。疫來無方，四時均能中疫，而冬疫常少二
症，俱不傳經，皆非傷寒也。

雷公曰：寒熱之不同也，何熱病亦謂之傷寒乎？

岐伯曰：寒感于冬，則寒必變熱，熱變于冬，則熱即爲寒，故三時之熱病不可謂寒，冬日之
熱病不可謂熱，是以三時之熱病不傳經，冬日之熱病必傳經也。

雷公曰：熱病傳經，乃傷寒之類也，非正傷寒也，何天師著《素問》，有熱病傳經之文，而
傷寒反無之，何也？

岐伯曰：類宜辯而正不必辯也。知類即知正矣。

雷公曰：善。

陳士铎曰：傷寒必傳經，斷在嚴寒之時，非冬日傷寒舉不可謂傷寒也。 辯得明說得出。

== 風寒殊異篇

風後問于岐伯曰；冬傷于寒與春傷于寒有異乎？

岐伯曰；春傷于寒者風也，非寒也。

風後曰：風、即寒也，何異乎？

岐伯曰：冬日之風則寒，春日之風則溫，寒傷深，溫傷淺，傷深者入少陽而傳裏，傷淺者入
少陽而出表，故異也。

風後曰：傳經乎？

岐伯曰：傷冬日之風則傳，傷春日之風則不傳也。

風後曰：其不傳何也？

岐伯曰：傷淺者，傷在皮毛也。皮毛屬肺，故肺受之不若傷深者入于營衛也。

風後曰：春傷于風；，頭痛鼻塞，身亦發熱，與冬傷于寒者何無異也？

岐伯曰：風入于肺，鼻爲之不利，以鼻主肺也。肺既受邪，肺氣不宣，失清肅之令，必移邪
而入于太陽矣，膀胱畏。邪，堅閉其經，水道失行，水不下洩，火乃炎上，頭即痛矣。夫頭
乃陽之首也，既爲邪火所據，則一身之真氣皆與邪爭，而身乃熱矣。

風後曰：肺爲胃之子，肺受邪，宜胃來援，何以邪入肺而惡熱，口渴之症生，豈生肺者轉來
刑肺乎？

岐伯曰：胃爲肺之母，見肺子之寒，必以熱救之，夫胃之熱，心火生之也，胃得心火之生則
胃土過旺，然助胃必克肺矣。火能刑金，故因益而反損也。

風後曰：嘔吐者何也？

岐伯曰：此風傷于太陰也。風在地中，土必震動，水泉上溢則嘔吐矣，散風而土自安也。

風後曰：風邪入太陽，頭痛何以有痛不痛之殊也了岐伯曰：肺不移風于太陽，則不痛耳。

風後曰：風不入于太陽，頭即不痛乎？

岐伯曰：肺通于鼻，鼻通于腦，風入于肺，自能引風入腦而作頭痛，肺氣旺則風入于肺而不
上走于腦，故不痛也。

風後曰：春傷于風，往來寒熱，熱結于裏何也？

岐伯曰：冬寒入于太陽，久則變寒，春風入于太陽，久則變熱，寒則動傳于臟，熱則靜結于
腑，寒在臟則陰與陽戦而發熱，熱在腑則陽與陰戦而發寒，随臟腑之衰旺，分寒熱之往來也。

風後曰：傷風自汗何也？

岐伯曰：傷寒之邪，寒邪也。傷風之邪，風邪也。寒邪入胃，胃惡寒而變熱，風邪入胃，胃
喜風而變溫，溫則不大熱也，得風以揚之，火必外洩，故汗出矣。

風後曰：春傷于風，下血谵語，一似冬傷于寒之病何也？

岐伯曰：此熱入血室，非狂也。傷于寒者，熱自入于血室之中，其熱重傷于風者，風祛熱入
于血室之内，其熱輕也。

風後曰：谵語而潮熱者何也？

岐伯曰：其脈必滑者也。

風後曰：何也？

岐伯曰：風邪入胃，胃中無痰則發大熱，而谵語之聲高。胃中有痰則發潮熱，而谵語之聲低。
潮熱發谵語，此痰也。滑者，痰之應也。

風後曰：春傷于風，發厥、心下悸，何也？

岐伯曰：傷于寒者，邪下行，傷于風者，邪上衝也。寒乃陰邪，陰則走下，風乃陽邪，陽則
升上。治寒邪先定厥，後定悸，治風邪先定悸，後定厥，不可誤也。

風後曰：傷于風而發熱如見鬼者，非狂乎？

岐伯曰：狂乃實邪，此乃虛邪也。實邪從太陽來也，邪熾而難遏；虛邪從少陰來也，邪旺而
將衰。實邪火逼心，君而外出，神不守于心也。虛邪火引肝，魂而外遊，魄不守于肺也。

風後曰：何論之神乎，吾無測師矣。

陳士铎曰：風與寒殊，故論亦殊，人當細觀之。

== 陰寒格陽篇

盤盂問于岐伯曰：大小便閉結不通，飲食輒吐，面赭唇焦，飲水亦嘔，脈又沉伏，此何症也？

岐伯曰：腎虛寒盛，陰格陽也。

盤盂曰：陰何以格陽乎？

岐伯曰：腎，少陰經也，惡寒喜溫。腎寒則陽無所附，升而不降矣。

盤盂曰：其故何也？

岐伯曰：腎中有水火存焉。火藏水中，水生火内，兩相根而兩相制也。邪入則水火相離而病
生矣。

盤盂曰：何邪而使之離乎？

岐伯曰：寒熱之邪皆能離之，而寒邪爲甚。寒感之輕則腎中之虛陽上浮，不至格拒之至也。
寒邪太盛，拒絕過堅，陽杜陰而力衰，陰格陽而氣旺，陽不敢居于下焦，衝逆于上焦矣，上
焦衝逆，水谷入喉，安能下入于胃乎。

盤盂曰：何以治之？

岐伯曰：以熱治之。

盤盂曰：陽宜陰折，熱宜寒折，今陽在上而作熱，不用寒反用熱，不治陰反治陽，豈别有義
乎？

岐伯曰：上熱者，下逼之使熱也；陽升者，陰祛之使升也。故上熱者下正寒也，以陰寒折之，
轉害之矣，故不若以陽熱之品順其性而從治之，則陽回而陰且交散也。

盤盂曰：善。

陳士铎曰：陰勝必須陽折，陽勝必須陰折，皆從治之法也。

== 春溫似疫篇

風後問于岐伯曰：春日之疫，非感風邪成之乎？

岐伯曰：疫非獨風也。春日之疫，非風而何。

風後曰：然則春溫即春疫乎？

岐伯曰：春疫非春溫也。春溫有方而春疫無方也。

風後曰：春疫無方，何其疾之一似春溫也？

岐伯曰：春溫有方而時氣亂之，則有方者變而無方，故與疫氣正相同也。

風後曰：同中有異乎？

岐伯曰：疫氣熱中藏殺，時氣熱中藏生。

風後曰：熱中藏生，何多死亡乎？

岐伯曰：時氣者，不正之氣也。臟腑聞正氣而陰陽和，聞邪氣而陰陽亂。不正之氣即邪氣也，
故聞之而輒病，轉相傳染也。

風後曰：聞邪氣而不病者，又何故歟？

岐伯曰：臟腑自和，邪不得而亂之也。春溫傳染，亦臟腑之虛也。

風後曰：臟腑實而邪遠，臟腑空而邪中，不洵然乎。

陳士铎曰：溫似疫症，不可謂溫即是疫，辯得明爽。

= 卷九

== 補瀉陰陽篇

雷公問于岐伯曰：人身陰陽分于氣血，《内經》詳之矣。請問其余。

岐伯曰：氣血之要，在氣血有余不足而已。氣有余則陽旺陰消，血不足則陰旺陽消。

雷公曰：治之奈何？

岐伯曰：陽旺陰消者，當補其血；陰旺陽消者，當補其氣。陽旺陰消者，宜瀉其氣；陰旺陽
消者，宜瀉其血。無不足，無有余，則陰陽平矣。

雷公曰：補血則陰旺陽消，不必再瀉其氣；補氣則陽旺陰消，不必重瀉其血也。

岐伯曰：補血以生陰者，盲其常補陰也；瀉氣以益陰者，言其暫瀉陽也。補氣以助陽者，言
其常補陽也；瀉血以救陽者，言其暫瀉陰也。故新病可瀉，久病不可輕瀉也；久病宜補，新
病不可純補也。

雷公曰：治血必當理氣乎？

岐伯曰：治氣亦宜理血也。氣無形，血有形，無形生有形者，變也；有形生無形者，常也。

雷公曰：何謂也？

岐伯曰：變治急，常治緩。勢急不可緩，亟補氣以生血；勢緩不可急，徐補血以生氣。

雷公曰：其故何也。

岐伯曰：氣血兩相生長，非氣能生血，血不能生氣也。第氣生血者，其效速；血生氣者，其
功遲。宜急而亟者，治失血之驟也；宜緩而徐者，治失血之後也。氣生血則血得氣而安，無
憂其。沸騰也；血生氣則氣得血而潤，無虞其乾燥也。苟血失補血則氣且脫矣。血安補氣則
血反動矣。

雷公曰：善。

陳士铎曰：氣血俱可補也，當于補中尋其原，不可一味呆補爲妙。

== 善養篇

雷公問于岐伯曰：春三月謂之發陳，夏三月謂之蕃秀，秋三月謂之容平，冬三月謂之閉藏，
天師詳載《四氣調神大論》中。然調四時則病不生，不調四時則病必作，所謂調四時者，調
陰陽之時令乎寧抑調人身陰陽之氣乎？願晰言之。

岐伯曰：明乎哉問也！調陰陽之氣，在人不在時也。春三月調木氣也，調木氣者順肝氣也。
夏三月調火氣也。調火氣者順心氣也。秋三月調金氣也，調金氣者順肺氣也。冬三月調水氣
也，調水氣者順腎氣也。肝氣不順，逆春氣矣，少陽之病應之。心氣不順，逆夏氣矣，太陽
之病應之。肺氣不順，逆秋氣矣，太陰之病應之。腎氣不順，逆冬氣矣，少陰之病應之。四
時之氣可不調乎。調之實難，以陰陽之氣不易調也，故人多病耳。

雷公曰：人既病矣，何法療之？

岐伯曰：人以胃氣爲本，四時失調，致生疾病，仍調其胃氣而已。胃調脾自調矣，脾調而肝
心肺腎無不順矣。

雷公曰：先時以養陰陽，又何可不講乎？

岐伯曰；陽根于陰，陰根于陽，養陽則取之陰也，養陰則取之陽也。以陽養陰，以陰養陽，
貴養之于豫也，何邪能乾乎。閉目塞兌，内觀心腎，養陽則漱津送入心也，養陰則漱津送入
腎也，無他異法也。

雷公曰：善。

天老問曰：陰陽不違背而人無病，養陽養陰之法止調心腎乎？

岐伯曰：《内經》一書，皆養陽養陰之法也。天老曰：陰陽之變遷不常，養陰養陽之法又烏
可執哉？！

岐伯曰：公言何善乎。奇恆之病，必用奇恆之法療之，豫調心腎，養陰陽于無病時也。然而
病急不可緩，病緩不可急，亦視病如何耳。故不宜汗而不汗，所以養陽也；宜汗而急汗之，
亦所以養陽也；不宜下而不下，所以養陰也；宜下而大下之，亦所以養陰也。豈養陽養陰專
尚補而不尚攻乎。用攻于補之中，正善于攻也；用補于攻之内，正善于補也。攻補兼施，養
陽而不損于陰，養陰而不損于陽，庶幾善于養陰陽者乎。

天老曰：善。

陳士铎曰：善養一篇，俱非泛然之論，不可輕用攻補也。

== 亡陽亡陰篇

鳥師問岐伯曰：人汗出不已，皆亡陽也。

岐伯曰：汗出不已，非盡亡陽也。

鳥師曰：汗症未有非熱也，熱病即陽病矣。天師謂非陽何也？

岐伯曰：熱極則陽氣難固，故汗洩亡陽，溺屬陰，汗屬陽，陽之外洩，非亡陽而何謂？非盡
亡陽者，以陽根于陰也，陽之外洩由于陰之不守也。陰守其職，則陽根于陰，陽不能外洩也。
陰失其職，則陰欲自顧不能，又何能攝陽氣之散亡乎。故陽亡本于陰之先亡也。

鳥師曰：陰亡則陰且先脫，何待陽亡而死乎？

岐伯曰：陰陽相根，無寸晷之離也。陰亡而陽随之即亡，故陽亡即陰亡也，何分先後乎，

鳥師曰：陰陽同亡，宜陰陽之共救矣，乃救陽則汗收而可生，救陰則汗止而難活，又何故乎？

岐伯曰：陰生陽則緩，陽生陰則速，救陰而陽之絕不能據回，救陽而陰之絕可以驟復，故救
陰不若救陽也。雖然，陰陽何可離也，救陽之中，附以救陰之法，則陽回而陰亦自復也。

鳥師曰：陰陽之亡，非旦夕之故也，曷不于未亡之前先治之？

岐天師曰；大哉言乎！亡陰亡陽之症，皆腎中水火之虛也，陽虛補火以生水，陰虛補水以制
火，可免兩亡矣。

鳥師曰：善。

陳士铎曰：陰陽之亡，由于陰陽之兩不可守也，陽攝于陰，陰攝于陽，本于水火之虛，虛則
亡，又何疑哉。

== 晝夜輕重篇

雷公問于岐伯曰：晝夜可辨病之輕重乎。

岐伯曰：病有重輕，宜從晝夜辨之。

雷公曰：辨之維何？

岐伯曰：陽病晝重，陰病晝輕，陽病夜輕，陰病夜重。

雷公曰：何謂也？

岐伯曰：晝重夜輕，陽氣旺于晝，衰于夜也。晝輕夜重，陰氣旺于夜，衰于晝也。

雷公曰：陽病晝輕，陰病夜輕，何故乎？

岐伯曰：此陰陽之氣虛也。

雷公曰：請顯言之。

岐伯曰，陽病晝重夜輕，此陽氣與病氣交旺，陽氣未衰也，正與邪鬭，尚有力也，故晝反重
耳。夜則陽衰矣，陽衰不與邪鬭，邪亦不與正鬭，故夜反輕耳。陰病晝輕夜重，此陰氣與病
氣交旺，陰氣未衰也，正與邪爭，尚有力也，故夜反重耳。晝則陰衰矣，陰衰不敢與邪爭，
邪亦不與陰爭，故晝反輕耳。

雷公曰：邪既不與正相戦，宜邪之退捨矣，病猶不瘥，何也？

岐伯曰：重乃真重，輕乃假輕。假輕者視之輕而實重，邪且重入矣，烏可退哉。且輕重無常，
或晝重亦重，或晝輕夜亦輕，或時重時輕，此陰陽之無定，晝夜之雄拘也。

雷公曰：然則何以施療乎？

岐伯曰：晝重夜輕者，助陽氣以祛邪，晝輕夜重者，助陰氣以祛邪，皆不可專祛其邪也。晝
夜俱重，晝夜俱輕，與時重時輕峻于補陰，佐以補陽，又不可泥于補陽而專于祛邪也。

陳士铎曰：晝夜之間，輕重自别。

== 解陽解陰篇

奢龍問于岐伯曰：陽病解于戌，陰病解于寅，何也？

岐伯曰：陽病解于戌者，解于陰也。陰病解于寅者，解于陽也。然解于戌者不始于戌，解于
寅者不始于寅，不始于戌者由寅始之也，不始于寅者由女始之也。解于戌而始于寅，非解于
陰乃解于陽也，解于寅而始于亥，非解于陽乃解于陰也。

奢龍曰：陽解于陽，陰解于陰，其義何也？

岐伯曰：十二經均有氣王之時，氣王則解也。

奢龍曰：十二經之王氣可得聞乎？

岐伯曰：少陽之氣王寅卯辰，太陽之氣王已午未，陽明之氣王申酉戌，太陰之氣王亥子丑，
少陰之氣王子丑寅，厥陰之氣王丑寅卯也。

奢龍曰：少陰之王何與各經殊乎？

岐伯曰：少陰者，腎水也。水中藏火，火者陽也。子時一陽生，丑時二陽生，寅時三陽生，
陽進則陰退，故陰病遇子丑寅而解者，解于陽也。

奢龍曰：少陰解于陽，非解于陰矣。

岐伯曰：天一生水，子時水生，即是王地，故少陰遇子而漸解也。

奢龍曰：少陽之解始于寅卯，少陰厥陰之解終于寅卯，又何也？

岐伯曰：寅爲生入之首，卯爲天地門戶，始于寅卯者，陽得初之氣也；終于寅卯者，陰得終
之氣也。

奢龍曰：三陽之時，王各王三時，三陰之時，王連王三時，又何也？

岐伯曰：陽行健，其道長，故各王其時。陰行鈍，其道促，故連王其時也。

奢龍曰：陽病解于夜半，陰病解于日中，豈陽解于陽，陰解于陰乎？

岐伯曰：夜半以前者陰也，夜半以後者陽也；日中以後者陰也，日中以前者陽也。陽病必于
陽王之時，先現解之機，至夜半而盡解也。陰病必于陰王之時，先現解之兆，至日中而盡解
也。雖陽解于陽，實陽得陰之氣也。雖陰解于陰，實陰得陽之氣也。此陽根陰、陰根陽之義
耳。

奢龍曰：善。

陳士铎曰：陽解于陰，陰解于陽，自有至義，非泛說也。

== 真假疑似篇

雷公問曰：病有真假，公言之矣。真中之假，假中之真，未言也。

岐伯曰：寒熱虛實盡之。

雷公曰：寒熱若何？

岐伯曰：寒乃假寒，熱乃真熱。内熱之極，外現假寒之象，此心火之亢也。火極似水，治以
寒則解矣。熱乃假熱，寒乃真寒，下寒之至，上發假熱之形，此腎火之微也，水極似火，治
以熱則解矣。

雷公曰：虛實若何？

岐伯曰：虛乃真虛，實乃假實。清肅之令不行，飲食難化，上越中滿，此脾胃假實，肺氣真
虛也。補虛則實消矣。實乃真實，虛乃假虛，疏洩之氣不通，風邪相侵，外發寒熱，此肺氣
假虛，肝氣真實也。治實則虛失矣。

雷公曰：盡此乎？

岐伯曰：未也，有時實時虛，時寒時熱，狀真非真，狀假非假，此陰陽之變，水火之絕也。

雷公曰：然則何以治之？

岐伯曰：治之早則生，治之遲則死。

雷公曰：將何法早治之？

岐伯曰：救胃腎之氣，則絕者不絕，變者不變也。

雷公曰：水火各有其假，而火尤難辨奈何？

岐伯曰：真火每現假寒，假火每現真熱。然辨之有法也，真熱者陽症也，真熱現假寒者，陽
症似陰也，此外寒内熱耳。真寒者陰症也，真寒現假熱者，陰症似陽也，此外熱内寒耳。

雷公曰：外寒内熱，外熱内寒，水火終何以辨之？

岐伯曰：外寒内熱者，真水之虧，邪氣之勝也。外熱内寒者，真火之虧，正氣之虛也。真水
真火，腎中水火也。腎火得腎水以相資，則火爲真火，熱爲真熱；腎火離腎水以相制，則火
爲假火，熱成假熱矣。辨真辨假，以外水試之，真熱得水則解，假熱得水則逆也。

雷公曰：治法若何？

岐伯曰：補其水則假火自解矣。

雷公曰：假熱之症，用熱劑而瘥者，何也？

岐伯曰：腎中之火喜陰水相濟，亦喜陰火相引，滋其水矣，用火引之，則假火易藏，非捨水
竟用火也。

雷公曰：請言治火之法。

岐伯曰：補真水則真火亦解也。雖然，治火又不可純補水也，祛熱于補水之中，則假破真現
矣。

雷公曰：善。

陳士铎曰：不悟真何知假，不悟假何知真。真假之間，亦水火之分也。識破水火之真假，則
真假何難辨哉。

== 從逆窺源篇

應龍問曰：病有真假，症有從逆，予知之矣。但何以辨其真假也？

岐伯曰：寒熱之症，氣順者多真，氣逆者多假。凡氣逆者皆假寒假熱也。知其假，無難治真
矣。

應龍曰：請問氣逆者何症也？

岐伯曰：真陰之虛也。

應龍曰：真陰之虛何遂成氣逆乎？

岐伯曰：真陰者，腎水也。腎水之中有火存焉，火得水而伏，火失水而飛，凡氣逆之症皆陰
水不能制陰火也。

應龍曰：予聞陰陽則兩相配也，未聞陰與陰而亦合也。

岐伯曰：人身之火不同，有陰火、陽火，陽火得陰水而制者，陰陽之順也。陰火得陰水而伏
者，陰陽之逆也。

應龍曰：陰陽逆矣，何以伏之？

岐伯曰：此五行之颠倒也。逆而伏者正，順而制之也。

應龍曰：此則龍之所不識也。

岐伯曰；腎有兩歧，水火藏其内，無火而水不生，無水而火不長，不可離也。火在水中，故
稱陰火，其實水火自分陰陽也。

應龍曰：陰火善逆，陰水亦易逆，何故？

岐伯曰：此正顯水火之不可離也。火離水而逆，水離火而亦逆也。

應龍曰：水火相離者，又何故歟？

岐伯曰：人節欲少而縱欲多，過洩其精則陰；水虧矣，水虧則火旺，水不能制火而火逆矣。

應龍曰：洩精損水，宜火旺不宜火衰也，何火有時而寒乎？

岐伯曰：火在水中，水洩而火亦洩也，洩久則陰火虧矣，火虧則水寒，火不能生水而水逆也。
故治氣逆者皆以補腎爲主，水虧致火逆者補腎則逆氣自安，火虧致水逆者補腎而逆氣亦安。

應龍曰：不足宜補，有余宜瀉，亦其常也，何治腎之水火不尚瀉尚補乎？

岐伯曰：腎中水火，各臟腑之所取資也，故可補不可瀉，而水尤不可瀉也。各臟腑有火無水，
皆腎水滋之，一瀉水則各臟腑立槁矣。氣逆之症，雖有水火之分，而水虧者多也，故水虧者
補水而火虧者亦必補水。蓋水旺則火衰，水生則火長也。

應龍曰：補水而火不衰，補水而水不長，又奈何？

岐伯曰；補水以衰火者，益水之藥宜重。補水以長火者，益水之藥宜輕也。

應龍曰：善。

陳士铎曰：人身之逆，全在腎水之不足。故補逆必須補水，水足而逆者不逆也。

== 移寒篇

應龍問曰：腎移寒于脾，脾移寒于肝，肝移寒于心，心移；寒于肺，肺移寒于腎，此五臟之
移寒也。脾移熱于肝，肝移熱于心，心移熱于肺，肺移熱于腎，腎移熱于脾，此五臟之移熱
也。五臟有寒熱之移，六腑有移熱無移寒何也？

岐伯曰：五臟之五行正也，六腑之五行副也。五臟受邪，獨當其勝，六腑受邪，分受其殃。
且臟腑之病，熱居什之八，寒居什之二也。寒易回陽，熱難生陰，故熱非一傳而可止，臟傳
未已，又傳諸腑，腑又相傳，寒則得溫而解，在臟有不再傳者，臟不遍傳，何至再傳于腑乎。
此六腑所以無移寒之證也。

應龍曰：寒不移于腑，獨不移于臟乎？

岐伯曰：寒入于腑而傳于腑，甚則傳于臟，此邪之自傳也，非移寒之謂也，

應龍曰：移之義若何？

岐伯曰：本經受寒，虛不能受，移之于他臟腑，此邪不欲去而去之，嫁其禍也。

應龍曰：善。

陳士铎曰：六腑有移熱而無移寒，以寒之不移也，獨說得妙，非無征之文。

== 寒熱舒肝篇

雷公問曰：病有寒熱，皆成于外邪乎？

岐伯曰：寒熱不盡由于外邪也。

雷公曰：斯何故歟？

岐伯曰：其故在肝，肝喜疏洩，不喜閉藏，肝氣郁而不宣，則膽氣亦随之而郁，膽木氣郁，
何以生心火乎。故心之氣亦郁也，心氣郁則火不遂，其炎上之性何以生脾胃之土乎。土無火
養，則土爲寒土，無發生之氣矣，肺金無土氣之生，則其金不剛，安有清肅之氣乎。木寡于
畏，反克脾胃之土，土欲發舒而不能，土木相刑，彼此相角，作寒作熱之病成矣。正未嘗有
外邪之干，乃五臟之郁氣自病，徒攻其寒而熱益盛，徒解其熱而寒益猛也。

雷公曰：合五臟以治之，何如？

岐伯曰：舒肝木之郁，諸郁盡舒矣。

陳士铎曰：五郁發寒熱，不止木郁也，而解郁之法獨贲于木，以木郁解而金土水火之郁盡
解，故解五郁惟尚解木郁也，不必逐經解之。

