= 如何分辨痛症
穆超
20170930

== 穆超

微信群里的各位前辈，各位老师，各位同道，大家晚上好。首先非常感谢大家牺牲宝贵的时
间来关注我们七针的微信课，那么也非常荣幸呢，和大家一起交流和分享自己临床上的一些
浅薄的经验和知识。本人学医尚浅，有不当之处，还望大家多提宝贵意见。

今天，主要是和大家分享临床上一些关于痛症的区别和分类。

大家都知道，在大多数患者的印象当中，针灸是可以治疗疼痛的。所以，针灸医生临床上碰
到的大多是疼痛类的一些患者。那么，在诊疗过程当中，正确地区分和判断患者的疼痛，是
内脏引起的，还是单纯的皮肉筋骨的疼痛，至关重要。只有正确地判断，才能为患者的诊疗
提供正确的方法。以此也可避免本不该发生的医疗事故和纠纷。为了更好地让大家能够理解，
我会引用一些常见的西医病名来解释，希望不会引起大家的一些误会。

关于疼痛到底如何区分內科——就是内脏——引起的疼痛，还是单纯的皮肉筋骨的疼痛呢？我大
体呢结了以下几点。

咱们就举例说明一下，从头到脚，然后具体地给大家区分一下。

首先来讲就是头部的一些疼痛。第一个，内脏引起的疼痛，大多比较剧烈，且同时伴随其他
的一些症状。比如说关于头痛里边，比如说恶心、意识的模糊障碍。腹痛里边，还有其他的
一些症状等等。那么患者能对疼痛的描述呢，一般的是剧痛，刀割样的疼痛或是烧灼样的疼
痛、钝痛、刺痛、跳痛、暴裂一样的疼痛，那么总体来说，内科引起的疼痛还是非常的剧烈。
那么皮肉筋骨引起的疼痛，一般比较单纯。患者的自述，也比较清晰，比如说是酸痛、胀痛，
或者是麻痛等等，同时也会伴有一定的功能障碍，比如说某一个动作会加重，不会很持续。

前几天我就接诊了这样一个患者。他来的时候就告诉我，他的胸部疼痛，尤其是在进食的时
候加重。通过我的一番查体……这是咱们的第一点，从疼痛的性质来区别，是内科还是外科
的疼痛。另外一点就是咱们常规治疗不缓解，疼痛不缓解或者是容易复发，那么我们要首先
要考虑是否是内科的疼痛。

怎么去治疗呢？其实咱们内经已经给出了答案。就是刚才我发的群里的那个话，病在肝，俞
在颈项；病在心，俞在胸胁。下面这一点是至关重要的，就是说咱们在接诊疼痛病人的时候，
我们首先要考虑它是否有内科的疼痛，是内脏引起的疼痛，这一点至关重要。这可以让大家
规避很多的风险。那么同理，比如说久治不愈的腰痛，有可能肾脏出了问题；久治不愈的肺
部疾病，久治不愈的肩背的疾病，也可能是肺出了问题。

我们通过调腰骨能不能调肾呢，能不能增加肾的功能呢？当然也可以。那么如何去诊察和判
断？当然咱们中医还有咱们中医的一些检查方法，比如说咱们的望闻问切，那么望闻问切，
这个大家一般通过症状、体型，通过他患者的自述，咱们也可以还能够诊断患者到底是内科
还是外科的疼痛。咱们还有一些中医特有的一些检查方法，比如说他的疼痛，并没有他表述
的那么明显。那么，这一点咱们怎么去判断它到底是内科的疼痛还是单纯皮肉筋骨的疼痛呢？

那么这一点，咱们可以通过两点。第一个就是通过查体，那么如何去查体，从哪个方面去查
体。第一个，咱们的背俞穴。内科的疼痛，一般都会在相对应的背俞穴或者募穴，会产生非
常明显的阳性反应点，那么我们通过调理堵塞的经络或者是病变的部位，然后来对五脏六腑
起到一个整体的调理作用。

那最后﹐非常感谢大家啊，牺牲宝贵的时间来关注我们七针的微信课。下面留出一些时间来
给大家提问。

比如说背俞穴上，如果查体的过程当中，查到这个背俞穴上有压痛，这个背俞穴的阳性点是
压痛，比其他的背俞穴压痛要更加明显。那么，这说明他的内脏有功能性的一些障碍。如果
有刺痛，比较明显的刺痛，或针刺样的疼痛，那说明他这个内科的病变，可能有些器质性的
病变。这是第一个，可以通过背俞穴和募穴来判断是否有内科的一些隐患。

那么第二一点，内经其实还提供一些非常详细的诊断方法。比如说，在《素问．金匮真言论》
里边说得非常地详细。病在肝，俞在颈项；那么病在心，俞在胸胁；病在肺，俞在肩背；那
么病在肾，俞在腰股；病在脾，俞在脊。

就说对于去治病，在调理的过程当中，一定要注意和患者进行心理的辅导和沟通，是至关重
要的。抑郁症到底怎么凋，内经里边其实也有。如果，我们第一条已经说了，如果他的疼痛
比较剧烈，首先我们要考虑是否有头部的一些器质性的病变。比如说脑膜炎、出血性的脑血
管疾病，比如说脑瘤、颅内血肿，dian xing xing的头痛等等，那么这些都可能会引起头痛。
首先要辨别这一点。那么这样的疼痛，一般会在患者的自述当中，会告诉你他的疼痛，如刀
割样、烧灼样刺痛、跳痛、胀痛还有爆裂的疼痛。

我说明这些的意思，并不是说针灸不能治疗。其实针灸，如果你是在医院里面的针灸科，咱
们完全有这个能力，可以去治疗。

提醒大家的就是当你判断他是器质性的病变、内科样的疼痛的时候，你的治疗，会不会引发
一系列的连锁反应，你能不能承受治疗预后的后果。这点事咱们是必须要考虑的。比如说因
为脑部出血性的疾病、或者是他有出血性的隐患，那么这一点，如果他来找你，可以通过一
些症状，可以提前预知，或者是预防或者是治疗。

你比如说，如果他头部有出血性的隐患，颅内压增高，那么他的症状非常的典型，就是一种
剧烈的头痛，或者是喷射性的呕吐。像这种情况，我们可以通过一系列的查体，可以判断她
是不是这样的疾病。比如说可以看他的百会。我们正常人的百会是凹陷的，如果他的百会凸
起，并且你能摸到百会的附近还有蛇果的波动感，这种就一定要提醒自己，患者有可能有脑
出血的隐患。

另外，还可以通过风府穴的紧硬程度，并且去看患者的舌头是否偏歪，舌下的瘀络是否饱胀、
比较明显。那么同时，患者可能伴有意识的障碍。比如去做一个指鼻子的试验，他可能非常
得缓慢，不能清晰地指到自己的鼻尖。然后可以做一个双手平衡的试验，如果他有脑部的积
患，不管他是脑部的肿瘤、囊肿还是出血还是栓塞，他都不能很好地去完成。这些都可以帮
助我们去诊断，也可以给患者做一个非常好的判断提醒，也避免了在诊疗过程当中的一些风
险。

刚才说的，只是头部的比较严重的隐患或者是疾病，大家一定要学会去规避这样的风险。

头部的这个疼痛当中比如说，面部的疼痛。面部的疼痛有少许的牙痛，是心脏引起的，这个
首先，尤其是老年人，他这个牙痛，首先要考虑他是不是有心脏的积患。大家都有这样一种
常识，就说在拔牙的过程当中，每个牙科医生都首先要问患者，是否有心脏病。还有一些牙
痛，其实是三叉神经痛。我就治疗过这样的一个患者。他就告诉我当时牙痛的时候他就去找
牙科医生，把牙拔掉一个，过段时间还痛，然后又去拔掉一个，直到把所有的牙都拔光了，
他才知道自己的疼痛并不是牙痛，而是三叉神经痛引起的。

所以说这样的医生，如果让患者碰见，那也是患者的悲哀。这里再声明一点，在咱们七针里
边，没有所谓的病名，也不能被患者的症状所困扰，我们只需要通过查体，解决他闭塞的经
络，或者是瘀堵的气血，给气血一个空间一个通道，他的病，症状都可以消除。

在这里只是提醒大家一点，就是在诊疗过程当中的风险。

再往下看胸部一些疼痛。胸部的一些疼痛，如果他的疼痛比较剧烈，或说是刺痛、灼痛，并
没有随着关节的活动有加剧的现象，首先要考虑是内科的一些疾病。

风险比较大的就是心绞痛引起的这种胸痛。心绞痛引起的心痛，比较好辨别。比如说他可能
同时伴有左肩的不适，左后肩胛骨的不适，他疼痛的时间不会很久，并且非常多的患者在夜
晚感觉会加重。

我见过很多这样的患者，他来的时候告诉我肩胛骨缝特别地难受，每到夜晚就加重。根据我
的经验和诊断的过程，我首先要考虑它是不是心脏引起的这种不适，只要是内科的疼痛，它
一般伴有一些其他的症状，比如说胸痛伴有咳嗽，可能是气管、支气管、胸膜里的疾病，这
是内科里边。如果有吞咽困难，他可能有食管类的疾病。非常严重的吞咽功能（障碍），大
家要考虑食道癌。我就悄悄地告诉他的家人，我说你到医院去做一个检查。那么经过检查的
结果，就是食道癌。

所以说大家在临床当中一定要去规避，多进行判断，就像警察破案一样，破案的过程当中，
诊断和思考是非常重要的。如果他的胸痛带有吐血，那么可能有肺结核、肺的梗塞，可能还
有原发性的肺癌，这些都要去考虑。如果是伴有呼吸困难，可能有些胸膜类的疾病，比如西
医所说的大叶性肺炎、自发性气胸等等。这些如果你诊断出来了，其实有些患者他并不知道
他自己的症状有多严重。这个时候，你可以让患者去做一个检查。

单纯的皮肉筋骨这种胸部的疼痛，它就没有这些类似的症状。同时伴有咳嗽，呼吸时候加重，
比如说咳血，比如呼吸困难、胸部的烧灼感，在呼吸的时候，会有一些刀割样的疼痛，单纯
的皮肉筋骨的毛病，它不会这还是伴随这些大的症状。

刚才讲的是头部的一些疼痛，还有胸部的一些疼痛。

背部的一些疼痛，首先要考虑第一个还是心脏，第二个胆囊，都会引起背部的疼痛。

腹部的疼痛临床就更比较多见。比如说上腹部的疼痛，上腹部的疼痛（需要）考虑的就比较
多。首先要考虑他的胃部。腹部类的疼痛，上腹部、左下腹、右下腹的疼痛，首先要考虑内
科的一些胆石症、胰腺炎、阑尾炎等等。还有一些，腹部的一些疼痛其实非常多，分类的标
准还是那样，如果他的疼痛，通过常规的治疗不缓解，并且他的疼痛的性质，是刀割、烧灼
样、钝痛、刺痛、跳痛，等等等等，比较剧烈、持续的痛，你首先要考虑是内科的病。

前段时间就治疗一个左腹部的疼痛，肚脐左上方的疼痛。这个疼痛，常规的进行治疗没有缓
解。我就让他去医院做个检查，他这个病就非常奇怪，可能很多人都没有听说过，是脾栓塞。
还有类似的，比如说左肩部的疼痛，那么有一个，这还是没有学七针之前，那时候不是很懂，
按肌肉解剖的一些理论去治疗，结果当时就缓解了，第二天又恢复原状，连治了三次以后，
我就让患者去做了个检查。检查的结果就是心肌梗塞。

刚才说的这些内科的疼痛，如果他的症状不是很明显，就是说，你能判断它（不）是内科的
疾病，那么它不会引起一些大的隐患。出现一些急性的突发现象的话，如果来找你治疗，咱
们可不可以去治疗，当然可以。

前段时间，我就接诊了一个外地的一个患者，他在电话里就告诉我，他就是一个单纯的颈椎
痛，天天晚上痛得睡不着觉。然后他来了以后，尽管我的第一个感觉，我看他的面色发黑，
面如漆柴，我第一个感觉他这个毛病，可能不是一个非常轻的病。通过我的查体，我就把他
的家属叫到了一边，（问）他有没有做过肝脏的检查，患者的家属就告诉我，这个患者是肝
癌晚期。这就应了咱们内经的那句话，就是病在肝，俞在颈项。

在这里我也提醒大家，就是如果有些久治不愈的一些颈椎病，有可能也是肝脏出了问题。

内经里给出的这句话，其实就告诉了咱们几点。第一点，我们通过他的症状可以判断他的病
位，就是病在哪一个脏腑。这是第一点。第二一点，我们也可以通过他外在的表现，比如说
我们通过调颈椎，能不能调肝呢？当然可以。那么我们通过调肩背，能不能治肺呢？当然也
可以。通过这句话，我们不光可以判断，不光可以诊断，也可以进行很好地治疗。当然只通
过这一点，是不能完全达到非常满意的效果的，我们可以通过十二经，通过背俞穴、募穴综
合来调理。这是调理内科的疾病。

再比如病在心，俞在胸胁。我们可以通过对胸胁部位的扎针，也可以调理心脏的一些疾病。
我经常在胸部肾经的走行上，比如神风、神堂等等这些穴位，如果出现了非常明显的阳性反
应点，那么在这里进行针刺，他的心脏病就会得到很大程度的一个缓解。

再比如，病在脾，俞在脊，这就让我们想起了一种病，比如说强直性脊椎炎，我们通过对肝
肾的调理以后，重点在脾胃上做文章，会对强直性脊柱炎的康复，有非常好的预后效果。

还有病在肺，俞在肩背。它说的是肩背的哪一个位置呢？通过临床上的一些摸索一些经验，
我们知道，它一般就是在大椎穴的三角区域。在传统针灸中，有一个定喘穴就是在那个三角
区的范围之内。我们通过对背部大椎、胸三椎、胸四椎的一些调理，可以对肺部的一些积患，
起到一个非常好的调理作用。

今天晚上讲课的一个主题，在这里我再给大家梳理一下。我们今天晚上分享这个微信课的目
的，就是提醒咱们针灸医生，在临床当中，对于内科疾病和单纯的皮肉筋骨的毛病的分类和
辨别，可以最大程度地减少患者（病痛），正确的治疗方法，还有规避临床当中的一些风险。
当然内科的一些疾病，在临床上的症状是非常多的，那么这些我们不需要去管它，如果你去
管那么多，纷纷繁复杂的症状，你又会走进一个误区，被患者牵着鼻子走，被症状牵着鼻子
走。七针治病的一个思路就是，我们眼里边没有病名，没有症状，只关注他的气血运行的通
道，是否受到阻碍。

因为我在临床当中碰见了一些内科病，通过一些判断，减少了患者的一些就诊的时间，也给
患者对自己的病情来有一个清晰的把握和认识。减少了不必要的纠纷，这就是今天微课的意
义所在。

== 问题

李洪峰：痛从上下者，先刺其下以过之，后刺其上以脫之。痛从下上者，先刺其上以过之，后刺其下以脫之。分享一下您的理解。::

李老师你好，你提的这个问题非常的尖锐，为什么？这是我们七针培训课里面的内容。刚开
始的七针理论里面，这是一个核心的内容，就是上下游理论。首先一点，我们先理解一下，
痛从上下，这个上下指的是什么？其实，读内经一定要会读，当你不知道这句话的意思的时
候，你一定要去往下看，先把它略过。就像师父讲的，先暂且按下不表。
+
这个上下到底指的是什么呢？你提的这句话，是《灵枢．周痹篇第二十七》，那么这段话的
下面还有一句话，是这样说的，故刺痹者﹐必先切循其下之六经，视其虚实及大络之血结而
不通，及虚而脉陷空者而调之。
+
通过这句话，我们就知道这个上下指的是什么，就是说，上指的是手之六经，下指的是腿的
六经。你知道了上下，就可以去判断是先刺上还是先刺下。刺上是刺哪里，就是刺手之六经，
下就是刺脚的六经。具体应该怎么去刺，首先一点，就是痛从上下者，这个痛是从上引起的，
那么我们要先刺下。打一个比方，比如说偏头痛，我们可能不要去管它的局部，我们就可以
在下肢六经的环跳上扎一针，有可能他的头痛就缓解，甚至是消失了。

四安阁：风府穴处坚硬是什么样的一种情形，发硬，不知道疼也在其列吗？::

网名是四安阁的这个老师，你好，风府穴处的坚硬是什么样子，这个其实你摸到这样的病人
就知道了。你按压的时候不知道疼，也是坚硬的一种。风府穴这个地方是非常柔软的，有些
鹅脑部的症状的，比如说血压高的人，比如说脑部有积患的，他的风府穴是非常硬的。这个
风府穴在内经里面说得非常明白，风府穴是卫气大会的地方，那么这个地方如果紧硬了，卫
气就无法更好地输布，不能更好地出，也不能更好地入。

东风生于春，病在肝，俞在颈项；南风生于夏，病在心，俞在胸胁；西风生于秋，病在肺，俞在肩背；北风生于冬，病在肾，俞在腰股；中央为土，病在脾，俞在脊。请问老师，这个古人是根据什么得出的人体规律。::

再回答第三个问题，为什么病在肝俞在颈项。其实这点中医说得非常明白。因为病在肝，那
么它主风，风善袭阳位，颈项又是人体的最高处。所以说当你的肝脏有问题的时候，它对应
的是风。那么颈项的部位，它会有症状。

请问强直性脊柱炎补肝肾后，具体如何从脾胃调理？::

因为大家没有学过七针呢，我只能从传统针灸上给大家讲一下。比如说强直性脊柱炎的患者，
调补脾胃的时候，可以用咱们经常用的老十针来调理，这个效果是非常好的。

感谢老师的微课，中医上有中央有病调四末，双上肢无力，调哪里呢？::

这句话你可以反着来调嘛，比如说中央有病，我们可以调四末，那么四末有病，我们可以调
中央。所以说双上肢无力，我们可以在脾胃上做文章，可以调中焦。

感谢穆老师，临床变化多端，治疗过程中担心引发更多的疼痛，诊察的水平又不够时，有什么要注意的原则可以参照吗？::

这个原则，我们立新师父讲得其实非常地明白。他用了几个字，第一个就是我们在扎针的过
程当中要：宁轻勿重，宁浅勿深，宁慢勿快，这十二个字。

会说话的猫：谢谢老师！请问三叉神经的牙痛和真牙齿痛怎么区别？::

网名是会说话的猫啊，这位老师你好。这个其实非常好区别，三叉神经痛的牙痛，它的疼痛
一般是在刷牙洗脸的时候触发，它有一个出发点。真牙痛它可能就不分时间，就是持续的一
直刺痛。

邪客于臂掌之间，不可得屈。刺其踝后，先以指按之痛，乃刺之。以月死生为数，月生一日一痏，二日二痏，十五日十五痏，十六日十四痏。一个病人手腕疼，用此方法并没有好，病人本身有抑郁症，该从哪方面入手。::

你说的这个方法，是内经提的方法，在内经里边提了很多这样的方法，比如说口干如角? 刺
足少阴。比如说膝中痛用圆利针，针尖如氂，刺膝无疑。其实内经提出了这些方法，大家一
定要注意，这只是一个病案的记录，而不是所有的病都这么治。
+
打一个具体的比方，就比如膝中痛，而员利针，针尖如氂刺膝无疑，那么膝中痛员利针直接
刺犊鼻，能不能刺得好？有的人能刺得好，但是大多数人是不行的，就算内经里边类似于这
样的记载，这都是一些病历记录，不是一个通用的方法。
+
师父一直在讲，如果一个患者本身有抑郁症的人，那么有抑郁症，焦虑症的这种患者情志病
是最难调的。我经常给大家打一个比方，如果这个人炒股，赔了五十万，天天睡不好觉，失
眠健忘烦躁，那么治疗这种病最好的办法，就是给他五十万。可能他的失眠就马上就好了。

程：老师请问癫痫怎么调理？::

癫痫的调理，首先要去判断，癫痫是外伤引起的还是情志引起的，还是本身原发性的。如果
是外伤引起的，我就治过一个就是手术后遗症的癫痫，这种还可治一些。原发性的其实更简
单一些。看这个癫痫能不能治疗，咱们有个判断的方法。第一个，看他的眼睛，你看他眼睛
的上方如果有三条红血丝，那么这种人是可以治的，在眼球的下方啊，就是黑眼珠的下方，
在白睛上，如果在下方有三条红血丝，也是可以治的，如果上下方都有，那么这种癫痫病人
是非常难以治疗的。
+
那么癫痫到底怎么治，内经上也有记载，一般的癫痫，我们都是通过，按卫气循行理论来讲，
癫痫都是因为卫气的回路受阻啊，就是说卫气不能很好地通过脊髓回到髓海，髓海不足才会
引起的癫痫。我们只需要把卫气回流的通道给它打开就可以了。重点就是在骶髂，督脉上做
文章。

阿寶：穆师兄，怎么拿捏“久治”这个度？::

根据不同的医生。我是怎么把握的呢？我一般都是三到五次。每一个患者来了以后，我都给
提前给他说明白，我说你这个疼痛，你这个病，如果三次或者是五次治疗，没有得到非常好
的缓解，我建议你另请高明。

会说话的猫：我遇两个诊断为干燥综合症病人，以口鼻干燥为主，喝水不能缓解，舌质有深浅不一的裂纹。针刺七天无效，可能我的法不对症，请老师赐教。::

你们提的问题都非常的尖锐，非常的有深度，这都是一些七针的大实货。其实你学了七针就
明白了。你既然提了，我就简单地回复你一下。
+
首先你把握一点，干燥，它就告诉你了，这个病是干燥，那么干燥，我们让它湿润就可以了。
怎么让它湿润，内经说得非常明白，大肠主津，小肠主液，所以你调大小肠就可以了。所以
说你的目的就是让他拉，让他泻，这个泻法可以通过调理大肠经、小肠经、脾胃经，然后增
加他的肠子蠕动，让他泻下来，你会发现他越泻越舒服，他越泻口里的津液越多。一般的病
人，如果拉肚子的话，他会越拉口中越干，那么干燥综合征的人，恰恰相反，他越拉口里边
的唾液会越多。

老师:中焦虚寒便溏，过敏性算炎，清涕，喷涕不断，鼻鼽便溏，现肩胛冷痛，紧。已灸至阳、身柱各半小时，但过了两小时，肩胛骨又冷痛。这个怎么处理？::

这个处理的方法，其实通过他的症状来讲，我们就知道它就是一个阳不足。你光灸后边也不
行。你想一次就见效，有的患者是急不来的。这个患者，第一个，其实很多的患者都明白一
句话，叫做病人不忌口，坏了大夫手。咱们医生，不是神医，患者是否遵医嘱，这个至关重
要，所以说第一个让患者戒掉一切寒凉，这是第一个。第二一个，你光灸背部，这样不够。
第二一个你你的时间也不够。那么还可以灸哪？灸腹部、灸肚脐的周围，然后时间要加长。

情志病，魂神意魄志的问题，可以针刺吗？灵枢本神篇说不可刺::

大家一定记住，大家读书的时候一定要知道古人的意图，古人说不可刺，并不是说一定不可
刺，而是说什么呢？针刺有风险。内经还说背俞穴不可刺，但是可以刺吗？可以。怎么刺？
浅刺，用鑱针去浅刺。
+
魂神意魄志问题归根结底还是什么，还是五臟的问题，因为肝藏魂，心藏神，脾藏意，肺藏
魄，肾藏志，那么这些情志病，其实归根结底还是五臟问题。调理五脏就可以了，五脏怎么
调，刚才已经讲过了。

== 陈立新

各位朋友大家好，晚上好。首先非常感谢穆超，给大家这样一个分享。有机会这样一个分享，
也是我们立新七针希望能做的一些事情。那么立新七针从创立到现在，一路走下来，跟我们
很多的网友，我们很多的支持者对我们的这个鼓励支持关心，是分不开的。在这里，我首先
对朋友们表示一个衷心的一个感谢。同时也是国庆中秋的来临，在这里，提前预祝大家国庆
节，中秋节快乐。

刚刚打开听了一下穆超给大家的分享，非常精彩，非常不错。同时我也看到一些朋友的一些
提问，其实大家这样子一个提问的话，我相信给穆超两天的时间，一个礼拜的时间，大家会
有永无止境的一个提问，为什么？其实这个就是我一直以来，我的一个观念，就是我们中医
进入了一个经验这样一个怪圈。中医已经成了一个经验医学，那么这个也是我一直在倡导提
倡，希望我们能够回到一个规律医学上。如果大家回到规律医学上去之后，就没有这么多的
疑问，就不会为这些小小的一症状或者某一病名牵着走。

但是要回到这个规律医学，你一定是要知道天文地理人事，也就是内经所讲的这个知道者。
所谓道，就是你能够了解这个道，那么一定是上知天文，下知地理，中通人事。一定是这样
一个立体的，我们人生活在自然界里面，首先离不开这个天，离不开这个地。我们会呼吸天
气，我们同时会接受这个地气对人的濡养，那么天地之气对人的影响，同时人自己对自己的
影响，环境对人的影响，比如我们的饮食，我们的生活起居七情六欲，这些对人的影响。那
么在这样一个比较复杂非常复杂的一个环境里面，人免不了会生病，那么怎样去防止这样子
的一些状况，或者怎样治疗这些疾病。

我们非常庆幸非常荣幸地能够接触到内经，能够了解到内经，也是老祖宗他们当年上古时候
远古时候，所观察到的所领悟到的自然对人体的一些影响，这些宝贵的一些认识思想，把它
们记录下来，传播了下来，那么在内经这样一本书传承下来，让我们在几千年以后，到今天
我们可以走一个捷径。

我经常会在看内经或者在解读内经的时候，心里面忍不住会对我们的祖先产生一种敬仰。对
我们的传统文化，对我们的祖国产生一种热爱，就是因为这个认知让我们产生不可抑制地这
样一个冲动。这个冲动其实是发自内心的，说它是冲动，就是因为有这个能量，所以会让我
们冲动。所以大家可以看到我，这么多年来一直在网络上，我会非常地关注，所有我们的同
学，我们的这些朋友，禁止大家去攻击我们的祖国，或者是糟塌我们的传统民族文化这样一
些东西，那么光是我们说有一个敬仰的心还是不够的。

内经医学这本书它其实是一个经典，有人说它是一本天书，因为看不懂啊，那么也有人讲这
个是神人所传，包括经络来讲，有人就是说通过内观，等等很多说法。事实上如果大家都从
天地自然这个角度去理解这些，你会发现其实它不是天书。古时候，我们说上古时候或者中
古时候，这些人其实他也是一个凡人，也是跟我们一样有七情六欲，两个耳朵一个嘴巴，两
个鼻孔一个鼻子，一张嘴，这都是这样一个凡人，但是所不同的就是思想，所以人与人之间
其实说有什么不同的，就在于思想和认知上面。你是外星人，也是一样的。

但是他为什么他具有这个创造力，为什么他具有这个破坏力，为什么他能够影响一方甚至影
响全世界，影响全人类？那就是因为他的思想，这个也是。

我们这些年一直在倡导，就是希望大家能够引起重视啊，就是你不要仅仅就是一些经验上打
转转，我们中医为什么有的时候人家会讲不科学，我们也看到在网络上有很多的一些名医，
经常在网上发一些关于他们认为的真相的一些东西，比如说什么季节来了，不能吃什么东西，
不能做什么，这不能做，那不能吃。但事实上，如果你从自然社会，天地自然，这个角度去
理解的话，我们说天垂象，地成形，那么实际上地上的五方，各有春夏秋冬，以中国来讲的
话，就是一年四季它都存在春夏秋冬的。古人就讲到一日分为四时，一日分为四时的话，人
也有阴阳二十五型。那么就是其实就是人和地天，都有不同的这样一个时间和空间的表现。
这个时空的表现，就是决定了我们在某一个状态的时候，某一个时间某一个空间的时候，如
果用坐标线来表示的话，就是时空的一个相交点，我们人在那个时候，可能就最好，可能会
最差，就会有这样子的一些表现。就是天和地，这样一个规律，然后人相应了就好过。那么
不相应，就是天地人不相合不相应的时候，就是难过或者就不能过。

那么我们怎么样去知道这个，就可以找到一条解决病痛解决疾病的这样一条路，一条捷径。
而不是说我们在一些经验，就是我在某一个地区或者某一个局部的一个范围，我积累的一些
认知，一些经验或者一些秘方一些招数，这个不是真正的中医。他应该不能代表我们的中医，
当然他也可以号称中医，但是不能代表中医，就好像刚刚所说的，你说西瓜不能吃，对不对？
有人就讲了这个水果不能吃，如果你水果吃太多会怎么怎么样，但是你千万别忘了，其实人
分阴阳二十五型。那么这个你不能吃，他不能吃吗？我不能吃吗，对不对，你可能吃一片西
瓜里就拉肚子了，那么我吃一个西瓜，我吃了也没事的。因为人跟人不一样。而且在东南西
北中，你说你这边不能吃，你在北方你不能吃，那么我到南方能不能吃呢，对不对？同样是
这个季节，你不能吃我也不能吃吗？

我们中医一定不能走在这样一个狭隘的认知里面去，回归到自然规律条路上来，我们就知道
一个对应法，对于九针来讲，一到九支针，那我们有大中小型号，这里面其实一排列组合下
来的话就，可以说这是几十万种排列组合。无论你多复杂，我可以用这么简单的就是这几支
针，就可以对应多复杂的，但是如何去对应这个复杂，那首先就是第一，你要对这个人体有
所了解，它有些什么规律，然后你要对这个世界，天有些什么规律，地有些什么规律。你要
对它们有所了解，然后才谈得上真正的这个天地人相合，它怎么去合，怎样一种方式去合。
不是说仅仅地扎几个穴位，在哪里取什么经络，取什么穴位，什么时间扎什么，这个其实就
是基础的一个认知。这种情况下，所谓的这个天人合一，其实并不是真正的天人合一。真正
的天人合一，你一定就是要去理解这个河图洛书，在内经里面，很显然它是有河图洛书的影
子。九宫就是很清晰的洛书的一个展示。

那么实际上它跟经络有什么关系，跟九针有什么关系，那里面关系其实非常多非常深，但这
个不是说几句话能解释说清楚的。如果说这些，可能因为对于我们的粉丝群来讲，可能相对
地显得好像是有点深奥，因为大家没有系统地学习这样一个过程，可能一下子你讲这个，不
知道你在讲什么。但是我想表达的就是说希望，而无论你是我的学员，或者你是中医爱好者
或者是你热爱中医，你学不学立新七针都不重要，重要的就是说我希望大家能够真正的对内
经有个认知，就是一定要回归到自然。一定要回归到天地自然里面去理解内经，而不是去死
守内经这本书，或者看古人谁谁谁注解的內经。他注解的，其实我们看到很多的名医很多名
人注解的内经，其实我们从天地自然这个角度去看，真的是很荒谬的。但是我们不能去说，
有些人已经死掉了，对我们不能去批判他。

我们是怎样去修正这个，我们中医里面的一些可能不足的或者有些偏谬的。同时，我们自己
的认知是否也带有偏谬。所以这样就是我们要做的事情还非常多，我们不要去说这个中医哪
里不好，或者西医哪里不好，其实中医西医都好，那么你说民间的中医不好或者有些庸医不
好，其实大家都好，应该说每一个医生，哪怕他是一个庸医，或者骗了人，从他的本意来讲
的话，可能他应该都不会骗人。人生下来不会是一个骗子，都是这样，可能因为环境，可能
是因为自己的一些，叫做什么呢？就是被迫的，或者是无奈的，可能去做到这些，或者他认
知只有这么高，那么他做了一些，就是比如我们讲的，这个叫做愚昧的善良，这样的发心，
那他只有这么一个认知，他用了这样一个方式方法去帮助人，他也想帮助人，结果反而害了
人。

所有的这一切，你要怎么去解决，就只有提高自己的认知，这些认知在书上是很难提升到的。
你在哪一个老师那里去也很难学，在我这边的一些学员，他们为什么能够接受七针，而且对
七针抱有这么高的一个认可度。其实就是我一直希望大家能够融入自然，回归到天地自然里
面去，而把这些规律，里面的这些道理都明白了之后，其实你根本就不会去纠结于某一个症
状该怎么治疗，然后它有些什么现象，然后我又该怎么去治疗，一个病名这些都不是真相。

人就是这样，他有一个基本的一个规律，对不对？然后这个规律，然后血气在濡养，所有人
离不开这个，那我们抓住这个规律，让你的气血去濡养它，就可以解决相应的很多问题。这
些问题可能就是因为阴阳的失和。我们都说阴阳的失衡，并不是说阴阳一样的大小，或者一
样的重。很显然在人体里面的这个阳，是远远大于这个阴的。有的人在讲到说好像是现代人
是阳虚，其实往往很多时候，就是在五脏的阴阳不平衡。这个阴阳平衡打破了，或者是经脉
的阴阳平衡打破了，但打破的原因，大部分的一个原因，只要是个痹，这个痹恰恰就是我们
内经九针最擅长解决的，把这个解决了，那么毫针去调就非常快，疗效非常快，而且远期效
果是非常稳定。在这一切之前，一定要有一个规律的认知，然后你才可以做到一个非常安全
的一个疗效，很神效的一个展示。

所认我看到有些朋友不断地在提一些病名一些症状，这个严格地讲，你要是问我我也没办法
给你解答。但是这个病到这里来的时候，我接手的时候，我要去给他治疗，我就有办法。为
什么相信你们，如果说真正回到内经医学高度上来的时候，你去了解天地自然这些规律，你
自然就知道，就是比如我今天在讲课的时候讲到这个，我们在生活当中我们要去做一件事情
的时候，首先我们要知道去找一个官，对不对？这个关键主管的部门领导，我们为什么去找
他？你不是说找直接找这个办事员，没用的，他就告诉你，我们有规矩，我们有法规，就是
这样子的，一句话就把你塞回去了。稍微有点头脑的人就知道不去找他，找他没用的，他直
接去找主管部门，找领导直接找不行的，可以间接地找朋友这样最后去找，把这个事情解决。

那么我们在治疗一些疾病，都是你不要仅仅是为这些病名或者这个症状约束到，你套在这里
面的话，你出不来。你要在这里面你要去做什么，它跟什么有关系。

比如说今天晚上穆超讲到这个病在脾，俞在脊。那么俞在脊，因为同时，前天群里有一个同
学问我，脊柱侧弯，小孩子，十二岁，怎么去调理。病在脾，俞在脊，如果你仅仅在脊柱上
这样去治疗的时候，可能是微乎其微的一个疗效，或者你好不容易把他弄正了之后，那过几
天又歪了，为什么？因为你没有解决他的根本。根本在哪里？根本在脾上，但是是不是脾就
一定有问题了，不是的，就不一定的。因为我们一定不要忘了这个脾跟心肝肺肾，还有关，
这五脏里面，它只是其中之一，它在中间，它灌四旁，那么它对心肺肝肾，它都要负责，那
么这四者里面如果说有阴阳的不平衡，那么就会导致这个脾左右上下的一个不平衡，就会导
致它这边弱那边强，或者是虚和实就出来了。那一出来的时候，如果左边虚，右边实，有可
能就会朝右边弯，有可能朝左边弯。那在五脏里面的话也是这样子，为什么脊柱会向一边侧
弯，像一个 S 形，而不是是一个问号形呢？因为就是跟五脏是有关的。

这是我举例，举个例子，就是说明我们一个理解，我们的一种思维方式。
 
继续这个问题，就是说我们真要去解决这个脊柱的问题，当然脊柱侧弯只是一个代表，那你
相应的其他问题，还可能是这个什么肠胃的问题呀，也可能是腰痛的问题，也可能心肺的问
题啊，也可能肝肾这些的问题。其实都是这样一个理。明白这个道理的时候，你就有相应的
办法出来，那比如说这个脊柱侧弯了，那我首先检查，是脾本身引起的呢？还是其他四脏影
响脾脏。这里面到底是这个气，所影响的还是血所影响的，因为我们五脏，这背后就有个营
血而卫气。那么在这个后面营血和卫气，到底经脉是阴经阳经，或者是阴阳上下左右前后所
影响到的，它到底属于痹证所致，还是这个气血本身的不足，它不足的原因是什么，是内因
呢，还是外因呢，对不对？那么环境所致呢？

就是说其实中医它要治病，涉及到相应的知识和认知是非常全面，非常广阔的。这说起来就
非常复杂。但是我们一定就是要从一个简单的认知，开始进入到非常复杂里面去之后，我们
再跳出来。这个时候你就会看非常复杂的东西，在这里可以直接地一眼看到真相，可以直接
就变得非常简单，学中医的过程就是说从简单到复杂，复杂得不得了，然后它再出来就变成
了一个简单，但是你这个时候的简单的是有认知的简单，你知道而简单，跟以前那种不知道
的一个简单，是两种境界。

所以我们应该说，中医应该从经验的这个怪圈里面跳出来，回归到规律医学，经验重不重要，
当然它也重要，重要就是我们首先在明白这一规律的前提之下，去运用这些经验，那么你就
可以说有很高的一个效率。其实这些经验的话，根本就不需要你去把它记载下来。就比如说
我们在中医的名著里面，大家应该知道内经里面其实中药方子只有十几个，应该是十三个吧。
那在张仲景的话，他那个方子，其实就是一二百个，那到了唐代的时候就几千个了，五六千
个。到那个明代的时候，我们知道那个叫普济方，这个上面是六万多，六万多首方。中医越
来越变得纷繁复杂，所以非常多的方不断地增加，你在一个地方就有不断的经验，不同的人
来了又有不同的经验，那么十几亿中国人的话，你可能接受这十几个人治疗之后，你就会有
十几亿的这个经验出来。那么谁来记录这些东西，记录下来又有什么意义，对不对？到最后
来讲的话，我们去按图索骥，或者按着这个方子去治病，很难治好，那么治愈率是非常低的。

但回规律医学，也许我不需要拘泥这些经验，我不需要掌握你这些方法，我自己明白这个道
理，明白这一规律，比如说我在东方，我在西方，我在南方，我在北方，我在中原。那么我
都有当地的天地人的结合，根据当地的时间、空间，然后在这里面去拿出我们治疗的方法。
在这里面，我们知道了这气是怎么走的，血是怎么走的，和它有些什么规律。然后这些规律
跟脏器五脏六腑有什么关系，跟情志又有什么关系，跟外界的六气又有什么关系。你把这些
结合起来，找到这么一个精确的点，那么你的疗效，其实就可以达到很高的。而且你在这里
面你自然就知道了，你在摸索这个自然规律，在这个过程当中，你自然就知道，哪些事情能
做，哪些事情不能做。那么其实在这里面，我们的医疗行为是可以做到非常安全，非常高的
这么一个安全程度。

不知不觉讲了满多了，由于时间的关系，我还要忙一点别的事情，因为这几天我一直在培训
讲课，那么一会儿还得早点休息，前两天没休息好，这个今天精神状态也不是太好。那么下
次有机会的时候再跟大家分享，希望我们更多七针的新老学员，还有我们讲师团其他的讲师，
有机会、有时间的时候呢，都给大家做分享。就像我们在做义诊一样，现在我们在重庆就是
十几个单位，我们都有联系做义诊、包括一些寺庙。实实在在就是要把这个疗效来展示出去，
给市民受益。你可能就是说有些人他经济比较困难，比较差，那我们可以用一种义诊的方式
来服务他们。

同时我们在重庆这边我们已经跟政府这边了，我们有联络，通过政府允许我们做了一个义诊
队伍，这是我们的政府支持的，给了我们这样一个文件，那么我们做这个应该是说在民间的
组织，在重庆的话算是第一家。未来我们可以去做很多的议诊活动，包括到农村去帮助一些
贫困的患者。当然，这也是需要我们七针的学员、我们七针的讲师、我们的医生大力的支持，
可是也希望我们的粉丝，我们网络上的一些支持者，立新七针的朋友，大力地支持我们。

我还有一个事情，那就是我希望给大家知会一下，就是我们立新七针有一个门户网站，我一
直以来就非常希望建论坛，这个论坛，大家在里面能够自由地交流，各抒己见。并不是说里
面就限于我们讲七针怎么样，你可以质疑七针的一些理论，都可以，大家在里面交流，但是
只要不涉及到攻击对方，攻击人身或者涉及到政府啊，我们的国家民族的这样一些反动的言
论，我们都是欢迎大家。

希望大家能够多多支持我们的网站，支持七针对内经医学弘扬的工作。谢谢！
