= 经脉——援物比类
冰台
2016-7-14 00:00

要理解经脉，先得了解中医的“援物比类”。

在古老的《易经系辞》有这样一段记载：“古者包牺氏之王天下也，仰则观象于天，俯则观
法于地，观鸟兽之文与地之宜，近取诸身，远取诸物，于是始作八卦，以通神明之德，以类
万物之情。”意思是说:远古时伏羲治理天下，仰望天上日月星辰，俯视大地山川形势，观
察鸟兽的皮毛文采和山岭泽壑的轮廓走向，近的就取象于己身，远的就取象于百足，于是画
出了八卦。并用它来再次领悟自然规律，以及人类社会现象，以这种援物比类的方式，去总
结天地之间万事万物的情状，以此沟通自然世界。在《黄帝内经》里，“比类”一词，比较
集中在《素问·示从容论》、《素问·疏五过论》、《素问·徵四失论》等数篇文章里面:

《素问·示从容论》::
* 受术诵书者，若览观杂学，及于比类，通合道理，为余言子所长。
* 臣请诵经脉上下篇，甚众多矣，别异比类，犹未能以十全，又安足以明之。
* 脉浮而弦，切之石坚，不知其解，复问所以三藏者，以知其比类也。
* 夫圣人之治病，循法守度，援物比类，化之冥冥，循上及下，何必守经。
* 不引比类，是知不明也。

《素问·疏五过论》::
* 臣年幼小，蒙愚以惑，不闻五过与四德，比类形名，虚引其经，心无所对。
* 善为脉者，必以比类奇恒，从容知之。

《素问·徵四失论》::
* 不适贫富贵贱之居，坐之薄厚，形之寒温，不适饮食之宜，不别人之勇怯，不知比类，足
以自乱，不足以自明，此治之三失也。

援物比类的思维方式，需要我们真正的融入自然才能够做到，也就是把人与自然融为一体。
作为一个明“道”的人，应该是如《素问·气交变大论》所说:“夫道者，上知天文，下知地
理，中知人事，可以长久。”这样的人，可谓是学识渊博，见多识广，而且善于举一反三，
如《素问·举痛论》所说:“善言天者，必有验于人。善言古者，必有合于今。善言人者，必
有验于己。如此则道不惑而要数极，所谓明也。”

在《灵枢·邪客》里，这样形容人与自然的关系:“天圆地方，人头圆足方以应之。天有日月，
人有两目。地有九州，人有九窍。天有风雨，人有喜怒。天有雷电，人有声音。天有四时，
人有四肢。天有五音，人有五脏。天有六律，人有六腑。天有冬夏，人有寒热。天有十日，
人有手十指。辰有十二，人有足十指，茎垂以应之，女子不足二节，以抱人形。天有阴阳，
人有夫妻。岁有三百六十五日，人有三百六十五节。地有高山，人有肩膝。地有深谷，人有
腋腘。地有十二经水，人有十二经脉。地有泉脉，人有卫气。地有草蓂，人有毫毛。天有昼
夜，人有卧起。天有列星，人有牙齿。地有小山，人有小节。地有山石，人有高骨。地有林
木，人有募筋。地有聚邑，人有䐃肉。岁有十二月，人有十二节。地有四时不生草，人有无
子。此人与天地相应者也。”

其中讲到“地有山石，人有高骨。地有林木，人有募筋。地有聚邑，人有䐃肉”，古人是将
自然界的石头比喻作人体的骨头，树木比作人体的筋，土地比喻成人体肌肉。人生存在这个
世界上，地球空间就是一个大自然，而人体内部就是一个小自然，这就是天和地的印象表现
形式，也就是常说的大宇宙和小宇宙的关系。

所以在内经医学的眼里，人体就类似于一个地球，与自然相应，与天地相合。人生活在大自
然里，人体规律也应该与自然规律相应相合，这就是内经所言“法天则地”、“援物比类”、
“和于四时”。我们把人体横截面来看，就可得知，人体构造与地球的构造非常类似，现代
科学研究证明，水占人体比重的70%，而水面积也占地球的71%。人的皮肤就类似地壳，人的
脊椎中心就类似地球的内核。地球上有高山河流、森林土壤、春夏秋冬的不同，刮风下雨、
地震洪灾等现象的发生，人体也是顺应自然界的，有骨骼气血、肤发肌肉、喜怒哀乐的表现，
也有生气哭泣、外伤劳损等表现。

《素问·离合真邪论》曰:“夫圣人之起度数，必应于天地。故天有宿度，地有经水，人有经
脉。天地温和，则经水安静。天寒地冻，则经水凝泣。天暑地热，则经水沸溢，卒风暴起，
则经水波涌而陇起。夫邪之入于脉也，寒则血凝泣，暑则气淖泽，虚邪因而入客，亦如经水
之得风也，经之动脉，其至也，亦时陇起，其行于脉中，循循然”。由此看出，古人是把人
体和天地自然看成一个整体，以“少阳、太阳、阳明、少阴、太阴、厥阴”这些路线为
“经”，对人体和天地自然进行对比研究。

所以光把人看做地球还不行，还必须融入自然环境来看。因为自然宇宙是这个整体，太阳月
亮，天空大地，森林大海，高山平原，这个整体是不能分开的。没有高山，也就显不出什么
是平原，没有天，也就显不出地，没有太阳的对称，月亮也就不成为月亮，离开了谁都不能
成为一个整体。人也是一个整体，没有任何器官和部位是完全独立来起作用的，都是相互相
存，而且这个整体还包括了天地自然在内，因为人类从未也不可能脱离天地自然而单独存活。
所以治疗也应该从整体宏观到局部微观，再由局部到整体这样一个反复循环的一个思考过程
来分析。
