= 经脉——线条非线条
冰台
2016-7-27 00:00

《灵枢·经脉》曰:“凡刺之理，经脉为始，营其所行，制其度量，内次五脏，外别六腑。”
在《灵枢·经别》里，有这么一句话:“夫十二经脉者，人之所以生，病之所以成，人之所以
治，病之所以起，学之所始，工之所止也。粗之所易，上之所难也。”由此可知十二经脉的
重要性，针医倘若不明十二经脉，开口动手都是错误。

关于经脉，我们曾经和现在，都有太多的误解。

古代的医家认为，用针灸治病救人，必须遵循人体正确的穴位和经络。为了帮助初学者死记
硬背这些经络穴位，官方就铸造了针灸铜人，画了经脉穴位图等等。如北宋针灸铜人，就是
北宋天圣五年（1027）宋仁宗诏命翰林医官王惟一制造的，其高度与正常成年人相近，胸背
前后两面可以开合，体内雕有脏腑器官，铜人表面镂有穴位，穴旁刻题穴名。同时以黄蜡封
涂铜人外表的孔穴，其内注水。然后以此对针医进行考试，如取穴准确，针入而有水流出，
取穴不准，针就不能刺入。

本来要求掌握经脉穴位的理念是对的，但初学者大多并不具备抽象思维能力，就很容易在执
行过程中犯了刻舟求剑的错误，针灸铜人和经络图的出现，就导致经络经穴变成了死东西，
以至于后世很多学针灸的人都以为，只需熟记这些经和穴的位置，记住一些用穴的经验，就
可以“治病”了。

明代是中国针灸学术发展的鼎盛时期，针灸名医辈出，出现了大量的针灸专著，如杨继洲的
《针灸大成》、陈会的《神应经》、徐凤的《针灸大全》、高武的《针灸聚英发挥》、汪机
的《针灸问对》等等，都是对中国针灸影响巨大的著作。在这些书的附图中，还主要是一些
经脉和穴位的简图，学者看图还需要开动一番想象力，不至于轻易的依葫芦画瓢。但到了清
代，由于政治原因，针灸开始由兴盛逐渐走向衰落，虽然仍然有一些著作出现，但书中附图
就比明代针灸书更精细了许多，标注了更清晰详细的经络线条和穴位点。

到了现代，由于国家大力支持针灸的发展，出版发行了绘图非常精准细致的经络穴位图，叫
做针灸国家标准，中医院校的医学生们全是以此为准则，学习这种精确到以“分”为单位的
国标经络穴位图。无论官方医院或是民间诊所，无论专业针灸医生还是业余针灸爱好者，几
乎所有的针医，都在遵循着“国标”给患者们进行针灸治疗。不知从什么时候起，大家竟然
把经络图上描绘的那些线条和点，理解为人体组成的一部分，这显然是犯了严重的方向性错
误。

我曾经花了十年的时间，学习过中西医的很多种针术，这十年所学到的各种纷繁复杂的针术，
对于后来我研究《黄帝内经》九针，起到了很大的帮助。我理解制作出来的九针，几乎可以
省略大量临床实践验证这一过程，因为拿上去患者身上一用，效果如何，可以立判高低。中
医的针术就离不开经络二字，我之前所学过的很多针术虽然完全是以西医解剖和运动力学之
类西医理论作为临床指导思想，但在宣传的时候也要牵强附会说是中医，因为这样能够令更
多的老百姓接受。但由于研究这些针术的老师们自己根本没明白经络到底是什么，所以在教
学的时候，学生自然也是稀里糊涂的。病到底怎么来的，又到底怎么治，没有清晰的思路，
基本都是以经验为用。

从事针灸的前面近十年时间里，我一直以为，人体的经络，就是经络图上那一根根细细的线
条。后来有一天我突然醒悟，古人画在人像表面的那些经脉循行线，其实只是经脉的示意图，
并不是经脉实体，就跟地图只是地貌实景的缩略描绘图是一个道理，经络图并不是经络本身。
我还发现，绝大多数从事中医针灸的医生们都是这样，在以刻舟求剑的方式在寻求经络，一
直把经络图当做经络在看待，并且还有专家们在做科学研究，试图在人体上寻找到经络图上
那些细细的线和点，以此证明经络的存在……

针灸医生们临床上也严格遵循着国标上面这些细线（经脉）的走向，不偏不倚，在患者身上
精确到一分一毫的去取穴扎针，把这些线条当成经脉，所以在线条上的穴位叫做“正经穴”，
凡是在这些线条之外的某些有疗效的点，就叫做“奇穴”。这些荒谬而错误的观念，时至今
日，已经根深蒂固，发展成为某些流派的标准，并逐渐占据了主流针灸医学的思想。

所以，重塑内经针灸必须先从经脉这个根源上去拨乱反正，当今中医针灸饱受现代医学知识
和解剖力学理论等影响，也已经到了必须追本溯源的关键时刻了，否则继续发展下去，真正
传统的中医针灸，将荡然无存。

经脉并不是线条，经脉是古代中医对人体的一种解剖方式，是立体的存在。内经把十二经脉
比喻为十二经水，其实就是告诉我们，经脉如同河流溪谷一样，是自然立体的，深浅宽窄不
等。我们在经络图上所看到的那些线条，只是古人用来示意的图，让我们了解经脉，并不代
表经络本身就是线条。

这个道理，就如同我们在地图上看到那些细细的线条，实际上代表的是宽大的公路，宽窄深
浅不一的河流。比如我国的省界，虽然省与省之间有地界的划分，但并没有精确到分毫的界
线，只是有个大概的划分。全国的空气与水其实是一个整体的概念，长江水在流经云南的时
候属于云南，流经四川的时候属于四川，流经武汉的时候属于武汉。但跨越这几个省市的水
都是属于长江水，这一点没有变，只是流经每个省市地区的时候，长江水会一直在“外有源
泉内有所禀”的进行小循环。虽然四川省的天空与甘肃省的天空也有分界，但空气在流动，
今天在甘肃就属于甘肃，明天转到四川就属于四川，但空气流经当地的时候会受当地自然条
件和环境的影响而产生变化。
