= 中医的自信
冰台
2016-10-26 18:36

2016年7月1日，国家主席习近平在庆祝中国共产党成立95周年大会上发表重要讲话，*习主
席说：当今世界，要说哪个政党、哪个国家、哪个民族能够自信的话，那中国共产党、中华
人民共和国、中华民族是最有理由自信的。*

2016年9月3日，习近平主席在二十国集团工商峰会开幕式主旨演讲中指出：一个13亿多人口
的大国实现现代化，在人类历史上没有先例可循。*我们有信心探索出一条具有中国特色的
发展道路，这份自信来自历史、哲学和文化的思考，文化自信是民族自信的总源头。*

我注意到，在习主席的讲话里，他对民族和文化有一种特别的重视程度。尤其是看到他说
*“文化自信是民族自信的总源头”这句话时，令我感同身受，也再次坚定了我对内经医学
的信念。*

*一个民族的自信，源于对本民族文化的自信。中医的自信，也源于对中医文化的自信。*

*这里所指的文化，并非被污染、扭曲、变异了的那些文化现象，而是指文化本源。人类文
化的根源是自然世界，*按理说全人类的文化根源应该是一样的，似乎文化可以相互结合，
以期发展得更好，这种想法没有错，文化的规律也是不停的发展和延伸，但民族文化无论怎
样融合怎样发展，都必须在根源未失的前提下才能够真正得到繁荣。一方水土养一方人是自
然规律，民族文化必须适应本民族所在地的天气和地气，你是什么种，就应该守住什么样的
土地，守住自己的根，再去结合异族文化，才有生长得更好的可能性。

丢失了本民族文化的根源，将带来什么危害？树木失了根将会枝叶枯萎最后死亡，民族失了
根将会衰败以致灭亡。民族文化落后，国家也就落后，一个民族失去了文化根源，就再也没
有引以为豪的资本了，没有资本就没有发言权。倘若本国文化已经被他国文化侵袭统治，即
使你做的再好，也是他国的文化使然，所以你永远只能成为傀儡。*尤其是文明文化被野蛮
文化甚至奴性文化所攻占，这是最可悲的，对方即使是兽类，粗鄙不已，你也只能唯他人老
祖宗的马首是瞻，你必须恭维和奉承并沿袭他国的民族文化，否则就会被殖民甚至灭了你，
你将变得懦弱，反抗无力。*

老祖宗们用智慧开拓总结的那些文化根源，可以证明你这个民族的优劣性，只有文化本源才
可以令民族长久的自豪和自信。文化可以发展，可以取长补短，但本源应该是纯正的，比如
汉字里夹杂英文，这是一种文化融合后的变异，只是一种潮流，属于一个时代的热，并不属
于文化本源。潮流这东西，时过境迁就将过时或演变成另一种状态，所以不能作为文化根源
来长远传承下去，否则变异的文化将使子孙后代无所适从，不可能拥有自信了。

自信能让国家和民族充满自豪，具有无穷的能量，生活自在而快乐，这是多么令人神往的境
界！中华民族具有５０００多年连绵不断的文明历史，创造了博大精深的中华文化，为人类
文明进步作出了不可磨灭的贡献，所以习近平主席说中华民族是最有理由自信的。虽然我们
最有理由自信，但我们却逐渐丧失了很多的自信，就是因为民族文化本源正在被逐渐丧失。

而民族文化最重要的其实是医学文化，因为医学是保障本民族繁衍生长昌盛的根本，戴上
“东亚病夫”帽子的中国在近代及现代曾饱尝欺凌，所以当代中国一直在发奋图强，近年国
家领导人也开始重视中医。中医本源《黄帝内经》是我国现存最早的医经，这部医经承载了
中华民族上古医学的高度文明。*按《汉书》所言，医经是可以令人“起百病之本、死生之
分”的，能够被奉为医经，一定是中医在思想和言行方面的准则。*然而大多数中医人连
《黄帝内经》的书名都没搞懂是啥意思，也在从事中医的临床诊治。有的中医名家著书立说
解读翻译《黄帝内经》，他本人却连内经九针都没见过，更谈不上领会九针真正的意义，他
是如何翻译内经的呢？类似这样的中医现状，振兴起来又有何益？

*医学的优劣，取决于文化根源的优劣程度，以及医生对文化根源的重视程度，*并不是取决
于医疗仪器和检测设备的先进与否。靠官方和财团的强撑而雄立的医学，如果不明而为，在
赚取巨大利益的同时，也必然会伴随大量的社会矛盾产生。因为广大患者才是衡量医学价值
的裁判，你若无能，你若有害，终将被逐渐醒悟的患者们反抗和否决。

做医生的，如果不明理，害人也害己，也许你能忽悠一时，但无法长久昌盛。如果自己的医
术比别人安全，比别人疗效快，比别人疗效更稳定，比别人医术的适应范围更广泛，日子过
得比别人轻松，收获最大却比别人付出的少……我相信所有的医生都梦想如此，这个境界，
你可以横行天下，该是何等的自信啊。

然而，对于一个学医的人，要想获得这份自信，就如同一个穷光蛋要想成为亿万富翁，谈何
容易。

我十六年来一直混迹在医疗圈，见过和认识的医生无计其数。我看到的绝大多数医生，脸上
堆满了疲累、尴尬、窘迫、疑惑、焦虑；脸色普遍苍白、瘦黄、浮肿、晦暗、枯槁；反应普
遍迟缓、木讷、茫然；行为方面常常表现出自私自利、狂妄自大、拘束谨慎、人云亦云、阿
谀奉承、翻脸无情……

这些现象是什么特征？病态！一个民族缺乏自信，会普遍表现懦弱衰败，一个医生缺乏自信，
自然会呈现出这些病态。然而医生是拯救病患的呀？医生自己尚且缺乏自信，一副病夫形态，
又能给患者带来多大的实惠呢？

我反思自己十多年的医路历程，其实代表了大多数中医人的真实状态，多年来，我一直在自
信与不自信之间反复纠结着。我对自己医术的自信，经历了这样几个阶段：*低能的自信—自
大—自卑—狂妄的自信—傲慢—自馁—认知的自信—张扬—内敛—文化的自信—轻松—愉悦—真正的自
信。*

在从医之初，仅仅学得一些基本简单的中医方法，我却充满了自信，天不怕地不怕，什么病
都敢接，什么病都敢治，嘴边常常充斥“绝对”、“可以”、“肯定”来应对患者的疑问。
然而，在临床上的黔驴技穷，令我的自信逐渐下降到无奈又无助的程度。这个阶段，我先是
处于一种盲目无知的自信，临床上的一点点成绩，就令我骄傲，然后，临床上遇到的挫折，
又令我感到自卑。我只好八方寻求打探，参加各种医术培训班，去学习别人的经验，以补充
自己的不足。于是中医和西医的各种疗法，杂乱的学了很多，由于自己缺乏认知，自然也没
有鉴别能力，我只能卑微的迎合老师们的观点，并追随他们的学术。

后来我学得西医解剖以及运动力学指导下的一些医疗方法，能够相对轻易解决以前束手无策
的一些骨关节病痛了，于是我再次自信满满，经常目中无人，唯我独尊。然而随着时间的推
移，临床经验虽然逐渐丰富，但我在临床中的疑惑却有增无减，我的自信又开始下滑，被迫
又不断的寻求参加特效疗法的培训学习班。后来我发现我所学到的这么多疗法，都只是在经
验和招数上徘徊，我只是在复制老师们的经验，去机械而忙碌的运用，然后积累一些运用的
经验。虽然学到的招数和技法越来越多，我却变得越来越自馁，因为在取得一些神奇疗效的
同时，我也深刻感受到医学道路充满了危险，唯恐手上的那些刀、针、钩之类，一不小心就
害人害己，所以那几年我表面上意气风发，骨子里却过得提心吊胆，生活在疲乏、窘迫、焦
虑之中。

由于自己的医疗行为一直是知其然而不知其所以然，有好几次治疗都差点酿成大祸，我诊治
病痛的过程越发的谨慎了，我不敢再说“绝对”、“肯定”之类的字眼，经常保持一种谦恭
的态度，回应患者的总是“试试看吧”，给自己的失败先预留一点余地。由于各种疗法总是
存在一些欠缺，尽管我小心翼翼，还是经常会发生一些小的医疗过失，压力令我憔悴不堪。
我不知病是怎么来的，也不知病到底是怎么治好的，老师们所传授的那些自圆其说的医学理
论，虽然经不起推敲，我却无力否定，我只能在疑惑中继续运用那些疗法。

我看到一些名医后人和名师高徒，学术随从者甚多，平日里总是昂首挺胸着，这些门派中人，
言论观点掷地有声，充满了自信，令我羡慕不已。于是我也曾去跪拜一些门派宗师，但入门
之后我才发现，江湖上门派之争一直存在，大家都极力维护自己的门派，我跟了宗师，就只
能坚持自家的学术思想，虽然也可以与同道交流切磋，但学术的根本观点却不能轻易改变，
因为一旦引用了其他门派的观念，就会被同行鄙视，谓之“剽窃”。*有了门派就有了围墙，
围墙之内，天地只有那么狭小，而宗师终究只是凡人一个，凡人无论多么睿智灵性，在局限
空间里取得的那些认知，终究是有限的，*作为徒弟，即或发现师父的学术思想存在谬误或
欠缺，也只能继承与维护下去，不敢修正颠覆，否则就会被众人指责“欺师灭祖”。

*跟了名师，也并不能真正获得自信。*

*真正的自信，还是在回归《黄帝内经》之后，我才逐渐体会到了。*

在回归内经医学之初，我挖掘了医学界从未见过的针具和方法，冠名为“立新七针”，完全
抛弃了肌肉、骨骼、神经、血管的影响，只在经脉和经筋以及气血的循行上做文章。这些内
经医学基础知识在临床上的神奇展现，令我又一次的恢复了自信。有一段时间我非常张扬，
我以为自己的认知很高了，却不知自己还处于术和法的层次上。我还被各种病名和症状左右
着，但我已经开始频繁出入各种场合讲学，特别在乎别人的恭维，在乎别人对我的尊重程度，
我不断的去贬低和攻击同行们的那些在我看来属于粗陋的学识，我愚蠢的去指点医学，告诉
别人这样做是对的，那样做是错的。渐渐的，我发现一些原本亲密的朋友关系，开始疏远了，
一些原本融洽的师生关系，也逐渐淡漠了，在刺激对方的同时，我自己也领受到一些反作用
力。我开始反省，开始收敛自己的行为，自信再一次受到打击，不得不包容别人的无知，以
减少自己的压力。

*医路走到2015年春夏之季，*当绝大多数针灸疗法还在脏器、经络、痛点、穴位、筋结、针
具等等上面大做文章的时候，*我所创建的立新七针针灸疗法，已经从经络穴位的层面，上
升到了内经医学的卫气层面。*我彻底摆脱了病名与症状的左右，也不再强求即时疗效，天
地自然之间的能量，是无限的，取之不尽用之不竭，自然规律在人体里的运用，可以令我们
的医疗行为无忧无虑。*放眼望去，市面上所有的疗法，都没有逃脱内经医学的框架，都是
依赖卫气取得的疗效，只不过日用而不知罢了。*于是我再也没有那么多的茫然了，也不再
需要通过试验去验证内经医学，立新七针的医疗行为变得前所未有的安全简单和轻松。*我
知道自己这时候才算正式进入了内经医学的殿堂，天地人三格局我已得其二，*像我这样的
凡人，曾经梦寐以求上医治国的境界，一直可望而不可即，现在终于可以在内经医学辉煌的
殿堂里撒一把野了，我的自信再次恢复，而且变得特别的自信。

2016年初，*随着对医学真相的恍然大悟，这时候我才真正意识到，只有对内经医学的信任，
才是中医人能够真正永远自信的根源。*虽然多年来医学路上的各种险峻和折腾，已经把我
的身体消耗得憔悴而老去，但我却充满了从未有过的自信与力量，我找到了真正的自信。因
为这时候，*立新七针不再纠结取穴和守经，我们只需守气，绝大多数患者都可以未卜先知，
信手拈来就有立竿见影的疗效，即使少数患者当场没有明显的改善，我也知道他们“痛虽不
随针，病必衰去”，坚持治疗多几次，病痛一定会显著缓解或痊愈。*

*我终于看到了内经医学的巨大格局，正所谓一切众生皆是幻相，病名和症状，其实都是幻
觉假象，唯有天气、地气、人气，才是中医的本源。*我知道这些大道至简的理念一旦得到
普及和弘扬，必将影响和改变全人类的医学现状，所以我忍不住说《黄帝内经》的卫气循行
获得诺贝尔奖应该是最当之无愧的，我渴望“得其人”，一起去挖掘和振兴内经医学。

*通过回归内经医学，我能看到遥远的未来，*我知道争与不争，那些都会来到，因为这是自
然规律，所以我已经不屑于当下的名和气，不再纠结别人对我认可与否。现在，一些曾经亲
密的学生和朋友们的疏远，已不再令我有伤感，*我对那些继续跟随我探索内经医学的朋友
们说“你若不离我就不弃”。立新七针针灸疗法并非我个人的发明创造，也不属于任何门派，
我们一直在努力探索，回归远古时期自然医学。*立新七针只是对内经医学进行整合运用的
一个冠名词，所以我和我身边少数真正掌握了立新七针学术思想的人，都充满了自信，这种
自信，源于他们对内经医学的信任，所以收获巨大的时候他们感到特别幸福。我们对内经医
学欲罢不能，收获的自信，令我们无法张狂，更令我们无法内敛，因为这份自信是接地气的，
可以以最好的自然状态生长繁衍，所以我们无忧无虑的自信着。

如今再度放眼中医界，在看到少数真正有认知高度中医人的同时，我也看到我曾经的自以为
是与狂妄自大以及郁闷窘迫，依旧在很多中医人身上此起彼伏的显现着；我还看到很多中医
虽然已经开始重视《黄帝内经》这个文化根源，但依旧没有明白内经医学的价值；我依旧看
到很多中医人快速的被西医诊治理念所俘虏；我看到各种脱离了内经医学根源的创新疗法还
在不断的现世；术这个层面的临床经验依旧吸引很多中医人趋之若鹜；我看到绝大多数中医
人仍然在病名与症状上纠结着。我看到我的过去，我知道他们普遍的缺乏真正的自信。

中医人为何不懂《黄帝内经》的价值？

因为中医早已远离了自然，远离了自然的中医人，少了许多的悟性与灵性，当然无法读懂
《黄帝内经》。于是读不懂的内经就被一些人扣上了“腐朽”、“糟粕”、“过时”等帽子，
导致内经医学被藐视，被抛弃，被遗忘。尽管还有少数中医人在苦苦坚持内经信念，由于阅
历不够，思维局限，导致认知上的不足，无法将内经解读明了，不能形成简明而完整的医学
体系，所以影响力十分微弱，中医的文化本源就这样渐渐地远离中医。

丧失了文化本源的中医，有什么理由不走向衰败？

内经之后的中医，就忽视了自然规律的重要性，开始重视名医的个人临床经验，中医人常把
前辈的方术、祖传秘籍、老中医经验、个人总结等等视若至宝，其实这些指导思想已经走偏
了。方术秘籍都是对症而用各有所宜的，经验虽然有用，但毕竟只是个人经验，不是普天下
的自然规律，所以肯定有很多不好使的时候。在茫然无助的状况下，某些中医人吸纳各家门
派之长，或引入西医诊治理念，“创新”了一些疗法，以补充在临床上的不足，这其实也不
是解决问题的办法。你全然不知这些所谓的创新疗法，其实真相都写在内经医学里，东拼西
凑的经验，并不是规律。其实，*中医应该首先低下那颗被虚荣心撑得高昂着的头颅，放弃
对经验的重视程度，回归到内经医学根本上去，重新建立一套有根源又能适应当代社会的内
经体系。*在尊重和恪守人体自然规律的前提下，每个中医去总结所在区域天地人三气对疾
病的影响，形成自己的经验，这样才可以做到信手拈来都是满满的疗效。

*人与自然是密不可分的一个整体，中医人的思维应该回归自然，中医也应该追根溯源回归
内经医学，这才是中医人自信的本钱。*《黄帝内经》的黄帝之意，是指汉族祖先天地人三
皇之一的人皇，代表着人类，内是指相对于天地自然而言的人体本身，因此*内经其实是认
识掌握人类生命规律的一本圣书。*《黄帝内经》由《素问》和《灵枢》组成，素问的素，
本义指未染色的原丝品，代表纯净、原始、本质，素问之意，即对病因进行追根溯源。《灵
枢》的灵，是神灵，指沟通天地万物的通神力量，枢是中心、关键、转轴之处，这里指气血
的运转，旺衰与否，灵枢之意，是探索自然规律，寻求解决病痛的方法。

通过书名，我们已不难明白《黄帝内经》对于人类有何等重大意义。

*大道至简，天地之间，至简者，莫过于自然规律。*

“守一勿失，万物毕者也。”事物千变万化，令我们眼花缭乱，感觉是法无定法，然而真相
只有一个。我们只需抓住事物的自然规律，就可以不变应万变，任病痛万千变化，终究不离
其根，顺藤摸瓜，岂有不能之理？*自然规律是不会随意变化的，这就是内经医学的根本！*

事实上，中医早就脱离了自然规律，演变成了经验医学。《黄帝内经》记载的药方仅有13个，
所列病名不足500种，那些其实只是为了举例说事而用。愚人不明，以为症状和病名就是医
学的真相，以为药方就是医学的核心价值，此风竟然愈演愈烈。内经之后，中医发展至今已
经两千多年了，一直都在围绕着患者的症状和病名做文章。发展至明代，中国历史上最大的
方剂书籍《普济方》，所记载的治病药方已多达61739个。发展到现代，中医也意识到了自
己的落后，开始大面积向西医学习，中医理论体系渐渐向西医靠拢，当代社会更是提倡中西
医相互学习。须知所谓科学的西医发展到现在才不过二百余年，已茫然的发现了近300000种
病名，一个不明向另一个不明学习，这将是怎样的一种认知？中医若继续被药方和病名所左
右，是危险的，一定会被繁琐的症状和病名撑至负累不堪，这样发展下去何时能够真正解决
问题？

一旦认知变成繁琐哲学，人类就再也无所适从。

中医文化根源一旦被扭曲甚至丢失，也就会演变成为繁琐医学，医生们面对层出不穷的各种
症状和病名，也将无所适从，只能陷入繁琐不已的状态之中，疲累不堪，还危机四伏，只能
谨言慎行，谈何自信。
