= 经脉——脏腑相使
冰台
2016-11-30 19:56

认识了任督二脉的概念，我们接下来就从脏腑角度去理解十二经脉的循行。

人体五脏六腑各自的功用以及相互之间的关系，就类似于一个国家的职能部门以及各部门之
间的关系，每个职能部门有自己的职权，有独立的流通渠道和分支结构，大家各司其职，同
时各个部门之间又缺少不了相互的帮助与联系。

内经在《素问·灵兰秘典论篇》里，讲述了五脏六腑的功用，并且刻意注明:凡此十二官者，
不得相失也。也就是说，每个职能部门都很重要，缺一不可，但都不能独立的存在，必须成
为一个整体。

灵兰，即灵台兰室之简称，相传是古代帝王藏书之所。所以灵兰秘典里所记载的都是非常重
要的内容。其中提到:“肺者，相傅之官，治节出焉”，相傅一职，辅助皇帝朝政。相是指
丞相，傅是太傅，指皇帝的老师。人的心脏是最重要的，类似一国之王，所以心为君主之官。
人体脏腑位置高于心脏的是肺，正是由于肺在诸脏腑中的位置最高，故《灵枢·九针论》
称:“肺者，五脏六腑之盖也”，肺被内经医学当做一个国家的相傅这个重要职责在看待，
而不是仅仅被看做现代医学的呼吸器官。

除了肺的生理位置很重要以外，肺的功能也是原因之一。《素问·经脉别论》:“脉气流经，
经气归于肺，肺朝百脉，输精于皮毛。毛脉合精，行气于府。府精神明，留于四藏，气归于
权衡。权衡以平，气口成寸，以决死生。”这段话里有*“肺朝百脉”一词，经脉血气为何
从肺经开始循行，还在于这个“朝”字。*

在古代，朝廷的指令是通过早朝来传达并贯彻落实的，皇帝一升早朝，文武百官皆到，文官
宣读君主旨意，宣读之后文武百官都奉旨回去，然后再将指令一级一级往下通报，传至各自
管辖的领域。

朝廷的指令要贯彻下去是通过早朝，而朝廷要了解全国各地的情况，也是通过早朝，由文武
百官上奏。朝廷各个部门，平时会收到管辖区内各地呈上来的折子，这些折子就是民众反映
的一些问题，如果部门处理不了，就需要上朝向皇上汇报。丞相在朝廷里的作用非常重要，
既要保障皇帝下达的诏书和下面上递的折子这个传递渠道畅通无阻，还要辅佐皇上调整职能
部门。

因为丞相光靠上朝还无法很好的辅佐皇帝，要贯彻、执行、落实、监督君主旨意，它还必须
有权对下面一些不称职的官员进行任免。所以肺虽然是“相傅之官”，但它同时还具备“治
节出焉”的能力。《灵枢·九针十二原》云:“所言节者，神气之所游行出入也，非皮肉筋骨
也。”*神气游行出入之所就是气血循行进出的部位，但并不是筋骨关节本身*，在上医治国
的理念里，四肢关节这些部位就相当于各级地方官员，我们在现实社会中办事，都说要打通
关节，你要是不跟管着你的官员搞好关系，他就不让你过，就这意思。所以节指来自全国各
地的节度使，丞相统管全国各级官吏。

这些道理，从“上医治国”的角度去看就一目了然，丞相对国家的管理好与不好，看下面各
级官吏的工作干得如何就知道了。同理，要想知道下面各级官吏做得好不好，看丞相的水平
就能得知。*因此，十二经脉循行的血气，要输布濡养到全身各部位，当然要以肺经之气为
首。*

明白这些道理后，我们就可以参照十二脏腑的功能与作用以及相使贵贱，去理解十二经脉的
循行顺序。比如首先重视呼吸（肺），其次是排泄（大肠），然后进饮食（胃），然后储备
运化（脾），然后先养天子（心），然后进一步分配输送（小肠）……

如果要进一步理解十二经脉为何从肺经开始，我们其实还应该去了解一下中医把十二地支对
应十二经脉的由来。
