= 经脉——抽象思维
冰台
2016-8-10 00:00

据我所知，针灸界其实也有人认为经脉不是线条。既然不是线条，那经脉到底是什么呢？经
脉存在于哪里？

这个问题，即使那些最权威的中医，似乎也没有给出一个令人信服的答案。大家只知道用针
去扎穴位，在穴位的选用、进针的手法、针刺的深浅方面，经验比较丰富的人，其余人就唯
马首是瞻，结果针灸被搞成了经验医学。

有人说，人类都已经登陆月球、把火箭射离太阳系、搞核融合、超级电脑……可是人类偏偏
就找不到中医最神奇的经脉。

这人很聪明，他也看《黄帝内经》，居然也分析出来经脉就是血管，悟性比很多忠实痴迷中
医的中医人还要强大，但他发现内经里的经脉就是血管以后，就以为抓住了中医伪科学的把
柄，于是他开始冷嘲热讽中医在故弄玄虚，明明是一根主血管，无数毛细血管，硬生生的被
中医整出个十二经脉来。

由于他看到《黄帝内经》说“地有十二经水，人有十二经脉”，他根本没搞懂内经医学援物
比类的用意，就片面的认为内经荒诞不经:“人为什么有十二经脉呢，就是因为地有十二经
水，这个所谓地有十二经水是因为周末秦汉之既，中国主要河川有十二条，那埃及主要河川
只有尼罗河一条，那么埃及人的经脉难道只有一条？”这种逻辑推理的错误，还在于他一开
始就不明，用一种不明的事物去证明另一种不明的事物的对错，这样的结论有什么科学意义
呢？

有人看到中医理论说经脉不通会发生病痛甚至危及生命，就用那些截肢的人来说事儿:别人
手脚锯掉了，也并没有因为手足上的经脉没了而送命呀？这也是无知的表现，他不明白中医
的经脉其实是在进行人体营卫二气的输布，营气就是血液循环系统，卫气则相伴营气而行，
与营气一体，相互进行循环，同时又有自己独立的一套循环系统。营气与卫气的关系，就如
同河流与河流上方的空气（这些将在本文后面进行分析研究）。如果被截肢的人他的截断面
一直是开放性创口，那么这个人能活多久呢？就像大血管断了，如果不结扎缝合起来，让血
一直流，岂不是很快没命？只要截肢处缝合闭拢了，那么经脉（营气卫气）就能自动从封闭
处连接，依旧是各归各路，继续进行循环，这个人当然不会有事了。

当然，也不能怪这些攻击经络学说的人无知，千百年来专业从事中医的人多如牛毛，人们尚
且对营气卫气的认知是稀里糊涂的，那些不具备临床经验的人，认知更是非常的低，又怎么
能够指望他们凭空想象就能够正确理解经脉呢？

主要还是由于认知上的不足，以及思维方式的不同，而产生了抵触和反对《黄帝内经》的不
同观点。因为他们只看到了血管（营气），却不懂人体还有更重要的卫气，更不懂卫气也是
经脉的组成部分。有些人只习惯于肉眼看得见的事物带来的感受，他无法享受到抽象思维带
来的愉悦。

一个缺乏抽象思维的人去评价中医，结论是很悲催的。这种人只要是遇到看不见摸不着的事
物，就很容易意志坚定的否决对方存在。所以，那些不善于抽象思维的人，你跟他讲中医经
脉，无异于与夏虫言冰。

抽象思维有多重要？打个比方，看《西游记》电影与看《西游记》小说，对人产生的作用是
不一样的。电影里的场景人物情节都是已经预先拍摄好了的，你的思维只需傻乎乎跟着情节
走就行，不需要开动想象力，所有观众看完电影，认知到的东西几乎都是差不多的，你我他
每个人眼里脑里的孙悟空都完全是一个长相。但是看小说就不一样了，由于每个人的学识、
阅历、性情、悟性等都不一致，在看小说的过程中，需要开动的想象力是不一样的，看完小
说之后，你我他想象出来的画面感可能就有很大的不同，脑子里所获得的认知，差异性就会
比较大。

经脉其实确实是只有一条，但我们在医学上不能一根筋死心眼，因为我们面对的是活生生的
患者。患者是活的，气血是活的，精神是活的，我们去应对的思维也一定要是活的。就像血
管，人体有动脉血管和静脉血管，然后动脉血管还附属有无数小血管与毛细血管，静脉血管
也附属有无数小血管和毛细血管，动脉血管与静脉血管通过**微血管进行交合**，血液循环
分为体循环和肺循环，体循环中，动脉里流的是动脉血，静脉里流的是静脉血。肺循环中，
动脉里流的是静脉血，静脉里流的是动脉血。

这些都是可以通过肉眼或显微镜在人体解剖上看得到的层面。还有一个层面，我们不能忽视，
那就是通过抽象思维领悟出来的存在。

我们可以在血管之上去想象，但是又抛开了血管，去想象这一条血管里面还包含着三条、六
条、十二条、无数条血管。

这就是运用抽象思维去理解经脉的方式，虽然抽象，并不是无中生有的，我们想象出来的那
些物质也是存在的，只不过平常被一些表象掩盖，我们视若无睹，日用而不知罢了。

为了更清晰的阐述对经脉的理解，我们可以拿个吹风筒来做个关于风的实验，因为通过对风
的观察可以提高我们对气的认知。我们看到，吹风筒吹出来的风，只是一股风，但我要把这
股风看做三条风，对我而言，这是很有必要的，而且也并不是空穴来风。我们知道，风筒最
中心吹出来的风力，是最集中也最强的，靠外边周围的风力就比较散，当然风力也最弱，所
以同样是一股风力，我们也可以看做里面有强中弱三股风的存在。

既然内经把经脉比喻成经水，我们再去观察一下流淌的河水。由于河床地理位置和结构的不
同，河流中心与边缘部分的水流，急缓程度是有所不同的，中间的流水是主流，往往流速比
较湍急，靠河边的水相对就流得比较缓慢些。这是相对于河流的宽度而言，相对于流水的深
度而言，无论在河流中心，中心靠外，河流边缘，我们用棍子去探，就会发现，即使在同一
部位，河水深处与浅处的水流力量也是不一样的。这就是自然现象，一条经水里面有那么多
的变化存在，那经脉有什么理由只能被我们看成是一条呢？

这些现象是我们通过思维想象出来的，但你总不能说想象出来的是不科学的，对吧？人类通
过想象，在那些很平常很普通的物质基础上，发明和制造了非常多高科技现代化的产品出来，
让我们可以欢欣愉悦的去受用。也有人通过想象，鼓捣出一些并无实际意义或经不起折腾甚
至是会对人类或社会带来伤害的产品，成为大多数人唾弃的“神经病”、“疯子”。*但我
们能够因为某些人的想象力荒诞不堪而否定人类想象力的作用吗？*中医队伍里确实有一些
糊涂医，也存在一些愚昧荒唐的疗法，但并不能因为这部分朽木的存在，就否定了《黄帝内
经》这棵参天巨树啊。

认知不同，观点就可能有所不同，这很正常，但无论认知高低，我们都应该尊重事实，尊重
自然规律。我们必须很清晰的认识到，人体仅仅具备血气是不够的，还需要有更重要的精神
支持。在道法自然的中医眼里，“血之与气，异名同类”，气血精神都是一种东西，《灵枢·营
卫生会》曰:“营卫者，精气也，血者，神气也，故血之与气，异名同类焉。”人体最重要
的是五脏，而五脏主藏血、脉、营、气、精神魂魄，血气精神之类，才是奉养生命和周全性
命的重要物质。

所以我们既然要评判或研究中医，就不能只把眼睛死死的盯在筋骨肉体上做文章。满脑子的
神经血管肌肉骨骼，你根本无法理解经脉这个概念。
