= 经脉与地支
冰台
2016-12-14 21:34

内经把十二经脉对应一年十二个月，《灵枢·五乱》曰:经脉十二者，以应十二月。十二月者，
分为四时。四时者，春夏秋冬，其气各异，营卫相随，阴阳已和，清浊不相干，如是则顺之
而治。内经医学处天地之和，从四时八风之理，法天则地，援物比类。人体经脉循行如环无
端、天人相应，自然界的季节变换、月亏月盈等规律就会影响人体经脉及其在经脉中运行着
的气血，所以九针治病一定要“和于四时阴阳”。

“四时”可谓是《黄帝内经》里提及最多的词语之一，四时指一年十二月份的春夏秋冬，又
指一天十二时辰里的早中晚半夜。《灵枢·顺气一日分为四时》黄帝曰:愿闻四时之气。岐伯
曰:春生，夏长，秋收，冬藏，是气之常也，人亦应之，以一日分为四时，朝则为春，日中
为夏，日入为秋，夜半为冬。

内经把人体与自然规律类比，认为自然界的年、季、日、时的周期变化，也影响人的气血随
着相应变化。如我们常常见到很多患者的病情是上午轻、下午重、夜晚更重，这种情况就和
气血运行有关。因为气血的运行是“阴阳相贯，如环无端”的，类似一个大的循环通道，所
以不同的时辰，气血运行到不同的经络，就会对人体产生不同的影响。

中国传统文化用十二地支来代表十二个月和十二个时辰，那么，十二时辰和十二个月的地支
是怎么回事呢？

天干地支是怎么来的？现在有多种说法，那不是我要关心的，我只寻找最符合自然现象和自
然规律的解释来为我所用，因为在我看来，符合自然规律的解释，即便不完全对，也错不到
哪里去。

有学者根据殷墟出土的商代甲骨文考证，认为干支在古代最主要是用于纪日，后世在此基础
上发展形成天干地支系统，用来纪年月日时。以此推测，古人在甲骨文之前应该是取树木的
“干枝”来纪日，上古之人一无所有，需要记事的时候他会本能的捡块石头划个痕迹做记号，
再后来用兽骨刻符号记事，但如果事情多了复杂了，仅靠刻画的符号也不便于计算，于是就
会折几段粗细大小不同的树干与树枝，来推演某些事情，类似最古老的计算器，我觉得这个
论说可信度比较高。

天干与地支的关系犹如树干与树枝的关系一样，天干为树干，地支为树枝。天干共有十个字
数，即甲、乙、丙、丁、戊、己、庚、辛、壬、癸，地支共有十二个字数，即子、丑、寅、
卯、辰、巳、午、未、申、酉、戌、亥。

由于天干地支的意义均来自于树木，所以他们的原始字义也源自于自然界树木的生长过程:

干者犹树之干也。

* 甲：像草木破土而萌，阳在内而被阴包裹。
* 乙：草木初生，枝叶柔软屈曲。
* 丙：炳也，如赫赫太阳，炎炎火光，万物皆炳燃着，见而光明。
* 丁：草木成长壮实，好比人的成丁。
* 戊：茂盛也，象征大地草木茂盛繁荣。
* 己：起也，纪也，万物抑屈而起，有形可纪。
* 庚：更也，秋收而待来春。
* 辛：金味辛，物成而后有味，辛者，新也，万物肃然更改，秀实新成。
* 壬：妊也，阳气潜伏地中，万物怀妊。
* 癸：揆也，万物闭藏，怀妊地下，揆然萌芽。

我们从植物的生长过程来看就明白了，子（种）初入土中，为先天之元，到丑种象始裂，寅
萌芽出于土，也就是说植物其实是从寅开始生长的。

支者犹树之枝也，地支也就是植物从种子入地逐渐生长的过程。

* 子：孳也，阳气始萌，孳生于下也。
* 丑：纽也，寒气自屈曲也。
* 寅：演也，津也，寒土中屈曲的草木，迎着春阳从地面伸展。
* 卯：茂也，日照东方，万物滋茂而生。
* 辰：震也，伸也，万物震起而生，阳气生发已经过半。
* 巳：巳也，阳气毕布已矣。
* 午：仵也，万物丰满长大，阴阳交相愕而仵，阳气充盛，阴气开始萌生。
* 未：眛也，日中则昃，阳向幽也。
* 申：伸束以成，万物之体皆成也。
* 酉：就也，万物成熟。
* 戌：灭也，万物灭尽。
* 亥：核也，万物收藏，皆坚核也。

古人根据太阳出没的自然规律、天色的变化以及自己日常的生产活动、生活习惯而归纳总结，
把一昼夜划分成十二个时段，每一个时段就叫一个时辰，分别以十二地支来表示，称为十二
时辰，这就是地支纪日:

23--1时为子时属水，1--3时为丑时属土，3--5时为寅时属木，5--7时为卯时属木，7--9时
为辰时属土，9--11时为巳时属火，11--13时为午时属火，13--15时为未时属土，15--17时
为申时属金，17--19时为酉时属金，19--21时为戌时属土，21--23时为亥时属水。

而地支纪月是以农历二十四节气为准的，如正月从立春开始，到惊蛰结束，为寅月；二月从
惊蛰开始，到清明结束，为卯月……十二月从小寒开始，到立春结束，为丑月。所以十二月
分别为寅月、卯月、辰月、巳月、午月、未月、申月、酉月、戌月、亥月、子月、丑月。

如果从时辰来看，寅时天光始明，代表一天的开始。从人象来看，阴阳交合为子，丑为胎孕
之期，寅为胎儿离母之时，凡婴儿出生后第一声哭，是肺的功能，因哭叫而使肺接触后天的
空气，就开始呼吸，人有了后天的呼吸，气血才能循经脉运行。肺似压气机，心似压水机，
心肺的机能不停，则人的生命长存，一旦失常，或发生病变，或导致死亡。所以十二经纳地
支，寅时配肺经为十二经气血流注的始源。
