= 医患关系的平衡点
冰台
2015-9-14 11:36

医生与患者，一个是救助者，一个是被救助者，二者本应该是一种非常和谐的关系。然而近
年来医患关系却日趋紧张，患者对医生和医院们怨声载道，而医生们也冤屈得叫苦连天，医
患关系矛盾激化，成了社会不安定的部分因素。

很多人把医患关系矛盾激化的原因，归结于药价和治疗费太高，我则不以为然。在消费意识
这一块，其实大多数的老百姓都是比较懂道理的，都知道买商品买服务需要花钱。商品越高
档服务越精致，我们为之付出的钱就相应的越多，是天经地义的事，不会有多少人去责怪飞
机头等舱票价为啥比普通舱贵那么多。因为人在消费或购物的时候，往往都有自知之明，懂
得量力而行，几乎无人会因为兜里钱少只能住得起廉价旅社，却跑到五星级宾馆门口大骂老
板黑心的。

缓和医患关系矛盾激化的核心，也就是平衡点，其实在于“认知”二字。

无论医生还是患者，极力追求的无非就是疗效，只要疗效好，钱其实不是问题。问题是患者
钱也花了，医生力气也花了，但最后疗效没出来。作为患者而言，钱不是天上掉下来的，都
是辛苦挣来的血汗钱，当然希望手里的每一分钱都能是实实在在的一分钱。结果成千上万的
钱花出去了，啥都没见着，患者当然心里不舒服了，就会骂医生，骂政府。而医生呢，也觉
得委屈：俺是严格按照现代医学理论在进行治疗，又没违规操作，药品也有批准文号的，俺
还有一颗大医精诚的心，俺慈悲为怀，治疗也尽力而为的，俺错在哪里了？

太多的人，都没有去思考过，治病的疗效到底怎么来的。通常媒体医院医生都把取得疗效的
大部分希望寄托在药品上，寄托在手术上，寄托在医术上，极少寄托在医理上的。所以都习
惯把患者往药品和各种先进的手术上去引导，而患者是无知的，当然只有听信医生和专家权
威的建议。所以患者基本上都认为治病的疗效好坏，理所当然是医生的事，而很多的医生也
认为治病就是针或药或手术之类的事，所以疗效不好的时候，大家都觉得冤。

实际上，疗效主要取决于医生对病痛的认知度、患者的身体状况、患者的配合程度，这三方
面的条件，只要有一条不够到位，疗效都不会好到哪里去。

如果医生的医术很不错，但患者的身体状况非常糟糕，那是很难在短时间取得多大明显效果
的。如果医生对医学的认知到位了，但患者疑信参半，或不配合，也很难有显著效果。

所以最重要的，还是取决于医生的认知度，如果医生的认知到位，疗效就不会差到哪里去。
对病痛的认知到位了，后两条就可以有也可以无，因为这个医生是可以预防在先，可以因利
势导的，也就不会发展到后来让患者钱花了却无效的时候，去激化了矛盾。患者是无知的，
如果患者能对病痛真相有所认知，也就不会成为患者了。往往都是由于医生在疾病到底怎么
来的又该怎么去，这些方面的认知度很低，或认知上出现偏差，甚至错谬的观念，就直接导
致了疗效的不好或不稳定。

以针灸医生为例子，正常的治疗，一定是精神状态、睡眠、饮食、气色等各方面越来越好，
人类在劳累或疲惫的时候，最好的恢复方法就是睡眠，然后就是饮食，如果饮食不好，睡眠
不安，如何恢复精力？患者的气色是一种身体好转的信号灯，即便疼痛症状暂时没有明显缓
解，只要气色变好了，睡眠饮食二便这些好转正常了，病痛的恢复与治愈就只是时间长短的
问题，最终都不会太令人失望。

但如果患者扎针治疗几次后，气色越扎越晦暗，甚至出现症状越治越重的情况，那一定是医
生在不明而为，这种情况医生是应该自我检讨的。

抛开西医疗法不谈，我们这里只讲中医理论，两千多年前的内经时代，医生治病是以九针为
主要治疗手段的。内经九针虽然有一些看起来粗大令人感到恐惧的针具，实际上那是有针对
性的时候才用的，并不是不分青红皂白所有病痛所有患者来了都用那些粗针和大针治疗的。

内经九针与现代的很多针法不同，内经九针绝对不会在肌肉、神经、血管、骨骼、脏腑等组
织上面直接扎针，因为在这些组织上扎针，要么就很容易出医疗事故，要么会给患者遗留一
些瘢痕结节等，要么会泄泻患者的精气。九针实际上主要是在气这个层面上做文章，通过调
理气血来治愈肌肉神经骨骼脏腑等方面的病痛，以柔克刚的方式取得疗效，有四两拨千斤的
功用，所以内经医学是非常安全绿色的。

九针的优越性很多，一是安全无毒副作用，二是疗效快捷稳定，三是方便简单，四是医疗成
本低廉，五是没有医疗废物，对环境污染很小……有这么多的优点，本应该大力推广造福百
姓的，可惜由于人们在认知上的错谬，竟然导致九针失传。所以我一直在努力呼吁更多的中
医好好地去研究内经医学，我们是中医，《黄帝内经》拥有更高层次的医学理论体系，何乐
而不为呢？干嘛像无头苍蝇一样到处寻求结合？

《黄帝内经》在论述人体血液循环气血调理的时候，有一句话总结得很好：“营气虚则不仁,卫
气虚则不用,营卫俱虚则不仁且不用”。所谓不仁，包括肢体的麻、木、冷、凉、精神的萎
靡、消沉等状态；所谓不用，包括肢体功能失常、记忆消退、失眠、食欲低下、便秘、腰酸
腿软、脊椎关节僵紧、精神不振、行动迟缓、反应迟钝等等功能失常现象。

营气，我们可以理解为血液循环和经络；卫气，我们可以理解为血液循环所必须的外通道和
经络的动力。二者都是属于人体饮食呼吸之后产生的能量，是支配人体生存所必备的动力，
所以营气和卫气对一个人而言，是很重要的。

在中医看来，营卫是阴阳之气，保气法就是保命的方法。如果男子破阳太早，则伤其精气，
女子破阴太早，则伤其血脉。现代人由于生活条件相对比较舒适便利，体质显得比较娇嫩，
而精神工作等压力又比较大，更应该注重气血的养护。可是有的人在刚成年，身体发育刚开
始成熟的时候，就饱受黄色影视书籍等刺激，开始比较频繁的手淫，或过度的纵欲性交，消
耗精血太甚，导致元气卫气营血等大亏，脏腑的发育也不够健全和完善了。然后逐渐的就引
起酸、困、乏、昏、软、僵、凉等系列后遗症状，缠绵不断，这类患者相对而言是比较难治
的。

所以有一些久病不愈的病痛，短期内不见显著效果，跟医生的认知高低就没有太大的关系了。
这部分患者大都表现为脸色苍白、眼圈发青、眼神浑浊、四肢发凉、心情抑郁、精神不振等
等。这部分患者属于风寒湿气入骨，入肾，经气血气五脏气俱虚，很难治的，需要一个比较
漫长的时间，调理的时候，需要多几次才有效，逐渐治愈，属于正常情况。效果虽然慢一点，
只要气色一天天在好转，那就是好事，不能责怪医生不努力，因为不可能拔苗助长。只要整
体好起来了，又何愁局部的病痛不会改善？医生的治疗手段只要不是给患者们雪上加霜的行
为，就问心无愧，对得起天地良心。

就好比一个穷人，本来就穷得一贫如洗，又遭遇了天灾人祸，哪有那么容易一下就富裕起来
的？但往往患者不能理解，听闻别的患者病痛多年被某医生一两次快速治愈了，就冲着这个
名声而来的，他们是不会考虑自己身体本钱的，看别人暴富，再穷的人也想一夜暴富。所谓
期望越大失望越大，只要短时间或数日内，治疗没有取得明显效果，患者就会对医生加以责
备怨恨，甚至背后谩骂攻击。

有一部分妇女的病也比较难治，那就是生孩子后没禁忌好，近年来国内有一股盲目崇洋之风，
很多女孩子看欧美国家女人生孩子后并不禁忌似乎也没什么事，也跟着学习效仿。其实中国
人的体质与欧美人种是不一样的，环境和饮食也不同，中国女人生育后应该适当禁忌。妇女
在刚生育后身体比较虚弱，本应当适度保养呵护，但很多人由于年轻无知，刚生了孩子，身
体还没恢复元气呢，就开始进食冷饮，坐卧湿地，睡眠受空调寒气等等侵袭，导致身体雪上
加霜，身体大虚，气血大败，从此一蹶不振，甚至到了形销骨立的状态。这种情况下产生的
病痛，哪里可能快速恢复？一定是需要一个长期的调理过程，蓄养营卫元气，然后才谈得上
真正治愈。

还有一种情况也比较难治，那就是医源性伤害，属于一种来自医生的病痛。通常是被一些带
钩带刃带烧灼功能的“针灸”疗法治疗过多次的患者，这类治疗方法受西医解剖理论的影响，
主张直接在患者筋膜肌肉上进行钩割切断烧灼等治疗，在患者的筋膜肌肉里遗留下难以消除
的瘢痕结节。特别是气血本来就循行不好的患者，未经这样切割烧灼还比较好治，一旦再三
的承受了这类“治疗”手段之后，皮肤肌肉上摸到全是一些颗粒结节和疙瘩，消不掉了，气
滞血瘀，严重影响到营卫气的循行，遇到再高明的医生，也经久不愈。自然的病痛好治，人
为的病因很难治。

病痛实际上是要靠卫气和血液的循环来修复治愈的，本来医生的行为应该是调养和增强患者
的营血卫气，筋肉骨骼的疼痛，是因为这些筋肉骨骼其实是受害者，本来需要气血濡养它们，
结果医生反而对筋膜肌肉一通钩割切损。无知者无畏，却令患者卫气泄漏，气虚的结果是血
也跟着虚，这就成了雪上加霜。

因为卫气是彪悍之气，见开而出，那里有缝就往那里跑，手术一刀下去，卫气就会顺着刀口
针眼狂泄出来，看看开刀后的那些患者吧，面如死灰，有气无力，两眼无神。这个泄气的过
程患者本人是无法感知到的，但只要患者回家照镜子，对比自己治疗前后气色的变化，就明
白你不知不觉中被无知的医生伤害了多少。

纵欲过度也如同手术之害，令精气狂泄。泄出去很容易，一时性起就狂泻出去，积蓄则需要
有个过程的。如果性爱适度，能够保持进出的基本平衡，那也没问题，但如果出的多进的少，
日久必虚，这时候要补回来，哪有那么容易？

卫气营血怎么来？不是靠呼吸直接吸进去形成的，也不是靠输血进去这么简单的。需要水谷
进入胃里，在体内化合，分为宗气营气卫气输送出来，濡养五脏六腑经脉经筋，各行其道，
各负其责。营卫气还必须靠自身能量而不是靠外力在人体内如环无端的循行，才能够进一步
的提升能量。

就如同做生意，有一百元本钱，可以赚几十，赚一百，二百，但很难赚到五百一千，世上没
有多少这样的机会。如果有一万元本钱，赚一千则不是难事，如果有一百万本钱，赚十万也
不会太难。治病其实也是这么个道理，这个本钱，就是患者你身上的气血，气血越足病就越
好治。问题是很多医生和患者都只顾看利润的多少，而从不惦量本钱的大小，所以不明而为
都是错。

当然了，治病不止这么简单的事，这里只是粗略的谈到一些方面的问题。除了气血，患者的
心态、饮食、居处、劳作、生活习惯等也是非常重要的，《灵枢•本神第八》篇里说：“用
针者，察观病人之态，以知精神魂魄之存亡得失之意，五者以伤，针不可以治之也”。讲的
是一个人的精神魂魄还有志意的重要性，如果这些都伤到比较深了，九针再怎么好，也是很
难治的，说明病痛的治疗，医生需要掌握很全面的知识才行得通。

作为一名医生，在没有把握的前提下，任意把病名冠在患者头上，这也是医患矛盾激化的最
主要原因之一，也许该医生是根据现代医学理论来得出的病名，治疗也规范的遵循了操作制
度。可你有没有想过，如果现代医学在这个病痛上的认知错了，你就跟着错了，这种有书为
证的借口，实际上是不负责任的治学行为。最后受害的是患者，当患者返回来责难你的时候，
你能说自己是无辜的吗？

我常对患者说，医生既然说你是这个病名，就说明他应该知道这个病的来龙去脉了，可他为
什么治不好你的病呢？他是故意的还是无意的？病名有了，病却治不好，凭什么说你的症状
就是这个病名？如果病因与病名都不相符合的话，这是怎样的一种医疗行为呢？作为患者，
你为什么不多动脑筋想一下，反问给你下这个病名的医生呢？

特别是一些生性比较胆小的患者，一旦身体出现一点病痛，本来就非常紧张，医生如果再给
他们扣个病名，加上治了半天又不见疗效，患者会被吓得魂飞魄散，以为自己是患了天下绝
症，从此精神志意消沉，寝食不安，小病变成大病，大病变成不治之症。这类患者很常见，
整天背着个病名，行尸走肉般游荡，毫无生活信心了，但又不甘于死亡，所以还坚持着四面
八方求医，期望遇到华佗扁鹊再世。治疗这种患者，医生如果不在调神上多下功夫，仅仅依
赖针灸药物之类，就想把他们的症状给治愈了，无疑有点超现实主义思想，最后也是会激化
医患之间的矛盾。

所以要治愈病痛，除了针灸药的调理之外，患者本身的情志、居处、劳作、饮食、睡眠等等，
都是很重要的，不可忽视。



——— 陈立新2015年9月14日写于重庆巴南立新七针针灸研究所
