= 神乎神客在门
冰台
2015-4-25 00:00

立新七针的诊治思路源于《黄帝内经》，诊治思路里非常重视*阴阳、术数、机、四时、尺
度、法天则地、援物比类……*等等这些理念，这些是中医的精髓，是道，也是法。可以说
离开了这些，仅仅会玩几支针具的立新七针，是没什么意义的，展现出来的疗效也一定是非
常平凡粗俗的。这也是为什么有个别学员学习立新七针回去运用不好的主要原因，因为他们
只是简单的在模仿，我讲课的时候虽然非常重视和提倡道法自然的思路与理念，但他们不以
为然，总是习惯于具体的招式，把精力放在录音录像和笔记上去了，结果把老师讲的关键的
一些字眼和理念忽略漏掉了，也完全没有消化老师讲的内容，吃了大米拉出来的还是成形的
大米颗粒，营养没有被你吸收，也就谈不上你会有什么长进。

学中医其实就是学道理，完整的中医必须包括四个层面：*道、法、术、器*。真正的医理，
都存在于自然之中，永远不会失传。但绝大多数中医学者都习惯在术这个层面做文章，更有
一些人只在器上做文章，由于一些特殊原因，这些人又恰恰占据了中医的主要舞台，结果疗
效又不好，从而被一些不明理的人误以为他们就代表了中医，从而对中医大加批判。所谓术，
就是一些经验，一些招式，比如说“老中医经验”，很久以来大家都把这些经验视若珍宝。
在我看来，这些经验其实是没什么价值的，因为与自然规律相比，这些经验简直就是小巫比
大巫。老中医的经验只是基于他本人或家族几个人最多几十人的一些认知，限于地域环境学
识等各方面的因素，老中医的经验大多都有很大的局限性，很多老中医从医一辈子，到老死
的时候认知都还没到位，你说你继承他的经验来干嘛用？所谓器，是指发挥疗效的工具，如
药材、针具、灸具、砭石等等，倘若道不明，法不通，你运用这些器材能有多大疗效？不言
而喻。可惜世人愚钝的不在少数，往往高举着不明理的一种“针”或“药”进行大肆宣传，
其实是不懂自己层次之低下的荒唐行为。

医者要给人治病，首先应该要明理，除外还要懂得分辨病的真假，这是最起码的认知。有些
人为的，天生的，或外界不可抗拒的原因所导致的问题，其实不属于病的范畴，靠医者的能
力是很难改变治疗的。真正的病，是那些内因与外因里应外合，导致的人体阴阳失调，这种
病是医者可治的。所以“病”可治与不可治，做中医的人首先头脑要清晰，哪些事有能力解
决哪些能力不能解决，心里要有数。

怎样治病？这是一个令所有人都最敏感也最关心的话题，内经说“粗守形，上守神”，意思
是说层次很低的医生就只懂得在患者身体上做功夫，医理稀里糊涂，主要是凭自己和别人积
累的的一些散碎经验在从事治疗，偶尔碰巧治好了，其实也不知到底是怎么好的，治不好也
不知为啥治不好。而层次比较高的医生则考虑问题比较全面，如神一样操控全局，可以预知
疗效未来。

对于现在的大多数中医而言，守神成了一种很高的境界，因为大家都认为可望不可及。其实
这个神，寓意很深远，既包括物质层面也包括思想志意这些层面，不是一成不变的。神是什
么？《灵枢•九针十二原第一》说“神客在門”，说明神是一种表现，包括方方面面。比如
在患者一方而言，患者的心态、认知、阅历、贵贱、居处、勇怯、年龄等等，无一不与神有
关联。在医者一方而言，医者的仪容、谈吐、表情、举止、年龄、学识等等，也无一不与神
有关。在医疗场所而言，医院（医馆）的地势、气势、格局、装修、色调、层次等等，也是
无一不与神有关。这些都关联到神，我们要守神，你说哪一样能少得了呢？

守神是说起来容易做起来难的一件事，患者是活的，诊治理论是活的，针具也是活的，社会
生态环境是变化的，医者怎么守神？比如《灵枢经》说针有九针，九为天下之大数，寓意能
力超强，涵盖天下。我们表面看只有九针，实则九中又有九，大家可以算算1到9这九个数字
的排列组合有多少种变化，多得吓人。而病痛有多少种？又有多少种变化？恐怕没人弄明白
过，所以无论你医者本人的能量有多大，仅仅一支毫针，或一双手，你能够解决多少纷繁复
杂的病因？《灵枢•外揣第四十五》说“*夫九针者，小之则无内，大之则无外，深不可为下，
高不可为盖，恍惚无穷，流溢无极*”，就是这个道理。

也就是说，除了针具在结构上的优势，九针变化运用起来所产生的能量是无穷无敌的。立新
七针疗法只用了内经九针中的七种针，这七种针的排列组合据说有5040种变化，如果七种针
里面又分大中小型号，那么就是二十一种针，这二十一种针又有多少个排列组合？由此可以
想象一下七针能解决多少问题。比如临症治疗，针者可以运用单一的毫针做治疗，可以用大
号和小号毫针结合，也可以用大号和中号搭配进行治疗，可以只用员利针，可以只用中号员
利针，也可以只用小号员利针，也可以大号员利针与大针结合，当然根据需要也可以选择小
号员利针与大针鍉针等结合，又可以大针与毫针结合，还可以大针毫针员利针结合，也可以
鍉针员针员利针毫针锋针大针长针一起组合运用……等等等等，灵活多端，变化无穷，具体
运用的时候，还是对应法。

九针变化无穷，而世间各种医疗的方法也数不胜数，这么多的变数，毫无头绪，我们怎么办？
我还是抓核心。值得我追求的医术，必须符合以下五个条件：

. 第一是安全，有损伤、毒副作用、后遗症、冒风险之类的疗法统统拒绝。
. 第二是有效，没有疗效或疗效低下的医术，无论你多么科学传承多么久远，一律扔垃圾堆
里。
. 第三是疗效稳定，今天治明天复发，或治疗只缓解一年半载稍不留意就复发了，那也剔除
我的眼界范围。
. 第四是医疗成本低廉，我当然希望用最低的成本去获取合理的利润，我想，任何患者也不
希望为了治个腰腿痛就把自己变成了穷光蛋的事情发生在自己身上。
. 第五是医者的劳动强度要低，成为一名好医生可能需要十年二十年甚至三十年，而要成为
一名患者只需一分钟，如果治疗一两个患者就把医生累半死，那千千万万的患者又靠谁去帮
助？

这五条规则，能够荣获绝大多数人的认可，是一种非常合乎道理的排列对比法，所以任何医
术任何门派，大家都无需争执，按此标准来衡量就行了，谁高谁低，孰优孰劣，立判高下。
这样一来，我需要什么，不需要什么，思路立刻就清晰了。

基于以上的一些观念，所以我这么多年一直都在狂热的研究和挖掘《黄帝内经》九针，在我
看来，以上五项优点，《黄帝内经》的九针都具备了，我有什么理由不研究推广九针呢？抛
开别的一切不说，至少九针是非常的单纯而且无毒害的，他不像药材有假冒伪劣粗制滥造污
染质变等等充满了那么多的变数，九针受外因的影响就少了很多。比如立新七针，诊治思路
别人虽然没办法模仿，但针具有很多人在模仿制作，那些模仿的人，再怎么贪图利润，也不
会傻到用腐烂锈蚀的铁丝来代替医用不锈钢制作七针去给患者治疗，对不对？至少这些方面
我少了很多的担忧。

除了针具，在立新七针的诊治理论方面，病因分为内因和外因以及内外因，内因有七情六欲
五劳七伤志意等等，外因风寒湿暑燥火跌损地域环境工作习俗等等。无论内因或外因，都又
有君臣佐使之分，也是组合起来有万千变化，一个患者的病因，可能属于内因，也可能属于
外因，又可能内因大于外因，也可能外因大于内因。内因有主次之分，比如心病大于劳伤，
筋骨问题多于皮肉问题等等。外因之中又可能寒湿偏重，或风寒偏重，或风热偏重…这么复
杂的外因与内因再一混合搭配，又会产生多少种组合？无法想象。

所以要治好一个病，不是那么简单的事。但这些所有的无限的复杂之中，始终有个中心，那
就是抓住患者的“神”，所以为什么内经讲“恬淡虚无，真气从之，精神内守，病安从来”，
如果不抓住这个神，则医术流散无穷，病就很难治好。所以真正要运用好立新七针，绝对不
是模仿做几支七针（九针）那么简单的事，你只知做针，而不知运用法，意义何在？有的人
用仿制的七针运用西医解剖学活运动力学作为诊治理论指导运用，那是远远不足的。要知道，
立新七针是基于内经的诊治理论而研发的，你用这些针具去结合西医的那些理论，就好比穿
鞋一样，大脚穿小鞋，不合脚。真正要做好立新七针，除了懂得针具的结构功用之外，还必
须领悟阴阳、术数、机、四时、尺度、法天则地、援物比类等等这些理念，这些理念才是中
医的核心，古时候那些医术高明的中医，都是用这些理念去围绕着患者的“神”为核心，来
开展诊治的。

正如《素问》一开篇就说，那些“知道”者，“法于阴阳，合于术数”。《灵枢经》在第一
篇也强调“上守机，粗守关”，这个机，不仅仅指气机，气机只是最起码最基本的层面，机
更应该包括四时、法度、场境、状态……等等。从内经的角度，上工是不会局限于脏器经脉
筋骨皮肉这些物质层面思考和处理问题的，明理的医者一切行为都应该合于四时，法天则地，
援物比类。

所以中医人一定要养成一个很大气的思维习惯，把眼界和高度都放宽放长远，无论做事业做
学问诊治病患，都不要拘紧狭隘，这样你的格局就很大，自然之道的那些理念就会源源不断
涌入你的脑子里，你的医术想不提高都难。如果仅仅把眼睛放在物质层面，就会被局限，你
就永远只懂得模仿或剽窃别人，医术很难得到比较大的提高，也很容易产生很多的困惑。人
们很多时候都说，性格决定成败。在医这一领域，性格就决定医术层次的高低，一个格局很
小的人，心中本来就很小，还把大量的偏见、狭隘、嫉妒、纠结、计较、埋怨等等负能量充
斥内心，他还能有多少空间装真理？所以这种人一定很难成就大事，再怎么努力一辈子，最
多就是做个名医，要想成为一名真正的“明医”则很难很难。
