= 伤寒论讲稿
刘希彦
:toc:

== 2014-04-26（1-11）

=== 答疑

我首先来回答两个网友提出的问题。之所以选择这两个问题来回答，是因为这两个问题比较
有代表性。

有一个网友提出传统中医用人体的大秩序来理解人体，那，人体的大秩序又是什么呢？

我觉得这个问题提的非常的好。因为这是我们无论从中医来讲，还是说从本身传统中医和非
传统中医的区别来讲，我觉得这个问题是一个很关键的问题。对于我们理解人体、治疗疾病，
也是一个最关键的问题。那，下面我就来讲一讲，什么是人体的大秩序？

说到人体的大秩序，我们知道我们经常所说到的，经络理论，它就是对人体的秩序的一种描
述。经络就是十二经，就是肾经肝经胆经这些。我们说的五行理论，就是现在运用最广泛的
一个辨证理论，也是对人体秩序的一种理解。五行理论是什么呢？就是把人体的五脏对应金
木水火土，比方说肝克脾，脾克肾，肾克心，心克肺，肺克肝，它是这样一种生克关。，这
个大家可以去查，就是这样的一种五脏的生克关系，用这个来指导，用药物来治疗疾病。这
也是一种对人体秩序的理解。

那对人体秩序的理解还有很多。像彭子益呀，包括说黄元御呀，他们会提出圆运动，包括左
升右降，就是说人体的气血从左升从右降，还有人提出三枢开合理论。三枢开合理论我听群
里有人讨论过，不管他。这些理论事实上都是对人体秩序的理解。大家也会按他认为正确的
对人体秩序的理解、人体运行的理解来运用它治疗疾病，或者说运用它来理解他认为正确的
一些医学流派，理解伤寒论，甚至用它来解释伤寒论的辨证体系。那我要说的一个问题是，
那这些秩序他发生一个什么样的问题呢？

这些不同的理解，其实它都直接或者间接的出自于《黄帝内经》，那这些理解造成一个问题，
它让后世中医的辨证体系非常混乱，这种混乱大家就各执一词，各执一套，所以说就造成包
括用药上面的混乱。其实这种混乱就造成医学不往前发展的一种状况，为什么呢？因为大家
不能够统一起来，不能够统一起来就造了成点就分散了，力量分散了结果大家就都在一直都
在一个水平线上打转。

我说所有的这些经络理论，脏腑理论也好，左升右降也好，三枢开合也好，其实这些理论是
不是对的？都是对的。人体确实存在这些规律。但是有一个问题，对于人体而言哪一种运行、
哪一种秩序才是主流呢？其实对人体而言表里的运行才是主流，才是最大的力量。

我们能够生存，我们能够存活，靠的是脾胃吸收了营养，再通过其他脏器的配合，将这种营
养、能量往体表输送，然后将代谢的废物从里——从肠胃道，（通过）大小便排出。其他的运
行方式的力量，和这个表里循环的力量相比它太微弱了。我说的其他运行方式包括五行生克、
左升右降、三枢开合这些运行方式。相对于这种表里运行方式它太微弱了。为什么这么说呢？
我先举个例子。

现在中国的环境不好了，空气不好了，很多人跑到南亚去生活，现在都有人移民马来西亚的。
在南亚只有一个季节——夏季。我们知道季节的变化是天的五行运行能量场，事实上人的五行
运行能量场是配合天的。所以整个春夏秋冬四季的变化是影响整个人体内部的五行生克的最
大的一个影响力，人体之所以存在五行生克就是因为天存在春夏秋冬四季的变换。所以这是
人体最大的一个因素，是左右人体内部五行生克的。

这个在《黄帝内经》里是有明言的，他是说过的。但是你们有没有思考过一个问题，我们在
南亚一样能够健康的生存，身体一般来讲不会受太大的影响。那既然我们的五行生克，人体
的肝克脾脾克肾，这个大的运行到了南亚它会受到很大的影响，它运行不了了，因为天的这
个大的环境改变了，那为什么我们还可以健康的生存呢？说明这个运行的力量不是人体最关
键的。

那什么是人体最关键的呢？我说一点，如果说人的表里不通了，我们一天甚至一刻都活不下
去。我举个例子，一个肺炎病人，如果他不能够及时的解表退烧，24小时之内就能够报病危。

再看我们所有的治疗手段。比方说我们知道我们有汤液，《伤寒杂病论》讲的汤液学，开方。
那我们还有其他的主要是针灸，砭，熏，古时候还有砭和熏。不管是针灸砭熏这些个治疗手
段，我们的治病原理都是由表治里。就是通过人的体表来治人体的里面。所以说无论医学上
来讲还是说真正的人体的运行，人的表里的运行，这个力量是最大的，我们治病也可以由表
治里。所以说为什么用《伤寒杂病论》的辨证体系来指导治病能这么的有效呢？《伤寒论》
就是抓住了这个表里理论。伤寒杂病论的辨证体系就是六经辨证理论，六经辨证体系的实质
就是把人体分为表、分里，中间还有一个半表半里。它用这套辨证体系来运用的时候它确实
能够真正的抓到人体的主流。这才是人体运行的主流的秩序。

为什么《伤寒论》会用表里理论来治病？除了表里理论是人体运行的主流外，还有一个是药
物的问题，我们以前说过药物在人体里面、的作用是粗线条的，它只能走表里上下的大层面，
做不到微调，所以我们从那些五行的理论或者说三枢开合等的理论，从这些个相对人体作用
力比较微小的规律来理解人体使用药物的话，事实上等于是误解、误用了药物，因为药物做
不到这种微调。

我们再来进一步思考这个问题，为什么古人使用药物和针石，就是针灸、砭熏之类的来治病
呢？而不是别的方式呢？比方说我们自古以来就有中医的外科手术。华佗就是代表，咱不说
华佗。文革的时候还有外国的纪录片的导演在中国的农村，拍到过完全针灸麻醉的中医剖腹
产，就是中医的外科手术可以做到剖腹产。这个事情网上是有的，大家有兴趣可以去查一下。
我们知道手术治疗是直接去人体内部做定点治疗的。

手术治疗就是把人体打开，哪里有病，直接去做定点治疗。针灸治疗是在人体的外部做定点
治疗，由外治内。那为什么说我们中国的中医明明有外科手术，却没有普及这种治疗方式呢？
说明我们的古人已经认识到，人体是可以通过大层面的治疗，不需要定点，而且是通过由表
治里的方式进行治疗。所以我们不需要从人体内部进行伤害性的治疗。

我们现在的中医主要使用脏腑辨证，就是我说的五行辨证，将这些疾病归结为肝的问题、脾
的问题、气的问题、血的问题，然后用药去调肝脾气血，后世中医在本质上已经接近西医的
内部定点思维了，就像西医的的手术叫内部定点思维，而偏离的传统中医的真正的整体观。
你把这个病定位为就是肝、就是脾的问题，它其实是个大运行嘛。以至于中医越来越背离了
其真正的传统，以至于世人说中医只能调理，中医治病慢。因为我们主要是在用定点思维来
看待人体的，相对于西医的某个病灶（的说法），它也是五十步笑百步，它并没有一种人体
整体的秩序观。

所以说我们从大的方面去理解人体，让药物做到它所能做到的，将大的方面治理好了，人体
是一个有自我组织、恢复能力的系统，小的方面也就跟着好了。但是你如果从小的方面着手，
你终将被大的方面、大的运行，像这种表里大运行这个大能量场，你只去调理这个肝克脾脾
克肾，用五行方式去治病，你调理又能怎么样呢？对不对，最后终将被这个大的运行，像这
个表里运行，你受它的制约，你就调不好。所以说你用大的表里运行作为着眼点，你参考经
络和脏腑的运行去认识人体，这就是六经辨证，就是《伤寒论》里的六经辨证的实质，是目
前最有疗效的一套汤液学的辨证方式。其实后世的人是为了理解和解释《伤寒论》里的六经
辨证体系，他们参考了《黄帝内经》里许多细微末节的辨证法，去解释《伤寒论》，去附会，
像前面提过的三枢开合啊、左升右降啊、五行脏腑生克啊，实质上你忽略了大的方面实际上
就是造成了一种对人体、对医学的误解。

所以我刚才讲的就是人体的秩序，所以说，其实在《伤寒论》理人体的秩序很简单，人体的
秩序就是表里关系，就是表里的运行，所以我刚才就是从很多方面来阐述这个问题，供大家
参考。

我现在回答第二个问题。有一个朋友问了，你提到“汗出症”用炮附子，白芍不是敛汗敛阴的
吗？为什么“汗出症”不重要白芍，而重用炮附子呢？

为什么回答这个问题？这个问题又牵扯到我们作为传统中医的一个大的思维方式。就是药物
既不治病，也不治症状。药物做不到去敛汗，我曾经说过出汗和敛汗这些都是人体的无数条
神经，包括他的各方面的配合，人体所发出的一个指令，药物也不能够代替人体去发出这个
指令。那么药物是不治病的，药物也不能替人体发指令，那药物是做什么的呢？

我举一个例子哈，有一个这样的医案，有一个病人呢他腹水了。他得了腹水这个病，那是一
个比较严重的内脏的病了。他腹水了之后呢，医生一来用药不外乎用祛湿啊、利水啊、健脾
啊、破淤啊，这样的方式，久治不愈，腹水没有好。有一个医生一来就给他开了两味药，90
克白芍，30克阿胶，那我们就要说了，白芍阿胶这两味药，用后世医学的讲法你腹水了，你
怎么能用养阴药呢？但是用了这两味养阴药结果是什么样的呢？

用了这两味药之后，90克白芍，30克阿胶，非常大的计量，用完了之后这个病人的腹水下来
了，腹水消了。所以说我举这个医案的例子，就是说明后世医家、后世的辨证体系对药物的
理解是完全错误的，没有一个药物能够祛湿，没有一个药物能够利水，没有一个药物能够止
汗，没有一个药物能够敛汗，它起不到这个作用，药物只是在恢复人体秩序。药物只是恢复
人体秩序！所以说当这个人的人体需要阴性物质来让它恢复到秩序平衡的时候，他用了白芍
和阿胶也一样能够去腹水；当这个人体个需要阳性物质恢复秩序的时候，你用了姜，你用了
桂，也一样能够去腹水。所以为什么后世中医走入不是中医、背离中医的境地，就是因为，
我们现在所见到的医书都是这样写药物的：这个药利水，这个药健脾，这个药……它不说这个
药的本体作用，我们真的不知道药到底能干嘛，我们只知道它有很多用，但这些用呢，有的
时候管用，有的时候就不管用。所以说我们学药要学体。

总结一下今天回答的这两个问题。事实上我们在这里探讨研究真正的传统中医，汉代之前的
道家传统中医，就是因为我们要回到本源。第一我们要用真正的人体的规律来思考人体，我
们要用真正的药物的规律来思考药物。而不是后世所说的混乱的辨证体系，也不是后世所说
的这个药物止咳，那个药物利尿。这都不是本源，这都走入了小道。走入小道的结果就造成
了混乱和疗效不理想。我们只能说《伤寒论》的东西用好了之后‘效如桴鼓，覆杯而愈’，那
为什么我做不到呢？因为后世的很多理解本来就偏离了道，偏离了真正的人体规律和药物规
律。所以说我们这一次来向大家讲《伤寒论》就是为了（让大家）重新理解真正的中医的原
则、中医的精神！今天选这两个问题就是因为它们牵扯到的是一些大的原则、大的规律。

谢谢大家！

=== 条文讲解

大家晚上好，我们这次学习交流的是医圣张仲景的《伤寒杂病论》。

我们知道，历代名家都对此书推崇倍至，历代经得起检验的汤液家无一不是精研伤寒的。此
书中的药方是属于经方的范畴。经方这个概念我就不多做解释，有兴趣的朋友可以自己去查
资料看看。

对于经方，自古就有这样的说法，说只要使用得当，就能有“覆杯而愈”的效果。所谓“覆杯
而愈”，就是说喝完药，把杯子洗了扣在桌上，病就好了。这个听起来好像不可思议，以我
个人的临证经验，还是所言不虚的。如果辨证准确，外感病只需要半剂药，上午吃下午好，
晚上吃早上好，该退烧的会退烧，该止泻的会止泻。慢性病也是几剂药就会有明显效果，甚
至是几剂药治愈的也有很多。绝对不是现在所说的中药慢。慢的那是后世中医，而不是真正
的传统中医。我看这里研究《伤寒论》的人很多，相信也有过这样的经验。

历代能够参透这本书的寥寥无几，原因是张仲景在这本书里没有系统的讲述他的医学理论。
这就好比一本武功秘笈，只有招数，在对人体的思考和组方规律上，没有详尽系统的内功心
法。加之又是一本残书，经过历代流传还有错简以及后人加上去的一些自相矛盾的东西，所
以历代能真正学通这本书的人是少之又少，很多人只能高山仰止。

现今对《伤寒论》的研究，很多只停留在依葫芦画瓢的阶段。在临证上，只要能够与书中的
方证对应上，就能有极好的治疗效果，书中没有提及的，或者那些似是而非的症状，分析起
来就有困难了，选方就没有把握，自己组方效果又不理想。《伤寒杂病论》的行文方式是极
简的，不过寥寥几万字，而疾病的反应又千变万化，哪能够一一对应呢？

胡希恕先生，大家都很熟悉了，是一个很好的经方名家，他提出辨证的最高境界是方证对应，
推崇原方原剂量。实际上，张仲景教的是加减变化之道，比方说他用桂枝汤变化出几十个方
子来，灵活治疗人体各种各样的证和疾病。胡希恕当然明白这个，他之所以不赞成加减变化，
是因为我们还没有弄清楚组方后面的原理。

这样就有了一个新课题：张仲景到底是如何思考人体，他的组方用药的原理是什么，这些药
物又是怎样在人体当中起作用？只有弄清楚这些问题，我们才能真正的学到“仲景之法”，而
不只在临“仲景之方”，才能像张仲景一样用简单的几十味药物因证组方，以一御万，而效如
桴鼓。

这一次，我们是用道家思想为理论基础来破解《伤寒杂病论》的内功心法。此心法和道家思
想有什么联系呢？我们知道，中国的文化在汉代之前主要是以道家思想为指导的，汉代后才
是主要以儒家思想为指导。张仲景是东汉以前汤液学的集大成者，此中的联系不言而喻。

要用道家思想解读《伤寒杂病论》，那就先要讲两个本体上的问题：

第一个问题是，人类到底有没有治病的药？

我的答案是人类是没有治病的药的。为什么？打个比方，我们创造了一台电脑，造了一台洗
衣机，我们今天就可以修电脑，今天就可以修洗衣机。而我们人呢？人是造物主造的，是上
帝造的最精密的仪器，是被造物。从哲学上来讲，我们永远修不了自己，除非我们有和上帝
同等的智慧，就好像一台洗衣机永远不可能修它自己一样。

既然说我们修不了自己，那医疗又是什么呢？先从西医说起。西医领域一直在致力于研究治
病的药，那西医领域到底有没有治病的药呢？先说感冒，现在大家都知道了，抗生素不是感
冒的特效药。在国外门诊，大夫是没有权利随便开抗生素的，若开了，他可能会面临吊销执
照的处罚。

那问题就来了，既然抗生素不是感冒的特效药，那感冒的特效药又在哪里呢？医学界的答案
是没有。如果感冒都没有特效药，那别的病呢？自然更没有特效药了。比方说糖尿病、高血
压，我们都知道，终身服药。这些药是控制血压，控制血糖，但不能治愈。不但治不好还伤
肝肾，因为服用这些药物引起肝肾衰竭的病人现在很多。如果病严重了呢，就是手术，把坏
掉的器官切割或置换。然后就是排异反应，因为不是你的器官人体不接受。这种治疗追求的
是五年存活期，如果能存活五年就算治愈。

那中医领域有没有能治病的药呢？一样没有。既然没有，为什么还要做中医？因为中医是靠
自体免疫力治病的。能够对抗疾病的只有人体自身的免疫力。因为我们人体的免疫基因链足
够对付已知的一切疾病。比方说爱滋病，人体免疫力一般的，能抵抗爱滋病十几二十年不发
病。个别免疫力极强的终生不发病。癌症非典之类的自愈的就更多了。既然人体免疫力能够
对付疾病，为什么还会生病呢？是因为我们的免疫力受到了抑制。真正的传统中医是反对用
药去治病的，而是着眼于恢复人体的秩序，然后让免疫力自己去治病。真正能“覆杯而愈”的
只能是人体自己，而不是药物。

第二个问题，传统中医和非传统中医的区别是什么？

我个人区分传统中医和非传统中医是以汉代为界的。

先说非传统中医。非传统中医是以药治症的。什么是症呢？比方说我们后世中医经常说的脾
虚肾虚痰湿淤血就是症。

我举一个病例来说明这个问题。男子的虚劳房事类疾病，后世中医大都从肾论治，分肾阴虚
还是肾阳虚。如果是肾阴虚，用生地熟地之类的滋阴药；如果是肾阳虚，那就是苁蓉巴戟天
杜仲这类的药。我早年学过很长时间的后世中医，我知道用这类药效果不会太好，暂时会有
缓解，往往牵延不愈，有时补肾药吃多了甚至于还会上火。《伤寒论》里有一个桂枝加龙骨
牡蛎汤，没有一味补肾药，治这个病却效如桴鼓，辨证准确了几剂药就能治好。桂枝加龙骨
牡蛎汤之所以能治好这个病，是因为它没有拿药直接去补肾，而是着眼于人体的大循环，人
体的循环恢复了，津血运化归肾，它的肾气自然就会增强。如果人体自己不能补肾，又有什
么药能直接补肾呢？兴许能隔山打牛的补一点，却起不到根本的作用。这就是后世医家治病
动辄给病人吃几个月的药，收效却不明显的道理。

再如治肿瘤类疾病，一般从淤血痰湿论治。我看现在的医生动不动一张大方子，几十味活血
化瘀消痞散结的药，如果人体大秩序没有恢复，自己就不散结，只用这些药无异于扬汤止沸。

《伤寒杂病论》的治病思想是道家的，就是不妄自作为，不干预天和，不代人体去治病。而
是致力于恢复人体秩序从而让人体自己去治病。

说到药，又牵出了另一个问题，既然药物不能治症，那药物学上所说的补肺补脾发汗通便又
怎么理解？其实这些说法也都是不可靠的。举例说明：我们常说桂枝是发汗的，学过《伤寒
论》的都知道，桂枝也可以用来止汗。白术这味药，后世说它健脾止泻。北京有个大夫，经
常用大剂量的白术治便秘，大剂量的白术一下去，大便就通了。到底桂枝是发汗还是止汗？
白术是通便还是止泻？其实这都是后世医家的说法。通便止泻哪能是药物能够做到的，这是
人体自身无数条神经配合而形成的一个指令，药物本身不能够代替人体来行使这个指令。药
物只是平衡人体的阴阳，恢复人体的秩序，然后由人体自己来下这个指令。比如桂枝，它只
是把阳气送到肌肉组织，表的阳气够了，它该出汗会出汗，该止汗会止汗；白术是气化中焦
的，中焦气化，津液得以运行，该止泻会止泻，该通便会通便。

真正的传统中医就是一把钥匙，用来打开人体免疫力的这把锁。西医致力于用药去治病灶，
后世中医致力于用药物去针对于某个病症，事实上都是不妥当的。这就是道家所谓的“无为
而无不为”，喜欢文化的朋友可以去研究这些哲学上的东西。

上次课我们讲了一些基本的道家传统中医观念。《伤寒》的核心辨证体系，六经辨证只讲了
一部分。因为这次有一些新来的朋友，我再将六经辨证从头讲一下，然后开始进入《伤寒论》
的学习。

《伤寒》的辨证体系是六经辨证。

何为“六经”？就是将“证”反应的位置分为表、里、半表半里三个层面。（《伤寒》里所谓的
“证”不是西医所指的病灶，而是人体对疾病所呈现出来的反应。如体痛、呕吐、发热、胁胀、
眩晕等。） 所谓“表”，指的是肌肉、骨骼、皮肤这个区域。

所谓“里”，指的是胃肠消化道这个区域。

所谓“半表半里”，就是除去“表”和“里”这两个区域之外广大的中间区域。 上面说的是位置。
从“病”的性质来说，有阴证和阳证。 何为阴证阳证？临证上，如果人体对疾病的抵抗产生
亢盛的反应，我们称之为阳证；如果人体对疾病产生虚衰的反应我们称之为阴证。

以感冒为例，我们区分风寒感冒和风热感冒，不是看这个病人受的是寒，还是受的是热，而
是看这个病人身体本身对感冒的反应，自体气血充足的人，一般都发烦渴、怕热之类的阳证
热症；自体气血虚少的人，一般都发畏冷、寒泄之类的阴证寒症， 脉象反应自体的气血盛
衰是最准确的。有的医生通过网络和电话看病，最大的障碍也在于此，没有脉象，单凭问诊，
对于阴阳的属性和程度很难有一个精准的判断。

既然病的属性有阴阳之分，表、里、半表半里三个层面自然各有一组阴阳，于是便形成了
“六经”。表病的阳证我们称之为“太阳病”，阴证称之为“少阴病”；里病的阳证我们称之为
“阳明病”，阴证称之为“太阴病”；半表半里的阳证我们称之为“少阳病”；阴证称之为“厥阴
病”。此所谓“六经”，是六经辨证之总纲。

我们知道，后世中医多用五行辨证、脏腑辨证、经络辨证等等。《黄帝内经》里提到的辨证
方式也是这些。为什么张仲景要在《黄帝内经》之外提出一套六经辨证呢？要破解张仲景的
组方用药规律，就必须弄清这个问题。 这个问题要在药物上找答案。后世常说某个药入肝
经入胆经入肾经，事实上药物不是智能的，不能定位。举例说明，黄芩这味药，大家都知道，
苦寒药，后世说它清肺火清胃火，也有说它清肝火清大肠火，说法不一。都对也都不对，只
能说明一个问题，药物并不能单独走到某一个脏腑或某一个经络，药物只能走层面。我们吃
辣椒，一吃额头有汗后背有汗，说明辣椒这味药它走表。大黄这味药，一吃就腹泻，说明它
走里走下。事实上药物只能走表里、或半表半里，不能精确到只走肝经只走胆经只走胃经。
张仲景在《黄帝内经》的学说之外提出一个六经辨证体系，就是为了指导用药物治病的。
《黄帝内经》里的辨证体系主要是指导针灸砭之类的疗法的，这些治疗是可以定位的，所以
《黄帝内经》里很少出方子。 很多人在争论《黄帝内经》里的辨证体系正确，还是仲景的
六经辨证体系正确，都正确，分工不一样。 那六经辨证和脏腑经络辨证是不是矛盾的呢？
据我的研究，它们并不矛盾。在张仲景的理论体系里头，脏腑经络虽不能涵盖六经，六经却
能涵盖脏腑经络，因为六经是大层面，大层面里面自然能包涵具体的脏腑经络层面。比方说，
“太阴”在六经里指“里”这个层面，自然也包含着这个层面相关的脏腑和经络，手太阴肺经和
足太阴脾经。其它经络脏腑看其归经的名称就可知道，都可以分属在六经里头，不一一例举。

现在出现一个新问题，既然肺经和脾经都络太阴，太阴又是里阴证，难道肺和脾就只是寒症
就没有热症吗？说明这个之前，先说一下什么是脏腑。 “脏”指的是五脏：心、肝、脾、肺。
肾。

“腑”指的是六腑：胆、胃、大肠、小肠、膀胱、三焦。

脏主收藏，腑主传化。脏主阴，腑主阳。“脏”所连络的都是阴经；“腑”所连络的都是阳经。
为什么？因为脏是不能受热的。比如说，我们吃过动物的肝脏肾脏肺脏，下锅只要炒几下就
熟了，可见“脏”不耐热，于是人体会将“脏”的热移于“腑”。因此脾没有热症，热会移于胃，
胃是阳明。以此类推，肝移热于胆；肾移热于膀胱；心移热于小肠；肺移热于大肠。下热利
的脉象往往右尺不盛而右寸盛，寸盛主热在上在肺，为什么症状是下热利呢？因为肺的热会
通过大肠排出去，肺受热就麻烦了。这是脏腑之间的规律和协作。

将经络脏腑观念引入六经辨证，在临证上有没有意义呢？ 是有意义的。举个例子说明。胡
希恕先生曾总结过，肾腹水用越婢汤有效果，而肝腹水用柴胡方才有效果，为什么？胡老说
他解释不清楚。其实只要参考经络脏腑就能解释：肾经既称足少阴肾经，少阴经在六经里是
表经，说明肾经是络表的，自然可以从表论治，越婢汤是治表病的方子，自然治肾腹水有用。
肝经既称足厥阴肝经，厥阴经在六经是半表半里经，可以理解为肝经是络半表半里的，柴胡
方是治半表半里的，所以治肝腹水有用。 再举一个药物的例子，在《伤寒》里常用炮附子
温下寒，下焦主肾，于是后世说的炮附子温肾阳。当阴症的出汗不止时，张仲景是用炮附子
来止汗的。为什么所谓温肾阳的药能止汗呢？因为汗出是表证，而肾经是络表的。所以温下
焦温肾的药也可以治阴症的出汗。 这就是张仲景对于六经和脏腑经络的思考方法，他虽然
没有在书中明确解释，却是可以通过他的组方用药规律和临证的效果反推出来的。我所研究
的仲景六经辨证体系，就是这样一套以六经统脏腑经络的辨证体系，如此一打通，在临证上
会有无穷的妙用，也便于在一个统一可靠的辨证体系里头理解和归纳后世的时方，具体的思
辨方式以后再在条文里细讲。

《伤寒》是以六经为辨证体系治病的。我们看每一个病事实上就是用六经这个定位系统在操
作。六经既明，我们开始正式进入《伤寒》正文。 先讲太阳病篇，

1、 太阳之为病，脉浮，头项强痛而恶寒。

这是太阳病的总纲，所谓总纲就是太阳病典型的证。 我们上面说过，中医不是治病灶的，
所以不管是什么病毒感冒非病毒感冒，也不管什么典型肺炎非典型肺炎。我们看的是人体对
这个病的反应，通过这种自体反应来分析人体，以此为依据来组方恢复人体秩序，让人体自
己去治病。所以作为太阳病的总纲是一些人体的反应，而不是病毒本身。这也就是为什么中
医不分科，好的中医大夫个人就是一所医院，可以治一切的病。只要发生同样的证，不管是
外感病和内伤病，用同样的方子都能治好。后世说《伤寒论》适合治外感病而不适合治内伤
病，说这话的人这是没有学透《伤寒论》，运用不当，然后归咎于《伤寒论》。

现在一个一个的证来分析。

何为“脉浮”，当体表感受到外界的邪气的时候，气血会本能的往体表走，去驱赶这个邪气。
而脉象和人体气血是相应的，于是脉浮于表，手指轻取就能摸到。 我们人每时每刻都在感
受外界的邪气。比如，走到外头风一吹，一个激灵，我们就已经感冒了。多数情况下，人体
的气血功能可以将这个邪气驱赶出去，所以不会发生感冒的症状。在自体功能相对薄弱的情
况下，气血和邪气在体表僵持住了，于是就发生了太阳病。 “头项强痛”，气血不能驱邪外
出，就要源源不断的增加兵力，多余的气血上冲于头就会发生头痛。气血往体表走，脖子里
的筋受到的滋养不够了，就会僵硬，发生项强。 “恶寒”，当体表的气血有余，体表温度就
会升高形成发烧，这就与外界有一个温差，所以会觉得怕冷些。一般来讲，当体表气血充实，
人应该不怕冷才对，可是，如果因为体表汇聚了过多气血，体内因此而空虚了的话，表热内
寒，这个人还是会怕冷的。如果发烧还怕热的话，就是温病了。 治病求其理，我们不能只
大概其理解，一定要把为什么出现这个症状，人体的规律是什么弄清楚。 以后还要把人体
和药物的关系完全弄清楚，不能模糊，不能大概其，这才叫学医。

2、 太阳病，发热、汗出、恶风、脉缓者，名为中风。

下面讲第二条， 太阳病有三个证型，一为中风，二为伤寒，三为温病。中风和伤寒是气血
功能偏向于不足的（未至虚衰，虚衰为阴症。）；温病是气血功能偏向于亢盛的。这一条说
的是中风。 “发热”，说到发烧，现在大家对这个很恐惧，只要一发烧，迫不及待的用抗生
素或者物理降温。这个观念不对。上帝造人为什么要造出疾病这个模式？说到底这是一个应
激模式，自保模式。可以这样说，如果没有疾病，我们一刻都活不下去。比如，如果没有发
烧这个模式，一旦感受了寒气，怎么能排出体外？体表的寒气驱除出去，人体自然会退烧，
强行退烧反而容易演变成肺炎或慢性低烧，因为邪气没有驱除，人体不会解除发烧这个模式。
西医是对抗思路，所以经常把急性病治成慢性病。道家中医要顺应人体来想问题，所以道家
中医不会把疾病看成敌人，而是看成朋友。我们要与人体和解，让疾病自退，对抗疾病的结
果常常是病治不好，人体的局面还更混乱了，一个病治成了多个病，并发症后遗症转移什么
的都来了。 “汗出”。人体有三个途径将邪气赶出体外：汗、吐、下。就是发汗、呕吐和大
小便。如今汗出而病未解，毛孔打开了，津液丧失了，肌表空虚，邪气往往就更深入了。
为什么会有“恶风”呢？一旦毛孔打开了，人当然会怕风；恶风也是一种虚怯的反应，津血虚
的人往往会怕风，所谓弱不禁风就是这个意思。 “脉缓”。感冒了，气血往体表汇聚形成脉
浮；如果不能发汗，气血被束缚，便会形成“脉紧”，就是像绳子一样绷得紧紧的；一旦汗出
了，脉便迟缓松懈了。这就是脉缓的道理。

太阳病，或已发热，或未发热，必恶寒、体痛、呕逆、脉阴阳俱紧者，名为伤寒。

之前说过，不管有没有发热，气血往体表汇集，里面空虚了，人都会感到“恶寒”。如果人体
不能发汗，气血郁于肌肉之内不得出，就会感到“体痛”。

“呕逆”的原因有二：一是气血的运行是要先往上走才能往表走，这种往上的运行会带动胃有
一种上逆的反应，此为“逆”；二是当气血大量往体表走的时候，胃所获得的气血会相应减少，
运化食物的能力减弱，胃就会产生一种本能的呕吐反应，将不能接纳的食物呕吐出去，此为
“呕”。 “脉阴阳俱紧”，脉的阴阳有三：越偏寸越主阳，越偏尺越主阴；左手偏血偏阴，右
手偏气偏阳；越沉越主阴，越浮越主阳。因为不能汗出，气血郁于体表，于是脉紧。 脉学
是个专门的学问，以后有机会我再专门用一堂课来讲。现在只需要知道个大概， 区别伤寒
和中风最直接的鉴别方法就是有没有汗出，汗出的为中风，不汗的为伤寒。但这不是最本质
的鉴别方法，本质的鉴别方法是津液的盛衰。

4、伤寒一日，太阳受之。脉若静者，为不传；颇欲吐，若躁烦，脉数急者，为传也。

5、伤寒二三日，阳明、少阳证不见者，为不传也。

这里讲的是一个传经的道理，“颇欲吐”传的是少阳，这是少阳病的证。“烦躁”传的是阳明，
这是阳明病的证。少阳和阳明以后会专门讲到。感冒是个急剧变化的病，如果两三天不传也
就不会传了，因为正常来讲，三四天也就好了。

6、太阳病，发热而渴，不恶寒者，为温病。若发汗已，身灼热者，名风温。风温为病，脉
阴阳俱浮，自汗出，身重，多眠睡，鼻息必鼾，语言难出。若被下者，小便不利，直视失溲。
若被火者，微发黄色。剧则如惊痫，时瘛疭，若火熏之，一逆尚引日，再逆促命期。

这一条讲温病。我们之前说过，伤寒和中风是气血功能呈不足反应的证型，温病是气血功能
呈亢盛反应的证型。伤寒和中风的区别在于汗与不汗。温病分普通温病和风温，区别也是汗
与不汗。其实汗只是个现象，它的本质是看津液有没有丧失。仲景的整个辨证体系就是以津
血的盛衰来作为阴阳判断标准并组方用药的。 温病的纲领是“发热而渴，不恶寒者”。“渴”
是内有热的渴；“不恶寒”说明气血虽往体表走，里面却并不空虚，所以发热而不恶寒。既然
是温病，为什么不直接说怕热呢？这就要说一下温病的原理了：我们如果平时吃多了饮食，
身体消耗不掉，人体就要烧掉这些多余的能量，如果一时不能完全代谢，这就产生了有热上
火的反应，就是温病。温病不一定要有外邪诱发，自体也会发病。如果再感受外邪，毛孔一
闭塞，温病就会加重，这就是“热伤风”的道理。如果汗出而解了，也就没有温病了，所以温
病往往是里面热，体表感觉并不一定热，如果热烧不出来，一般只是不恶寒；当然，严重的
温病是表里俱热的；轻微的温病，病人甚至有怕冷的现象，只是这种怕冷并不感觉需要多穿
衣服。 “若发汗已，身灼热者，名风温。”温病若出汗，说明里面的能量从体表排出来了，
体表自然会感觉到灼热。一般情况下，汗出了病也就好了，如果身体持续灼热，说明热邪还
没有排除完。外汗耗散了津液，加上里热也烧灼津液，便产生了津液不足的现象，这就叫风
温。中风和风温，只要带个风字的，都有津液不足。 风温的症状是“脉阴阳俱浮”，说明病
在表，所以“自汗出”；因为要不断自汗出，肌肉里会积累过多津液，所以“身重”。“多眠睡”
也是温病的表现，因为热往大脑走，人就昏昏欲睡，春夏天人爱犯困，一坐有暖风的车人就
犯困，也是这个道理。当身体里有过多的热，呼吸自然要加重以帮助排出热能，所以“鼻息
必鼾”。这一条在儿科很有用，幼儿不能摸脉，也不能问证，感冒了怎么辨别是热证是寒证
呢？一般来讲，呼吸粗重，大便臭，打屁多，面色赤红，鼻孔干的是热证。幼儿的阳气是最
旺的时候，加之家长生怕饿着了，不停的喂食，肠胃容易囤积，多发热证。现在很多家长一
见孩子感冒，不分寒热就急着添衣服捂被子，于是造成高烧肺炎进医院。 下面讲的都是典
型的津液虚的反应， “语言难出”，当人体津液虚的时候，首先就是筋膜结缔组织缺少滋养
了，因为这里面的血管少，容易缺少津液，舌头里面主要是筋，所以就不灵活了，说不出话
了。若医生再误治，下泻药，更伤津液，于是便产生“小便不利”，已无尿可下。再严重则
“直视失溲”，眼睛直了，眼睛里的筋络失去滋养；膀胱也是结缔组织，膀胱失去滋养，约束
力丧失了，便“失溲”，也就是小便失禁。“若被火者”，若用火熏蒸之类的方法误治，热蒸郁
于肌肉，便“微发黄色”，也就是发黄疸。津液再严重丧失，便“如惊痫，时瘛疭”，也就是相
关大脑的惊厥惊恐反应。 为什么大脑会发生这样的反应呢？这个需要顺应人体来理解，人
体让哪个地方兴奋起来，就是往哪个地方调集津液，这是人体的基本模式，惊恐说明大脑缺
津液了。后世治疗这种证一般用定惊止痉的药，什么蝎子蜈蚣川芎的，全部是些通窜化瘀药，
这就是不顺应人体想问题，典型的头痛医头脚痛医脚。《伤寒》里是用白虎汤下热救津。到
了这个阶段就已经很严重了，因为人体的自保模式一定是先保护大脑，大脑出问题了，一定
是极期反应，若再用“火熏之”，“一逆尚引日，再逆促命期”，一次逆治可能还能支撑些日子；
再次逆治，病人很快就会死亡。

我们说，治病分六经，六经之一的太阳经的三个证型，中风、伤寒和温病，其原理至此都讲
完了。可见学医不难，真正的医就是用简单的东西去对付万病的。

下面的几条是讲一些中医文化上的东西，当然跟证也有关系。了解了解，就当轻松一下。

7、病有发热恶寒者，发于阳也；无热恶寒者，发于阴也。发于阳，七日愈；发于阴，六日
愈。以阳数七、阴数六故也。

前面说过，恶寒主要是体内津血虚少的原因。若体表还能发热，则是“发于阳”，是太阳病；
若体表不能发热，则是更虚了，“发于阴”，是少阴病了。 至于六和七，这两个数字很有意
思，《易经》里一个卦就是六个爻，到了七就变了，这是东方人特有的哲学和计算法。西方
呢，上帝造人用了六天，第七天是休息日，也是这两个数。从人体来说，女子七年一个生命
周期，七七四十九岁就是更年期。从天气来说，一般一次寒流也就是六七天，必定会转暖。
无论是宇宙还是人体，这两个数字好像都适用。中国文化是天人之学，中医更是天人之学，
因为人是天地的一个部分。这些问题有兴趣的朋友可以去深入研究，这对道家传统中医的恢
复是有大作用的。限于时间，在这里就先不详做解释了。在《伤寒》里，张仲景也没有详细
解释易理，而是把大道化为通俗易懂的语言和切实可行的操作方法，目的就是让百姓“日用
而不知”，这才是圣人之道。反而是后世的中医喜欢五行八卦的谈一大堆玄学，让人看不懂，
真推敲起来里面未必有真正的道。

8、太阳病，头痛至七日以上自愈者，以行其经尽故也。若欲做再经者，针足阳明，使经不
传则愈。

9、太阳病，欲解时，从巳至未上。

10、风家，表解而不了了者，十二日愈。

上面说过， 古人对天地的计算法是《易经》，所以现在看见这样的条文就不好懂了。有的
人直接斥之为迷信。西方文明几百年就把地球破坏了，就是因为他们没有意识到很多被他们
称之为迷信的东西很可能是真正的宇宙科学。真要发扬中医，建议中国医药大学首先开一门
《易经》课，而不是学什么物理化学代数几何。当然，这是不可能的，他们连什么是传统中
医还没搞明白，哪里谈得到这些，所以就靠我们真正热爱文化的人来做了。

针灸上得问题，因为是另一个学科，这里统一先不做解释。如果有感兴趣的，可以去请教群
主夏正安，他在这方面很在行。

11、病人身大热，反欲得衣者，热在皮肤，寒在骨髓也，身大寒，反不欲近衣者，寒在皮肤，
热在骨髓也。

这里说的是里外阴阳不交通的情况。病人感觉身热，能量气血都在体表了，如果不往里回，
里面就更空虚了，里面就寒。所以这样的病人虽然体表发热，却还是感觉恶寒，且欲加衣服
盖被子。有时候，病人是里热，外面却感觉怕冷，因为热郁在里面出不来，这种情况虽冷，
却不愿意多穿衣服，甚至还想脱衣服。 这种情况往往是因为体内有痰饮、宿食或者淤血之
类的原因造成的。人体是一个不断运行着的能量场，一旦哪里有阻塞，上下表里就容易不交
通。治病求其本，以里为准，里寒则是寒证，里热则是热证；该温里寒温里寒，该去里热去
里热，该去瘀滞去瘀滞，不要被表面现象迷惑。表里交通了，能量就平衡了。

下一条是桂枝汤，就开始教怎样组方开药了。我会结合一些临床经验来教大家如何理解药物，
如何治病。相信大家到时候更会感觉到中医并不难。 今天就讲到这里，谢谢大家。

== 2014-05-03（12-22）

大家好，今天接着讲伤寒论。讲的是桂枝汤。

12、 太阳中风，阳浮而阴弱。阳浮者，热自发；阴弱者，汗自出。啬啬恶寒，淅淅恶风，
翕翕发热，鼻鸣干呕者，桂枝汤主之。这一条讲中风的治法。

先说脉象，“阳浮而阴弱”（脉之阴阳请参看第3条）。阳浮说明病在表，所以发热；阴弱，
说明津液虚了，汗出所致。

恶寒、发热是太阳病的主证。“汗出”、“恶风”表明津液虚了，这是太阳中风，也就是桂枝汤
的主证。

“鼻鸣”是感冒常见的症状，人体的气血大量往体表走时，壅塞多余的气血自然会往上冲到头
部，就会形成鼻腔充血，于是鼻塞鼻鸣，同时也能阻止邪气进入肺部，人体就是这样设计的。
我去医院，看到耳鼻喉科有很多治鼻炎的在熏洗鼻子，很荒谬。鼻炎不管是什么原因诱发的，
实质在于表气不通，感冒的时候你们可以去体会，如果一开始不出汗，只要微有汗出，鼻子
马上就通了，光去洗鼻怎么行？有的洗成了慢性鼻腔疾病又去做手术，然后得空鼻症。空鼻
症极度痛苦，这种病人自杀的，向医院维权的很多。

现在又有一个问题，为什么太阳中风有汗出了还会鼻鸣呢？治感冒是微有汗出才会解，如果
汗出多了，精气过多丧失，正气消耗，不但不解，病反而会趁机深入，便形成了中风。邪气
不去，气血自然还是会大量往体表往头部走，所以还是会有鼻鸣。

“干呕”，当气血往上往体表走时，里就空虚了，于是胃会虚弱，接纳不了食物，就会有呕的
反应。表气还并不完全通畅时，气血就会往上逆，也会加重呕。干呕则说明胃里是空虚的。
“胃家实”就不是太阳病了，是阳明病了。

上面是桂枝汤证的现象，现在来说桂枝汤 [桂枝汤方：桂枝 三两（去皮） 芍药 三两 甘草
二两（炙） 生姜 三两（切） 大枣 十二枚（擘）] 的方义。中风这个证是已经汗出而病不
解，好比打了一仗没打赢，兵力丧失了，津液也虚了，脾胃也弱了，想再战就必须先建中，
建中洲之运化，生脾胃之津液。前面说过，仲景的整个辨证体系是以津血的盛衰来作为阴证
阳证的划分标准并组方用药的。那津血从何而来呢，津血自然是从脾胃运化而来。脾胃好比
汽车的发动机，是一切动能的来源。在《伤寒》的原则里，治病首先要守中建中，就是守中
土，建脾胃之运化。脾胃都不运化，津血都不生成，谈何自体免疫力，谈何治病？

建中用什么药呢？《伤寒》里是四味药，人参、姜、炙甘草、大枣，简称“脾四味”。很常见
的药，对脾胃最管用的自古以来就是这四味。生姜和大枣已广泛种植，是最常见的食材了。
中国人早已经将这四味药引入了日常生活之中。很多人追求稀有昂贵的保健品，其实最管用
的东西都会被普及，哪里可能昂贵呢？昂贵的多数没什么用。这就是所谓的“老百姓日用而
不知。”

[桂枝汤方：桂枝 三两（去皮） 芍药 三两 甘草 二两（炙） 生姜 三两（切） 大枣 十二
枚（擘）]

现在说药性，先说甘草和大枣。这两样东西都是甘而微温，煮出来汁液黏黏的甜甜的，甜入
脾，能够直接补充胃里的津液，同时性质不寒凉，不会妨碍脾胃的运化。所以这两样补充脾
胃津液最适合。

出现一个问题，我之前说过反对药物归经，甜入脾又如何解释？现在来说说五味和五脏的关
系。

“辛”，也就是辛辣辛散之类的味道，是上行的，它走上走表，肺在上，自然能入肺。肺是主
收敛主吸纳的，辛味是行散的，和肺的主要功能相反。辛味一来自然先刺激到肺，肺就会亢
奋起来抵抗，这是人体的自保模式。所以适量的辛气能刺激助长肺的功能，辛多了则伤肺。
这就是“辛入肺”的道理。这种解释是层面之学，是实证而严谨的理解药物对人体的作用原理，
而不是主观臆断的说归某经归某脏腑。

“酸”是收敛的，而肝的作用是升发疏泄，酸的作用和肝的作用相反，自然一进入人体就先抑
制肝的功能，肝脏受到抑制自然也会亢盛起来，所以“酸入肝”，适量酸味助长肝气，酸味多
了也伤肝气。

“苦”是降而寒的，心脏在上，功能是永远勃动向上，永远有热能的。适量的苦助长心的功能，
苦多了则伤心。

“咸”是下行的，所以地球上海水是咸的，因为海的位置最低。肾脏是人体的元气之所在，它
像水泵一样，位置虽然在下面，却是引能量上行的，这种元气能量在西医称之为肾上腺素。
能量的代谢物是废水，从膀胱排出，就像汽车有个水箱。既然肾的功能是上行，适量的咸能
助长肾的功能，咸多了则伤肾。

最后说到“甜”。甜味不偏不倚不走不散，温和居中。脾胃在中间，所以入脾。脾胃津液的主
要成分是食物转化的糖分，而甜本身就是糖分，等于能直接补充津液。脾是主运化的，而甜
有和缓之性，与脾性相反，所以适量的甜是助长脾的，甜多了则伤脾。这就是为什么炙甘草
和大枣两味药入脾的原因。

再说说脾四味里其它几味药。

姜，我们知道它温中而发散，能让脾胃热起来运行起来。所以只要是脾胃寒的，一味姜就管
用。后世的中医一见津血亏，就喜欢用麦冬地黄来滋阴养血，问为什么不用姜，说则答曰姜
性热，会耗散津液。现在的医生都这么说，这简直是千古谬论，贻误世人。津血靠的是脾胃
运化而生成，难道是靠生地麦冬里那些黏液直接补进去的吗？后世的中医理解问题就这么简
单。脾胃虚了寒了，本身就是阴了，麦冬生地之类的滋阴药，也是寒凉属阴，阴上加阴，脾
胃就更不运化了。《伤寒》的用药法则是从阳引阴的。阴上加阴必是死路。除非阴虚阳亢，
同时脾胃不缺运化之力，才可用麦冬地黄滋阴制阳。我看过很多慢性病的病人，吃了很多年
中药的，病没治好不说，看脉证尽是一派阴寒之象，再看吃过的方子，无非就是滋阴养血之
类的药。

人参这个药要多说几句。后世说它补气，“气”是什么？从医理上来说，气是“阳”，是能量，
是无形的气化物质；与气相对应的是“血”，血是“阴”，是有形的物质。既然“气”是能量，气
化是需要热能的，所以姜桂附是气化药；“味”是有形物质，像地黄这样没有香气，却很粘稠
的东西就是典型味厚的，所以补阴。药物主要是以“气”和“味”两个方面组成的。人参呢，人
参在土里长得很慢，得土气最厚，所以补中入中焦；它的“气”是一种很厚郁的参香，所有香
的东西都有刺激亢奋的作用。这种气有没有热能呢？我们尝一下就知道了，它不辣不麻不热，
没有热能。所以人参亢奋的是主要是“阴”的层面，“阳”的层面居少。《伤寒》里人参是用来
救阴的。药物里亢奋阳的药居多，能亢奋阴的很少，这就是人参作为药物的不可替代性。经
方里人参寒热不禁，既能合热药治阴证，也能入白虎汤之类的寒凉之剂治大热伤津。后世说
人参补气，所谓“阳化气、阴成形”，人参既然没有热能，哪里能阳化气呢？

还有一味所谓的补气药黄芪也是如此，黄芪的作用类似于人参，也是没有一点热能的，只是
黄芪的香味更轻更升能往表走，能滋养表而已。后世的中医却惯用这两味药治虚寒之证，说
是补气。有一个癌症术后的病人，四肢冰冷懒言少气，脉沉弱得摸不到，已是四逆汤的症候，
非姜附不能救的。去找北京一个大医院的专家，没用姜附，主药是五十克黄芪。后世对药物
的认识阴阳混淆，气味不明，陈陈相因，人云亦云，以至于中医落到了今天这个境地。

总结一下脾四味的作用：炙甘草和大枣，甜而温，能快速补充津液。炙甘草得土气纯厚，补
中最速；大枣微香，又能帮助脾的运化。甘草色白，偏向于补津；大枣色红，偏向于补血。
姜是亢奋阳的，运化脾胃而去寒。参是平性，是亢奋阴的，生成津液而不上火。这四味药各
司其职，在临证上可以选而用之。

桂枝的作用呢？桂枝性温，其气是一股热郁的浓香；桂枝煎的水有一股微微的甜味。桂枝的
作用主要是气，而味很少。桂枝的气相比薄荷、白芷，没那么轻扬；相比川芎、当归又没那
么浓厚。所以薄荷、白芷是走表走头的，桂枝只能把能量送到肌肉里，我们称之为“解肌”。
至于那一点微微的甜味呢，也是有作用的，前面说过，甜是入脾的，脾又主肌肉，所以桂枝
是一味气化中焦脾胃而解肌的药。

桂枝后面标注的“去皮”历来有各种不同的理解。我的理解是，此药效果好的部分是桂树的嫰
枝尖，皮和木不分开的部分。如果皮和木分开了，就不是严格意义上的桂枝了，所以剥落下
来的皮要去掉，效果不好。皮里面的木头是没有疗效的。现在药房的桂枝一般都是皮和木分
开了的，一截截的木头渣子都在里头。

白芍，这是一味极其常用的药。后世有说白芍敛肝的，有说养阴的，有说降胆火的。到底是
什么呢？药物的作用不能光凭书上的几个词语去理解，因为语言的传递太有限了，也太笼统
了。比如阿胶地黄白芍书上都说是养阴养血，可这三味药一尝就知道，相差很远。所以我主
张真要学药，药材一定要单味煎好品尝过，细细体味，才能确切把握其性味。白芍没什么气，
味是一种类似于破水缸里存的陈年雨水一般寡淡的沤味，这是典型的阴而降的味道；其次有
些苦，苦是主降主泄的；酸味不多，绝对没有五味子、山萸肉和乌梅那么酸，所以它不是以
酸敛为主的；黏液也不多，滋阴强壮的作用也不大。这就是尝过之后的真实感受。总结一下，
白芍以降和泄为主，收敛滋阴为辅。临床常用它治腹痛，降则能引气血下行，苦则能泄而去
实，所以能治腹痛。

现在我们将桂枝汤的药和中风的证做个一一的对应。中风是汗出后津液虚了，人体却要再次
作战，于是白芍、姜、草、枣合在一起主守，守津液；桂枝一味主攻。当然，生姜也有一定
的解表作用，但整个方子是以守为主的，服了药之后还要喝粥，用五谷直接补充津液营养。
桂枝将阳气送到体表，于是该发汗的会发汗，该止汗的会止汗。白芍的作用相反，负责将阴
气收回，阴成形的力量强了，阴血充足了，才是病愈的根本原因。后世说桂枝汤是发汗的，
我说过药物不能代人体行指令，药物只是让人体回到正常状态。会使用经方的都知道，桂枝
汤止汗的效果也是如神的。我曾经治过一个病人，只要稍一动就汗出如洗，脉浮大，口不渴。
之前吃过很多敛阴止汗的药，黄芪白术所谓固表的也吃过不少，汗出反而加重。用桂枝汤一
剂而愈。

简而言之，桂枝就是“阳化气”，白芍就是“阴成形”，调和阴阳，一阴一阳之谓道；姜、草、
枣守中。仲景的核心法门就是这两个，所以桂枝汤被称为伤寒第一方。理解了桂枝汤，讲后
面的就好办了。

最后还要讲一下药物剂量的问题。历来一般认为书中的一两是三克，三两就是九克。汉代的
衡器已经出土几十年了，汉代的一两是约十五克（15.625克），桂枝三两也就是约四十五克。
现在学院教材里的衡器换算，说汉代一两等于十五点几几克，很精确。到了讲桂枝汤的时候，
依然是三两等于九克。教材连度量衡的问题都可以公然自相矛盾，这就是我们的学院，这就
是我们的医学，有什么办法？我的经验，要想治疗效果好，一定要尊重汉代剂量的。当然，
病有轻重，人的体重也有差异，是要变通的。一般外感病轻的可以取书中一半的剂量，病重
甚至可以超过书中的剂量。慢性病依病情轻重可以取书中三分之一到三分之二的剂量，病重
的也可以超过书中剂量。为什么是三分之一到三分之二的剂量呢，因为古人用药一般都是一
剂，药简力专，下药必效，不可能像现在一吃好多剂。咱们现在约定俗成的方法，慢性病至
少也要开个三剂五剂的，开一剂药房都不给抓，所以剂量可以轻一点。

煎药的方法也尽量要依照书中的提示，现在一剂药煎两回是不妥当的，因为药物不同，药性
释放的时间也不一样，煎两回喝常常味道有差异。最好一次煎好分两次喝。一般煎个三十到
四十分钟即可。宣散解表药不要超过三十分钟，滋补药可以煎一小时以上。

13、 太阳病，头痛、发热、汗出、恶风，桂枝汤主之。

这一条有重复前面之嫌。汉代的书是竹简，一旦绳子断了就容易错顺序，加上流传靠传刻传
抄难免有误，也难保后人不根据自己的理解自己往上加东西。这就给我们的研究造成困难。

14、 太阳病，项背强几几，反汗出恶风者，桂枝加葛根汤主之。

[葛根四两 麻黄三两（去节） 芍药二两 甘草二两（炙）

生姜三两 大枣十二枚（擘） 桂枝二两（去皮）]

上七味，以水一斗，先煮麻黄、葛根，减二升，去上沫，内诸药，煮取三升，去滓。温服一
升，覆取微似汗，不须啜粥，余如桂枝法将息禁忌。

这个条文好像是冲后面来的，后面有一条“太阳病，项背强几几，无汗恶风者，葛根汤主
之。”这个顺序应该弄错了。

在感冒的时候，如果身重酸痛，是肌肉的反应；如果是“强几几”这样的僵直不灵活的反应，
是筋的反应。筋的常见的反应还有身子僵硬不能转侧，痛经，容易抽筋等。这就是“强几几”
为什么发生在项背，脖子这一片里面全是筋，这是人体运动的枢纽。颈椎病腰椎病，哪怕骨
头有错位增生，其实不是骨头的问题，是因为维系骨头的筋出了问题，才引起骨头的问题。
很多病人增生、突出、长骨刺，以为是骨头的问题，其实是维系骨头的筋出了问题，骨头才
要增生寻求支撑。那筋的问题是津液虚失去滋养的问题。所以一定要学会思考人体才能真正
的治病，千万不要轻易相信某个药治某个病，或者某个方子对应某个证。在具体的病和证的
层面上没有一成不变的，还是要把人体弄清楚才能减少误治。

回到条文。当人体大量气血往体表肌肉走的时候，筋就失去了滋养，于是就发生这种项背强
几几的现象。这种情况下就要用到一味药，葛根。葛根煎好的汁液清、稀、滑，类似于人的
津液，会有一点直接滋养津液的作用，但这绝对不是它的主要作用，如果只是为了直接滋养
津液，可以选择更黏滑的天花粉。葛根主要是有一种上升之力，喝多了胸口会觉得顶。香气
淡而升，不芳烈，所以不能开孔窍，只是引津液而上行。为什么是引津液，不是引别的呢？
因为它本身就像津液，这是《易经》的同声相应，同气相求原则。就像衣服上有油要用汽油
去洗一样，清水是洗不掉的。

和葛根相对应的是白芍，白芍煎的水也是清、稀、滑，有苦降之性，所以引津液下行。葛根
治颈椎痛我临床常用，很有效，不过要重用，至少四十五克以上，因为葛根本身药力很轻，
食品嘛，超市有卖葛根粉当早餐的。白芍治腹痛都知道，立竿见影。腹痛是什么？前面说过，
不是腹部肌肉痛，而是腹部里面的筋痉挛，也是筋缺少滋养了，所以用白芍引津液下行。

这个方子是有传抄错误的，“汗出恶风”是桂枝汤证，应该就是桂枝汤加葛根，不应该有麻黄。
麻黄的原理后面的条文会专门解释。好，今天就讲到这里，下回再接着讲。谢谢大家。

学伤寒既为医人，更为医医。本群更欢迎对伤寒有疑问的人，只要是抱着追求真理之心，以
后都是能济世救人良材。

下面继续《伤寒论》条文的讲解。

20、 太阳病，发汗，遂漏不止，其人恶风，小便难，四肢微急，难以屈伸者，桂枝加附子
汤主之。

桂枝加附子汤方

桂枝 三两（去皮） 芍药 三两 甘草 三两（炙） 生姜 （三两） 大枣 十二枚（擘） 附子
一枚（炮、去皮、破八片）

大家会发现，伤寒论的很多条文都是一个完整的医案。 《伤寒》的好处是都以医案的形式
讲治病方法，好操作好模拟；不好的是没有详尽的医理解释。当然，这只是后人的看法，也
许在当时这些医理和阴阳之道都是常识，无需特别解释，一看就懂的，就像现在一说什么分
子原子大家都懂一样。

要不怎么说文化衰落，大道已废呢，在孔子的时代，孔子就说大道已废，所以他要编订《诗》
《书》《礼》《易》《春秋》以传承文化，并且呼吁恢复周礼。中国文化成熟得早，别说周
代，商代的青铜器，原始社会的玉器现在用现代化工具都做不出来。现在已经出土了八千年
前的骨笛，乐器的出现是必须有数学、音律学和工艺作为支持的。“盛极必衰”这是天道，连
《伤寒论》这样的医学普及读物，近一千多年来竟然都说难以参透，可见中国文化早已衰落
了。不过大家也不要悲观，还有一句话叫“否极泰来”，历经五四、文革、发展经济的毁坏，
中国文化算是“否”到极点了，也许快到“泰来”的时候了，怕就怕“泰来”的时候到了，文化却
消亡了，所以要靠大家来留存最后一炷香火。

说回条文，太阳病如果用药不当，误发了汗，造成“漏不止”，就是大量出汗止不住，人就会
陷入阴证。因为一个汗一个下是最容易虚人的。慈禧太后因为看京剧受了寒，连续腹泻几天
止不住，太医就束手了，然后就看着她死了。腹泻这么快死人，必是阴证，阴证的腹泻非四
逆汤不可救。学通了《伤寒》的人这不是什么难断的病。慈禧最后的用的那个方子我见过，
石斛老米之类补中养阴之品，典型后世医家的思路。当了帝王又能如何？好医生未必在庙堂
之上，民间未必没有高手，古来如此。慈禧若到这里来找医生，我知道，以座中很多人《伤
寒》造诣，都有本事救她。

下面讲的是陷入阴证的过程，“其人恶风”，前面说过，是津液已经虚了。“小便难”，因为津
液虚而无尿可下了。这里说的是阴证津液虚的无尿可下，前面讲过热证伤津液的无尿可下。
所以治病不能单凭一个证来判断，要综合起来分析才行，《伤寒》的法则是要几个证同时来
参才能得出结论的。现在的医生，一听尿少就利尿，一听口渴就滋阴，这不是真正的医道。

“四肢微急，难以屈伸”，津液虚少，筋里面血管少，首先失去滋养，于是四肢拘急不灵活了。

综合分析，太阳病，津虚，是桂枝汤证。炮附子可以止虚汗（原理参看前言）。虚汗一止，
津液自回，才可以阻止陷入阴症的过程。所以这个方子治桂枝汤转向阴证的变化方。有人说，
敛汗不是要用白芍吗？说药有某种功效是后世的说法，药没有敛汗不敛汗的，人体需要强阴，
用白芍这样的阴性药材可以敛汗；人体需要扶阳，用炮附才可以敛汗。

21、 太阳病，下之后，脉促胸满者，桂枝去芍药汤主之。

桂枝去芍药汤方

桂枝 三两（去皮） 甘草 二两（炙） 生姜 三两（切） 大枣 十二枚（擘）

前面说过，太阳病误下会出现气上冲的情况。这也是误下，出现“脉促胸满”，情况不一样，
其实原理是一样的：因下药，也就是泻药的作用气血暂时陷里，表证还未解，药效过去，气
血自然还会再回到体表来驱邪，因气血已伤，能量不够了，不能顺利达表，于是便产生了
“脉促胸满”这样的证。“脉促”的意思是脉往上往寸部顶，寸盛尺弱。这是津液不能气化出表
而产生的壅塞反应，自体感觉便是“胸满”。这是桂枝汤的适应证。为什么去芍药呢？既然是
气血能量不够，自然要助一把力以驱邪外出，芍药是引津液下行的，所以要去掉芍药。去掉
芍药，等于桂枝的向外之力增强了，所以桂枝不用加量，依然是三两。

有人问我，什么是“道家”中医。这一条就是最能体现道家中医特色的。后世的中医，一碰到
“脉促”寸盛，就说是相火胆火，又说白芍降胆火，不仅不会去白芍，更加苦寒药，桂枝这样
的助阳药自然是不敢用的了；又说“胸满”是气机上逆，应该下气，或说寸盛尺弱是肾不纳气，
更加五味山萸之类的收敛药。于是用药一派收敛寒降，这都是对抗思路。

根源是没有从人体的角度来考虑问题，从脉象而言，寸盛尺弱说明气血是够的，只是分配不
均匀，都跑上面去了。那为什么会跑上去？人体的自然模式是哪里有邪气或有瘀滞，气血往
哪里跑。后世中医碰到寸盛尺弱一般会辨为肾不纳气，那自然要补肾。气血既然没有不够，
只是分配问题，补那些滋腻之品有何用，非但无用，很有可能还助长了邪气。如果邪气不去，
气血又怎么可能自己回来？用补肾纳气的方法效果怎样，我早年学后世中医的时候屡试屡败，
吃上个一两个月不见什么效果的多得很。《伤寒》的处理方法是道家的顺应思路，顺应人体，
顺势助人体一把力，驱邪出表后脉象自宁。效果怎样，试过便知。

如果脉象的寸盛尺弱是寸大而虚，尺弱而细，驱邪的同时重用建中药，再配合些补肾药也是
可以的。这还是《伤寒》的津血原则，津液虚的自然是要先建中补津血。若只用脏腑辨证，
也不驱邪，也不建中，一味补肾是很难奏效的。不但难以奏效，还很容易上火，后世有句话
叫“虚不受补”就是说这种情况。虚既然不受补，那实就可以补吗？实当然不能补，补了更上
火；那不虚不实的话，又补它做甚？这就说明了补之一法的局限。人身自有大药，要着眼于
恢复人体的运化循环让人体自己去补，不要越俎代庖。人体自己补才是真正的补。若身体真
能靠药物补起来，我相信没有人去锻炼了，费那力气干嘛？也不会有人生病，当归地黄大家
都吃得起。一定要补也只能辅助，人体若有邪气，若中焦不运，若表里不通，补也只是造成
堵塞。

22、若微寒者，桂枝去芍药加附子汤主之。

桂枝去芍药加附子汤方

桂枝 三两（去皮） 甘草 二两（炙） 生姜 三两（切） 大枣 十二枚（擘） 附子 一枚
（炮、去皮、破八片）

这一条是接上一条说的，在“脉促胸满”的基础上又多了个“微寒”的证。“微寒”的意思应该是
脉微恶寒，而不是微微恶寒。说明已经陷入阴症，于是加了炮附子。炮附子不单是虚汗可加，
一切阴症都可以加。

这几条都是用一个桂枝汤在加减变化，桂枝汤的变化方后面还有很多，无非是因邪气的性质
和气血的阴阳盛衰而加减变化。顺气血而上则去芍药用葛根，顺气血而下则重用芍药。偏于
阳则加石膏；陷于阴则加炮附。表不解加麻黄而成葛根汤；里兼热则少佐大黄而先表后里。
表虚加黄芪而成五物汤，主治肢体萎废和麻痹；里虚则加芍药饴糖而成小建中，主治虚寒之
腹痛；气机闭阻则加厚朴杏仁；水湿中盛则加茯苓白术。这些都是经常会使用到的药。

《伤寒》里的药物很有限，也就三四十味常用药打转转；方子更有限，无非几个主方变来变
去；药物既然是作用于阴阳表里，而不作用于病，就可以不必那么多药，只要力量专一，分
工明确就可以，所谓“药简力专”就是这个意思。《伤寒》是本乎“道”的，因而能大道至简，
以一驭万。后世搞出很多药性含糊驳杂的药，也搞出了很多的方，一个方子几十味药，方子
越组越大，疗效越来越不确定。

今天就先讲到这里，下次再接着讲，谢谢大家。下面是讨论时间，我会继续在这里关注大家
的发言。

== 2014-05-10（23-26）

=== 答疑

我要回答的第一个问题是有朋友问我：“为什么现在有的中医说中医只能调理，不能治病？”

我看在座的有很多朋友在《伤寒》上也是很有造诣的，我也经常关注大家的发言。我要说的
是：“大家一定有这样的经验，使用《伤寒论》的方法和方剂在治病的时候，像感冒这样的
病，一般一剂药甚至是半剂药，该止泻的止泻，该退烧的退烧。大家一定有过这样的疗效，
或者说是效果。我经常说如果你学了《伤寒》，感冒做不到一剂药治愈，那一定是还没有学
到家。事实上退烧和止泻只需要半剂药，大家一定有过这样的经验。

有些久治不愈的病，用《伤寒论》的方法和方剂来治，经常也能做到“一剂知，二剂效，三
剂已” 。什么意思呢？就是有没有效果，第一剂药就知道了，第二剂药就应当有明显的效果，
第三剂药有可能就会治好了。就算是更麻烦的、更严重的慢性病、脏腑的病，那五剂、七剂
也应该是有明确的效果。我现在说的是《伤寒论》的临床效果。正因为《伤寒论》有这样的
临床效果，所以历代的大家、历代的医学家才这么的推崇《伤寒论》，推崇张仲景。也就是
为什么，大家坐在这里来寻求、来学习传统的医学，来学习《伤寒论》，就是因为这个原因。

那在后世的医学呢，一般来讲，疗效就要慢很多。尤其是在治病的时候，有时给病人开十幅
药，调理一两个月，也没有太明显的疗效。这是很正常的，所以说很多后世的医家，他们自
己就会说中药不能治病，中药只能调理。事实上这就是后世医学的一些问题，那我们来这里
学习，来探讨，也是在探讨后世医学的一些问题，包括什么才是真正的医学的传统，什么才
是真正的中医的精神。

有朋友问我能不能介绍下脉诊方面的问题，就是摸脉。我觉得有必要介绍一下的是——仲景脉
学，就是《伤寒论》的脉学。《伤寒论》的脉学，它是比较简单的，主要是断阴阳，然后用
脉的浮、沉、促，来断病的位置。它还是以阴阳和病位为基准的，它是一套比较简单的脉学。
而脉学在后世却发展的很复杂，复杂有复杂的好处，当然也有它的坏处，就是往往让人混淆
和忽略了最本源、最核心和最精准的东西。

后世的脉学也跟后世的医学一样，发展得太花哨了。其实真正的大道是“大道至简”的！至
“简”，一来是简单,二来是抓住了本质。所以说我们现在很多后世的人来学《伤寒论》，觉
得《伤寒论》很复杂，其实《伤寒论》等我们讲完了、学通了之后，你会发现《伤寒论》的
原则是最简单、最容易操作的，也是最有法度，有具体的标准可依、可循的。后世说的很多
东西，让我们看起来觉得好深奥。其实《伤寒论》里面都是说汗出怎么样，不汗出怎么样，
都是很简单可操作的东西。正因为后世的人把医学搞复杂了，以这种复杂的心态去看一个简
单的东西——看《伤寒论》，反而觉得看不懂，就像一个复杂的人看不懂一个简单的人一样。
所以说后世的人会觉得“我看不懂《伤寒论》是不是因为它很复杂呢？”就会用一种更复杂的
心态去看《伤寒论》，结果就会更加看不懂。历来都说《伤寒论》难学，但是其实《伤寒论》
是“大道至简”，是一套很简单的东西，我们慢慢学，以后就知道了。

至于脉诊这个问题，我觉得仲景脉学——《伤寒论》的脉学，有它比较特别的地方和一套比较
特殊的方法，所以说我希望以后能以专题的形式来跟大家分享。

我在网上，包括我们的群，还有外面看到很多朋友在争论，不认同六经辨证体系，不认同表
里辨证体系是主流，他们认为各种辨证体系都有它的优长，都有它的特点，应该博采众长，
有这样的说法。就这个，我想再解释一下。

首先我要说的是，类似于博采众长、百花齐放这样的说法，我觉得更加适用于政治，作为政
治的演讲或者作为艺术的评价，我们常说艺术要百花齐放嘛。但是作为一门医学，是永远在
追求真理的，就是我们永远会追求更好、更对、更有效的那个东西。所谓的文无第一，武无
第二，就是这个道理。那我再解释一下，为什么六经表里体系是最适合于汤液学的一个体系？
我现在提出一个问题大家思考一下。

《黄帝内经》成书于战国之前。张仲景的《伤寒杂病论》是在几百年后在东汉写出来的。也
就是说在张仲景之前，那些经络、脏腑之类的辨证理论早就已经有了。那为什么张仲景要创
造性的提出以六经、表里来论病呢？

这个问题的答案是，因为张仲景他研究出来真正适合汤液学的辨证体系是六经体系，他才写
了《伤寒杂病论》这部书来拨乱反正，为什么六经体系是最适合于汤液学的呢？我们在前面
的课里有解释，刚来的同学可以去把前面的课拿出来看一下。

张仲景写了《伤寒杂病论》来为汤夜学找到了最合适的、也是最有效的辨证体系，本来汤液
学就此可以步入坦途的，只是张仲景没有料到，后世的一些医学家，又用那些他曾经摈弃的、
纷乱的理论体系来发展汤液学。更为讽刺的是，很多医家引用这些理论体系，还是为了更好
的解释和读懂《伤寒论》。

后世的中医典籍浩如烟海，后世的中医典籍解释和运用《伤寒论》的也浩如烟海，他们都在
推崇《伤寒论》的成就，认为这是最高圭臬，汤液学最高的准则。后世那这么多的书籍，用
经络也好、脏腑也好、五运六气也好来解释《伤寒》的这些医家、名家，哪一个能真正的解
释得通《伤寒论》呢？我相信没有。所以说大家才会觉得《伤寒论》很难学，也才会寻求
《伤寒论》到底是什么。后世还发展了很多各有特色，百花齐放的辨证体系，事实上哪一个
能达到六经辨证的治疗效果呢？其实也没有。相信来这个群的人都明白这一点。

很多，甚至于开创了很多辨证体系的开山宗师们，很多历代的大家，他们留下的医案都说有
些病只要能和《伤寒论》的原条文对应上，就能效如桴鼓。如果对应不上，疗效就不能确保
了，所以他们都很推崇《伤寒论》，只是不太明白《伤寒论》里头的到底是什么，看不懂而
已。这些都说明一个道理，就是后世的医学、汤液学走的是回头路，是岔路。结果大家也看
到了，中医汤液学相比仲景时代，衰落得太厉害了，这2000年以来都在衰落！！！宋元时候
的医家就开始批评他们的医家不如前代。唐代的孙思邈在写了《千金方》之后，也说张仲景
原来比他要早得多、全面的多，他也发出这样的感叹！

这两千年来，我们非旦没有让中医有所寸进，反而让中医治病从“覆杯而愈，一剂而解”沦落
到中医不治病、中医治病慢、中医只能调理这样的境地。这就是因为“走回头路”造成的结果。
也正是因为如此，我们今天才聚在一起研究经方，研究《伤寒》，重新回归到真正的传统中
医。如果我们再不能回归到真正的传统，中医的前景也许不是再走两千年弯路那么简单的了。

今天的答疑就先讲到这里，谢谢大家的倾听。十分钟后我们开始进行《伤寒论》条文的讲解。

经方-刘希彦(885477952) 20:07:07

大家晚上好.

先来分享两则网友的答疑。

老师，漏汗和下后胸满，这服药后还需要啜热稀粥吗？要温覆取汗吗？

《伤寒》里方后有注，将息如前法，应该就是可以的。

一默 21:59:34

为什么加葛根汤却明言不须啜粥呢，老师

希彦 22:01:05

桂枝汤不发汗，啜粥温覆可以助汗，亦可补津液。葛根汤有麻桂，本身就是发汗剂，所以无
需啜粥助力。

一默 22:02:01

我问的是桂枝加葛根汤没说清楚，不好意思

希彦 22:03:33

项背强几几，里面的筋缺少津液，既然这是主证，自然不啜粥取汗，以免津液耗散。

一默 22:04:32

哦

想明白了，谢谢老师教导

我最近在注意论中方后服药法，很多地方想不明白

希望老师后面讲的时候，能兼顾地讲一下这方面的知识

希彦 22:07:01

你很细心。务必弄明白是成为好医生的前提。

一默 22:07:53

经方-刘希彦(885477952) 20:10:14

《伤寒论》的每个方子后都写有药物的煎煮和服用方法，和现在的方法是有出入的。限于时
间我没有在课上讲解。有时间大家可以去研究一下。

天一 22:01:33

老师我们可以交流一下吗?

希彦 22:01:51

请说。

天一 22:03:36

伤寒论的真实高度有多高

天一 22:04:37

群里面的人是在捧举伤寒论吗?

希彦 22:05:02

实践便知，历代各派医家无不推崇，无论对外感还是内伤病，疗效远远超过一般医学。

这个无须争论，各派都可学，我也学过。自然就能去伪存真，随着实践和疗效的印证，有些
东西自己就会剔除掉。

天一 22:07:53

我感觉今天我们研究的深度比仲景当时想的都多。

希彦 22:09:46

你说的有道理，后世医学的确搞复杂了。有些理念汉代是常识，而且体系不杂乱，所以医理
无须讲，现在大家没有真正的传统中医思维，而且体系混乱，才需要这样讲清楚。

天一 22:12:20

后世医理也有可用之处，后世医理的加如使我们现在所处的阶段是扩大仲景成果的阶段。

天一 22:15:19

如郝万山老师讲，五苓散可以治疗脑积液，这就是对仲景方的发挥，这就是对仲景成果的扩
大。

希彦 22:17:28

仲景讲治证，只要是五苓散的方证，就可以治一切这个证对应的病。伤寒本来就是对证不对
病的。这是伤寒最核心的理念，应该不叫发挥和扩大。

希彦 22:18:57

仲景之所以辨证施治，而不是辨病施治，就是这个原因，就是为了以有限之法治无限之病。

希彦 22:19:47

辨证施治也是仲景开的先河。

天一 22:20:18

噢噢!明白了。谢谢老师。

要回答什么是药的“体”，要先说，到底什么是药的“用”。

比方说，我们说一个药，说这个药治什么什么病，这个药治咳嗽，这个药治胃痛，这个药治
肿瘤……这就是在说药的用。药的用还有更高一个层次的说法，比方说我们说这个药清热，说
这个药祛湿。还有一种说法就是这个药入肝、入肺，或者说归某条经，肝经、肺经……

关于药的“用”，我想提出几个问题。第一个问题，为什么药物的归经学总是各执一词。举一
个例子来说：山药。一般的医书上会说山药入脾经，也有说入肾经，也有说补肺，也有说补
虚，还有的说补气，那这个药到底是入哪个经、补什么呢？再举个例子比方说黄芩这个药，
苦寒药，有的说这个药清胃火，有的说清肝火，还有的说清胆火，清肺火的、清大肠热的都
有，那这个药到底清哪里的热呢？几乎所有的药物在归经学上都是各执一词，很混乱的！这
是我提出的第一个问题，为什么会这样？

我提出的第二个问题是药物在临症上问题。打个比方，我还是举例子来说吧。比如说大黄这
个药，我们说它是泻药，是泻药的话，它吃了就会腹泻，但是如果是热性的痢疾，吃了它还
止泻，这个大家都知道。再比方说白术这个药，我们后世有说它健脾止泻，之前我有讲过北
京有个大夫专门用大剂量的白术来通便。最典型的是桂枝，我们知道这个后世说它是发汗药，
那其实学过《伤寒论》的人都知道，桂枝更多的时候是用来止汗的。上回有个朋友，带了个
小孩来我家里玩，正好我煎了一点桂枝，在尝新买的药材，这个小孩喝了大概10克的计量，
（小孩觉得好喝，那个小孩才2岁半，）第二天他的妈妈跟我说孩子夜里睡觉的时候发汗明
显的少了。那桂枝到底是止汗、还是发汗呢？

我再提出第三个问题。我们都知道《伤寒论》里面的用药是非常之少的，《伤寒论》里面的
方子治各种病，无论是外感病、脏腑病、慢性病、急性病效果都是非常之好的。《伤寒论》
里面永远就是那么几味重复的药在那里转过来，转过去，那为什么能够治一切病呢？这就说
明药物并不针对某个病，药物也不针对某个症。我前面说过药物归经这个说法事实上也是人
为的、臆断的东西比较多。我说过药物不能说它入肝经、入肾经，因为它不是智能的，它不
能只是走肝经、只是走肾经，你甚至不能说它只是走脾胃、只是走肾……它走的是层面，发散
药走上，寒凉药走下，或者说有的药走表，有的药走里，要根据它们的性质。所以说药物走
的是大层面！

我要说的药的“体”就是这个。药不能够臆断它走某条经、不能够说它针对某个病，这都是后
世的医学，都是我们所反对的“头疼医头、脚疼医脚”主观臆断的医学思路。所以说我们要学
“药”，就要知道它的“体”，这个“体”是什么呢？这个“体”就是药物在身体里面它到底走什么
层面，它在表里、阴阳、正邪、顺逆，这样的一些个能量场里起到的作用是什么，而不是去
牵强附会的把它和经络脏腑联系起来。

我这次讲解《伤寒论》，在讲解条文和方子的时候，我也会讲解药，我就是着重于讲药的
体——药在作用于人体机体里面的真实的作用！当然，如何来鉴别药的体？有没有规律？有没
有一套方法能够让我们更加系统地、更加准确地、更加详细地来掌握药的作用呢？我想以后
我可以做专题来讲，就可以更详细的做出对药的鉴别和理解。

我们说药物的那些作用，包括它对于五行、对于五运六气、它和五运六气的对应……它到底有
没有这些作用呢？我以前说过其实很多东西它都是有的，包括它对于经络和脏腑也是偏向性，
但不是绝对的。我们用那种绝对的东西去讲的话，比方说我们就说我们用这药去清肝火，但
是这个药它走很多层面，不单只肝，如果我们用这种思维去做的话，不能够得心应手，不能
够“指东打东、指西打西”呢？其实我们从更加宏观的角度来讲，人存在于宇宙当中，影响人
体的因素太多了，在外有命理生克、五运六气，在内有脏腑经络、气机升降、枢机开阖等，
而且七情六欲它对生理也有很大的影响。

如果这些影响我们都去推求、都去分析，那还怎么治病呢？所以“药”者“钥”也！用药治病，
其实就是一把钥匙，我们只要找到这把钥匙，从核心的地方，轻轻一桶就开了。所以经络的
治疗完全印证了从一个点开锁就是能治好人体的。我们要真正地了解这把钥匙，真正的搞清
楚这把钥匙到底是一个怎样的结构，我们才能打开疾病这把锁。关于药物的解释我原来已经
讲过了，但是很多道理总是越讲越清楚的。今天的答疑先到这里。谢谢！

=== 条文讲解

刚才有朋友在分享一些心得，我看了也很受益。其实我们现在看到的《神农本草经》也好，
《黄帝内经》也好，未必就是最本源的版本，都是经过历代传抄，难保会有增减。增减之人
水平也很难保证。书就是这样，书中有真亦有假，可惜世人信假不信真。所以我们以“经方
求真”为题，但求真耳。

下面接着讲解《伤寒论》的条文。

23、 脉微而恶寒者，此阴阳俱虚，不可更发汗、更下、更吐也。

这里又讲到一个治病的大法则。

我们前面说过，病有三个解决方法：汗、下、和解。其实还有一个方法就是吐，人为催吐的
药现在用得少了。汗、下、吐这三个方法都是伤津液的，只可用于三阳证，三阴证不可用。
因为阴证不可更伤津液。这也再次说明了《伤寒》的体系是以津血的盛衰为原则来辨证组方
的。

23、 面色反有热色者，未欲解也，以其不能得小汗出，身必痒，宜桂枝麻黄各半汤。

桂枝麻黄各半汤

桂枝 一两十六铢（去皮） 芍药 生姜（切） 甘草（炙） 麻黄（去节）各一两 大枣 四枚
（擘） 杏仁 二十四枚（汤浸、去皮尖及两仁者。）

上七味 ，以水五升，先煮麻黄一二沸，去上沫，内诸药，煮取一升八合，去滓，温服六合。
本云，桂枝汤三合，麻黄汤三合，并为六合，顿服。将息如上法。

这一条可以看出《伤寒》组方之严谨和精准。面有热色，太阳证仍在。汗出是桂枝汤，不汗
是麻黄汤。身痒说明汗已到了皮肤下，只差一点就要出来了。这时候算是汗还是不汗呢？算
汗与不汗之间，于是用桂枝麻黄各半汤。可见经方用药法度之森严，是不可以主观和随意的。

有人说,《伤寒》里的方子擅长治外感病，如果是感冒效果很好，如果不是感冒，效果就不
明显了。这话是不对的，要看你在治慢性病的时候是不是也有这样严谨的法度，一般所谓的
经方家，能大概选个差不多的方子就不错。至于后世的医生，同一个病人，这个医生是这样
一套方子，那个医生是那样一套方子；用药也全凭主观，这个医生喜欢用这些药，那个医生
喜欢用那些药；剂量这个医生六克十克，那个医生二十克三十克。这只能说明一个问题，后
世的中医根本就没有一套确切的体系，所以大家才各想各的办法，各凭各的理解。现在的辨
证法，五行生克的脏腑理论是主流，这套理论对不对？是对的。脏腑之间当然有生克关系，
就像树木会影响河流，河流会影响田地，但旱季一来全都要缺水。不能说五行生克不对，相
对于人体的表里大循环，它的作用太小了。以它来为原则来组方治病无异于螳臂当车，收效
怎么可能明显。所以后世的中医自己都说中医只能调理不能治病，给人开药一开就是十几二
十剂，甚至吃几个月也没个明显的效果，就是这么来的。

以这个方子为例，我们可以来谈一下如何运用经方治慢性病。

我们知道，荨麻疹、带状疱疹之类顽固的皮肤病西医是没有特效药的。我们中医不管它是何
种病毒，长何种疱疹，我们看问题很简单，所有的疱疹其实就是本条所说的，湿气到了皮肤
下出不来了，于是形成疱疹。再辨证如果是太阳证的话，我们就可以用桂枝麻黄各半汤来治。
我用这个方子治好的皮肤病很多，都是三五剂药就能治好。

我有一个朋友，自己家里有搞医的，去泰国旅游一趟回来得了荨麻疹，吃了一年多的中药还
只是好些了，没有治愈，平时什么葱姜蒜海鲜都不敢吃，说是发物。我治这个病从来不禁发
物，不但不禁，麻黄桂枝生姜本身就是最发的东西。病在表从表解，发出去病就好了，这就
是道家的顺应思路。我那个朋友吃的方子里都是些什么丹皮、白藓皮、金银花、生地之类，
说是清血热，结果清了一年多还没清好。这就是后世中医的思路，不从整体来看待人体，而
是局部的得出一个结论：“血热”，然后用药去对抗，去清这个血热。为什么治不好，原理我
在前言里已经说过了，西医以药治病灶也好，后世中医以药治“症”也好，其实是一回事，五
十步笑百步而已。

那什么是“证”，什么又是“症”呢？“证”者证据也，是人体的整体运行上出现了问题，显现在
外部的证据，比如口苦、肋胀、发热、痞痛之类，通过这些证据去找出人体是如何失衡的；
“症”本身的就是结论，如气虚血虚肾虚脾虚之类。这是不一样的两种辨证理念。一个是以证
来推断人体的整体运行；一个是忽视整体，将人体出现的证和具体的脏器和气血的本身联系
起来。

当我们用药物去健脾去凉血的时候，我们已经是在代人体行事了，药物又怎么能替代人体本
身呢？所谓治病求其本，并不是说这个病是肝的问题，那个病是肾的问题就是求其本，而是
要再问一句，肝为什么有问题？肾为什么有问题？你又没比别人少吃肉少睡觉，甚至补肾清
肝的药吃了一大堆，为什么还有问题？还是要回到人体的大循环上来。《伤寒》的思路是着
眼于人体大循环的，所以《伤寒》不讲肝怎样肾怎样血怎样气怎样。还是那句话，人身自有
大药，要让人体自己去补去清，我们只是用药去恢复人体秩序，不能代人体行事，这才是道
家的顺应医学。

下面讲白虎汤，这是用途极为广泛的一个方子，治温病治热证的。《伤寒》也是有温病这个
体系的。六经辨证，各有阴阳，本来就没有偏废。《伤寒》不分派，不分什么温病派滋阴派
扶阳派，人体就是人体，人体没有派别，疾病没有派别，只有辨证施治。一分派就已经背离
医学之道了。

26、 服桂枝汤，大汗出后，大烦渴不解，脉洪大者，白虎加人参汤主之。

白虎加人参汤方

知母 六两 石膏 一斤（碎 绵裹） 甘草 二两（炙） 粳米 六合 人参 三两

这里说的是桂枝汤使用不当，误汗后转为热证的情况。

先说脉象。从这个方子来看，再次说明洪脉、大脉在《伤寒》里确实是津液虚的脉，因为这
个方子里有人参粳米救津液。阳气亢而津液虚的脉一定要沉取才能判断，沉取是空而无力的。
这里脉洪而大，脉洪大说明阳气有余，津液虽虚，阳气却是很亢盛的。

再说病位，这是太阳和阳明同病，也就是表里俱热。怕热汗出是表热，大烦大渴是里热，是
胃热现象，胃属阳明。

石膏这个药要重点说一下。石膏煮出来是无色无味的清水，细品有一股微微的寒凉之气。寒
不用解释；凉事实上是一种冷而散的味道，比方说薄荷糖就是典型的凉味，所以能去表热。
石膏寒且凉能同时去表里之热。

这个方子石膏用一斤。汉制一斤是今天的250克。石膏治阴证的标热都可以用到三五十克，
因为药力不重，又是矿石，很压秤，要重用才有效。石膏这个药一定要用生石膏。煅石膏性
质相反，不解热而收敛，用了耽误事。现在很多医生治热证习惯性的开个二三十克，说明他
们没有亲身试验过这个药。很多大医家清热不喜欢用黄连黄芩这样的苦寒药，而是用石膏这
样的寒凉药。因为芩连是苦的，苦的作用主要是降，就是将气血往下拉，是折损气血的，苦
寒药吃的时候虽然感觉去火了，但气血被强制下行了，不吃了又会再次上火，上得更厉害，
因为人体的气血还会反弹回来。甚至有人吃苦寒药吃成了心悸气上冲的反应，这就是气血受
损了。石膏只是寒凉而不苦降，药力和缓而不彪悍，不容易折损气血，所以用石膏清热不容
易反弹。后世用药一个很大的弊病就是惯用芩连清热，病人就会依赖医生，病迁延不愈，吃
的时候好一些，不吃又不好，总在吃药。

知母，苦而阴润，有点像树的嫩皮汁液的味道。这个药形象的说是从云化雨的，炎热的天气，
哪怕冷空气来了，要有点潮气才能下雨。后面有一个桂枝芍药知母汤，主治阴证的下肢关节
湿痹疼痛。这个方子里为什么用到知母，打个比方吧，热性药材让骨节间的湿蒸发为热气，
知母再将其化合为废水从小便排出去。

所以知母有利水的作用。

方中的人参在第9条里已经说过，是亢奋阴的，生津液治口渴，寒热不禁。粳米是直接补充
津液的。

我们《伤寒》的第一章还没有学完，其实已经讲到太阳病，少阴病（桂枝加附子汤），阳明
病的治法了。六经已涉及三经。所以伤寒还是很好学很好理解的。

今天就讲到这里，谢谢大家。

== 2014-05-17（28）

希彦老师2014-5-17晚《伤寒论》讲课笔记第七次

每周和这么多热爱中医的朋友的在这里见面，是很开心的事情。 还是老规矩，先答疑，后
讲新的课程。

=== 答疑

有朋友问到说：“如果说有皮肤病像湿疹，病在表，是不是就是应该是脉浮”?

我觉得这个问题问得很好，对临床很管用。所以先回答这个问题。

在回答这个问题之前，我要说一下，我在之前的课里讲到更多的是关于《伤寒论》的辨证体
系，为什么要用六经辨证体系？为什么不用经络和脏腑来辨证？这方面讲得比较多。是因为
张仲景找到了在汤液学临证上最有效的辨证体系。这是得到了几千年印证了的。张仲景为什
么主要以问证来断病，而不是像后世医家那样主要凭脉来断病，也是同样道理。

那为什么《伤寒论》是以问证为主看病，后世以脉像和舌像为主来看病？因为脉和舌象有时
候并不准确。

比如说我们有表证时候脉不一定浮，有里证脉也不一定沉。舌像呢，舌苔黄舌体大未必是热
症，舌体瘦薄也未必是寒症。

在反应人体上，舌像往往体现的是标，而不是本。正是因为脉和舌像这两个东西它具有不确
定性，所以《伤寒论》是以问诊为主的。比方说有体痛发热一定有表证，有胸肋满痛，有忽
冷忽热一定有半表半里证，这是一定的，不会错的。 张仲景在脉上主要是判断阴阳的，比
方说在阴证的时候，一般都有脉的印证，“脉微细”，“脉弱”。脉是用来印证问诊的，四诊之
末，也就是最后一步才是脉。我的经验是，脉在阴阳的辨别上很准确；而辨表里病位，必须
要问诊。

现在的医生摸个脉就开方，只说明一个问题，这是一个不会传统方法的中医。

我们这个群里头，当有些人来求医时，群主有个详细的问诊单。其实这个问诊单里面所包含
就是一整套《伤寒论》的问诊法，详尽的对一个人的病位和阴阳进行一个了解。所以大家可
以去看一下这个问诊单，了解一下传统中医的严谨和对人体认知的全面。

有朋友问桂枝加附子汤如何运用？借这个问题正好可以说一下前面学过的太阳病篇的临证运
用。

我说两个自己的医案吧，我在临床上经常用桂枝汤或者桂枝加附子汤这两个方剂止汗。

我曾经治过一个病人，问证问不出来什么证，就是汗出如洗，每天都不用动，有时稍微一动
汗就像流水一样，凉席上都淌水。脉浮大。汗出是病在表。因为表有邪气，人体就要用汗来
解，汗出而病不解，则总要出汗。 我用桂枝汤，吃完第一剂的时候汗出得更厉害了，病人
问我说怎么汗出得更厉害了？我说没事继续吃，吃完第二剂的时候就止汗了，再也没有出过。

如果有人说桂枝汤是发汗的，或者桂枝这味药是是发汗的，千万不要跟他学，这不是传统中
医，甚至不是个真正的中医。

有人说，桂枝发汗，桂枝汤止汗。学医不能玩文字游戏，更不能为辩论而辩论，这是古今很
多医家的通病，所以仲景之后医学的理论越来越丰富，而临证效果一直在退步。医学要实证，
甚至要自己去试药，才能当医生。我就经常自己试药。有次我煎了一些桂枝，就桂枝一味药，
朋友带一个两岁半的小孩来玩，要喝，就给他喝了大约共十克的剂量，结果告诉我说，晚上
这小孩睡觉出汗明显比平时少了。

所以我们现在讲一些对药物的新的理解方法和对人体的新的理解。其实不是新的，是真正的
传统中医的理解。现在传统的都变成新的了，反倒后世发展出来的谬论成了传统。

如果说病人汗出多，偏阴证一点的呢？就是桂枝加附子汤。我治过一个妇女，寸脉大，但是
尺脉很弱。多年来无故汗出，冬天也一样，而且经常烦躁，吃了很多药没有效果。那你看这
个证，寸脉大，有表证，那尺脉没有呢？只要尺脉没有，一定是三阴证。因为尺脉是主阴，
阴是有形物质，是津血。我们前面说过，《伤寒论》是以津血的盛衰为原则来分阴阳的。津
血多是阳证，津血少是阴证。

既然偏阴证，就用了桂枝加附子汤，病人也是一两剂之后出汗就基本上很了，几剂药之后就
好了。后来又有过几次汗出的迹象，这个方子一吃就有效。这个方子在临床上还可以用在有
很多病上面，一下子也讲不完。我就举一两个汗出的例子来讲，这也是配合太阳篇的条文。

今天的答疑就先到这。十五分钟后继续《伤寒论》条文的讲解。

=== 条文讲解

28、服桂枝汤，或下之，仍头项强痛，翕翕发热，无汗，心下满，微痛，小便不利者，桂枝
去桂加茯苓白术汤主之。

桂枝去桂加茯苓白术汤方

芍药 三两 甘草 二两（炙） 生姜 三两（切） 白术 茯苓各三两 大枣 十二枚（擘）.

此条文普遍都认为有错误。应该是去白芍，而不是去桂枝，因为仍有表证，所以不可能是去
掉桂枝。那什么要去掉芍药呢？因为芍药我们说过是敛津液，是阴成形的。而此条有湿证，
湿为阴邪，所以不能用白芍。

现在说说湿证，湿证是很常见的证。这里的情况是湿阻中焦脾胃，说了三个证状： “心下满”，
心下一般来讲指的是心脏以下腹部以上，胃周围的这一片区域。为什么张仲景不说湿气在脾
或在胃，而说是心下呢？还是那个原因，在张仲景的眼中，人体是用层面来区分的，湿气可
以在上中下焦，可以在表在里，却不可能只在脾只在胃。邪气的也好，药物的作用也好，往
往都是层面的，不是定点的。所以仲景用的是“心下”这个词，这种词语是很能反应仲景的人
体观念的。心下满说明湿气囤积在这个区域，所以感觉到胀满。

“微痛”。心下至腹部的“痛”一般多见于陷胸汤和承气汤方证，此区域的痛在湿证里不多见。
“微痛”，只是轻微的反应，可见还是以满为主，有可能是湿证引起的胃的轻微疼痛，湿证型
的胃病很多。

“小便不利”。这里说的是水湿不运化下行的“小便不利”。这个证多种情况下都有可能发生，
有津液虚极的小便不利；有热炽伤津的小便不利；有湿证的小便不利。所以《伤寒》的原则
不会是单一证状，而是多个证指向一个结论，且还要印证于脉。单个证状是会有歧义的。这
一条的小便不利是偏向于虚寒的，当然没有那么寒，真正阴寒的湿证在茯苓白术之外还要再
加干姜附子。

茯苓和白术是极为常用的两样祛湿药，经常同时使用。

先说茯苓。茯苓是寄生在松树根上的菌类，乃松根之精华。我常说中医不仅是道，也是艺术，
随便说几样常用药就美得不得了：芍药是芍药花的根；丹皮是牡丹花的皮；桂枝桂皮是桂花
树上的，桂花本身也是药；栀子是栀子花的果实；辛夷花是玉兰花的花蕾；佩兰是兰花科的
茎叶；还有竹叶、菊花、柏叶、各种香草香料等等，真是既入药，又入画入诗。

茯苓煎成的水就是清水，无色无味在本草上称之为“淡味”，味淡的东西性质是向下的，就像
清水永远往下渗一样。甜的东西才会粘住，所以甜入中焦。药物对人体的作用就是这么简单，
不必去牵强附会那些所谓成份的作用，把问题搞复杂了，反而离真理越远了。成份的作用有
没有？有的，但真那么起作用吗？却未必。比如一个人胃寒了，多少维生素片下去也未必吸
收；胃热起来了，运化正常了，不用维生素片，吃几片青菜能吸收到足够的维生素。

所有的营养补充剂在理念上都是试图越过人体正常吸收功能去行事，结果往往是不但没补进
去多少，反而加重肝肾负担，所以现在富养型疾病特别多，就是营养囤积不吸收成为负担造
成的疾病，心血管病、糖尿病、癌症都是这一类疾病。

茯苓不寒不热而清爽，所以下行的不是火也不是淤血，而是将水湿这样粘腻的东西带下去。
有说茯苓利水，有说茯苓安神，有说茯苓治眩治心悸，其实就是这个下行之力。同样是下行
药，石膏凉而寒，是降热的；知母苦而润，下热兼生阴；白芍阴润苦酸，得阴气最全，敛降
津液而强阴；赤芍比白芍苦，则重凉血破淤之力；桃仁苦温而味厚，所以下血破血；厚朴苦
温而气厚，下的是气，除腹部胀满；芩连类苦而燥，毫无滋养之性，且下降之力彪悍，下热
的的同时折损气血。这些药单味煎来尝过就很容易区分开来。

我理解药物不喜欢说“用”，比方说茯苓安神利水治心悸就是用，我喜欢说“体”，就是这个药
的本体作用。说用容易不求甚解，容易理解局限，不知道其原理，单知道个治心悸，到底是
治哪种心悸呢？这就容易用错。况且药物不能代人体行使某样指令，更不能直接祛除某种病
证，它只是一种作用于人体的能量，当这种能量顺应了人体辅助了人体，让人体回归正常秩
序，人体自己的力量便能祛除病证。所以只有理解药物的“体”才能准确而变通的将药应用于
百方百病。

白术香燥而温，根入药。植物一般是枝叶气烈而发散，根茎味厚而收敛。白术却是根部有香
燥之气，所以其气偏厚，是一种温厚的香气，这种香气闻一下就能感知到，是走不到体表的，
充其量就在中焦的位置，所以是气化中焦的药，能燥散中焦水湿。中焦涵盖脾胃，所以说白
术去脾湿去胃水。

《神农本草经》上说白术主湿痹、死肌、止汗、消食。湿痹消食很好理解，死肌呢？脾主肌
肉，脾健运了，肌肉自然能得以滋养而生肌；湿气不是汗解就是尿解，湿气多的人有时候汗
也多，湿去了自然止汗。后世有说白术是止泻的，这个好理解，湿气从肠道走会腹泻，湿去
了自然止泻。有用白术治便秘的，这个怎么理解呢？脾胃不气化，水湿不能化生为津液输布
全身，于是水湿囤积在中焦，而下焦的肠道粘膜却得不到津液的滋养而干结。白术让中焦气
化运行，津液化生了，得以输布至肠道，于是也就不便秘了。治病要求其理，识药也要求其
理，这样心里才能清晰明了。

苍术是白术更偏根须的部分，其气更香燥，运行力更强。古人是苍术白术不分的，统称白术。
临床上可以兼而用之。

这两样药综合起来可以这么理解，白术将能气化的水湿气化为津液和能量让人体利用；茯苓
将不能气化的废水淡渗下去排出体外。所以这两样药能相须为用。

《伤寒论》的原则，北窗不开，南风不入。但凡人体里有湿淤食淤血淤之类的瘀阻，表气是
打不通的。所以要想要想解决表证，必须同时祛瘀。

茯苓白术在临床上是使用频率极高的药，所以讲的比较详细。今天就讲到这里，下周再接着
讲。谢谢大家。

== 2014-05-24（29-30）

=== 答疑

刘希彦老师(885477952) ：

大家晚上好。

还是老规矩，先答疑，后讲伤寒论。

有朋友说，他不是学中医的，不学中医基础知识能学好伤寒论吗？

我用语音回答这个问题。

这个问题呢我从两个方面来回答。这位朋友是来自我们群，他说他不是学中医的。首先我讲
这个问题。你所指的学中医是什么呢？是不是中医药大学的学中医的。如果说你认为中医药
大学的学中医的才是真正学中医的。那这个问题呢我觉得你有可能弄错了。像现在我们在这
里学这个经方，学《伤寒论》，学汉代之前的传统中医，我负责任的告诉你，真正学院学中
医的在你面前他称不上学中医。所以说你才是真正学中医的。

现在这个中国的教育中国的学院问题很大，这个大家都知道。中国的学院在西方文化的方面，
它往往是很落伍的。它要传授一些早就已经落伍的知识。这些已在外国的大学效法过了。那
中国的大学在传统文化方面呢？因咱们的历史的原因，他所传授的是一些被歪曲了的传统文
化。所以我们才要到这里来寻求。

那没有中医的基础知识能不能学好《伤寒论》呢？我教学生也有五年了。以我的经验，哪怕
你没有任何的中医基础，直接学《伤寒论》，一般来讲，如果你够用心的话，半年到一年，
你就能够对付，那么说你就能够成为一个临床效果很好的一个医生了。你没有学过之前的中
医基础，我甚至于要恭喜你，因为你没有学过很多的可能并不正确的中医观念。用胡希恕先
生的话说，学《伤寒论》三年期满，皆能行道救人。我认为这个只是一个比较保守的说法，
“三年期满”，应该指的是最普通的普罗大众，像如果说对传统文化感点兴趣的，悟性比较好
的。“一年期满”就可以了。所以说大家放心，学《伤寒论》并不是你们所讲的那么复杂，那
么麻烦。真正的医学，真正的传统文化，它是很好学也很好用的。学不通，学不会，学了没
有用。说明你没有学对。

好，关于这个问题我就解答到这里。

现在讲讲第二个问题。

有朋友经常会问到高血压的问题。因为高血压这个病呢很普遍。那么说关于这个问题的原理
和治疗。我今天在这里大致的说一下。人类呢他是这个地球上唯一直立行走的动物。所以说
比方说一只老虎，它可能有500斤，但是它的高度不及我们高。那这是人类的第一个特点。

人类的第二个特点。人类有一个巨大的大脑，有一个消耗人体相当大一部份气血功能的一个
大脑，这个大脑之大也是一般的物种所不能比拟的。人类的海拔高加上大脑消耗气血之多，
于是人类面临了一个困境就是，他把足够的气血把足够的血液送入大脑很不容易。那负责人
体送入大脑的这个功能在哪儿呢？在下焦，在下焦元气之所主，也可以说是肾脏。就像这个
一般我们的水泵主在下面一样，把这个水“泵上去”，所以当人上了一定岁数，他的元气功能
肾的功能衰退了之后，那他就不容易把这个气血送入大脑了，那我们知道，大脑是不能缺气
血的，缺气血大脑就会痴呆就会死亡。

那这个时候怎么办呢？这个时候人体就会产生一种自保功能，这种自保功能就叫高血压。高
血压是什么呢？它事实上就是通过把血管壁变厚的方式来增加血的压力以送入大脑，我打个
比方，当这个水管里面的水很少的时候，压力不够的时候，我们把水管捏一下，捏小一点，
这个水呢它就送出去了。那么高血压也是这样，它能过把血管壁变厚的方式，使血的压力增
强了，于是就送入大脑了。所以我经常讲，疾病不是人类的敌人，疾病是人类的朋友，是人
体的自保模式，没有疾病，我们一刻都活不下去。西药强行降了血压的方式呢，事实上它更
加的伤害肾脏，伤害肝脏，伤害人体的这种输送血液的功能。所以这是一种既不能彻底治愈
又不得不偿失的治疗方式。所以说我们中医呢，在治疗高血压方面呢就有了一定的优势。就
是我们能够着眼于整个人体功能的这么一种培养和治疗，来达到让人体自己。。当人体的元
气功能够了，气血功能够了的时候，人体是一个智能系统，它会自己把这个血管壁变薄，把
这个所谓的病灶给它消除。

那高血压病人需要注意什么呢？当然除了注意好的生活习惯锻炼休息，来让自己的气血功能，
元气充足之外，还有一点就是，一定要注意，你的体表是畅通的，我们说的是表气是通畅的。
为什么呢？因为从这个病来说，当你的体表不通的时候，那么说你会更加的加大了血管里面
血液的这么一种压力，他在某些时候就会更容易突然一下把这个血管壁冲破形成脑中风，那
我们知道，我刚才说到一个“表”的问题，为什么说到“表”的问题呢？如果你已经是高血压了，
你怎么样舒解这个血管壁的压力呢？是不是我们的这个体表通畅，这个血管里面的血液它除
了血管就化身为津液，这个津液能够气化出人体，它是不是血管里面的压力就小了，我们看
一个这几千年以来最常用的一个高血压的一个方子，叫“小续命汤”。这个方子最早是孙思邈
提出来的。

小续命汤呢，历来版本很多，但是呢，它有基础的两类药是不会轻易动的，第一个就是“麻
黄桂枝”解表药，第二个就是川芎这一味去淤血的药。我在之前说过。人的表气不通呢，第
一是因为这个津液的化身功能弱；第二呢，当人体里面有淤阻的时候，无论是淤血是湿气还
是积食就是有过多的饮食，人体的表气都不会通，那一般的老年人呢他一般就是体内有淤血，
体内的化身能力也不够，所以这个小续命汤这个方子，它就是“建中”，用甘草啊这些。建中，
解表，加去淤。所以说它就抓住了这个高血压的主要矛盾，以至于说哪怕不会辨证的人，使
用这个方子治疗高血压多数时候也能够奏效。

当然了，我们不是说要用这个方子去滥用，也还是要辨证，我只是说这个医理。

那家里如果说有高血压病人的，尤其是老人有高血压的，那应该注意什么呢？我教你们一个
急救方法，就是在家里所有能够容易够得着的地方，放上针或者类似于针的尖锐物品，一旦
发生高血压的这种征兆的时候呢，第一件事不要去打急救，第一件事情应该拿针先扎自己的
耳垂扎出血然后呢再扎自己的人中扎出血，然后再是十个手指尖，也要扎出血，重一点没有
问题。为什么呢？因为这个血管它破了它爆了其实只差一点点压力，它不会是差很多压力，
差很多压力它就全爆了。它破一个小口子它只差一点压力，你马上把这种压力释放出来，那
么说它的血就不会继续的伤大脑，你明白了，所以说这个病人也许说该瘫痪的不瘫痪，该死
亡的他可以不死亡。然后再去打120。所以说把这一点告诉身边的有这个疾病的朋友。

=== 条文讲解

希彦老师于“伤寒经方求真群”《伤寒论》讲稿（第八次讲课）

今天是伤寒论太阳病上篇的最后一次课。

我看很多初学的朋友已经开始给身边的人开方子了

先不要着急，不把六经病学完，不要急着行医。会弄错。

真正的中医就像破案，需要来回比对寻找，需要综合分析。

下面正式开始讲课。

29、 伤寒脉浮，自汗出，小便数，心烦，微恶寒，脚挛急，反与桂枝，欲攻其表，此误也。
得之便厥，咽中干，烦躁，吐逆者，作甘草干姜汤与之，以复其阳。若厥愈足温者，更作芍
药甘草汤与之，其脚即伸。若胃气不和 语者，少与调胃承气汤。若重发汗，复加烧针者，
四逆汤主之。

此条阐述了病在阴证和阳证之间的转化规律和治疗方式。

首先是“自汗出，小便数”，说明这个病人的津液在通过两种主要途径在大量的耗散。我们说
过在《伤寒》里区分阴证和阳证就是津液的多少。这个病人“心烦”，这是津液虚的虚烦；
“微恶寒”是脉微怕冷；“脚挛急”是筋失养了。

脉微；怕冷；筋发生挛急反应，脚伸不直了，这些证都指向津液虚，这就已经是明显陷入阴
证的指证了。这时“反与桂枝，欲攻其表，此误也”。阴证不能发汗攻表，因为在人体津液不
够的时候，人体的自然模式是先保里，先保内脏，这时候还用桂枝攻表以耗散津液，自然是
误治了。

误治的结果当然是造成津液更虚了，于是“得之便厥”，“厥”的意思是四肢冰冷，气血已经不
能够往四肢走了，这是比较严重的阴证了。

同时还有“咽中干，烦躁”，这两个像是热证，为什么比较严重的阴证还会出现热证呢？还是
要说到人体的自保模式，当津血不够的时候，人体就要亢奋起来，以加快津血的运行和生成，
于是产生这种上火的反应，我们称之为“虚火”，也就是津虚而有火。咽喉是全身阴经的交汇
点，所谓诸阴之汇，是需要大量津液滋养的，在这种情况下首先就会“咽中干”。还会“烦躁”，
我们称之为虚烦。虚烦也可理解为大脑通过情志反应在调集津液。同时还会发生“吐逆”，因
为胃部的津血供应不够了，消化能力弱了，胃不受纳了。

这时候要“作甘草干姜汤与之，以复其阳”，阳就是津液。我们以前说过，表里同病是要先表
后里的，这里也有恶寒表证，为什么只用温里的药呢？这又牵系到另一个法则：三阳病是先
表后里，三阴病是先里后表的。这里表证并不严重，所以治里就可以了，里阳温津液复，表
证人体自己就解决了。

后世医家碰到这种“咽中干、烦躁”的虚火虚烦的反应，处理方法一般都是滋阴清热去烦，用
药通常是生地麦冬栀子芩连辈。这是不推求人体原理不辨阴阳的结果。

如果是阴证的虚火，仲景的处理方法先要用干姜和甘草，来增加胃的生化能力，因为津液是
不能用滋阴药直接补的，而是要靠脾胃运化来吸收生成，这个原理前面已经解释过了。所谓
甘温除热说的就是这个。

有个前提，要在阴证或胃弱的情况下才可用此法。实热证当然要下热以存津。脉细数或虚大
的阴虚阳亢证则要用滋阴之法，也就是用麦冬生地了。这种阳气不虚反亢的阴虚证，实质是
脾胃不缺生化能力，甚至还有热，所以可以滋阴以制阳。

甘草干姜汤

甘草 四两（炙） 干姜 二两

上二味，以水三升，煮取一升五合，去滓，分温再服。

“若厥愈足温者”，意思服了甘草干姜汤后四肢不冰冷了，脚温热了，这时脚却还不能伸直，
说明筋还是缺少滋养。

为什么会这样呢？我们说过，《伤寒》的治疗法则是从阳引阴的，用药物让阳气先生成，然
后通过阳气的运行带动脾胃的运化来生成津液生成阴。可是，阳可以即有，阴却不能速生，
为了加快阴的形成，“更作芍药甘草汤与之”，

芍药甘草汤

白芍药 甘草（炙）各四两

上二味，以水三升，煮取一升五合，去滓，分温再服。

芍药是负责阴成形的，甘草是直接补充脾胃津液的。为什么要用炙甘草呢？因为《伤寒》补
阴始终不离脾胃，不逾越人体的自然生成机能。甘草干姜汤在前，芍药甘草汤后，于是“其
脚即伸”了。这个顺序是不能错的。中轴脾胃永远是治病的前提和关键，就像车轮的车轴，
汽车的发动机，后世之所以滥用滋阴寒凉药就是忽略了中轴脾胃的作用。

在误攻表伤了津液之后，也有可能发生另外一种情况，就是“若胃气不和，谵语者”。这种情
况是阳明证。阳明证一般是里热证，也就是是肠胃中实。

为什么会这样呢？前提还是津液虚了，人体要亢奋起来，一来是促进津液生成，二来是要靠
这种亢奋将津液送到大脑和五脏，以保证重要部位的供应。这时候肠胃中若有积滞，这些积
滞也要消耗津液来传化，里外都争夺津液，于是津液不够分配了。谵语反应说明大脑用亢奋
在争夺气血；肠胃的热结反应说明肠胃用亢奋在争夺气血。这就是阳明里热证了。

阳明里热证之所以还在阳证范畴，没有因为津液虚转为阴证，本质上不是津液不够的问题，
而是津液分配不来的问题。这也是阳明里热证和阴证的区别，也是阳明里热证的发病机理。
这就意味着只要将肠胃的积滞下了，津液就够分配了，人体也就协调过来了，病也就好了。

这时候要“少与调胃承气汤”。

调胃承气汤

大黄 四两（去皮，清酒洗） 甘草 二两（炙） 芒硝 半升

上三味，以水三升，煮取一升，去滓，内芒硝，更上火微煮令沸，少少温服之。



为什么是“少与”呢？因为服多了造成严重腹泻，津液就伤了。与治病不能大汗出，只能微汗
一样，津液伤了，又转成其它情况的病了。所以调胃承气汤里大黄虽然下四两，其实只让你
先服一点点，大便通了也就不服了。方后也注明了“少少温服之”。

说说调胃承气汤里的大黄和芒硝这两味药。大黄是植物的根茎，有走窜而寒凉的香气。其香
气自然趋下，有泻下破淤之力，既能下宿食，亦能下淤血，用途很广泛。芒硝是矿物质，微
酸而咸寒，其清热之力类似于石膏，其散结之力类似于牡蛎，只是性质要酷烈得多在承气汤
里取其清热软坚结之力。

大黄擅长破淤阻，芒硝擅长软坚结，所以这两个药经常相须为用。

接着讲下面的条文。用桂枝误攻表伤了津液之后，“若重发汗，复加烧针者”，也就是继续伤
津液，于是陷入阴症了，“四逆汤主之”。四逆汤是太阴病之主方，里是三味药，炙甘草，干
姜和生附子。

这里着重说一下生附子。

附子这个药是有毒的，阳毒，号称“扶阳第一药”，阴证没有它是不行的。生附子毒性更强。
植物的所谓毒性其实是偏性，凡物皆有毒，看毒理报告，连蔬菜水果都有致死量，只是偏性
弱，每公斤体重的致死量很大而已。生附子一般必须煎煮一小时才可服用。那煎煮一小时毒
素就分解了吗？当然不是全部分解，是部分分解，因为我们治病靠的就是这种毒素，全分解
了就没用了。

这里需要解释一下植物毒素的问题。我们知道很多植物未煮熟的情况下都有毒，比如蔬菜里
的扁豆，黄花菜。扁豆未煮熟毒死人的情况是有过的。植物毒素和化学毒素不一样，植物毒
素一般人体是可以辨认分解的，所以哪怕我们吃一辈子扁豆，里面的残余毒素不会造成累积
而肝肾衰竭。化学药品就不一样，化学药品的毒素是人造的，人体很难辨认代解，所以西药
吃成肝肾衰竭的很多。附子半夏这样的所谓毒性药材只要不发生煎煮不当的急性中毒，那些
老药罐子吃一辈子也没事。

附子和半夏这两个药，真治病不要用药店里的，那是用化学药品制过的，已经成药渣了，没
有疗效了，而且还有化学毒素。现在的扶阳派用附子动不动几百克一剂药也不见效，这就是
用化学药品用所谓新方法炮制传统中药的结果。这是另一个中医面临的大问题，以后再专门
讲。

生附子这个药大家可以找来没用化学药品制过的试一下，咬一点放在嘴里嚼，都不用咽下去，
立刻就会感觉到嘴麻头晕后背发热，说明它的走窜之力是很强的。生附子擅长于走，擅长与
将阳气四通八达。这就有一个弊病，阴证的病人首先是胃的生化能力弱，光用阳气通行全身，
胃不生化，岂不是更耗散气血，涸泽而渔？所以在《伤寒》里生附子必须和干姜同用，干姜
是温里，能促进脾胃的生化能力。炮附子在《伤寒》里是可以单用的，因为附子炮过之后，
其通行之力大减，其扶阳之力温和而绵长，没有耗散之弊。

在四逆汤里，干姜温里，附子通阳，炙甘草建中补津液，共治太阴里寒。

至此，太阳病上篇就讲完了。事实上已经降到了六经之四经，太阳、少阴、阳明、太阴的治
法。还有少阳和厥阴没有讲到。慢慢的，大家就对人体的疾病有整体的认识观念了。

今天讲的内容有点多，就到这里了，谢谢大家。

== 2014-05-31（31-32）

希彦老师2014-5-31于经方求真群周六晚讲课第九次

大家好。

最近天气热，温病比较多。

一年当中有两个时间段是温病最多的，一个是夏至之前，一个是中秋之后。

夏至之前，人的毛孔汗腺还没有完全打开，温度一高，能量没有出路，温病多。中秋之后，
汗腺已经趋于关闭，温度不降亦是同理。

行医之人不可不注意天人感应之理。

今天还是先答疑，再进行《伤寒论》的讲解。

=== 答疑

刚才说到毛孔的问题，这是人与天地交通最大的枢纽。

有朋友问到这样问题。经方-久久：病理的平素爱出汗症状，视为营卫不和，但是有人特别
不爱出汗是什么原因？据伤寒论93条：太阳病，先下而不愈，因复发汗，以此表里具虚，其
人因致冒，冒家汗出自愈。所以然者，汗出表和故也。里未和，然后复下之。这条胡希恕解
释说，汗、下误治，表里俱虚，此时人就不出汗了，等到出汗，就说明津液恢复了，可见这
种出汗属于人体自保功能，难道不出汗都是自保功能？都说明体内津液虚？还是说有别的问
题也可导致平时不爱出汗，请老师解疑。”

汗的问题。这个也是《伤寒论》里面的一个很大的问题，也是开篇的一个大问题。汗是这样
的。当人的津液充足的时候，有病邪进来，它是会发汗的；当人的津液不足时，一般是不会
发汗的。所以说“三阴证”一般不出汗，那津液更虚的人呢？身体更虚的人、气血更虚的人呢？
他甚至连发烧都不会发，人体嘛它是一个智能模式，对吧。你没有那么多的能量那么多的津
血，它不会发烧也不会发汗，所以说有很多亚健康的人他不会发烧。

所以说《伤寒论》里有个原则，就是说治疗三阴证它不能发汗，也是顺应人体的作为，它是
一个顺应的医学。我们的治疗是顺应人体的自我排病功能的，这是《伤寒论》的一个大原则。

那人体除了津液不够的不发汗之外，那人体还有没有别的原因的不发汗呢？人体还有另外一
个很常见的原因，他不会出汗，就是有堵塞。

这个堵塞是什么呢？比方说我们吃多了饮食，叫食积，积食是一种堵塞。我们有湿气，中焦
有湿气，这个也叫堵塞。我们说体内有淤血，这个也叫堵塞。人体是一个循环的能量场。它
的循环是从内向外这样的一个能量场。当有这样的不通畅时，人体是发不了汗的。这个时候
它的主要原因不是津液够不够的问题，而是堵塞的问题了。所以说《伤寒论》有这样的治病
原则，一边解表一边去湿，一边解表一边去淤血。它就是这样来的。

竹林听雨：讲义第6页“此六经对应的是《易经》的卦象”，老师，这里是如何对应的呢，又
是如何推演的呢？

这是一个很大的问题，我只能先简略的说一下。

首先，《易经》的卦象，它是一个“阴爻”，一个“阳爻”。它只有阴爻和阳爻的组合在变化，
来推演一切事情，它是一个极简主义的科学。用这种阴阳的组合可以把世上一切事情推求出
来，因为天地间无非也就是一阴一阳而已。

这个问题太大，我只能简而言之了。——比方说我们说太阴证，是不是就阴爻多呢？如果说是
阳明症，那是不是阳爻多呢？那泰卦应该是三个阳爻在下，三个阴爻在上，那如果说我们现
在倒过来，三个阳爻在上，三个阴爻在下，那是不是就是少阳证？

为什么张仲景他本身并不在《伤寒论》行文当中用《易经》的推演来推演人体？

就像我说的那样，大道是大道，但是大道还要化为具体的临证方法和对人体的认识才是医学。
从卦象直接到方子，这个不是那么容易的。况且真懂易理的人，是不必借助药物的。《伤寒
论》就是自道而来的术。《伤寒论》里面制定的几个大原则，比方说津液原则，津液多则是
阳，津液少则是阴。那以津液为原则来辨别病的实质和变化，事实上他就是在紧紧地守住阴
阳。把它化为具体的认识，就是津液了。所以说我认为这也是张仲景优秀的地方。

限于时间，这个问题我就先讲这么多。

竹林听雨：第7页“下焦主肾”，上焦和中焦呢？和手少阳三焦可有联系？

这个问题也问得非常好。我说过这个六经辨证是区别于经络辨证、脏腑辨证这些后世辨证的。
后世的辨证法里有个三焦辨证，那为什么说我会把三焦辨证也放进来讲呢？因为我觉得这个
说法很好。

伤寒论》的六经辨证是上下表里这样的一个认识。那为什么是上下表里呢？因为能量从下往
上走的时候是往上再往外。就是说想往外走往表走就必须得先往上走。想往里走呢？必须得
往下走。就是说主上亦主表，主下亦主里。所以说六经辨证的人体的运行方式是上下表里的
方式。那自然在运行过程当中，我们不仅有表里，还有上下，有上下就有中，所以说上焦下
焦中焦这三个概念，我觉得非常好！所以我也会经常提！



那下焦主肾怎么理解？你看这个措辞。《伤寒论》里边经常有这个“主”字。比方说某某症，
什么主之。“主之”的意思就是说以它为“主”，主要是它，这是一个不完全确定的说法。为什
么不完全确定呢？因为人体是层面的，下焦最主要的器官是肾。所以说下焦的功能主要跟肾
有关系。但是肾不等于就是整个下焦，下焦主元气，下焦也主阴，那自然肾不可能说代表整
个元气和阴的层面，它只是主要通过肾来体现。

什么是三焦？我们姑且给它下个不太精确的定义吧，它事实上就是人体里面的一个空壳，就
是承载我们的脏器的那个空壳，它里面有很多的淋巴，网膜组织，它事实上是一个水液代谢
代谢的一个空间，那这个组织它在半表半里，所以当我们说到少阳的时候，包括足少阳胆经，
也包括手少阳三焦，它事实上指的是半表半里这个区域。

今天的答疑就先到这里，十五分钟后进入《伤寒论》的学习。

=== 条文讲解

接下来是本周的伤寒论条文讲解。

今天开始讲解太阳病篇的中篇。

31、太阳病，项背强几几，无汗恶风，葛根汤主之。

葛根 四两 麻黄 三两（去节） 桂枝 二两（去皮） 生姜 三两 甘草 二两（炙） 芍药 二
两 大枣 十二枚（擘）

将葛根汤放在太阳病中篇的第一条是有深意的。这个方子事实上是上篇学过的主要法则的一
个总结。


“无汗”要用桂枝和麻黄这两味药合用发汗。

“恶风”是津液虚，用姜草枣芍药救津液。

这几个证都是以前学过的。

这个方子很有意思，它事实上就是桂枝汤加麻黄和葛根。有汗是用桂枝汤的，汗出津液虚了，
里面有姜草枣芍救津液；无汗是用麻黄汤的，麻黄汤是麻黄、桂枝、杏仁、甘草四味药，这
个方子以发汗为主。现在的情况是津液又虚又无汗，怎么办？于是用桂枝汤合了麻黄和葛根。
按说津液虚是不能发汗的，但病在三阳，救了津液是可以发一点汗的。

由此也可以看出，组方用药是以津液盛衰，也就是人体的能量盛衰为原则的，这是方证里面
的规律。所以治病求其本，辨证也要求其本，不能只死板的对应方证。

这个方子的另一个特点是葛根和芍药同用。葛根是升津液的，白芍是降津液的，它们的作用
会不会互相抵消。我经常被问到这个问题，力量相反的两个药在一起会不会抵消？药物在一
起是不会抵消的，寒药和热药在一起也不会变得不寒不热，因为药物是走层面的，它们各有
各的层面，各有各的道路。葛根升津液是从肠胃往上升津液，芍药降津液是将全身的气血往
回收往下降，本就是两回事两条路。又如黄芩，是降半表半里和三焦系统的热的，干姜是温
里增加脾胃功能的，经方里它们经常在一起合用，也不会一寒一热互相抵消。

葛根汤治现在的一种常见病颈椎病很好用。

当然，我们不能说某个方子治某个病，这不是中医精神。我们要辨证。肩颈酸痛属于哪个病
位？表证。颈椎病是维系骨头的筋松弛了，脊椎承压便用增生来增强自己，人体自我保护模
式而已，只要是骨节增生的问题都是此理。筋的问题是津液的问题，这是津液虚。看脉象，
津液还没有虚到阴证的程度，那就还在太阳病的范畴。津液虚的太阳病用桂枝汤，上部缺津
液加葛根；有汗无须麻黄，若无汗更加麻黄——组出方子来就是葛根汤。

上面演示的就是一个完整的《伤寒》体系治病的过程。

六经辨证治病就是这么简单，先六经后阴阳而已。无须止痛药，也不需要什么补气养血药，
它只去着眼整体恢复人体的平衡，秩序恢复了，津液就会自回，人体很快就会自愈。《伤寒
论》的六经辨证是一套真正以一驭万的方法，其中的方子也是外感病和内伤病通治的。很多
病人拿着拍的片子去找中医，其实真正的中医是不需要看片子的，甚至不需要问病名的。只
要问证就好了，然后按六经辨证之法分析人体出现的问题，就能组方子。吃了药你想治的病
会治好，不想治的病也会治好。我自己还不会治病的时候，去找一个老中医治我的颈椎病。
我没有说我还有失眠和便秘，结果吃了药都好了。

在这套方法里我们可以看出中医的核心理念：其一，中医是辨证施治，而不是辨病施治。其
二，中医是思考人体的，而不是研究病灶的。其三，中医治疗的是人体整体上的问题，而不
是病本身。人体治则病治，像西医那样只治病灶不治人体，伤害人体不说，就算暂时对付了
症状，病还会复发和传变。

开篇借葛根汤先重申一些中医独有的思维方式。

太阳与阳明合病，必自下利，葛根汤主之。

这一条简单来说，就是太阳病再加上腹泻，也可以用葛根汤来治。腹泻证是里证。里证属阴
是太阴，属阳是阳明。这里虽然说是阳明，当然也不会太热太实，太热太实就应该合承气汤
了。

刚才说了，葛根是治上部津液虚的，腹泻要说津液虚也是下部津液虚，为什么腹泻也能用葛
根汤治呢？

太阳病，病应该从表解，如今表不能解，人体自然就要寻求其它解决途径，于是从肠道解，
变成了腹泻。葛根汤是主治太阳表证的，表证若从表解了，就不用从里从肠道解了，腹泻自
然就好了。葛根是从肠胃升津液的，能让陷于下部造成腹泻的津液回来，所以也能帮助止泻。

《伤寒》里很多药物和方子都是治上亦治下的，这也说明中医治病对人体的思考是整体的，
思考药物亦是药物在人体里的整体作用。

后世喜欢说这个药治肝治胃，那个药止痛止泻；或者说这个药治这个病那个病。这种说法是
人为的把人体割裂为一个个的脏器和局部的病症，这就失去了中医最核心的整体观，也曲解
了药物在人体里的作用，已经接近西医化思维了。用这种思维来指导辨证和用药无异于缘木
求鱼，自然是达不到好的治疗效果的。

今天就先讲到这里，谢谢大家。

== 2014-06-07（33-34）


今天好像是高考吧。这里有没有要参加中医药大学考试的学生，我在这里友情提醒一下。你
们在这里学了张仲景《伤寒论》的理念，千万别用这些理念去参加考试。那样的话你很有可
能考不上。

虽然都遵张仲景为医圣，但是在我们这个时代，真理的路上从来就是寂寞的，谎言的门前才
会挤破头。

闲话少说，还是先来答疑吧。

=== 答疑

晴天小师妹：半表半里在哪还是概念很模糊，只知道有淋巴等一些腺体，请老师再明确一下，
可以吗？

刘希彦：大家可以参看一下我在教材里面说的，“表”就是皮肤、肌肉、骨骼。“里”就是胃肠
道。表和里之外的中间区域，全属“半表半里”。他为什么会这样来分人体呢?

用这个区分法来区分人体，事实上是反映了张仲景最重要的一些思想。就是药物不治病，药
物是顺应人体去治病，药物是帮助人体自己去排病，它只是协助人体排病的模式。人体主要
是两个排病模式，要么从体表排，要么从肠道排，这是人体通向外面的出口。人体要把邪气
排出去，必须得走这两个通道。

那一旦进入这个“半表半里”了呢，那就麻烦了。所以这个“半表半里”从外出、从里走都不好
走。多数的疑难杂症，多数的慢性病，多数的脏器病，它的症都发在这个区域。这个区域的
病，它就要有另外一套解决方法，就是所谓“和解法”。

何谓“和解”呢？就是把病邪在三焦的淋巴系统排除掉。三焦是什么？就是空壳里面这些个淋
巴呀，那些个网膜啊，那些个黏膜组织啊，通过这样的一个系统，让病从这个系统里头往下
走，通过小便这个方式排除掉。

一般临床来讲的话，当你把这个系统疏通了之后，全身也就通了，病也会很自然的往体表和
往肠道走，所以说我们喝了小柴胡汤以后，有汗出而解的。

能量上下交换谓之和解，三焦这个地方，上下交换之地，上下不交通了，才会生病。

柴胡汤的方义是上下和解之法，上下和解了，人体循环通畅了，人体该汗汗，该下下了。

我曾经给病人用过小柴胡汤，那个病人一吃又腹泻又呕吐的。小柴胡汤是一个止呕止泻的方
子，止呕止泻在临床上很多用，那为什么他吃了还会呕吐和腹泻呢？说明药物没有什么止呕
止泻，所以说你顺应人体自己的排病模式，人体他会自己去排病，这是人体自己的方式。它
是这样的！讲的有点杂乱，大概解释一下是这样。

晴天师妹：如果食道得了癌症算半表半里症吧？

病灶没有“半表半里”的这个说法。打比方说，我们得了一个胃的病， 那算“里”吗？我的胃
有病了，或者胃里头长东西了、胃炎、溃疡了，但是我反应出来的证是什么呢？

反应出来的证是身上酸痛、汗出、头晕，也就是表证。如果这个表证指向桂枝汤，你下一剂
桂枝汤，这个胃溃疡准好。所以说我们不能说病灶在哪。

事实上你要问的是关于食道是哪个区域的问题。一般来讲的话，我们说人体没有绝对的划分。
我们可以这么理解，人体主上亦主表，主下亦主里。

我们可以这么理解，人体主上亦主表，主下亦主里。这么说吧，如果我们说胃和肠是里的话，
那脾呢？脾它也是里，但是相对于胃，它更趋向于半表半里一点。再往上的食道呢，就更趋
向半表半里一点。所以说，哪怕是表，皮肤就更表，肌肉呢，次之。

落实到用药的时候，也要有层面上的掌握的。这个以后在精准用药的时候再来说这个，我们
把人体当成一个区间去思考就好了，可以认为食道就是一个由里走向半表半里的途中的一个
区域。这才是六经的意义，就是用一个线段来划分每一个具体问题的具体坐标。

六经不是绝对的，在病位上只是我们定位的一个工具。

医易之道：老师，肝性条达，为什么会有泻肝，敛肝之说，泻肝可理解为泻胆，敛肝可理解
为肺的肃降吗？

刘希彦：肝主疏泄，“主”疏泄，说明这个脏器的功能它主要是疏泄，但是万物都是一阴一阳，
有疏泄，就有收敛。肝这个脏器也一样，它主要是以疏泄为主，但是它一定也有收敛的功能，
一定有一阴一阳。所以说当我们疏泄太过的时候是不是也需要收敛呢？

不能说泻就只能泻胆，胆也有一阴一阳，不能悬空解释人体，不能为解释而解释，这是后世
医家的弊病。

晴天小师妹：关于下焦，女性病，如月经失调等或者男性的前列腺症等，都属于下焦病吧，
都属于半表半里症吧？

刘希彦：你所思考的应该是下焦这个空腔里是属于半表半里吧。我觉得这还是前面这个问题。
病灶在哪，不等于病在哪。

为什么《伤寒论》可以用几个主方变来变去，几十味药来回组合就可以治一切病，就是因为
它不治病，它治的是人体的大格局，治的是人体的循环。

病在哪，不管！在于整个人体在哪里失衡了，假如说你得的是子宫的病，子宫在哪呢？不管
它，我整个人体的失衡在半表半里，有半表半里的证，那我就按半表半里的方子来治，柴胡
汤，你的妇科也就能好了，这就是《伤寒论》的思维体系。月

我一直在说这个问题，后世医学衰落的原因就是以药治病。总认为药能治病灶，药越来越多，
一个药店几面墙，何止几百味药。疗效呢？很多医学院的中医教授自己都不相信中医能治感
冒。

今天的答疑就到这里，十五分钟后进入《伤寒论》讲解。

=== 条文讲解

我们现在正在讲《伤寒论》，中篇的特点就是方子多。几乎经方的大多数主方这篇都讲了。
那经方的主方有多少，十几个。涉及药物多少，三四十味。却能治人体一切病。其中道理，
不言自明。下面接着讲条文。

33、太阳与阳明合病，不下利但呕者，葛根加半夏汤主之。

葛根 四两 麻黄 三两（去节） 甘草 二两（炙） 芍药 二两 桂枝 二两（去皮） 生姜 二
两 半夏 半升（洗） 大枣 十二枚（擘）

这一条是接着上一条来讲的，说明这一条的主证还是葛根汤方证，行文已略去。兼证不是下
利了，而是另一种阳明病，就是呕。呕是胃问题，在《伤寒》里胃的问题属于阳明，脾的问
题属于太阴。

“呕”前面说过，胃弱不受纳会呕，有表证气血上逆也会加重呕。有呕加半夏，这个都知道。
那半夏是做什么用的呢？

那半夏是做什么用的呢？半夏在经方里是最常用的药之一。这个药煎成水几乎无色无味，略
有些滑滑的。这个药力量很轻，小剂量不会有明显反应，大剂量的煎水喝下去之后有两个感
觉，一是呼吸顺畅了深了；二是喉咙里微麻。呼吸深了说明半夏有降逆的作用。麻呢？所有
麻的东西都有宣通和消散的作用。半夏的麻在喉咙和口腔，喉咙是诸阴之会，说明半夏是作
用于阴的——痰和饮都属阴。喉咙和口腔又是里和半表半里（也就是肠胃和三焦粘膜系统）的
出口，咽喉麻了说明人体里面也是麻了的，只是人体里面没有神经感觉不到。

这么推求，半夏就是作用于里和半表半里的。半夏没有热能，所以宣通的作用不强。半夏煎
的水有些滑滑的，用同气相求原则，也能证明半夏消散的应该是水和痰层面。历来说半夏的
作用无非化痰散结，止咳止呕，就是这么来的。

举个临床上的例子吧，半夏是可以治失眠的。

有人会说，半夏跟失眠有什么关系，半夏不是治痰的吗？我们知道，失眠无非是阳在上，是
晚上阳不入阴，降不下来。如果这个“阳”的实质不是实火，而是痰和水层面的郁火，半夏就
能有作用。

这也说明，药在人体里面只是一个能量场作用，如果人体通过降逆消散的能量作用达到了正
常的状态，相关产生的病症就都能治。所以不能说药物治失眠这个病，也不能说药物治痰这
个症，这都不是真正的中医思维方式。而是要弄清楚药物在人体里到底起什么作用。我们现
在药物学，一堆药治什么病治什么症，对于药的本体作用却笼统得很，无非是寒热补泻之类
大概其的描述，总之落不到实处，结果用了有效没效都不知道个所以然。

后世医家喜欢把药物的作用一味玄学化，尤其是明清医家多有此弊，说到药物喜欢绕天文地
理阴阳五行之类的玄学名词。比方说半夏是“禀天秋燥之金气，入手太阴之肺经。”

这两句话，前半句玄之又玄，后半句似为针灸而设——药物进入人体走的是大层面，又不可能
顺经络而循行，只有针灸才能定位经络。

这都是不落到实处的医学，只是文字本身的一种圆满。中国文化用金木水火土之五行来对一
切，只是一个代号，只是一种意向，并不等于肝就是木，肺就是金，就像处女座并不等于是
处女，狮子座也不等于是狮子一样。

你在大道理大意象上说通了，人体里面到底怎么样了，具体的机理是什么？还是落不到实处。
再说了，治病的时候还在绕玄学名词，只会把实际问题搞复杂。说明还没有参悟到大道至简
的境地，这样治病犹如秀才造反，纸上谈兵，必定是要打败仗的。仲景之学的好处就在于朴
素，虽然里面有大道，并不是空谈大道，而是落实到人体的机理：病位怎样？津液怎样？表
里上下的运行怎样？这才是道以致用，这就是仲景之学这两千年来高于众人的原因。

半夏这个药如今问题很多。现在药房的半夏几乎是无效的，用了也是耽误事，因为都是用明
矾石灰水反复煮过制过，就是药渣，哪能有什么效果。

为什么要这样制呢？因为生半夏是有毒的，会引起过敏，严重的急性中毒甚至会引起死亡。
半夏是天南星科，和芋头是一个科属，其毒素和芋头毒素是同一类。削了生芋头手是会发麻
的，就是这种毒素的作用。植物毒素是普遍存在的，蔬菜里也有。绝大多数植物毒素都有高
温分解的特性，半夏毒素也是如此，所以半夏经过煎煮是不会引起中毒的。

《伤寒》里用半夏只注明一个“洗”字，可见用的是生半夏。近代名医张锡纯用生半夏，只用
开水浸一浸晒干就入汤剂直接煎煮了，稍制其毒性而已。这些方法都可以仿效。真要治病还
是要用生半夏才能有效的。《伤寒》里用半夏论升，据考证，汉代的一升半夏约等于130克，
这个方子里半升就是65克。半夏煎出来的水味道很淡，说明这个药力量很轻，所以要重用。
在《伤寒》里一般是65到130克的区间。为什么现在中医不治病治病慢，从药物上来讲，半
夏这味药是最能说明问题的，炮制方法是问题，剂量更是问题。

34、太阳病，桂枝证，医反下之，利遂不止，脉促者，表未解也，喘而汗出者，葛根黄芩黄
连汤主之。

葛根黄连黄芩汤方

葛根 半斤 甘草 二两（炙） 黄芩 三两 黄连 三两

这是由桂枝汤证误治，转为阳明证的病例。此时的证是“利遂不止”，就是腹泻不止。腹泻有
寒有热，这里是寒是热呢？要接着看下面的证。

“脉促”，前面说过，脉促是脉往寸部顶，寸主上主表，人体的气血往哪里走说明哪里有病邪，
这里是因为表证未解。

“喘而汗出”，这是一个很典型的情况。一般来讲，外感病无汗才喘，因为气血上涌不能出表，
汗出了就不喘了。这里汗出了还喘，说明是肺里面有热，人体要用喘的方式将热排出去。肺
有热也会移于大肠，所以同时有腹泻。综合起来看，这个腹泻应该是热性的。

这个方子用药很简单，炙甘草是建中补津液的不用讲。黄连和黄芩是苦寒药，是降火的。这
两样药性味相近似，只有味，苦味；没有气，不能行散。从层面上来讲，这两种药是降里和
半表半里的热的。黄连的苦味尤重，几倍于黄芩，所以黄连的作用更偏里，而黄芩的作用更
偏半表半里。葛根是升津液为主，兼能滋养津液的，其用量很重，汉制半斤，一百二十多克。

这个方子有意思的地方是药物的搭配。葛根升而芩连降，一对矛盾的组合。其实是不矛盾的，
前面说过，药物走的是不同的层面。芩连是降里热，将肺和大肠里的热排出去；葛根从肠胃
升津液，同时作用，自然就止泻了。

我们前面说过，表里合病的治疗原则是要先表后里的，这里面有没有治表证的药呢？葛根的
作用既然是把津液往上送的，人体运行的规律，主上亦主表，主下亦主里，所以葛根重用也
能解表。葛根性平微凉，尤其适用于热证的解表。

这个方子在阴阳上也可以理解为降浊火升清阳，再加建中。所以这个方子不仅仅是治腹泻这
么简单的，真正理解了会有无穷的妙用，以后专门讲临证的时候再来谈。

今天讲得有点多，耽误大家到这么晚。下次我稍微控制点时间。今天就到这了， 谢谢大家。

== 2014-06-14（35-36）

大家晚上好。

=== 答疑

今天还是回答大家的疑问，再讲《伤寒论》的条文。今天我看大家在讨论一个医案，就是30
年贫血那个。贫血了30年，吃了无数补血的药，没有好。结果吃苓桂术甘汤很有效果。这是
为什么？我们知道，苓桂术甘汤里的茯苓，桂枝、白术都是发散清解药，并没有滋补药。

之所以能治血虚，就是我之前课里说的那个道理，靠补血药去补血就是缘木求鱼。只有人体
的循环恢复了，人体自己补血才能补血。苓桂术甘汤里的药是整个生化中焦津液，去中焦湿
气的，人体运行恢复了，自然血就生了。这才是真正传统中医的观念。

我再解释一下，我前几天网诊的那个医案。就是柴胡用90克那个，应该大家有印象。那个病
没有面诊，是填的问诊单。局面比较复杂，首先有太阳温病反应，高烧；又有忽冷忽热的半
表半里证反应，患者平时爱酒肉，口臭舌腻。这个局面应该是比较复杂的，又没有摸脉，尤
其之难。其实我们只要学会了六经辨证，事实上都能化难为易。首先太阳、少阳、阳明皆有。
阳明是有腹泻，刚忘了说了。那三阳并病是什么，治从少阳。所以以柴胡汤为主方。我用的
是大柴胡。因为温病发热严重，而腹泻不严重，所以大黄易为石膏，150克。患者的口臭舌
腻，肠胃里有积滞，所以生姜换成藿香佩兰。经方也要变通使用。肠胃有积滞了，还去用生
姜健胃助火，是不行的。这个患者吃了两剂就全好了。中间还跟媳妇做了一次爱，其实感冒
做爱是会家中的 ，但也好了。很多人感兴趣为什么柴胡90，这么重的剂量。小柴胡汤原方
就是125克，我现在考虑药店的感受，也就下个40，50克。不过就是多吃几幅嘛,但这个患者
体重200斤，所以我还是开了90克。所以用药要灵活。这个方子就讲到这。

释然：“女性临近七七月经漰漏，是厥阴收敛有问题吧，同时脸红，潮热，出汗属于少阳证，
请问如何理顺这个人体的秩序?谢谢老师。”

经方-刘希彦

释然同学问的这个问题，事实上是更年期的问题，女人七七四十九岁是更年期，那更年期是
什么？女性每个月有月经，月经是主阴的，是阴血。到49岁时，女性的阴的层面急剧的减少，
于是月经就断了，就进入了生命另外一个周期，这个周期内不能够再生育了，那么在这个阴
的层面急剧减少的时候会发生什么情况呢?我们知道。万物里都包含一对阴阳的制约力，人
体亦然。当人体的阴急剧减少时，阳就会亢盛。于是在更年期所发生的就是烦燥，潮热等这
类的阳亢的证，这就是更年期的生理上的人体的原因。这个问题就说到这里。

九九骗骗：“老师您好，可不可以谈一下痛经的成因？”

经方-刘希彦

其实我们知道，痛经是哪里痛？是子宫痛吗？不是的。为什么，因为子宫里面没有神经。那
是哪里痛呢？其实当我们感到腹部痛时，是腹部里面的筋腱在痉挛在痛。那腹肌里面的筋腱
为什么会在痛呢？因为津液虚了，供养筋的津液不够了，这跟颈椎痛是一样的道理。为什么
津液会虚呢？因为人体在来月经的时候，要调动大量的津血能量去通月经，于是附近腹部的
这些筋它获得的津液相对就少了，于是就痛了。这个是痛经的原理。

经方-晴天师妹：怎么区分虚汗或不是虚汗？

经方-刘希彦

虚汗或不是虚汗最准确的分法不要从汗上面来分，要从你的身体是阴证，还是阳证上来分。
如果说你身体很虚，是阴证，你还在出汗，那它叫虚汗。如果说你是阳证出汗，那是正常的。
所谓的治病求其本，就是这个意思。所以说还是牵扯到怎么样区分阳证和阴证的问题，那这
就是一个大问题，我们在课里头一直在讲这个问题，所以我就先讲这么多。

平常心问头晕头痛是不是可以解释为到达头部的津液不够。这种情况是会头痛头晕。当人体
表不解，津液不能外达，因而造成上达于头部津液过多的时候，头也会痛，也会晕。当人体
有上热的时候，头也会痛也会晕，当津液不够时。所以这就需要辨证，这就需要用多个证来
指向一个结论。

比如，如果说我有头晕，同时还有心烦口苦，那是什么？那就是上热了。如果说头晕同时有
恶寒，怕冷，虚弱的这种反应，那就是津液不够，阴证了。这就是像破案一样，多个证指向
一个答案，才不会错，才是《伤寒论》严谨的治病流程。

好的，今天的答疑就先到这里，十五分钟后进入《伤寒论》条文的学习。

=== 条文讲解

35、太阳病，头痛发热，身疼，腰痛，骨节疼痛，恶风，无汗而喘者，麻黄汤主之。

麻黄汤方

麻黄三两（去节，味甘温） 桂技二两（去皮，味辛热） 甘草一两（炙，味甘平） 杏
仁七十个（汤去皮尖，味辛温）

右四味，以水九升，先煮麻黄，减二升，去上沫，内诸药，煮取二升半，去滓，温服八
合，复取微似汗，不须啜粥，余如桂枝法将息。

在太阳病里，中风是津液虚的证，已经汗出了，治疗要以救津液为主；伤寒是表紧无汗的，
津液还没有耗散，治疗以解表为主。麻黄汤就是典型的解表剂。先来看证。“头痛发热”不用
解释了，前面已经说过了，这是表证的典型症状。“身疼腰痛，骨节疼痛。”这是因为表紧津
液不得出，所以囤积在肌体里面造成疼痛。当然寒气进入肌骨造成局部瘀堵也会疼痛。“恶
风”是典型津液虚的证，这里可能是传抄错误，此条有恶风不通。“无汗而喘”，因为津液往
上走，又不能汗出，肺的压力很大，只能通过喘来缓解。麻黄这个药我们说过，是宣通毛孔
的，它本身没有能量，所以它合桂枝这样的能量剂才能发汗。桂枝是作用于肌肉的，将肌肉
里的水湿往外逼，麻黄打开毛孔，协同作用以致汗出。我们知道，麻黄合石膏能治温病，这
里石膏也是能量剂，一种寒降的能量，石膏将热降下去，麻黄打开毛孔，所以温病服了也能
汗出而解。杏仁既能宣散又能下气，宣散助麻黄发表，兼下气则能平喘。杏仁因为其药性比
较驳杂，所以在《伤寒》里一般都不做主药，只是配合使用。这里杏仁七十个，大约二十几
克吧，古时候的杏仁都比较小。炙甘草这里只用一两，量很轻，可见津液不怎么虚。少量的
甘草，也可以理解为是发汗后的善后之药。

说一个麻黄汤的医案。

有一个老人夜里常尿炕，用现在的中医理念，自然是从肾论治，结果吃了无数补肾收敛药都
不见效。后来遇某医给开了剂麻黄汤，一剂而愈了。这其中的原理用后世的五行辨证体系是
没办法解释的，发汗药跟遗尿有什么关系？用六经辨证却不难解释：人吃进去饮食，通过中
焦气化作用变成能量送出体表，不能完全气化的能量则代谢为废水，通过肾和膀胱排出体外。
如果肌表的气化作用弱了，意味着大量的能量会代谢为废水，加重膀胱的压力，于是容易遗
尿。

麻黄汤里麻黄和桂枝的组合无非是加强体表的气化功能，所以也就能减少膀胱和肾的压力，
也就能治遗尿。有人会问，患者若有肾虚怎么办？我们不能只看肾虚这个结论，要问为什么
肾虚？肾脏的代谢压力减轻了，肾脏自己就能补回来，自然就不虚了；当然，佐以适量的补
肾药也许会有些帮助，但要适度，滋腻药多了，妨碍了气化功能，就适得其反了。

这个医案很好的阐释了如何用人体表里循环的观念治病。表里循环是大循环，其力量大，是
人体运行的主流；相比而言，脏腑五行生克的循环是小循环，其力量小。后世的医生用五行
生克理论断为脾克肾，光是去健脾补肾，这治的就是小循环，从小处着眼，必将为大所制，
自然久治不愈。

有人说《伤寒论》的方子擅长治外感病，不擅长治内伤病。从这个医案亦可看出这个说法是
不客观的。既然我们治的是人体而不是疾病，何来内病外病这一说？所谓辨证施治，辨的是
证在外还是在内，而不是病在外还是在内。这是传统中医和后世中医主要区别点之一。有一
本民间偏方的书上载了一个治老人遗尿的偏方，说用白芷泡酒服用有神效。民间偏方之所以
称之为偏方，是因为用常规的中医理念解释不了，却又很有效验。天下事本为一理，你的中
医理论果真正确的话，就应该能解释一切有效验的方子，如果解释不了，只能说明这套理论
有问题。

如果我们参透了《伤寒》的辨证思路，这个偏方是可以解释的：白芷是辛散的，是解表气化
剂；酒也是解表气化剂。这个偏方说白了和麻黄汤的作用相类似而已。

下次课，我们会讲柴胡汤。柴胡汤是临证运用最广泛的方子，没有之一。

36、太阳与阳明合病，喘而胸满者，不可下，宜麻黄汤主之。

2014年6月14日

== 2014-06-21（37）

大家晚上好。刚才看群主说是第十二次课了，不知不觉和大家在一起三个月了。时间过得真
快。今天我看已经有八百多个人，看来大道不孤，真正的传统中医还是大有希望的。

今天讲小柴胡汤。通观古今经方大家的医案，柴胡类方剂可谓是使用频率最高的。不仅经方
家喜欢用，时方家也喜欢用。还有人说，学《伤寒论》学会两个方剂，一个桂枝汤，一个柴
胡汤，也就学会了伤寒之法。可见此方之重要。所以今天不答疑了，我将以整堂课的时间来
系统的讲解这个方子。下次课再来讲解医案和答疑。下面进入伤寒论的学习。

37、太阳病，十日已去，脉浮细而嗜卧者，外已解也。设胸满肋痛者，与小柴胡汤。脉但浮
者，与麻黄汤。

这是第37条。

小柴胡汤方

柴胡 半斤 黄芩 三两 人参 三两 半夏 半升（洗） 甘草（炙） 生姜各三两（切） 大枣
十二枚（擘）

这一条讲小柴胡汤。这个方子很重要，可以说是治病的时候用途最广泛的一个方子。为什么
呢？因为它是治半表半里的阳性病，也就是少阳病的主方。半表半里涵盖的是除表与里之外
的广大区域，三焦系统和大部分脏腑都在这个区域，各种疑难杂症也大多在这个区域。

为什么疑难杂症多在半表半里？因为表病相对来讲没那么复杂，万病若能出表都是好事。偶
尔长湿疹长皮肤病是好的，说明病出表了，毒素出来了，里面就无事了。长疮长疔更好，我
记得小时候很多人都会长疮，尤其是春夏之交的时候。现在长疮的少了，生癌的就多了。

是不是跟抗生素有关系？很难讲，先不说化学毒素的伤害和沉积，吃过西药片的都知道，抗
生素是很苦的，用中医的角度来看都是苦寒的东西；大量的水输入身体也会造成阴寒，因为
水是阴性的。所以西医治疗往往会让人体陷入阴证。

阴证有个特点，就是很少发烧和疼痛，病人自体感觉没那么难受。病入了里，身体里面没有
神经，当然没那么难受。很多人输了液觉得舒服些了，其实是阳证治成了阴证。当时舒服些，
随后又会造成别的疾病，所以现在长期依赖医院的病人特别多，疑难杂症和恶疾也特别多。

为什么病会从表进入半表半里呢？根源在脾胃。《伤寒论》是以脾胃为中轴来看待人体的。
脾胃好比车轮的轴心，其它的地方好比车辐，车辐是围绕车轴运转的。当脾胃弱了之后，津
液能量化生不够了，无力将病邪排出于体表，病邪就会入内。如果在半表半里这个区间僵持
住了，就产生了半表半里证。

先把整个条文解释一下，再来详细讲小柴胡汤。

为什么说“脉浮细而嗜卧”是“外已解也”？我们前面说过，脉浮紧是表不解，汗不得出。如今
是脉浮而细，说明体表通畅了，邪气已经开始解了，所以脉不紧绷着了。为什么脉细呢，说
明气血也消耗了。

这时人就会产生“嗜卧”的反应，就是老想睡觉，这是人体为了生长气血产生的一种自我调节
反应。这种反应往往是在邪气解除之后才会有。当人体还有邪气的时候，哪怕疲乏也常常是
烦躁的，想睡也睡不着，因为肌体需要亢奋起来去攻邪。

我在临证上经常碰到这种情况，病人刚吃药的头几天会头晕，或嗜睡，有时还会有腹泻的反
应，

病人往往以为这是不好的反应，其实不是这样。如果没有给病人下泻药，甚至下的是一些所
谓的健脾止泻药，病人反而有腹泻的话，这是大好的反应，这是人体自己在排邪气排淤积。

《黄帝内经》里有一句话：“药不暝眩，厥疾弗疗。”暝眩就是眩晕反应，这句话的意思是说，
吃了药如果没有头晕反应的话，严重些的病是治不好的。我有病人刚吃一二剂药的时候头晕
得要扶墙，但病很快就好了。嗜睡、腹泻事实上也是暝眩的类似反应，原理是一样的，是人
体生长能量和排病邪的反应。

如果“脉但浮者”，就是脉只是浮，没有嗜睡反应，那病邪还没有完全去，还有表证。条文里
说的是与麻黄汤，古代用竹简刻字很费力，难免惜字如金，不能但凭一个脉浮就给麻黄汤。
还是要全面辨证，有充分的麻黄汤证才给麻黄汤。

“设胸满肋痛者，与小柴胡汤。”这个胸满肋痛是柴胡汤的四个主证之一。另三个主证是“往
来寒热”，“心烦喜呕”，“嘿嘿不欲饮食”。

要弄清这四个证的机理，就要详细解释一下人体的表里大循环。

在之前的课里我经常提到人体的大循环，那人体的大循环到底是什么呢？休息十五分后给大
家解答。

好，接着讲课。

学中医主要学观念，观念对了治病才有把握。今天也是借小柴胡汤继续深入讲解传统道家中
医对人体的理解。

对于人体的循环历来理论很多，五行生克，圆运动，三枢开合等等都是。下面讲的是我的人
体的大循环理解。

人体吃进去饮食，脾胃将其吸收气化为能量。气化的阳性热能以往上往外的走势向体表散发，
就像喷泉一样。人体气化出去的能量只能是一部分，没有完全喷射出去的水还要再回落下来，
从体表回归于三焦的网膜和淋巴系统，然后下行。

这些下行的有能量物质，也有代谢后的废水，能量物质在以肾为中心的下焦元气系统封存起
来，废水则是尿液通过膀胱排出去。肾封存的能量物质又能通过元气（类似于西医的肾上腺
气）的温煦作用，再次气化上行，成为小肠和脾胃以化食物的动能，也成为人体的应激能量，
再次形成气化循环。这就是人体的能量大循环。经络学里的说脾经胃经为里经，肾经膀胱经
为表经，也是基于这种循环来定义的。

半表半里证的实质是脾胃弱了，气化无力了，里外上下的循环痞塞不通，邪气便结于半表半
里这个中枢位置。

邪结于肋下和胸中这两个区域形成“胸满肋痛”。为什么在这两个区域呢？因为胸中是气化能
量出表的中间区域；肋下是回收能量下行的中间区域。胸中结滞则有胸满。肋下这个位置是
躯壳内的三焦系统离体表最近的地方，只隔着薄薄的一层肌肉，里面结滞住了，便会投射到
肋下的体表神经产生感知。

邪陷于半表半里，正邪在表里之间交争。当正气稍胜时，驱逐病邪往表走，人体便感觉发热；
反之，正气虚而病入里，人体便感觉发冷。这就是“往来寒热”的原理。

“心烦”是因为上焦有热。

人体正常的模式应该是下热上寒，也就是《易经》里的泰卦的格局，下阳上阴。为什么要这
样呢？因为下面为阳，阳主上行；上面为阴，阴主下行，便形成了上下交通，此所谓阴阳交
泰。气化物质由下往上升，升的过程中渐渐冷却后，凝结为有形物质往下降，回归下焦；下
焦通过元气的作用再次将有形物质转换为无形能量上行。这是用阴阳的运行来理解人体的大
循环。

当因脾胃虚而痞塞不通的时候，人体上部的能量不能下行，于是郁积而生热，便为心烦；人
体下部得不到回收能量的补给，便会变冷，于是形成了上热下寒、上阳下阴的局面，也就是
《易经》里的痞卦，上阳下阴，阳更上，阴更下，于是阴阳就离绝了。此为少阳证里面蕴含
的易理。

当因脾胃虚而痞塞不通的时候，人体上部的能量不能下行，于是郁积而生热，便为心烦；人
体下部得不到回收能量的补给，便会变冷，于是形成了上热下寒、上阳下阴的局面，也就是
《易经》里的痞卦，上阳下阴，阳更上，阴更下，于是阴阳就离绝了。此为少阳证里面蕴含
的易理。

喜呕”，胃弱了，不能接纳食物。

“嘿嘿不欲饮食”也是此理。“嘿嘿”二字的含义历来有很多解释，有说头晕的；也有说是胃里
不舒服的呻吟声。这都对，都是少阳证常见的反应。

此为柴胡四证。在临证上只要四证具其一，便可作为少阳证来治，都会有比较理想的治疗效
果，不必悉具。

现在来说小柴胡汤的方义。

这个方子只有七味药，建中的参姜草枣占了四味，可见少阳病的根源是脾胃虚。柴胡是疏通
剂，疏通半表半里之结滞。半夏是降逆的，降的是水。黄芩是苦寒的，降的是火。

先建中，再以柴胡疏通表里，夏芩降之，生姜升之，循环便得以恢复。为什么没有干姜附子
这些能温下寒的药呢？因为少阳证是以上热为主的，下寒并不明显，只需循环恢复了，能量
归于下焦，下焦自然就热起来了。半表半里的阴病厥阴病会用到干姜附子。

小柴胡汤运用是非常广泛的。在古今的医案中，小柴胡汤几乎可以用于治疗一切急慢性疾病。
我个人用它治过的病也数不胜数，涵盖诸如妇科儿科、肿瘤瘰疬、消化肝胆、无名炎症、血
压血糖、哮喘皮肤等所有类别的疾病。因柴胡汤运用之广，据说江湖上还出现了一个“柴胡
派”，治病专开柴胡类方剂。

柴胡汤之所以运用广泛，首先是因为半表半里所主的区域太大；其次，当三阳并病的时候，
是治从少阳的。意思是，当同时具有太阳证、阳明证和少阳证的时候，只要治少阳就都可以
治愈，这又大大的增加了柴胡类方剂的使用频率。

现在从药物上来讲小柴胡汤。

七味药当中的脾四味是后世医家认为不治病的药。现在医生的方子里很少有甘草大枣了，用
一点甘草还说是“和百药”，说不起什么实质作用。柴胡、半夏、黄芩也不是什么特别的“治
病”的药，只是普通的常用药。为什么这么普通的几味常用药组成的方子却可以治好这么多
的疾病呢？这就有力的证明了药物是不治病的，药物治的是人体的秩序。小柴胡汤正因为能
平衡一种很常见的人体失衡的局面，所以才得以运用无穷，治好那么多的病。

柴胡这味药历来误解很多，最主要的就是说它升提，很多后世的医生因此不敢用它。

少阳病的四个主证，心烦也好，胸满也好，呕吐也好，头晕也好，包括兼证口苦、咽干、目
眩，哪个不是上逆的的症状？为什么吃了都能好呢？

先且不说柴胡是不是真的升提，本身上逆的证是人体通过向上的趋势来驱邪，顺势而为就应
该升提来解决。《伤寒论》里所谓病在上从上解，病在下从下解；病在表从表解，病在里从
里解，说的就是这个顺势而为的大原则。惧怕柴胡升提实质上就是一种对抗人体，而非顺应
人体的治病思维。

柴胡这味药，香气清淡平和，煎的时候很难闻到，尝的时候才有。这种香气没有白术之厚，
没有桂枝之散，没有白芷花椒之辛扬，而是平正冲和，不偏不倚，所以疏通的是半表半里。

柴胡还略微兼有一些辛凉气和苦味。辛凉则能透表；苦则能通下，所以柴胡兼能疏通表里上
下。经方里作为主药的药，都有其不可替代的属性，柴胡所禀的中庸之性便是。柴胡算不上
升提，要说升提，姜桂芷椒荆防都比它升提得多。

如此平和的一味药，既非香烈，且有微苦，何来升提之说？何来耗肝阴之说？如果用柴胡都
怕升提耗阴的话，芷椒荆防怎么办？南方人天天吃辣椒吃火锅怎么办？我曾见过一个老大夫
开方子，白芷、藿香、黄芩、苦参这样峻烈的药一开就是二十来克，柴胡开个三五克却还小
心翼翼，实在不可理解。正是这些谬论耽误了中医这么多年。

今天内容有点多，不过算是把半表半里证系统了讲了一下。现在六经只有厥阴病没有讲了，
其实你们会越来越发现，《伤寒》体系内容不多，也不复杂。

仲景之学是好学更好用的，大道甚夷而民好径，后世医学反而越学越繁难，这是我个人的体
会。

今天就讲到这里，谢谢大家。

2014年6月21日

== 2014-06-28（38-39）

刘希彦老师《伤寒论》讲课——周六晚八点于经方求真群第十三次

大家晚上好。

感谢大家三个多月来每周守在这里听我的课。我一直很惶恐怕教不好教不对，因为我们是分条语音和文字的方式上课，所以信息量和真实感肯定比不上面授。但大家这么不离不弃，让我实在感动。我也尽力想把更多的内容和信息量讲给大家。

上回我说到，咱们六经已讲了五经，只有厥阴没有涉及了。所以，我们现在可以讲一些临证上的东西了。

临证就是临床，我喜欢不临床这个词，因为我们中医不需要病人开刀住院吊水成天躺在病床上，古来也没有医院这个词。我喜欢叫临证，中医是找证据的，找人体到底出现什么问题的证据。

今天，我就开始结合医案教大家怎么找证据。

上一堂课讲了小柴胡汤。现在，我结合自己的几个医案讲讲小柴胡汤的应用。

我们知道柴胡四证，又知道四证具其一就是柴胡证。且三阳并病治从少阳。所以少阳柴胡证
的运用和治疗是比较简单的。如果，一个病就有四证之一，那就是照书生病了，讲起来也没意思，所以，我今天会讲几个相对不那个容易判断的医案。

2011、9

安母，女，中年

自述：肝硬化腹水11毫升

刻诊：左脉弦，右脉弦而略滑。容易打嗝，常年心烦，老觉得心里憋着，别的没有什么不适，
胃口睡眠亦好。平时觉得身体还可以，这次查出来有肝腹水，自己都觉得很意外。舌有齿痕。

我既然说是要讲小柴胡汤的医案，那就已经交底了，肯定是小柴胡汤为主方。那我们就来分
析一下为什么小柴胡汤是主方。

脉弦？不能凭脉断证，这是传统中医和后世中医最重要的区别之一。脉只是用来印证的。

这个病人比较麻烦，没有什么明显的证，我们临证常有这样的情况。

有时是病人自感正常，的确不明显。有的是病人迟钝，有却说不上来。

打嗝是胃弱，老觉得心里憋着，其实和胸肋苦满是类似反应，病人不可能照书生病，临证需
要变通的认识问题，所以可以定为少阳病。气郁明显，兼里湿，小柴胡加香附陈皮茯苓白术
泽泻。

需要说一下胃弱，我们学过，少阳病是胃弱引起的，所以有胃弱就要注意了。

现在说处方。

柴胡 20 黄芩 15 法夏 15 炙甘草 10 大枣 15 西洋参片 10 香附 30 陈皮25 茯苓 30 白
术 30 泽泻 20 生姜四片

现在说效果。

七剂后病人去检查，腹水不见了，距离上一次检查只有11天。检查的大夫是同一人，觉得不
可思议，疑心自己上一次看错了。病人自述多年的打嗝好了；多年前因为调动工作问题不如
意，老觉得心里有个结，吃了药之后觉得这个结好像打开了，心里舒畅了。

再讲一个感冒的病例。

某演员、男 ， 年龄， 32 体重：102公斤

发热39度多，浑身疼，忽冷忽热，

刻诊：头重脚轻，头热脚寒，胸闷，头晕，无汗，轻度腹泻，无食欲，舌苔黄厚腻，苦臭，
咽干，胸腹久按是感觉烫手，不觉得渴，但喜饮，冷热都喝，精神状态可，吸烟，有咽炎。

网诊无脉象，患者自述：脉象浅，无力，发虚，平常大概每分钟跳动87下。

平时情绪容易烦躁，唇口有一点干燥，睡眠多梦。

这个也是一堆感冒症状，至于是什么方证，桂枝？白虎？麻黄？其实都不太像。

局面再复杂，我们也要学会从中条缕分析，化繁为简。

表证有无汗头重；

里证有腹泻

是否有口苦，患者说不清楚，胸闷、咽干、无食欲，则是半表半里证胸肋苦满，不欲饮食的
范畴。

再说，头热脚寒符合少阳证上下不交通的机理。

三阳并病，治从少阳。

因为肠胃有积滞，选大柴胡。

腹泻不明显，胃中有热，大黄、生姜换成生石膏。舌苔厚腻口臭，胃中有腐浊，加藿香佩兰。

生石膏150，柴胡90，黄芩30，法夏30，枳实20，白芍20，大枣30，藿香20，佩兰20

只给了二剂，吃了就好了。

下面是我说一个群里头最近传的一个医案，也是因为不好辨证大家不太理解，我说一点自己
的理解。

不好意思，我不知道怎么操作上传，请管理员杏林风帮我传上来吧，

麻烦杏林风传一下。

张娃，男，8，高热39.0多，双侧痄腮3天，刻诊，手脚热，周身热，没有怕冷。头晕，头痛，
颈部不舒服，出汗，饮食差，精神差，腹痛，大便一次，稍干，小便3次，微黄，没有口干
口苦，饮水一般，面色稍红，两腮部，肿大，按之热，痛，舌红，苔白，脉浮数略滑，小柴
胡。

谢谢。

这个病例喝小柴胡汤很快就好了。首先也是没有明确的少阳证。据现有的证看更偏向于麻杏
石甘汤，或者白虎汤一点。为什么不是这两个方子呢？注意这两个证“饮食差”，“精神差”。
这就有胃弱了，辨证要求其本，所以这个热是胃弱的虚热。小柴胡汤是治胃弱虚热的。石膏
下去，胃就更寒更虚了。所以还是小柴胡更合适一点。这是我个人的一点浅见。

今天的病例就分析到这里。十五分钟后进入《伤寒论》条文学习。

大家好。

其实今天我在这里讲真正的传统中医，对后世中医做一些批判和修正，事实上已经是在树敌
了。因为真正的传统中医千分之一都不到，后世中医何其之多。所以我做好被歪曲被抹黑的
打算。曾经有体制内的专家悲观的说，中国真正的传统中医可能只有几百人。

只是我十年前学医的时候听到的话，到了今天让我欣慰的是，今天我们这个群里学传统中医
的就有几百人了。所以，我觉得这一切做得都很值得。

闲话少说，进入《伤寒论》

今天讲一个很重要的方子：大青龙汤。

38、太阳中风，脉浮紧，发热恶寒，身疼痛，不汗出而烦躁者，大青龙汤主之。若脉微弱，
汗出恶风者，不可服之，服之则厥逆，筋惕肉瞤，此为逆也。

这是第38条

麻黄 六两（去节） 桂枝 二两（去皮） 甘草 二两（炙） 杏仁 四十枚（去皮尖） 生姜
三两（切） 大枣 十枚（擘） 石膏 如鸡子大（碎）

古人竹简刻字不易，行文太简，以致于文字中处处有玄机。此条说“太阳中风”，紧接着讲的
却都是伤寒的证：“脉浮紧”，“发热恶寒”，“身疼痛”，“不汗出”。

这是为什么呢？从后面所出的大青龙汤这个方子里是可以找到答案。

大青龙汤这个方子很有意思，它事实上是以治伤寒的麻黄汤为底方，炙甘草加倍，然后又加
上了生姜、大枣和生石膏。

倍甘草加姜枣这说明有津液虚。中风证的实质不在于有汗无汗，在于津液虚。但为什么条文
中没有出津液虚的证呢？因为开头已经说是“太阳中风”了，也就等于说有津液虚的证，只是
略去了。

这就是《伤寒论》的行文方式。这种行文方式会让读不惯古书的现代人不知所云，望而生畏。
没办法，我们要学医要攻古籍就得习惯这个。

有伤寒麻黄汤证的“不汗出”，又有中风桂枝汤证的津液虚，自然是麻黄汤加姜枣来解表并建
中生津液。

后面多出了一个证——“烦躁”。烦躁是轻微的里热，没有到真正的热证那种汗出而喘和大烦渴
的地步。这是津液虚的烦躁，也是人体的自我调节机制，用所谓上火的方式亢奋起来，加强
津液的运行和化生。既然有烦躁，就加了一点生石膏去标热。石膏用得不多，鸡子大，古时
候鸡蛋小，应该也就是个几十克而已。

综合来看，此方证其实就是三个方面：表不解，津液虚，有轻微里热。

其实我们就算不学大青龙这个方子，熟悉了张仲景的组方规律，自己也可以组出此方来：表
不解麻黄汤；津液虚是姜草枣芍，因为要发汗去掉白芍；有微热加生石膏。组出来就是大青
龙汤。

这个方子还有个值得注意的地方，就是麻黄的剂量是六两，也就是90克，而石膏的用量却很
轻。因为此时的里热主要是毛孔不开郁在里面了，而不是真的有多热，所以石膏的用量是较
轻的，而重用麻黄打开毛孔。有人评价《伤寒论》的方子活泼灵变且丝丝入扣，从剂量的变
化尤其能体现出来。

后面说“若脉微弱，汗出恶风者，不可服之”。

如果已经脉微汗出，就不能服用大青龙汤，毕竟大青龙汤是发汗剂，若再发汗的话，势必更
亡津液。就会有“厥逆”，就是四肢冰冷，四逆证了；还会有“筋惕肉瞤”，筋脉和肉都会有瞤
动不灵活的反应，这也是津液大虚的反应。这就是所谓的逆治了。

大青龙这个方子，除了外感病外，很多头部的疾患都有机会用到它，比如鼻五官疾患、颅内
疾患、癫痫羊角风之类神经科疾患，包括治现代医学所谓的“中风”，也就是高血压中风也可
以用到。

治中风瘫痪的古方的续命汤也是这个方子的变化方，加了一些去瘀血的药而已。

这是因为头部疾患常常是因为表不解，湿邪火邪不能出表，上冲于头而造成的。大青龙的方
义就是建中解表，再用生石膏清降头部之邪气。

我们中医就是这样整体的看待人体的。所谓千古神方续命汤，懂得了人体的大循环，解释起
来也很简单。

今天就先讲到这里了，谢谢大家。请大家随意讨论。

== 2014-07-06（40）

大家好。首先我要感谢群主和管理员。群越来越大了，管理的事物很多。可能大家看不到他
们在做什么，其实，我们这个群这么秩序井然，学习氛围好，没有乱七八糟的东西，都是管
理的结果。我一星期只来上一次课，而他们每时每刻都要管理，而他们做的这一切都是无偿
的，所以感谢，感恩。

现在进入讲课，先答疑后讲《伤寒论》条文。

问：“1.四逆汤方中只有干姜温里甘草补液，为什么不加大枣、人参？特别是没加人参，个
人认为四逆汤证一定也有胃气衰弱的问题，但是又不加人参以复胃气，是不是因为人参效力
缓，而四逆汤证又急又险，不适合用人参？人参(包括脾四味)和干姜的本质区别在哪里呢？
望老师解疑。”

答:为什么四逆汤里没有人参？”我记得我以前的课提过人参这味药的作用。它是亢奋阴的，
“阴”是有形物质。我对人参的这种认识和大多数医家不一样，我有自己的见解。因为很多医
家认为人参是补气的，后世医家所说的“气”这个概念比较含糊，我不太欣赏。气是阳性物质，
事实上人参是亢奋阴的，阴证是有形物质，就是人的津液、血液。人参这味药能刺激胃生津
液。阳性物质是有热能的，那是姜附，人参和姜附能是一回事吗？

在《伤寒论》里，我这种说法有两个基本点来证明它：

第一，如果人参是热性药，是滋补药，为什么白虎汤证有大烦渴的时候要加人参？这说明人
参可以用于热证，实热证。

第二，在《伤寒论》里，“四逆汤”为什么没有人参？因为人参亢奋的是阴的层面，而四逆汤
证本身就是一个太阴证，属阴，所以它不用人参。

后世的药性众说纷云，一会儿是归经学，一会儿是补气，一会儿又是补阴，又或者是其它，
总之比较乱。这样会让中医陷入一种无法可循，无据可依的地步。

问：“那有水湿痰饮是不是用人参要小心？”

答:没错，水湿痰饮证用人参要小心，所以说你没有看过一个去湿的方子里有人参。去湿的
方子里不会有人参的。

以前的课老师说了一个治病原则：三阳病先表后里，三阴病先里后表。可是，太阳和少阳并
病，光解表会不会有问题，因为少阳病不可发汗。是不是可以理解成在一个方子里一边解表
一边治里，也是遵循了三阳病先表后里的原则呢？

说一下六经治病顺序的问题。我们说过，“三阳证”先表后里；“三阴证”先里后表。那三阳并
病呢？就是三阳证同时有呢？是治从少阳。若是只有太阳证和少阳证呢？这种情况下是并治。
就会有柴胡桂枝干姜汤和柴胡桂枝各半汤这样的方子。我再清晰的把它重复一遍，就是《伤
寒论》里一般来讲的原则。“三阳证”先表后里，“三阴证”先里后表，三阳并病治服少阳，太
阳少阳合并则并治，还有少阳和阳明并治方大柴胡。这样说就清楚了。

先不休息，下面接着讲《伤寒论》。今天讲的也是一个很重要的方子，小青龙汤。

40、伤寒表不解，心下有水气，干呕发热而咳，或渴、或利、或噎、或小便不利，少腹满，
或喘者，小青龙汤主之。麻黄（去节） 芍药 细辛 干姜 甘草（炙） 桂枝（去皮）各三两
五味子 半升 半夏（洗） 半升

这一条一上来就已经给出了结论，证属伤寒，“表不解”，同时“心下有水气”，心下是指中焦
这个区域。简单说就是外寒内饮。那这个结论是怎么得出来的呢？下面就是“证”，也就是证
据。首先是“干呕发热而咳”。干呕发热是常见的表证；咳嗽是小青龙汤的主证。下面的证前
面都加了个“或”字，说明或许有，或许没有。“或渴”。前面说过中焦有水气，也就是有湿症
会渴。有湿症为什么还会渴呢？湿气囤积于中焦不气化，等于就是废水，没有被吸收利用，
人体的粘膜组织得不到津液的滋润所以会渴。热证也会渴，阴虚阳亢也会渴，但临证上最多
见的渴是有湿症的渴。所以治病不能一见到渴就用麦冬生地滋阴，滋阴只适用于阴虚阳亢症。
“或利”。表不能解邪气的时候，人体就会寻求别的出口来解决邪气。肠道是最方便的出口，
所以感冒病人常常会腹泻。如果有湿气的话，更有可能发生腹泻。“或噎”。吃东西会噎住，
食道里不润滑，也是因为湿证造成的上部津液缺乏。“或小便不利，少腹满”。人体是一个整
体的大循环，当中焦不气化不运行的时候，小便的下行能力也会变弱，水湿也会囤于下焦，
所以“少腹满”。“或喘”。表气不通会喘；有湿气也会喘。为什么有湿气会喘呢？我们看有没
有湿气经常会看舌头，舌头胖大有齿痕就是有湿气，说明湿气会让人的肌体组织浮肿，自然
人体内部也是浮肿的，浮肿会让体内的空间变得狭小，肺的压力就会增大，就要用喘来释放
压力。有湿气的时候气短气紧，不能平卧，也是这个道理。先将到这里，休息十五分钟，再
接着讲小青龙。

刚才大家在讨论四逆加人参汤的问题，说得都很好。我说四逆汤里没有人参，是想说明张仲
景不会用人参去救阳。事实上人参是寒热不禁的，四逆汤里加人参也能加速津液的生成。

好，接着讲小青龙。为什么上面这些证都加了个“或”字呢？因为咳喘也好，渴也好，下利也
好，小便不利也好，腹满也好，这些证状不止湿气会出现，别的原因也会出现。所以我们需
要多条证来共同得出一个结论。比方说，同时有渴，又有小便不利，那这个渴就应该是湿证
的渴了。这就是《伤寒论》的辨证方法，跟破案一样，需要多条证据指向一个答案，最后再
印证于脉。这样的得出的结论才能保证准确。

现在说说这个方子的组成。麻黄和桂枝是解表的；干姜和甘草是建中温阳的；半夏是降水之
逆，也能化痰。这几味组合在一起既能解决表证，也能解决湿证。中气有了，气化也就有了；
气化有了，小便也就有了。前面说过，这两个功能本来就是一体的大循环。用芍药是因为有
腹证，芍药的苦降能泻腹部之实，有下行之性，是治腹痛腹满证的主药。苦泻下行当然也是
有助于利水的，所以利水的方剂里也能用它。细辛这味药，药如其名，有细而辛烈的香气，
是疏通孔窍的。在这里是疏通肺窍，起到宣散止咳的作用。《神农本草经》上说它“主咳逆、
头痛、脑动、百节拘挛、风湿痹痛、死肌。久服明目，利九窍，轻身长年。”这段话有两个
信息，一是说明细辛的香窜疏通之性无所不至；二是说明这个药是可以久服的，且能轻身长
年，不是后世说的“过钱有危险”。五味子主要是酸的，有收敛的作用。为什么要用这味药，
需要从人体的大循环来解释：所谓“一阴一阳之谓道”，人体的功能是有吸就有呼，有散就有
敛，就像宇宙一样，永远是对立统一的二元双向力的。比方说，我们说肝主疏泄，是说肝以
疏泄为主，事实上肝也有收敛的功能，也要敛肝血，不可能只是疏泄。整个人体的收敛功能
是下焦元气所主，也可以说是肾所主。人体代谢剩余的精气自上焦下行，交由肾来封存和再
利用。咳嗽等于是人体一次次强行的宣肺和解表，这是很消耗元气的。此方中多数是宣散气
化剂，也是耗散的。耗散多了，则越发不能收敛，于是我们需要增强收敛功能，收敛足够的
元气，才能更好的宣散以驱邪，就像我们要蹲得深才能跳得高一样。所以我们需要五味子来
增强元气的收敛作用，才能更好的宣散和止咳。在经方里，只要是以咳嗽为主证的方子都会
用到五味子这味药。后世说五味子补肾，我认为五味子在小青龙汤里所主的未必是这个作用，
因为补肾要有补肾的方证，诸如有尿多腰疼之类方证才需补，用药不能不讲依据；再者，补
肾有补肾的方法，借个后世医家的说法，肾阳虚是要用姜附的，肾阴虚才用五味子这样的酸
敛药，用药不能不讲法度。小青龙有寒饮，要补也是补肾阳，不可能再去补肾阴以助湿邪。
后世为了自圆其说，说五味子酸敛且燥湿，酸敛之物如何能燥湿呢，最多也就是不那么滋腻
而已。所以这样的说法是很难成立的。要说酸为涌泄，能引水下行，倒还有几分道理。

小青龙汤治疗咳嗽很常用，用对了往往有一剂知二剂已的效果。这是因为咳嗽的时候外寒内
饮这种局面很常见。

总结一下，大青龙汤是治外寒内有标热的；小青龙汤是治外寒内有寒饮的。

好，今天的课就讲到这里，谢谢大家，请大家随意讨论。

再答个疑吧。咳喘是为什么？人体为什么要咳喘，说明人体在排邪气，不是肾虚，很多咳喘
的肾脉并没有虚。人体既然要喘，为什么要去平它呢？应该建中逐邪让其自平。后世一见咳
喘就镇咳纳气平喘，不顺势而为，而是对抗人体。结果怎样？落下了“咳嗽难治”“中医不治
喘，治喘要丢脸”这样的话，不得不深思。

== 2014-07-13（46-50）

刘希彦老师7月13日讲课

大家晚上好。

上课之前我想问大家一个问题:为什么张仲景的这套体系会成为几千年来临证效果最好，最
受推崇的一套体系？

我的理解是:张仲景体系的特色是，他讲的是实实在在的人体运行。在他的语言系统里，没
有五运六气，没有天地玄机，没有虚着解释人体。而是病位如何？津液如何？人体反应如何？
都是实实在在的。五运六气要不要懂？要的。天地运行要不要学，也要的。经络五行要不要
参，也是要的。可这些都不是临证的根本。临证的根本是人体。

后世研究的伤寒也好，后世别的体系也好，都有一个问题，喜欢走虚的，喜欢在外围打转，
究其实对人体的运行却解释不清楚。

张仲景是没有讲人体的运行，因为他们是竹简时代，如果再讲人体的运行，就不是几万字的
伤寒论，就是几十万字的伤寒论了，用竹简如何能传播呢？这就要靠大家去参方证后面的人
体运行。可惜后世的研究都不顺着仲景的思路走，都是借仲景炫耀自己上知天文下知地理中
知经络脏腑。医学复杂了，临证效果却越来越差。所以我这次来讲伤寒论，就是以仲景之法
为法，在仲景的基础上，破解仲景条文后的人体运行规律。

言归正传，现在开始《伤寒论》讲解。

46、太阳病，脉浮紧，无汗，发热，身疼痛，八九日不解，表证仍在，此当发其汗。服药已
微除，其人发烦目瞑，剧者必衄，衄乃解。所以然者，阳气重故也。麻黄汤主之。

这一条前面讲的是无汗身痛的太阳病，也就是伤寒麻黄汤证。服了药，稍微好一点了，病人
有些“发烦目瞑”。目瞑是一种类似于眩晕困乏的反应。前面说过，邪气重的时候，人是亢盛，
就是累也不能睡。服药后产生困倦反应，说明邪气快解了。严重的会出鼻血，出了鼻血病就
好了，这是为什么呢？因为“阳气重故也”。这里的阳气指的是津血，就是津血多。人体津血
多自然病解得快。如果体表不够通畅，不能迅速的通过体表解决邪气，津血就会寻求的别的
途径解决，出鼻血就是一种常见的方式。小孩子爱出鼻血其实是好事，一场感冒就躲过去了。

就这一条我们来讲讲出血这个证。像牙龈出血、便血、经期血淋漓不尽，这都是很常见的。
如果我们顺应人体来思考，其实都是人体在排邪气。包括大便颜色深，就是有潜血，也是如
此。

我奶奶年轻的时候，得一个病几年不愈，百药不效。有一天晚上，她忽然拉黑色的大便，据
她说拉了半马桶，病从此就好了。所以我们不能见血止血，而要去考虑人体到底哪个层面有
邪气。如果顺应人体来思考，我们还可以更宽泛的理解这个问题。不单出血，慢性腹泻，慢
性鼻炎，人体有异常分泌物，甚至频繁遗精，都有可能是人体在体表不能解决邪气的情况下
寻求的其它途径。所以《伤寒》里治遗精给出的方子是桂枝加龙骨牡蛎汤和小建中汤，这两
个都是治太阳表证的桂枝汤的加减变化方。条文中出鼻血给出的方子是麻黄汤。麻黄汤是驱
邪气出表的，邪气从表解了，就不必用出鼻血来解了，鼻血自然也就不出了。这是顺应人体
的辨证思路。

后世的医家是不敢这样用药的，他们认为桂枝是活血的，麻黄是发散，是出血证的大忌。他
们一见到出血就是凉血止血，用生地丹皮茅根鹤草之类。如果是阴虚阳亢这些药还能奏效，
如果是别的情况吃了是不会好的。比如经血淋漓不尽这个证，我早年也袭用凉血止血的套路，
仅治好过一例，其余的都失败了。《伤寒》里治血证的方剂，桂枝茯苓丸、桃核承气汤、温
经汤都用桂枝，而且桃核承气汤还有里热证的。历代伤寒名家的临证效果证明这些方子治血
证反而有捷效。我个人治出血证，用干姜桂枝的时候比用生地茅根的时候多。

跟大家分享一个我治出血症的医案:张某，男，青年。自述：痔疮出血疼痛，出血量很大，
走路都受影响。刻诊：便秘干结，胃有些返流，大腿根部酸痛，腰酸痛。脉不稳定，时而亢
躁，时而缓弱。平时食肉多，运动少。

处方：柴胡 30 白芍 30 黄芩 15 法夏 15 枳实 15 酒大黄 10 厚朴 20 大枣30 炙甘草 25
干姜 20 吴茱萸 20 桂枝 20 当归 20 四剂

效果：四剂内出血即止；便秘基本缓解；大腿根部疼痛减轻；痔疮还会痛；小便时微有涩痛
感。

为什么会这么开方？大家可以讨论下，休息十五分钟后再接着来讲。

好，接着讲课。

刚才那个医案，大家讲的都很好。我说说我自己的认知吧。

辨证：患者提供的症状不多。里证有便秘；表证有腰酸腿根部酸。半表半里证却不明显。脉
时而亢燥时而缓弱，或可理解如疟状，病在进退之间，类似于往来寒热，邪实津虚；胃返流
类似于呕，况且半表半里证是胃弱邪入引起的；大腿根部内两侧疼痛，为肝胆经。综合来看
可以视为有半表半里证。且失血而脉弱，又有痔疮肿痛便秘，寒热夹杂，情况复杂。三阳并
病，治从少阳。便秘痔疮严重，用大柴胡加减。这就是真正的传统中医思路，不是看痔疮看
出血，而是看邪气在哪里，津液盛衰如何，循环秩序如何。后世的医家总是喜欢搞出些这样
的理论，出血要禁干姜桂枝，感冒要禁什么什么药？这都是以病论病，忽略人体整体,头痛
医头脚痛医脚。痔疮出血这么严重，我用的都是些热药发药活血药，是因为在我的眼中没有
病，只有人体。这样才能治病。

此病人的二诊处方：

柴胡 30 白芍 30 黄芩 15 法夏 15 枳实 15 酒大黄 10 熟大黄 5 厚朴 20 大枣20 炙甘草
25 干姜 20 吴茱萸 20 肉桂 20 当归 20 滑石 20（包煎） 四剂

效果：患者服完后告诉我痔疮基本好了，小便涩痛也消失。

今天再讲一条伤寒论吧。

50、脉浮紧者，法当身疼痛，宜以汗解之；假令尺中迟者，不可发汗。何以知然？以荣气不
足，血少故也。

脉浮紧，身疼痛的，本当以汗解。如果尺脉迟，就不可发汗，因为尺脉迟是荣气不足，血少
的表现。这一条虽短，却体现了三个原则：

第一，津液虚不可发汗；

第二，判断津血之多少，也就是阴阳问题，脉象比较准确，《伤寒》里碰到阴阳问题往往会
有脉象的描述；

第三，判断津血之多少，尺脉比较准确。

所谓寸脉主上主表主阳，尺脉主下主里主阴，这也是顺应人体运行的很客观的理解方式，因
为人体的气化过程是从里从脾胃开始的，气化的阳性能量向上向表走；剩余能量再从表回落，
转换成阴性的有形物质向下向里回到肾，完成这样的一个大循环。所以，脉的运行和人体的
循环方式是可以互证的。

真正的中医不仅辨证不能故弄玄虚，辨脉也不能故弄玄虚，必须在人体里找到实实在在的依
据。后世的脉学玄虚的名词多，虽然那些玄虚的东西说得也有道理，但不能只谈玄虚的概念，
那就犯了空想，以玄说玄的错误，还是必须弄清楚人体里面实实在在是什么。这也是仲景体
系和后世体系不同的地方。判断津血之多少，不但尺脉，沉取也是很准确的，沉取无力而虚
则是阴，因为浮为阳为表，沉为阴为里。迟脉是脉来迟缓的意思，表示血气不足，运行无力。
“荣气”这个概念，接下来会有专门的解释。

好，今天就讲到这里，谢谢大家。

== 2014-07-19（53-63）

大家晚上好。现在天气这么炎热，耽误大家乘凉的时间了。今天先答疑，后讲伤寒论。

问：“请老师具体讲下“实证”“虚证”。”

答：关于实证和虚证，现在也是后世的医家搞得越来越乱。都不知道什么是“实”什么是“虚”。
好像所谓的阳证的都是实证，所谓阴证的都是虚证。不对，这个概念是不准确的。实就是里
面堵住了，虚就是里面空虚，是物理概念。打比方，“承气汤证”，肠子里有东西堵住了，热
性的便秘，这叫实证。那如果说里面有寒的东西，也在这里面结住了，这叫寒实，就是说阴
寒凝结。当我们有寒实证的时候，腹部里面也会痛，它就是有寒的东西结在那里了，这也叫
实证。于是我们有个方子叫附子，细辛和大黄，就是泻这个寒食的。附子是温养的，大黄是
泻。所以说这就是实。虚也是一样。不实则为虚，空虚之意。有虚寒，也有虚热。

这个是虚实的鉴别，有时我自己也会说错，因为有时候习惯嘴上不严谨，但是你心里必须得
清晰什么是虚什么是实，所以当你读到一些真正的古书古籍时，读像《伤寒论》这种严谨的
教材时，你就知道他在讲什么，不能搞错。

问：平时调理身体吃什么？那些保健品有没有用？

答：调理身体最好的是少思虑，多运动。我对很多人说过，都表示很难做到，尤其是前一个。
所以大家还是喜欢问保健品的事，这个简单易行。关于保健品我说两个观念：

第一：对于西药的保健品一定要慎重，现在连维生素C都被认为对人体有副作用，遑论其它。
我有朋友的小孩因偷食维生素C当糖吃，患上了白癜风。第二：不要追求昂贵的中药保健品。
昂贵是因为稀有，不是因为有用。且昂贵更容易招致作假。凭古人的智慧，最有用的东西都
普遍种植了的，比如脾四味里的大枣、生姜。我们知道，《伤寒论》的原则人体是以中轴脾
胃为中心的，治病首先考虑的是建中，也就是说脾胃无差，人则无病。日常养生健脾胃就好
了。那健脾胃用什么？我们都知道参姜草枣。但有个问题，这四味或甜补或辛辣，偏性还是
很强的，毕竟是药，用不对反倒不好。于是我们还有个调理脾胃的方子：八珍糕。

八珍糕里面主要是食材，基本配方是扁豆、山药、薏苡仁、莲子、芡实、苓术之类。这个很
温和，也很安全，以前的人用这些再加点白米，这种的很安全，当主食吃都可以。我尤其建
议老人和孩子常用这个。我家里有时候也会备一点。需要注意的是，如果长期服用，不要去
药店买，药店的药材都是硫磺熏过的，这是潜规则了。长期服用毕竟不好。群里的瑶琴是做
无硫药材的，她很有经验，关于药材的事情有时候我也经常请教她，她曾经建议我买八珍糕
的原粉，而不是那个做好的糕，这样没有添加剂，也不会作假，冲服也好，自己蒸也好，或
兑入面粉里做馒头用，就当是杂粮馒头，都很方便，给小孩做辅食不错，这个事可以咨询一
下她。

好，答疑就到这，接着讲课。

53、病常自汗出者，此为荣气和，荣气和者，外不谐，以卫气不共荣气谐和故尔，以荣行脉
中，卫行脉外，复发其汗，荣卫和则愈，宜桂枝汤。

54、病人脏无他病，时发热自汗出而不愈者，此卫气不和也，先其时发汗则愈，宜桂枝汤。

此二条讲的是经常自汗出，也就是出虚汗的情况，宜用桂枝汤来治疗。自汗出用桂枝汤是前
面讲过的，只是新增加了两个概念——荣和卫。荣，也称之为营，简单来讲就是指血管之内的
血液；卫指行于血管之外的津液和气化的能量。血液通过毛细血管渗出行于脉外，也就成了
津液。所谓血汗同源就是这个意思。《伤寒》里只有这么几条谈到荣卫的概念，这些不像是
仲景的行文习惯，疑为后人所加。因为照仲景的习惯，是不会搞很多复杂的名词概念的。他
一般只是笼统的称之为“津液”，或者“血”，甚至通称为“阳”。因为强行将血管之内和血管之
外的津血区分开来，临证上也不现实。比如，当我们一汗出，脉立刻就缓和了，说明血管内
外本为一体，很难截然的割裂开来。

这一条里说，荣气和则卫不和，又说自汗出是因为荣和卫不协和。为什么荣气和就会卫不和
呢？为什么不协和就自汗出呢？又是为什么会不协和呢？有的人出虚汗出好多年，难道是一
直协和不了吗？有说桂枝汤能治荣卫不和的自汗出，是因为桂枝走卫气，白芍敛荣气。我试
验过，这种情况不用白芍，单用桂枝也能治好。这又是为什么？——都是本糊涂账。后世的中
医喜欢制造很多概念，事实上纸上谈兵的多，落实到人体上却经不起推敲，反而制造混乱和
曲解。按照仲景的观念，人要有表证才会自汗出。这就有一个问题，如果经常自汗出，难道
是经常有表证吗？这是有可能的。风寒暑湿燥，人体无时无刻不在感受外界的邪气。如果我
们脾胃功能好，津液充足，表里通畅，邪气随时随地的被我们解决掉了，我们也觉察不到。
反之，如果津液的能量不够，邪气总解决不掉，人体的自保模式就总要调集津液去解决，这
就成了出虚汗。诸如出虚汗，手足烦热，颈肩腰腿的酸痛，经常脑袋昏沉，都是慢性的外感
病反应。我们平时所谓的感冒只是急性的外感病反应。慢性也好，急性也好，只要是桂枝汤
方证，就可用桂枝汤。桂枝汤里姜草枣芍是建中气敛津液的，桂枝是增加气化能量，解外驱
邪的。如此一合力，自然邪气去虚汗自止。当然，如果津液不太虚，单用一味桂枝解外，津
液也就自己回来了，也能治好。

61、下之后，复发汗，昼日烦躁不得眠，夜而安静，不呕，不渴，无表证，脉沉微，身无大
热者，干姜附子汤主之。

干姜附子汤方

干姜 一两 附子 一枚（生用，去皮，破八片）

先下后汗，亡了津液，陷入阴证，这时出现一种新情况：白天烦躁不能眠卧，晚上安静。前
面讲柴胡汤的时候说过，若中轴脾胃虚了，津液气化之力弱了，人的大循环受到限制，就会
产生上下不交通的现象，于是上热下寒，也就是上下的阴阳不顺接。这里讲的是津液更虚，
里外阴阳严重不顺接的情况。里外阴阳不能互相制约，白天行阳气就过于烦躁，晚上行阴气
就过于安静。那为什么不用柴胡类方剂来治疗呢？看后面，“不呕”，说明无半表半里证；
“不渴”说明也不是热证；“无表证”，那就是里证了；“脉沉微”是里阴证；“身无大热”说明热
只是表象。通过层层排除，最后锁定为里阴证。而柴胡类方剂是治半表半里证的，所以不能
用。

这是比较难的辨证，必须了解整个六经病的特点，通过综合分析比对，才能得出准确的结论。
我经常提醒初学者，在把整个六经学完之前不要给人看病，因为临证错综复杂，不能全面分
析的话就容易出错。

这个方子很简单，就两味药，生附子和干姜。若再加一味炙甘草就是四逆汤了。为什么不用
炙甘草呢？因为甘以缓之，甜的东西有缓和之性，这里要取生附子的通行之力来打通里外阴
阳，所以不用炙甘草。

63、发汗后，不可更行桂枝汤，汗出而喘，无大热者，可与麻黄杏仁甘草石膏汤。

麻黄杏仁甘草石膏汤方

麻黄 四两（去节） 杏仁 五十个（去皮尖） 甘草 二两（炙） 石膏 半斤（碎，绵裹）

一般来讲，发汗后如果外感病没好，是要用桂枝汤的。也有不可用的情况，热证就是其中一
种。怎么知道是热证呢？比如有怕热、大烦、大渴索饮，表里俱热。这个方子也治热证，却
没有上述这些明显的证状，那怎么知道是热证的呢？因为有“汗出而喘”。一般外感病，气血
往上走，表气又不通，肺就会喘；如今汗出了，表气通了，肺还在喘，说明是肺里有热，要
通过喘来排除热量。只有“汗出而喘”，没有其它热证的反应，说明热证较轻微。这个方子就
是麻黄汤换了一味药，将桂枝换成了石膏。所治便从偏寒的表证变成了偏热的表证。这个方
子在肺炎发高烧的时候使用机会很多，尤其是小儿肺炎，因为小孩阳气旺，又容易积食，一
般热性肺炎较多。据说非典的后期，中医出来力挽狂澜，治愈了很多，这个方子就是主方。

好，今天就讲到这里，谢谢大家。

== 2014-07-26（64-67）

太阳病中篇就是方子多。《伤寒论》里主方多数在这一章里会讲到。 今天就要讲几个临证
上非常常用的方子。 在接下来的一些条文里，我们还会讲到临证上很常见的水饮证，也可
以叫湿证，它和淤血证一样都是临证很常见的。

64、发汗过多，其人叉手自冒心，心下悸欲得按者，桂枝甘草汤主之。

桂枝甘草汤方

桂枝 四两（去皮） 甘草（炙） 二两

发汗过多，津液耗散了，津血同源，血也就不足了。心脏带血带不上来，于是就会剧烈跳动
以加速带血。这就发生了“其人叉手自冒心”的现象，也就是心脏突突的，自己都能感觉到，
恨不得要用手按住。 “心下悸”这个证以前说过。如果有表证，人体的自然机能，气血会往
体表去驱邪。若津血不足，气血往上走的能量不够，于是就会发生悸动的现象，就像车爬坡
时候的的反应一样，这是人体自己在努力。 这个病情看上去严重，但方子极简单，就是桂
枝和炙甘草。炙甘草建中补津液，桂枝解外兼增加上行之气化能量。津液有了，表证去了，
上行能量加强了，自然也就不心悸了。 对于这个方子，历代的名家有各种解释。 黄元御用
五运六气说来解释，说是木郁而风动，所以悸。那木郁又是因为土败，所以用桂枝疏肝木，
炙甘草建中培脾土。 五行脏腑辨证体系的名家来解释，心跳心悸是肾克心，或理解为肾中
有陈寒，造成肾中寒水上冲。那肾不好又是因为脾土克肾水。于是辨为脾克肾，说桂枝温肾
阳，炙甘草健脾且缓脾之过盛，则不能克肾。 那到底谁是对的呢？其实这都是以玄说玄。
木郁怎么会风动呢？肝主疏泄主生发，肝郁了，应该更不会动才是啊。寒性沉潜趋下，肾中
有寒又怎么会上冲呢？这些都是为了附会玄学而臆想出来的，而不是对人体运行机理的客观
理解，这也就造成了后世辨证和用药上的混乱。仲景的高明之处，就是他对人体的表达是实
实在在的生理机能和运行，而不只是停留在玄学层面。 心下悸或心悸这两个证很常见，说
到底就是津液不足，不能顺畅的完成气化运行而造成的。 津液不足的原因有很多，这一条
是发汗过多造成的单纯津液不足。中焦湿气囤积，也会造成津液不足，因为水湿不气化造成
的津液不足。可以在这个方子的基础上加两味去中焦湿气的药，茯苓白术，这就成了后面要
学的苓桂术甘汤，这是治中焦湿气的主方。 还有因为津血久亏造成心下悸的，这就要用炙
甘草汤了。炙甘草汤还是桂枝甘草为主药，加姜参枣温阳建中，再佐以地黄阿胶之类滋阴药
补津血。还有因为下焦淤血造成努耗津血于下，津血上行无力的，这时候可以用桂枝甘草汤
合去瘀血的方剂。 桂枝甘草汤及其变化方在心脏病上使用的机会很多。诸如早搏、房颤之
类，只要是心脏运行不良的疾病，病机主要是上述几种，用对了就会有立竿见影的效果。

65、发汗后，其人脐下悸者，欲做奔豚，茯苓桂枝甘草大枣汤主之。

茯苓桂枝甘草大枣汤方

茯苓 半斤 桂枝 四两（去皮） 甘草 二两（炙） 大枣 十五枚（擘）

上面说过，湿气囤积中焦不能气化，而心下悸，是苓桂术甘汤。这一条是脐下悸，是湿气囤
积在下焦不能气化。这个时候会发生一种叫“奔豚”的症状。《金匮要略》里这样解释奔豚：
“气从少腹上冲胸咽，发作欲死。”感觉有气从腹部上冲，这是人体在发动能量，想将囤积的
水湿气化上去。能量不够，不能走表完成水液大 循环，只能上冲胸咽。这个发作起来很难
受。 这个方子和苓桂术甘汤只差一味药，就是去白术加大枣。 很多人解这个方子喜欢从苍
术和大枣入手去分析。其实奥妙是在茯苓。我们知道，人体的原则，病在上从上解，病在下
从下解。水湿在中焦可以气化上行为主，在下焦则要以往下利水为主了。这里是“脐下悸”，
水湿在下焦，于是去了气化中焦的白术，而将利水的茯苓加倍。这里的茯苓用半斤，约等于
125克；而苓桂术甘汤的茯苓只有四两，也就是一半的剂量。 插一句，苍术和白术古人是不
分的。 为什么加大枣？大枣是补津液的。如果水湿气化往上，等于有化生成津液被利用的
可能；如果水湿往下利，那就只能作为废水排出去了，于是多加一味大枣补津液。

66、发汗后，腹胀满者，厚朴生姜半夏甘草人参汤主之。

厚朴 半斤（炙，去皮） 生姜 半斤（切） 半夏 半升（洗） 甘草 二两（炙） 人参 一两

“腹胀满”，脾胃虚常有这个证，腹中不运化了。 主药是厚朴，下气除满的，用半斤。再合
半升半夏，半夏是降逆的，主要是降上焦的水的，那和腹满有什么关系呢？《伤寒论》思考
人体是一个整体，上下表里的运行是一体的。有时候是因为上面不降了，下面才堵住。所以
厚朴常和半夏同用；厚朴也常和枳实同用，枳实是除胸满的。 本方是治脾胃虚寒的引起的
腹满，驱寒的生姜用的也重，半斤。炙甘草和人参用得少，二两和一两。临证上，如果津液
不是很虚，甘草可以少用，人参可以不用。如果寒不重，生姜也可以减少。 现在因为生活
习惯不好，脾胃虚寒的人多。脾胃虚表现为腹胀的很普遍，所以这个方子现在使用机会很多。

67、伤寒若吐、若下后，心下逆满，气上冲胸，起则头眩，脉沉紧，发汗则动经，身为振振
摇者，茯苓桂枝白术甘草汤主之。

茯苓桂枝白术甘草汤方

茯苓 四两 桂枝 三两（去皮） 白术、甘草（炙）各二两

这个方子在临证上运用极其广泛，是使用频率最高的方子之一。这是治中焦水饮的主方。多
数治水饮的方子也是由它变化而来。 “心下逆满”。水饮囤积中焦则有心下满；气化上行不
能顺畅，人体就会有心下“逆”的感觉。 “气上冲胸”。这是类似于奔豚的反应，虽然不是起
自脐下，原理是一样：水湿不能顺畅气化上行，到胸部就阻塞住了，就会有气上冲胸之感。
“起则头眩”。蹲下站起来头就晕，严重的甚至什么都看不见，要扶墙。人体是一个整体，当
我们说脾胃有水湿的时候，不是说水湿仅仅在脾胃，而是以中焦脾胃居多。事实上有湿证的
时候全身哪里都会有水湿，比方说脸会肿，舌头会胖大，小肚子也比平时明显等等，自然大
脑里面也会有水湿。大脑水湿多，就会头昏不清醒；水湿多则血就相对少，蹲下一站起来，
大脑供血不上则眩晕。 “脉沉紧”。脉沉，邪气在里；紧主寒，亦主束缚而不通畅。这是湿
证有可能出现的脉象。但脉象这个东西不是绝对的，有时候中焦湿气未必就现这个脉象，临
证上缓脉弦脉浮脉也很多。 “发汗则动经，身为振振摇”。肌肉里面也会有水湿，一发汗便
会激动，水湿便在体表经络里窜行，身体便会“振振摇”。 方中的几味药都是之前学过的。
先说炙甘草。水湿去掉之后，脾胃会空虚，用适量的炙甘草能建中补津液。如果让脾胃虚着，
水湿就有可能还会再次囤积。 我们现在的炙甘草是蜜炙的，很甜腻。《伤寒》里的炙甘草
并没有说明是蜜炙的，有研究说《伤寒》里的炙甘草事实上就是直接炒或炙的，并不加蜜。
我赞同这个说法。几个祛饮的方子都有炙甘草，而且用量不轻，如果蜜炙的话，恐有助湿之
弊，因为湿证饮证是里面有水湿阻滞，还是属于偏实证的范畴。当然，如果是虚证，是可以
用蜜炙甘草的，比如小建中汤。 现在中医的炮制方法很乱，我和夏正安最近也在恢复一些
传统的炮制方法，希望能对中医的临证效果有所帮助。 相比桂枝，白术香气温厚，气化的
是中焦区域，擅长化中焦脾胃的水饮。 茯苓将不能气化的水饮从下焦水道通利出去。 桂枝
的气化之力是往肌肉走的，走的是大循环。桂枝的用量比白术还多，为什么呢？因为《伤寒
论》的思路注重整体，注重人体的大循环。人体的能量气化出表，剩余的才能代谢为尿液排
出体外，这是一体的运行。就像蒸笼的原理，水蒸气上不去，也就没有凝结的水珠滴下来，
只是一团不运行的水在锅子里面。 桂枝这味药在经方里似乎是无所不能的，是出现频率最
高的药之一，表证用它，里证用它；水湿痰饮淤血用它；虚实寒热也都能用它。这当然不能
理解为桂枝通治百病。经方的治病思路治的不是病，治的是人体的秩序和循环。桂枝是走体
表大循环的，只要需要走外的力量，需要建立从脾胃到肌肉的大循环，桂枝就都能用上。

== 2014-08-03（71-74）

我们这个群就要破一千人了。我感到很高兴，因为真正的传统中医能团聚这么多人。可大家
是不是真的用传统的思维方式在思考中医呢？我知道很多人都觉得后世有后世的道理，博采
众长总是没有错的。我说点个人的体会吧。我学中医分两个阶段，前半个阶段学后世，后世
很好学，比较简单。后半个阶段学仲景学伤寒，比较难学。可是我在后世中医那里学了那么
多年，纠结痛苦了那么多，疗效真的一般，看好一个病高兴好久。等到我学经方学伤寒，论
疗效真是一个天上一个地下。不但是我，古今很多先贤大医家都有想同的体会。后世的有些
方子有些药物还是可取的。但如果你在大的思维方式上，在辨证体系上，在对人体的理解上，
不是真正传统的，那学医的道路就太难了，就是后世说的，三代也未必出一个名医。这个名
医还指的是有一些经验，在有限的一些病上有那么些经验。而学经方学伤寒，胡希恕先生说
过，三年期满，皆能行道救人。而且是全科医生，不是只能治某些病。以我的经验，我的学
生里，用功的，天分高的，半年就行道救人的也有。这群里有很多经方高手，我恳请你们也
出来分享分享医案和经历，带带后学者，为真正的中医正名。这是功德无量的大好事。

好，闲话少说，进入《伤寒论》的学习。

这两堂课学的是去饮的方子。这套方子很重要。临证上极为常用。为什么呢？因为现在的人
食肥甘而少运动，所谓饮证湿证多。今天学的这个方子很重要，五苓散。

71、太阳病，发汗后，大汗出，胃中干，烦躁不得眠，欲得饮水者，少少与饮之，令胃气和
则愈。若脉浮，小便不利，微热消渴者，五苓散主之。五苓散方

猪苓 十八铢（去皮） 泽泻 一两六铢 白术 十八铢 茯苓 十八铢 桂枝 半两（去皮）

这一条讲了两种渴证。一种是大汗出后胃中干的渴，这种渴只要喝点水就好了。要少喝，因
为很渴的时候不要喝太多，容易伤脾胃，很饿时候也一样，所以“少少与饮之，令胃气和则
愈”。中医讲人体都讲个适度。反观医院里面，只要一进去，不管大人和小孩，一天往身体
里吊好几瓶水，且不管吊的是什么，这个方式本身就是很有问题的。另一种渴是胃里有湿气
的渴。有湿气为什么还会渴？因为水湿囤积不气化，也就供应不到身体的各个部分，自然就
会渴。这种渴是更常见的。在临证上因为缺水的渴其实很少，因为渴了我们自然就会喝水，
所以多数的渴是水湿囤积。现在的医生一见渴证就用麦冬生地滋阴，反助其湿，这是不对的。

这个问题讲了很多遍了，还会反复讲，因为中医大法则就这么几条，《伤寒论》本身也在反
复强调这些东西。可见今之弊古也有之。五苓散的方证，后面还有更详细的讲解，这一条讲
的是“脉浮，小便不利，微热消渴。”脉浮和微热是有表证，有表证用桂枝。很多人会问，那
没有表证是不是就可以不用桂枝呢？不能这么理解。因为水湿的气化是往体表气化的，桂枝
是走体表大循环的，不用桂枝如何能气化水湿？再说，对于表证不能这么狭隘的去理解，不
是发烧体痛有感冒症状才是有表证。我们前面说过，人体其实有很多慢性的表证，比如颈肩
痛、腰痛、肌肉酸、浮肿、头痛头晕、汗出异常、烦热，诸如此类都是。很多人对经方里很
多方子都有桂枝不理解，其实表证的体现形式远比我们想象的宽泛。五苓散的主证是“消渴”。
消渴就是总想喝水，喝了又渴，也就是说胃里头虽有饮，却不寒，还有点微热，如果胃里头
寒的话，是渴而不欲饮的。胃里头微热，说明气化能力还不太差，所以这个方子相比苓桂术
甘汤，桂枝用得少，只有半两；白术用得也少，只有十八铢。茯苓和白术等量。关键是另加
了两味偏寒的淡渗药：泽泻和猪苓。泽泻和猪苓的性味是淡而咸寒的。淡说明没有粘稠物质，
所以下渗；咸也是下行的，能走肾开水道。这两味药微寒，所以适合微热的湿证。猪苓比泽
泻更偏寒些，作用也更偏下。后面有个治下焦湿热的方子猪苓汤，就是以猪苓为主药的。在
五苓散里，泽泻的用量最大，近两倍于其它药的剂量。五苓散的方义是重用向下淡渗利水的
药，轻用气化药。也就是说这种水湿囤积是以水湿不下行为主的。水湿下行了，等于是北窗
开了，南风也就进来了，无须重用桂枝，表气也就能通了。所以说，方药就是个能量场，这
个能量场只要和人体匹配，能帮助人体回归正常循环，病自然就会好。

我曾经用五苓散为主方治好过一例黄斑病。黄斑病号称眼部癌症，是眼球后部黄斑区的一种
病变。病人先是找的北京协和医院的眼科，号称中国最权威的眼科。协和的专家说这个病是
治不好的，就算花十几万手术了，很快就会复发。我用五苓散为主方治疗一个星期，病灶就
缩小了；治疗一个月病灶就消失了。现在好几年了，没有再复发。当时这个病人在脉证上主
要反应为中焦有湿气，脉弦缓，身重乏力，却又口渴想喝水。他是一个演员，爱漂亮，听信
了美容专家的话，要多喝水，于是不渴也喝。五苓散里没有一味药是所谓专门治眼睛的。为
什么能治好这个病呢？说明药不是用来治病的，是用来协调人体的，而治病的是人体自己；
同时也说明中医无绝症，因为真正的传统中医是开免疫力这把锁的，只要人体免疫力能抵抗
的病，中医都能治。既然癌症有自愈的，艾滋病也有终生携带不发病的，那么理论上癌症艾
滋病传统中医都能治，而且用这些简单的经方就可以。黄斑病事实上是黄斑区积液，因为患
病位置多以成为所谓的绝症。积液无非水饮而已，用中医祛湿的办法，其实很好治。有人觉
得中医能治艾滋病是天方夜谭，其实不然，大多数病毒感染类疾病，比如肝炎、疱疹，一旦
得了，病毒都是终生携带，所谓的治愈就是携带而不发病。如果以此为标准，艾滋病当然也
是可以治愈的。

好，大家先休息一下。

继续讲课。

73、伤寒，汗出而渴者，五苓散主之；不渴者，茯苓甘草汤主之。

茯苓甘草汤方

茯苓 二两 桂枝 二两（去皮） 甘草 一两（炙） 生姜 三两（切）

之前我们学了两个祛中焦湿气的方子：苓桂术甘汤、五苓散。现在再学一个茯苓甘草汤。怎
么区分这三个方子呢？主要是从“渴”这个证上来区分。有渴的是五苓散。以微寒的泽泻猪苓
为主，泽泻用量最大。不渴的是茯苓甘草汤。不渴说明胃里面有寒，以生姜为主，生姜用量
最大。之前学过的苓桂术甘汤没有提及渴与不渴，说明在寒热问题上居中，所以既没有泽泻
猪苓，也没有生姜，只是重用茯苓桂枝，行散利水而已。我们学经方难就难的搞清楚每样药
和方证的关系；更难的是搞清楚每样药和人体的关系。但只要搞清楚了，我们就能像张仲景
那样灵活的加减变化。

74、中风发热，六七日不解而烦，有表里证，渴欲饮水，水入则吐者，名曰水逆，五苓散主
之。

前面我们讲了，五苓散的主证是“消渴”；这里讲了五苓散的另一个主证，“水逆”，也就是喝
水下去会吐出来。人体有水饮湿气，又有热，就会很想喝水，只是水喝下去胃接受不了，于
是要吐出来。有时候人胃口特别好，吃下去又胃胀不消化，也是这个道理，说明胃里有宿食
积滞，且偏热性反应。这里说“有表里证”，里证指的是有里饮。表证明显也是引起水逆的原
因。有表证的话，津液就会往上往表走，人体本身就是上逆模式，自然也容易将不能接纳的
水通过呕吐的方式走上焦排出体外。前段时间，有一个八十多的老人找我治疗，已经垂危，
喝水就吐，水谷不入。西医诊断为皮革胃，疑为胃癌。顾名思义，胃皮革化了，不接纳饮食
了，西医说没有办法。这个病名很吓人，西医的本事就是制造病名，却不能治病。因为病人
在外地，岁数又太大，不方便来面诊，于是用网诊的方式填了个问诊单。我就是用五苓散为
主方治疗的。家属告诉我说吃了几剂药明显有改善，喝水吐的情况缓解了，胃的烧灼感也没
有了。所以我们做中医不要被西医的病名吓到。至此，几个重要的祛湿的方子就讲完了。回
顾一下，主要是苓桂术甘汤、五苓散和茯苓甘草汤。这几个主要是去中焦水饮的，何为水饮，
就是有形的水。如果是无形的湿气，苔白腻，胃饱闷，后世常用的一些芳香药，如果藿香、
佩兰、白寇、砂仁更合用。

好，今天就讲到这里，谢谢大家。

== 2014-08-09（76-78）

今天先答疑，然后讲伤寒论。

医案：有位江西的朋友，大老远来济南调理身体。先在某医处调理了几个月，无明显效果，
某医倒也直率，请这位朋友另请高明。

这个江西朋友的一个亲戚在济南，也见过吴老师，便推荐他去找吴老师试试。这个情况
是两个胳膊干燥脱皮，而且痒的严重，已有多年，看其部位，重点在双臂阳明大肠经。诊其
脉，则右寸独大，两尺微弱。吴老师问他有无腰痛，双腿无力等表现，他点头称是。

后来吴老师告诉我，这是很典型的阳明不降，然而阳明不降的根源在于两尺微弱，肺脉
独大，则肺部有热，肺气不降，自然引起阳明之不降。而以前治疗方案皆是以麻黄连翘赤小
豆之类，自然难效。

吴老师依旧处以养肺阴降气之方，以天冬、黄芩、熟地、肉苁蓉、怀牛膝、当归、白芍
调理之。

四天后，该朋友前来，询问之下，得知，双臂阳明部位吃了第一付药就不再痒了，而且
干燥脱皮的现象消失，只剩下皮肤还有点暗红，与第一次来时干燥起白皮相比，已然不可同
日而语。而且服药后腰部没有再痛。

普通之医，见皮肤问题，总喜欢调以发表，然此等脉象，明是肾阴虚引起的阳明不降，再以
发表处之，自然无效，而养阴以降上焦之气，宛如去其郁堵，则上焦之气自然顺降，不调皮
肤而皮肤自调。

希望老师能从表里循环层面来来解说这个病例。

这是后世中医的思路和方法，我说过，六经体系的辨证思路是可以统后世的方法的，只有有
疗效的方子应该都可以用统一的辨证思路来解释。下面我就来解释一下。

伤寒论》的原则是表里原则，病在表从表解，病在里从里解。这个病人是两个胳膊脱皮，所
以理所应当从表解，于是第一个医生就用了治表的方式来治疗，就是典型的麻黄连翘赤小豆
这一类的方子，可是没有治好，第二个医生用清热和滋阴的方法，他的方子主要有三类药：
滋阴药，清热药，然后是下行药（牛膝 白芍），大家来思考一下，为什么用滋阴清热下行
的药就治好了呢？首先我们看，这个病的症状是：两寸的脉大，尺脉无。尺脉无说明津血虚
少，寸脉大，说明有热，阴虚而有热，很明显这是虚热症状。我曾经讲过，只要是虚证，就
首先要补津液，补津液的话，如果说胃是寒的，没有生化能力，那就要用生姜草枣“脾四味”
来补；如果说胃有生化能力，而这个人体的主要矛盾是阴虚阳亢，这种情况则可以直接用滋
阴药来补，这其实也是一种补津液。说到底，我们讲桂枝汤的姜草枣也好，还是此方的滋阴
药也好，他们都是一种补津液的方法。所以这个方子里用滋阴药还是津液原则，这不脱离
《伤寒》的原则，《伤寒》最大的原则就是阴阳，津血的盛衰是阴阳的指标。任何的治疗必
须以津血盛衰为第一位，也就是人体自身的功能和免疫力。六经里分阴阳也是以津液盛衰来
分的。这个病并没有明显太阳表证，比如汗出，体痛，低烧之类，而是以阴虚阳亢，上盛下
虚（腰腿无力），津液失调为主要矛盾，所以用滋养阴液平衡阴阳的方式就能治好。所以用
六经的思路是可以统一切方和一切病的。 我们治病是需要抓大方向的，当这个人体的局面
是以阴虚阳亢为主要矛盾的时候我们用滋阴药把津液补足了，人体津液有了，自然就能解决
表症。其实《伤寒论》里也有很多方子，并不是直接去治病。我们之前提到过的小柴胡便是，
小柴胡只是调达上下，而调达上下先要建中，建中参姜草枣四味用齐，整个小柴胡才七味药，
事实上就是补津液。并没有拿哪一味药针对某一种病，但是，却非常有效，病就好了。所以
我们之前说过，真正好的辨证体系，是可以统摄其余辨证体系的，甚至说是可以解偏方的，
所以我们用六经的方式解也一样可以解释清楚。

可是为什么很多人很排斥后世的滋阴派，甚至排斥一些用滋阴药治病的医生呢？因为后世的
滋阴派所缺少的是一个完整理解人体的辨证体系，尤其不讲究表里病位，他们只管阴虚阳虚，
容易滥用滋阴药，很多症状都一概而论为阴虚，为阳虚；阳虚便用人参黄芪，阴虚用生地麦
冬。我们知道，人参黄芪生地麦冬这些都属于阴柔的药，附子姜才属于阳性的药。所以滋阴
药不一定不治病，滋阴派的问题在于他们缺少了一个整体表里阴阳的概念，也没有一个人体
辨证能够行之有效的概念，而是完全依赖于滋阴药。

九九骗骗：“老师我有个问题，温病是不是太阳病。温病不恶寒，好像不符合太阳病的提纲，
恶寒，头项强痛，脉浮。”

九九骗骗问温病是不是太阳病？这个问题也问得很好，你要说温病不是太阳病它也有一点表
证，要说它是太阳病它又有里热证，那这是为什么呢？其实在临证，表证也好，里证也好，
它不是那么的清晰的。我们学六经只是学一个归纳方法。打比方，就像我们去临摹一个画像，
我们要在上面摆个几宫格，然后一格一格的去临摹它。我们也是一样，六经就是六格，用来
看清人体，像温病这样的病，你要说它是阳明证，阳明这个区域指的是胃和肠这个“里”，它
胃和肠也没有太热，也没有实证，实证就是里面堵住，便秘热结。那你要说它是表证太阳证
的话，它又多一点里热反应，事实上这是偏向于热性的表里兼有的病。那最典型的就是麻杏
石甘汤这个方子所主的病。它没那么的怕热，也没那么的“里”。当然，也有“里”的温病，所
以我们要以一种客观的方式来看待人体，而不要局限于去追究到底是什么。人体他就是一个
客观存在，他就是有的时候不是那么的绝对的。六经只是一个坐标，并不是所有的病都在正
坐标点上，有的偏左有的偏右，兼而有之是很正常的。

在下半堂课我们要讲《伤寒》条文里的栀子豉汤，我先将条文贴上来大家预习一下。

76、发汗后，水药不得入口为逆，若更发汗，必吐下不止。发汗吐下后，虚烦不得眠，若剧
者，必反覆颠倒，心中懊侬（竖心旁加个农字），栀子豉汤主之；若少气者，栀子甘草豉汤
主之；若呕者，栀子生姜豉汤主之。

栀子豉汤方

栀子 十四个（擘） 香豉 四合（绵裹）

上二味，以水四升，先煮栀子得二升半，内豉，煮取一升半，去滓，分为二服，温进一服，
得吐者，止后服。

栀子甘草豉汤方

栀子 十四个（擘） 甘草 二两（炙） 香豉 四合（绵裹）

上三味，以水四升，先煮栀子、甘草取二升半，内豉，煮取一升半，去滓，分二服，温进一
服，得吐者，止后服。

栀子生姜豉汤方

栀子 十四个（擘） 生姜 五两（切） 香豉 四合（绵裹）

上三味，以水四升，先煮栀子、生姜取二升半，内豉，煮取一升半，去滓，分二服，温进一
服，得吐者，止后服。

77、发汗、若下之，而烦热，胸中滞者，栀子豉汤主之。

78、伤寒五六日，大下之后，身热不去，心中结痛者，未欲解也，栀子豉汤主之。

好，先休息十五分钟，再接着上课。

发汗后，胃弱了不接纳，所以水药不得入口，入口即呕，此为逆证。要是再发汗，胃更弱了，
大肠也不吸收了，于是会腹泻不止。在发汗和吐下之后，会发生“虚烦不得眠”的情况，为什
么呢？因为人体如果津血虚了，首先会烦躁，这是人体在亢奋起来加速津血的生成和运行；
津血更虚的话，人体出于自保，是不会进入深睡眠的，深睡眠时血的循环极慢，各脏器，尤
其是大脑容易因缺血而受损。这就是为什么血虚的人都容易失眠多梦，白天则疲倦，想午睡
一会儿，躺下却又睡不着的原因。

当然，栀子豉汤方证还没有虚到这么严重，只是“必反覆颠倒，心中懊侬”，指神魂不安，心
里老有事翻来覆去放不下，老是很郁烦，又说不出个所以然，这就是津虚的虚烦。“反覆颠
倒”这个证很形象，可以引申开来理解。比如有的人喜欢碎嘴，喜欢唠叨个没完；有的人遇
事喜欢思来想去，决断不下，在生理上都是属于血虚而烦的范畴。时下流行的一个词“纠结”
亦是这个，可见现在的人血虚而烦的居多。成天熬夜、打游戏、吃辣、喝酒，贪眼目口腹之
欲，消耗阴精，强调阳气，不虚烦才怪。

我总结所有关于栀子豉汤这个方子的条文，将其方证归纳为四句话：心中懊侬，虚烦不眠、
胸窒身热、心中结痛。从这四点可以看出，其所治为偏热的虚烦。我们知道阴虚阳亢是用生
地麦冬的，这里能不能用呢？不能。因为这里是以热为主虚为辅，生地麦冬这样的药物太滋
补了，属强壮剂，无异于火上浇油。那这种情况用什么补虚呢？用豆豉。

这里的豆豉与我们以前做菜用的霉豆豉是一类东西，做菜的时候放在油里一炸，很香。有香
味就有疏散之性，能发散上焦的热，后世医家解表常会用到它；又为豆类发酵而成，具和中
滋养之性，却不滋腻温补，在这里恰好合用。栀子豉汤的方证还有“胸窒身热，心中结痛”，
说明这个热是在胸中这个位置，也就是比表略深一点，又比里略浅一点的位置。这个方子治
食道的病变很有效果。食道是什区域？胃属里，食道连着胃，在胃的上面，主上亦主表，那
就比胃更偏一点表了，所以病位正合。

综上所述，这个方子所主的区域是里向表去的一个过渡区域，就是“胸中”，又略微区别于半
表半里证的“胸肋”。那这个区域的热用什么来解呢？栀子。栀子就是栀子花的果实，形状像
个小灯笼；其气微凉香，其味苦；凉而香则能往表走，苦则能往里走，两头都跨着一点，正
合这个区域。栀子后世说它利三焦湿热清心火。三焦、心，事实上也是在这个区域里的。所
以，我们说学六经辨证，六经只是坐标，我们要用六经这个坐标来灵活的客观的来看待人体。
有的人辨证非要弄清楚到底是少阳还是太阳，非此既彼，这就陷入了偏见和主观。有时候就
是少阳太阳都有一点，那用药上就兼顾，用柴胡桂枝各半汤。治病就是应该这样灵活圆融的。

下面说的是加减法。“若少气”，加炙甘草。炙甘草建中，中运自然气补。“若呕”，胃不接纳
了，则用生姜。

好的，今天就先讲到这里了，谢谢大家。

== 2014-08-23（82-88）

大家晚上好。今天讲真武汤。

82、太阳病发汗，汗出不解，其人仍发热，心下悸，头眩，身瞤动，振振欲擗地者，真武汤
主之。

真武汤方

茯苓 芍药 生姜（切）各三两 白术 二两 附子 一枚（炮、去皮、破八片）

发汗后病不解，还发热，而且出现了“心下悸”，“头眩”的反应。我们知道，这两个证是津液
虚造成的。津液虚有阴证的津液虚，也有湿证的津液虚（因湿而水饮不气化成津液）。这里
是二者兼而有之。“心下悸”是水饮在中焦。“身瞤动”，肌肉会动，湿气在肌肉里游走，这个
跟表证是有关系的，如果没有表证，湿气不会跑到肌肉里来。“振振欲擗地”，就是站不稳了，
要倒下去的感觉，“振振”是身上颤动，这是有湿气，且津液大虚了，湿多血少。综合来说，
这是一种湿气在全身游走，且津液大虚的证。茯苓和白术去中焦水饮；炮附温全身之阳救津
液；生姜健胃兼发表。合而用之，既救津液又去肌肉之湿。

这个方子里不好理解的是白芍，历来争议很大。白芍无非两个作用，一是敛津液，二是泻下
焦之实，在这里主要是引全身之水往下走。泻水可以用泽泻猪苓，亦可用少剂量的大黄，为
什么要用白芍呢？因为泽泻猪苓咸寒，大黄太破，泻水之力都太强，白芍温和些；这里有津
液大虚，苓术附姜合用是热燥的，将湿气化去之后，白芍兼有敛津液善后的作用。所以仲景
用药并不局限于药物具体是治什么的，也没那么多死板的用药禁忌，什么白芍不能用于湿证，
白芍伤肾阳，这都是局部的医学，背离了中医的整体精神。仲景是把药物看成一种能量场，
以之平衡人体的能量场而已。

此方以真武为名，真武者，北方水神也，名之以治水之方。

现在我们基本上已经学了一整套祛湿的方子了。我们可以来回顾一下。我们以去中焦水饮的
苓桂术甘汤为中心点，来归纳一下这些方子。比苓桂术甘汤更寒更阴证一点的，口渴而不想
饮水的，是茯苓甘草汤，这里面加了生姜。比茯苓甘草汤更阴证一点的，就是我们现在学的
这个真武汤了。那比苓桂术甘汤更热更阳证一点呢？五苓散。五苓散桂枝这样的热药用量很
少，而是重用泽泻猪苓这样偏寒的药。五苓散治的是中焦的渴欲饮水，且水逆，水入即吐。
这是中上焦的反应。如果是下焦的反应呢，小便不利，下焦泌尿系统生殖系统炎症为主的，
那就是猪苓汤了。猪苓汤也是治偏热证的，没有桂枝白术，有滑石阿胶，润滑下焦，利尿治
尿道涩痛。如果热明显，还可以加大黄，大黄破一切下面的淤和热。如果比猪苓汤更热的证
呢，还有茵陈蒿汤，茵陈栀子大黄。

刚才讲了饮在中焦下焦，下焦也就是偏里，这些方子。那水要是在表呢？我们也学过两个方
子:越婢汤，大青龙，这两个方子都是可以发越表之水的，这里面有什么？越婢汤是麻黄石
膏，大青龙是麻黄桂枝石膏。当然，表水偏阴证的可以用我们刚才说的真武汤。里水用利尿
药，用攻下药；表水用麻桂这样的发表药。这还是一个原则，病在表从表解，病在里从里解；
病在上从上解，病在下从下解。所以我们现在看六经辨证已经可以看出一个轮廓了，无非是
两个原则，一个是病位原则，就是刚才说的；一个是阴阳原则，阴证阳证落到具体就是津液
的多少，这个脉象反应更准确。经方体系治病就是这两个大方向，说简单也简单。

另外还有一个祛邪的原则作为辅助，就是我们常说的淤血、痰饮、水湿、宿食、气滞之类。
无非就是身体的一些瘀滞而已。这套利水方剂就是祛邪的，但也要在病位阴阳的大原则里辨
证选方。

好，先讲到这里，休息十五分钟再接着讲条文。

好，现在继续讲课。

很多人都说《伤寒论》难读，好像东一句西一句没个条理，其实是有条理的。它不是按六经
的顺序依次讲，而是穿插来讲，所以我们学到太阳病第二篇，事实上六经基本已经有个大轮
廓了，阴阳的概念和区分方法 也已经有了。于是书里就开始讲一些治病的原则和禁忌了，
下面的条文讲的就是这个。其实如果学得扎实的话，学完太阳病三篇就可以进入临证了。

83、咽喉干燥者，不可发汗。

84、淋家，不可发汗，汗出必便血。

85、疮家，虽身疼痛，不可发汗，汗出则痉。

此三条的原理一言以蔽之，就是津液虚的人不能发汗。

先说第一条。“咽喉干燥”，注意这个“燥”字，以前提到咽干，却没有提到“燥”。“燥”比“干”
更热，说明这里是热伤津的情况，不能再发汗以耗津液。

第二条，“淋家”是指有尿道炎症，小便淋漓如膏甚至有脓的人。这种炎症反应也是消耗人体
津液的，所以也不能发汗，发汗后容易小便带血。这是津液伤了，下焦之热反重，无津液来
泻热，只能动血。

第三条，“疮家”。长疮也会消耗人体津液，哪怕身体疼痛有表证，不可以发汗，发汗后就会
“痉”。“痉”是偏亢盛偏热性的津液虚反应，人体的筋腱剧烈抽缩，严重的话人还会僵（角）
弓反张。

86、衄家，不可发汗，汗出必额上陷，脉急紧，直视不能眴，不得眠。

“衄家”，就是经常出鼻血的人。为什么出血？是人体在排邪气，和汗出同理。既然和汗出同
理，治疗也应该用桂枝汤类救津液为主的方剂，结果却用了发汗剂，津液大伤了。津液大伤
发生“额上陷”，额头上瘪了，这是很严重的情况了。“脉急紧”。脉“急”，人体在亢奋起来以
加快津液的生成和运行，以保证供应；发汗过了，津液伤了，反而更易感受外邪，于是脉
“紧”。“直视不能眴”，津液伤了，人体的结缔组织因为里面血管少，更容易缺少津液。维系
眼睛转动的是结缔组织，眼睛还需要泪液的润滑，所以眼睛对津液缺乏是最敏感的，于是发
生了眼睛直视不能转动的现象。“不得眠”。津血少了，人体出于自保是不能深睡眠的，因为
睡眠时血液运行减缓，人体组织会更得不到津液供应，所以人体就要保持亢奋。治失眠要找
到失眠的原因，是火是湿是实是虚，各有不同。后世医家一见失眠就用安神药，见病治病，
诸如合欢皮、夜交藤、远志、茯神、柏子仁之类都开在方子上，早年我也这样用，收效甚微。

87、亡血家，不可发汗，发汗则寒栗而振。

“亡血家”，就是经常失血的人，不能发汗。发汗则“寒栗而振”，就是打寒颤。喜欢打寒颤是
津液虚的人，人体感受外邪时津液调集不够，便用寒颤的方式迅速调集津液到体表。有人爱
打喷嚏也是同理。还有一撒尿就打寒颤也是同理，津液往下走，体表就不够了，于是用寒颤
的方式往体表调集津液。这也说明人体无时无刻不在感受外邪，表证是随时都可能会有的，
感冒只是急性的表证而已。

88、汗家重发汗，必恍惚心乱，小便已阴疼，与禹余粮丸。

禹余粮丸方（方佚）

反复发汗，那就是津液虚了。会“恍惚心乱”，这是津虚烦躁的范畴。“小便已阴疼”，津血虚
的人小便后尿道、肛门、阴部会疼痛。这是结缔管道组织的一种少滋养不润滑的拘挛反应。

我有过这样的经验，头天喝了大酒，第二天早上起来想尿尿不出来，尿完了之后尿道涩痛不
舒服。津液虚的人射完精，阴部或肛门会疼，亦是同理。

== 2014-08-30（90-97）

太阳病的第二篇已经快学完了，其实学到现在，伤寒论的治病方法大家应该也能总结出来了。
第一是津液原则，这是关于自身能量，也就是自身免疫力的，这其中包括建中、滋阴、扶阳、
清热等方法来救津液。第二是驱邪的原则，我们常说的湿、饮、淤血、痰、宿食之类就是邪。
第三就是病位的原则，六经就是病位，是关于病从什么途径来解决的问题。病在表从表解，
病在里从里解之类的话就是这个。经方再神奇，也无非就是依据这三个原则来组方的。

以桂枝汤为例，五味药，桂枝、芍药、姜草枣。后四味药是救津液的。桂枝是驱邪出表的。
桂枝里包含了驱邪和病位两个诉求。

今天首先要讲的《伤寒论》90和91条，就是关于治病大原则的条文。

90、本发汗，而复下之，此为逆也；若先发汗，治不为逆。本先下之，而反汗之，为逆；若
先下之，治不为逆。

《伤寒论》的原则，三阳病，先表后里；若先下，也就是先里后表了，那就是逆治。如果里
病紧急，比如承气汤证，那属于特殊情况，要先下，如果先治表去发汗，也属于逆治。

91、伤寒，医下之，续得下利清谷不止，身疼痛者，急当救里；后身疼痛，清便自调者，急
当救表。救里宜四逆汤；救表宜桂枝汤。

“下利清谷不止”，这是指虚寒腹泻，同时身疼痛有表证，应该先救里，因为这是三阴病的范
畴，三阴病应该先里后表。用四逆汤。阴证是津液虚造成的，救里就是温脾胃之阳气来化生
津液。传统中医是靠自身免疫力来治病的，津液的功能也就是免疫力功能。由此可见津液原
则是首位的。服了四逆汤之后，腹泻止住了，只是身疼痛了，说明病不在太阴了，应该转为
太阳了，那用桂枝汤救表就可以了。这里“急当救里”的“急”，不是紧急的意思，而是迅速的
意思。三阴病就该先里后表。后文“清便自调者，急当救表”也是迅速的意思，有表证就该治
表，没有表证紧急不紧急的。

这里讲一下三大临证原则，津液原则涵盖的方法主要有建中、滋阴、扶阳、清热下热等等，
这都是救津液的方法；病位原则主要就是病在表从表解，病在里从里解，病在半表半里和解；
驱邪原则里的邪是什么？诸如饮、湿、痰、气、淤血、宿食、痈脓、表里寒热之类都是邪。

接下来我们要讲柴胡汤。我们知道，《伤寒论》是穿插来讲六经的，治半表半里的柴胡汤运
用很广泛，所以我们还要接着深入的来讲。

好，先休息十五分钟，再接着讲课。

好的，接着讲课。

96、伤寒五六日，中风，往来寒热，胸肋苦满，嘿嘿不欲饮食，心烦喜呕，或胸中烦而不呕，
或渴，或腹中痛，或肋下痞硬，或心下悸，小便不利，或不渴，身有微热，或咳者，小柴胡
汤主之。

小柴胡汤方

柴胡 半斤 黄芩 三两 人参 三两 半夏 半升（洗） 甘草（炙） 生姜各三两（切） 大枣
十二枚（擘）

上七味，以水一斗二升，煮取六升，去滓，再煎取三升，温服一升，日三服。若胸中烦而不
呕者，去半夏、人参，加栝蒌实一枚；若渴者，去半夏，加人参合前成四两半，栝楼根四两；
若腹中痛者，去黄芩，加芍药三两；若肋下痞硬者，去大枣，加牡蛎四两；若心下悸，小便
不利者，去黄芩，加茯苓四两；若不渴，外有微热者，去人参加桂枝三两，温覆微汗愈；若
咳者，去人参、大枣、生姜，加五味子半升，干姜二两。

这一条又讲小柴胡汤。

首先提出的是柴胡四证：“往来寒热，胸肋苦满，嘿嘿不欲饮食，心烦喜呕”，前面已经讲过
了的，这是最常见的四个主证。后面的证都加了个“或”字，说明有可能有，也有可能没有，
属于兼证的范畴。下面一一来分析这些兼证。

“或胸中烦而不呕”。上下不通则“胸中烦”；“不呕”说明胃逆和胃弱不明显。虽说不明显，一
定是有胃弱的，半表半里证本来就是胃弱后运化不力造成的表里上下痞塞不通。方后的药物
加减法说这种情况要去半夏人参，加栝蒌实。其实去半夏就可以，人参可去可不去。栝蒌实
在这里是宽胸散结气的。方后的加减法应该是后人加上去的，不过颇为在理。“或渴”，胃弱
加之痞塞不通有上热。自然津液虚而渴，所以半表半里证常有渴证。 针对这个，方后的加
减法是去半夏，增量人参和加栝楼根。半夏是降水之逆的，当然可以不用；人参是亢奋胃阴
而生津液的，可增量；栝楼根就是天花粉，滋阴药，寒而润，既能润燥，也能清热，津虚而
有热可以用到它。“或腹中痛”，上下不通，气化所余之津液不能回归于下焦，下焦津液不足，
自然腹部筋腱挛痛。方后加减法是去苦寒之黄芩，加芍药引津液下行。“或肋下痞硬”，痞硬
说明肋下结得很厉害。去掉甘壅之大枣，加散结且收敛浮阳之牡蛎。其实这种情况可以增量
柴胡、黄芩和半夏，具体原理后面讲小陷胸汤的时候会讲到。 其实牡蛎不是治肋下痞硬最
有效的药，牡蛎散的是坚结，比如肿块、肿瘤、增生之类，而肋下痞硬只是水和热之结滞。
这种情况可以增量柴胡、黄芩和半夏——黄芩治热，半夏治水，柴胡疏散。

“或心下悸，小便不利”，这个是中焦有饮。方后去黄芩，加茯苓利水.“或不渴，身有微热”，
不渴，方后去人参；身有微热是兼有外证，加桂枝。“或咳者”，方后去人参、大枣、生姜，
加五味子、干姜。五味子干姜治寒咳，原理第40条说过。至于说去人参大枣生姜，未必要去，
如果津虚且有表证，留着效果更好。

97、血弱气尽，腠理开，邪气因入，与正气相博，结于肋下。正邪分争，往来寒热，休作有
时。嘿嘿不欲饮食。脏腑相连，其痛必下，邪高痛下，故使呕也，小柴胡汤主之。服柴胡汤
已，渴者属阳明，以法治之。

此条讲的是半表半里少阳病的发病机理（前面第37条已经详细讲过了，可参看）。

脾胃弱了津液虚了，“血弱气尽”，不能驱邪外出，于是腠理开了，邪气进来了。正气与邪气
相博，互不能胜，在半表半里的位置僵持住了，便结在了肋下，其实是胸肋里面的三焦区域，
于是胸肋苦满。 正邪交争，正胜邪退，病往表往阳走则发热；正退邪胜，病往里往阴走则
怕冷，于是“往来寒热”，且“休作有时”，发作和停止有定时。脾胃弱，自然“嘿嘿不欲饮食”。
“脏腑相连”，脏为阴为敛藏，腑为阳为传输，一静一动一阴一阳，其功能是相连的。少阳病
为痞塞不通，脏腑运行自然也不顺畅，邪气上不能出表则为邪高，下不能通则会痛，此谓
“邪高痛下”。胃为脾之腑，胃不降因此会呕。

以上为柴胡四证之原理。

服了小柴胡汤如果很渴，说明兼有阳明病，此阳明为肺胃区域有热，条文中说“以法治之”，
可以用小柴胡汤加生石膏。小柴胡加生石膏汤这个方子用途很广泛，证属少阳的诸如高热、
腮腺肿大、淋巴肿大、大脖子病、甲状腺亢进、乳腺的增生肿瘤类疾病，用之有奇效，往往
几剂而愈。为什么呢？因为病发于上多为阳证，生石膏的不仅寒降，且辛凉而散上焦之热结。

好，今天就先讲到这里，谢谢大家。

== 2014-09-06（99-100）

经方-夏正安:今天刘希彦老师临时有事。暂时由我根据刘老师的讲义接着上周的课代为讲解
条文。现在接着上周讲解伤寒论条文：

98、得病六七日，脉迟浮弱，恶风寒，手足温，医二三下之，不能食，而肋下满痛，面目及
身黄，颈项强，小便难者，与柴胡汤，后必下重。本渴饮水而呕者，柴胡汤不中与也，食谷
者哕。

这一段出现一些后面才有的内容，行文也有些乱，疑有错简。

病了六七日，“脉迟浮弱”，脉浮病还在表；脉迟弱，并不紧数，说明邪气已经在退。“恶风
寒”，说明津液还虚；“手足温”，说明津液已经在慢慢恢复，手足已经开始热了。这时候病
已经快好了，大夫却“二三下之”，反复的用下药，于是又伤了胃气，“不能食”了；“肋下满
痛”，说明病在半表半里；“面目及身黄”，有黄疸，结合后面“颈项强，小便难”这样的津虚
证来看，应该属于阴黄，就是陷于阴证的黄疸。黄疸是因为脾胃运化不力，三焦水道不通，
脾脏黄色的营养淤在肌肉里，淤而生热所致。只要小便利了，黄疸就会好。同时津血虚少陷
入阴证，那就是寒热夹杂，属于六经之厥阴病的范畴。那么，上证处柴胡汤是否合适？该处
什么方？按上述情况，柴胡桂枝干姜汤加茵陈合适。给了小柴胡汤，服药后必定会“下重”。
何为下重？就是很想排便，肛门坠胀，却排不出来。这种下重的局面是肠道有热，脾胃却虚
寒，推动力不够引起的，与黄疸的原理类似。小柴胡汤还是以清热为主的，所以并没有解决
阴证的问题。黄疸、厥阴病、柴胡桂枝干姜汤是后面的内容，这里就先不详作解释。“本渴
饮水而呕”，如果渴欲饮水而呕逆，这是前面学过的五苓散方证，柴胡汤自然也不合用。

99、伤寒四五日，身热恶风，颈项强，肋下满，手足温而渴者，小柴胡汤主之。这一条可以
看做是一个典型的小柴胡汤的医案。

“身热”有表证。“恶风”、“颈项强”，表证兼津液虚。“肋下满”，柴胡四证之一，四证具其一
便可以确定是半表半里证。“手足温而渴”，偏向于热的方面，那就是少阳证。处小柴胡汤。
这里有太阳病，也有少阳病，为什么只用小柴胡汤呢？临证上不管是三阳并病还是二阳并病，
只要有少阳病就要以少阳病为主来治。为什么？原因有二：第一，半表半里是中间区域，是
表里的枢纽，半表半里不通，里外皆不得通；第二，半表半里证的实质是脾胃弱，所以柴胡
类方的方药都是以建中为主的，脾胃功能恢复了，无论哪个区域的病就都可以得到解决。

好了，今晚的第一节就到这里了。休息十五分钟中后，接着讲，会有一个很重要的方剂，小
建中汤。

经方-刘希彦:大家晚上好。不好意思，今天临时出了点状况，所以现在才赶回来，实在对不
起大家。感谢夏群主替我代了半节课。万分感谢。

很多朋友建议过想让我讲脉学和药物学。其实，我把药物学和脉学是穿插在《伤寒论》的条
文里来讲。我讲课的宗旨是注重临证，也就是要让大家在最快时间内成为一个能用真正传统
中医思维治病的医生。所以专拣最重要最实用的东西说。

张仲景写《伤寒论》亦是这个思路，我这也算是师法先师了。闲言少说，下面讲一个很重要
的方子，小建中汤。

100、伤寒，阳脉涩，阴脉弦，法当腹中急痛，先与小建中汤。不差者，小柴胡汤主之。

小建中汤方

桂枝 三两（去皮） 甘草 二两（炙） 大枣 十二枚（擘） 芍药 六两 生姜 三两（切） 胶
饴 一升

“伤寒，阳脉涩，阴脉弦”。脉之寸为阳，浮取为阳。脉涩如何解释呢?《濒湖脉学》里形容
是“轻刀刮竹”，用刀刮竹子会有磕磕楞楞的不流畅的感觉，自来水管里没水了也会有这种擞
动。严重的涩脉是血行有阻滞，比如癌症就会现这个脉象。这里是轻微的涩脉，主的是血少。
说到涩脉，有一个很有意思的事情，曾经有一个叫杨文魁的老大夫，到瑞典去看儿子。瑞典
的市长听说中国来了个神医，市长会都不开了，来看望他。并且带来了六个病人。老大夫
不懂英文，只挨个摸脉，一模就说是癌症，一直摸到第五个都是癌症。都说对了。老大夫心
想，这不是试我吗？于是成心好好露一手，摸到第六个的时候，他说这个人五个星期死，后
来果然五个星期死了，怎么救都没用。老大夫摸的就是涩脉。这个脉很难，手感不好找。秋
天正常就会现轻微的涩脉，大家可以趁这个季节体会下。好，接着说条文。“阴脉弦”，脉之
尺为阴，沉取为阴，弦脉如何解释呢？就是像琴弦一样绷直。弦脉是主饮主寒主气滞血瘀。
弦脉临证很多见，我们来详细分析一下弦脉出现的机理。弦脉事实上是脉象亢盛起来的一种
表现。有饮有寒有淤，人体就要亢盛起来调动气血去攻，攻之不下，脉便会一直绷着，和有
表证要现紧脉是同一原理。如果血充足，脉亢盛起来就是滑脉，滑脉的触感是血液像珠子一
样流利的从血管里通过；如果血不充足，又要亢盛起来，就只能摸到脉管绷紧，里面的血却
鼓荡不起来，这就是弦脉出现的机理。弦脉如果回到正常的状态应该是缓或细弱的脉，所以
弦脉属于虚的范畴。有是时候会有弦滑脉出来，这是因为血不够却又有热，有热则血鼓躁，
于是弦和滑同时出现。涩也好弦也好，总之是津血少。津血少而又有外邪，气血要去体表攻
邪，腹内的津血就不够了，于是“腹中急痛”，这是腹部的筋腱缺少津液在痉挛。人体只要痛，
津血就会往痛的地方汇聚，这也是人体争夺气血的一种自保功能。

下面说方药。说先与小建中汤，若没好，再与小柴胡汤。《伤寒论》很少有这种不确定的表
达。就这个条文，我们可以这么去理解：这里只有一个证，就是腹痛，然后就只有脉象了。
腹中痛不是少阳病的确证，亦不是太阳病的确证，但参以脉象，有一点是可以肯定的，就是
津血虚。津血虚自然是要以建中为主，小柴胡汤是以建中为主的方子，小建中汤更是以建中
为主的方子。于是，张仲景给出了一个建议，先用小建中，不行再用小柴胡。这说明一个问
题，在临证上，病人的证状似是而非，找不到确证的情况是常有的。作为一个经方家，若能
真正参透人体的运行规律，就能根据现有的证状锁定一个范围，纵然一次不中，二次也会中，
不会超过三次。我在教学生临证的时候，碰到证不全的情况，我也经常会说出两个相近似的
方子，不是这个就是那个，因为是近似方，就算不准确，病情也会缓解。如果你能开两次药
给病人治好，无疑已经是个好大夫了。就怕你不知道怎么思考人体，不知道方药在人体里的
确切作用，治好了不知道为什么治好，治不好不知道为什么治不好。这样的话，病人就算来
十回也还是治不好，就像那些后世中医，一个病治半年一年，迁延不愈的多的是。所以我主
张学医要把人体的运行规律，以及方药和人体的确切关系搞清楚，这才是仲景之学的精神。
小建中汤事实上是桂枝汤将芍药加倍，并且加了胶饴。桂枝驱外邪，外邪去津血自然就会回
来。将芍药加倍是为了增加收敛津血的作用，同时止腹痛；胶饴就是麦芽发酵制的糖，性温，
糖是能直接吸收的，温补津血的作用很快。此二药和姜草枣合用，便能速补津血。好，今天
就讲到这里了，谢谢大家。

== 2014-09-13（103）

《伤寒论》太阳病中篇就是方子多，基础方大多出自这一篇。今天讲一个很重要的方子，大
柴胡汤。

我们知道，柴胡类方剂在临证上是使用频率最好的。而大柴胡又是柴胡类方剂里使用频率极
好的，尤其在重症上面使用率高。 很多同学提议要我结合课程讲一些医案，讲一些临证的
心得。我今天就尝试着结合大柴胡来穿插讲一些临证的心得吧。

103、太阳病，过经十余日，反二三下之，后四五日，柴胡证仍在者，先与小柴胡。呕不止，
心下急，郁郁微烦者，为未解也，与大柴胡，下之则愈。

大柴胡汤方

柴胡 半斤 黄芩 三两 芍药 三两 半夏 半升（洗） 生姜 五两（切） 枳实 四枚（炙） 大
枣 十二枚（擘）

用了下药造成误治，柴胡证仍在的话，先给小柴胡汤。服了小柴胡汤后发生了“呕不止”的情
况。呕不止是剧烈的呕吐反应，区别于小柴胡汤的“喜呕”。且有“心下急”，心下是胃的区域，
感觉急结，里面有食物堵住了。这都是因为病人有柴胡证，本来就上下不能交通，同时又有
宿食积滞，堵在了胃肠里，于是形成了少阳和阳明的合病，此为大柴胡汤的方义。既然是少
阳阳明的合病，阳明如何治呢？在大柴胡方后面的加减法里有提到，大柴胡汤是要加大黄二
两的，没有大黄不成其为大柴胡汤。枳实加大黄，已经略具承气汤之意了，只是没有厚朴芒
硝，用药发热量也轻些。大柴胡证的热是在中下焦，主要表现为便秘或腹泻，所以只是“郁
郁微烦”，区别于小柴胡证的上热心烦。大柴胡汤是小柴胡汤去了党参炙甘草，加了芍药、
枳实和大黄组成的。加芍药是引津血下行，且去腹痛；加枳实、大黄是泻肠胃之实。去了党
参炙甘草是因为肠胃有积滞有热，所以不用这种滋补的东西，只保留大枣和生姜建中。用生
姜是因为有呕，当然也是因为胃虚。大柴胡汤的积滞不同于承气汤证，大柴胡汤有胃虚，是
胃虚不能运化的瘀而生热、寒积化火的积滞；承气汤是真正的实热证的积滞，所以大柴胡汤
里可以有生姜。说到这个大柴胡主治胃虚而有火的积滞，我和大家来分享一个医案，是我前
段时间治的一个，很有代表性。是一个痔疮出血的医案。

张金文，男，青年。自述：痔疮出血疼痛，出血量很大，走路都受影响。刻诊：便秘干结，
胃有些返流，大腿根部酸痛，腰酸痛。脉不稳定，时而亢躁，时而缓弱。平时食肉多，运动
少。患者提供的症状不多。里证有便秘；表证有腰酸腿根部酸。半表半里证却不明显。不明
显不等于没有，往往不明显是最考验医生功力的时候，也是考验医生是不是真正理解人体的
时候。

我是这样的考虑的。脉时而亢燥时而缓弱，或可理解如疟状，病在进退之间，类似于往来寒
热，邪实津虚；胃返流是呕的类似证，其原理一样是胃弱，半表半里证是胃弱邪入引起的；
我说过，《伤寒论》的六经辨证体系是可以统脏腑经络体系的，我们也可以参考经络辨证。
大腿根部两侧疼痛，为肝胆经。胆为厥阴，肝为少阳，络的是半表半里。综合来看可以视为
有半表半里证。且失血而脉弱，又有痔疮肿痛便秘，寒热夹杂，情况复杂。不管多复杂，总
之是有三阳并病，那就是治从少阳。便秘痔疮严重，便秘是阳明，少阳阳明合病，用大柴胡
加减。

一诊处方：

柴胡 30 白芍 30 黄芩 15 法夏 15 枳实 15 酒大黄 10 厚朴 20 大枣30 炙甘草 25 干姜
20 吴茱萸 20 桂枝 20 当归 20 四剂

首先说为什么用干姜，因为脉虽然不稳定，总体来讲是偏虚弱的，干姜能温中救津液。桂枝
当归是行血的，所谓血无止法，出血证通俗说是由血行不畅而溢出，通畅的水管和河流都不
会外溢，哪里堵住了才会外溢。病人偏虚证，桂枝当归适用。这就是为什么止血药大多是活
血药，比如三七。吴茱萸苦辛温是降胃之逆的。厚朴不用讲，下气宽肠。

现在来看看效果。四剂未尽出血即止；便秘基本缓解；大腿根部疼痛减轻；痔疮还会痛；小
便时微有涩痛感。二诊处方：

柴胡 30 白芍 30 黄芩 15 法夏 15 枳实 15 酒大黄 10 熟大黄 5 厚朴 20 大枣20 炙甘草
25 干姜 20 吴茱萸 20 肉桂 20 当归 20 滑石 20（包煎） 四剂

滑石寒滑而除下焦湿热，且润滑尿道涩痛。

现在来看效果。患者服完后告诉我痔疮基本好了，小便涩痛也消失。痔疮这个病很难短期除
根，嘱病人多吃素多运动善后。所以治病不可拘泥，有胃虚中虚，就可用姜，有大肠湿热就
可用大黄。这其中并不矛盾，有是证用是药，这才是经方法度。好，先讲到这，休息十五分
钟，接着讲大柴胡汤。

刚才有朋友问到药的问题。先说大黄，生大黄，酒大黄。熟大黄。一般来讲，药制后气便减，
味便厚。更易走下焦。承气汤里的大黄就是注明酒洗的。这是酒大黄，熟大黄比酒大黄更温
和。取其缓下，一般用它。枳壳和枳实，性质差不多，枳壳温和些，枳实峻烈些。

好，接着讲大柴胡汤的加减。在临证上，如果热象明显，生姜也可以去掉，甚至可再加生石
膏，只留大枣建中即可；如果水饮明显，则可以将生姜换成白术；如果肠胃有腐浊，可以将
生姜换成藿香佩兰。如果有大柴胡证且寒象明显，是寒积化火的肠胃积滞，则可以将生姜换
成干姜。经方要如此灵活加减才更能效如桴鼓。大柴胡之所以能如此广泛的运用，是因为有
半表半里证，同时有下焦瘀滞的局面非常多见。这种下焦瘀滞不仅限于肠胃积滞，也包括淤
血。芍药和大黄的组合就是可以祛瘀血的。经方大家胡希恕很擅于用大柴胡治疗各种疾病，
甚至有“大茶壶”（谐音）的外号。胡老常用用大柴胡治疗哮喘、心血管疾病和肝脏的疾病，
因为这些疾病往往伴有淤血证，大柴胡里的芍药和大黄的都能下淤血。当然，可以再加当归、
川芎、丹皮、桃仁等去淤血的药，显效更快。前面我说过，大柴胡再疑难症重症上很常用，
下面我就来分享一个这样的病例。

曾某、女、成人。刻诊：脖子上长了个肿瘤，手摸有小芒果大小。汗出多，尤其是晚上。胸
中和脖子略有阻塞感，偶有气窜感。大便二三日一行，略不爽。脉象左右皆浮燥，沉取略偏
虚；右脉偏有力。病人害怕是恶性的，要去医院检查，又惧怕手术，因为脖子上神经血管太
多，手术不好做。

我说要不先吃中药治一段时间，管它是什么，只要吃中药能消掉不就没事了吗。下面说一下
辨证思路。病家证不多，亦不是很明显。胸塞可以理解为胸肋苦满范畴；便不爽是阳明。可
以从大柴胡论治。汗出多，太阳病，桂枝汤。那就是大柴胡合桂枝汤加减。

柴胡 25 黄芩 15 生半夏 50 大枣 15 枳实 20 厚朴20 白芍 15 藿香10 大黄 6 桂枝 15
炙甘草 15 生石膏 60 夏枯草 15 生锻牡蛎各25

先说为什么去生姜加生石膏，因为脉浮躁，且右脉略显有力。这是有标热，加石膏。散坚结，
牡蛎石膏夏枯草半夏皆有此效。为什么加藿香？因为是夏天，中焦易湿阻。这是考虑到五运
六气。

五运六气是可以考虑，但前提必须是人体的反应，病人舌象湿滑。《伤寒论》体系是以人体
实实在在的证为依据的。我不是反对五运六气，我反对的是抛开人体的实证谈五运六气。我
们治的是人体，治的又不是天地。证轻药也轻，除半夏牡蛎外，剂量都不重。

现在来看效果。服药一周后，瘤子明显缩小。大便通，去大黄，再服。前后共服药十五剂，
瘤子用手基本就摸不到了。病势已去，停药。嘱其注意生活规律，心情舒畅，多食海带散结。
不久后瘤子完全消失。

大柴胡汤里新出现一味没讲过的药，枳实。枳实这味药是橘类的幼果，其味香烈而苦辛，是
破气药，上能破胸之气满；中能消痞导滞；下能破大肠之气闭气结。和厚朴作用相近似，只
不过厚朴温厚，枳实峻烈。厚朴苦温，香味淡厚而非浓烈，苦走下，厚也走下，在经方中主
要用于除腹满；枳实主要用于去胸满。二药常同用。

好，今天先讲到这里，谢谢大家。

== 2014-09-20（104-106）

大家晚上好。今天接着讲《伤寒论》。

104、伤寒十三日不解，胸肋满而呕，日晡所发潮热，已而微利。此本柴胡证，下之以不得
利，今反利者，知医以丸药下之，此非其治也。潮热者，实也。先宜服小柴胡汤以解外，后
以柴胡加芒硝汤主之。

柴胡加芒硝汤方

柴胡 二两十六铢 黄芩 一两 人参 一两 甘草 一两（炙） 生姜 一两（切） 半夏 二十铢
（本云五枚，洗） 大枣 四枚（擘） 芒硝 二两

感冒十三天不好，已经到了血弱气耗的时候了。“胸肋满而呕”，呈现出来的是柴胡证。“日
晡所发潮热”，“潮热者，实也”，这是说有潮热的人是里面有实，有积滞。有积滞的人到了
日晡，也就是黄昏的时候，阴气重了，气血运行能力弱了，瘀滞得会更严重，于是发生这种
潮热，像潮水一样定时发作。有淤血证的人会睡前烦躁发热，甚至越睡越兴奋也是这个道理，
睡前是阴气最重的时候，内有淤血此时也会瘀滞得更严重，于是淤而生热。

“已而微利”，潮热事实上也是人体在亢盛起来调集能量排瘀，所以潮热之后会有微微的腹泻。
“此本柴胡证，下之以不得利。”古人行文太简，联系前后文来看应该这样解释：如果是柴胡
证的潮热，用大柴胡下之，应该就不腹泻了。为什么本来有腹泻，用了大黄这样的下药泻药
反而还不腹泻了呢？这也是一个临证上要注意的问题。如果是肠胃的积滞造成的偏实热的腹
泻，用了大黄反而会止泻；如果是偏实热的便秘，用了大黄就会大便通畅。所以，说一样药
物止泻或者通便是容易误导人的，用这种理解去治病，时效时不效当是常事。药物只是一种
能量，这种能量只是让人体回到正常秩序和状态，至于腹泻也好止泻也好，是人体自己去协
调的事。后世的医家总喜欢用药物直接去通便去清热去消炎，结果病没治好，病人元气大伤，
陷入阴证，越发缠绵不愈的比比皆是。在这种中医理念被歪曲的时代，做真正的中医很难，
现在的人以为便秘就是上火，上火就要泻火，你给他开大柴胡，他一见到生姜大枣立刻就认
定你是个庸医了。我治过一个痔疮疼痛大出血的病人，刻诊脉证偏阴，用干姜桂枝，合了一
点点大黄，很快血就止了。病人之前吃过很多泻火药，不但没好，反而越吃越严重。所以辨
证辨的是证，不能跟病症扯到一起，不能说出血就要禁桂枝干姜，就得用止血泻火药，有时
候你越用止血泻火药越止不住。现在有的人又在研究人体的局部现象和药物的关系，比如什
么舌象要用干姜，什么药瘦人适用，胖人不适用之类的，这都是割裂人体，背离了综合辨证
整体思考的原则，偶尔或许能中，以此为原则来临证开方只会将医学带入小道。

“今反利者，知医以丸药下之，此非其治也。”接着前面的条文说，该吃下药的吃了下药该止
泻，如果吃了下药反而腹泻加重了，那就是医生用丸药下了。何为丸药呢？在古代指类似于
巴豆这样的温性烈性的泻下剂。大柴胡汤是建中疏通为主，泻下为辅的，用了巴豆竣下当然
是误治，腹泻当然会严重。下面说解决方法，要先以小柴胡汤解外，再用小柴胡加芒硝汤下
之。

为什么要分两步治疗呢？因为泻下之后津液脾胃皆虚，此时如果又解表又治里，津液如何能
兼顾表又兼顾里呢？所以只能治从少阳。少阳的治法是以建中救津液为主，然后就是疏通半
表半里。津液复了，枢机通了，人体自己就能解决问题。这就是三阳并病治从少阳的原理。
在这种津液伤了情况下，哪怕里有瘀滞，也只能先治少阳。小柴胡汤让津液复枢机通，人体
自己将外证解了，如果里证还有，这个时候就可以兼顾攻下了。于是要用到小柴胡加芒硝汤。
小柴胡加芒硝汤是用约三分之一剂量的柴胡汤，加上芒硝组成的。这个组方也很严谨：之前
已经用过柴胡汤，津液已复，外证大致已经解了，所以柴胡汤可以减量。因为芒硝虽然也是
攻下药，攻下之力却不如大黄，其性寒咸微酸，更偏向于去潮热散坚结。这里主要是潮热，
用芒硝更合适。

好，先讲到这里，休息十五分钟接着讲桃核承气汤。前面我们讲过饮证和宿食的治疗，就是
五苓类方和承气类方。从这个方子开始我们就会陆续讲到关于瘀血证的治疗。

好，继续上课。

106、太阳病不解，热结膀胱，其人如狂，血自下，下者愈。其外不解者，尚未可攻，当先
解其外。外解已，但少腹急结者，乃可攻之，宜桃核承气汤。

桃核承气汤方

桃仁 五十个（去皮尖） 大黄 四两 桂枝 二两（去皮） 甘草 二两（炙） 芒硝 二两

太阳病不解，热结于膀胱。准确的讲是热与淤血结在膀胱这个区域，也就是腹部下方这个区
域。这是实热型的淤血证。如何鉴别呢？“其人如狂”。下焦有淤血，人体的自然模式，津血
就要汇集于下焦去攻这个淤血，那头部的津液就缺乏了，这时候头部也要启动自保模式兴奋
起来争夺津血；加之有热，热不能下则上冲，这种兴奋反应就会很强烈，“如狂”了。之前学
过阳明实热证有谵语和烦惊的反应，和这个原理一样，都是有瘀滞在下面堵住了，同时有热
证。不但热证的淤血有“如狂”，阴证也会有，只是没那么强烈。

我曾经治过一个病人，看上去脾气非常好，非常谦和敦厚的一个人。他叫秘书出去，关上办
公室的门，然后掀开老板椅上的衣服给我看，老板椅上一道道砸痕，白色的木头都被砸出来
了。是他砸的，门后放着一根棍子。再看脉象，弦迟脉，一派瘀滞阴寒之象。我用柴胡桂枝
干姜汤合当归川芎牡蛎龙骨，一个星期后病人告诉我，情绪好了，不砸了。这就是阴证淤血
的“如狂”。当然，阴证淤血证的“如狂”一般还可以自控，也就是莫名烦躁抑郁、情绪容易起
伏、容易悲观而已，因为没有热上冲；热证的“如狂”往往强烈到不能自控。如果病人自己有
便血的话，淤血证也就解了，病也就好了。如果用药物治疗的话，就需要辨证了。若外证没
有解，那就不要管腹中淤血的问题，按先表后里的原则，要先解外。外证解了，只有少腹急
结了，这就可以攻下了，如果是热证的淤血，那就用桃核承气汤。有些医家见桃核承气汤里
有桂枝，便认为这个方子治的是表里同病。其实不能这么理解，因为条文中说得很清楚，外
证已解才用桃核承气汤。那桂枝在这里起什么作用呢？首先，《伤寒》理解人体是一个运行
着的能量场，这个能量场以压力锅做比方，只有把气放出来，旁边的阀门才会掉下去。同理，
只有打开向外的通道，下焦的淤阻才更容易向下排。人体的脏腑关系也是这样：五脏的经络，
比如脾经、肾经、肝经都是从下往上升的；六腑的经络，比如胃经、膀胱经、胆经都是从上
往下降的。脏腑相连，脏之气往表往上走，腑之气随之往里往下走，脏不升则腑不降。所以
用桂枝事实上是借用向外的力量来帮助降里下淤，并不局限于有没有明显的表证。再者，与
后面的抵当汤对比来看，桃核承气汤之蓄血主要蓄在膀胱这个区域；抵当汤之蓄血蓄在里，
也就是以大肠为主的这个里的区域。膀胱经是络表的经络，桂枝走表，气化增加，自然废水
的下行之力也会增加，此二力原为一体，自然用桂枝解外也就能通利膀胱。炙甘草是顾护中
气的；大黄芒硝是攻下的，这都不用再解释了。这里说说桃仁这味药。桃仁辛厚香苦，辛香
行散，味厚郁则能走血，苦则破下，所以主要用于开破淤血。它没有滋养之性；偏性不强，
香苦兼有，所以寒热虚实都能用。好，这个方子就讲完了。

今天的课就讲到这里。谢谢大家。

== 2014-09-27（107-122）

大家好。上次课我们讲了治瘀血的一个方子，桃核承气汤。按说应该接着讲治淤血的方子。
可《伤寒论》的行文是有些乱的，因为当初是竹简，这么多年传下来，就难免有顺序的错误。
在条文上接下来讲的是怎么治虚热。虚热包含两个层面的意思：第一是津血虚而有热；第二
是无宿食、痰饮、淤血这样的实阻，而有热。虚热在临证的时候是最多见的，是最复杂的，
是最容易辨证不当，也是最容易治错的。今天，我把几条治虚热的条文放到一起来讲。

下面讲的这个方证就是一个完整的虚热证的医案。这个医案在临证上很容易治错，所以大家
要认真看。

107、伤寒八九日，下之，胸满烦惊，小便不利，谵语，一身尽重，不可转侧者，柴胡加龙
骨牡蛎汤主之。

柴胡加龙骨牡蛎汤方

柴胡 四两 龙骨 黄芩 生姜（切） 铅丹 人参 桂枝（去皮） 茯苓各一两半 半夏 二合半
（洗） 大黄 二两 牡蛎 一两半（熬） 大枣 六枚（擘）

这个方证很容易让人以为是承气汤证，这个辨证过程比较复杂，但弄通了也很简单。在讲之
前，要重温一下治病的大原则。

我们读《伤寒论》经常会看到汗后如何如何，下之后如何如何。其实这是仲景以外感病为例，
就是从现象教你怎么治病。若要真正读懂这本书，就要理解现象后面的本质。汗下后的实质
含义是津血虚，所以不管有没有汗下，只要是津液虚就可以同样来论治。

《伤寒论》基本上都在讲外感病。那所谓的内伤病慢性病怎么治呢？我们开篇便说过，中医
是治人体的，而不是治病的，既然不是治病，那就不分什么外感病内伤病。《伤寒论》治病
的依据是人体显现出来的证，只要是有相应的证，就用相应的方子，一切病就都可以治。所
以，桂枝汤也好，柴胡汤也好，可以治相应的无论外感内伤的一切病。

我们后面学《金匮要略》就会发现，《金匮》里那些所谓的内伤病，也还是用《伤寒》里这
些方子来治疗，无非随证略施加减而已。所以《伤寒论》事实上是以外感病为例子在教你治
万病。这一条就是这样，首先是下后“胸满烦惊”。“胸满”是柴胡证；“烦惊”呢？实证虚证？
一时不好下结论，继续往下辨证。“小便不利”，湿证还是津液虚，还是不好下结论，继续往
下辨证。

“谵语”，这是阳明实热证的津液虚引起，那前面的就都有结论了，“烦惊”是有热。那“小便
不利”是津液虚吗？后面还有“一身尽重”，这个小便不利就是湿气郁于外的小便不利。那这
个情况就是外有湿，内有热。这个和津液虚矛不矛盾？不矛盾。湿郁也会津虚，因为水湿不
气化不循环。所以我一直说真正的传统中医治病就像破案，一条条排查比对综合分析，直到
找出确切的证据。

“不可转侧”是躺在床上翻身困难，前面学过有津液虚引起的，这里兼有“一身尽重”，那这个
翻身困难就是因为湿气郁于肌肉了。

这是三阳并病，自然治从少阳，那就是用柴胡汤做主方。然后就是加减之法了。首先是用大
黄下热存津；然后龙骨牡蛎铅丹安神定惊，铅丹是取其金属重坠之性以镇定，有毒，所以我
们现在不用了；外有湿，用桂枝茯苓。

为什么不直接用大柴胡呢？因为这个情况津液虚明显，所以用小柴胡加减，小柴胡里有人参
炙甘草，更能救津液。从这里可以看出，《伤寒论》教我们的是治病的原则和方法，灵活应
对人体的方法，不可拘泥。方证相对在初级阶段是可以的，想要到更高阶段就要突破这一层。

《伤寒论》用药精简，我们前面学过的就已经涵盖大部分主药了。这一条再讲两样常用药：
龙骨、牡蛎。

好，先讲到这，休息十五分钟接着讲

现在讲两样很常用的药，龙骨和牡蛎。龙骨是远古动物的化石，取其镇定收摄之性。这个药
安神很管用。我现在用得少，没办法，药房哪有真的远古动物的化石，据说都是用猪羊的骨
头高压锅焖的。一般我宁可重用些牡蛎，至少牡蛎是真的。牡蛎是就是海中的牡蛎壳，取其
燥涩镇敛之性。这两样药经方里同时用的时候很多，用在惊、狂、卧起不安这一类的证。临
证上治失眠烦躁多思多虑，效果也很好。

两药还可以用于治遗精阳萎，所以有医书说这两样药是补肾的。其实这两样药只是毫无滋养
之性的钙化物而已，哪能补什么肾呢？本身补肾这个概念于药物对人体的真实作用就有待商
榷。应该说是其镇敛的作用能收精气趋下，精气下自然肾气足。也正是因为这两样药无滋养
之性，亦不热不寒，所以寒热虚实皆能用。同为收敛药，芍药微苦酸寒，性质温和，偏向于
敛津液，亦能泻实；五味子温燥而酸收，主要用于咳喘水饮；山萸肉酸温固脱，主要用于元
气不固；乌梅则酸而轻升，无温补之性，可用于温病之虚浮，暑月之收敛；龙骨牡蛎煎水接
近于无色无味，因其为骨壳之钙化物，秉重镇收涩之性，它们不是靠酸味和黏质来收敛的，
所以和前面那些收敛药都不一样。

牡蛎这味药用途很广泛，除敛涩之外，还可用于燥痰湿和化坚结。痰湿和坚结虽然叫法不一
样，无非都是瘀滞凝结之物而已。我们之前只知道辛温发散是去瘀滞的，其实收涩之法也可
以去瘀滞。好比皮肤上有疮痘积液，未必要破溃才去，人体自己的收敛吸收也能去掉。牡蛎
就是用其收涩之性来化痰结瘀滞的；又因其是坚硬的壳类，同气相求原则，更能化坚结。牡
蛎在肿瘤、结节、增生类疾病上运用很多，尤其是治身体的上部的效果更好。

118、火逆下之，因烧针烦躁者，桂枝甘草龙骨牡蛎汤主之。

桂枝甘草龙骨牡蛎汤方

桂枝 一两（去皮） 甘草 二两（炙） 牡蛎 二两（熬） 龙骨 二两

这是个局面比较复杂的医案。首先是火逆，上逆之证，上逆应该汗出而解，却用了泻下药，
津液虚了而病却不解；又因为用了烧针的疗法，添了烦躁。

这种情况就比较难办了，要说是津液虚，却又有热证，不能用姜枣之类补津液；要说有热证，
却又只是烦躁，并无大热，况且津液虚了，寒凉之药未必妥当。

再看仲景用药：病在上从上解，还是要用桂枝解外，却只用一两，因为本身就是上逆证了，
一两桂枝略助其力即可，无须多用。既然有热，不用姜枣救津液，只留炙甘草；那烦躁怎么
办呢？寒凉药不合用，那就用龙骨牡蛎，不寒不热不滋养，敛火而已。

这就是仲景之法度。为什么那些谈玄论道的医理指导临证往往效果不佳，因为那些医理一到
人体的真实机理，到药物于人体的真实作用就止步了。于是方药混乱不堪，医生们各凭各的
理解，方药各异，能不能治好就看运气了。

研习《伤寒论》的医生，他们在同样的情况下处方用药是大致相同的，因为这个体系有严谨
的法度。

122、病人脉数，数为热，当消谷引食，而反吐者，此以发汗，令阳气微，膈气虚，脉乃数
也。数为客热，不能消谷，以胃中虚冷，故吐也。

脉数是有热，有热当消化力强，食欲亢盛，可为什么吃了东西反而呕吐呢？这是因为发汗消
耗了阳气，膈气也就虚了（膈气可以理解为中上焦的气化之力）。人体出于自保，就要亢奋
起来增加气化之力，所以脉数。这个脉数不是真的有热，而是一种临时应激机制的热，所谓
“客热”，客者过客也，不是主人。

这种热是标，胃里面其实是虚冷的，不能消化食物，所以会呕吐。伤寒论》里专门用脉象来
讲辨证的地方极少。就这一条可以来讲一下脉象的问题。诸如脉数、脉躁动、脉促寸盛、脉
大之类，很容易让人误解为是有热。这些表面亢盛的脉象很有可能是客热，其实底子是寒的，
临证很容易弄错。很多医生一见这些脉象就下清热滋阴药，于是温病派滋阴派就出来了。如
何在脉上鉴别是真热还是假热呢？其实沉取重取一下就知道。如果脉浮取轻取亢盛，沉取重
取就虚了空了，或松手无回弹力，或尺虚不任按，这都是真寒假热的脉象。

好，今天就先讲到这里，谢谢大家。

== 2014-10-11（124-127）

大家晚上好。今天这堂课就可以把太阳病第二篇讲完了。今天的条文有一个新的内容，就是
将瘀血证的治疗。

下面进入条文的解读。

124、太阳病六七日，表证仍在，脉微而沉，反不结胸，其人发狂者，以热在下焦，少腹当
硬满，小便自利者，下血乃愈。所以然者，以太阳随经，瘀热在里故也。抵当汤主之。 抵
当汤方 水蛭（熬） 虻虫各三十个（去翅足，熬） 桃仁 二十个（去皮尖） 大黄 三两（酒
洗）

此方也是治热证的血结下焦的，常常被拿来与桃核承气汤做对比。这里也用对比的方式来解
释这个条文。

首先，它们都是有血与热结在下焦，但位置还是有所区别。桃核承气汤是“热结膀胱”，膀胱
区域会硬满，也有可能会尿异常，比如膏淋、尿血；抵当汤是“小便自利”，说明膀胱里面没
有结住，那就是结在里了，所谓“瘀热在里”，也就是肠道为主的这个区域。膀胱经络表，所
以桃核承气汤有桂枝，气化走表以利膀胱，而抵当汤没有桂枝。芒硝除了软坚攻下去潮热，
还有凉散的作用，凉散则能达表，所以桃核承气汤有芒硝，抵当汤无。

其次，桃核承气汤是“少腹急结”；抵当汤是“少腹当硬满”。硬满比急结程度更深，说明里面
的淤血结得更顽固，则攻下之力不能缓，所以抵当汤里没有炙甘草，而桃核承气汤里有。结
得更顽固，耗费的津液也多。下焦耗费津液越多，上焦就越缺津液，加之热不能下则上冲，
于是人就会有惊狂的反应。桃核承气汤结得轻是“如狂”，而抵当汤结得重是“发狂”。淤血结
得顽固，就要用到水蛭和虻虫这样的虫类药。水蛭就是水里吸血的蚂蟥；虻虫是吸牛的血的
牛虻。它们都是吸血的昆虫，吸血的昆虫有个特点，它们叮在身上，血就不会凝结，只能任
由它们吸。它们都能抗凝血，自然能散开已经凝结的淤血。它们的性味都是腥而微寒的，只
清解不滋补，一般在实证热证上运用较多，用于虚证寒证要合扶阳药。药店里现在那种大根
的养殖的水蛭，是水蛭的另一个品种，是不吸血的，不是那种吸血蚂蟥，所以用了也无效。

这一条还有个值得注意的地方，就是“表证仍在”。桃核承气汤和抵当汤都兼有表证，为什么
抵当汤不用桂枝，而桃核承气汤用呢？仲景可能考虑的是“热结膀胱”，膀胱经是络表的。所
以六经辨证体系在临证上也可以参考经络脏腑辨证。

125、太阳病，身黄，脉沉结，少腹硬，小便不利者，为无血也。小便自利，其人如狂者，
血证谛也，抵当汤主之。

前面说过，桃核承气汤是热结膀胱，那有没有小便不利呢？不一定，有可能利，有可能不利，
也有可能尿血。单一证状不能说明问题，要多条证结合来看。

这一条说有“少腹硬”，那就有可能是淤血证。

再看前后文，有“身黄”和“小便不利”，这是黄疸，所以这个少腹硬满应该是湿热结在膀胱，
不是血证。

如果腹部硬满，没有身黄呢？那就可能是血证了。那还有没有别的可能性？也有可能是宿食，
是承气汤证。于是又要找新的证据：承气汤证是谵语，是烦惊；血证是如狂，发狂。如果有
“狂”是血证了，这时候再参看小便，小便不利的有可能是热证膀胱，桃核承气汤证；小便自
利的是瘀热在里，抵当汤证。

这里讲的就是综合辨证的过程。

这一条说“如狂”是抵当汤主之。前面说过，桃核承气汤是“如狂”，抵当汤是“发狂”。为什么
这里又说抵当汤是“如狂”呢？可见读书不可死在句下，如狂、发狂其实是差不多的，措辞而
已，临证之时想截然区分也不太现实。说到底还是要对人体有理解，死抠字眼抠原文毕竟是
浅层的方法。

126、伤寒有热，少腹满，应小便不利，今反利者，为有血也，当下之，不可余药，宜抵当
丸。

抵当丸方 水蛭 二十个（熬） 虻虫 二十个（去翅足，熬） 桃仁 二十五个（去皮尖） 大
黄 三两

这里又再次讲通过小便来鉴别瘀血证。如果“少腹满”又“小便不利”，那就是水证；小便利呢，
那就可能是“有血”。

这里下血用抵当丸。抵当丸和抵当汤事实上是一个方子，一个为丸药，一个为汤剂。丸药一
般来讲要温和些，吃到肚子里慢慢消化；汤剂吸收快，要竣猛些。

为什么这里要用丸药呢。从条文来抠字眼可以这么理解：抵当汤是少腹“硬满”，这里是少腹
“满”，可见结的程度轻一点，毕竟抵当汤是竣下药，要慎重的，于是就改作丸药来用。

127、太阳病，小便利者，以饮水多，必心下悸；小便少者，必苦里急。

小便利有可能是水液不能气化出表，只能靠小便走。如果再饮水多，就会停饮于中焦，于是
心下悸。如果小便还少的话，那就更糟了，水结在下焦，就会少腹里急了。

至此，太阳病中篇就讲完了。从下堂课开始讲太阳病的下篇。

今天就讲到这里，谢谢大家。

== 2014-10-19（128-130）

今天我们讲太阳病下篇。

《伤寒论》不是按六经的顺序依次讲的，而是穿插讲的，也就是说在太阳病的上中两篇已经
涉及到全部六经的病了。如果是善于思考总结的人，已经能用全面的六经思维治病了。如果是
勤奋的人，将主要的方证记住，也可以做一个治愈率比较高的大夫了。好，现在开始讲太阳病
下篇。

128、问曰：病有结胸，有脏结，其状何如？答曰：按之痛，寸脉浮，关脉沉，名曰结胸也。

129、何为脏结？如结胸状，饮食如故，时时下利，寸脉浮，关脉小细沉紧，名曰脏结。舌上白
胎滑者，为难治。

太阳病第三篇的开头讲结胸。结胸是不是一个新的证？其实不是。我们之前有过一个类似
证，就是少阳病的胸胁满痛。它们的区别在哪里？其实就是位置。少阳病一般是胸满和胁痛，
痛的位置在胁下，这是肝胆经循行的区域；而结胸的痛是在心下，也就是胃及其周围的这个位
置，这是脾胃经循行的区域。在六经的归纳里，肝胆是属半表半里的；肺、大肠、脾胃是属里
的，于是，胁痛和心下痛在六经上也可以理解为半表半里和里的区别。

此二条讲了结胸和脏结的区别。

结胸是两个主证：

“按之痛” ，就是有痛感，里面有东西结住了，是实证。其次是“寸脉浮，关脉沉” 。这个脉
象很值得研究。一般胃也好，大肠也好，中下部有积滞，脉象的反应却不是尺脉浮，而是寸
脉浮。为什么呢？可以这样来理解，人体的循环是一体的，下面通了，上面的能量才能气化
出去，就好比农村的柴灶烧火，要想火能烧得大，就要把下面扒通；下面不通，自然寸脉就
会出现有表证的浮脉。 “关脉沉” ，关脉体现的位置在人体为中，脉沉说明病在里，关脉沉
说明病在人体中间位置的偏里。

一般来讲这种“痛”或“痞”的证，偏热的居多，所以胸胁满痛是少阳病的主证，不是厥阴病的
主证。如果有类似结胸的证，却没有热证反应，而是呈阴寒证的反应，那叫脏结。脏结是
“如结胸状” ，也就是说，按之痛这个和结胸是一样的；寸脉浮也是一样的。不同的是“饮食
如故，时时下利” ，胃口虽然还可以，却总是拉肚子，这是虚寒的腹泻，就是太阴证了。太
阴证应之于脉象就是“关脉小细沉紧” ， “小细”为津血虚； “沉紧”为里有寒。我们之前说
过，判断阴证脉象是最准确的。如果再“舌上白苔滑” ，这是脾胃湿寒很重，说胃气也坏了，
那就很难治的。脏结是很麻烦的病，临证上，诸如肝硬化肝癌胰腺癌胃癌的晚期常现这个证，
里面的肿块已经开始痛了，而脉象舌象又一派阴寒，所以连仲景都说“为难治” 。

这一条是书中第一次提到舌象，所以这里也顺带说下舌象的问题。舌象的反应有的时候是标，
有的时候是本，比较容易混淆。比如有时候舌尖红，再看脉证却是阴证，这样的情况很多；
有时候舌苔黄，却也不是热证。所以《伤寒论》里极少提到舌象。后世喜欢用舌苔的黄或白
来判断寒热，其实苔白和苔黄未必是热证的确证，舌糙舌老舌干舌体红（非暗红，是舌体而
非舌尖）更能证明热证；舌体娇嫩或湿滑或淡白则更能证明寒证。舌象用来判断水饮证和血
瘀证亦可借鉴：舌淡胖湿滑有齿痕一般是水饮，舌偏黯而有瘀斑一般是淤血。舌苔少或无或
地图舌一般是津血中气大虚之象。

130、脏结无阳证，不往来寒热，其人反静，舌上胎滑者，不可攻也。

所谓脏结，就是既有类似于结胸的痞结，又是阴证，那能不能攻呢？我们前面讲过，阴证是
津血虚的证，是不能攻的。问题是阴证只是个笼统的大概念，如果阴的程度并不重，在扶阳
救津液的前提下，还是可以稍微攻一下的。我碰到阴证的结胸和淤血证，就常常在干姜附子
的基础上加一点点黄芩大黄之类，一般黄芩不超过十五克，大黄不超过十克，效果非常好。
我曾经治过一个痔疮出血的，血出得很严重，辨脉偏阴证，我用了二三十克的干姜当归，加
了十克大黄，只吃了几剂血就止住了，痔疮也缩小了。我治晚期癌症，也经常扶阳药和攻痞
结的药同用。治病的首要原则是阴阳，也就是津血功能，是自体的免疫力，其次才能考虑攻
邪。那阴到什么程度就完全不能攻呢？那就是本条所说的了。

这里首先说的是“不往来寒热” 。往来寒热是少阳证，这是说不通的，有注解说“一云寒而不
热” ，我觉得应该是这个。只寒不热，只觉得怕冷恶寒，完全不感觉上火烦躁，这就很阴了
（阴证有烦躁，阴证有标热的情况是很多见的，这是人体亢奋起来生成津血和祛病的自然反
应） 。然后是“其人反静” 。何谓“反静”呢？前面说了，人体如果有淤堵，一般来讲是会烦
燥一些的，这是人体排病的自然反应，有时候脉很虚，却又很躁动，就是这个道理。这里有
脏结，人反而很安静，说明气血太虚了，一派纯阴之象，人体已经亢奋不起来了。 “舌上苔
滑” ，上面我讲过，舌苔腻滑是阴证。如果有以上这些情况，说明阴证很严重，那就不能攻
了。当然，判断阴证严不严重，还要参看脉象，尤其是尺脉的虚实。从这一条可以看出《伤
寒论》的辨证体系是必须要严谨，要有据可依的，不可只凭主观。

今天我们讲了结胸证的辨证，其实结胸证辨治原则也可以引申应用于一切痞结癌瘤。下次
课就讲结胸证的治法。今天就讲到这里，谢谢大家

== 2014-11-01（135-138）

大家晚上好。

今天接着讲结胸证的治法。

通过结胸证的治法我们了解一切人体的“实”证的治疗原则。所以非常重要。结胸证在《伤寒
论》里也是讲得非常的详尽的。

135、伤寒六七日，结胸热实，脉沉而紧，心下痛，按之石硬者，大陷胸汤主之。

这是一个完整的大陷胸汤的医案。

首先是“结胸热实”，说明是热证同时是实证。体内有形之淤堵都可以称实证，结胸是其中很
典型的。脉沉说明病在里；脉紧说明邪盛。有说脉紧主寒主宿食，可见其中亦寓淤堵之意。
“心下痛”，这个是大陷胸汤的辨证关键，必须有痛，而且是不按就痛。这说明淤堵得很厉害。
按之才痛的说明淤堵得不那么厉害，是用小陷胸汤。当然，不是所有的痛都可以用大陷胸汤，
还必须有“按之石硬”，才可以用大陷胸汤这样的猛药来攻。我们知道所谓四诊是望闻问切，
古人讲究礼仪，并没有把手诊列入四诊之中。其实，用手按压身体来诊病是很重要的。比如
柴胡汤证有胸肋苦满，有时候病人自己感觉并不明显，那就需要借助手诊，按病人的肋下和
肝胆经的循行路线，如果有明显的痛感，或是借助轻微捏挤和拍打病人便有灼痛感和青紫，
这也是可以证明的。承气汤证和瘀血证在临证上是必须要用手做腹诊的，如果手按腹部有抵
抗和疼痛感，非宿食即淤血。手诊在日本发展得比较好。我们现在的医生诊病摸个脉，再问
是什么病就开方子了，四诊都是不全的。

138、小结胸病，正在心下，按之则痛，脉浮滑者，小陷胸汤主之。

小陷胸汤方

黄连 一两 半夏 半升（洗） 栝蒌实 大者一枚

所谓“小结胸病”就是不太严重的结胸证。位置是正在心下，要按才会痛，不按不痛。“脉浮
滑”，这个在临证上是不一定的，里面有结实，脉未必就沉，当然更未必会浮；脉滑是解释
得过去的。

滑脉是血管里面的血来去如走珠，像珠子一样滑利。滑利说明有热，迟缓弦说明有虚寒。像
珠子一样里面鼓鼓的说明津液不虚，如果津液虚，就算要亢奋起来也只能是脉管亢奋起来，
形成弦脉和大脉，里面的血是鼓荡不起来的。现在来说说组方。因为结实并不严重，所以只
用黄连苦降，不用大黄芒硝甘遂来破下；栝蒌实是散结的；半夏有散结的作用，且能降水。
还是辛开苦破之法。

我们可以就柴胡汤、陷胸汤（丸）、承气汤做一个类比。小柴胡汤的满痛是在胸肋位置。胸
虽属太阴，位置却偏上，上为阳为表，是里往半表半里过渡的区域；肋偏三焦，是半表半里
的投射区域，于是辛开药用的是疏通半表半里的柴胡，以及能去胸满的枳实。苦降药是黄芩，
黄芩没有黄连苦，质枯空，性味比黄连轻。黄连和黄芩都是清半表半里之热的，黄连比黄芩
更偏向于走里一点。如果有里热可佐少量大黄而成大柴胡汤。小陷胸汤的结实是正在心下，
这个位置比里更偏上偏半表半里；比半表半里又要偏里一点，于是不用纯粹攻里的大黄芒硝，
也不用偏走半表半里的黄芩，而是用偏走里的黄连苦降。小陷胸汤和柴胡汤里都有半夏，半
夏散痰水之结和降水，性质偏温和，是适用的。栝蒌实味苦淡寒，主要是寒降的，兼有散结
的作用。大陷胸汤（丸）结实的区域从心下一直到少腹，位置更下，于是用大黄芒硝来攻。
因其结实更硬更痛，于是再加擅长破坚结的甘遂和葶苈子。承气汤是有宿食宿便结在肠道，
其痛在腹部，所以用攻里的大黄芒硝。再加去腹满的厚朴。枳实和杏仁类似，既宽胸也下气，
所以承气汤里佐有枳实，大陷胸丸里佐有杏仁。

栝蒌实这个药，历来都说宽胸理气——就此可以理气药做一个盘点，对比一下各自的作用。

先说厚朴，其气香温，其味厚而苦，苦厚走下，所以是除腹满，理下焦之气的。枳实是橘类
生涩的幼果，既香烈通窜又苦而破下，所以破气最速，既除胸满也通下焦。枳实常和厚朴同
用，一刚一柔。杏仁既香而散，又润而苦，性质柔和，也是既宣肺气也通下焦。柴胡兼具辛
凉温苦，性质平和，所以宣通三焦，寒热不禁。瓜蒌实味苦而淡，偏寒。苦淡寒这三种味道
都是降的。瓜蒌实还略具微香，能疏散宽胸，但绝不辛窜。所以是以降为主，以散为辅。其
整体作用是偏里而趋下的，但又没那么下，没到肠道，基本上是作用于中上焦的里。小陷胸
汤的心下就是这个区域。《金匮要略》里有个治心痛彻背的栝楼薤白半夏汤里也用到瓜蒌实。
由此可见，结胸证的用药还是以苦降破下为主的。

下面分享我刚治过的一则陷胸汤的医案。

曹某、男、29

正值降温，患者吹了风，又运动出了点汗，于是胃的区域隐痛，但又感觉不是胃。用手按能
摸到里面有清晰的痞块。患者除了有轻微大便不爽，人感觉无力不舒服，没有其它明显的证。
脉象不虚，却也不实，寸略浮大。

辨证：“按之痛，寸脉浮”，这是结胸证。按才痛是小陷胸汤的范畴。不按就痛是大陷胸汤的
范畴。大陷胸汤用药峻猛，而病人的脉没那么实，不按的时候也只是轻微隐痛。经方用药贵
在客观有据，兼而有之便兼而用之，但主次要分明，这种情况以小陷胸汤为主，加一点大黄，
兼用大陷胸汤之泻下之法。

处方：瓜蒌 30 黄芩 20 熟大黄 20

当时是晚上，药店已经关门，我手边只有以上三味药，缺半夏和黄连，黄连以黄芩代之。病
人只服了一剂半，痛感和里面的痞块便消失了，其它症状也痊愈了。小陷胸汤总共只有三味
药，这里缺一味，代一味，病人还是很快就痊愈了，可见中医的灵魂是辨证思维，而非药物。

在今天下课之前，我要向大家通报一件事情。我们的微信群已经上线了。这个微信群得以上
线，首先是因为我们这个qq授课平台得到了大家这么多的关注，让我看到我是有这么多和我
志同道合的朋友关注传统经方中医，关注《伤寒论》的医学思想。

我在刚学医的时候，有中医界的专家曾悲观的说，中国真正的传统中医可能不足三百人，而
且年龄很大，每天都在流失。

现在光我们这里就有上千位传统中医的研究者。

对我而言，传播传统中医既是快乐，亦是善举。人生里最快乐的事情就是做自己喜欢的事，
如果有人跟你一起做大家喜欢的事就更快乐了。

我感谢在座的和我一起在这个公益平台里研究中医的人，我也感谢现在和我一起做现在这个
微信平台的人。他们都是来自于这个课堂。感谢他们不计时间，也没有金钱报酬，来做一件
公益的事情。

我们的 微信平台主要是在生活和实践层面来阐释和传播真正传统中医的思想。让更多的人
能接受真正的医疗养生观念，接受真正的中医。请大家多多转发。我们在这里研究中医是善
举，传播中医亦是善举。感谢大家。稍候夏群主会将微信平台的具体添加方式告诉大家。

今天的课就讲到这里，谢谢。

== 2014-11-07（141）

今天是立冬。秋天结束了，冬天来了。在五行上，秋属金主肺，冬属水主肾。这个大家都知
道。那为什么秋主肺，冬主肾呢？有人会说，《黄帝内经》就是这么说的，还要问为什么吗？
当然要问。我们研究《易经》是了解天地运行的规律，我们研究医学研究《内经》就要了解
人体内部的运行规律。我们养生也好，行医也好，如果不了解人体运行的规律，知其然不知
其所以然，怎么能解决人体的问题。我们知道，夏天天地阳气上升，人体多汗，气血行于表，
毛孔是打开的。体表热，体内寒，夏天要少食生冷多吃姜就是这个意思。秋天天地阳气降敛，
人体气血也往内走，于是毛孔关闭了，汗少，肺通皮毛，毛孔不开了，肺的压力就大了。体
内的能量也没有出路了，所以秋天肺热的，胸闷的，咳嗽的，上火的很多。冬天呢？天地之
气闭藏，敛于最深最下之处，这就是肾的位置了。肺的压力随之减轻了，由肾来闭藏精气。
以前讲，立冬前后要吃饺子贴秋膘，这是顺应自然为冬天的寒冷做准备。但是我要提醒北方
的朋友，现在有了暖气，事实上整个冬天是初秋的温度。所以很多人到了冬天胸闷，尤其在
暖气房里，出去吸口凉风就舒服了。所以我建议有暖气的朋友，贴秋膘会让你上火，冬天会
烦躁失眠，还是应该清淡。

冬天气血行于内，养五脏，犹如树养根，如果还是二十几度，等于没有冬天，必定五脏失养，
气血亏耗。所以冬天暖气不是好事。我的习惯是暖气关小，室内温度十五度以下。其实最好
是不要高于十度，否则是违逆自然戕害性命的事情。这样做家里人会反对我。所以没法操作。

闲话少说，下面进入《伤寒论》条文学习。

141、病在阳，应以汗解之，反以冷水噀之，若灌之，其热被劫不得去，弥更益烦，肉上粟
起，意欲饮水，反不渴者，服文蛤散；若不差者，与五苓散。寒实结胸，无热证者，与三物
小陷胸汤，白散亦可服。

文蛤散方

文蛤 五两

上一味为散，以沸汤和一方寸匕服，汤用五合。

五苓散方

猪苓 十八铢（去黑皮） 白术 十八铢 泽泻 一两六铢 茯苓 十八铢 桂枝 半两（去皮）

上五味为散，更于臼中治之，以白饮和方寸匕服之，日三服，多饮暖水，汗出愈。

白散方

桔梗 三分 巴豆 一分（去皮心，熬黑研如脂） 贝母 三分

上三味为散，内巴豆，更于臼中杵之，以白饮和服，强人半钱匕，羸者减之。病在膈上必吐，
在膈下必利，不利，进热粥一杯，利过不止，进冷粥一杯。身热皮粟不解，欲引衣自覆，若
以水潠之洗之，益令热却不得出，当汗而不汗则烦。假令汗出已，腹中痛，与芍药三两如上
法。

“病在阳”，就是太阳病，应该以汗解，却用冷水喷面，以冷水浇身（“噀”为喷面，“灌”为浇
身），身体的热量被冷水劫夺走了，病反而更不能去了。于是更觉得烦躁了，这是表不解，
水热上冲之烦；皮上有粟米一样的凸起，也就是鸡皮疙瘩，这是汗愈出而不得出。

“意欲饮水，反不渴者”，这句有两种理解方法：

一是想喝水，却又不是很渴，说明虽有烦，里热证却不明显；二是渴欲饮水，却又不是很渴，
饮水不多。

若做第一种理解，应该用大青龙汤，解表加去烦；若烦热不重，麻黄桂枝各半汤亦可。做第
二种理解，应该是五苓散，五苓散是治中焦有饮又渴欲饮水。后面也说了，若服文蛤散不愈，
可以用五苓散。这里用文蛤散，是不对的。关于文蛤这味药，胡希恕先生曾经详细考证过，
下面引用两段胡老的观点：

“文蛤这个药，《医宗金鉴》说是五倍子，五倍子古人叫文蛤，说得也有理。《医宗金鉴》
说实验用过，文蛤治不了消渴，用五倍子反而有作用。有些人认为，牡蛎这个药可治渴，文
蛤也能治渴，是海物的东西都治渴。不过《医宗金鉴》说实验过，这个做个参考。我实验过
五倍子，治消渴没多大作用，还不如牡蛎、花粉。花粉牡蛎散都治渴的。在《金匮要略·百
合病》里有，叫栝楼牡蛎散。专用文蛤并不理想，五倍子我试过效果不好，作个参考。真正
贝壳类的文蛤没用过，五倍子用过，不像《医宗金鉴》说的那么好用。我想牡蛎可以治渴，
文蛤也可以治渴。……文蛤散这个药就是解渴，这在《金匮要略·消渴篇》里这么说‘渴欲饮水
不止者，文蛤散主之。’文蛤咸寒止渴。此段‘意欲饮水，反不渴者’，怎么用文蛤散呢？当
然不是的。”

下面这句“寒实结胸，无热证者”不好理解。

我们知道，结胸是偏热证的，用药也是以寒下为主。何为“寒实结胸”呢？就是有结胸的证状，
却没有热证，所以是寒实，是寒水寒痰在里面凝住了，而非水热之结。

那寒实结胸和脏结有什么区别呢？寒实结胸虽无热证，津液应该是不会太虚少的，所以可下；
而脏结是津液虚少的，所以不可下。

后面说用“三物小陷胸汤”，“小陷胸汤”应该是错简，应该就是用三物白散。白散这个方子的
主药是巴豆。巴豆这个药大家很熟悉，不是因为常用，而是旧小说里常出现，做泻药用。在
从前巴豆是常用的药，现在很少用了。巴豆和寒下的大黄芒硝不同，它是热性的下药，所以
能治寒实。

巴豆这个药很峻猛，所以用得很少，只用一分，约合四克左右。而且不是全服，加上其它药
为散一次只服“方寸匕”，约为二克左右。近代有一种用法就是用巴豆霜。巴豆霜是将巴豆碾
碎，将其中的油用吸油纸吸掉，因为油的药力很强。这种用法比较温和，入丸药用量一般也
就是三克之内。巴豆还有个特点，就是服热粥可助药力，腹泻会加重；服冷粥则减药力，腹
泻就止。

桔梗这个药后世很常用，说用来宣肺止咳。后世论药太笼统，宣肺止咳的药何其之多，药性
也千差万别，岂可一言以蔽之。桔梗单味大剂量煎服会觉得胸闷、喉中拘紧，胃中顶而欲呕，
说明这味药是往上宣散的。桔梗微辛，可它不是很散，没有香味，不能走表。它的宣散偏向
于里的层面，所以用它来结于里结于上的痈脓，是治肺痈排脓的主药；也用它来治肋下刺痛。

贝母这味药现在价格被炒得很高，后世常用它治咳嗽。贝母的作用和桔梗有相似之处，其作
用有三：散结、排脓、祛痰。

我们前面学了热性的结胸，也就是水热之结的治法，大小陷胸汤。现在又学了寒实结胸的治
法，三物白散。后面还有别的类型的痞结症的治法。

这个痞结证在《伤寒论》里是论述很完备的一个系统。现在肿瘤类疾病这么多，这个系统要
好好学。

好，今天就讲到这里。谢谢大家。


== 2014-11-15（143-145）

下面进入《伤寒论》的学习。

我们知道妇科在中医里是专门的一科。很多疾病牵系到妇科，比如经期，比如妊娠期，处理
和治疗方法会不一样。到底有什么不一样呢？这里头的原则和原理又是什么？今天要讲的三
个条文就是讲这个原则的。

143、妇人中风，发热恶寒，经水适来，得之七八日，热除而脉迟身凉，胸肋下满，如结胸
状，谵语者，此为热入血室也，当刺期门，随其实而取之。

妇人在感冒的时候来月经，解释这种特殊的情况，是很能说明和印证一些人体运行规律的。

条文中说的先是发热恶寒，典型的太阳病。这时候月经来了。“得之七八日，热除而脉迟身
凉”，可以理解为感冒七八天后，不发热了，脉也由浮转迟了，身上也凉了。却出现了新的
证，“胸肋下满，如结胸状”，胸肋下面满，是少阳证。为什么说如结胸状？这是我前面说的，
结胸和胸肋苦满实质上其实是一回事，都是水热之结，只是结的位置和程度有不同。这时候
如果还谵语，那就是热入血室了。这个血室可以理解为妇人的子宫。

治疗方法这里说是刺期门，可见有少阳证。有谵语，是少阳和阳明合病，可以考虑柴胡剂合
桃核承气汤。

妇人感冒时来月经通常会由太阳证转为少阳证，因为表病时气血要往体表走去驱邪，而月经
来了，气血又要往里走去逐淤。于是气血两头难以兼顾，便在表里之间进退。气血在表里之
间进退正是半表半里少阳证的特性。这时候要以建中生津血为主，这样气血就可以两头兼顾
了，再辅之以疏通表里以驱邪，柴胡汤正适合这种功用。可见要理解经方首先要理解人体运
行原理，才能活学活用。

所以中国人主张经期和产后不能碰冷水，不能着凉着风，不能吃生冷，这都是很有道理的。
女性的生殖系统在修复的时候，如果着凉食冷，势必因为气血难以兼顾以至于坐下病。

西医之所以不提倡这些，是因为西医是研究局部病理的，它不研究人体整体能量场的运行和
协作关系。中医的灵魂是整体的治疗观，可惜现代中医的研究发展方向是向西医的局部观和
病灶研究靠拢。

144、妇人中风，七八日续得寒热，发作有时，经水适断者，此为热入血室，其血必结，故
使如疟状，发作有时，小柴胡汤主之。

中风七八日，已经快好了，这时候“续得寒热”，变成了少阳证，寒热往来。 所谓“发作有时”就
是像疟疾一样定时发作。

这时候月经正好断掉。月经停了，人体应该更能腾出能量去解决外邪，怎么外感的症状反而
会加重了呢？这是因为“热入血室”了，可见这个月经并不是正常的断掉，而是邪气陷进去了，
和经血一起结在里面了，经血下不来了，所以才会发生疟疾那样定时发作的忽冷忽热。这时
候要用小柴胡汤来治。

用小柴胡汤来治好理解，现少阳证当然用小柴胡汤。既然说了血结在里面了，为什么不用祛
淤血的药呢？

这就说明传统中医治病主要不是驱邪，更不是治病灶，而是着眼于人体整体的治疗，人体能
量有了，运行秩序恢复了，自然会自己去驱这个邪。换句话说，如果人体整体没有协调过来，
用药物强行去驱邪很难驱掉，就算驱掉了，也还会再次滋生邪气。

145、妇人伤寒，发热，经水适来，昼日明了，暮则谵语，如见鬼神状，此为热入血室，无
犯胃气，及上二焦，必自愈。

这种情况的前提和上面是一样，感冒和经期同时出现。这里证是阳明证，“昼日明了，暮则
谵语，如见鬼神状”，这几个证前面解释过多次，就不重复了。因为经期的缘故，这是“热入
血室”，也就是热与血互结，而不是承气汤的热与肠内宿食互结，选方的话可考虑桃核承气
汤和抵当汤。

如果不去使胃气和上二焦受邪，气血能集中力量在下焦祛瘀，就会自愈。

以上几条都是在讲外感和经期同时出现的情况怎么理解和处理，通过这几个条文我们可以分
析出气血的运行规律，哪里有邪气，气血就往哪里汇聚，去排那个邪气，这是人体的应激机
制。如果疏通不及，便会邪与气血互结而成实邪；而相对缺少津血空虚的地方，也会发生相
应的证状，比如谵语，这是大脑用兴奋在争夺气血。

有人问我，怎样才能领会到《伤寒论》条文后面的人体运行规律和组方原则？在初期只能是
笨方法——书读百遍其义自现。通过对原文的前后联系无数次的阅读理解比对，条文中的蛛丝
马迹就会渐渐清晰起来。比如以上这几条，读多了自然就能领会条文后面隐藏的人体规律。

脂砚斋评《红楼梦》有一句话：“草蛇灰线，伏脉千里”，意思是哪怕相隔一千里，只要灰上
面留有细微的痕迹，你也能知道这条蛇是从千里之外什么地方来的。我读《伤寒论》喜欢用
这千里伏脉的理解方法。

领会人体的运行还有一个方法就是打坐，通过打坐来内观。从医学上来讲，这是探究生命内
在未知层面的一种极好的方式。经络的运行，真气的流转都可以在打坐内观的时候感知到。

中医是实践学科，先切实的去研究去领会，再应之于临证，所谓进一寸有一寸的惊喜，当你
一步步看到自己的临证效果有提高的时候，当你以前不能治好的病现在能治好的时候，你就
会在心里和两千年之前的张仲景会心一笑。这就是学医的快乐。

好，今天就先讲到这里，谢谢大家。

== 2011-11-22（147）

大家晚上好。

《伤寒论》条文太多，我们每周只有一次时间上课，所以我尽量讲重要的方子和方证。

今天讲一个临证上运用很广泛的方子，柴胡桂枝干姜汤。

这个方子，去看那些伤寒大家的医案，比如胡希恕啊，刘渡舟啊，绝对是使用频率最高的方子
之一。

这个方子有柴胡是治半表半里的，有干姜是治偏阴证的，所以可以治半表半里偏阴的证。这种
证临床很多。很多医家将它归入厥阴方、

我认为它的寒热属性应该是少阳到厥阴的过渡方。下面进入条文。

147、伤寒五六日，已发汗而复下之，胸肋满微结，小便不利，渴而不呕，但头汗出，往来寒热，
心烦者，此为未解也，柴胡桂枝干姜汤主之。

柴胡桂枝干姜汤方

柴胡 半斤 桂枝 三两（去皮） 干姜 二两 栝楼根 四两 黄芩 三两 牡蛎 二两（熬） 甘
草 二两（炙）

这才是柴胡桂枝干姜汤的条文。

这是个运用很广泛的方子，很多经方家把它当做治厥阴病的方子用。所谓厥阴病是治严重的上
阳下阴，阴阳离绝之症的（正常的人体状态应该是上阴下阳） 。照这样来看，说这个方子治厥阴
病是不妥当的。我们可以对比后面厥阴篇的主方乌梅丸方来看。

乌梅丸方中有黄芩黄连清上热，有附子温下寒。黄连苦降最酷烈，附子温下升阳力最雄，这才
能翻转阴阳，治阴阳离绝。这个柴胡桂枝汤干姜汤虽然也有黄芩清上热，可黄芩较之黄连苦降
之力太轻；至于干姜，只是温中而已，谈不上温下寒。

所以这个方子并不擅长治上热下寒。从方中有大量的滋阴药敛阳药来看，这个方子还是治津液
虚的少阳证的，可以作为少阳证向厥阴证的过渡方来用。

我看过很多经方派的医案，用这个方子治典型的上热下寒收效是很缓的，有时候十几剂下去效
果也不是很理想。这个方子有桂枝，也可以理解为治津液虚偏阴证的太阳与和少阳合病。上一
个方子柴胡桂枝汤是治普通的少阳和太阳合病，紧跟着就是这个方子是治津液虚的少阳（或厥
阴）和太阳合病，从行文上而言也比较说得通。

来看条文。首先看“先发汗而复下之”这就是已经是指向津液虚了。

“胸肋满微结”这是少阳证。

“小便不利” ，柴胡证本来就有上下不通，津液不得下的小便不利；这里再加上津液虚，小便自
然更少了。

“渴而不呕” ，这里有上热，也有津液虚，渴会比一般的半表半里证更明显。呕为胃上逆，不呕
说明中焦痞塞不通并不严重，所以不用半夏消痞降逆。

“但头汗出” ，汗出是太阳中风证，单单是头有汗，是因为津液虚了，能量不能全面的达表，只
能头部汗出了。有外证，所以方中有桂枝。

“往来寒热，心烦” ，这是少阳证。

从病位上来说，这是以少阳证为主的，太阳证为辅的。所以有柴胡也有桂枝。从阴阳上来说，
是津液虚，且胃虚而有上热，所以有干姜甘草温中救津液，也有栝楼根黄芩滋阴清热。
这个方子有味新药栝楼根，也就是天花粉。用得比较重，用了四两。天花粉是阴润补津液。天
花粉合牡蛎就是一个止渴的经方，牡蛎是收敛浮阳的。

这里既有温中的救津液，也有清热养阴的救津液，说明这个方子是以津液虚为主治的。 初期的
厥阴证有时候口渴并不明显，可以将方子里的天花粉减轻，就可以治初期的厥阴证了。表证不
明显亦可去桂枝。

栝楼根是瓜蒌的根部，晒干了和山药一样，色白多黏质。色白则入肺，也就是入上焦；多黏
质则滋阴。这个药在经方里主要是用于虚热证的补津液，比如后面的痉病。 《神农本草经》
里对这个药的解释主要是三方面：消渴、烦热和补虚。后世的医书说这个药的寒凉作用类似
于石膏，只是多一个滋阴的功能，可用于阴虚证的解热。

柴胡桂枝干姜汤的条文就讲完了。下面通过一个我治过的病例，来分析下这个方子的应用。

李主任

病人自述有肝纤维化、脾肿大、血糖高、血粘稠。

刻诊：双脉弦缓硬，推动无力。肤色暗黄明显，舌质暗，有齿痕。怕风，肝区自感不适，夜尿
频繁，后腰怕冷。因为是官员，平时好几顿晚饭，胃感觉吃东西不太消化。问诊后，他屏退身
边的人，把老板椅上的衣服掀起来，椅子上砸得白色的木头都出来了，指给我看，门后有根棍
子，是他砸的。这叫狂躁症。

处方：柴胡桂枝干姜汤加味

柴胡 30 干姜 30 桂枝 20 黄芩 15 生牡蛎 45 龙骨 45 炮附子 15 茯苓 30 白术
30 白芍 20 当归 15 川芎 15 炙甘草 15 茵陈 15

没有口渴，去天花粉。脾肿大，舌齿痕，中焦有湿证，加苓术。有湿热，加茵陈。
有瘀血证，芍归芎。龙牡镇静收敛浮阳。

炮附子温下寒，治尿频。

效果：一周后，病人就说情绪稳定了，不砸了，夜尿次数减少。后来又多次诊治，基本上就是
这个方子为主方，加减使用过消肝脾肿大的鳖甲，疏肝理气的香附枳实陈皮。

因病人应酬多，很多生活习惯改不掉，主要是吃得滋腻饮水多的习惯，所以服药时间较长。后
来多次劝诫，讲明人体吸收水的原理，才改掉了多喝水的习惯。基本上如此断续服药调理将近
大半年。病人的体检报告出来，脾肿大消失、肝恢复正常，血糖血象也回复正常。

所以有时候喝水多也会出问题的。和这个病人也是做了很多思想工作，才说通。所以治病是不
容易的，不但要开药，还要帮病人找到生活习惯的问题，才能治好大病。

和这个病人关于喝水的问题，我有很详尽的关于人体运行原理的沟通，这个作为例子收入在
希彦馆今天推送的新文章里。希彦馆是一个传播传统经方中医思想的公益微信平台。比较通
俗，侧重养生和人体原理。是这个课堂的辅助。 是这个课堂的一些学生无报酬义务来做的
一个公益平台，所以感谢这个课堂。希望大家关注这个微信平台，也希望大家转发，转发也
是为中医尽一份自己的力量。

一会儿请管理员将微信平台的二维码发上来。好，今天就讲到这里，谢谢大家。

== 2014-11-29（149）

大家晚上好

今天我们讲一个很重要的方子，半夏泻心汤。

为什么说它重要呢，因为它所治的是我们这个时代最典型的病。什么病呢？虚火。准确讲就是
胃虚而有火。

我们这个时代，不运动；口腹之欲不节制；脑力过度开发，思虑多，思则伤脾，这都造成脾胃
虚。然后生活节奏快，压力大，熬夜，欲望多，这都造成有火，于是人人都说自己上火，上的
多数就是这种虚火。

虚火有些什么具体的病的表现呢？比方说经常烦躁；各种莫名其妙的炎症迁延不愈；比方说肠
胃总不好，比方说失眠，这都有可能是虚火。

好，下面进入条文。

149、伤寒五六日，呕而发热者，柴胡证具，而以他药下之，柴胡证仍在者，复与柴胡汤。
此虽已下之，不为逆，必蒸蒸而振，却发热汗出而解。若心下满而硬痛者，此为结胸也，大
陷胸汤主之。但满而不痛，此为痞，柴胡不中与也，宜半夏泻心汤。

半夏泻心汤方

半夏 半升（洗） 黄芩 干姜 人参 甘草（炙）各三两 黄连 一两 大枣 十二枚（擘）

此条第一句说本是柴胡证，误用了下药，如果柴胡证仍在，还是要用柴胡汤。

这说明在仲景的体系里是不管病的来路的，一切以自体当下的反应为基准，有柴胡证仍用柴胡
汤。那些以五运六气为基准的流派，为什么治病效果不理想，就是因为忽略了人体的反应，对
人体认识很含糊，却过度的在外因上做文章。我们治的毕竟是人体，药治不了天地。

有柴胡证用柴胡汤，就算之前用过攻下药，也不算逆治。服要后会“蒸蒸而振” ，这是阳气蒸腾
上来了，人会振作振动，津液重新驱邪出表，所以“发热汗出而解” 。误下后若出现“心下满而
硬痛”的结胸证，那就用大陷胸汤。如果只是满，并不痛，那就是痞，不能用柴胡汤，要用半
夏泻心汤。

这里着重说一下“痞” 。要把痞弄清楚，就要先说治痞的主方大黄黄连泻心汤。

泻心汤的药物组成是黄连、大黄这两味药。我们知道大陷胸汤里有大黄，小陷胸汤里有黄连。
那为什么大小陷胸汤里比泻心汤要多出杏仁、葶苈子、瓜蒌、半夏、芒硝这几味药呢？因为这
几味药都有疏散坚结的作用。为什么要疏散？是因为结胸比痞多一个痛的证。这说明，结胸和
痞都是水热之结，只不过结胸是更坚结的证，所以要用到大量的疏散药；而“痞”结得没那么
严重，所以只是以黄连大黄这样的苦降药为主。大黄黄连泻心汤中的大黄这一味药有一点疏散
作用，但还是以攻下为主的，其散坚结的能力不如芒硝。

此条文里说痞是“但满而不痛”就是这个意思，由这些用药的法度可推知这些药物在人体中的
具体作用。

这个半夏泻心汤治的又是哪一种痞呢？治的是有脾胃虚的痞。痞是结在心下的，也就是胃周围
的位置。痞是水热之结，而胃是又虚寒的。这不矛盾，这种胃虚寒，同时又有热有结滞的现象
在临证上是非常多见的。脾胃司能量司运化，因脾胃虚，人体的大循环受限，生淤生火很好理
解。

在这个方子里，用黄连是泻心汤的方义；因为脾胃虚，所以不用大黄，而用半夏来降逆。这两
味药事实上也有点小陷胸汤的意思，只是没有瓜蒌，不以散结为主。参姜草枣是治胃虚寒，也
是救津液的。

刚才顺带说了半夏泻心汤、大黄黄连泻心汤、陷胸汤的区别。现在再说说半夏泻心汤和几个柴
胡汤的区别。

半夏泻心汤所治以呕、利、痞为主证的。呕和利是胃肠的反应，也就是里的反应。痞是结在心
下区域，也是偏向于里的反应，所以，泻心汤治的是偏里的，只是依寒热虚实的不同，有单纯
的三黄泻心汤，也有加了建中药的半夏泻心汤。

柴胡汤的胸肋满痛，其实质也是痞结，所以柴胡类方里也有黄芩大黄这样的去痞的药，以及半
夏、枳实这样的散结的药。柴胡汤也有胃虚，所以有参姜草枣这样的建中药。那小柴胡汤和半
夏泻心汤最重要的区别是什么？

最重要的区别只是一味柴胡。如果去掉柴胡，小柴胡汤和半夏泻心汤的药基本上就是一回事了。
柴胡是疏通半表半里的，疏通三焦表里的。这就说明，柴胡汤和半夏泻心汤相比，只是多了诸
如发热、往来寒热这些所谓的半表半里的外感证，所以也就多了柴胡这一味药。
从这些药与证的变化之法度中，我们就可以明白这些药在人体当中的各自的具体作用，将药物
和人体的病理规律解读清楚了，我们就可以突破方证相对的束缚，可以开始尝试运用经方的组
方规律来运用药物自由组方了。

所以，只要我们以务实的态度，以人体的立场来解读《伤寒论》 ，以《伤寒论》自身语境体来解
读《伤寒论》 ，而不是以《黄帝内经》里那些脏腑经络五运六气来附会《伤寒论》 ，我们就可以
破解《伤寒论》的组方规律。

今天就讲到这里，谢谢大家。

== 2014-12-06（151-153）

大家晚上好

我一开课的时候就讲过，我们这次《伤寒论》的讲座是破解《伤寒论》方证背后的人体运行规
律，是破解经方的组方遣药规律。

不知道大家注意到没有，我比较注重讲解每一种证，每一个方剂背后的人体运行规律。这不是
我的独创，

这是张仲景的方法，张仲景在《伤寒论》了不谈那些金木水火的玄虚，只是将道化于术当中，
谈的都是实实在在的人体反应 比如汗出体痛呕烦之类。

而后世中医，于人体实际是模糊的，于玄虚玄奥一个比一个高深。我只是以仲景之法为法而
已。

仲景没有讲方证后面的人体原则，等于只讲了招数，没有内功心法。如果说我还有所裨益的话，
就是破解了一些这样的原则。

今天我将要讲的这两条会就是解释这些原则的。

151、脉浮而紧，而复下之，紧反入里，则做痞，按之自濡，但气痞尔。

“脉浮而紧，而复下之，紧反入里，则做痞” ，这是说有脉浮紧的表证，下后邪入里，于是形成
了痞。这个痞有所不同， “按之自濡，但气痞尔” 。要解释这个情况，就需要和前面的痞证来比
对分析一下。

对不起，刚才网络中断了。

大陷胸是痞硬，不按就痛；小陷胸是痞硬，按才痛。这两个可以理解为已经结至坚硬，才会
有硬和痛。

大黄黄连泻心汤只是痞，没有按痛，但是有满。这个只是水热之结，没至坚硬，所以不痛。半
夏泻心汤痞结的程度应该和这个也一样，只是同时有胃虚寒。

本条说里有痞，但“按之自濡” ，就是按起来不但不满，还是软的。于是这个说了个“气痞” ，
就是水和气的结，并没有热。我们知道热证一般都容易胀、硬、痛；如果是伤口，热则会有红
肿化脓；有风热证的人头会肿大，厨师为什么都头大，因为天天对着火和油烟。这里是软的，
说明没有热，只是水和气的结了。那用什么方子呢？后面的《金匮要略》里有一个枳实白术汤，
就这两味药，治“如旋杯”的痞结，就是身体里面有个东西，从外面能摸到，摸着像盘子一样，
光滑有形状，但又没有感觉，不满不结痛，这就是气痞。枳实破气，白术燥湿。这种情况看起
来好像很严重，其实就这两味简单的药就能治好。

很多人惊叹于经方经常能用简单的药治好很复杂的病，又参不透背后的原理，于是说古方学究
天人。其实如果真正参透了人体的规律，参透了药在人体里面的具体作用，你也可以组出这样
的方子来。

153、太阳病，医发汗，遂发热恶寒，因复下之，心下痞，表里俱虚，阴阳气并竭。无阳则阴独，
复加烧针，因胸烦，面色青黄，肤瞤者，难治；今色微黄，手足温者，易愈。

讲到这里，我想插一句， 《伤寒论》里很多条文都是在讲误汗和误下之后的处理方法。

这至少说明两个问题：其一，从当时的医生都喜欢用汗下之剂可以看出，当时医学的主流应
该是顺应人体自己的排病模式来治病的，没有像后世那样搞出那么多以药治病的方法和药物；
其二，张仲景解释误治很多，解释常态的辨证并不多，甚至没有专门解释六经辨证体系为何，
说明六经体系在当时是常识，无须特别解释。从这两点可以看出，汉代的医学并不混乱，至少
在顺应人体的治病思路和六经辨证体系上是有普遍共识的。

《伤寒论》其实并不难读，它是最实在最简明的医书，简明到都是人体实实在在的反应，以及
根据这些反应做出的处理方法，都是可模拟可操作的，没有一句玄虚之词。

为什么这样简明的医书现在却成了难以参透的天书呢？因为我们现在的医学理论变混乱便复
杂了，反倒背离了最本源的东西。医学是实践的学问，当医学越来越不能治病的时候，我们
回过头来发现原来汉代的医学那么简单，那么有效，于是像我们这样的觉悟者重新来追寻汉
代的医学，来破解上古的经方。

此条第一句讲的是不该发汗的时候发了汗，感冒没有好，变成了发热恶寒的局面；不该用下药
的时候用了下药，于是心下痞，且表里阴阳都虚竭了。没有了阳气，阴就变成了孤阴，孤阴不
长，这是很危险的局面了。又去用烧针针灸，这是强行的调动阳气。

这里顺便说一下针灸的原理为何？这里只讲人体的运行原理，当人体受到伤害和刺激的时候，
气血就会往那里汇聚，这是人体的的自保应激机制，所以受伤了会胀会红会肿。针灸事实上就
是通过这种原理人为的在调集和引导能量，用这种方式来打通经络，打通人体的循环，达到治
病的目的。六经辨证体系的汤液学也是用药物恢复人体的能量平衡和循环，而非以药治病。所
以真正的汤液学和针灸本质上是通的。

用了烧针之后，就是烧过的针来扎，人体发生了胸部的烦热，这是人体在努力的生成能量，所
谓血虚化燥就是这个道理，如果血不亢燥起来，怎么加速生成？

如果面色青黄，皮肤跳动，就很难治。因为面色青是肝的本色，面色黄是脾的本色，说明肝
脾都很衰弱了。皮肤跳动，这是在调集津血，说明津血已经很虚少了，不足以供养皮肤了。我
前面说过，类似于烦躁、惊狂、战栗、抖动，这都是人体调集津血的应激功能。为什么我们遇
冷的时候会寒颤？

因为人体要用这种方式迅速调集津液到体表。为什么我们撒尿的时候也会寒颤，因为排尿时能
量迅速下行，上部能量不够了，就会用寒颤的方式往上往表调集能量。容易抖腿多为中年人，
因为肾气虚衰了，就要用抖腿的方式往下部调集能量。

前面的课里说过，下焦有淤血，人就会有“发狂” 、 “如狂”的反应。这里包含前面说的两个原
理：一是人体有应激机制用能量去化这个淤血，因为淤血为失去活性的血，等同于异物刺激；
二是下焦牵制了能量，到达头部的能量少了，人就会用发狂这样极端激动的反应往大脑调集能
量，这也是一种应激自保机制。人体的就是这样来回的在寻找平衡。所以很多精神病抑郁症，
以及神经官能疾病诸如帕金森、美尼尔之类，要从淤血，从脾胃津液论治。

有人可能会觉得这个解释太直白，不像别人说的那么高深玄奥。但我们静下心理性的体察和领
会我们的生理，人体是不是就是用这两个原则在时时刻刻的防御和平衡呢？《伤寒论》之后的
两千年，医学典籍都停留在谈玄说奥的层面，只有《伤寒论》里是实实在在的人体反应。只有
实实在在的参透《伤寒论》里人体反应背后的人体规律，并且用顺应和协助人体排病之势的思
维去思考如何治病的时候，才是真正认识医学的开始。

今天就讲到这里，谢谢大家

== 2014-12-21（155）

伤寒经方求真群， 《伤寒论》公益讲课

有请刘希彦老师

大家晚上好。

今天讲附子泻心汤。讲了这个方子，关于痞结证的方子就讲得差不多了。

伤寒论没有专门讲治癌的，当时也没有这个名词。其实关于结胸和痞的治法里面包含癌肿类疾
病。

所以今天在讲完方子会专门讲下这个问题。

155、心下痞，而复恶寒汗出者，附子泻心汤主之。

附子泻心汤方大黄 二两 黄连 一两 黄芩 一两 附子 一枚（炮、去皮、破，别煮取汁）

对于后世的中医理念来说，这是无法理解也无法解释的一个方子。三黄是大苦大寒大破之药；
炮附子是至阳至热之药。它们怎么能搁在一起呢？

用《伤寒论》的理念来解释，它们是不矛盾的。我们还是回归到人体来讲这个问题。

当体表有邪气的时候，就会发生太阳病，太阳病事实上是通过发热的方式将津液汇聚于体表来
排病。这个体表之水热一旦陷入，就有可能在体内形成痞。痞的实质是水热之结。

有形之痞结形成后短时间是很难有变化的，而病本身有可能会传变，也许会从三阳病变成三阴
病。痞一旦产生之后，人体的应激模式就要消耗大量的气血去攻这个痞，如果人体的津血并不
是很充足的话，也会因此渐渐陷入虚证。

如果这个虚主要表现在脾胃上，出现呕利这样的证状，那我们就用半夏泻心汤，参姜草枣健胃
建中，芩连去痞；如果这个虚表现在表，就是本条说的“恶寒汗出” （这里应该是怕冷而出虚汗
的意思） ，我们前面学过，治表阳虚汗出的是炮附子，于是就有了这个附子泻心汤。

这就有一个问题，如果人体已经虚寒到要用附子来温阳了，那这个痞还有可能是水热之结吗？
当然有可能。所谓痞，通俗的说就是一个结块，是一个自我封闭的不容易和外界交通的东西。
若能与外界交通了它也就自己消散了。所以痞的属性不会因为外面的环境而改变的。再者，津
液向痞汇聚去攻痞，这个局部往往是不会虚寒的，但它会造成其它地方的虚寒。于是水热之结
和表之阳虚有了同时存在的可能，攻痞的三黄也就有了和附子同时存在的可能。

那脏结又是什么呢？脏结其实也是一个痞。前面说过， “病发于阳，而反下之，热入因作结胸；
病发于阴，而反下之，因作痞也。 ”也就是说，三阴病也有可能形成痞。先是三阴病，然后形成
痞，那这个痞一般不会是水热之结，有可能是寒实，也就是水寒之结。这个寒实也可以下，用
巴豆这样的温药下；还可以有用附子细辛大黄汤来下。

有人会问，不是说脏结不能下吗？《伤寒论》里没有说过脏结不能下，只是说过“脏结无阳证，
不往来寒热，其人反静，舌上胎滑者，不可攻也。 ”这里既然说脏结在虚寒情况下不可以攻，言
下之意是病人没到那么虚寒的话是可以攻的。其实，原则上阴证是不可以攻的，但不太严重的
阴证则是可以攻守兼施的，此所谓变通之道。本条只是虚到“恶寒汗出” ，并没有虚到四逆和人
静苔滑的程度，所以结合温阳药还是可以攻的。

至此，结胸、脏结和痞的基本原理和治疗原则就都讲了。

我们可以就此来谈谈癌症的问题。癌症事实上就是身体里面的一个结。既然是个结，不管结在
什么位置，都有可能是结胸、脏结和痞这三个类型。

如果是结胸和痞的类型，我们是可以攻的。这个攻不限于陷胸汤，因为陷胸汤主治中焦；如果
发生在大肠，可以用大柴胡、承气汤之类的方子来攻。我用大柴胡合散结化瘀药治过大肠癌，
效果非常好，病人服了有持续的缓泻，但越泻精神越好。这是因为结滞去了，被牵制消耗的气
血少了，精神反而好了。

网上盛传的一个治消化道癌症的神方（铁树叶、白花蛇舌草、大枣三味合方） ，前两味药是偏寒
凉的，能散热结化痈脓，碰上偏热偏实的癌症，药力虽然不如硝黄迅猛，久服是会有作用的。
如果是脏结的类型，气血不太虚的话，我们也可以攻，但要结合温阳建中药来攻。如果病人津
血太虚，那就不要先急着攻，先温阳，等阳回津复再攻守兼施，也就是温下之法，大黄这类的
攻下药和温阳药结合来用。

我治过一个肝癌晚期的病人，末期肝疼已经疼了三四个月了，已经被医院退回来了。周身黄疸，
面色发黑，也就是到黑疸的程度。 《金匮要略》里说过，黑疸本身就很难治，别说还是晚期肝癌
病人。病人脉弱，别人穿衬衣，他穿毛衣，明显是阴证，只是胃气尚存，食欲尚好，勉强可攻。
我用大剂量的附子干姜和小剂量的攻下散结药治疗一个月，病人全身退黄，眼球恢复白色，还
带人上山砍了一车树亲自运到邻县去卖了，当初来就诊的时候连走路都走不动了。

有人会说，老师你在讲到病的时候从来不出方子，是不是留一手。其实讲辨证和药理就可以了，
你就可以用这套理论根据具体情况去组方子。方子是随证而设，因人而异的。我就算贴一个方
子放在这，也只是个案而已，不能施之于所有人。若有人拿这去治所有人的肠癌，可能会治好
一些，也会耽误很多人。《伤寒论》讲的是治理人体，治理人体各种失衡的局面，而不是讲治病。人体治好了，病也就
自己好了；人体治不好，用再多药去治病也不会有效果。人体失衡的方式就这么几种， 《伤寒论》
里基础方也就那个几个，药也就是常规那么几十味，临证去化裁组合就好了。此所谓辨证施治，
而非辨病施治。后世好以某药治某病入手学医，起手就低了，疗效自然不会好。

好，今天就讲到这里了。欢迎大家加入传播古中医理念的微信平台——希彦馆。

谢谢大家。

== 2014-12-27（157-158）

伤寒经方求真群， 《伤寒论》公益讲课

有请刘希彦老师

大家晚上好。

前面讲过一个半夏泻心汤，说是治我们的时代病。我们这个时代运动少则脾胃不运，思虑多则
克伤脾胃，贪口腹之欲则脾胃负担重，因此多数人的脾胃是虚的；加之欲望多且喜熬夜，便会
有虚火。

火盛于上，元气虚于下，便会上热下寒，阴阳逆乱。这种情况便有用半夏泻心汤的机会。接下
来讲的两个方子是半夏泻心汤的变化方，和半夏泻心汤合称三泻心汤。

157、伤寒，汗出解之后，胃中不和，心下痞硬，干噫食臭，肋下有水气，腹中雷鸣下利者，生
姜泻心汤主之。

生姜泻心汤方

生姜 四两 （切） 甘草 三两 （炙） 人参 三两 干姜 一两 黄芩 三两 半夏 半升（洗）
黄连 一两 大枣 十二枚（擘）

此条的证状是汗出表病解除之后出现的，应该是发汗太过了，伤了津液和胃气，表病并没有真
正的去，而是内陷了，于是“胃中不合，心下痞硬” 。

下面说“肋下有水气” ，这个“肋下”在这里有些难解。因为后面说的是腹中雷鸣和腹泻，可见
这个水气应该在肠道。这个“肋下”疑是错简。

这个方子和小柴胡汤很接近，之所以没有柴胡就是因为没有肋下满痛这样的半表半里证。这也
能佐证提到“肋下”是有误的。这个方子是治以肠胃为主的消化道反应的，也就是治阳明区域。
我们已经基本熟悉仲景的组方规律，可以试着自己来辨证组方。

“胃中不和” ，是汗后津液虚所致，参姜草枣是适用的。

“心下痞硬”用黄芩黄连。

“干噫食臭”这是胃弱而上逆，是呕的类似证，用半夏生姜。

“腹中雷鸣下利” ，这个证以前没出现过，这里讲一下。腹泻这个证，如果有腹满痛、屎屁
多而臭、肛门灼热，一般来讲是肠中有热。在这里只是腹中雷鸣，没有腹满痛这样的承气汤
证，说明有热而不重。其实这个热是胃弱中焦痞结造成的，中焦痞结上下就不交通，上下不
交通，大肠里的水热就不能吸收和运化出去，于是淤而生热。首先是建中健胃，运化有了，
热也就去了。结合用黄芩黄连引热下行，辅助祛邪。有医家说，这个方子和半夏泻心汤比，
这个方子是偏向于治胃寒的，因为加了四两生姜。但是大家有没有注意到，还减了二两干姜，
半夏泻心汤的干姜是三两，这里是一两。要说温中，干姜还更合用。所以，这个方子应该是
偏向于治胃逆的才对，也就是这里说的“干噫” 。

方后的注解有“泻肝”的这样的说法，显然是后世医家加上去的。 《伤寒论》的原文里没有这样
的说法，仲景辨证分表里阴阳，而不取五行脏腑。

158、伤寒中风，医反下之，其人下利日数十行，谷不化，腹中雷鸣，心下痞硬而满，干呕心烦
不得安，医见心下痞，谓病不尽，复下之，其痞益甚，此非结热，但以胃中虚，客气上逆，故
使硬也，甘草泻心汤主之。

甘草泻心汤方

甘草 四两（炙） 黄芩 三两 半夏 半升（洗） 大枣 十二枚（擘） 黄连 一两 干
姜 三两

条文中说，病人一天腹泻几十次， “谷不化” ，大便里有未消化的食物，且“腹中雷鸣” 。同时病
人有“心下痞硬而满，干呕心烦不得安” ，这是胃虚的范畴。医生只看到了心下痞，没看到胃虚，
便用了攻下的药，于是痞更严重了。 “此非结热” ，意思不是单纯热证的水热之结，主要是因为
胃中虚造成的心下痞硬。

这种情况用甘草泻心汤。炙甘草干姜大枣温中建中，芩连去痞，半夏散结降逆。

这个方子是半夏泻心汤去了人参，将炙甘草增为四两。按照这个证情来说，增加炙甘草是对的，
严重腹泻，津液一定是大虚了的，人参也可以不去，很多医家用这个方子是保留人参的。
现在说一下半夏泻心汤、生姜泻心汤和甘草泻心汤的区别。

这三个方子都是主治呕、逆、痞的。也就是胃虚心下痞结造成的上吐下泻，上下不交通。若以
半夏泻心汤为基础方，如果胃逆明显，就减干姜，重用生姜，变化为生姜泻心汤。如果津液虚
明显，就用甘草泻心汤。

甘草泻心汤这个方子很有意思。后面的《金匮要略》里说可以治狐惑病。这个狐惑病主要的症
状是诸如喉、阴、眼、口等等身体粘膜组织的炎症和溃疡。据我的临床经验，久治不愈的炎症
上火，只要是有胃虚津液虚的，用这个方子是有速效的，往往一两剂便可痊愈大半。慢性腹泻
和胃病，往往是因为肠胃粘膜组织的炎症和溃疡，也是这个方子的适用范畴。

炙甘草有缓急迫的作用。这种阴火虚火往往有烦躁不安，尤其是溃疡类疾病，比如口腔溃疡，
兼有剧烈的疼痛。取甘草的甘缓之性，这也是增量炙甘草的另一个原因。

因为这三个泻心汤经常运用于治疗上热下寒，也有人把它归入厥阴类方的范畴。由此可看出，
运用经方重要的是明白人体运行原理，明白这个方子作用人体的何种失衡。这样才能灵活运用。
方证相对不是不可以，但势必局限了对经方的运用。

今天就讲到这里。欢迎大家加入传播传统经方中医的公益微信平台“希彦馆” ，关注和转发也是
为恢复传统古中医贡献您的一份力量。

谢谢大家。

== 2015-01-10（161-162）

十一月初六
十一月小
甲午年 丙子月 壬申日
生肖 马
一九第 6 天 日十二建 成西历 2015.01.10
农历 甲午年 丁丑月 丙戌日生肖 马

伤寒经方求真群，公益讲课。

有请刘希彦老师。

大家晚上好

前面我们讲过关于痞结的病，也就是身体长了个肿块的病，有两种基本情况。
一种是水热之结， ；一种是水寒之结。

水热之结用芩连硝黄来下，水寒之结可以用干姜附子合大黄来下。

如同时有胃虚，可以用半夏泻心汤，也就是脾四味合芩连夏。

那还有没有其它情况呢？还有一种就是气痞。也就是说这个痞结是以气为主的，当然里面一定
有水，但它的特点是还有气。就是我们下面要学的这个方子。

161、伤寒发汗，若吐若下，解后心下痞硬，噫气不除者，旋覆代赭石汤主之。

旋覆代赭汤方

旋覆花 三两 人参 二两 生姜 五两 代赭 一两 甘草 三两（炙） 半夏 半升（洗）
大枣 十二枚（擘）

吐下之后，心下痞硬。前面讲过这种情况是水与热结在了心下。这一条的证和前面略有不同，
就是有“噫气不除”这个证。老往上嗝气，而且嗝气后痞硬也不解除。这是水与气结在心下了。
看方子，参姜草枣夏，这五个药和半夏泻心汤一样。这是建中降逆的。半夏泻心汤里还有黄芩
和黄连两味药是降热的。这里换成了旋覆花和代赭石。因为这里是水和气之结，旋覆花是散结
气的。 《神龙本草经》谓“旋覆花，味咸、温。主治结气、肋下满、惊悸、除水、去五脏间寒热，
补中下气。 ”

代赭石是赤铁矿的氧化物，是铁氧化合而成的。金石类的药物一般都重镇降逆，引能量下行。
代赭石就是这类药的代表。后世的张锡纯善用此药，其用不外乎顶巅之疾、上盛上逆之疾。妇
人难产之际，急服此药，可顺产，我试过确实有验。此药重镇破关格之力由此可见一斑。
前面说过，对于痞结，经方用药是辛开苦破之法。这里的旋覆花主要是辛开，代赭石是破降。
代赭石没有芩连的苦寒，用在这里是合适的。

至此，痞结的几种主要类型就讲完了。

很多人认为《伤寒论》没有温病。其实是有的，伤寒之法是治人体的失衡的 ，而非病本身，人
体失衡的情况大抵就那几种类型，那方子也就那几个主方。

比方说热在下焦，承气汤类。热在上焦，如果有大热伤津的津液虚，白虎汤。

如果只是温病的外感病，比如肺炎，比如热伤风，还没有津液大伤的程度，就是下面这个方子
——麻杏石甘汤。

你看伤寒之法就是简明，后世的温病学无非是把其中的一个分支详细化。详细化是好事，可又
同时走向了辨证的含糊纷乱，和方剂用药的杂乱不明。这又是弊端。

下面讲麻杏石甘汤 。

162、下后不可更行桂枝汤，若汗出而喘，无大热者，可与麻黄杏子甘草石膏汤。

麻黄杏子甘草石膏汤方

麻黄 四两 杏子 五十个（去皮尖） 甘草 二两（炙） 石膏 半斤（碎、绵裹）“下后不可更
行桂枝汤”这句话的意思是，下后如果病不解，不一定都是桂枝汤证。如果“汗出而喘，无
大热” ，可与麻杏石甘汤。

我们前面学过“无汗而喘” ，这是因为没有汗，只能靠呼吸排解肺里面的能量和压力，汗出来就
不会喘了。这里为什么有汗了还会喘呢？这是因为肺里有热，有多余的能量，汗出了也不能完
全排解，必须要喘来帮忙。如果是热重以至于伤了津液的话，我们可以用白虎汤，这里热并不
重，所以只用麻杏石甘汤即可。此所谓“汗出而喘无大热” 。你看《伤寒论》的条文是极简极准，
也是极客观的，后面是实实在在的人体运行的原理。学《伤寒》 ，重在明白方证后面的人体运行
原理，方可活学活用，否则就只能停留在方证相对的阶段。

这几味药大家都知道了，麻黄是宣通的，能宣通人体孔窍，能解表，这都有助于帮助排热。杏
仁也是疏通宣肺的。石膏清热。甘草建中。

这个方子在小儿肺炎上运用很广泛，非典的时候也起过大作用。一般偏向于温热的感冒用它都
可以解决。那偏温热的感冒有什么证状呢？这里只说了个“无大热” ，没有更详细的证。
我补充下面几点：怕热，口渴喜冷饮或欲多饮，呼吸粗重，手指放在鼻孔上感觉出来的空气热，
屁多大便臭。我们知道，儿科为哑科，后面三点在辨别小儿感冒是热性还是寒性上很有用处。
小儿感冒一般热性的多，因为这是一生中阳气最旺的时候，食欲也旺，一天吃的次数很多，容
易食积。 《红楼梦》里太医给王熙凤的女儿看病就说，饿一两顿就好，不用吃药。其实不管大人
小孩，只要是偏热的感冒可以不用吃药，只要减食减肉，或者饿一两顿就能好。

关于小儿感冒这个问题，我推荐大家看一下我们传播传统经方中医的微信平台里的一篇文章—
—《中医妈妈的宝宝高烧实战手册》 ，使我们这里的一个同仁写的。

微信平台的二维码我发在下面——

今天就讲到这里了。谢谢大家。

== 2015-01-17（168-175）

农历 甲午年 丁丑月 丙戌日生肖 马
西历 2015 年 1 月 17 日星期六

伤寒经方求真群，公益讲课

有请刘希彦老师。

大家晚上好。

不知不觉开课到现在已经快一年了。

我想哪怕是初学的朋友也一定感觉到了， 《伤寒论》和后世的中医不太一样。
第一是药物少，学了这么多方子就是一二十样药在打转。
对于后世中医而言，有时候一张方子就有一二十样药。

《伤寒论》里的主方也就那么几个，其它无非是主方的加减化裁而言。为什么这个医学体系这
么简单呢？

因为这个体系不是治病的，是治人体失衡的，治病的是人体自身的免疫力。人体失衡的方式就
那几种，所以主方就那么几个。所以，能治病的医学未必复杂，大道至简嘛。

现在去一个药店，好几面墙的药，然后医生自己都说，中医不能治病，只能调理。

古时候真正的大夫，甚至不需要药店，一个药匣子背几样药就可以行医了，真正的行医。别看
只是一个药匣子，照样能治病，因为这里面有真正的医道。

闲话少说。刚才说《伤寒论》的主方就那么几个，无非变化加减而已，现在就来讲几个白虎汤和桂枝汤的变化方。

168、伤寒若吐若下后，七八日不解，热结在里，表里俱热，时时恶风，大渴，舌上干燥而烦，
欲饮水数升者，白虎加人参汤主之。

白虎加人参汤方

知母 六两 石膏 一斤 甘草 二两（炙） 人参 二两 粳米（六合）

上五味，以水一斗，煮米熟，汤成去滓，温服一升，日三服。此方立夏后立秋前乃可服，

立秋后不可服。正月二月三月尚凛冽，亦不可服之，与之则呕利而腹痛。诸亡血家亦不可与，
得之则腹痛。利者但可温之，当愈。

这一条好理解，都是热证。只是要注意一条，就是“时时恶风” ，恶风是津液虚，白虎汤就是治
热证加津液虚的，里面有粳米。人参是治渴的，只要是津液虚的渴，人参是寒热不禁的。

方后的服法里说，这个方子夏天可服，立秋后到来年开春都不可服。意思是这是凉药，天热的
时候才可以用。这话不对，应该是来的人加上去的。我们知道，人体气血的运行是顺应天地能
量场的运行的。夏天地上热地下寒，人体则气血运行于表，好出汗，表热而里寒；冬天地上寒
地下热，气血运行于里，表怕冷而里热。所以民间有冬吃萝卜夏吃姜的说法，姜能温里，而萝
卜能清解里面的滞热。夏天最常用的外感药藿香正气水也是温性的。

我们是治人体，不是治天地，怎么能天气热就下凉药，天气冷就下温药呢？要看人体的具体情
况是寒是热。以我的经验，冬天的感冒热证往往的比夏天多。况且，人体的内部情况也未必和
外界的环境一致，比方说北京的秋冬极其干燥，照样也会有很多湿症。所有这些话是不足取的。
这是一个白虎汤的变化方，所以大家看，变化加减也很容易，首先是白虎汤证，有大渴，加人
参，人参强阴救渴。

方法简单，药的作用也清晰，不像后世，一味人参说出无数的名堂，到了临证使用难免一团浆
糊。

下面说桂枝汤的变化方。

174、伤寒八九日，风湿相抟，身体疼烦，不能自转侧，不呕，不渴，脉浮虚而涩者，桂枝附子
汤之。若其人大便硬，小便自利者，去桂加白术汤主之。

桂枝附子汤方

桂枝 四两（去皮） 附子 三枚（炮、去皮、破） 生姜 三两（切） 大枣 十二枚（擘）
甘草 二两（炙）

上五味，以水六升，煮取二升，去滓，分温三服。

去桂加白术汤方

附子 三枚（炮、去皮、破） 白术 四两 生姜 三两（切） 大枣 十二枚（擘） 甘草
二两（炙）

上五味，以水六升，煮取二升，去滓，分温三服。初一服，其人身如痹，半日许复服之，
三服都尽，其人如冒状，勿怪，此以附子、术并走皮内，逐水气未得除，故使之耳，法当加桂
四两。此本一方二法，以大便硬，小便自利，去桂也；以大便不硬，小便不利，当加桂。附子
三枚恐多也，虚弱家及产妇宜减服之。

伤寒八九天，风和湿交集在一起，于是出现了身体疼痛，而且不能翻身，转身困难。这就说明
津液大虚，是阴证。再往下辨，不呕说明没有少阳证；不渴说明没有阳明证。再参之以脉象，
浮虚而涩，脉虚涩，阴证无疑；脉浮，表证未除。于是用桂枝汤去白芍加炮附子而成桂枝附子
汤。

加附子是因为阴证；去白芍是因为主证在肢体，而白芍是敛下的，所以减掉。如果大便硬，
小便自利，就要去掉桂枝，加白术而成去桂加白术汤。这个地方值得注意。我们一般说白术
去祛湿的，应该是小便不利才加白术，这里小便利为什么加白术呢？

可见认识药物不能从解决什么症状，治什么病去认识。白术我们前面说过，是气化药，气化的
是中焦这个区域；而桂枝呢，气化作用能达肌肉。肌肉属表，肾经络表，所以桂枝利水走肾。
白术气化能力弱，只能在中焦，让水饮在中焦运化，并无桂枝那样强的利水的作用。水饮运化
于体内自然粘膜组织能得到水的供应，所以白术也能治饮证和寒凝证造成的大便硬；水饮运化
至肌肉，则能将剩余能量经肾经和膀胱经两条络表的经络下行于膀胱而成尿液。这才是真正认
识药物的方法。药物在人体中只有一种能量场的作用，而那些所谓的祛湿利水只是这种能量场
作用引起的反应。如果只是去认识药物解决什么症什么病，就有可能误用药物，也会局限药物
的使用。只有认识了药物最本质的在人体中的能量场作用，才能理解经方，读懂《伤寒论》 。
这两个方子在关节炎、风湿、肌无力之类的肢体疾病上的运用很广泛。方后的注解说，这个方
子服用后身体会麻痹，会头晕，这是附子的作用，不要大惊小怪。准确的讲这是附子用对了中
病了的反应。我曾经做过试验，给一个正常人和一个阴证病人同时服用同样剂量的附子。阴证
病人有身体麻痹和严重的眩晕的反应，而正常人则没有这些反应，只是觉得有些上火。病好比
土堆，附子好比推土机，有土堆则有阻滞反应；没有土堆，推土机就顺畅的开过去了，反而没
有反应。

有一个刚刚查出晚期淋巴癌的病人，我在详细问证的时候得知，她在一两年前，吃附子理中丸，
比说明书上的剂量多吃了一丸，晕倒了，再也不敢吃了。附子理中丸那样的成药的附子含量是
极少的，吃了居然有这个大的反应，当时要是来找我的话，我一定知道她身体里面有大病。不
用等到两年后仪器查出来已经是晚期了。

注解里说，如果是虚弱的人或者产妇，附子不能用的太多。这是用药的一个原则，就是身体越
弱，最好轻药缓服，打个比方吧，烧柴火，越是火势弱的时候，越不能猛吹，得轻轻吹才越燃
越旺，吹猛了火反而烧不起来。人体就是这么简单，无非一个能量场而已。天地万物原为一理。

175、风湿相抟，骨节疼烦，掣痛不得屈伸，近之则痛剧，汗出短气，小便不利，恶风不欲去衣，
或身微肿者，甘草附子汤主之。

甘草附子汤方

甘草 二两（炙） 附子 二枚（炮、去皮、破） 白术 二两 桂枝 四两（去皮）

这个方子和前面的类似，我们把它当个医案来看吧。

“风湿相抟，骨节疼烦，掣痛不得屈伸，近之则痛剧”阴证湿证，肢体疼痛，附子、桂枝；
“汗出短气，小便不利”表证加中焦有饮，桂枝、白术； “恶风不欲去衣，或身微肿”桂枝。桂
枝证多，重用四两；其它皆用二两。再加甘草建中补津液。于是有了这个甘草附子汤。 《伤寒论》
所传授的就是这样灵活的变化组合之道。

这几条都提到一个“风湿相抟” ，抟是交集在一起的意思，何为风湿交集呢？风为表证，当表证
和人体的湿气互相纠结的时候，就会发生这样的情况。像皮肤过敏，湿疹风疹之类也是这种原
理。

好，今天就讲到这里。欢迎大家到安徽的秋浦书院来听我的公益讲座。也欢迎大家关注我们传
播汉传古中医理念的微信平台。

谢谢大家。

== 2015-01-31（177-178）

农历 甲午年 丁丑月 癸巳日 壬戌时
生肖 马
三九第 9 天 日十二建 定2015 年 1 月 31 日星期六

伤寒经方求真群公益讲座

有请刘希彦老师

大家晚上好

今天这讲就能把太阳病下篇讲完了。

太阳病上中下三篇，是伤寒论的主干。

因为伤寒论是穿插着讲六经病的。一般来讲，如果三篇真学到手了，应该已经是一个好大夫了。
别的不讲，外感病半剂一剂而愈应该是没问题的。

177、伤寒脉结代，心动悸，炙甘草汤主之。

炙甘草汤方

甘草 四两（炙） 生姜 三两（切） 人参 二两 生地黄 一斤 桂枝 三两（去皮） 阿
胶 二两 麦门冬 半升（去心） 麻仁 半斤 大枣 三十枚（擘）

这个方子用药驳杂，疑非仲景原方。条文也过于简单，只有一脉一证。

“脉结代”很多医家都认为是津液虚。熟悉《伤寒论》的都知道，真正的津液虚是要用附子的，
这里没有附子；况且津液虚的典型脉象应该是弱细脉。那这里的脉结代到底是什么意思呢？我
们可以从用药反推出来。

我们先看这里面用得最重的药，生地黄一斤，麻仁半斤。这两个药是祛瘀的。有人说生地黄是
滋阴的。其实我们平时说的生地黄是干地黄，干地黄既祛瘀也滋阴，这里的生地黄应该是新鲜
的地黄。新鲜地黄的祛瘀作用很强。阿胶和麦冬也是祛瘀和滋阴作用都有的药。桂枝增加气化
能力，也是能祛瘀的。

还有参姜草枣，这是建中补津液的药。桂枝是增强气化作用的药。

由此来看，这个方子所治应该是祛瘀为主，然后就是补津液。其侧重应该不在津血虚，因为没
有温阳药，如果真要温阳会用附子干姜，而且不能用那么多阴柔的药。何谓“脉结代”？下一
条有解释。如果真是因为津血虚成这样，那就很虚了，不是生姜和桂枝能解决问题的
所以这个“脉结代”还是以淤为主的，不是以虚寒为主。后面的煎煮法有用清酒煮，酒只是增
强升发之性。酒精一煮就挥发了，事实上没多少热性的作用。

“心动悸”是心脏的异常反应，所以这个方子在心脏病上运用得多。之前我们学过一个桂枝甘
草汤，只有桂枝和甘草两味药，这是治汗出过多，心脏带血不上产生而剧烈悸动反应的。所以
只用甘草补津液，桂枝增加气化，也就是增加心脏的带血能力。这里呢，显然是以淤血为主。
同时又有建中药；还有那么多滋阴药，又像是有阴虚阳亢。仲景组方治病的原则是抓主证，化
繁为简的思路，这里用药驳杂，理路含糊，所以不像仲景的原方。

但这个方子作为一个心脏病的基础方是可以参考的。心脏病的根源是血的问题，因为供血出现
了问题，所以心脏才发生一些变化来应对，心脏本身不会无缘无故的出问题。血的问题无非下
面两个方面：第一是血不足，这个建中就可以了；第二是瘀，血瘀、湿淤、寒淤、血液营养物
质富集而粘稠，都有可能导致供血不顺畅，进而影响心脏。这个方子在这两个方面都有兼顾。

下面说说几味新药。

这个方子很有意思，它把最有代表性的三样滋阴祛瘀药，麦冬、阿胶、地黄放在一起了。那我
们就来比对着分析一下这三样药。

首要这三样药煎出来都是黏滑的，我们知道有黏质能滋阴，其实黏质还哟一个作用，就是祛
瘀。何为淤？就是人体里面一些淤积的粘稠物质。据易理的同气相求原则，粘稠的物质能去
掉粘稠的物质，就像肥皂汽油才能洗掉油渍血渍一样。

麦冬微寒，色白，是入上焦的；它有一股轻升的香气，也是入上焦的，所以说麦冬能润肺化痰，
痰就是上焦呼吸系统里的淤积。

地黄微寒，色黑，味沉厚，是入下焦的。以祛下焦的瘀血为主。鲜地黄以祛瘀为主；干地黄，
也就是生地祛瘀和滋阴皆能；熟地黄，也就是蒸晒过的地黄，以滋阴养血的作用为主。

阿胶是驴皮熬的膏，性平，不寒不热，色红，微腥香。腥气是能祛瘀血的，所以祛瘀血它很擅
长。后世又称之为补血养阴的圣药，是因为它养阴的作用很中庸：既粘厚，能入下焦养肾阴；
又清香，能入上焦养肺阴。所以用途很广泛，是古代女性常服的滋补调理之品。

这三样药的共同之处是它们只有在人体有虚热，或者阴虚阳亢的时候才能起作用，因为这三样
药都是阴柔的。真正的热证不能用，哪怕偏寒凉的麦冬生地也不行，因为有滋养作用，用了如
同火上浇油；真正的寒证也不能用， 《伤寒论》论的大原则是从阳引阴，因为人是温血动物，本
身就是一个阳性的存在，真正的阴证只能用温热药来生化津液。至于在这两者之间的情况，我
们可以用这几样药合芩连石膏，或者合姜桂附来调节我们所需要的寒热配比。

麻仁就是火麻仁，我们都知道它能润肠通便，有油脂，有润下的作用，养阴的作用不大，主要
用于虚热的便秘，兼能去瘀血。

178、脉按之来缓，或一止复来者，名曰结。又脉来动而中止，更来小数，中有还者反动，名曰
结阴也。脉来动而中止，不能自还，因而复动者，名曰代阴也。得此脉者，必难治。

此条是讲脉象的。

脉按着来得就缓，说明津血虚，若还稍止再来，这叫结脉，就像绳子上打了个结，疙瘩了
一下然后又连上了。如果脉不稳定，有些躁动，又忽然停止，然后又很燥急，不仅打结，还摇
乱不定，这是很不好的脉，这叫“结阴” ，说明不仅是阴证，还很逆乱。如果脉会忽然中止，当
下这次的跳动没有了，然后用下一次跳动来替代它，这叫代脉。这也是阴脉，说明津血很虚了。
这是很难治的。

至此，太阳病的三篇就讲完了。下次开始讲阳明病。

欢迎大家关注传播经方古中医理念微信平台

二维码在下面

今天就讲到这里，谢谢大家。

== 2015-02-07（179-183）

十二月十二
十二月大
甲午年 丁丑月 丁未日
生肖 马
五九第 5 天 日十二建 破
西历
2015 年 2 月 7 日星期六

伤寒经方求真群，伤寒论公益讲课。

有请刘希彦老师。大家晚上好。

最近有很多新来的朋友。有我在秋浦书院讲课时守藏营的，90 后大学生加入了这里。

90 后来学习传承古中医，看来中医真的是有希望了。欢迎你们，

下面开始讲课。今天讲阳明病篇。前面三篇太阳病已经讲完。不过没关系，后来的朋友可以看
前面的讲义，群文件里有。

下面进入《伤寒论》学习。

辨阳明病脉证并治

179、问曰：病有太阳阳明，有正阳阳明，有少阳阳明，何谓也？答曰：太阳阳明者，脾约是也；
正阳阳明者，胃家实是也；少阳阳明者，发汗利小便已，胃中燥烦实，大便难是也。

这一章开始专门讲阳明病。

这一条讲的是阳明病常常和其它经的病同时出现。

太阳病有可能和阳明病同时出现。胃是个空腔是消磨和腐化食物的，脾脏是把胃消化的精华物
质向上输布的，然后糟粕下输于肠道。如果胃出现阳明证，也就是里面燥结，脾脏无津液可向
上输布，则可称之为脾约。太阳病发汗过多，消耗了胃中的津液，常常是发生脾约的直接原因。
这时候有可能会出现太阳病和阳明病同时存在的情况。

少阳病本来就有胃弱和津液虚，再加上少阳为上下不通，肠胃容易瘀滞，也容易同时发生阳明
病而大便不通。这种少阳阳明病，用我们前面学过的大柴胡汤来治。

纯粹的阳明病称之为正阳阳明。也就是说没有其它经的病和它并存。正阳阳明就是胃和肠里面
有积滞堵住了，也可以称之为里实。

需要注意一下的是，古人的胃不单是指胃，指的胃和肠两个器官。阳明的定义也包含这两个区
域。

180、阳明之为病，胃家实是也。

《伤寒论》中六经名字，我们知道主要指的是表里病位。这个表里的大层面是能涵盖脏器经络
的。从脏腑而言，肠胃属于阳明区域，所以条文中很多发生于肠胃的病，哪怕不是热证，也称
之为阳明病；脾属于太阴区域，发生于脾的病，哪怕不是寒证，亦称之为太阴病。因为脏为阴，
腑为阳。以此类推，膀胱属于太阳，肾属于少阴；胆属于少阳，肝属于厥阴。

在《伤寒论》里，如无特别解释，阳明病常规情况下指的是“胃家实” ，就是肠胃里的实证，而
且一般指的是实热证。

181、问曰：何缘得阳明病？答曰：太阳病，若发汗、若下、若利小便，此亡津液，胃中干燥，
因专属阳明。不更衣，内实，大便难者，此名阳明也。

问，为什么得阳明病？答，太阳病若因为发汗、泻下、利小便耗散了津液，那肠胃里面就会干
燥，会发生燥结反应，这就会发生阳明病。当然，这是从太阳阳明来说的。其实不管是何种原
因，只要是“不更衣” ，就是不大便； “内实” ，就是里面堵住了；总之只要是大便艰难，就是阳
明病。

182、问曰：阳明病外证云何？答曰：身热，汗自出，不恶寒，反恶热也。

问，阳明病发生时，身体的外部会有些什么证状？答， “身热，汗自出” ，这个不是因为体
表有寒邪而出汗排邪，而是因为里面有热，有淤积在肠道不能排出来的能量，要通过体表排
出来，所以要身热汗出。所以叫“汗自出” ，自己就要出汗。照这个原理，有时候发潮热的
人，出虚汗的人，也有可能是肠胃有积滞，只不过津血偏虚，所以只能一阵阵潮热，出汗也
是虚汗，不能大汗出。

“身热，汗自出”容易和太阳病混淆，于是又加了一个证， “不恶寒，反恶热” 。我们知道，太
阳病发热，同时是会恶寒怕冷的，而阳明的发热的同时还会怕热，不会怕冷。所以怕热是阳明
病的确证。如果再怕辨错，可以多问一句，怕热是愿意少穿衣服，还是脱了衣服又冷。如果是
不愿意多穿衣服，那就是阳明热证无疑。

“身热，汗自出”容易和太阳病混淆，于是又加了一个证， “不恶寒，反恶热” 。我们知道，太
阳病发热，同时是会恶寒怕冷的，而阳明的发热的同时还会怕热，不会怕冷。所以怕热是阳明
病的确证。如果再怕辨错，可以多问一句，怕热是愿意少穿衣服，还是脱了衣服又冷。如果是
不愿意多穿衣服，那就是阳明热证无疑。有的虽然感觉热，却穿得很多，这个就可能是虚热，
不是阳明实热。

183、问曰：病有得之一日，不发热而恶寒者，何也？答曰，虽得之一日，恶寒将自罢，即自汗
出而恶热也。

问， （阳明）病得的第一天，不但不发热，而且还怕冷，这是为什么？

这里的病指的是阳明病，古人竹简刻字不易，所以常用略文。我们知道阳明病是胃肠中有积滞。
人体的自保模式，那里有淤积和邪气，气血就往哪里走。所以肠胃中有积滞的时候，气血往里
去攻这个积滞，体表往往因缺少津液为感觉冷。如果这个积滞攻下去了，大便通了，津液回来，
体表也就不冷了；如果大便不通，那么里面的能量就要烧出来，于是就是后面回答的内容了，
恶寒很快就没有了，里面的能量试图往体表排，便发生自汗出和怕热的反应。

在临证上，很多轻微的阳明病，病人也会怕冷的，因为里面的热滞没那么重，没到烧出体表的
程度。这种情况医生往往容易看错。这就是要综合脉象，还有是不是口渴索饮，是不是喜冷饮，
是不是愿意多穿衣服，是不是呼吸有热感等证状一起来辨。

从这一条来看，辨证不是那么简单的，要整体的看待人体，越全面约好，不要被单一证状，单
一层面的问题所迷惑。要把人体从表到里的整个循环路径都排查清楚才能下结论，不然容易错。
所以《伤寒论》是真正的整体辨证法，是整个的思考人体之作为。学了《伤寒论》再去学后世
中医，就会发现片面和臆断的东西很多。

今天，我们深入的学习了阳明病的发病机理。真正学通了《伤寒论》就会发现，中医一点都不
玄奥，也不高深，都是实实在在的人体的机能和原理。这就是古经方中医的大道至简，易懂易
行，好学好用之处。

好，今天就讲到这里了，谢谢大家。

农历
甲午年十二月（大）建丁丑
十九

== 2015-02-27（187-197）

伤寒经方求真群，免费公益讲课

有请刘希彦老师

今天不好意思，我这边出了点状况，开始以为要停上了。

刚才又弄好了。所以，紧急通知群主告诉大家上课。实在对不起。

现在开始上课。

我们讲到阳明病了。

以前讲过很多，学伤寒要学到方证后面的人体原理和规律，否则不能活学活用，不能应之于
万病。今天我就集中讲几条阐释人体运行规律的。

187、伤寒脉浮而缓，手足自温者，是为系在太阴。太阴者，身当发黄，若小便自利者，不
能发黄。至七八日大便硬者，为阳明病也。

这里说的“伤寒”，说的是像伤寒病的外感。“脉浮而缓”，可见是有表证，脉不紧不燥无汗出
异常，可见表证不严重，手足也是温热的，这个病那就可能是在太阴了。

太阴属里，可以指里的阴证，也可以指属里的脾系统的病。脾主肌肉，主输布津液。人体是
这样，脾输布的是黄色营养，肝输布的是红色营养。脾的津液输布异常，身体当然就发黄了。
要是小便通畅呢，说明水液的输布是通畅的，那就不会发黄。如果到了七八天的时候，大便
硬结，那这这个病邪是在肠道里，那就是阳明病了。

在《伤寒论》的原则里人体自始至终是一个循环着的整体，有了这种思维方式，理解方药就
好办了。

191、阳明病，若中寒者，不能食，小便不利，手足濈然汗出，此欲作固瘕，必大便初硬后
溏。所以然者，以胃中冷，水谷不别故也。

阳明病，如果中寒的话，会吃不下东西，小便不利。从这里看，这个中寒应该是胃虚寒有水
饮的意思。胃属阳明，所以胃的病也可叫阳明病。

下面是“手足濈然汗出”，手足汗出这个证比较常见。后世的中医对于这个问题说阴虚，说血
热，说气虚等等的都有。以我的经验，这些情况倒也是有可能发生手足汗出，既然都有可能，
那就说明这些都不是唯一的原因，很有可能不是最根本的原因。

我们从人体循环来理解，汗出是向体表排邪气。为什么手足汗出严重呢？一定是体表排邪受
限，才会向手足排。大家可以注意观察一看，手汗的情况一般秋冬天比较多，秋冬天体表不
易出汗了，所以这样。秋冬天容易出现两种极端的情况：一是手足汗多；二是手足特别干，
皲裂掉皮，有时候红肉都露了出来。其实这里面的原理和中风和伤寒一样，一是汗多不解，
二是表紧不汗，都是人体在对抗邪气。如果手足干还发烧，而且有怕热的情形，这就有可能
是食积，这就是温病的范畴了，还有可能是淤血。你看这些道理都是一以贯之的。后世医学
说是阴血，里面有瘀滞消耗津液，阴血肯定虚。其实说阴虚还是现象，不过是内有积滞或淤
血产生的现象，后世医学这种以现象解释现象的说法容易丢失根本。根本原因还是要从人体
的大循环来理解。

我们往后看，就明白这里的手足汗出是什么原因。“此欲作固瘕”，固瘕是什么，不太好理解，
从字面上来解释，固是坚固，瘕是结块。后面说必定大便初硬后溏，因为胃里头冷了，水谷
不别了，也就是液体的和固体的不能消化融合了，一起送入肠道了，于是有的太稀有的又太
硬。这就容易形成肠道的结滞。那这个“欲作固瘕”作快要形成结滞结块讲比较妥当。所以还
是里面有积滞。这个初硬后溏也是个比较常见的证，说到底是胃虚造成的，临证上，胃虚而
有热更为多发这种证。

195、阳明病，脉迟，食难用饱，饱则微烦头眩，必小便难，此欲作谷疸。虽下之，腹满如
故。所以然者，脉迟故也。

“脉迟”，脉的推动力不够；“食难用饱”，吃不下东西，也容易饱。吃饱了就会烦，这是有热；
会头晕眩，有小便不利，那就是有湿了，湿而热会发黄疸，这是由阳明食积引起的，所以叫
谷疸。

这种胃虚的阳明病，哪怕是用了下药，一时解决了腹满的问题，还是很快会再次腹满的。这
种情况临证上很多见，如果脾气弱的话，攻淤血攻积滞，攻完了很快又会淤回来。因为脾胃
主运化，脾胃不能运化自然还要淤回来的。这就是为什么《伤寒论》很多大部分方子，哪怕
是攻淤的方子，只要有胃虚都有建中药脾四味。很多后世的中医方子里基本上没有姜草枣之
类，问他们为什么不用，他们说甘草大枣又不治病。在他们的观念里只有以药治病的思路，
此乃中医之大谬。

197、阳明病，反无汗，而小便利，二三日呕而咳，手足厥者，必苦头痛。若不咳不呕，手
足不厥者，头不痛。

阳明病，无汗，说明体表有闭阻，不能将热排出来，只能从小便来排热，所以小便利。

再过两三天，“呕而咳”，呕说明胃弱了，咳说明肺气也开始闭阻。“手足厥”是闭阻更严重了，
气血不到四肢末端，肘和膝以下厥冷，称之为“厥”。只要有里外循环的闭阻，不管热证和寒
症都可能发生“厥”。这样必定会头痛，因为邪热闭在了里面。

照这些证来看，有可能走到少阳了。少阳证的本质就是胃弱了，里外上下不交通。如果没有
呕、咳、厥的反应，说明没那么闭阻，头就不会痛。

现在来看，其实伤寒论里的人体规律一点都不复杂，都是一以贯之的，无非表里循环而已。
后世解伤寒就是总到不了这个最简单的地方，总讲得很复杂，什么五行经络五运六气都往里
面塞，他们也许认为越深奥就越正确吧，其实大道至简，学中国文化一定要明白，复杂就很
有可能反倒不对。

好了，今天这么晚了，就讲到这里了。不好意思耽误大家。谢谢。

农历
正月初十
正月小
乙未年 戊寅月 乙亥日
生肖 羊
八九第6天 日十二建 收

== 2015-03-07（207-209）

伤寒经方求真群，公益讲课。

有请刘希彦老师。

大家晚上好。

我们讲了这么久的课了，大家有没有想过，六经辨证的实质是什么？

实质其实是人体在通过表或里的途径排病。排之不出，于是有了证。

排出去了，我们就不会有感觉了，就像我们有时候受了寒，却并不感冒一样，这就是人体排
出去了。

所以，古经方医学最大的哲学基础就是，方药不治病，而是帮人体排病。

我们只治六经病，六经病就是三个排病渠道，表、里、半表半里，各分阴阳属性而形成的。
并不治具体的病，伤寒论里也从来没提到个一个具体的病的名字。因为我们我们只是协助人
体去排病而已。

这就是为什么伤寒论来来去去就那个几个方子，就那个几十味药，而且是常用药。非这些方
药是万用神药，是万病都要从这三个渠道排，这是道家思想的医学，顺应人体之作为，而非
自己妄自作为。能排病的只有人体自身，而非方药。

很多解《伤寒》的人，喜欢用方药治病这种逻辑去解释，这种脱离人体自身之作为的思路是
很容易误解误用经方的，疗效也不会很好。我解经方都是在说人体之作为，方证后面的人体
原理，这才是张仲景的语境和逻辑。你们学了我的思路，能更好的治病，不是我高，是仲景
高，也不是仲景高，是“道”高。汉代之前的医学都是道家思想的。

这就是回到了我第一堂课讲伤寒论哲学基础的时候讲到的问题。脱离了这个问题，用以药治
病的思路去认识中医势必走入小道，后世中医就是被这个思路带入误区的。

好，现在接着说阳明病条文。

207、阳明病，不吐不下，心烦者，可与调胃承气汤。

调胃承气汤方

甘草 二两（炙） 芒硝 半升 大黄 四两（清酒洗）

阳明病，“不吐”，说明没有少阳证，不在大柴胡范畴；“不下”，没有腹泻。只是心烦，这里
的心烦主要是指里有热，。单凭一个心烦可以确定里有热有阳明病吗？当然不能，前面已经
说过阳明病，必定有阳明病的脉和其它证，行文上不重复而已。我们不仅要学会读已有的文
字，还要学会读张仲景略去的文字。

心烦是津液虚的表现，所以用的是调胃承气汤，比大小承气汤多了炙甘草。炙甘草有温补的
作用，严重的热实之证是不适宜的，这里没那么热，没那么实，还有点津液虚，就可以用了。

大黄这里用的是四两，也就是六十多克，注解里有洗也有切，那就是生品。生品晒干重量要
减轻很多，常规来讲三斤鲜药材晒一斤左右的干药材。这里还有三升煮成一升，大约是三十
分钟的煎煮时间，不是现在习惯的后下，只煎几分钟。大黄里面有两种成分，一种是泻下的
成分，一种的收涩的成分。酒洗能减缓泻下之力，也能让药效更走下焦；煎煮时间长，泻下
之效减，收涩之效增。所以认识经方用药的剂量一定要考证清楚，不能一看剂量大就认为不
合理。

208、阳明病，脉迟，虽汗出不恶寒者，其身必重，短气，腹满而喘，有潮热者，此外欲解，
可攻里也。手足濈然汗出者，此大便已硬也，大承气汤主之。若汗多，微发热恶寒者，外未
解也，其热不潮，未可与承气汤。若腹大满不通者，可与小承气汤，微和胃气，未令至大泻
下。

大承气汤方

大黄 四两（酒洗） 厚朴 半斤（炙，去皮） 枳实 五枚（炙） 芒硝 三合

小承气汤方

大黄 四两（酒洗） 厚朴 二两（炙，去皮） 枳实 三枚（炙）

上三味，以水四升，煮取一升二合，去滓，分温二服，初服汤当更衣，不尔者，尽饮之，若
更衣者，勿服之。

这一条先说脉象，“脉迟”，脉来迟缓。阳明病也会脉迟吗？会的，实热闭于里也会阻遏气血
运行造成脉迟缓。脉数，也就是脉跳得过快，当然表示阳亢，但脉迟未必表示阴盛，阳热闭
于里也现迟脉。所以脉的阴阳以脉体的虚实来辨比较确实，尤其是重取的虚实，而不是快慢。

“虽汗出不恶寒者”，汗出恶寒是太阳病，如今不恶寒，说明有阳明里热证。“其身必重”，水
液囤积肌肉，太阳表证还是有一些的。“短气，腹满而喘，有潮热者”这是里有实热的表现。
据此得出结论，“此外欲解，可攻里也。”表证已经快解了，可以攻里了。治病原则是先表后
里，里证重急可先攻里。这里的情况就是里证相对于表证更重更紧急，所以可以先攻里。

“手足濈然汗出者，此大便已硬也”，我们前面说过，只是手足汗出，而不是全身汗出是津液
不足。这里为什么又说是大便硬结呢？因为大便硬结，气血就要汇聚于里去攻这个结滞，体
表的气血相对不足，于是只能手足汗出排排热排表邪。阳明证的津液不足一般来讲不是津液
的绝对值不足，而是里热里结消耗牵制了过多津液，所以这种情况可以用下药，把里实里热
下了，津液也就够分配了。读《伤寒论》必须心里有个人体大循环的概念，条文才好理解，
也才不会觉得条文有矛盾。这种情况用大承气汤。

“若汗多，微发热恶寒者，外未解也，其热不潮，未可与承气汤。”这是讲的是有太阳表证，
而“其热不潮”，里实热并不严重，那就不能用承气汤，要先表后里。

“若腹大满不通者，可与小承气汤，微和胃气，未令至大泻下。”如果腹大腹满大便不通，可
以给小承气汤，下了里面的实热，让胃气回和，不可以用大承气汤大泻下。这里其实是有略
文，腹大满，没有提腹痛，其实典型的承气汤证按压腹部是有腹痛的。提到腹痛，我们就要
说到手诊的问题。一个严谨的诊病过程，像这种里实证最好辅助手诊。我们前面学过的结胸
证有按之才痛和不按就痛的区别，这就需要手诊了。少阳证严格来讲也要手诊，有的病人自
己感觉胸肋苦满不明显，一按肋下就觉得里面胀痛。如果不手诊就有可能漏诊。承气汤证是
典型需要手诊的，大承气汤这样的大下之剂，最好看有没有腹痛，如果没有，只是腹大满，
那就用小承气汤，不可大下。

小承气汤相比大承气汤，大黄剂量不变，去了芒硝，减轻了厚朴枳实的剂量，其实是大承气
汤的温和版。一般大下之剂，《伤寒论》里至少有两个方子以备用，可以先用温和一点的探
路，的确是中病了，没有用错，且病不去再用峻猛一点的。还有一个调胃承气汤，这个就是
治胃虚的承气汤证，那就更温和了。这几味药的剂量也可以随证加减：实多，多用大黄；热
多，多用芒硝；腹满腹胀屁多，多用枳实厚朴。

209、阳明病，潮热，大便微硬者，可与大承气汤；不硬者，不可与之。若不大便六七日，
恐有燥屎，欲知之法，少与小承气汤，汤入腹中，转矢气者，此有燥屎也，乃可攻之；若不
转矢气者，此但初头硬，后必溏，不可攻之，攻之必胀满不能食也。欲饮水者，与水则哕。
其后发热者，必大便复硬而少也，以小承气汤和之。不转矢气者，慎不可攻也。

阳明病用大承气汤的指证是大便硬结了，大便不硬结是不可以用的，那有什么办法知道呢？
腹痛是一个指证，但这个不借助手诊有时候不一定明显，那就还有一个指证潮热，这是津液
被里面的淤阻牵制，热不能顺畅外出而发的一阵阵的潮热。

还有一个办法，就是用小承气汤先探路。比如六七天不大便了，是不是里面有硬结呢？先用
小承气汤，如果不腹泻，只是打屁严重了，那就是有燥屎，因为里面堵着，水液下不来，只
有气能出来。这时候可以用大承气汤攻。如果没有这种情况，说明里面的硬结并不严重，只
是一开始有一点燥屎，后面一定是溏稀的，这种情况有脾胃虚，是虚火，这是不可以攻的，
攻的话脾胃更虚了，便会腹部胀满而不欲饮食。病人这时候想喝水，喝了水也有可能会哕出
来，因为胃弱了。

如果病人再次发生怕热潮热的反应，说明里面又再次硬结了，这是硬结初起，津液也已经虚
了，只能先用小承气汤来缓攻。服了小承气汤，照样还是打屁不变得严重，不能用大承气汤。

这一条讲的是用发热、潮热、打屁这三个证来判断肠道里硬结的程度。

还有一种特殊情况，就是拉水，拉清水，水里面偶有硬渣，一天很多次，急迫、臭、屁多，
这也是里面有硬结，结住了，水能过，粪便过不了。这时候也要用承气汤。药下去，往往会
拉出一些硬块来，病就好了。

好，今天就讲到这里了，谢谢大家。

农历
黄帝纪元 四七一三年
正月十七
正月小
乙未年 己卯月 壬午日
生肖 羊
九九第4天 日十二建 平


== 2015-03-21（210-222）

有请刘希彦老师。

大家晚上好

今天接着讲阳明病。

很多人认为阳明病就是大便秘结或热泻，也就是肠道有实热。这样的话，阳明病的适用范围
是很窄的。

其实，只要是里有积滞的病都可以当阳明病来治，未必要那么严重才是，病轻则药轻就是了。
胡希恕先生说的“食、水、淤”致病，这个“食”为第一，也就是里有积滞。轻微的里有积滞有
些什么症状呢？

今天的条文主要就是讲这个的。

210、夫实则谵语，虚则郑声。郑声者，重语也。直视谵语，喘满者死，不利者亦死。

这里讲用人的声音来辨证。

前提还是阳明病，如果是实证，就是里面有硬结，病人会谵语，就是大脑亢奋说胡话；如果
是虚证，也就是里面没有硬结，只是有滞热，那就会“郑声”，意思是这个人很啰嗦，总是翻
来覆去的说同重复的话。

现在有个名词叫“话痨”，说的就是这种“郑声”的情况。我们现代人运动少脾胃虚，饮食又滋
腻重口，势必会造成肠胃里面的淤积，不是气血能量充足的人，这种淤积很难到硬结的程度，
多数就是里面有滞热有虚火而已，于是便成了话痨。

阳明病到了极期会怎样？“直视”，津液彻底虚了，都不能滋养眼球了，于是眼睛直了，不转
了；“谵语”，这是有实热的反应，那就很危险了，因为津液还在持续消耗。这时候如果发生
“喘满”，就是生命机能迅速下降，正常的呼吸功能已经不能支持了，病人是会死亡的。“不
利者亦死”，这里疑有错简，应该是“下利”。这时候如果病人还在腹泻，也很危险，病人也
会死亡。

212、伤寒若吐若下后不解，不大便五六日，上至十余日，日晡所发潮热，不恶寒，独语如
见鬼状。若剧者，发则不识人，循衣摸床，惕而不安，微喘直视，脉弦者生，涩者死。微者，
但发热谵语者，大承气汤主之。若一服利，则止后服。

阳明病是很迅猛很凶险的，这里讲病情恶化的过程。到了十来天不大便了，傍晚的时候会发
潮热。因为傍晚是肾经主时，肾经络表。借着人体经气循行到表才能发出热来，说明里面硬
结得很厉害了。病人不恶寒，开始发谵语，一个人说胡话，像见了鬼一般。再严重，发作的
时候不认识人；气血难到末端，手搅扰不安，不是摸衣就是摸床；怵惕不安，微喘，直视，
这是津液持续走虚的证。

这时候如果脉弦，病人是不会有危险的。如果脉涩，病人就会死亡。涩脉是如轻刀刮竹般有
涩滞感，津虚大虚会现此脉；气血有阻滞，比如有癌肿，也会现此脉。这里主要是津液大虚，
也是里有阻滞，这种情况病人会死亡。

“微者……”如果脉微的话，下文如何？没有了。应该是丢失了。我们知道诸如脉弦脉大脉涩都
是有邪气的，是虚而亢之象。脉微，脉象回复柔和，刚强者死，柔者生，说明邪气退了，这
时候应该是病欲解了。如果还有少许余证，少与调胃承气汤就可以。

如果只是发热谵语，那赶紧用大承气汤，不要耽误。阳明病耽误了是很容易死人了。我见过
这样的医生，明明就是大承气汤证，又是顾忌病人年纪大，又是顾忌病人体质虚，非要去用
生地麻仁润下，这些都是滋腻润养之剂，下去如同火上浇油，这样把病人一路治到病危抢救
的很多。现在的中医，对于麻桂附石硝黄这样的所谓猛药，往往弃之不用，不管什么情况，
总之在生地麦冬陈皮黄芩这些不痛不痒的药之间打转转，治小病迁延不愈，治大病就要误人。

用攻下的药，只要大便通了，就要停药，不可尽剂。

219、三阳合病，腹满，身重难以转侧，口不仁，面垢，谵语遗尿，发汗则谵语；下之则额
上生汗，手足逆冷。若自汗出者，白虎汤主之。

“三阳合病”，腹满、口不仁、面垢、谵语是阳明病；身重难以转侧是太阳病；少阳证这里没
有出；遗尿是津液大虚，膀胱结缔组织失养不能约束了。三阳并病治从少阳。治少阳的柴胡
类方都是以建中补津液为主的。如果只是发汗，津液更虚，谵语会更严重；如果只是下，也
会津液更虚且内陷，那就只有额头上有汗出了，别的地方出不来汗了，手足还会逆冷。如果
下之后，还有热证的自汗出，可以用白虎汤。白虎汤是解热加救津液，里面没有下药。

这里有两个新的证。口不仁是嘴里粗糙、没味道，或舌头不灵便，这是里热口舌肿胀引起的。
面垢是脸上脏脏的，总像没洗干净一样。肠胃里面有积热的人，一般脸上会有脏脏的，而且
肿胀粗糙。大家会发现，人一过了三十岁，尤其是吃肉喝酒的男性，就会渐渐变得头大脸肿
皮肤粗糙。这是因为三十岁后，人体的代谢渐渐变满，如果还像从前那样摄入，体内一定有
里热积存。所以我们建议三十后要慢慢的转向吃素，不然容易显老，疾病也会多。

221、阳明病，脉浮而紧，咽燥口苦，腹满而喘，发热汗出，不恶寒反恶热，身重。若发汗
则躁，心愦愦反谵语。若加温针，必怵惕烦躁不得眠。若下之，则胃中空虚，客气动膈，心
中懊憹，舌上胎者，栀子豉汤主之。

“脉浮而紧”，“身重”是太阳伤寒；“咽燥口苦”是少阳；“腹满而喘，发热汗出，不恶寒反恶
热”是阳明。这是三阳并病。这种情况如果发汗，人就会躁扰不安，心里头昏乱，谵语。如
果用温针，就会惊怵烦躁睡不了觉。如果攻下，胃里头就虚了，邪气进入胸膈里头，扰动不
安不舒服，心中郁烦不宁，舌上苔厚，这就是胃虚而邪热郁于胸膈，是栀子豉汤的适应证。

栀子豉汤的胃虚有热与半夏泻心汤的胃虚有热有什么不通呢？栀子豉汤是以上热为主；半夏
泻心汤是胃虚寒为主。

222、若渴欲饮水，口干舌燥者，白虎加人参汤主之。

前面讲的阳明病是肠胃里头有热结的。如果没有热结，而只是里头有热呢？这就是白虎汤的
适应证。里热最烧灼人的津液，所以白虎汤里有粳米速补津液。如果里热没那么严重，津液
损耗也没那么大，而且兼有一点表证呢？那就是麻杏石甘汤，麻黄杏仁疏散解表，石膏清热，
只有一味甘草补津液。

后世温病学里的代表方子桑菊饮和银翘散，事实上方义和麻杏石甘汤类似，是清凉解表之法。
这两个方子我也经常用。有人说，《伤寒论》没有治温病之法，这是不符合事实的。《伤寒
论》只是药简方专，一种情况就是一个代表方而已。

在这个群里讲课，不知不觉已经快一年了。感谢大家一起来传承圣学。你们当中有人跟随我
一起为中医做公益，在我们新建的微信平台里付出。感恩。也欢迎大家关注我们传播古经方
中医理念的微信平台，关注转发也是一种力量，更是一种付出。感谢大家。

== 2015-03-28（223-224）

西历 2015 年 3 月 28 日星期六

伤寒经方求真群，公益讲课。

有请刘希彦老师。

大家晚上好。

每周的课都是我在这里讲，也不知道大家的反馈。有些新来的跟不跟上？刚才有一位一个月前
刚接触中医的朋友，说听了几次课，脑子里已经有一个轮廓了。
不至于完全听不懂了。这就好，慢慢来，其实很简单。一般来讲学中医先会模糊一段时间，时
间到了自然会明白

这个不像应试教育的学习，不像学习西方文化，学一个步骤明白一个步骤。这个会有一天蓦然
全贯通了，这就是中国文化的学习特点。

今天我们学习猪苓汤，这也是一个很常用的方子。

223、
若脉浮发热，渴欲饮水，小便不利者，猪苓汤主之。

猪苓汤方

猪苓（去皮） 茯苓 泽泻 阿胶 滑石（碎）各一两

上五味，以水四升，先煮四味，取二升，去滓，内阿胶烊消，温服七合，日三服。

这个方子，很多经方家归入利水之方。的确，从药物来看，除了阿胶外，都是所谓的利水药，
但这个归类法我认为值得商榷。这个方子应该是有治阳明里热和利水的双重功效。

这里的“脉浮发热，渴欲饮水”是里热的反应。脉浮不一定就是表证，有里热而脉浮也是很常
见的。这里的小便不利主要不是因为津液虚，若津液虚到小便不利，那就是大虚了，这里还没
到这个程度。但津液虚是有的，毕竟是阳明里热，里热是烧灼津液的。这里的小便不利主要是因为热蕴于下焦，膀胱内浊热蕴结，尿道涩滞不通。

热蕴下焦用滑石。滑石的清热作用类似于石膏，同时这个药非常的滑，是润滑剂，又能走下焦，
所以对尿道的涩滞热痛很有效。阿胶既能滋养阴液也能润滑。这两样药合在一起，既能解热养
津液，又能润滑尿道，适合这里的小便不利。

猪苓的作用类似于泽泻，比泽泻更咸寒更能走下。说这个方子是利水之方，是因为有猪苓、茯
苓、泽泻。既要利水，为何还有阿胶这样滋腻的东西？再说，药没有什么利水不利水，这三味
药只是有降渗的作用，擅长走下焦。药物只是一个能量场而已，这种下行能量场未必只针对水，
有水引水，无水引热。比方说茯苓，也可用于安神和去烦，就是用其引火下行之作用。所以这
几味药在这里主要是降下焦之热。

猪苓汤和承气汤的区别：承气汤是泻肠中硬结；猪苓汤是泻膀胱热蕴。

猪苓汤和白虎汤的区别是：白虎汤擅长解上焦之热，兼救中上焦津液虚；猪苓汤擅长清下焦之
热，兼救下焦津液虚。

猪苓汤擅长治下焦的炎症。尤其擅长治尿道涩痛不畅，若偏热的可以再加大黄；若偏胃虚的可
加干姜甘草；兼有水饮的，可加白术桂枝。我甚至用猪苓汤加炮附治过阴证的尿道炎症。阴证
的病人，同时在膀胱尿道这个局部有湿热瘀火是完全有可能的。炮附针对阴证，猪苓汤针对下
焦的虚火。所以我说药物无非是能量场，这个能量场只要能适应人体的切实情况就能治病。

猪苓汤加大黄对肾、膀胱、尿道这个系统的结石有奇效，很大的结石有时候都能排出来，这主
要是因为大黄的攻下，加上阿胶滑石的润滑。

224、阳明病，汗出多而渴者，不可与猪苓汤，以汗多胃中燥，猪苓汤复利其小便故也。

这里的汗出多而渴，是胃中热且干燥，应该是白虎汤的方证，自然不能用猪苓汤。猪苓汤是利
下焦的，下焦有热则利热，无热那就只能利小便了。用在这里是不对证的。

一般习惯把猪苓汤归入利水的方剂，大约是因为这个条文。这还是受某方治某病，某药治某症
的思想的影响。单说利水其实是局限了猪苓汤，没有真正认识到方药在人体里的能量场作用。
就像上一条里举的例子，很多时候并没有湿证，我们也能用猪苓汤治好病。

说一个猪苓汤的医案吧。

这是一个女病人，症状是尿道酸胀不舒服，心烦不得眠，气短，食道有烧灼感，口渴欲饮水，
喝水多了会有胃胀感，头晕沉，脉弱，舌薄偏干苔少。

当时我给的是猪苓汤，加了两味药，干姜和黄芩。方子是这样：泽泻 10 猪苓 10 茯 苓
25 滑石 15 阿胶 10 白术 15 黄芩 10 干姜 8

药开得很轻，当时想的是如果有效再加量。只给了三剂，一剂后所有症状都减轻了，病人觉得
很舒服，吃完三剂基本上就好了。

我说下这个方子为什么这么开。气短，口渴欲饮水，头晕沉，这是有湿气有水饮。心烦不得眠，
食道有烧灼感，可脉象又是弱的，说明不是真的有热，而是属饮郁化热。你看，脉证相参就是
这个意思。

舌薄苔少，是津血虚。为什么会舌头偏干呢？不是有湿证吗？有时候中焦湿气囤积，津液不气
化上行，也会舌头干的。所以辨证不能死守局部，要整体的来看人体，要从人体的大循环和整
体关系来思考，不能死守局部，不能一见舌头干就是要滋阴，这样必定会误判。

猪苓汤首先能清下焦湿热，也能利水湿，也能养血，这都是合这个病人的情况的。加了点白术，
增加气化力量。可这个病人还有脉弱，也就是说，下焦局部是有湿热，可人体的整体情况是偏
阴寒的，怎么办？加干姜。干姜扶阳。扶阳就好了吗？还可以再推敲。心烦，食道烧灼，这是上热。脉弱，这是下寒。属寒热相格。

加黄芩、干姜，辅之以调和寒热。

再看这个方子，将病人这么复杂的情况，方方面面都兼顾到了，药物却只有八味，这就是经方
用药，药简力专，思路明确，药的方向明确，效果也就明确。后世的中医是以药对病症，心烦
什么药，不眠设什么药，一个病症的一味药那就不止八味了，何况一个病症还不止一味，所以
一开就二三十味，效果还不好。

好，今天就讲到这里了。谢谢大家。

农历
二月初九
二月大
乙未年 己卯月 癸卯日
生肖 羊
日十二建 建
华夏黄帝纪元
四千七百一十三年

== 2015-04-04（228-236）

西历 2015 年 4 月 4 日星期六

伤寒经方求真群公益讲座

有请刘希彦老师

大家晚上好。

以前我们讲六经辨证，最常见到的条文表述是此为表，或此为里，或是半表半里。

半表半里， 《伤寒论》里面没有明确提出来，用表里之间来表述，事实上也就是半表半里的意思。

今天我们来打破一下思路。

有没有可能在这三者的中间区域呢？比方说在表和半表半里之间。当然有的。下面的条文就是
这个。

228、阳明病，下之，其外有热，手足温，不结胸，心中懊憹，饥不能食，但头汗出者，栀子豉
汤主之。

这里讲的是阳明病误下。阳明病如果没有大便硬结，所谓“其外有热” ，这是热正试图从体表来
解，那就顺应人体的排病模式，用白虎汤或麻杏石甘汤。这是不能下的。如果误下了，有可能
会结胸，就是热邪内陷与津液互结。如果不结胸，只是“心中懊憹，饥不能食，但头汗出” ，这
是下药把胃弄虚了，运化失权，热郁于胸膈之中不得出，那就是栀子豉汤的适应证。

从这里可以看出，六经的思维方式是一以贯之的，实际上就是一个层面的划分，有的很典型是
表，有的很典型的是里，也有在半表半里，也有的在这三者的的中间区域。这里的热郁于胸膈，
可以理解为比表更趋向于里，却又没到半表半里。不管怎么样，只要以表里层面的思路去理解，
就能找到合适的处理方法。

事实上，比如小柴胡汤的加减，也是有这种区间微调的含义，比如小柴胡汤加生石膏。
下面讲一个小柴胡汤的医案。

231、阳明中风，脉弦浮大而短气，腹都满，肋下及心痛，久按之气不通，鼻干不得汗，嗜
卧，一身及面目悉黄，小便难，有潮热，时时哕，耳前后肿，刺之小差，外不解，病过十日，
脉续 浮者，与小柴胡汤。

这一条可以作为一个完整医案来分析。

脉弦，津液虚而有邪气；脉浮，有表证；脉大阳气亢。

心和肋的区域痛，而且久按有气不通的感觉，还有短气，这是少阳证胸肋满痛的范畴； “时 时哕” ，胃逆也是少阳的范畴。

腹都满” ， “鼻干不得汗，嗜卧” ， “有潮热” ，这是阳明里热的范畴。

“一身及面目悉黄，小便难” ，这是黄疸的范畴，属于热蕴肌表。

“耳前后肿” ，耳前主要是阳明胃经循行，耳后只要是手少阳三焦经和足少阳胆经循行。

这还是一个三阳合病。用针刺的疗法，病稍微好了点，外证还是不解，言下之意是里证有所好
转。这时候已经病了十来天了，脉又再次浮了起来，说明邪气又盛了。这时候若是没有什么新
的情况的话，那就还是三阳合病治从少阳，与小柴胡汤。

236、阳明病，发热汗出者，此为热越，不能发黄也。但头汗出，身无汗，剂颈而还，小便不利，
渴饮水浆者，此为瘀热在里，身必发黄，茵陈蒿汤主之。

茵陈蒿汤方

茵陈蒿 六两 栀子 十四枚（擘） 大黄 二两（去皮）

上三味，以水一斗二升，先煮茵陈，减六升，内二味，煮取三升，去滓，分三服。小便当
利，尿如皂荚汁状，色正赤，一宿腹减，黄从小便去也。

茵陈蒿汤也可以看成是一个区域中间的方子。

阳明病主要是身体里面有热结引起的。人体排热，主要是下和汗两个途径，若不能下，那就会
汗出多。发热而汗出多，这是热发越出来了，身体是不会发黄的。如果只是头出汗，身体无汗，
从颈部汗就回去了，小便不利，口渴想喝水，这是热淤在里面了，身体必定会发黄，用茵陈蒿
汤来治。

我们说汗和下排邪，若不能汗呢？人体就会通过小便来排邪气，膀胱经和肾经络表，人体就是
这样设计的。若汗不能排，小便也不排，那就会发黄。什么会发黄疸。为什么会发黄呢？经过
胃的消化，人体分化出两种营养，一种是红色的营养，经过肝脏的过滤送入心脏来输布，这就
是血液；一种是黄色的营养，经过脾脏送入肺脏来输布，这就是津液。所谓津血是这样分开来
讲的。肺主皮毛，这里是汗不能出，津液的淤积，所以是发黄。

茵陈是退黄的草药。这味药微寒、淡、有轻升的香味，这就具备了两种能量属性，一是轻升之
力，能发散于肌表，二是寒淡能利水。这能开表郁而利水。这味药用的最重。

栀子前面说过，淡苦而兼清香，擅长利三焦之水热。大黄这里用得轻，只有二两，约三十克，
若再去皮晒干，那就是十克之内的剂量了。有人说大黄是通大便的，我们说过这样认识药物是
很容易局限和误用的，大黄只是一种寒而破下的能量场，能下大便自然也能利小便。大剂量能
下大便，剂量小，就只能利小便了。大家不妨试试，一般大黄用个几克只能通利小便，而不能
通大便。

这三味药，茵陈重用，主要开肌表水热之郁；栀子利三焦之水热；大黄轻用，下里之水热，里
外全都廓清，服后尿色红赤，很快就能退黄。

当然，这是治热证的黄疸，若是偏阴证的黄疸，可以用桂枝、五苓类方剂合茵陈来退，这
个后面会讲到。

刚才群主说到的那个讲座，如果在北京的朋友，我建议去听听。因为主办方给的题目是讲古
中医的生命观。事实上是讲整个经方中医的哲学体系和对人体的思维方式。是一些本原的东
西。 《伤寒论》是一本论“术”的书，在“道”上基本不提。当时的社会是崇尚道家的，对于
当时人的知识结构，这种基本原则是不用讲的。可我们今天不讲，很多东西就会难以理解，
理解了也不知为何坚守，这就容易变乱。后世医学就是这样变乱了的。因为崇尚儒家了，对
于天地之道就淡漠了。

正好有这么个讲座的机会，让我讲讲这个古中医之“道” 。这个很重要，所以我建议有可能的朋
友去听一听。

我现在在做的是一个古中医恢复的系统工程。还有一个侧重于对病和养生的理解，侧重实际运
用的微信平台。

我知道很多朋友关注了这个平台。如果是做医生的朋友，这个平台是很实用的，比方说，今天
刚推送了一篇关于癌症的文章《癌症也是很脆弱的》 ，基本上所有关于癌的问题里面都解答了。
碰到这样的病人可以发给他看看，这样就可以省去很多答疑和科普的时间，对病人也很有好处。
因为真正传统中医思维的认识，有助于病人的正确选择和临床康复。

今天就讲到这里，谢谢大家。

农历
二月十六
二月大
乙未年 己卯月 庚戌日 丙戌时
生肖 羊
望 20:05:32 日十二建 危
华夏黄帝纪元
四千七百一十三年

== 2015-04-12（243-247）

西历 2015 年 4 月 12 日星期日

伤寒经方求真群，公益讲课。

有请刘希彦老师

大家晚上好。

我们现在讲的是阳明病，阳明病就是里热证吗？不可以这么理解，准确的说，是里实证。
里实证也有不那么热的。不可能都是热证。

下面这个方子就是治里实偏寒的证的。

243、食谷欲呕，属阳明也，吴茱萸汤主之。得汤反剧者，属上焦也。

吴茱萸汤方

吴茱萸 一升（洗） 人参 三两 生姜 六两（切） 大枣 十二枚（擘）

有人说，这里可能是写错了，这是寒证，怎么能说阳明呢？阳明病的总纲是“胃家实” ，就是肠
胃里面有东西堵住了。有东西堵住发热证比较多，但不等于都发热证，这就是寒证的胃家实。
堵住了，吃了东西“欲呕” ，意思是想呕，却没有呕出来。如果是太阳病，气血上逆走表，是容
易呕出来的；如果阳明病，里有热，反应会比较强烈，也是容易呕出来的。这里无热症，又无
表证，所以只是欲呕。如果是胃虚寒，食不受纳的呕，喝了热汤应该缓解，这是喝了热汤更严
重，说明是堵住了。 “属上焦”的意思是指堵在了上面。

这个方子四味药，后三味好理解，参、姜、枣健胃。姜本身也能止呕；呕家不喜甘，用大枣就可以了，炙甘草太甜腻就不用了。

这里详细说说这味新药吴茱萸。这个药很苦，苦的东西都有降的作用，能降逆；苦的东西一般
都寒，吴茱萸是温的，所以能止寒证的呕逆。温苦的东西一般都有清解的作用，比方说厚朴是
温苦的，能下气；麦芽炒焦了，多了温苦之性便能化食。吴茱萸还有辛辣之味，有辛散的作用，
这就兼具了解肌表的作用。吴茱萸主要是降胃镇逆，胃寒胃弱的呕吐，同时有逆证的可以用。
头部的疾患常用到吴茱萸，因为头部的疾患，无非是表不解而邪气上冲，吴茱萸镇逆加解肌表，
正对病机。比如头痛；比如黄斑病、青光眼等眼睛的疾患；比如癫痫、羊角风、美尼尔综合病
之类，只要是跟胃寒胃弱及上逆有关的都可以用它。

244、太阳病，寸缓关浮尺弱，其人发热汗出，复恶寒，不呕，但心下痞者，此为医下之也。如
其不下者，病人不恶寒而渴者，此转属阳明也。小便数者，大便必硬，不更衣十日，无所苦也。
渴欲饮水，少少与之，但以法救之。渴者，宜五苓散。

这一条将三种实证：心下痞、阳明热结、中焦有饮的鉴别。

先是讲因误下而致痞的情况。寸脉缓，说明表证不明显，准确讲是转为里证了，所以病人从发
热汗出转为恶寒，而且不呕，不在少阳。这个里证是心下痞。恶寒是因里有痞牵制津液，而致
恶寒。关脉浮是说明邪在中焦。尺脉为阴，尺弱说明阴血虚。

如果病人没有下过，只是不恶寒而且渴，这是转为阳明了。小便多，津液丧失了，所以大便硬。
这里说不恶寒，没说怕热，说明里热并不明显，而里实明显。没有里热，所以十日不大便也不
觉得很痛苦。

如果没有其它证，只是渴欲饮水，那有可能是饮证，先稍微给一点水缓解渴，以免饮证加重，
在用适当的方法来治，这里适合五苓散。

247、趺阳脉浮而涩，浮则胃气强，涩则小便数，浮涩相抟，大便则硬，其脾为约，麻子仁丸主
之。

麻子仁丸方

麻子仁 二升 芍药 半斤 枳实 半斤（炙） 大黄 一斤（去皮） 厚朴 一尺（炙，去
皮） 杏仁 一斤（去皮尖，熬，别作脂）

趺阳脉是指足背部的胫前动脉。古人号脉所谓“三部九候” ，三部指的就是寸口（腕部桡动脉） 、
趺阳、人迎（颈总动脉） 。现在只有寸口脉，古医术在传承过程中的流失由此可见。

这里也是以脉论病。趺阳脉是足阳明胃经的经脉，对于脾胃的问题反应较为清晰。趺阳脉浮说
明胃气强；涩说明津液虚，这个津液虚是怎么造成的呢？胃气强，气化能力够，不是因为阴寒，
那这个津液虚就是小便数造成的，此所谓“涩则小便数” 。浮和涩合在一起，大便就会硬结。这
里硬结是脾无津液可输布，脾受到了制约，所以称之为脾约。

这种情况用麻子仁丸来治。这个方子里的大黄、枳实、厚朴是小承气汤。说明是偏热结。这里
和小承气汤证不一样的是有津液虚，于是用麻子仁做主药，麻子仁富含油质，润肠道的作用很
强。杏仁能下气能润肠，这里熬作油脂来用，是取其滋润肠道的作用。芍药是敛津液的。

同样是热性的便秘，于三个承气汤之外又有这个麻子仁丸，反应出经方用药的核心精神，以津
液的盛衰为原则来加减组合。

好了，今天就讲到这里了。谢谢大家。

二月廿四
二月大
乙未年 庚辰月 戊午日生肖 羊
下弦 11:44:26 日十二建 满
华夏黄帝纪元
四千七百一十三年

== 2015-04-26（248-258）
2015 年 4 月 26 日星期日

伤寒经方求真群，伤寒论公益讲座。

有请刘希彦老师

大家晚上好。

今天讲几个承气汤的条文。

248、太阳病三日，发汗不解，蒸蒸发热者，属胃也，调胃承气汤主之。

发汗而不解，说明病不在太阳。 “蒸蒸发热”是指从里面往外蒸的发热，说明热在里。所以说这
是属于肠胃里面的问题。可以用调胃承气汤。

249、伤寒吐后，腹胀满者，与调胃承气汤。

腹胀满也有可能是胃虚而气满，属于厚朴生姜半夏甘草人参汤方证。这里用调胃承气汤，说明
是里有实热的胀满。

250、太阳病，若吐若下若发汗后，微烦，小便数，大便因硬者，与小承气汤和之，愈。

太阳病，汗吐下之后不愈，一般来讲会变成虚证。若体内素有积滞和内热，也有变成实热证的。
如果微微发烦，小便数，大便硬结，用小承气汤可以治愈。

251、得病二三日，脉弱，无太阳柴胡证，烦躁，心下硬，至四五日，虽能食，以小承气汤，少
少与，微和之，令小安，至六日，与承气汤一升。若不大便六七日，小便少者，虽不受食，但
初头硬，后必溏，未定成硬，攻之必溏；须小便利，屎定硬，乃可攻之，宜大承气汤。

这一条的第一句是有问题的。脉弱说明偏向于阴证，此时若有心下痞硬，应该是半夏泻心汤的
方证。至于烦躁，中焦痞塞，上下不交通也是会有烦躁的。所以此处疑有错简。后面说与小承
气汤，显然就不成立了。

这一条的重点是第二句。可以当做一个临证案例来看。如果六七天不大便了，能不能攻呢？还
要看一下小便，如果小便少那就不要着急攻。里面若有大便硬结的话，小便一定是会多的，因
为大便是含有水分的，大便硬结了，小便一定会增多。如果小便少，说明不是硬结。小便少还
有可能说明里面没有那么热，打个比方，如果一样东西受热，水分一定会释放出来，人体也一
样。这两种情况都不可以冒然去攻，如果攻的话，一开始可能会有一点硬的大便，后面必定是
溏稀的。

必须要等到小便多起来，这时候里面才是有硬结了，就可以用大承气汤来攻了。

252、伤寒六七日，目中不了了，睛不和，无表里证，大便难，身微热者，此为实也，急下之，
宜大承气汤。

眼睛如果转动不利了，是什么问题？我们前面说过，是津液虚，因为眼睛的转动要靠大量津液
来润滑。 “无表里证” ，这句话有问题，因为后面说大避难就是里证，身微热也可以算是轻微的
表证。这是阳明里实引起的眼部津液虚，下实热则津液自回，用大承气汤。

253、阳明病，发热汗多者，急下之，宜大承气汤。

有阳明里实，同时有发热汗多，这是里热外透，这个里热很严重了，应该赶快用下药，可以用
大承气汤。

254、发汗不解，腹满痛者，急下之，宜大承气汤。

这是接着上条来说的：这时如果用发汗的方法，病是不能解除的。腹部感觉到满痛的话，要赶
快用下药。可以用大承气汤。

255、腹满不减，减不足言，当下之，宜大承气汤。

这也是接着上条来说的，如果腹满不减轻，或者减轻得很少，还是应该用下药。可以继续用大
承气汤。

256、阳明少阳合病，必下利，其脉不负者，为顺也。负者，失也，互相克贼，名为负也。脉滑
而数者，有宿食也，当下之，宜大承气汤。

阳明少阳合病，一定会下利，这是人体通过肠道来解除病邪。如果脉象不虚的话，这是顺的，
因为二阳病，脉象就应该偏盛一点。如果脉象“负”的话，这是“失” ， “失”者，无非是失津
液的意思，也就是虚的意思。这是既有二阳病的热，又有津液虚，这就互相矛盾制肘了。

脉滑者，如珠子从血管里滚过。说明两个问题，一为有热，二为津液不虚。脉数，说明有热。
从脉象来看，这是有宿食，应该下，可以用大承气汤。

这里以脉论病，不符合《伤寒论》的脉证合参，证为主，脉为辅的原则。疑为后人所加。

257、病人无表里证，发热七八日，虽脉浮数者，可下之。假令已下，脉数不解，合热则消谷善
饥，至六七日不大便者，有淤血，宜抵当汤。

这里既说无表里证，又说发热七八日，发热就是典型的表证，这是矛盾的。无里证，又脉浮数，
怎么可以下呢？这是说可下就有点不好理解了。

如果用了下药，脉还是数，病也不解，而且还有能吃又容易饿，六日天不大便，这是有淤血，
可以用抵当汤。为什么这里判为淤血证呢？因为有“消谷善饥” ，这是淤血证的一个指证。体内
有淤血，气血就要去攻这个淤血，会加大消耗，再加之又是热证，所以能吃易饿。阳明瘀血证，
是适合用抵当汤的。

258、若脉数不解，而下不止，必协热便脓血也。

脉数不解，说明有热；下利不止，说明这个热是肠道里面有实热，人体在用下利排这个实热，
却一直未能排干净。实热未解，而人的津液是有限的，津液因下利消耗得太多了，人体就要动
血液来排邪气。血液与邪气相抗，兵力折损，就会形成很多死亡的败血，于是就会发生便脓血
的现象。一般来讲，有脓就是有热，所以这是说了是“协热” 。

今天就讲到这里了，谢谢大家

== 2015-05-16（260-262）

西历 2015 年 5 月 16 日星期六

伤寒经方求真群 公益讲课

有请刘希彦老师

大家晚上好。

不好意思，前两周因为临时的事情都没有上成课。对不起大家。

今天我们把阳明病篇讲完。

阳明病篇最后讲的是湿热。

我们前面讲过表热上热，也讲过里热。这都是纯粹的热。但还有一个比较多见的证型就是湿热。
湿是阴邪，热是阳邪。一般来讲有热怎么会有湿气呢？热和湿应该是不能兼容的。
人体的复杂性就在于此，胃弱，水液运化失权就会有湿，同时也有可能有热，这就成了湿热。

下面讲条文。

260、伤寒七八日，身黄如橘子色，小便不利，腹微满者，茵陈蒿汤主之。

湿热的第一个方子是茵陈蒿汤。这个方子是茵陈、栀子、和大黄。

身黄，小便不利，这是全身性的湿热明显。里热，里热不明显，腹部只是微满。没有典型的承
气汤方证。所以主要用茵陈和栀子清热利水，和少量大黄下。

大黄是既下大便，也下小便，也下淤血的。一般来讲用量不大的话，下小便的可能性大。这里
有轻微腹满，所以是很合茵陈蒿汤方证的。

如果没有里证，只有阳黄呢？那就是下面这个方子——

261、伤寒身黄发热者，栀子柏皮汤主之。

栀子柏皮汤方

肥栀子 十五个（擘） 甘草 一两（炙） 黄柏 二两

栀子是除烦热的，也能清湿热退黄。柏皮就是黄柏，和黄芩、黄连作用相类似。黄柏味厚，更
能祛下焦之湿热。这里能不能用茵陈呢？当然也是可以的。茵陈不苦，其气轻升，更能走表。
这里有发热，说明有表证，茵陈也是合用的。

上面这两个方子都是胃弱不明显的。胃弱明显的湿热是下面这个方子。

262、伤寒淤热在里，身必黄，麻黄连赤小豆汤主之。

麻黄连轺赤小豆汤方

麻黄 二两（去节） 连轺 二两（连翘根是） 杏仁 四十个（去皮尖） 赤小豆 一升 大
枣 十二枚（擘） 生梓白皮 一升（切） 生姜 二两（切） 甘草 二两（炙）

黄疸都是因为水湿瘀滞引起的，分阴黄和阳黄。我们前面说过，黄疸纯粹的阴证少，阴黄一般
来只是热象较轻的黄疸，我们可以用五苓散加茵陈来治。还有一种阴黄是寒热夹杂的：脾胃偏
向于虚寒，因为脾胃不运化，淤而生热而发黄。这种情况就要用到这个方子。

方子里有姜草枣，这是建中温胃的；麻黄、赤小豆、连轺（也就是连翘） 、生梓白皮、杏仁，这
几味药无非是疏散和清热两种作用。

这个方子我在临证上运用很多，并不局限于黄疸。现在有一种身体失衡的局面很常见：脾胃是
虚寒的；由于饮食滋腻又不运动，加之熬夜，于是会有上火。这种虚火其实并不热，用不着白
虎汤；也不实，用不着承气汤，主要是由于身体处于瘀滞状态引起的。这种失衡引起的疾病很
多，只要对证，都能用这个方子来治。我常用这个方子治疗各种瘾疹类皮肤病；其次就是咽喉
或者泌尿系统的炎症。

连翘有注解说是连翘的根，这个存疑，因为不确定这个注解是否原文。我们现在一般用的就是
普通的连翘，也就是连翘的果实。它有类似薄荷的方向，有发散的作用，也有微苦，能解热利
尿。后世中医常用连翘，说它治咽喉肿痛，治瘰疬，治风热感冒，治皮肤病，治黄疸。

后世中医以用讲药，一来是太复杂，二来也容易局限和误用药物。其实药物只是一个能量场，
它有走表的发散的作用，自然不管是瘰疬瘾疹，还是风热感冒咽喉肿痛，只要是人体上部的偏
热的邪气都能将其散掉；它散中兼有微苦，自然就能利湿热退黄疸。

赤小豆不苦不香，淡而降，微寒性燥，是利湿热排脓的药。需重用才有效。这个药很压秤，这
里用的是一升，汉制一升约 200 毫升。200 毫升的容易装赤小豆是多少，大家可以去称称看。
生梓白皮这个药是梓树的内白皮。 《神农本草经》谓： “梓白皮，味苦寒，主治热，去三虫。 ”这
个药现在用得少，有时候药房没有，一般用桑白皮代之，也有用茵陈代的。 《医宗金鉴》曰： “茵
陈可代本药，但不如桑白皮有泻肺、利水、消肿之效也。 ”

这个麻黄连翘赤小豆汤就是正治胃虚型湿热的。里面除祛湿热的药外，有一味健胃温阳的生姜。
后世有个类似的方子组得也很好。叫三仁汤。

这个方子的组成是杏仁、白蔻仁、薏仁、厚朴、半夏、通草、滑石、竹叶。这里面以宣通利湿
的药为主，只是加了一味辛热的白蔻仁，还有微温的厚朴。

这种组方的方式和麻黄连翘赤小豆很类似。对于治疗一般的湿温病，我个人觉得比麻黄连翘赤
小豆汤更好用。有时候病人午后犯困，郁郁微烦，问证无热象，脉却有微热，舌淡胖大的，这
时候当热治当寒治都不好治，就有可能在三仁汤的范畴。又比如，我用麻黄连翘赤小豆汤治好
的皮肤病很多，有一次，一个带状疱疹，

辨证是湿热，我没有用麻黄连翘赤小豆汤，用了三仁汤，效果也很好，三四剂药就好了。
好，到这里就把阳明病篇讲完了，下次讲少阳病。今天就讲到这里了，谢谢大家。

农历
三月廿八
三月小
乙未年 辛巳月 壬辰日
生肖 羊
日十二建 闭
华夏黄帝纪元
四千七百一十三年

== 2015-05-23（263-266）

西历 2015 年 5 月 23 日星期六

伤寒经方求真群， 《伤寒论》公益讲座

有请刘希彦老师。

大家晚上好。

今天我们讲少阳病了。半表半里病很多，因为这个区域很大。江湖上有个柴胡派，只开柴胡汤，
也能成名医。可见这个柴胡汤适应面之大。

柴胡汤原来也讲过，今天我们系统的来讲下少阳病。

263、少阳之为病，口苦、咽干、目眩也。

从这一条开始进入少阳篇。

其实少阳病的主要方证我们前面已经学过了，这一篇只是系统的来梳理一下。关于半表半里少
阳证的人体原理，第 37 条有详尽的解释，这里就不再重复。

我们知道，少阳病有四个主证：往来寒热，胸满肋痛，心烦喜呕，嘿嘿不欲饮食。这一条作为
少阳病的总纲，又提出三个纲领性的证。为什么不直接用四证来作为总纲呢？它们之间矛不矛
盾？它们不矛盾，证后面的人体原理其实是一样的。少阳四证是见其一便可定为少阳病；而少
阳病的总纲却没有这样说。这里的三个证，见其一还不能定为少阳病，须和其它的证合参。就
像太阳病的总纲里的三证，说“太阳之为病，脉浮，头项强痛而恶寒。 ”这三个证见其一是不能
定为太阳病的，少阳病也会头痛，少阴病也会恶寒。这个需要注意。

现在来说一下这三个证的原理。

先说“口苦” 。人体这个躯壳，外面覆盖着皮肤；内腔壁覆盖着粘膜。这个粘膜区域属于半表半
里的范畴。如果这个区域出现上半部分的热证，属于少阳病，其原理第 37 条做过详尽的解释。
苦的东西一般来讲是寒降清热的，如果内粘膜组织有热，人体的自然机能就会分泌苦味的东西
去清这个热。这些苦味的东西西医上有一些专门的名词，我们可以先不要去管它。内粘膜没有
味觉，而内粘膜的出口——口腔是有味觉的，于是口里头便会觉得苦。换言之，口里头觉得苦，
整个上焦系统的内粘膜都已经有热了。

“咽干” ，少阳病是半表半里之热郁于上焦，自然就会咽干。咽干的原理和口苦的原理相同，都
是整个上焦内粘膜系统的邪热。

“目眩” ，少阳证是因胃弱，气化循环受限，上下不交通引起的。邪热郁于上而不得下，上冲于
头，就会目眩。

264、少阳中风，两耳无所闻，目赤，胸中满而烦者，不可吐下，吐下则悸而惊。

我们以前讲过太阳病的中风，这里提出一个少阳病的中风。中风到底是什么意思？这个说法不
一。通观《伤寒论》的条文，中风一般指的是因体表丧失津液而造成的津液虚，津液虚表虚则
风邪容易进入人体，大概是这个意思。

少阳病同样也会中风，这时耳朵听不见了。肾经络表，肾主耳，风邪郁表，耳朵就听不见了。
表虚也会造成耳朵听不见，表虚则肾虚，老年人肾气衰了，耳朵也会听不见。 “目赤，胸中满而
烦” ，这是少阳证。少阳证而有津液虚，不能够再行吐法和下法耗散津液，否则会发生惊悸的反
应。

265、伤寒，脉弦细，头痛发热者，属少阳。少阳不可发汗，发汗则谵语，此属胃，胃和则愈，
胃不和，烦而悸。

头痛发热是典型的太阳证，为什么这里说是属少阳呢？因为有“脉弦细” ，津液是虚的。少
阳病的实质是胃虚津虚，邪气内陷，与正气相持于半表半里。少阳的外感病也是会有头痛发
热的。假设这是一个病例，如果没有其它的太阳或少阳证来佐证，在这种相对含糊难断的情
况下，但凭一个脉弦细，也可以倾向于少阳，因为津液虚是要慎行解表之法的。这里体现的
是脉证相应原则，就是要脉和证一起来比对印证，得出最符合人体实际的结论。

少阳既为胃虚津虚，自然不能发汗，发汗津液更虚，加之少阳有上热反应，大脑就会产生缺少
津液的热性反应，就会谵语。这是大脑用兴奋的方式在调集津液以自保。这个问题说道根源还
是在胃，胃若能和，能生化津液，自然就会好；若不能和，那就会“烦而悸” ，这也是跟津液虚
和上热有关的反应。

266、本太阳病不解，转入少阳者，肋下硬满，干呕不能食，往来寒热，尚未吐下，脉沉紧者，
与小柴胡汤。

这一条的几个证就是典型的半表半里证了。 “脉沉紧”说明邪气入里了，不但肋下有痞结，胃里
面也不运化了，所以会“干呕不能食” 。如果吐下了，胃里面空虚了，脉也就不会沉紧了。 《伤
寒论》的条文多数情况下没有完整的脉证，这两条都是脉证很齐全的病例。

今天就讲到这里了，谢谢大家。

农历
四月初六
四月小
乙未年 辛巳月 己亥日
生肖 羊
日十二建 破
华夏黄帝纪元
四千七百一十三年

== 2015-05-30

西历 2015 年 5 月 30 日星期六

群主-夏正安(409227821)

伤寒经方求真群公益 讲课

有请刘希彦老师。

大家晚上好。

之前，我们将条文讲得比较多，讲治病的案例讲得比较少。系统的讲治病更是没有过。以后我
会有讲一些关于治病方面的东西。

治病最麻烦的是什么？儿科。因为不能摸脉，亦不能问证。 《伤寒论》讲脉证相应。这怎么看病？
但是，这也很考验大家的辨证能力，和对人体的理解程度。所以今天就讲讲儿科的治法。

儿科也有容易的地方，就是儿科相对而言病因比较简单，没有成年人那么麻烦。比方说，虚劳、
淤血、情志治病，这些儿科都比较罕见。儿科只要分清寒热证，还是很简单的。问题在于不摸
脉，这个寒热证怎么分？

很简单。鼻孔出来的空气发烫，呼吸粗重，面红赤或肿大、大便臭或屁多、身体烫饮水多、
胃口好多食易饥饿。有类似这样的症状就是热证。寒症呢？小儿纯寒症少。没有热证的，不
等于是寒症。但如果虚弱不食，面色发白发清，神散声微、大便清稀不臭，鼻息寒微，也就
是呈衰弱反应的就是寒证了。

说个案例。有一个二岁多的小孩，烧不退。刻诊，鼻息虽然未能明确判断发烫，但鼻孔发干；
面色轻微发红，大便不通。我判断为热证。看前面大夫给服用的药物，竟然是桂枝汤。这就是
误治了。

我给了麻杏石甘汤加大黄。麻黄 5 克，杏仁 5，生石膏 25，甘草 3，大黄 3。服下，几分钟后大
便既通。一个小时后烧退。你看，小孩的病，虽然不能摸脉不能问，通过可察知的情况，辨证
准确了，亦很简单。

我这里有两篇写小儿疾病和保健的文章，很好，贴给大家看一下。一篇是张琼写的，也是在这
里学经方。

中医妈妈的宝宝高烧实战手册

文·张琼

身为一个母亲，最担心、最焦虑的莫过于孩子生病。身为一个中医母亲，面对孩子突如其来的
疾病，尤其是高烧，是如何应对的呢？

2014 年 11 月 17 日，我的孩子优优 1 岁 1 个月零 23 天终于爆发第一次高烧，初量体
温 38.8℃！这在西医标准已经够吃退烧药的了。我身边许多家长只要孩子体温超过 38.5℃，
就会果断给孩子吃退烧药：美林、布洛芬等。我至今仍依稀记得我父亲大雪天背着年幼的我
去急诊排队挂号的情景，好像除了送医院吃西药，我们对于孩子的高烧就束手无策了一般。

也许有的家长会想：孩子病了在给他吃药之前，首先是不是应该彻底搞清楚他到底为什么生病
呢？发烧是每个人都会有的一个发病症状，人会因为很多原因而发烧，比如急性肠胃炎，比如
破伤风感染，而感冒只是其中的一种情况，而且发烧即使不强行退烧也是会自愈的，那是不是
可以解释说发烧并不是人体“坏了”呢？那发烧到底是什么呢？

发烧，就人体运行的原理来说，是人体的能量（也就是俗称的抵抗力）与邪气相对抗于体表的
表现。

正常情况下，人体的能量随时可以把受到的风、寒、暑、湿、燥、火等邪气驱逐出体外，但在
人体能量出现问题的情况下，人体能量就会与邪气相持与体表，于是形成发烧。所以用退烧药
强行退烧，就等于撤去了人体的屏障，邪气就会深入里面，这就是为什么许多孩子在医院，治
来治去，久治不愈。而邪气深入人体里面的第一个屏障就是肺，就会形成肺炎。各位宝爸宝妈
们，不是因为高烧引发了肺炎，事实上很多肺炎恰恰是强行退烧引起的，而肺是一个脆弱的器
官。

如果邪气再进入，就有可能进入骨髓。强行退烧其实往往是退不下去的，退烧药把人体屏障退
掉后，人体正气受到伤害，人体便衰弱了，继而转为低烧，时间久了烧退不下来，邪气进入骨
髓，骨髓里的造血指标出现问题，降不下来，医院就会怀疑是白血病，然后这些孩子很可能会
被当成白血病儿童来对待，接受一些很可怕、痛苦的治疗。事实上邪气退了，指标也就恢复正
常了。如果一开始没有用错了办法就不会出现这样的情况。

有的家长会担心，发高烧会不会把孩子脑子烧坏啊？我可以坚定地告诉你，别说发烧，就算
是惊厥（俗称抽风）这样的重症，一般情况下也不可能造成脑损伤，别说是发烧了。该如何
正确的辨别孩子的寒热症呢？即使不懂中医的家长们，也可能听说过，儿童感冒发烧有热症
和寒症之分，不同情况要区别处理。热症的邪气主要来自于体内，体内有多余的积存的食物
能量，它在特定的诱因，比如感冒、进食不适当的食物等情况下，人体想把这些多余的能量
烧出去，热症的表现看上去像感冒，但事实上是一种里热反应，在这种时候，要赶紧给孩子
撤掉能量，减少喂食，并且减少衣服，帮助孩子散热。热症的表现通常有伴有便臭的肠鸣腹
泻、便量大，气泡臭屁，便秘，小便短赤（即小便量少偏黄） ，口渴饮水多，局部（例如
脸颊、下巴）皮肤干燥、粗糙，脸颊通红，流脓黄鼻涕，尺肤（小胳膊内侧）发烫，呼吸粗
重发烫，精神状态亢奋等，热症即是温病。温病首先要做的就是减食。正常情况下孩子是多
热症的，因为从生理的角度来讲，婴幼儿期是一个人一生中阳气最旺的阶段，孩子看起来弱
小，其实身体比我们大人都好。所以一般的孩子感冒发烧都是应该减食的。我的孩子优优的
身体表现就是热症，所以在生病的这几天里，首先减食，停掉一切辅食，以及尽量拖延喂奶
间隔时间，减少次数。

再来说说寒症，寒症是指人的气血功能、脾胃功能本身就虚，它不够能量把寒气驱逐于体外，
于是正邪相持于体表。寒症的表现与热症相反，孩子没有呼吸粗重、大便臭等症状，多表现
出精神萎靡，脸色发青、发暗等，寒症的孩子不宜减食，只要脾胃的负担不要过大就好。有
的家长会问，是不是孩子受风着凉就可以辨别为寒症呢？我的回答是：在看过了我上述的辨
证法之后，你会明白，这个结论是完全错误的。而事实上很不幸的，当下许多儿科医院门诊
大夫他们就是这样辨别寒热症的，这是完全错误的，在真正的传统中医面前显得太业余了。
接下来，我就把我是如何照顾孩子，逐步退烧的经过分享给各位家长，希望对大家有所启发。
因为优优发烧是热症反应，我开始给他减食，但为了防止脱水，注意适当给水，还给他吃大
米粥。大米粥此时是最好的补充人体津液的来源。 （注：不要用小米粥，小米属温性，补
益作用很好，不适用于温病。 ）

17 日晚上睡前洗了温水澡，体温 37.5℃～37.9℃之间，夜里两次测出高烧 39.2℃，第一次在
3点左右，第二次在 5 点左右，整晚睡眠不好，容易醒，但状态尚可。给他做了 5 分钟背
部刮痧。古时的儿科多用刮痧推拿为小孩子医病，因为孩子尚年幼，吃汤药确实有一定障碍。
（第一天腹泻 6 次）

18 日上午体温基本保持在 37.5℃左右，时高时低，基本保持在 37℃～37.9℃之间。辨其症状，
腹泻、便臭、食欲减退等症状仍然还有，精神状态明显较前一天低靡了很多，整个人都显得
安静，对于喝水的欲望也有所减退，变得粘人，总要求妈妈抱。继续给他喝白米粥，适当给
水。蒸熟的苹果有收敛的作用， 给他吃下小半个。 下午接近 5 点的时候体温又出现反复，
最高 38.8℃，给他洗温了水澡，刮痧，夜里体温基本保持在 37℃多，低于 38℃。 （第二天
腹泻 5 次）

19 日上午体温基本在 37.3℃左右，不超过 37.5℃。依然只给他吃白米粥，减少哺乳，喂了
少量蒸熟的苹果（他食欲不佳，吃了很少） 。到了下午体温完全恢复正常，低于 37℃。
（第三天腹泻6 次）

20 日除早晚各有一次腹泻外，整日体温正常，食欲一般，但对奶食欲不减，精神状态明显低靡，
粘人需要总抱着。

21 日大便恢复正常，其余诸症全部消失，他已完全康复。一共半天高烧，两天的低烧，不
药而愈。我想他是非常棒的宝贝，全靠自己打完了这场战争，

整个过程没有任何药物的帮助，并且大获全胜，至今无反复，状态良好！

还有一篇文章，是说儿童保健的，纠结时下的一些误区。

不要用爱的名义毁了孩子健康

口述：刘希彦

文字整理：张琼

昨天遇到一个孩子，从小就喜欢喝饮料吃零食，经常打针吃药，不吃饭不吃菜光吃肉，不出去
玩，光看电脑电视，六岁验出白血病，身上到处都是脂肪瘤。家长还在问，到底是缺什么营养，
说马上去买了让他吃，还抱怨说晚上吃得太少了，平时应该再要求严格一点让他多吃些就不会
这样了。

在这个病例里面有两个问题，第一个问题是这个家长在遇到孩子有一点小病的时候，就带他去
医院打针吃药。我们知道中国的医院是滥用抗生素的。国际卫生组织早就声明，抗生素不是感
冒的特效药，在国外的门诊这是禁用的，对孩子的免疫力和身体功能的伤害很大。

抗生素，顾名思义，它是一种对抗性的药物，是伤害和压制自身机能的，是一种以杀害人体的
正常细胞和免疫细胞为代价的抗病行为，现在很多疾病的高发，与抗生素的滥用是有关系的。
从古中医的角度来讲，当人体感受外界邪气的时候，人体就会形成发烧这个机制，将邪气驱赶
出去，只有当正气不够的时候，邪气才会往内入。现在的医院里，用抗生素输液退烧，水本身
就是阴寒的物质，将那么多冰凉的水直接从血管输入人体；再加上抗生素是苦的，舔破片剂的
糖衣可以尝到，中医讲苦则为寒，为降，它和输液的道理一样，当这种苦寒的药片和阴寒的液
体进入人体，都是在打压人体的阳气。发烧是人体抵抗病邪的第一道天然屏障。当人体的阳气
被打压后，人体对抗病邪的能力就弱了，邪气会长驱直入进入肺，所以一般的小孩在强行退烧
之后，往往容易在几天之后引发肺炎，这是人体的正气和邪气在肺这个地方僵持住了。

这个时候如果再给孩子输液，继续打压人体的正常的功能和阳气，那么邪气还有可能再次深入，
深入骨髓。这就是为什么很多孩子感冒发烧一段时间之后治不好的话，医生就会建议去查一个
骨髓。这样的话就有可能被归入白血病了。因为这时候骨髓细胞一定是异常的。那么多的抗生
素进入人体，人体也要抵抗排异，他的骨髓细胞不可能正常。

古中医的理论，我们不会用药物去强行退烧，而是以增加人体能量的办法去帮助退烧。打个比
方，感冒受寒后喝一碗姜汤，发烧为什么还喝姜汤这种热性的东西？发烧是因为人体没有足够
的能量把邪气排出体外，于是在体表形成发烧，这其实是人体在体表增加能量去排出邪气。你
用姜汤助它一把力，邪气自然就排出去了，邪气一去，烧便自退。所以古中医讲的是让病自退，
我们是一个顺应人体，顺应机能，顺势而为的思路，和西医的对抗式治病思路是有本质上的区
别的。疾病到底是什么？疾病很多时候其实就是我们自己的排病反应。对抗式治疗伤害了免疫
力，容易诱敌深入，等于自毁长城，造成严重的后果。当然这里要特别提醒一下，不是所有的
感冒都适合用生姜，寒证才适合，尤其是小孩子的感冒一般热证居多，应该用清凉解表的方子。
请辨证后准确使用。

这个案例里面的第二个问题是平时不怎么给孩子吃主食，而是给孩子吃很多的肉。大家有没
有想过，主食为什么会被称之为主食？顾名思义，它提供给人的是基础营养。基础营养是碳
水化合物，是淀粉。现在很多家长自己的饮食生活习惯就有很大的误区。他们认为米饭里没
有营养，而肉才营养，肉里面含有的主要是油脂和蛋白质，他们认为蛋白质才是营养，而事
实上一个人一天对于蛋白质的需求是很有限的，营养学家说过一个鸡蛋就足够供应人体对蛋
白质的需求。多余的蛋白质吃下去就会变成毒素——人体接受不了需要排出来的东西在广义上
来讲都是毒素。这个时候孩子要不了那么多的蛋白质，而且还需要耗费能量和气血去把它排
出来。加之当下的肉含有过多的激素、化学残留物等很多不好的东西，这也是非常伤害孩子
的身体功能的。我接触过很多小孩抽动症、疝气、顽固湿疹的病例，他们共同的特点是家长
都会给他们吃很多的肉类，鸡腿一次吃两个。这样的孩子脾胃一定会被搞坏。为什么会坏呢？
除去前面讲的肉提供不了人体的基础营养外，还有能量场的问题。脾属土，土是什么？从五
行能量来说，它需要土的能量来补充，五谷才是得土气最全的。你不给他吃主食，光给他吃
肉，他的脾胃能得到土气吗？

现在的家长生怕孩子吃的不够，总觉得孩子多吃才是好的，于是追着孩子喂饭，威逼利诱让孩
子去多吃。他们不去思考一个问题，如果是你不想吃东西，却强迫自己吃下去，你会出现什么
结果？你会出现脾胃功能很差，厌食，甚至便秘。孩子也是一样，他可能已经吃了一些零食和
饮料，你再强迫他去吃，他的脾胃功能就坏了。脾胃功能坏了吃下去的东西也不会吸收。有一
个孩子，眼睛抽动的很厉害，找我求诊，我问孩子的家长，他是不是吃很多的肉类，他说家里
有老人总是给孩子喂很多的肉。我又问他是不是不吃了还在追着喂，他说是。我说你得把这个
习惯改掉，结果他说“我的孩子去化验了，还贫血！ ”言外之意是，都贫血了还让少吃吗？但他
不去思考，孩子不饿了还在吃，吃了那么多肉，为什么还贫血呢？其实就是他的脾胃功能坏了。
脾胃功能坏了不吸收营养，吃什么都不能变成为气血。我见过一些“胎里素”的宝宝和生下来
就跟着爸爸妈妈吃素的孩子，只要他们的脾胃功能是好的，也不会出现贫血。很多时候不是吃
下去就能解决问题的。

还有一种孩子的脾胃功能也不好，就是有压力的情况下吃饭的孩子。你追着孩子喂饭就是在给
他压力，他在很憋屈的一种状态下吃饭。古人云“食不言、寝不语” ，古人在吃饭的时候不主张
管教孩子。孩子在一种压力底下被逼着进食，边哭边吃，这样不光造成孩子的脾胃功能差，还
会让他整个的身体出问题。造成的不良结果有诸如：疝气、肠篓、贫血、发育迟缓、脂肪肝、
心跳异常等等……这些问题说到底都跟脾胃虚有关系，因为脾为后天之本。再次提醒家长，千
万不要一听到脾虚、气血虚就联想到加强营养。 《红楼梦》里，贾宝玉生过大病之后，贾府让他
吃了很长一段时间的清粥小菜。病后反而不给进补，不给有营养的吃，这是为什么？像贾府这
样的贵族家庭，他们深谙养生之道，知道孩子在生完病，身体还处在虚弱的情况下，根本消化
吸收不了那么多的肉和滋腻的东西。给他能吸收的，让他的脾胃在轻松的状态下慢慢恢复功能。
这其实是一种顺应生命的思维方式。咱们当下的思维方式是什么？全部是最简单粗暴的。
民间有一句话：若要小儿安，三分饥与寒。小孩容易食积，一旦食积就容易感冒。还有的小孩
容易得热伤风，其实就是穿多了，很多家长认为小孩和老人一样是脆弱的，于是就给孩子穿很
多的衣服。还有很多老人带孩子喜欢拿自己的体感温度去衡量小孩。其实小孩阳气旺，属于纯
阳之体，你看冬天小孩都不烤火，只有大人才需要烤火。而且孩子生性好动，穿得过多就更不
能散热了。其

我有一位好朋友，她生怕女儿长不高，因为她们全家的个子都不高，于是她给孩子吃的很多。
我给她的建议是少吃，少吃一点可能会长的更高。因为道家讲“虚则灵” ，堵死了怎么还能
够生发生长呢？你堵住了她的生发之气。但她不这样想，她认为营养够才会长高。中医的角
度来讲，影响人长高的是什么呢？我们说肾主骨，一个人的肾气影响他整个骨骼的发育。五
行来讲，脾克肾，肾的功能是受脾的制约的。如果一个人的脾功能失调的话，就会影响肾的
功能。脾虚，或者老有食积，就会克肾。从这个理论上来讲，给孩子吃多了，也会影响长高
的。当下的孩子把甜味饮料当水喝，甜的东西入脾，甜多了就会引起脾的亢盛和失调，也间
接影响肾的功能。现在有一种说法是孩子，喝太多甜饮料会让孩子得白血病，除了饮料里有
很多化学合成的糖分之外，说到根本还是“脾克肾” 。孩子把那些甜的饮料当水喝，肾的功
能必定受克制，肾主骨，而白血病是骨髓的异常，都有连带关系。所以五味不可偏胜，怎么
能把甜饮料当水喝呢？

现在的孩子盐给的也太早，一岁就开始吃盐，甚至跟大人吃一样的量。小孩都是肾虚的，因为
肾脏后发育，所以生下来都是大小便失禁的，走路也不稳，这都是肾功能没有发育好的表现，
直到青春期，我们的肾才发育完成。盐会造成肾脏负担，小孩的肾功能承担不了这么多的盐。
我碰到好多这样的病例，孩子到了十几岁，外表看着都好，却还尿床，无法医治，很痛苦，可
能就是因为喂养方式的不得当，过食甜和咸，给孩子的脾和肾造成了严重的伤害。所谓脾为先
天之本，肾为后天之本，这两个根本都伤了，就会造成孩子这样那样的疾病。

但是最近很奇怪的是很多家长来找我，说看到他们的孩子有很多地方都有青筋，比如关节上、
手上、甚至舌头底下都有很明显的青筋。我们说造成淤血症的主要原因是来自于情绪。现在的
孩子智力开发的太早了，两三岁就开始送去早教、幼儿园里学英语识字，学这个，学那个。思
伤脾，人一思虑身体就会郁结。孩子正在生发之时，一思考他当然会“淤” 。除了情绪之外，饮
食过多，长期的食积也会造成淤血。淤血症会影响孩子的身体发育，也会造成孩子心理上的压
抑，导致心理发育不健康。一般来说淤血症是大人才会得的，生活观念改变了，很多疾病都在
提前。

其实家长都是出于“爱”才造成这些问题。让孩子多吃多穿少动，是出于爱；不让孩子输在起
跑线上，很早就去学习知识，也是出于爱。每当听到别人说自己的孩子好聪明，一岁就唱歌，
两岁就识字，多好啊，于是就让孩子早早去学很多东西。

古时候的人想法和我们不一样。古人说到很多伟大人物的时候，都会说他们三岁还不会走路，
六岁还不会说话，这样的人最后会成为伟大的人物。反而那些什么都来得早的，成为长大没出
息或夭折的典型。万物皆有其理，早熟自然就会早衰，生命皆有其自己的轨迹。就像一朵花，
开得早凋零也早，生命能量都是有数的。所以古人不希望别人说自己的孩子聪明。古人也不希
望自己的孩子早熟，因为古人都是”道”的思维，希望顺其自然。早熟的人精神压力也大，年
纪太小，懂得却太多，没有足够的经验和心理承受能力去承受这些思想和知识带来的痛苦和副
作用。现在的人不考虑这些问题，好多孩子跳楼自杀，家长却不理解他们为何会有那么大的精
神压力和负担。

我有一个朋友，孩子三岁了，走路还走不好，需要踮起脚，不太稳当，她有些着急，我劝她说
“这在古时候是正常的，现在那些走路太早的反而不对，是不是吃了什么带激素的东西把孩子
催的早熟了，以后呢是不是会早衰？甚至早夭？又或者会造成什么疾病出来？”她一听就觉得
有道理，她就坦然了。她说她本身就是一个崇尚自然的人，平时住在山里头，吃的也是身边没
有激素化肥污染的粮食蔬菜。这样说来，她的的孩子身体里是干净的，发育的时间自然也会偏
于正常。现在正常的反而显得不正常了，你看看这个时代。

人类应该回过头来，想想自己的本原，顺其本性，不要一味求快求多。万物皆失其性，那就离
毁灭不远了！也只有顺其自然才能让孩子健康成长！

这两篇文章都是公众号“希彦馆”里的，里面有很多关于疾病养生的认识和理念，也是我们这
个课堂的一个补充。大家可以关注。

好，今天就讲到这里了，谢谢大家。

农历 四月十三
四月小
乙未年 辛巳月 丙午日
生肖 羊
日十二建 除
华夏黄帝纪元
四千七百一十三年

== 2015-06-13（268-272）

西历 2015 年 6 月 13 日星期六

伤寒经方求真群，伤寒论公益讲课

有请刘希彦老师。

大家晚上好。我们今天接着讲《伤寒论》的条文。

268、三阳合病，脉浮大，上关上，但欲眠睡，目合则汗。

我们接着讲少阳病的条文

这里讲的是三阳合病的情况。 “脉浮大，上关上” ，脉浮说明有表病；大脉是指大而中虚的脉，
这是津液虚而邪气盛； “上关上” ，脉的上部浮大明显，这是主上热的。
“但欲眠睡” ，我们前面讲温病和阳明病的时候说过，热病会有欲眠睡的反应； “目合则汗” ，目
合，人体进入半休眠状态才有汗，说明津液虚，人在正常醒着时候津液消耗大，没办法出汗以
驱邪。

综合来看，既有“脉浮”的太阳病，亦有上热津液虚的少阳病，还有欲眠睡的温病（温病必有
里热，实质上是太阳和阳明的合病） ，此所谓三阳合病，治从少阳就好了。小柴胡加生石膏和大
柴胡都可以考虑。

治病就是这样，不管证多么的不常规，或者多么的不常见，只要能弄清楚证后面的人体原理，
自然就能按六经思维将其归类并治疗。

269、伤寒六七日，无大热，其人躁烦者，此为阳去入阴故也。

伤寒六七天之后，病有可能往阳证转，也有可能往阴证转。 “无大热” ，已经没有太严重的热象
了。只是“躁烦” ，躁是躁扰不安，烦是心烦，这都是偏情绪的反应，是由津血虚引起的。前面
说过，人体一旦津血虚，便会启动烦躁的自保模式，一来是通过亢奋来加速津液的运行和供应，
二来也是通过提振人体状态来加速津液的生成。

既然是津液虚的躁烦，说明不是转入阳证，而是从阳入阴的趋势。

270、伤寒三日，三阳为尽，三阴当受邪，其人反能食而不呕，此为三阴不受邪也。

伤寒三天后，就该传三阴了。病如果得不到解决，人的津血就会因为抵抗邪气而衰退，自然就
会往三阴病走。 如果病人胃口很好，也不呕，说明胃气不衰，甚至胃中还有热。胃气不衰，津
血自然不会太虚，那病有可能是快好了，三阴应该没有受邪。271、伤寒三日，少阳脉小者，欲已也。
一般来讲，邪气盛的时候会出现弦脉、大脉、数脉、滑脉之类的亢盛的脉。脉平稳和缓了，哪
怕是脉小脉微了，也说明邪气已退，脉回到了原本的状态。这时候病就快要好了。

272、少阳病欲解时，从寅至辰上。

这几个时辰是凌晨三点到七点，犹如一天之中从冬到春的过渡，少阳病是对应春季的，顺其时
病自然得解。寅时是肺经主时，卯时是大肠经主时，辰是胃经主时。此三经均属里，肺为太阴，
大肠和胃属阳明。少阳病之本质原为胃弱，里气充实，胃气来复，自然能驱邪外出。

像这种以脉和时辰论病的地方，都是王叔和加的，联系上下文就不难看出。

至此，少阳病就讲完了。本章虽名为讲少阳病，并没有对少阳病有详尽的分析，这是因为前面
都已经讲过了。这一章侧重讲了少阳病和其它经病的传变，也是为了让大家更清晰少阳病在六
经病里的坐标关系。

少阳病篇的条文很少，因为前面在太阳和阳明的时候已经讲过很多了。

少阳病临床运用非常广泛，我们来讲两个医案吧。

曾某、女、成人

刻诊：脖子上长了个肿瘤，手摸有小芒果大小。汗出多，尤其是晚上。胸中和脖子略有阻塞感，
偶有气窜感。大便二三日一行，略不爽。脉象左右皆浮燥，沉取略偏虚；右脉偏有力。
患者不相信医院，亦不肯去医院检查，并不清楚究竟发于什么位置，亦不知良性恶性。找我诊
治。

辨证：病家证不多，亦不是很明显。胸塞便不爽可从半表半里大柴胡论治；汗出多，太阳病，
桂枝汤。病人有标热，加生石膏。散坚结，牡蛎石膏夏枯草半夏皆有此效。暑湿之月，将生姜
换成藿香。处大柴胡合桂枝汤加减。证轻药也轻，除半夏牡蛎外，剂量都不重。

处方：大柴胡合桂枝汤加减

柴胡 25 黄芩 15 生半夏 50 大枣 15 枳实 20 厚朴 20 白芍 15 藿香 10 大黄 6
桂枝 15 炙甘草 15 生石膏 60 夏枯草 15 生锻牡蛎各 25

效果：服药一周后，瘤子明显缩小。大便通，去大黄，再服。前后共服药十五剂，瘤子用手基
本就摸不到了。病势已去，停药。嘱其注意生活规律，心情舒畅，可用夏枯草煎水代茶饮。不
久后瘤子完全消失。

从这个案例我们可以看中医治病快不快，哪怕是这样的慢性病，用六经辨证来治，也是很快的。

曹某、男

正值降温，患者出吹了风，又运动出了点汗，于是胃的区域隐痛，但又感觉不是胃。用手按能
摸到里面有清晰的痞块。患者除了有轻微大便不爽，人感觉无力不舒服，没有其它明显的证。
脉象不虚，却也不实，寸略浮大。

这里有痞结，而且隐痛，是不是少阳病？要看区域，是在胃区，而且没有别的少阳证，那就要
斟酌。

辨证： “按之痛，寸脉浮” ，这是结胸证。按才痛是小陷胸汤的范畴。不按就痛是大陷胸汤的范
畴。大陷胸汤用药峻猛，而病人的脉没那么实，不按的时候也只是轻微隐痛。经方用药贵在客
观有据，兼而有之便兼而用之，但主次要分明，这种情况以小陷胸汤为主，加一点大黄，兼用
大陷胸汤之泻下之法。

处方：瓜蒌 30 黄芩 20 熟大黄 20效果：当时是晚上，药店已经关门，我手边只有以上三
味药，缺半夏和黄连，黄连以黄芩代之。

病人只服了一剂半，痛感和里面的痞块便消失了，其它症状也痊愈了。小陷胸汤总共只有三味
药，这里缺一味，代一味，病人还是很快就痊愈了，可见中医的灵魂是辩证思维，而非药物。

最近有很多朋友询问我，我的书怎么能买得到。我的《经方求真——道释伤寒论》上卷已经断
货了。新的即将出来，是全部的完整本。估计应该在一两个月之内就能印刷完成。届时请大家
关注群里的信息。

好，今天就讲到这里了，谢谢大家。

农历
四月廿七
四月小
乙未年 壬午月 庚申日
生肖 羊
日十二建 满
华夏黄帝纪元
四千七百一十三年

== 2015-08-22（273-277）

西历 2015 年 8 月 22 日星期六

群主-夏正安(409227821)

各位群友好，刘希彦老师的伤寒论讲座马上要开始了

之前因为刘老师在安徽屯蒙学舍开讲《伤寒论》 ，以及安排印书的事宜，不得不中断了一段时间
的讲课

这几天有群友来询问这个信息的真实性：

是屯蒙学舍的一位弟子前些天在群里发布的：

我在这里统一回复一下，

安徽屯蒙学舍发起的关于刘希彦老师《道鉴伤寒论》的助印，这个信息是真实的。请大家支持。

好，讲课正式开始，有请刘希彦老师

各位群友大家好。前段时间因为我的书稿《道鉴伤寒论》要整理完成，加上屯蒙学舍青年归藏
营的古中医课程是封闭式集中上课，耽误了一段时间，很抱歉。

今天我们继续讲《伤寒论》 。

之前已将讲完了三阳病篇，今天开始讲三阴病篇，首先讲的是太阴病。

从这一章开始讲三阴病。

三阴病一言以弊之就是：脾胃弱，津血虚少，人体对疾病呈现出消极衰退的反应。

我们说过，临证上辨表里病位，一般问证准确；辨阴阳，最准确的是脉。简而言之：诸如
细、弱、虚、空之类血管里血少的脉是阴病的脉；反之不是阴病。哪怕脉象迟缓，只要血管里
的血充实，也不可断为纯阴证；哪怕脉象躁数，只要血管里血虚少，也不可断为纯阳证。所谓
血管里血的多少是判断阴阳病的关键。

因为《伤寒论》论病不是每条都提及脉象，往往略去，但“脉证相应”是《伤寒论》的大
原则。以上便是作为对三阴病脉象的补充。

273、太阴之为病，腹满而吐，食不下，自利益甚，时腹自痛。若下之，必胸下结硬。

此条为太阴病之总纲。

陷入阴证必定因津血虚；津血虚必定因脾胃虚，饮食不能生化为气血所致。太阴病的病位
为里，亦可理解为里阴证，所以太阴病的总纲里首先提到的是脾胃系统的反应。

“腹满而吐，食不下”这事实上是脾胃系统几乎停止运行了，胃虚寒而不能运化便会吃不下
东西，吃下去的也不受纳会呕吐出来。腹部也是胀满的，肠道也不运作了。270 条说过，如果
病人胃口好便不会往阴证转，所以这里首先说的是胃口的问题。

“自利益甚” ，病人腹泻严重，腹部时而会隐隐作痛。这是寒泻。热泻一般会有排下有力，屁多
屁响且大便偏臭，肛门灼热之类的反应；寒泻虽然也难以自控，却不感觉到排下有力，也不会
屁多而臭。

“时腹自痛” ，这个腹痛也须和实热的承气汤证腹痛区别开。除了隐隐的间歇疼痛这个特点外，
虚寒的腹痛喜按喜温，按腹部或用暖水袋暖腹部会觉得舒服，因为里面没有热。实热的腹痛不
喜按不喜温，按之痛剧。所以腹部的证应该是要按诊的，现在运用的人不多了。

“若下之，必胸下结硬” ，这时候如果再用下药，就会胸下结硬。我们顺应人体来分析，这种结
硬也是一种人体的自保模式，它用一种痞结状态阻止身体的能量继续向下流失。这里的结硬和
结胸的区别是，结胸有按之痛或不按也痛，而这个结硬一般来讲是没有明显痛感的，因为只是
寒水之结，并无结热。

274、太阴中风，四肢烦疼，阳微阴涩而长者，为欲愈。

“中风”是指腠理开，体表丧失津液，风邪得入的证候，所以四肢烦痛。同时又是太阴病，
所以称为太阴中风。

脉浮取为阳，寸为阳。阳脉微，说明邪气已退。脉沉取为阴，尺为阴。阴脉涩为血少，同时又
长，说明气血已经来复，邪气去而正气生，所以说病快好了。

这里需要注意一下，为什么说“阳脉微”是邪气已退，我有这样的经验，诸如脉躁、动、大、
弦、数，如果不是因为气血充足，沉取不足的话，那就是亢燥所致，皆为身体有病邪，机体要
亢进起来逐病邪，所以现这样脉如果安定下来，回归本来的样子，往往是偏弱的脉。

病人往往脉象是亢燥的，如果脉象缓和了，说明病邪在退。这里说的就是这种情况。

有些阴证的病人，脉虽微弱，但平稳和缓，这样的是好治的。有些脉虽细弱，却弦、燥、散乱，
这样的是不好治的，说明病邪仍重；如果再不平衡，比如上盛下弱，如前后盛，中间弱，这也
是不好治的，说明大循环有问题。

我们给病人用了药，判断药用得对不对，不要但凭病人说的主观感受，因为病人的叙述有主观
有误差，应该结合脉象来审察。

277、自利不渴者，属太阴，以其脏有寒故也，当温之，宜服四逆辈。

太阴病的总纲里有一个鉴别要点： “食不下” ，准确说是脾胃虚寒的食不下。很多重症的病人，
临死前几天的反应就是吃不下，胃气绝了，任谁都救不了。这里又加了一个不渴。胃中虚寒自
然不想喝水。腹泻会脱水，一般来讲病人会想喝水的，如果还是不想喝水，说明里面已经很虚
寒了。这时候应该用温里之法，可以用“四逆辈” ，也就是用以姜附为主药的方子。

临证上，想不想喝水也是鉴别阴证一个要点，它直接反应胃里面是热还是寒。脾胃为中土，是
能量生化的中心，是全局的关键。一般来讲，不管整体是寒是热，只要胃里面是虚寒的，都可
以加一点姜温里。生石膏、黄芩、黄连这样的寒凉药和姜同用的方子《伤寒论》里很多，比如
大青龙、越婢汤、柴胡汤、半夏泻心汤等。反过来讲，如果胃里有热，能食索饮，这些方子里
的姜也可去掉。 《伤寒论》所授的是加减变化之道。

不管是什么病，如果病人现太阴四逆汤证，是好办的，先用四逆汤温里就没错。因为三阴病
治从太阴，也就是说，三阴病都要先温里，脾胃不吸收，自身都没有能量，就没有治病的前
提。

这里说说癌症，很多癌症的病人前期往往有内热，甚至现阳明病。这时候好办，是可以攻的。
麻烦是晚期的时候，往往现太阴病，一派虚寒之象，可病邪却没有退，反而进，晚期的癌症往
往有痞痛。这个时候有两个处理方法，如果太虚寒无食欲的，一定要先用四逆辈温里；如果食
欲尚可，或寒热夹杂的，可以在温里的基础上，加一点点攻的药，我的经验，这种情况是以大
剂量四逆汤为基础，可以加小剂量的陷胸汤或承气汤。

有的晚期癌症已有痛的病人，这样来治会很快止痛，立竿见影；有的已倒床不起的，能迅速恢
复机能，甚至能起来做事工作。

攻的药剂量一定要小，用几克即可。温里的药可以几十克不限。这样才有效果。现在很多治癌
症的，喜欢用散结攻破药一味的攻，不懂攻守兼施，如果病人阳气仍存或有作用，如果病人已
经久病阴寒到了晚期，只会促其速死，这样的情况我见过很多。

炮附子不要用药店的，现在统货都是化学胆巴制过的，没什么药效了。扶阳派用到几百克，药
效未必有多少，咸咸的喝下去都是胆巴。最好是遵循古法炮制的，也就是直接炒制的。如果是
重症病人没有古法炮制的附子，是会误人的。

好，今天就讲到这里，谢谢大家。

农历
七月 初九
七月大
乙未年 甲申月 庚午日 六月廿四
立秋 七月廿六白露
生肖 羊
日十二建 开
华夏黄帝纪元
四千七百一十三年

== 2015-09-12（279-280）

西历 2015 年 9 月 12 日星期六

群主-夏正安(

各位晚上好，讲课即将开始。

多了很多新朋友了。

很多朋友是从微信平台过来的，非常感谢大家对刘希彦老师的支持，对我们的原创文章的支持，
对汉传中医体系的认同。

有你们的认同与支持，我相信古中医一定不会消亡。

我们目前有两个 2000 人群，其中一群很早请就满员了。二群也是有一千多人了。

有少数朋友两个群都加了，请自行退出一个，

以留机会让更多新朋友能进来学习交流，谢谢

今晚刘希彦老师继续讲解《伤寒论》条文,

为保障讲课秩序，已经开启群禁言。

有请希彦老师！

大家晚上好。

今天先接着讲伤寒论的条文。

279、本太阳病，医反下之，因尔腹满时痛者，属太阴也，桂枝加芍药汤主之。大实痛者，桂枝
加大黄汤主之。

桂枝加芍药汤方

桂枝 三两（去皮） 芍药 六两 甘草 二两（炙） 大枣 十二枚（擘） 生姜 三两（切）

上五味，以水七升，煮取三升，去滓，温分三服。本云桂枝汤，今加芍药。

桂枝加大黄汤方

桂枝 三两（去皮） 大黄 二两 芍药 六两 生姜 三两（切） 甘草 二两（炙） 大
枣 十二枚（擘）

上六味，以水七升，煮取三升，去滓，温服一升，日三服。

太阳病是人体欲将病邪从表解，医家当用解表方顺势而为。如果用下药，属于误治。用了下药
后，病人腹满，时而会隐痛，这是邪气被下药引入了里，人体只得调整模式，从里解病邪，于
是发生了腹满隐痛的证。从所处的方剂来看，此时应该还有太阳中风的证，同时有腹部的隐痛，
属于表里证皆有。人体被迫要从表和里两个通道解病邪。本着先表后里的原则，还是以桂枝汤
为主方。这种腹满隐痛非实热的痛，而是津血不够，运化不力引起的，只需增加芍药到六两，
敛津液下行即可。

如果是大实痛，也就是里面有实热结滞，那就要用大黄了。还是本着先表后里的原则，用桂枝
汤加大黄。大黄剂量用得不重，二两。这里的二两应该是生品二两，去皮晒干后，折合成现在
的剂量，当在十克之内。说明这个所谓的大实痛没有严重到承气汤证的地步。如果真的那么严
重的话，是可以先下承气汤的。所谓在里证重急的情况之下，是可以打破先表后里的常规的。
这个大实痛在临证的时候也可以灵活的来看。 实是什么， 人体里面一切的淤堵都可以称之为 “实” ，
无论是食积淤血，还是痞块肿瘤。有实就可以下这个实，所以对于有淤堵的情况，临证都可以
在主方的基础上，增加一点下的药。大黄就是常用的下药。原来有一个老大夫，擅长治妇科，
他的经验就是在活血化瘀的药里加一点点大黄，不多，几克就好。效果非常好。

这在实质上就是给病邪找出路。 《伤寒论》的原则是看人体在哪个层面排病，就帮助人体从哪里
把病排出来，这又更高明了一层，是顺天而行的思维，这才是六经表里辨证的核心理解。

280、太阴为病，脉弱，其人续自便利，设当行大黄芍药者，宜减之，以其人胃气弱，易动故也。

太阴病的脉应该是弱的。脉弱，说明津血虚，同时又有热利，肠道有实热，这种情况也是常有
的，所谓的寒热夹杂证便是。在临证上，可以用建中的药合大黄芍药来治。甚至干姜和大黄，
附子和大黄同用，我在临证上经常这样用，效果很好。条文中的意思是，在这种情况下，大黄
和芍药还是要用，只是要减少用，因为胃气弱的人，只能经受得起小剂量的大黄，如果图一时
之快，大黄芍药下多了，伤了津液和正气，病反而不解了。一般来讲，这种情况我下十克之内
的酒大黄，宁可多服几剂，以图缓攻。

为什么内有实热的情况，条文里也归入太阴病呢？因为所谓六经只是一个坐标体系，人体更多
的病情未必在正坐标点上，而是在坐标点之间，甚至有交错情况，就像此条所说的，津血虚脉
弱，同时里面又略有实热。我们不需要去纠结六经之名，而要把六经当检索工具，找到病邪具
体的坐标和性质，然后用《伤寒论》的治病原则，按照实际情况变化组方治之就可以了。此所
谓不可死于句下。

至此，太阴病就讲完了。太阴病的实质是人体在津血虚弱的情况下，需要从里来排解病邪的局
面。治病的首要原则是建立人体能量，然后才是引能量去排解病邪。三阴病都有胃弱津血虚的
问题，所以三阴病的治疗都要以温中生津血为先。这就是所谓的“三阴病治从太阴” 。

有些朋友问黄斑病和高血压的治法，还问有没有什么方子可以治？

中医都衰落就是从认为一个什么方子就能治什么病开始的。

我们治的不是病，治病是人体，我们只是帮助人体开启该有的模式，所以伤寒论没有病名，
更没有说什么方药能治什么病，只是说治六经，六经病是人体自身的六种困局，可以这么去
理解。

我治黄斑病高血压没有什么固定的方子，按六经辨证来就好了。我曾经提到过 的那一例黄斑病
用的是小柴胡汤加几味祛湿的药，都是最常用的方药，就能治好。

至于高血压，这个病其实很简单，大可不必去吃药。说到底这是营养堵塞病，我曾经让病人节
食，尽量吃素，吃七分饱，然后多运动，结果十几天，血压就下去了。服了多少年的西药也没
办法完全下去。所以一个病总有一个来由，找药其实就已经是下策了。

我在希彦馆平台有一篇文章是专门讲高血压的，里面也提到一些方药上的运用。很多朋友可能
没看过，我在这里贴给大家。

用道家思维解读高血压

我是研究汉传古中医的，就是汉代之前的中医，汉代之前的古中医是道家思维的。道家思维又
是什么呢，说简单些，就是顺应一切天地之间的自然规律。既然用道家思维来看高血压，就要
去思考人体为什么会出现高血压。一切疾病其实都是人体为了应对某种特殊情况产生的应急手
段，所以用道家思维看待这个问题，就会明白出现高血压是有道理的，人体不是盲目的，人体
做的一切处理都是有道理的，那为什么要有高血压呢？先要搞清楚这个问题，之后才能谈到怎
么解决高血压。

说到人体为什么要升高血压，这就要牵扯到人类构造的问题。人类有两个特征，第一，直立行
走。带来一些问题，人的海拔与体重比例，相对于其他动物，是最高的。第二，人类还有一个
比其它动物容量大很多的大脑，大脑需要消耗很多气血。所以人类就存在一个困境，血压不够
的话，供不上大脑，大脑就要死亡。于是天地孕育人的时候，就有了高血压这种模式，来专门
应对这种情况。我们顺应人体来思考，高血压既然是人体自我调节的自然模式，那什么原因才
会造成高血压呢？

第一个原因，血液清洁度的问题

清水的话，流动起来会很容易，浑水则不易。现在的人营养摄入大大超过了所需，等到岁数增
长之后，身体机能走向衰退，对营养的需要只会更少，如果继续过剩，囤积的营养物质便会进
入血液，血液变粘稠，流动不再流畅，心脏难以将血液送上大脑，人体为了解决这个问题，就
升高血压，或者将血管壁变厚、变细，压力便升高，这样血液就更容易升入大脑，所以营养摄
入过剩是造成高血压的一大主因。

怎么解决呢，我的观念是人到三十之后就要逐渐转向吃素。大家就要问了，人是可以吃肉的，
为什么要吃素了呢。其实很简单，因为现在我们运动量太少了，大部分时候都在房屋里，要不
就是在车里，当然，如果你是运动员，或者体力劳动者，是可以吃一些肉的。也就是说，我们
的消耗与摄入要成正比才对。所以我们可以用减少摄入的方式，或者增加运动的方式让自己的
血液流通，这样不仅会减少患高血压的几率，也一样会减少癌症以及糖尿病的几率。

第二个原因，衰老的问题

我们中医讲，人老先老腿，腿是肾主管，人的元气在肾。肾是代号，指的是人的下焦系统，随
着年龄的增长，我们的肾功能会衰退。肾是人体的压力泵，压力泵的功能降低了，血液压不上
大脑，人体也会启动应急模式，将血管壁变细、变厚，就像水管，水压不够我们一捏，水就能
喷出来了。

衰老引起的这一类高血压，该如何办呢。通常来讲，就是要保养自己的肾气。肝肾都属阴，
所以要保养精气，晚上要早睡，不要过于操劳。还有就是，要常锻炼下肢，老是不走路，血
液不走下焦，也是很不好的。所以我们正常作息，锻炼下肢，这些都可以保养肾气。我们经常形容
一个老人身体好，就说腰板很硬，腿脚利索，这是因为下焦都属肾管，所以肾气好，高血压一
类的老年病，出现的可能性就会小很多。

第三个原因，身体里有淤堵

除了血液粘稠，肾脏功能不好，还有其他原因么。还有第三类原因，就是身体某一层面有淤堵，
有淤堵的话，人体就会升高血压，加大压力攻这块淤堵。身体里有淤血，有痰，都属于这一类。
还有另一种情况，体表不通畅，我们经常不运动并且思虑，这样容易闭塞，体表不通畅，人体
气血送不到肢体的末端，所以人体也会升高血压，送气血到体表。这一类我们统称为人体大循
环受限高血压。以上情况，痰湿就从痰湿攻，淤血就攻淤血，大循环问题的话，就让他生活规
律，减少思虑，也能让体表大循环通畅。

治疗高血压的千古神方——续命汤

治疗高血压，中医历来有个神方，续命汤。其实我们都知道中医是要辨证的，因人而治，这种
所谓的神方，只能说在多种情况下有用，也不是每一次都会有效。我现在来讲一下这个方子的
组成。

续命汤里面包含三类药。首先是解表药，麻黄桂枝，发汗，打通体表循环；第二类，当归川芎
这一类，去瘀血；第三类，地黄甘草，补肾补脾胃，有的还加炮附子，也是补肾阳补元气；第
四类，石膏黄芩，所谓清上热降血压的。大家看传统中医很有趣，后世中医会大量用银杏叶羚
羊角这一类降血压的，只治标，传统中医就很全面，都兼顾到了，所以才在高血压临床时，使
用率很高，所以大家使用时还是要辨证，不可滥用。

高血压的应对方法

高血压事实上是一个生活习惯病，也是身体正常衰退引起的疾病。用药物，就算一时降下来了，
生活习惯不好将来还是会出现，所以我建议大夫首先要将病人不好的生活习惯，引起高血压的
原因找出来，然后再说药物的事。关于药物的，我就不再说了，按照我前面说的传统处方，辩
证加减组合是可以的，至于辩证组方的方法，这是个大课题，大家可以关注我的教学平台，在
这里就不细讲了。

我在临床上见到最多的高血压病人，实际上还是营养过剩类型的多，中年以后酒肉多，又不运
动引起的。其次是情绪问题，长期思虑压抑，一般来讲这两类我见得比较多。

高血压有一个应急措施，假如病人有类似中风前的一些症状，像是晕眩，站立不稳时候，我一
般建议高血压患者，家里都放一些尖锐的物品在容易触及的地方，比如针，能够扎破皮肤的，
因为假如血管壁破裂，一些血液进入大脑，引起中风，事实上在这时，压力只差一点的，如果
差的多，全身的血管岂不是全破了，所以如果只是一点点的话，我们在手心脚心放血，压力放
下来，很快就可以缓解。

所谓解铃还须系铃人，一些疾病只要找到了原因就好办，当今医学的问题，就是很多疾病病
因不明，所以往往找不到很好地解决方法。我们也常见到一些高血压病人，长期服药，结果
越来越不好控制。也有住院的，做心脏支架，但是我们看到，就算这么处理了，结果也不一
定好，怎么回事呢。还是要用道家思维来想，这个既然是自然人体的模式，我们就要顺其自
然，不能采用对抗的模式，水只能疏不能堵，如果强行的去抑制，人体也只会积蓄更大的压
力来反弹，所以也常常出现打了支架之后，反而发生不良的情况，长期服药很多时候也会有
比较严重的情况在后期发生。到底该怎么处理高血压，相信大家知道了高血压产生的人体的
原理之后，都会有自己的思考和选择。

贴在这里大家慢慢的看。有兴趣的朋友也可以加我们的希彦馆微信平台。里面有很多传统古中
医思维的养生知识和防治疾病的知识。

今天就讲到这里了，谢谢大家。

农历
七月 三十
七月大
乙未年 乙酉月 辛卯日
七月廿六白露 八月廿六寒露
生肖 羊
日十二建 破
华夏黄帝纪元
四千七百一十三年

== 2015-09-19（281）

西历 2015 年 9 月 19 日星期六

各位群友晚上好，在讲课之前，我先说两句。

有群友提到刘希彦老师和我平常在群里说话的时候不多。

这点确实很抱歉，希彦老师非常忙，经常奔波于各地，来群里公益讲课也都是抽挤时间的。我
呢，每天除了接诊，还要捣鼓药材，杂务缠身，确实上网来与大家交流得很不够。

作为群主，没有起到踊跃发言的带头作用，望大家谅解。

我的想法，以后还是要尽量找机会与大伙做一些交流互动或医案分享。

接下来开始讲课。

伤寒经方求真群，伤寒论公益讲课。

有请刘希彦老师：

大家晚上好。

《伤寒论》的讲解已经过了多半。因为条文太多，很多没有逐条讲，只捡重要的讲了，不过很
快完整的书就要出来，到时候大家可以根据书来学习。

今天开始讲少阴病。

281、少阴之为病，脉微细，但欲寐也。

少阴病为表阴病，此条为少阴病之总纲。

“脉微细” ，前面说过，判断阴证和阳证，脉最直观。这里先讲脉，微细脉。 “但欲寐” ，
总想睡觉。当阳气运行于外，阴气运行于内时，人是醒着的；当阴气运行于外，阳气运行于
内时，人便睡觉。少阴病，表阴有余，病人便会发生“但欲寐”的现象。生活中，老年人比较
容易随时随地打瞌睡，这就是因为阳气的生发之力不够了，阴行于表的结果。现在的年轻人
容易失眠，是因为现在的生活节奏太快太紧张，阳气亢盛，阳有余而阴不足，所以晚上阴气
置换不出来，于是便入睡困难。这里关于少阴病讲的非常简略。我们前面学过很多关于阴证
的指证，比如怕冷不欲去衣披；比如肢体僵紧转侧困难；比如不欲饮食，饮则饮热；比如汗
出多小便多。这里不再重复，临证的时候是需要共参的。

其实只要是有表证，同时津血虚到阴证程度的，都可以用少阴病的思路来治。比方说我们前面
说过的桂枝加附子汤就是例子。表证为中风，同时津液大虚，于是加附子解决阴证的问题。 《伤
寒论》里这一类的方子很多，都可以归入少阴方，后面还会陆续讲到。

后世的医学不太行寒热并进之法，在他们的概念里，寒热的药在一起会抵消。其实他们忽略了
一个问题，就是药物还有层面，就是不同的药走不同的层面，有的走表有的走里，有的走上有
的走下。就像干姜是温胃的，而大黄是泻下，他们在一起作用的层面不一样。

《伤寒论》以层面辨证，所使用的药，层面的指向性也很明确。这也算是伤寒论的一个特色吧。
好，今天就讲到这里，谢谢大家。

农历
八月 初七
八月大
乙未年 乙酉月 戊戌日
七月廿六白露 八月廿六寒露
生肖 羊
日十二建 除
华夏黄帝纪元
四千七百一十三年

== 2015-11-07（281-294）

西历 2015 年 11 月 7 日星期六

群主-夏正安(409227821)

伤寒经方求真群，伤寒论系列讲座

有请刘希彦老师

经方-刘希彦(

大家晚上好。

今天接着讲《伤寒论》 ，少阴病篇。

281、少阴之为病，脉微细，但欲寐也。

少阴病为表阴病，此条为少阴病之总纲。

“脉微细” ，前面说过，判断阴证和阳证，脉最直观。这里先讲脉，微细脉。 “但欲寐” ，总想睡
觉。当阳气运行于外，阴气运行于内时，人是醒着的；当阴气运行于外，阳气运行于内时，人
便睡觉。少阴病，表阴有余，病人便会发生“但欲寐”的现象。生活中，老年人比较容易随时
随地打瞌睡，这就是因为阳气的生发之力不够了，阴行于表的结果。现在的年轻人容易失眠，
是因为现在的生活节奏太快太紧张，阳气亢盛，阳有余而阴不足，所以晚上阴气置换不出来，
于是便入睡困难。

这里关于少阴病讲的非常简略。我们前面学过很多关于阴证的指证，比如怕冷不欲去衣披；比
如肢体僵紧转侧困难；比如不欲饮食，饮则饮热；比如汗出多小便多。这里不再重复，临证的
时候是需要共参的。

其实只要是有表证，同时津血虚到阴证程度的，都可以用少阴病的思路来治。比方说我们前
面说过的桂枝加附子汤就是例子。表证为中风，同时津液大虚，于是加附子解决阴证的问题。

《伤寒论》里这一类的方子很多，都可以归入少阴方，后面还会陆续讲到。

282、少阴病，欲吐不吐，心烦，但欲寐，五六日自利而渴者，属少阴也，虚故引水自救。若小
便色白者，少阴病形悉具。小便白者，以下焦虚有寒，不能制水，故令色白也。

这里说的实际上是少阴和少阳的合病。 “但欲寐”是少阴；欲吐而心烦这是典型的少阳。
到了五六天的时候，小便多而且渴，这是少阴。因为少阴是表阴，表虚会出虚汗，当汗不能出
时，便会转由小便出，所以有一种小便多也是表虚或表阴证。小便多了，病人就会渴，这是津
液虚了，饮水自救。如果小便色白，说明体内没有热，少阴病的指证就更具备了。

后面说，小便色白是因为下焦虚寒，不能制约水了，所以色白。像类似这样语境的话，我怀疑
是王叔和加上去的。因为张仲景论病是大循环概念，一般会说此为表，此为里，或此为津液虚。
这里说是下焦有虚寒，人体是一个大循环系统，能量运行到体表，气化剩余的部分下行为尿液，
小便的颜色和多少难道仅仅和下焦有关？能不能制约水，难道只和下焦有关？关于水道系统的
论述，之前的文字显然没有这样的语境。就连猪苓汤也没有定义为是治下焦病的。这就开了后
世局部看待人体的先河。这本书的难读之处就在于有很多王叔和加上去的话，保不齐还有历代
传抄者加上去的东西。当然，我们也要感谢王叔和，没有他，我们今天还能不能看到这本书就
要打问号了

283、病人脉阴阳俱紧，反汗出者，亡阳也，此属少阴，法当咽痛而复吐利。

“脉阴阳俱紧”这是太阳伤寒，汗出应该脉缓。这里说“反汗出” ，说明汗出了还有紧脉，这个
紧脉就有点难以理解了。后面说的是亡阳，意思是亡了津液。津液虚再加上有邪气，哪怕有汗
出，也是有可能会现弦脉或紧脉的，因为血管里面的血少，一旦因为邪气亢盛起来，里面的血
有限，便只能摸到脉管变得紧张起来，而摸不到血液的鼓荡。所以这里的脉紧主的是亡阳。这
种紧脉应该同时有细，或沉取虚才对。条文里说这种情况属于少阴。

后面说会咽痛而吐利，说明胃气也很虚。那到底是少阴还是太阴，我说过，情况往往是交错的，
不可死于句下，临证时依据证的反应用相应的方法处理就好了。

284、少阴病，咳而下利谵语者，被火气劫故也，小便必难，以强责少阴汗也。

少阴病，怎么还有“谵语”这种阳明里热的证？后面说，这有可能被火疗劫发了汗。三阴病是
不能发汗的，发了汗，津液大虚了，小便也困难了，而且这种外源性的热邪强行进入了人体，
人体也要想办法排出去，所以有咳和下利这样的排邪现象。谵语是大脑缺津液，同时又邪热上
冲时，产生的调集津液的自保反应。这里应该是外源性的热进入了人体，且灼干了津液。

虽然很混乱，随证处理就好了：津液虚，辨明阴阳，姜附草枣地黄阿胶都可用；热邪，分清层
面，滑石、猪苓、大黄、石膏皆可用。总之行寒热并进之法即可解。

287、少阴病，脉紧，至七八日，自下利，脉暴微，手足反温，脉紧反去者，为欲解也，虽烦下
利，必自愈。

少阴病， “脉紧”说明有闭阻之寒邪。一般来说，如发生紧、弦这样的脉象，就可能跟宿食、淤
血、痰饮之类的淤阻有关系。若自身没有淤阻，大循环通畅，哪怕气血虚一点，也很难有缠绵
不去的病邪。所以任何疾病的发生内因永远是第一位的。

条文中说，到了七八天的时候，病人忽然下利，下利说明人体将里面的淤阻排出来了，这时候
“脉暴微” ，脉迅速变微弱了，因为邪气去了，脉不紧了，就回到了原本的微弱的脉象。而此时，
手足反而温暖了，这是大循环通了，气血能走到肢体末端了，脉也不紧了。这就是病快要解了。

这时候虽然还为下利所困扰，但一旦邪气排尽，就会自愈的。从这一条再次可以看出，
《伤寒论》看人体是很简单的，无非是能量和循环的问题而已，见过农村的柴灶吗？你只要
明白烧火的原理，就能明白医学的原理。医学该回到简单直接的思维上来，大道至简，弄玄
虚了，只会妨碍我们对人体的真实理解。

293、少阴病，八九日，一身手足尽热者，以热在膀胱，必便血也。

少阴病本为津液虚，到了八九天的时候，人体的阳气回来了一些，而津液却因久病而亏耗。人
体的阳气要亢盛起来去排邪气，这时候无足够的津液可以调动，只能强行调动血液来帮助排邪
了，于是发生“热在膀胱” ， “便血”的热象。有称此种情况为“少阴热化证”的。这样说也通，
因为阴证的本质在津血虚，而不在于寒热，临证我们会发现，阴证的病人，上火、长痘、长疮
的也不在少数；厥阴病更是以有明显上热为特征，少阴也有热化，就连太阴都偶见外热内寒的
格局。所以，后世的医家，见火便清火；见血便凉血止血，而不从人体的大局和自身之作为去
思考问题，此为最常见的流弊，不知害了多少病人。

我曾经碰过一个牛皮癣的病人，脉证一派阴寒，夏天都穿着长袖夹克，再问吃过的药，说这些
年吃过的金银花丹皮生地论麻袋装，病却只进不退，这就是把癣疮等同于血毒和血热，然后见
毒解毒，见血凉血，典型后世医家见病治病的思路。

294、少阴病，但厥无汗，而强发之，必动其血，未知从何道出，或从口鼻，或从目出者，是名
下厥上竭，为难治。

少阴病， “但厥无汗” ，四肢厥冷，没有汗，津液大虚了。如果强行发汗排邪，人体无津液可调
动，只能调动血液来排邪。因脾胃大虚，中土不能制衡，很可能失其常度，血就要从口鼻从眼
睛出来。这种极端的情况名叫“下厥上竭” ，下面已经厥逆，上面却还在耗竭血液，说明人体已
经完全逆乱了，是很难治的。

《伤寒论》的讲解已经接近尾声了，大家可能发现，其实现在讲的课重复的概念很多。 《伤寒论》
是六经串讲的，其实在前面已经把六经病都涉及到了。

我讲课这一年多来，一直有朋友在问面授的事情，说希望有面授。实际操作的层面，的确是需
要面授的，包括临床上如果运用， 《伤寒论》独特的脉法到底是怎么样的。这都需要一个贯通式
的教学，来打通所学的知识，形成一个辨证的临证思维。

所以我计划了两个面授班，一个在北京，一个在上海。这都是初学者和学过的都适合的，因为
是拉基础大框架，打通式的教学。

之前有放通知在群公告里，现在北京的班已经满员了，上海的班还剩几个名额。大家若有需要
可报名。

http://url.cn/fkRQqy

这是开课的信息链接。好，今天就讲到这里，谢谢大家。

农历
九月 二十六
九月大
乙未年 丙戌月 丁亥日
八月二十六寒露 九月二十七立冬
生肖 羊
日十二建 除华夏黄帝纪元
四千七百一十三年

== 2016-01-22（301-303）

西历 2016 年 1 月 22 日星期五

各位群友，晚上好，大家期盼的刘希彦老师的伤寒论公益讲座，今天继续开讲。刘希彦老师
近来忙于北京、上海、安徽等地巡讲，很辛苦。有请刘希彦老师

大家晚上好，前段时间忙《道鉴伤寒论》的事情，没有给大家上课，抱歉。今天继续讲伤寒论。

301、少阴病，始得之，反发热脉沉者，麻黄附子细辛汤主之。

麻黄附子细辛汤方

麻黄 二两（去节） 细辛 二两 附子 一枚（炮，去皮，破八片）

上三味，以水一斗，先煮麻黄，减二升，去上沫，内诸药，煮取三升，去滓，温服一升，
日三服。

少阴病是表之阴病，阴病不可发汗，我们前面学过，麻黄和桂枝的组合是发汗的，因为桂枝是
解肌，能将肌肉里的水湿逼出来。这里不能发汗，而病又在表，于是用了麻黄和炮附子的组合。
炮附子是温阳的，因为炮过，通行之力减了，能量不至于迅速走散，更能停留在肌体里，而温
全身上下之阳。当体表的阳气足了，自然就能将邪气排出去，炮附子也有固摄阳气的作用，所
以能用于阴证虚汗的止汗，也能用于温下寒。生附子更多的是通行经络的作用和气化的作用。
当四逆的时候，生附子能将能量迅速送到肢体末端形成循环；当阴寒下利的时候，生附子能振
奋肠胃形成气化。四逆汤里是生附子，因为四逆汤的主证就是四逆和下利。

细辛这个药有一种芳烈窜升的香气。 《神农本草经》认为它主要有三个作用：主咳逆、除湿痹、
利九窍。这里用细辛，对比前后条文来分析，应该是因为有“脉沉” 。脉沉在这里是说明里面有
寒痰或寒饮之凝结，所以细辛是合用的。

说到细辛的作用，就要和麻黄、桂枝来做对比。桂枝的香气相比细辛，更厚更浓，质重则不能
行远，桂枝的作用基本上是脾所主的路线，从中焦气化到肌肉而已。

麻黄没有香气，没有香气则没有形质，无形的东西走得最远，比如声波，比如光，所以麻黄是
开周身之孔窍的。没有形质也有个缺点，就是犹如刀没有柄，它没有力量，所以麻黄合桂枝这
样的药就能发汗，单用则不能。麻黄和炮附子的组合是治少阴的主方。因为炮附子主温阳振奋，
而非主发散。

细辛介于两者之间，比起麻黄它有香气，比起桂枝它香气偏轻。轻则升，所以在《伤寒论》里
细辛主要治咳逆和上焦的寒痰凝结。

有一个问题，既然是阴证，为什么没有炙甘草之类建中补津液的药呢？这就是我推断细辛在这
里是针对寒痰凝结原因。在经方里，如果要去攻一个顽固的结滞，是不会用甘草的，比如抵当
类、陷胸类、承气类的方子大都没有炙甘草，因为甘以缓之，甘味会缓和攻的力量。

302、少阴病，得之二三日，麻黄附子甘草汤，微发汗。以二三日无证，故微发汗也。麻黄附子甘草汤方
麻黄 二两（去节） 甘草 二两（炙） 附子 一枚（炮，去皮，破八片）

上三味，以水七升，先煮麻黄一两沸，去上沫，内诸药，煮取三升，去滓，温服一升，日
三服。

这个就是少阴病的正治方了，用了炙甘草。条文中说“以二三日无证，故微发汗也” ，应该是指
刚病了两三天，还没有那么严重的阴证出现，所以可以稍微发一点汗。其实这个汗与不汗，是
要看人体自己的，人体有能量可以汗出以排邪，它是会出的。麻黄合附子不是发汗剂。这里的
意思是有可能会微微出点汗，并不是一定会出。古书行文太简，需要根据一贯的语境和规律来
理解。

麻黄附子细辛汤和麻黄附子甘草汤的寓意是一实一虚。一个是里有寒痰寒饮，为实，用细辛温
散之；一个为虚，用炙甘草建中补虚。这个思路和前面的大小柴胡汤，麻黄汤和桂枝汤的思路
是一以贯之的。

303、少阴病，得之二三日以上，心中烦，不得卧，黄连阿胶汤主之。

黄连阿胶汤方

黄连 四两 黄芩 二两 芍药 二两 鸡子黄 二枚 阿胶 三两（一云三挺）
上五味，以水六升，先煮三物，取二升，去滓，内胶烊尽，小冷，内鸡子黄，搅令相得，
温服七合，日三服。

前面说过，当津血虚极的时候，人会眩冒躁烦，这时候不要误以为有热，这是阴阳离绝的死症。
如果津血没虚到那么严重，人体只是出于自保亢奋起来产生虚热，会出现什么情况？那就是现
在这种情况“心中烦，不得卧” 。

这个“心中烦”是有上热的。津血虚不够供给身体所需，人体便用烦来亢奋，加速运行来生成
与供给。在脉象上的反应比较常见的是细数脉；也有可能是大脉，也就是大而沉取虚的脉。细
和虚说明里面血少，阴虚；数和大说明推动力有，阳热不缺乏，也就是阴虚阳亢。这种情况，
一般来讲用生地、阿胶、麦冬这样的滋阴药就可以解决了。阴补上去了，阳火就制约住了。如
果阳火更偏胜怎么办？那就是现在这个方子，不仅用阿胶、白芍、鸡蛋黄滋阴强壮，还用黄连
和黄芩清热。所以中医说简单也简单，中道之医而已，在能量上不是越强越好，要取居中平衡。
过与不及都会生病。现在那些顿顿吃肉还敢进补的人，其实很多病是花钱补出来的，偏离中道
了。

“不得卧” ，不能躺下，躺下也不能睡。这种情况现在很多，很累了，想躺下睡一会儿却睡不着，
烦乱，甚至躺都躺不了，稍躺一会儿心神不安的又要起来。问题还是出在津血虚上。当人血虚
的时候，心脏每跳动一下的带血是不够的，这时候人体出于自保，不会让你深睡眠。深睡眠的
时候，心跳极缓，带血就更不够了，人体组织就要缺血，大脑容易缺氧受损。所以血虚的人睡
眠是很浅的。更严重的血虚，人体就不让你睡了。很多人用吃安眠药来入睡，久而久之会失效，
因为人体的自保机制也很强大，它和安眠药的抑制作用是相反的力量，是对抗的力量。血不够
而强行抑制入睡的话，有猝死的危险，这就是为什么有人服了安眠药就醒不过来了；老人有时
候会在睡梦中自然死亡也是同样原理。

有医家说，这个方子是治“少阴热化” ，倒是也可以这么说，但这个方子所治是不是归属于
少阴呢？其实不必分得那么绝对，只要是阴虚而阳火偏胜都适用。人体只要产生这种困局就
可以用这个方子去解这个困局，就可以治一切因此而产生的病。我举一个古代的医案：有人
得了腹水，很多医家治过没治好，用药无非是健脾利水祛瘀之类。后来有一个医生开了大剂
量的阿胶和白芍，病家不敢服，说阿胶滋阴，白芍敛阴，病人有腹水，怎么能服这个药呢？
后经医家劝告大胆的服了下去，一剂腹水就消下去了。这个例子说明，药不是治病的，药是
作用于人体能量场的。当人体阴虚阳亢的时候，会不会出现腹水的情况呢？可能不多见，但
也是会有的。这种时候，只有先让人体能量场回到正常状态，人体才有可能自己去排病。换
言之，只有人体自己能治病，药物怎么能直接治病呢？后世医学之弊，就是臆想某药治某病，
而不去研究药物和人体真正的关系和作用。这就只能动辄拿经验说事，但经验总归会时验而
时不验，验了不知道为什么验，一旦不验又不明白为什么不验，然后就束手无策。

好，今天就讲到这里，谢谢大家。

农历
十二月 十三
十二月小
乙未年 己丑月 癸卯日
十一月二十七小寒 十二月二十六立春
生肖 羊
四九第 5 天
日十二建 满

== 刘希彦简历

刘杰（1976— ） ，字希彦。古中医研究者，古琴家，编剧，作家。国学研究者，在古琴、红学、
京剧等传统文化领域皆有造诣，师从于吴派古琴大师汪铎，致力于古中医的研究、恢复及传播
多年。亦是作家、舞台艺术家、编剧，其创作的舞台剧作品曾获国际舞台艺术丹尼奖。著有《经
方求真——道释伤寒论》一书，并创作有随笔集《纸醉金迷多忧愁》 。

中文名：刘杰；别名：希彦；国籍：中国；民族：汉；族出生地：湖南武冈；出生日期 1976
年；职业：编剧；毕业院校：中央戏剧学院；代表作品 《经方求真——道释伤寒论》~《纸醉
金迷多忧愁》

古中医

刘希彦自幼倾心中国传统文化，从上世纪九十年代创作至今，从未停止过对国学的学习和研究，
立志将传承国学文化作为自己真正的理想。闭门研习道家古中医近十年，用真正的传统中医思
维临证治愈了诸如肿瘤、黄斑病、肝硬化腹水、肝纤维化、糖尿病、狂躁症、哮喘、不孕不育
等大量的重症绝症。并且授徒多人，有许多医药大学的学生及各大医院的专业中医慕名向其学
习。

2014 年，与医友夏正安创立“伤寒经方求真群”网上公益授课平台，短短几个月学员便上升到
一千多人，居全国中医网上教学平台学员人数的首位。自首次开讲之后每周授课一次，好评如
潮，每周六晚上成为众多中医从业人员，中医爱好者期盼的时刻。

医圣张仲景的《伤寒杂病论》为传统中医的根，是中医临床的圭杲，亦是历代医家难以参透的
最高经典。刘希彦在《伤寒杂病论》的研究上尤其精深——强调把握药物的“本” ，理解人体运
行“大秩序” ，不仅仅停留在方证相对，死守原方原剂量，而是活学活用。

希彦老师认为其道源于《道德经》的道家思想，其术源于《易经》 。讲道家医学就要讲无
为，讲顺应天然。医学自仲景之后，整体趋势是越来越有为，越来越喜欢滥用药物对抗疾病。
希彦老师在讲义里说：两千年来，我们非但没有让中医有所寸进，反倒让中医治病从覆杯而
愈、一剂而解，沦落到中医不治病，中医治病慢，中医只能调理的境地。在讲义里，希彦老
师还说：毋容置疑的，中国文化也好，华夏医学也好，一定有过一个今天无法企及的高度。
“盛极必衰”这是天道，连《伤寒论》这样的医学普及读物，近一千多年来竟然都说难以参透，
可见中国文化早已衰落了。不过我们也不必悲观，所谓“否极泰来” ，人为因素导致的断层，
中国文化算是“否”到极点了，也许快到“泰来”的时候了，怕就怕“泰来”的时候到了，文化却
消亡了，所以要靠大家来留存最后一炷香火。

同年，在好友张影伦的帮助下，创建公众号“希彦馆” 。

影视经历

2001 年创作电视剧《爱在阳光灿烂时》 ，主演陈坤、李小冉，该剧为最早一批偶像剧中收视率
最成功的剧目之一。

2003 年与香港著名导演关锦鹏合作，创作根据文学家巴金先生著名小说改编的同名电视剧《家
春秋》之《春》 、 《秋》二部。

2005 年创作以上世纪二十年代上海最早的时尚行业为背景的电视剧本《海上繁华梦》 ，该剧本
以史诗般的铺排和极富旧上海气质的笔调在业界引起轰动，被很多影视策划人和剧本编辑称为
是商业和艺术结合的典范，刘希彦更被誉为是“为数不多能将电视剧写出气质的编剧” 。

刘希彦因此剧本和著名的大师级编剧盛和煜结缘。盛和煜曾创作过《走向共和》 、 《乾隆王朝》 、
《夜宴》 、 《赤壁》等多部大剧大片，并且是湖南卫视大片办主任
。2007 年在湖南省广电领导的主持下，刘希彦和盛和煜正式拜师，并共同组建影视工作室，合
作至今。

在与盛和煜合作期间参与了大量优秀项目，尤其值得一提的是根据《红楼梦》改编的电视剧《黛
玉传》 。此剧和新版《红楼梦》同时面世。

和盛和煜合作期间，刘希彦延续其做大剧做名著的路线，后又参加了根据方芳小说改编的电视
剧《武昌城》的创作。

2010 年，刘希彦进军电影行业，加入刚刚成立的乐视影业任剧本总监。为乐视影业的创立和资
源奠定贡献了重要的力量。期间参与了大量电影项目的策划和开发。后又加入蓝莓国际影业任
剧本总监。期间还担任编剧为该公司创作了电影剧本《敦煌》和《武则天》 ，并参与赵宝刚电影
《触不可及》的剧本策划。

舞台作品

为北京当代芭蕾舞团创作舞剧《金瓶梅》 （又名《莲》 ） ，导演王媛媛，舞美叶锦添，音乐陈其
钢。2010 年全球首演于香港艺术节，现为该团保留剧目常年在国内外演出。

为北京当代舞团创作舞剧《希·夷》导演：杨海龙、曹沛仲。此剧荣获第二届丹尼国际舞台表
演艺术奖评委会特别奖。

与著名音乐人李泉合作，为贵州省建省六百年创作非物质文化遗产主题剧目《鹡宇鸟》 。担任
作词的主题歌《云中的鹡宇鸟》被范逸臣、杨培安、李琦等多位歌星翻唱。

为北京当代舞团创作大型舞剧《警幻绝》 （又名《镜花昙》 ） ，导演赵梁，2011 年 12 月于北京全
球首演。现为该团保留剧目，常年在国内外演出。

为北京当代舞团创作大型舞剧《莎乐美》 ，导演朝克，杨海龙。2010 年 12 月于北京全球首演。

为浙江省话剧院创作六十年院庆剧目音乐剧《果果的绿野仙踪》 ，导演钟浩，现为该团保留剧目，
亦为国内演出场次最高的儿童剧之一。

为新疆省鄯善创作大型旅游实景演出剧目《梦回楼兰》 ，导演王俪桥。
