= 正安“立新七针”培训课——七问解答
冰台
2014-10-8 00:00

通常情况下，每个人总是站在自己的角度去看问题，所以就一定会有不同的疑问和见解产生。
因此立新七针的培训班也一直面临很多人的疑问，如果我避而不回答，那就难免令人产生更
多疑神疑鬼的问题出来。但是所有真正了解立新七针的人都知道立新七针是光明磊落的，所
以我不但要回答，还要公开回答这些问题。

[qanda]
你的技术短短九天时间学员能学多少，会不会因为学艺不精而坏了你的声誉？::

冰台回答：真正学中医，其实就是要明白事理。我的课程就是教学生明白事理，让他们做一
个“明医”，不做＂名医”，因为名医有可能是靠运气成功的，而明医则不受天时地利人和
的制约，他们懂得如何运用机会去成功。立新七针的培训课程是传授思维方式，通过几天的
培训，让学生们尽量多的懂得自然之道，今后养成从自然的角度去思考问题，并左右自己的
行为方式，把吃进肚子里去的食物变成自己身上的肉。这样就避免了千人一面的状况发生，
每个学生将来都会拥有世上唯一的、自己独到的针法，所以立新七针的培训课，不但师徒之
间不会互相影响，学生与学生之间即使隔壁开诊也不会互相影响，而且今后他们的事业一定
越做越好，立新七针的价值体现就在这里。如果仅仅传授技术的话，那其实是没什么价值的，
如果只教你学招式，学某针法具体治某病，那三千六的学费也显得贵了。因为技术就有局限
性，受天时地利人和的影响，老师用得好你未必也用得好，所以只懂得技术的医生大部分都
只是庸医，极少数运气好的人能做个名医，主要还是由于他们对事情的来龙去脉没搞明白。

全国这么多人学了后都去开店的话，会不会影响你的生意？::

冰台回答：立新七针培训课程传授的是思维方式，思维是无限的，取之不竭，用之不尽，所
以思想灵活的老师根本无需保守，即使倾囊相授，转身立刻又会有新的能量产生。学生在进
步，老师也在进步，而且老师的起点高，进步会更快，士别三日当刮目相看，除非这个老师
整天忙碌着讲课治病挣钱，根本无暇思考研究总结，或者遇到的学生悟性极高，天赋很好，
否则老师永远都是老师，学生望尘莫及，又如何能够影响到老师的利益？做老师的，都巴不
得能够遇到悟性天赋都是一流的学生，倘若败给这样的学生，那便是三生有幸。你所担心的
问题，只存在于通常情况下的那些培训班，老师传授的只是技术，技术是有限的，师傅就那
么几招，市场就那么大，教会学生就会饿死师傅，那师傅就一定会保守。所以如果你明白立
新七针培训课程的真相以后，你担心的这些，都不是问题了。

我是一名乡村医生，关注您好几年了，近期按照陈老师的理论我尝试着自己做针，扎针的确效果立竿见影，更加使我学习的动力倍增。想参加你的培训，但我只有乡村医生证，没有执业医师证，可以吗？::

冰台回答：中国古代的名医，如果按照现在的法规去定义，他们绝大多数人都是在非法行医，
但他们很多都是明医。决定是否可以行医的真相，其实应该是由医术实战的高低来判断。只
善理论不善实战的医生，即使拿到行医资格也只会忽悠害人，哪里谈得上治病救人？世界是
变化的，现在是以书本理论知识去考取行医资格，但谁也不能保证十年二十年以后国家政策
还是这么个规定。而且在务实的患者们心中，医生能否快速彻底的治好他们的病痛，比医生
是否拥有合法行医资格显得更重要。我们说机会永远是为那些有准备的人而准备的，所以聪
明人一定是把重心放在提高实战技能方面。

你们收女学徒吗？::

冰台回答：中医是讲阴阳的，孤阴则不生，独阳则不长，阴阳也代表男女，所以立新七针也
不可能只是男人的天下。

我是西医，想学立新七针，但我担心听不懂您的课。::

冰台回答：立新七针的课程是从生命和自然的角度去讲解中医针术，用所有人都能明白的生
活现象和道理去教学生们思考问题。立新七针源于黄帝内经九针，内经的诊治思路和西医理
论有天壤之别，一个是从自然社会人文事物各种规律现象方面去获得理论支持，一个是从实
验室运动力学尸体解剖小白鼠身上获得理论支持，格局完全不同。可以说两者都是科学的，
若要说谁更符合生命的需求，就看你站在什么角度去看了，因为在科学面前我们所有人都是
盲人摸象。但我教学生有一个法门，那就是任何事都不要仅靠自己的耳朵和眼睛做主，所有
结论都必须用脑子独立思考，通过信解行证得来，这样你学什么都无需顾虑，多多益善。

中医爱好者可以学吗？::

冰台回答：中医爱好者可不可以学立新七针，这个问题其实应该是摆在次要去考虑的，首先
你要搞懂你该不该学立新七针，也就是说你想来参加这个学习班的目的是什么？爱好中医没
错，但如果条件受限，却想把中医当成事业来做，那就错了。道理如下：一，学医需要有一
个学习消化吸收的过程，并不能立刻把你投资的学费转变成可观的利润，如果你穷得迫切需
要挣钱养家糊口，那就千万不要把学医行医当成自己的事业来做，心急吃不得热豆腐，借钱
学医和倾家荡产去学医的人，最后结果往往都是损人害己。所以穷人当下应该做的事，是首
先找一份工作去打工，挣到生存的必须费用，学中医应该是在解决了自己和家人温饱的前提
之下，才可以付出这份精力，这个道理务必要明白。二，学医术如同做生意，做生意你先要
考虑的是市场和销路问题，不能看到货好就赶紧掏钱进货，等到把货拉回家才发现缺乏销售
渠道，那怎么办？医术这玩意儿就是要在明理的前提下不断在临床中实践积累，否则囤货一
辈子也就只是拥有个理论，理论家最多就写几本书赚几个稿费，变不了超级利润，不能产生
超级利润的医术是没有出路的，在旮旯处悄悄摆个地摊，那你得多久才能赚回成本？再说摆
个地摊如果没合法手续还要被执法人员追得四处逃命，这样的行为就是犯傻。三，学医又不
同做生意，买卖是面对商品，商品是死的，很容易摆弄，一进一出差价就出来了，或赚或赔
取决于市场风云变化，顶天最多就是钱的问题。但行医则面对的是活人，活人有思维会跑动，
那就有变数，不容易掌控，如果你不明疾病的来龙去脉，不明事理，那就随时都可能遇到非
常大的风险，这可是人命的问题，出了事你会一夜白头甚至承担牢狱之灾，所以这些问题才
是你首先需要考虑的。

我不是从医的，也不靠学这个挣钱吃饭，我是听朋友说您的理念很好，可以让我去参加学习吗？::

冰台回答：你这个出发点非常好，我很支持，我甚至提倡“学医不为行医”，这是一种很高
的境界。绝大多数专业医生来参加学习的首要目的，是想改变自己的处境和经济收入，发心
不同，结果也就不一样。首先，你不为生计发愁，不为挣钱而学医，这样你就可以非常安静
平和的去研究医术，往往更容易弄通透很多事理，也就更容易成功。我以前的培训班里有几
个学员就不是医疗行业的，他们有的是企业老总，有的是单位工程师，有的是设计师，有的
是从事证券的，他们不缺钱，他们学医的目的也不是为了用医术去治病挣钱。他们来跟我学
习的目的，主要是想弄明白人体病痛的真相，当他们身体出现一些病痛的时候，能够很清醒
的明白自己该何去何从，不让自己和家人被某些无知的医生或谬误的医术所伤害，所以我很
高兴的欢迎他们来学习。其中有一位证券行业的学员，他在历经若干次的挫折与失败之后，
领悟到一些东西，近年来事业上收获颇丰，一个很偶然的情况下听到朋友在介绍立新七针的
诊治思路，觉得很有道理，就报名来参加学习，他只是想寻找到一种能让自己坚定信心的理
论支持。结果他发现他在金融行业的投资思路与我讲的黄帝内经的针灸思路非常相似，根本
理念都是一样的，九天的课程听得他欢天喜地，大呼不虚此行。在立新七针看来，生活中所
有的事，我们如果在不明真相的情况下参与了进程，都是在赌博，赌博的结果不是害别人就
是害自己。行医治病的道理也如此，医生如果不探明病痛的来龙去脉，茫然下手，不是害患
者就是害自己。股票也是一样，如果仅仅靠耳朵和眼睛去炒股，那一定是凶多吉少，只有真
正弄明白事情的真相和规律，你才会立于不败之地。
