= 针所不及
冰台
2014-5-23 00:00

再好的理论，也必须靠实战的征服才能够证明你的重要性。常规的中医学是先学理论，然后
以理论去指导临床实践。而我非常有幸，没有学过系统的现代医学理论，所以我读内经的时
候，是先积累了一些实战经验，反过来从实战的角度去寻找内经理论的支持，也就是反其道
而行之，以实践指导理论。因为我在生活中懂得一个道理，野孩子没人瞧得起他，哪怕地位
非常卑贱的乞丐也不会对他客气，但达官贵人的孩子出来，年纪再大的百姓见了心下也油然
而生几分尊重。七针师出无名，所以曾经有一段时间凡是个会动的东西都要跑过来往七针头
上拉泡屎，你没经历过体会不到那种感觉，屈辱啊。

所以我一定要寻找合适的内经理论来包装我的实战经验，以证明我针术疗效的科学性。因为
在我看来，《黄帝内经》是中医界绝对权威的大佬，大佬说是对的就是对的，大佬说是错的
就是错的，一般人没法也不敢违抗。这一步骤是必须的，如果我不寻找内经支持，我实在想
不出这几支针还能怎样才能活下去？还有比黄帝内经更早更成系统更权威的吗？当我找到合
适的内经理论，把这些针术针法与内经紧密结合起来，并且得到一些有一定境界的同道中人
认可的时候，我觉得可以公布公开了，把这些针放养到自然社会中去，让所有人都去运用，
让更多的人充分感受到内经古九针的魅力所在，我们就用这样的方式去振兴中医针术。

任何新生事物都免不了饱受同行的争议和打击，情有可原，我也懂。医疗界毕竟大家都是有
学问的知识分子，地痞无赖是相当的少，偶尔有拱出来找茬的家伙其实都不是真正的学医的
人啦，所以相对而言，也算一片净土，只要是真早有生命力的，都必定可以繁荣生长起来。
而且知识分子们是讲道理的，他们一根筋的比较多，不懂转弯，所以遇到可能的攻击的时候
呢，我们可以运用多转几个弯弯圈的策略去化解他们的拳头，也就是太极的圆，一个圆可以
四两拨千斤，三个五个圆呢，就只需用五钱拨千斤了，当一根筋看到自己一千斤奋力扔进去
听不见个水泡响声，就把他给整蒙了，他也就闭嘴了。

排除很多的干扰之后，就可以一路走得比较顺畅一些。当然，打铁还需自身硬，要化解面对
的强大力量必须要有前提的，首先七针的强大疗效是实实在在明摆着的，不畏惧任何挑战，
不服，是骡子是马就拉出来遛遛，别忘了七针虽然没文化，但它们的名气都是在艰苦环境里
身经百战打出来的；其次七针的针具和理论是出自《黄帝内经》，无论从里往外分析还是从
外往里分析，都经得起推敲，都可以解释通透，理论讲出来我懂你懂他懂大家都懂，也就是
说大家公认七针是《黄帝内经》的血统了，而且还道法自然，所以这七针也算有强大后盾支
撑了；第三点非常重要，国人普遍有羡慕嫉妒恨的情怀，我分析过这些心态和后果，基本上
招损的那些，都是那些比别人强的个体自然人居多，通常是没有人面对一个乞丐或地痞无赖
之流会产生羡慕嫉妒恨。目前我又毫无保留的拿出来与大家资源共享，这是为中医做的一件
好事，我已经空了，你还羡慕嫉妒我个啥呢？而名誉来说，我自己尽量退缩到后面，让那几
支针在前面成为吸引所有人眼光的目标。在这样的前提下，攻击我的人必定就少了很多，再
说一般人的那点攻击是奈何不了我的，我能写会说又擅长实战，所以个别人来攻击我通常都
反受其辱，别忘了冰台可是网络上身经百战被万人骂出来的，已经修炼成不死的小强。如果
还有人要去攻击这些针，那就是攻击《黄帝内经》啦，艾玛，你布道七针谁用谁好使啊？你
这显然是与众人为敌啊！最后也是自取其辱，呵呵。

哈哈，开个玩笑而已，真正学医的人，特别是有一定层次的人，都是善于思考的，也是善于
观察实践总结的，所以他们懂得如何对待一件事物，不会不理性，更不会有无知的冲动，我
以上仅仅开个假设的玩笑而已，放松一下读者的情绪。玩笑话说完了，该言归正题了，继续
讲针。虽然七针疗效不错，但我们必须清醒的认识到一个严峻的问题，那就是四个字：针所
不及！

实际上在我看来，中医的完整体系包括了砭、针、灸、按跷、中药、导引、祝由、咒禁等多
方面的内容，理论上来说，这些方法可以包治百病。古代的中医这些方法基本都懂，我实在
无法想象现在的很多中医自身僵硬板结，腰腿痛缠身，他们是怎样理解气血二字的，古时候
的中医，稍有名气的都是全科大夫，他们在针灸药按摩气功祝由这些各方面都是深有认识体
会的高手。说到全科大夫这一点，有人认为当今应该遵循古法，教育培养全科大夫的中医，
这我有不同见解。我认为全科大夫在古时候是可行，所有的病你都要会治，那时候方圆几百
里可能也就你一个大夫，你不治谁治？再说那时候方圆几百里才你这么一个大夫，患者也不
一定门庭若市，因为人口少啊，现在别说方圆几百里，就一个小镇子，你医术稍微出名一点，
就忙的你够呛，人多为患啊，大把的人争先恐后行医挣钱呢，难不成你还要身兼数职去取别
人的饭碗？你让别人还活不活了？小心不知啥时候你背后就被人猛插一刀，死了也不明白为
啥死的。所以学中医千万别忘了与时俱进这一规律，此一时彼一时，我们现在的中医，再效
仿古带中医搞全科门诊就不实际了，也是行不通的。但这并不意味着我们现在的中医就不需
要掌握这些方法，当然，你是一枚粗工也就罢了，如果是一个中医，这些方法每一种都应该
有所掌握才合理，如果是一个上医（比如大师级别的），那这些方法每一种都应该精通才对，
否则德不配位。

在临床治疗中，虽然并不要求你做全科门诊去包治百病，但在专科疾病的诊治中，也一定要
善于择优组合去运用这些方法，否则就是不配称为中医的。因为就人体结构和生命组成而言，
除了肢体关节脏腑神经血管体液等等，还应该包括血、气、精神、志意这些，否则这个生命
是不完整的。而且这些成分还必须是处于正常状态，也就是“血气已和，营卫已通，五脏已
成，神气舍心，魂魄毕具，乃成为人”，这才是人应该具有的状态。如果某一方面或几方面
都失常了，那就是“患者”，做医生的，你用什么方法去调理？仅仅会用针甚至仅仅会用毫
针，那是远远不够的。地球上几十亿人口，为什么没有完全一模一样的两个或多个人存在呢？
因为这就是自然规律：变数。所以在道法自然的中医看来，他所面对的每一个患者，都不是
固定不变的，不可以用一方一法去应对所有的患者。

那么中医面对一个时刻在变化的未知世界，怎么去捕捉“机”？这里面有虚实方法之分，你
要捕捉的是很多方面的“机”。实的方面，指中医选择使用砭、针、灸、按跷、中药、导引、
祝由、咒禁等方法去治疗；虚的方面指每一种方法的运用，都会涉及天地人的内涵，每一个
运用这些方法的中医，他在医术方面修炼的层次、以及自身学问的厚薄、见识多寡、阅历深
浅、经验多少、身体状况、心情情绪、环境对象等等都会决定他施术的质量，同时患者的疑
信程度、知识层面、体质气血强弱、经络畅通情况、心情情绪、天气，地域，饮食、病史、
治疗史、对病痛的认知程度等等也会决定疗效的好坏。这些如果详细说起来就太罗嗦太复杂
了，如果一句话以盖之，也就是虚中有实，实中又有虚。

其实砭、针、灸、按跷、中药、导引、祝由、咒禁等每一项医术背后都包罗万象，深不可测，
也就如内经所言“夫大则无外，小则无内，大小无极，高下无度”。一个人穷其一生也难领
悟透彻。所在内经里有“针所不为，灸之所宜”一说，也就是提醒我们针是有局限的。必须
做到博学广闻，通贤达智，虽然这些方法众多，我们不一定能够全部精通，但我们必须朝着
精通这个方向去努力，这才是值得推崇的治学态度。医者必须明白，只有集这些方法于一身，
就类似于拥有了由多个强悍的单元体组成的一个大的组合，你身上的能量才会威猛无比，临
床实战中信手拈来，方可事半功倍。

各种医术的组合，是大的组合。那么每一个单元体里，又应该有一个小的组合，这才是合符
自然之道的。比如中药，并不是一味药独打天下可以完成任务的；比如按跷，里面又有分用
手用脚用肘用膝用足等不同功用组合而成，甚至还有不同手法的门派组合；又比如导引，也
是由呼吸吐纳等多种方法结合起来，都不是单一的一种。所以我们如果再来看中医针术，毫
针虽然非常重要，在很多方面表现也非常强大，但就中医整体而言，针，不应该只是毫针的
天下，因为你面对的不是固定不变的就那么几种状况，如果有机会让你真正回到自然界各种
环境里去实战，你就会深刻认识到，单一的毫针，无论疗效还是理论都显得非常不足。所以
真正从道法自然的角度去看针，九针组合是最合理的，针对皮肉筋骨血脉有各自不同的治疗
方法和理论，这样的组合，才可以所向披靡，战无不胜，才可以称之为真正中医的针术。

以上观点为冰台个人愚见，意在抛砖引玉，望高人斧正！
