= 冰台看九针
冰台
2014-3-22 00:00

两千年前的古人，治病是以九针为第一选择的，也就是说必欲治病莫如九针，他们会尽量不
采用药物和砭石之类的方法治病，因为药物有毒副作用，而砭石的痛苦巨大。所以在《灵枢
经》里，黄帝一开篇就说得非常明白：“余子万民，养百姓而收其租税，余哀其不给而属有
疾病。余欲勿使被毒药，无用砭石，欲以微针通其经脉，调其血气，荣其逆顺出入之会”。
黄帝是排斥药物和砭石的，首推选用精妙的针术去治疗百姓的病痛，因此后面才详细讲述了
九针针具，以及诊治理论和具体的运用方法。

然而，自《内经》记载九针之后，两千年来，我们再也没有见到九针的身影，也就是说，九
针失传了。按常理而言，如果内经时代九针医术很盛行的话，那么《黄帝内经》这样一部引
导初学医者由浅入深的入门教材，不可能作为经典之作流传后世的，应该是以记载九针的经
验积累和应用阐发方面的书才更具有成为经典的价值。而恰恰《黄帝内经》成为了经典之作，
所以只能证明在内经时代九针医术就已经开始罕见，没有什么人运用，濒危失传，所以才有
人写了这本书，以此告诫警惕后人，期望他们以正确的方式继承发扬九针医术。

那么，九针为何失传？我推测九针失传的原因有三：

. 两千年前适合制作九针的金属材料稀缺，最适合制作九针的金属，恐怕非金和银莫属了，
而自古以来金银就贵重，并不是一般老百姓能够随意消费的，所以古时候九针医生至少应该
不是穷得一塌糊涂的人。也因此限制了九针的使用人群不可能有很大，这是九针不能盛行流
传的主要原因。

. 九针时代出现了《黄帝内经》这样一本长篇巨著，不遗余力的讲解了很多基础的医学知识，
说明那时很多医者对九针理论已经出现了认识上的谬错，亟需规范和整改。我们以今证古可
以想象，应该还是由于医者行业中一知半解、不求甚解、或听到风便是雨这样的人多了，导
致了九针的疗效不佳，患者们白白承受了痛苦却没有得到疗效，自然就会开始排斥九针，从
而导致九针出现衰败局面。

. 由于内经时代后期《伤寒论》等药书的出现，加上当时九针针具制作等受条件限制，疗效
也不尽如意。而野生药物则在屋前屋后田间地头山上河边随处可得，药性也很好，所以后人
逐渐开始重药轻针，从而导致九针开始失传。

不管怎样，九针终究是失传了，但九针是好东西，这一点肯定是没错的。尤其是在两千年后
的今天，九针对于我们更是显得非常重要。所谓物极必反，阴阳之道也，九针失落上千年，
现在随着社会进步，现代各种金属材料包括黄金也是价廉易寻易买，越来越多的金属可以与
人体亲和，甚至放入人体几十年也不会出现什么异常问题，这样的金属正是制作九针的上好
材料。而药物所产生的毒副作用日益成为诟病，越来越多的人们已经醒悟，开始追求无药疗
法，所以绿色无毒无害安全的九针是时候该重新出世了，一切都是顺理成章的事。中医的未
来一定是针的天下，药已经横行上千年，由于自然、环境、基因、炮炙等条件的变迁，早已
今非昔比，成了扶不起的阿斗，也应了盛极必衰之理，也是天意，所以目前药物气数逐渐开
始消退，不管是否心甘情愿，让位已经是定律了。

两千年后的我们，要想真正理解和挖掘古九针，明白古人的思想和理念，我们至少应该做到
以下三点：

. 遵循内经原文；

. 圣人之为道者，上合于天，下合于地，中合于人事；

. 信解行证。

也就是说，内经古书，我们现在所见最早版本也不过宋代的而已，其中是否有错谬，我们不
得而知。因为看不到更早版本的原书，所以现在的《黄帝内经》，哪怕有可能是将原文印错
的，我们也只能遵循原文去读，否则一切都乱了。至于经文内容字句的意思，无论怎样解读
都可以，但所有的观点和结论，都必须切合实际，必须是道法自然的，然后再拿到实践中去
运用和验证，最后才可以得知你的解读是否正确。
