= 《灵枢.官能篇》解读（下）
冰台
2014-3-26 00:00

冰台前言：

上一篇日志已经解读了官能篇的后半部分，今日继续解读本篇的前一部分。

本篇名曰官能，内容上实际又分为两部分，前部分讲的是针刺技术，后一部分明示了行医资格。

所谓官能，意即官方标准，类似于现在的国标，属于公众认可的行为与能力。前部分的针刺
之道即是官方颁布的针灸运用法则，后半部的择人标准是专门针对针灸医生设立的，类似于
当今的执业医师准入制度，当然了，就针灸系统而言，古时候的国标与当今的国标是有很大
不同的。

就后半部分内容来看，其实古人是想通过本文告诉大家，作为一个针灸医生所必须具备的几
项基本条件：善于观察、善于分析、善于交流与沟通、思维灵活、动手能力强、做事细腻、
内心平和、能明白经脉气血的重要性、懂得调神、具有内功。

这就是官能篇后半部分文字所要表达的理念，在内经时代的古人看来这些条件是针灸医生的
最基本的要求，但对于当今的针灸医生而言，这标准实在是太高太高了，绝大多数条件都无
法满足。我们读内经，一定不能逐字逐句的抠字眼，那样的解读只适合书呆子，物是人非，
今非昔比，你解读出来何用？真正实用的，是要以博古通今的方式去道法自然，这样才能够
真正明白《黄帝内经》的内涵。

原文及释义：

*黄帝问于岐伯曰：余闻九针于夫子，众多矣不可胜数，余推而论之，以为一纪。余司诵之，
子听其理，非则语余，请其正道，令可久传，后世无患，得其人乃传，非其人勿言。*

（冰台释义：黄帝告诉岐伯说，我听你传授的九针医术已经很多，数不清了，我想总结一下，
说出来你听听，如果有不对的地方就告诉我修改，然后我著书流传后世，造福后人，并要求
他们选择适合的人才可以传经）

*岐伯稽首再拜曰：请听圣王之道。*

*黄帝曰：用针之理，必知形气之所在，左右上下，阴阳表里，血气多少，行之逆顺，出入
 之合，谋伐有过。知解结，知补虚泻实，上下气门，明通于四海。审其所在，寒热淋露，
 以输异处，审于调气，明于经隧，左右肢络，尽知其会。寒与热争，能合而调之，虚与实
 邻，知决而通之，左右不调，把而行之，明于逆顺，乃知可治，阴阳不奇，故知起时，审
 于本末，察其寒热，得邪所在，万刺不殆。知官九针，刺道毕矣。*

（冰台释义：岐伯恭敬行礼，说：请圣王明示。黄帝说，用针的道理，首先是必须明白身体
和气血的关系，明白经脉走向和起止，通晓每条经脉气血的多少缓急，阴阳出入，以及汇合
之处，查寒热之因，知虚实所在，明补泻之法，这样才能保证扎针永远不会犯错。）

*明于五输，徐疾所在，屈伸出入，皆有条理，言阴与阳，合于五行，五脏六腑，亦有所藏，
四时八风，尽有阴阳，各得其位，合于明堂，各处色部，五脏六腑，察其所痛，左右上下，
知其寒温，何经所在，审皮肤之寒温滑涩，知其所苦，膈有上下，知其气所在。先得其道，
稀而疎之，稍深以留，故能徐入之。大热在上，推而下之，从下上者，引而去之，视前痛者，
常先取之。大寒在外，留而补之，入于中者，从合泻之。针所不为，灸之所宜。上气不足，
推而扬之，下气不足，积而从之，阴阳皆虚，火自当之。厥而寒甚，骨廉陷下，寒过于膝，
下陵三里，阴络所过，得之留止，寒入于中，推而行之，经陷下者，火则当之，结络坚紧，
火所治之。不知所苦，两蹻之下，男阴女阳，良工所禁，针论毕矣。*

（冰台释义：还要明白五输穴的调理，是与阴阳五行以及季节的规律变化相合的，五脏六腑
都有相应的表现，我们通过观察皮肤细滑还是粗涩，症状的表现来分析，经脉所过处肌肤的
温度差异，最后来判断病邪所在之处。治疗之前还必须先弄明白用针之道，然后对症选择不
同针具，按照以下方法进行治疗：“稀而疏之，稍深以留，故能徐入之。大热在上，推而下
之。从下上者，引而去之。视前痛者，常先取之。大寒在外，留而补之。入于中者，从合泻
之。针所不为，灸之所宜。上气不足，推而扬之。下气不足，积而从之。阴阳皆虚，火自当
之。厥而寒甚，骨廉陷下，寒过于膝，下陵三里。阴络所过，得之留止，寒入于中，推而行
之。经陷下者，火则当之。结络坚紧，火所治之。不知所苦，两蹻之下，男阴女阳。”这些
道理，是一个好医生所必须明白的，这才是具备了九针医术。）

*用针之服，必有法则，上视天光，下司八正，以辟奇邪，而观百姓，审于虚实，无犯其邪。
是得天之露，遇岁之虚，救而不胜，反受其殃，故曰：必知天忌，乃言针意。法于往古，验
于来今，观于窈冥，通于无穷。粗之所不见，良工之所贵，莫知其形，若神仿佛。*

（冰台释义：用针是有法则的，道理必须上合于天，下合于地，中合于人事，必须明白虚实
与禁忌，该补还是该泻，明白哪些病能治与不能治，否则治了无效甚至令病症加重，不但劳
而无功，反而会引来灾殃。既要吸取古人的经验，也要结合当今的实际情况，还要懂得博古
通今之后去道法自然，明白真正的医道，这样才是一个良工所为。）

*邪气之中人也，洒淅动形。正邪之中人也微，先见于色，不知于其身，若有若无，若亡若
存，有形无形，莫知其情。是故上工之取气，乃救其萌芽；下工守其已成，因败其形。是故
工之用针也，知气之所在，而守其门户，明于调气，补泻所在，徐疾之意，所取之处。泻必
用员，切而转之，其气乃行，疾而徐出，邪气乃出，伸而迎之，遥大其穴，气出乃疾。补必
用方，外引其皮，令当其门，左引其枢，右推其肤，微旋而徐推之，必端以正，安以静，坚
心无解，欲微以留，气下而疾出之，推其皮，盖其外门，真气乃存。用针之要，无忘其神。*

（冰台释义：病邪伤人往往是在不知不觉的时候，所以上工治未成之病，下工则治已成之病。
未成之病是看不见摸不着的，但我们可以通过患者气血的变化而感知。所以用针之道，是要
明白邪气存在于皮肉筋骨血脉哪一个层次，然后再去调理，该补还是该泻，留针还是不留针，
进针与出针的快慢。扎针过程中最重要的一点，就是千万要重视患者的神，也就是元阳之气，
不可妄自泄漏之。这里讲到一个泻必用员，补必用方，这是讲的方法，并非针法，在《素问
•八正神明论》里有关于方和员的解释，但却说“补必用员，泻必用方”，这一点灵枢素问
是相矛盾的，实际上也不矛盾，因为讲的其实都是同一个道理。其原文如下：“泻必用方，
方者，以气方盛也，以月方满也，以日方温也，以身方定也，以息方吸而内针，乃复候其方
吸而转针，乃复候其方呼而徐引针，故曰泻必用方，其气乃（守）行焉，补必用员，员者行
也，行者移也，刺必中其荣，复以吸排针也，故员与方，非针也”。）
