= 《灵枢.官能篇》解读（上）
冰台
2014-3-24 00:00

冰台前言：

本篇内容实际上分为两段，前部分讲的是针刺技术，后一部分才明示了官能，限于篇幅，这
里就只解读后部分的官能。

所谓官能，与官针之意大概类似，官针篇是讲九针的，也就是公认认可的疗效最好最安全的
针具标准，官能意即官方从业标准，是公众认可的一个人所具备的能力。《灵枢》本篇的用
意，其实是提醒学医者，学医之前首先要明白自己所具备的优势，发挥自己的特长去学习。
什么样的人适合学针灸，什么样的人更适合从事导引吐纳，什么样的人可以祝由治病，什么
样的人应该从事按摩，这是有定数的，老师应该“得其人乃传，非其人勿传”。

古人这一观点我非常认可，每一个行业里面都有精英和庸才，有的人干了几十年，资历是有
了，但就技术而言，仍然只是一个庸才。其实那些庸才并不一定就是愚笨之人，只不过当初
选择了并不太适合自己的职业，也许他转行，换一个适合自己能力的职业，就成了精英。同
时也证明了你干这个不行并不代表干别的也不行，你干的不好并不代表别人也一定干不好的
道理，所以不要自卑，更无需妒忌攻击，应该正视自己，让自己做得更好。我们按照《灵枢·官
能》的标准来看针灸行业，是那种“语徐而安静，手巧而心审谛者”的人，才适合从事针灸
的。事实上，确实有很多不适宜针灸的人在从事针灸，比如“爪苦手毒，为事善伤”之人，
本应该从事按摩推拿的工作，却整天混迹在针灸行列之中。这样做下来的结果，就是医者荒
废了自己的天赋，患者也耽误了病情，为医者，不可不察也。

《灵枢•官能》原文：

*雷公问于黄帝曰：针论曰：得其人乃传，非其人勿言。何以知其可传？黄帝曰：各得其人，
任之其能，故能明其事。雷公曰：愿闻官能奈何？黄帝曰：明目者，可使视色。聪耳者，可
使听音。捷疾辞语者，可使传论。语徐而安静，手巧而心审谛者，可使行针艾，理血气而调
诸逆顺，察阴阳而兼诸方。缓节柔筋而心和调者，可使导引行气。疾毒言语轻人者，可使唾
痈咒病。爪苦手毒，为事善伤者，可使按积抑痹。各得其能，方乃可行，其名乃彰。不得其
人，其功不成，其师无名。故曰：得其人乃言，非其人勿传，此之谓也。手毒者，可使试按
龟，置龟于器下，而按其上，五十日而死矣，手甘者，复生如故也。*

冰台注解：

雷公请问黄帝，《针论》说：得其人乃传，非其人勿言，那什么样的人才可传呢？黄帝说：
每个人天生禀赋都不同，人生阅历和学识都不一样的，如果针对这个人的能力，委以重任，
那他就能干得很出色。雷公说：愿听您说下择人的官方标准。黄帝说：眼睛好使的人，善
于观察，就可以让他从事望诊治病。耳朵好使的人，善于聆听分析，就可以让他从事听诊
治病。善于讲解道理的人，具有很强的说服力，可以让他去与患者交流沟通，此即现代大
都市里逐渐兴盛的所谓之“话疗”。性格谈吐都温柔，心灵而手巧的人，更适合从事针灸，
通过调理经脉血气，使阴阳平衡，达到治病的目的。关节柔软筋骨灵活，而且内心平和的
人，可让他从事导引和呼吸吐纳的职业。说话恶毒犀利，语言刁钻的人，可利用以毒攻毒
之法，让他用嘴去吸吮脓疮之毒，适合祝由咒语治病的行业。手掌粗大有力者，可让他从
事按摩推拿的工作。按照每个人所具备所擅长的能力，传授适合的医术，也就是顺水推舟，
他们将来才能成为名医。如果一个人从事了与他天赋相逆的职业，最终是不能有多大成就
的，当然更不可能有什么名气。哪种人属于手毒之人？大家都知道乌龟长寿，所以可让他
做个试验，将乌龟用缸子倒扣，他用手放在缸上，施展内力去抑制乌龟的行动，乌龟不出
五十日就死了，这就是手毒。连号称长寿的乌龟尚且如此短寿，更别说客于肌肤之间的病
邪了，手毒之人其实也就是内力深厚的人，只需随意轻轻拍两下，内劲能够透进去，病邪
立刻烟消云散，但一般人是做不到的。
