= 什么是九针（一）
冰台
2013-10-30 00:00

纵观国内针术界比较热门的一些针法，从诊治理论上来划分，大体上分为中医经脉气血理论
和西医运动解剖理论两大类别。当然了，这两大类下面又细分为好多种不同的门派观点，我
这里讲的是九针，所以只谈跟针法有关的。按针具针形来看，真正中医理论指导之下的各种
针法，几乎都是以纤细毫针为治疗手段；而西医理论指导下的针法，大多以刀、钩、棒等形
状的针具为主，具有切割、撬拨、钩割、烧灼等功能。

我不能说谁对谁错，评判一件事物，是由每个人所站角度和对事物的了解程度以及主观意念
等因素决定的。任何一个人站在自己的角度，他都会认为自己是对的，对方是错的。因此如
果我要说，在治疗常见肢体关节疼痛方面，经脉气血理论比解剖理论显得更加有道理和人性
化，对方就一定会据理力争，而且对我所提到的经脉气血也颇感不屑：这些经脉气血不也是
建立在软组织基础之上的吗？离开软组织体液这些你焉能存在？呵呵，好的，那么我又反问
一句，且不拿死人与活人作比较，就说正常人和植物人，您所说的这些软组织体液之类在他
们身上都存在的，对吧？但他们二者之间有什么不同之处呢？

所以如果整天老是纠结于这些问题，那我们学医就一点意义都没有了，我要是早知道医生这
个行列里面也有很多卑鄙小人的话，我要是早知道研究九针会无事惹尘埃的话，我早就可能
去卖烤红薯了，那工作比目前这事业优雅单纯多了。我想做的，只是想将老祖宗的一些理论
和思想，挖掘研究一下，看看能不能够给我们后人带来一些快乐和幸福。老祖宗总结出来的
内经医学高深莫测，理论基础在两千年前就已经非常成熟的了，你却拿几百年几十年之内才
出现的理论观点去跟他们做比较，指出经络穴位之类跟解剖其实是有些关系的，扎针取穴点
其实就是效法西医总结出来的反应点结节之类……听到这些振振有词，我真的想摔烟缸，你
不去深入了解内经也就罢了，据说你在学校里也读过内经，也认识几个字对不对？内经里早
就指出经脉通路上形成结节和反应点的原因，以及调理方法，你以为反应点结节之类是你们
现在才发现的啊？总不能说你睁眼看到太阳，太阳就成了你发现的了，你难道不知道太阳已
经存在了上亿年？类似你这样的炎黄子孙，居然张冠李戴已经习以为常，我不敢说你臭不要
脸，因为我们都标注自己是文明人，所以要讲礼貌。但我真的不知道到底是你对，还是老祖
宗错了？那么唯一可以让我心情平静下来的方法，就是叮嘱自己稍安勿躁，继续站在老祖宗
的肩膀上深入研究，不要俯身去跟那些站在祖宗脚背上翘首楚盼，不求甚解却又望文生义的
人一般见识。

就我对内经的理解，我必须把我认识到的某些内容说出来，不吐不快。我们都知道，《黄帝
内经》的治病理念是调理经脉气血，以恢复人体正常功能作为目的来达到治病功效。古人连
体内五脏六腑的形状大小功能部位颜色等等这些全都研究得清清楚楚，不可能反而对外部的
肌肉血管神经这些东西没有认知，老祖宗又不是脑残研究一半扔一半。所以古人的针术理论
里没有肌肉解剖方面的运用，其实并不是古人不懂解剖，而是刻意为之，以此暗示后人，针
术里根本就不需要这些玩意儿。而国内盛行的那些西医运动解剖疗法，却恰恰主要是在肌肉
肌腹这些部位做文章，这从根本上就已经与内经本义相佐。

我再重申一句，我讲的这些观点并不是我总结出来的，穴位经脉也不是我发明的，气血理论
也不是我研究出来的，我只是将老祖宗埋藏在书中隐秘处的思想挖了一些出来，然后让这些
理论重见天日，让更多的人受惠，你千万不要还像以前那样指责冰台发明了什么，创造了什
么，我可没那么伟大，我只不过付出了一些脑力劳动而已。我只是背靠内经在宣传内经，我
演讲的都是内经里的东西，我是按照我所理解的内经在讲，我说的有理有据，所以我并没有
错对不对？即使你认为我说的不对，那也跟我本人没太大关系，你看不懂听不明白是你自己
的智力有问题，但你不可以指责我做错了，因为这些道理是老祖宗总结的，说得直白一点，
俺只是一个壳子，内瓤子装的是《黄帝内经》部分内容，所以你不能做了买椟还珠的事，然
后把所有的不满都发泄到椟身上。

《素问•刺要论篇第五十》说：“刺皮无伤肉、刺肉无伤脉、刺脉无伤筋、刺筋无伤骨、刺
骨无伤髓。”《素问•调经论篇第六十二》说：“病在脉，调之血；病在血，调之络；病在
气，调之卫；病在肉，调之分肉；病在筋，调之筋；病在骨，调之骨。”在古人的理念里，
针是用来调理经脉血气的，并不直接涉及体内的脏器，而且脏器也是严禁扎的。要调理气血
的问题，并不直接扎针破散血气，而是通过调理经络这个气血的载体来做文章。肌肉也不可
以直接扎针，要调理肌肉的问题，是通过调理肉与肉的分间之气来起作用。要调理筋骨的问
题，也仅仅是在筋和骨上去做文章，不涉及肌肉神经血管。《黄帝内经》除了脏腑功能运化
等方面的阐述，主要就是突出“骨度”一篇重点。为啥没有专门讲神经肌肉这些的篇章呢？
就是因为九针里所有的针，都不是用来扎肌肉的，也不是用来扎神经血管这些组织的。也就
是说从事九针的针者，在解剖方面，能够了解脏腑的功能分布和互相之间的关系，了解人体
骨骼的形状和分布这些就行了，其他的如肌肉神经血管等等就无需深入了解。有肌肉动脉主
干神经的那些部位，根本就不是要扎针的地方。所以，明白了这些道理，我们如果真正要研
究内经九针，首先就必须放下西医的肌肉运动解剖理论。

那么常见的中医针术呢，我们看到的，几乎都是以细小的毫针为用，而且具有针具越来越细
小的趋势。毫针细小并没有错，错就错在所有的病，无论皮、肉、血、脉、筋、骨的问题，
不分病的大小和深浅，针灸师们统统一律都以毫针为用，成了毫针控，这就不对了。须知，
古人设立九针并不是没有道理的，九针各有其形，各有所宜，病有大小深浅之分，针亦应有
大小长短与之相应才对。偏偏千百年来错误的思想早已将九针里面其他的几种针具深埋地下，
剩下毫针和锋针支撑门面，而散落民间的某些针术秉承了九针的某些理念，由于没有身份证
的黑户口，得不到公众的认可，最后发展到今天，本身就非常不景气的中医针灸，毫针控们
完全占据了主导地位，这当然会极大地影响到患者对针灸疗效的体会和认识。这种以单一毫
针代替所有九针，去治疗变化万千不同病痛的行为，很明显违背了《黄帝内经》的宗旨，类
似“病深针浅”、“病大针小”等等力不从心的情况必定会频繁发生，因此导致国医针术逐
渐衰败，地位等同鸡肋。

另一点，几乎市面上所有的中医针灸术，都是以固定的穴位作为治疗点，忘记了道法自然，
也就没明白气血经络与脏腑之间的关系。针灸师们牢记呆板固定的穴位，以不变的思路和方
法去应对万变的症状，这一状况也是有违《黄帝内经》旨意的，所以单纯的毫针，本身就已
经注定了临床治疗中一定会有较大比例的患者，出现疗效差强人意的状况。

按古代的医术地位排列，是一针二灸三药，针术是治病的首选。《灵枢》开篇第一句话就说
了：“余子万民，养百姓，而收其租税，余哀其不给而属有疾病，余欲勿使被毒药，无用砭
石，欲以微针通其经脉，调其血气，荣其逆顺出入之会。”这里所说的“微针”，并不是仅
指毫针，是微妙精妙的针法之意，由此可见古人对针术的重视程度。按道理，中医针灸经历
几百上千年的发展，本应该欣欣向荣，成为主宰医疗市场的权威才对，目前的现状如何呢？
针灸历史几千年，到了近代，一些已经西化的中医们对传承内经的中医理论进行了“科学”
化的修改，将本应个性化的诊治思路进行了“国标化”“规范化”这样的“发展”，到如今
不但没有繁荣昌盛，反而沦落成为一种可有可无的辅助疗法。

只是可惜《黄帝内经》九针也被毫针控们间接地影响了，人们丝毫不会去分析思考内经九针
的诊治思路有多么的优越，不明白九针到底是怎样调理气血经脉的，全部都把眼睛放在了针
具外形上，看到的大都只是意淫出来的阴暗面，脑子里首先冒出来的就是危险、痛苦、野蛮
等等字眼，很少有人会相信这么粗这么大的针，会没有危险，会没有痛苦，会没有副作用。

我们无从得知九针从什么年代开始失传的，自《内经》之后，汉宋明清以来的大量针灸典籍，
都是以毫针为主要研究对象，均没有见到关于九针运用和发挥方面的阐述。现代虽然有新九
针出炉，但已经与古九针的原貌原义几乎扯不上关系了。明代汪机在《针灸问对》开篇有这
么一段话：“今之针士。决痈用锋针铍针。其他诸病。无分皮肤肌肉血脉筋骨。皆用毫针。
余者置而不用。甚有背于经旨矣。”根据汪机所言，证明至少在明代，九针除毫针锋针之外，
其余几支针就已经早已无人运用。

本人常有感于此，倾力钻研针术十载有余，苦读《黄帝内经》，常为之茶饭不思寝食不安，
无奈经文深奥无比，百思仍不得其解，收获寥寥无几。直至某一日突然受到某种自然现象的
启发，方才渐渐明白内经某些章节之原始本义。开悟之后，索性怀揣内经，完全融入自然和
社会生活中，历经几度春秋，终于豁然开朗，将失传千年的九针原型，挖掘整理出来。并将
此九针之术运用于临床治疗，在疗效方面竟然获得极大成功，深受学生和患者的好评。在深
深感慨古人无限智慧之余，也意识到这些针法针术必须广为传播，让天下民众受益，方才不
负老祖宗们著书《黄帝内经》之本意。

那么，接下来，我就带着大家来看看，九针到底是什么，到底能起到怎样的治疗作用？
