= 浅论九针的解读
冰台
2013-11-25 00:00

中医针术治病，九针一定是非常有必要的，毕竟世道变化万千，人与人之间的差异性越来越
大，各有所需的状况肯定会越来越明显。不是你不明白，是因世界变化太快，早已今非昔比
了。有些人比较固执于纤细毫针，武断的排斥粗针九针，这是由于他总站在自己的角度说话，
所以观点比较狭隘。内经说“圣人之起度数，必应于天地”，这句话最有道理，行为做事道
法天地，这样才是圣人所为。

排斥九针的人，大都是因为不了解九针，当你真正了解九针的内涵，就会热爱九针的。

要了解九针，必须先解读《黄帝内经》。

可是，我们现在的人，应该怎样去解读两千年前的古书《黄帝内经》呢？一两千年前的有些
字我们是认不得的了，有些语言我们也是听不懂的了，怎么办？有人说请专门的古文字专家
来解读内经里的生僻字，企图这样能够解读内经。这想法其实很可笑，莫说专家们解读的也
未必是对的，或许他也只是靠片言只语的证据去猜测和推测而得出的答案呢，即使他解读的
完全符合古人当时的社会，那又有多大意义？你可知道此一时彼一时，完全按照两千年前社
会所存留下来的这点残次不全的理论，去解读去复制九针，那即使解读出来也一定是谬误百
出的。大家都知道，古时候的自然生活社会现象与如今有很大的差别了，别的不说，语言文
字就太大差别了对吧？然后很多的生活习俗与行为表达方式，也有很大的改变了。想想我们
周围吧，短短几十年我们身边就有很多习俗已经消失或改变了，更何况两千年之历史长河，
其中变化之大可想而知，这怎么能相等对待呢？

所以我们读古书，要理解很多事必须要与古代相区别开来，明白今古有哪些不同之处，又有
哪些共同之处。比如现在一个人早上在北方，中午坐飞机飞到南方，下午又飞到东方，这样
的事情是很容易做到的，古人则根本做不到这一点，所以古人分析问题和考虑问题的时候，
也有他们的局限性和狭隘性。但别忘了古今是有共同之处的，比如古时候有一年四季春夏秋
冬，现在也有这样的季节变化；古时候有白天晚上，现在也有昼夜之分；古代有刮风下雨雷
鸣闪电等自然现象，现在同样会有风雨雷电；古时候江河的水是从上游往下游流的，现在我
们依然能见证水是从高处往低处流。这些自然现象是永远不会改变的，我们只要明白这些道
理，抓住这些不变的自然现象去分析古人的思想与意思形态，那就可以最大程度的还原古九
针，领悟内经针术的要旨。

古时候治病，受交通信息渠道的限制，大夫们可能大都是以本地人的生活习俗体质状况来问
诊下药，即使在大都市里，北方人来到南方，也是需要几个月甚至一年这么漫长的路程而来，
患者在这个过程中或许已经逐渐适应了当地的水土气候。可现在治病你不仅仅要考虑身边的
患者群体，还要考虑来自远方异地的患者，如果你依然唯古训为教条，这是不够用的。还有
人与人的异同，这也要考虑，或许你常年遇到的患者都是细皮嫩肉或养尊处优的人，这类患
者稍有病痛就来找你治疗，即使病痛很多年的，由于自我保养意识较强，加上生活富裕，所
以病邪大多也只在肌肤，不至于病入筋骨，所以你就会感觉毫针已经足矣，何须大针呢，但
你换个地方行医试试看？如果在穷乡僻壤，城乡结合部，来者大都是贫困农民，这些人不但
经常反复感受风寒湿，而且是带着风寒湿也要继续劳累的人，他们的病痛不到病入筋骨这一
层不会轻易来找你治的，即使来了也早已成了痼痹，那你的毫针，你的意念，你的功力，恐
怕真不是那么好玩的了。

所以我们解读九针要考虑因地制宜，与时俱进，不要死守教条，《素问·示从容论篇第七十
六》说“圣人治病，循法守度，援物比类，化之冥冥，循上及下，何必守经。”就是这个道
理。现代人越来越有文化，脑子却越来越不如古人好使，所谓“不知比类，足以自乱，不足
以自明。”我觉得有些问题我们真的应该认真思考一下，比如东南西北各个地域，风情习俗
思想地位劳作等等因素，所导致的病因是不一样的，而且这些因素还会随着时代的变迁而变
化，所以看古书不能尽身临其境，必须要知进退。以东南西北中各地为例，现在这只是代表
一个方位了，每个地方都有来自全国各地的人聚集，如果你单纯说居住在南方的人就是南方
人，那就错了。比如古时候说“南船北马”，意思是说南方人善于驾船，北方人善于骑马，
看看现在有几个南方人善于驾船，又有几个北方人善于骑马的呢？现在南方也生活着很多从
小在北方长大的人，这些外地人是近年从事各种生意或工作而迁徙过去的，你能以南方本地
人的体质和生活习俗来思考他们的病患么？

而且古代的南与今天的南是不一样的，现在的南方北方气候环境风俗等等都大为改变了，搞
得南不像南，北不像北，这还能用古人积累的经验来说事吗？古代巴蜀之地属于啥？天府之
国，大汉的粮仓，自古兵家必争之地，而近代随着工业发达，开发开采，城市已经不再是以
前的城市，农村不再是以前的农村，人也不再是以前的人了。我小的时候我们现在这个地方
是蔬菜生产基地，农民栽种了大量的新鲜蔬菜，每天车载船装的输出新鲜蔬菜到外地。而现
在以前那些蔬菜地全部修成了工厂房屋道路，以前的农民成了市民，不但不能自给自足，反
而需要从外地大量运进蔬菜来供给市民。以前说“自古苏杭出美女”，我前些年去杭州，大
街小巷的瞅，眼睛瞅酸了都没遇到一个真正合眼的美女，反倒是古代巴蜀之地重庆的美女们
皮肤水灵细滑身材婀娜多姿，都出啥状况了？

时过境迁对吧？那我们读古书还能泥古不化么？

呵呵，这不同病因不同地域不同体质需求都不一样的了，哪能继续泥古不化呢？如果我们继
续依照前人解读《黄帝内经》的方式去解读九针，我们解读出来的九针，虽然跟那些古人近
代人现代人所解读的九针在语言文字上有所区别，但有一点是无论如何都跟他们是相同的，
那就是同样的没有啥实用价值。
