= 心主是什么

http://blog.sina.com.cn/s/blog_727392820102wqku.html[原文地址]

“心主” 二字连用， 在《内经》 中， 共出现 34 次 。 其中以心主舌、 夏、 脉、 噫、
汗、 身之血脉等的形式， 共出 现 7 次， 这里的 “主” 作动词用， 意为主管、 掌管
之意; 其 余 27 次， 出现于 20 篇中。可见“心主” 在《内经》 时代 即是一个专有名
词。

在 27 个专有名词“心主” 中， 又可以分为两大类: 第一种， 作为手足阴阳十二经的一
个有机组成部分， 与 “足厥阴” 相对， 不用 “手厥阴” 说法， 而用“手心主” ，
如 “手心主之脉 ” “手心主之筋 ” “手心主之正” “手心主之 腧 ” “手心主之别”
“手心主之本” 等。第二种单独组 词， 共出现于 5 篇 7 次， 分别见于《灵枢·经脉》
“心主 手厥阴心包络之脉” “手少阳之别， 名曰外关， 去腕二 寸， 外绕臂， 注胸中，
合心主” ; 《灵枢·胀论》 “膻中者， 心主之宫城也” ; 《灵枢·邪客》 “包络者， 心
主之脉 也 ” ; 《素问·皮部论》 “心主之阴， 名曰害肩” “上下同 法， 视其部中有
浮络者， 皆心主之络也” 《素问·血气形志》云: “少阳与心主为表里”。

第一种用法可以看出“心主”作为经络的话属于手，分别三阴三阳的话归为“手厥阴”。为
什么定义为“厥阴”，《外经微言》有祥解“属手厥阴者，以其代君出治，**为（手少阴）
心君之相臣**，臣乃阴象故属阴。然奉君令以出治有不敢少安于顷刻，故其性又急，与肝木
之性正相同，亦以厥阴名之，因其难顺而易逆也”。因此侧重阴阳之名的话经文就云“手厥
阴”，如果不重阴阳则云“手心主”。

第二种用法中 5 篇 7 次的“心主” ， 对于 理解心主内涵有重要参考意义，但是理解
“心主”不能仅仅只看这些文字，你得从经文其他论述中体味出真意，那么到底怎么理解
“心主”？“心主”的秘密其实在《难经》和《内经》里已经讲了。

《内经》云“**少阳与心主为表里**”又云“肾合膀胱三焦”，敦煌文献 《不知名氏辨脉
法之二》曰: “右肾及手心主合三焦”，综合经文内涵，其意即云心主在肾中也。《难经》
“肾有两脏也，其左为肾（水），右为命门（**__火__**）。命门者，谓精神之所舍也，男
子以藏精，女子以系胞，其气与肾通” 《难经》云“脐下肾间动气者（即命门），人之生
命也，十二经之根本也，故名曰原。三焦者，原气之别使也”，三焦乃命门之别使也，故而
**__“心主”即命门也，无形之火也，肾中之原气也__**。参见博文<<20170427-如何理解
三十六难“左者为肾，右者为命门.adoc#,《如何理解三十六难“左者为肾，右者为命门”》
>>。

《外经微言》云“**__心主之气与肾宫命门之气同气相合，故相亲而不相离也__**”，又曰
“各脏止有一而肾有二者，两仪之象也。两仪者，日月也。月主阴，日主阳，似肾乃水脏宜
应月不宜应日，然而月之中未尝无阳之气，日之中未尝无阴之气，肾配日月正以其中之有阴
阳也。阴藏于阳之中，阳隐于阴之内，叠相为用，不啻日月之照临也．盖五脏七腑各有水火，
独肾脏之水火处于无形，乃先天之水火，非若各脏腑之水火俱属后天也。夫同是水火，肾独
属之先天，实有主以存乎两肾之间也。主者，命门也。命门为小心，若太极之象能生先天之
水火，因以生后天之水火也。于是裁成夫五脏七腑，各安于诸宫，享其奠定之福，化生于无
穷耳”故知“心主”与“命门”一物也。

然《外经微言》云“(心主) 然而离心非主，离肾亦非主”，就是说心主发挥功能需要肾
（命门）与心的配合，心以心包络为臣来配合，命门以三焦为别使，配合的地方在“膻中”
，只有这样命门才能作为“心主”而为十二宫之主，因此**古人特立一名为“心主”与“命
门”分别，其实是一物二名，也可以明白“心主”是个虚脏的概念**。

《外经微言》“雷公问于岐伯曰：十二经各有一主，主在何经?岐伯曰：**__肾中之命门为
十二经之主也__**。雷公曰：十二经最神者，心也。宜心为主，不宜以肾中之命门为主也。
岐伯曰：以心为主，此主之所以不明也。**__主在肾之中__**，不在心之内。然而离心非主，
离肾亦非主也。命门殆通心肾以为主乎。岂惟通心肾哉。五脏七腑无不共相贯通也。””
**故命门之火，谓之原气(难经云：三焦者，原气之别使也)。命门之水，谓之原精**。精旺
则体强，气旺则形壮。命门水火实藏阴阳，所以为十二经之主也。主者，即十二官之化源
也。”“ 为当曰：命门为十二官之**主寄于何脏**?岐伯曰：七节之旁中有小心（肾脏内
也），**__小心即命门也__**。为当曰：鬲肓之上，中有父母，非小心之谓欤。岐伯曰：鬲
肓之上，中有父母者，言三焦包络也，非言小心也。**__小心在心之下，肾之中__**” 。
小心为真主，故曰心主也。

赵献可《医贯》对此论述也是一样的“玩内经注文．即以心为主．愚谓人身别有一主非心也．
谓之君主之官．当与十二官平等．不得独尊心之官为主．若以心之官为主．则下文主不明则
十二官危．当云十一官矣．此理甚明．何注内经者昧此耶．盖此一主者．气血之根．生死之
关．十二经之纲维．医不达此．医云乎哉．或问心既非主．而君主又是一身之要．然则主果
何物耶．何形耶．何处安顿耶．余曰悉乎问也．若有物可指．有形可见．人皆得而知之矣．
惟其无形与无物也．故自古圣贤．因心立论．而卒不能直指其实．孔门之一贯．上继精一执
中之统．惟曾子子贡得其传．然而二子俱以心悟．而非言传也．若以言传．当时门人之所共
闻．不应复有何谓之问也．后来子思衍其传而作中庸．天命之性．以中为大本．而终于无声
无臭．孟子说不动心有道．而根于浩然之气．及问浩然之气．而又曰难言也．老氏道德经云．
谷神不死．是为玄牝之门．造化之根．又口．**恍恍惚惚．其中有物．佛氏心经云．空中无
色．无受想形识．无眼耳鼻舌身意．又曰．万法归一．一归何处．夫一也中也性也．浩然也．
玄牝也．空中也．皆虚名也．不得已而强名之也**．立言之士．皆可以虚名著论．至于行医
济世．将以何味的为君主之药．而可以纲维一身之疾病耶．余一日遇一高僧问之．自心是佛．
佛在胸中也．僧曰非也．**在胸中者是肉团心．有一真如心是佛**．又问僧曰．真如心有何
形状．僧曰无形．余又问在何处安寄．僧曰**__相心在下边__**．余曰此可几于道矣。”

赵氏又曰“余所重先天之火者．非第火也．人之所以立命也．仙炼之为丹．释传之为灯．儒
明之为德者．皆是物也．一以贯之也．故命其名曰医贯”赵氏此论精当，《外经微言》云
“少师曰，命门之系人生死甚重，《内经》何以遗之?岐伯曰：未尝遗也。主不明则十二官
危。所谓主者，正指命门也。七节之旁有小心。小心者，亦指命门也。人特未悟耳。少师曰：
命门为主，前人未言何也，岐伯曰：广成子云：**窃窈冥冥，其中有神。恍恍惚惚，其中有
气。亦指命门也**。谁谓前人勿道哉”。
