= 经络常识简说
曾骞

. 经络，“经”和“络”是两个不同的部分。经脉是纵行的，络脉是横出的。但都注意，都
不是线。经脉不是一条线，络亦不是一条线。或者比喻地讲，经脉是大河道，络脉是小河道。
经脉与络脉就是经络的主体。正所谓“十二经脉者，内属于腑脏，外络于肢节。”这是一个
立体的系统。经络，是如环无端的。看看我们的山河大地，大地上布满了河道，人身亦如此：
“经脉者，人之所以生，病之所以成，人之所以治，病之所以起。”

. 十二正经是气血通行的主干，十二经别别出于正经，循行于体内，以辅正经循环不足。行
于分肉间。十二经别，即，别行之正经。

. 奇经八脉不拘于正经，交错于十二正经之间，以调节正经气血盈亏。

. 十五络别行于体表，以加强正经间的联系。是主要的大络。

. 诸络脉与孙络，网络遍布周身，渗灌各部。络脉由正经支而横出，浮而常见。而所谓孙络，
即络脉之支别。

. 经络连属，内部五脏六腑，此为经脉之所络属。外部的十二经筋与十二皮部为十二正经所
渗灌。人体外部的五官九窍与四肢百骸等，皆依赖经气濡养，依靠经络联系。

. 十二正经的分布规律是：四肢经脉上下分布的规律，与五脏的位置，和脏腑的表里关系有
关。具体地说，
.. 心、肺、心包在胸膈以上，所以心之脉，肺之脉，以及心包之脉，等于这三条阴脉，因
其阴脉故分布于上肢内侧。
.. 腑经随脏，因而小肠之脉，大肠之脉，三焦之脉也分布于上肢，因为脏腑表里的关系，
且腑为阳，所以这三条腑经，就分布在了手臂的外侧阳面。就是这个道理。以此推之，肝之
脉，脾之脉，肾之脉，因肝脾肾位于胸膈以下，故而此三经本属阴，故而分布于下肢内侧面，
胆之脉，胃之脉，膀胱之脉，此三阳，为腑之脉，自而为阳，腑经随脏，故而此三条腑脉分
布于下肢外侧阳面。

. 头部经脉之分布，以六阳经脉为主。少阳（手足）于侧头，阳明（手足）分布于面部，手
太阳分布于颊与颧，足太阳布于巅与后勺。

. 躯干部经脉分布规律，以背为阳，阳经分布在腰背。腹为阴，阴经分布在胸腹部。故，肩
背部是手三阳分布的区域。足三阳的话，足太阳主要循行经过与分布腰背部；足少阳则循行
分布在背腹之间的侧腹；足阳明经，由腹部而出于髀，走入阳部。足阳明此经由阴走阳，是
阳经走行中的一个特殊。但从人身本一体的概念去看，就不会觉得奇怪，足阳明虽为阳经，
却具坤母之德，四象五行皆借土，阳明一而贯之。

. 十二经脉与脏腑的络属关系。阳经皆属腑而络脏。阴经皆属脏而络腑。

. 在阳经皆属腑而络脏。阴经皆属脏而络腑的基础上，再结合十二经别的循行，加强了脏腑
之间的联系。故，生理功能的正常依靠此联系，在病理上也自然会相互影响。

. 十二经走向与流注的规律。首先是十二正经循行走向的规律：手之三阴，从脏走手；手之
三阳，从手走头。足之三阳，从头走足；足之三阴，从足走腹。简单扼要言，我们将双手举
起来，所有的阴经都是向上行，所有的阳经都向下行，记得，研究经络的时候，我们最好是
在站立时把自己的双手举起来。阴升阳降，就是十二经脉走向的规律。

. 经络是如环无端的。其实这一特点就是在遵循着世间的万事万物是互相联系的这一真相与
原理。经络如环，顺逆相接而无端。端着病之。十二正经是气血循环的主要通道，顺逆相互
连接，形成了一个连同的整体，气血因此有了依次流行的道路。

. 手足同名的三阳与三阴经，彼此也是相互衔接的。所以，实际上就是六经。站好，把手双
双举起。明白了吗。

. 手足同名经互相衔接，对于人之生理与病理均有重要影响。大致地说，我们知道手少阴与足少阴是互相衔接的，那么也就明白了，心肾之气相交之因。依此而推，足太阴脾与手太阴肺相互衔接，从生理功能上去看，脾之气散精，而后上归在肺。其他的用不着去举例子了。如果还要再详细一点，可以把手足三阴三阳同名而连的相交处写一下。

. 互相勾搭处：
* 手太阴与足太阴相接于*中府*
* 手少阴与足少阴相接于*心中*
* 手厥阴与足厥阴相接于*天池*
* 手太阳与足太阳相接于*晴明*
* 手少阳与足少阳相接于*瞳子髎*
* 手阳明与足阳明相接于*迎香*

. 既然说到经络是个立体系统，那么就存在着十二经脉的表里阴阳关系。十二经分属六脏六
腑。涉及到的表里关系，简说之，就是以脏为阴、腑为阳。阳在外为表，阴在内为里。所以，
腑经皆属阳为表，脏经属阴为里。

. 经脉表里的来由：在体内，由于经脉的属络关系，使脏腑内部互相贯通。再者，十二经别
组成六合，阴经之别合入阳经，加强了互联。在体外，表经的别经入走里经，里经的别络入
走表经。再而，十二正经表里两经的末端皆相互衔接，这个在简说Ⅰ里有。

. 关于十二经脉的五行关系。我有我的一个简单看法，这个五行关系其实就和十二地支一样，
存在三合，以及相拱，相冲，相害，相生等。最主要的是三合关系。这个三合关系，对于古
针的临床应用有莫大意义。

. 讲到十二经别。再罗嗦一下，经别是别行的正经，是由正经别出的另一经脉系统。有了十
二正经，为什么还要有十二经别。经脉之外，别有正经，非络噢。十二经别自正经别出后皆
走内脏，手足六阳经别均行过与其表里的脏腑，足三阳之经别属腑而散于脏，手足六阴经别
均行过本经所属之内脏，后合入与其为表里之阳经，从而组成六合关系。所以，我自己在临
床中发现的中神规律，就是来自于这个规律。言归正传，有了十二正经，还需要十二经别，
其实作用无外乎是加强通连内外，将表里二经在体内外的联系增益。我们来观察一个自然现
象，在大河道的附近，一般都存在地下水的。这个地下水就是经别，如果用援物比类的思想
来看问题。

. 十二经脉在体表，十五络为之沟通。表里二经在肢端相接，表里通气。所以，手之四末阴
阳，是最大的阴阳之一。

. 阳经经别自本经别出后复注于本经。

. 阴经经别自本经经别出后注入阳经。

. 阳、阴经别之脉气不按经脉流注的次序传注，所以走向亦与正经不同，其重要的特点就是：
没有顺逆的分别，均由四肢（肘膝）别入内脏深部，复出头颈浅部。所以，我们认真地分析，
其实这个经别之动向，有心者请认真看，这与卫气循环以及骨空都是有关联的，这是一个重
点，需要好好研究，就会有成果。

. 经别，我们就来看看经别。
+
简单详细一点地讲，其实经别就是卫之大循环中所包含的一部分。这个部分里有卫气之路，
以及骨空之注，更重要的一点是，还有营卫之合处。经别，是三大系统的一个使者，精气神
之内枢。
+
* 足太阳、足少阴经别，从腘部分出，入走肾与膀胱，上出于项合于足太阳膀胱经；
* 足少阳，足厥阴经别从下肢分出，行至毛际，入走肝胆，上系于目，合于足少阳胆经；
* 足阳明、足太阴经别从髀部分出，入走脾胃，上出鼻頞，合于足阳明经；
* 手太阳、手少阴经别从腋部分出，入走心与小肠，上出目内眦，合于手太阳小肠经；
* 手少阳、手厥阴经别分别从本经分出，进入胸中，入走三焦，上出耳后，合于手少阳三焦经；
* 手阳明，手太阴经别从本经分出，入走肺与大肠，上出缺盆，合于手阳明大肠经。

. 十二经别的循行方式是离入出合。所谓离，就是指别出，入就是指注入体腔深部，出则是
指从深处浅出体表，而合则是因为不管阴或阳之经别浅出后力量都是汇入至阳经。离入出合，
四个字，是对十二经别循行方式的总结，这四个字直接简说了经别之循行的内在规律。有一
个问题是，为什么十二经别都汇于阳经？我们要明白一个事实，那就是六阴经的主干部分，
都不在头面，头面只有六阳经（简说Ⅰ中第八条目有详），那么这样的话，如何体现出经络
之间的整体性与不可分割性呢，所以，阴经就借助了经别合入阳经而最终与其在头面的阳经
合而为一：“十二经脉，三百六十五络，其血气皆上于面。”

. 经络的循行方式五字诀：上下出入别。这五个字，代表了经络的礼法。

. 经络通于人身方式七字诀：循挟贯过抵至绕。这七个字，代表了经络的劳动方式。

. 经络互联的三字诀：交会合。这三个字，是经络内部的纪律。

. 经络于人身互联三字诀：散系布。这三个字，是经络自己的空间学，如有方，建与筑。

. 关于奇经八脉。为什么叫奇经八脉，因为这些脉都不入五脏，也没有表里相配合，不像十
二经那样存在表里复注。而且，另一点重要地说，也不随着十二经流注循环的。别道奇行。
与脏腑联系上，奇经八脉主要联络奇恒之腑，与十二经不同的是，于五脏六腑没有络属关系。
所以这个奇字也直接在呈现着其络属之深处。奇经，表其性与质，八脉之脉，表其象，贯连
如山脉如地脉之阔并有条理纳统各路。所以，就是得把这个八脉看成是八条阔带，但这就并
不意味着十二经就是线了，经络不是线的概念啊，不管是什么经脉，都不是线的概念，包括
孙络也不是，思维上去认知经络为线的概念就是错的，我们在地图上看长江黄河是线，但实
际呢，长江黄河宽阔奔流，其他江水河道也是如此，对待经络，我们不能因为示意图中的经
络示意线而将经络本身看作了线，真是这样去认识经络的，不管是什么家，都是猪聪聪。这
里是借题发挥再强调。

. 但是，我们不能说奇经八脉和十二经没有关系，没有这回事，原理上我们是知道经络都互
为联系的，但形而下地讲，奇经八脉究竟和以三阳三阴为基础的十二经存在着一种怎样的裙
带，那就需要看奇经八脉概念的创立和什么有关。和八肱有关。什么是八肱。这要讲到天圆
地方。天圆地方是什么，不是说天是圆的，地是方的，现在中学的教科书就是这么批判天圆
地方的，写出这种脑残观点的教材编写者是猪聪聪，是垃圾。天圆地方是古人的时空概念，
天圆意为苍穹之浩却至大无外，地方，则是指四方与四隅，所以名之以方。四方与四隅，在
人体上就是对应着人的前正中纵带、后正中纵带，头部以及尻尾部，子午卯酉四方；腰、膝、
手、足就是四隅。这是人身地理。十二经脉于人身地理上依助于奇经八脉而将四方四隅都联
系起来了，这是经脉立体性的基础之一。回到经脉河道的概念上来讲，因为奇经八脉沟通了
十二经之间的联系，把部位相近或功能相似的经脉系之，再加上奇经八脉对十二经的经脉气
血起着蓄积、渗透的种种调节，那么，我们可以这样说，奇经八脉就是湖泊，与江水河道般
的十二经组成在一起就是：江湖。

. 任、督、冲、带、维、跷。全是带着所主所司的意思。都是政治家。呵呵，其实，人体的
经络循环，就是一种最大的政治。所以说，上医治国。
. 任脉，实从“妊”来。所谓的诸阴之海。足三阴经皆交会于任脉。手三阴虽未直接相会于
任，但别忘了，手足同名相衔接，与足三阴相连接，所以任脉容诸阴之气。是阴经之海。要
注重这个海字，既然为海，则是源泉。任脉为病，男子内结七疝，女子带下瘕聚。
. 督脉：顾名思义，督统之意。总督诸阳。为阳经之海。和任脉不一样的是，督脉的话，手
足经（当然是指阳经）都可以聚汇于督。重要的大交会处，第一是大椎，手足六阳之会。第
二是百会，足三阳之会。关于督脉，督脉能贯通入脑，连通心脏，这意味着什么，智慧的修
炼与心间寂寂之息见都与督脉有深刻的内在关系。督脉上的每个穴道名字都极具深意，想说
的是，腰阳关是什么呢，就像我们看到的地平线上升起的那个太阳。

. 冲脉：又叫太冲脉。有个太字，级别很高，极为强大的力量。好像一个太极。太极分两仪，
一上一下。冲脉起于胞中，简单地说由中而出，其上行支者，不管是内行入脊柱内还是外行
沿胸腹上头，其目的都是向诸阳经渗灌。下行支者，目的都是向诸阴经渗灌。所以，我们看
这个冲脉，是需要将其如一个太极鱼图那样去看的。整个人体因为有了这个阴阳螺旋的存在，
而变得具有相当的生命力。关于所谓的太冲脉所指，历来都有争论，其实这个有什么好争论
的呢，太冲脉就是冲脉啊。不管是上行或下行，这个冲脉都是从胞中出来后从阳明的气冲而
出的，然后又假少阴之道，这就是个很有意思的事情。为什么？一句话：后天以返先天。冲
脉统贯了二经，统贯了先后天。所以自然是十二经脉之海。

. 伏冲：是指冲脉循行进入脊椎骨内的部分。简单地讲，就是冲脉在体内深层的分部。

. 带脉：近取诸身，束腰如带。古人的腰带都很宽大的。在我们捆腰带的这个地方有一条脉，
就是带脉。想想古代官员的革带。带脉统束纵经，这是个基本常识，也没什么好说的。关键
的一点是，我们知道了带脉是起到统束作用的，就别误解越紧越好，凡事都需度。所以带脉
为病，一是不和，二是失约。前者实证为主，病在经气阻滞而造成过于紧束，约束权苛自遭
胀急与宽膨；后者虚证为主，病在经气虚衰，脉遭松弛，故提携诸脉废弱。

. 维：阴维与阳维脉。维就是维系的意思。阴阳维，维络一身表里之阴阳。阳维维于阳，阴
维维于阴。阴主里，阳主表，所以阴维脉主一身在里之阴，阳维脉主一身在表之阳。维字，
虽然讲，都清楚是维系、维络，但落实到维脉而言，究竟是维了什么。一般书里都会这样写
类似这样的解读：阳维有维系联络全身阳经的作用，阴维有维系联络全身阴经的作用，正常
而言，所谓的阴阳自相维能对全身气血盛衰起到调节溢蓄等。其实，这种样的解读还是抽象
了，不够具体。甚至会有些陈词滥调。阴维与阳维循行都是由下至上的，这是与十二经的阴
阳经循行方式不同的。阴维是与任会合，阳维是与督脉会合，从循行上去看阴阳维的会合处，
这才是一个关键点。阴维等于是与阴脉之海会合，阳维等于是与阳脉之海会合。所以，我个
人觉得，这个维字，更多的是带“纲维并主持”之意。阳脉统于督，阴脉统于任这是个基本
常识，维脉就是负责主持阳经与阴经其气血力量最终是明确的没有偏离地会统于该汇统的地
方，维脉是主持诸阳与清阴，并不是统，是人体气血规律这个大老板用于管理诸阳与诸阴的
一个督察。所谓的阴阳自相维，就是在强调纲维备之下的有主有持。阳维维于阳，并且上行
于卫分，阴维维于阴，并且上行于营分。所以吧，维脉，其实也可以从某种意义上讲是卫营
相和的一个纽带之一。

. 跷：阴跷与阳跷。所谓的“跷”字，是足跟。从经脉上看，阴阳二跷均起于足跟部，因为
阴阳二跷的统摄作用，而使得足跟之筋骨捷而矫之。以司职而分的话，阳跷主一身左右之阳
气，阴跷主一身左右之阴气。以任督为中轴，左右各有一对阴阳跷。因为没有任督的腧穴，
所以其阴阳跷的脉气是两侧各别的。循行的特点是，阴与阳都是由下至上，这是与十二经的
阴阳经循行方式不同的。阴阳跷会在目内眦相交合。生理功用，司目之开阖与肢体肌肉运动。
当我们的眼睛闭起来的时候，并不意味着我们是完全不可见的，我们依然还是可以看到这个
世界，闭上眼的时候，并不是纯粹的漆黑，还是有颜色，这个现象不知道大家注意过吗。道
理很简单，我们看东西，表面看是眼睛在看，其实是我们的神在看，只不过是通过眼睛这个
工具而已，上下眼皮的开阖就如帘子一般。所以，阴跷与阳跷所司的是我们的神之目帘的张
与闭，并不是说可以直接作用于我们的真正内视。阴阳跷的平衡基础是：气并相还。

. 冲、任、督三脉是一源三岐。原因是，都起自胞中，同出会阴。同样的，太冲脉前挟脐二
分上行，后伏冲脊内，冲脉不可能孤立地只行于腹面，也不可能单纯地伏冲于脊，它还需要
下渗三阴，冲脉是个太极，任督是子午南北。

. 所以，奇经八脉有没有“开阖枢”，当然有。不能因为奇经八脉的基本形式不是三阴三阳，
就否认且无视奇经八脉具有“开阖枢”。说奇经八脉没有开阖枢，是一种片面与狭隘。从经
脉的生理作用的特点，以及从以三阴三阳为基本构成形式的十二经讲，十二经具有开、阖、
枢，而从医者的格局与视角上讲，经脉都有开、阖、枢。将奇经八脉与十二经放在一起看，
就理解得了奇经八脉的这个开、阖、枢了。这种联系，不再是单将某一经与奇经八脉相联系，
而是将三阴三阳与奇经八脉相联系。比如，任为阴之海，三阴归之，故任于三阴具阖；而阴
维本络诸阴，故阴维于三阴具开；再说到枢，所谓的枢，则具承转表里，三阴之枢在哪里，
在冲脉。三阳与奇经八脉之间的开、阖、枢也是类此。不要受到传统的开、阖、枢概念的束
缚，要将这三个字上升到一种格局上的庙算与兵法，作为医者，懂得了开、阖、枢三个字，
就懂得了怎么样去分辨主要矛盾与次要矛盾，是一种高层次的方法论。或者再罗嗦地讲，我
们总是在谈所谓的道法术器这四个很难听的字，那么就应该明白，我们对待某个概念，也应
该用道法术器的思维来理解。认为开、阖、枢只存在于十二经，这是术器的层次；知晓了开、
阖、枢不仅仅只限存在于三阳三阴的构成形式中，而是一种看待经络互相联系以及阴阳出入
的相对概念，这是法的层次；把这三个字，理解得了已经了然于心中它是一种格局概念，一
种演绎形式，而可将其用于把握整体的天人地时，这是道的层次了。

. 经络行载气血，而气与血，说白了，气以行血，血以补气，气依顺，血依通，气血的真相
是什么？我们去搞清楚经络的问题，这不是最终的目的，了解经络只是手段，我们更深的目
的是为了通过经络去更多地了解关于气血的真相、人生的真相。气血不光是人的立身之本，
也是人与宇宙自然相互沟通的根本力量所在。整本《黄帝内经》其实都在强调气血的作用，
在强调人与天地的沟通中气血所起到的作用。人的每一个心念，其实都参与在了天地生克之
中，而心念与神与意系之，而神与意与气血系之。说白了，气血的真相是什么，是因果啊。
经络的本质呢？也是因果啊。因为“经脉者，人之所以生，病之所以成，人之所以治，病之
所以起。”你看是不是因果。因果二字简说了经络与气血的本质。

. 经络并不能因其命名、起止、排列、行布等方面烙印着哲学的因素与意味，而只用哲学的
眼光来看待经络之律。我们不能这样去割裂与断取经络的演绎本质。当我们看了天，也看了
地，再反观照见自己时，我们才会清楚地意识到有关经络，它是一元心物。

. 经络之律，其实就是宇宙法则在我们人身上最直接的演绎方式，我们的身体有十二经、奇
经八脉，我们的人生也有十二经与奇经八脉。人生起点至终点，所有的轨迹都充满了经纬，
人生经络不断循行：重叠往复的孤独，漫长的等待与瞬时的失去。或者将这组词语换为：亢
却脱力的欢喜，短暂的欢愉与极处的渴望。可又有什么分别呢。阴阳出入而已，因果而已。
每个人的人生景观，就是因果两个字而无他。朝什么方向走都是砖头与从容大道之间，我们
往往对此懵懂无知。因而有了这样一个残酷的事实：我们往往只是拥有几缕鸡毛，而从未接
近过宇宙。

（等到简说4，会再回到经络的一些最基本常识。比如经络是怎么产生的，人体总共有多少
数量的经与经的分支，《内经》中经脉的含义具体指的哪些等这些按惯常套路，开篇即谈的
基础内容。这个简说系列是散谈，所以有时在天空说，有时在地上说，有时在水里说，有时
则是在草丛里。）
