= 在重构中实现再生

== 一

写作本书的起因与大学的经历有关。

或许与所读的专业有关，在读大学时，曾对传统文化诸如诗词、书法、篆刻之类十分感兴趣，
于是，拜名师，临名贴，摹名印，习古韵，吟古诗，填古词，虽说学得很耐心，也很用功，
奈何天性愚钝，始终不得其门径而入。李鼎教授能诗善词，又写得一手漂亮的好字，心中十
分敬羡，尊崇有加。约在大三，某日闲逛，路过校内书店时，偶遇《针经》，见扉页上写着
李鼎、李磊（注：李鼎教授的学生，中国第一位针灸博士）所注，也没多想，随手买下，留
作记念用。多年后，因整理书架，在不经意间翻阅此书时，才发现此书尤为难解，一时兴起，
决心要搞个明白。

然而，难度却超出了我当初的预想，虽然日思夜想，仍是一头雾水。因为找不到解决问题的
出路，所以处处疑似为出路，只能漫无目的地在疑似相关的领域中逐一摸索，为此几乎遍览
了中医、针灸等相关书籍。还是老子说得好，“少则得，多则惑”。起初的目标很简单，无
非是想把《针经》中的时穴模型的演绎原理想个清楚。只是在疑似相关的领域摸索久了，形
形色色的理论看得多了，原初的问题非但没能解决，反而遭遇到更多的问题。面对各式各样
的学术体系，各说各话且都言之在理，心中茫然无措，于是试图从中理出些头绪，找出中医
理论的核心基础及其基本框架来，祛纷杂归之于简约，纳百家归之于一致。久而久之，便有
了些心得，决定写些文字归纳一下，这便是此书之所以写作的最初缘由。

== 二

想起来还真的有些悲怆，覆巢之下无完卵，曾经博若汪洋的中国传统文化巨系，到如今，只
落得中医硕果仅存，生存惟艰着。回到故纸堆里，有心疏理一下中医学的核心架构，却又深
感无奈。自先秦时起，经过二千多年的发展，中医学已经成为蔚然大观的医学巨系，广博是
自不待言的。然而，方药、针石各有各的基础，伤寒、温病各有各的理论，学派纷呈，百家
驰骛，各是其所是。即便针对同一问题，也是各人各说，很难辩出个所以然来，以至于初学
者难窥其门径，硕学者难穷其究竟，更遑论中医学的核心架构究竟是什么的问题了。

身处生存惟艰着的时代，虽说广博却是支离的理论将不足以支撑起难测的未来。坦率地说，
现代中医之所以会陷入困境，且不奢谈什么创新与发展，就是传承也难以为继，固然缘起于
现代医学的冲击，也与中医本身的理论困境分不开。看似各种理论都言之成理，也就意味着
每种解释都有些问题，有些欠缺。既然不知中医理论的核心基础及其基本框架为何物，无法
赋予史上诸家之学以一致性的解释，那么，中医理论本身也就会因此而失去了令他人信服的
说服力，将来的路会越走越窄。

然而，以现有的基础，倘想提炼出中医理论的核心基础及其理论架构，又谈何容易！问题是
明摆着的，难度也是明摆着的，但作为中医中人，虽知此事难为却又不得不为之。无论能否
成功，总得有人去试着去解决，否则，中医将很可能无法走入未来。绕室徬惶许久，记起高
武曾说过，“不溯其源，则昧夫古人立法之善；不穷其流，则不知后世变法之弊”。追根溯
源，中医学的理论基础奠定于《内经》，史上诸家之学多是在《内经》的基础上，参之以临
床治学之心得而自成一家之言的，心想何不单刀直入，径自从《内经》入手来反思这一理论
难题呢？

= 三

记得读大学时，老师授课总是口不离《内经》曰如何如何，于是花了些功夫研读了《内经》
及其诸家注释。谈不上有什么心得，只是觉得《内经》行文晓畅，论述通透，读懂似乎不难，
至于诸家注释，仅是随文解释而已。虽说某些经文一时难以吃透，却并没有进一步深入的兴
趣。多年之后，决定回头返读《内经》后，才发现经义深邃如渊，倘要真正地读懂，决非是
件容易的事。

本人治学入手于《针经》。在当初，虽说看不懂《针经》之所以然，但所论的对象必是气血，
这是确然无疑的，因此，在后续的治学过程中，始终围绕着气血这一核心关键词，不断深入
而旁涉诸家之学的。循着这一治学思路再读《内经》时，才蓦然领悟到《内经》的整个理论
体系，就是置基于气血运行系统之上的，由此猜想，整个中医理论体系的核心基础及其架构
也应构建于气血及其运行系统架构之上。于是乘兴深入，几经周折之后，终于厘清了《内经》
理论的内在脉络。以此为基础，溯源穷流，去伪存真，进行了彻底的理论重构。

之所以要重构，就在于《内经》存在着些许不足。诚然，《内经》之学千古独步，构思之恢
宏，立意之幽远，论述之精妙，足以垂式百世而不隳，但是缺点也很明显，首先，博而寡要，
甚或有些散乱，让人摸不着头绪。倘若不能学贯天人，能够随文解读，管窥其一二尚且不易，
更遑论深入领会了，以至于某些令人难以置信的低级错误，一错就是几千年，居然无人能够
识破纠正。传承啊传承，传到后来，竟然是讹传，因此，将《内经》中的理论体系模型化、
框架化，实现最大限度上的无歧义化表达，以便于一般读者易于理解与把握，也就显得十分
必要；其次，自《内经》之后，中医理论有了极大的发展。虽说史上诸家之学大多祖述于
《内经》，但既能成为一家之言，必有其独到之处，也就是说，仅以《内经》的理论架构已
经不足以反映当今中医学理论体系的全貌了，与其削足以适履，倒不如换履以适足。权衡再
三，痛下决心，决定花些时间，重构基于《内经》之上的理论架构。

== 四

并非是为了标新立异，而是不得不然。

人们总是习惯于在前人的基础上去思考所面临的问题，至于前人遗留下来的基础本身是否就
是个令人值得反思的问题，去思考的人就少得多了，尤其在已被广泛地认可的情况下。中医
理论的基本架构奠定于《内经》，后世医家虽然有所扩展，但核心框架没有人去改动过，甚
至我还没见过有谁深入思考过。中医中人已经习惯于在《内经》曰如何如何中思考问题，很
少有人会去反思《内经》中的理论架构如何成为可能的问题。因此，后世诸家之学，虽说各
有其独到之处，不过是在既定的理论架构之上有所发挥而已。本书既以重构《内经》中的理
论架构为目标，那么，《内经》理论本身也就成为有待于反思的问题。很显然，这是古人尚
未涉足过的领域，仅凭现有的理论基础将不足以支撑起如此宏大背景之下的中医学反思，原
创也就了必然性的选择。

那么，究竟该以怎样的思路，以实现中医核心理论的重构呢？这是个令人颇费思量的问题。
因生性好猎奇，历算、易理、丹道、佛老乃至于印度诸家之学等等，靡不一一掠阅，观其大
略，因此，重构所必须的知识储备还算充分，足以应付。真正的难题是，中医是传统性非常
强的理论体系。倘要重构，那就必须既要有所创新，又要尽可能地保持其传统性的理论特征，
做到形神皆得而勿失，否则，岂不成了画虎不成反类犬？踌躇经年，思酌再三之后，决定采
用在现行的架构之上进行扩展的思路，并择取我之所学，将之融入到扩展后的新架构中去。

首先，以气血及其运行时系统的系统模型为中医理论的核心架构。视气血及其运行时系统为
中医理论的核心基础，这是自《内经》时起，就被公认为中医的理论基石之一，但是，《内
经》所载述的气血及运行系统虽说十分详备，却失乎蔓杂，以至于后世学者中，鲜有能窥其
全貌者。通过分析《内经》中的相关载述，提炼出在理论表达上虽更为简约，却更为强大的
理论模型，让人一望便知其大概，这是本书必须优先解决的关键性问题之一。为此，参酌丹
道、瑜珈等诸家之学，以期更完整地勾勒出气血巨系统的总体轮廓；参酌天文历算方面的知
识，依据天人之理，针对现存的攸涉气血运行方面的诸家理论，尤其在流注学方面，进行反
复的校验与演算，去其伪存其真，澄清诸家理论的原义与欠缺，提出改正的基本思路；参酌
治易论医的心得，量体裁衣，创建了六行、易象等抽象符号系统，并以此符号系统建模基于
气血巨系统之上的理论模型；其次，将中医如伤寒、温病等，针灸如经穴、针法等诸家之学
置基于气血巨系统的理论模型之上。以气血巨系统为核心基础，反思后世诸家之学的缺陷，
并进行了针对性的理论重构，从而实现基于气血理论之上的诸家之学大一统。

虽说为了最大限度地体现中医的传统性特征，在引入新型的理论架构时，十分注意所创架构
的向前兼容性，因此，重构之后的理论架构较好地保存了传统中医中一切合理的理论元素，
但既曰重构，必然有所创新，否则，岂不成了循袭了？要创新，就得有破有立，引入新型思
想，革除旧有弊端，如废五行而倡六行，驳《圣济》而遵《甲乙》等等，与现行理论的主流
思想不可避免地存在着较大的出入，因此，远看则神似，细究则形异。在那些言必称古人，
唯传统是从的人看来，某些改革性的理论方案几近离经叛道。但我认为不破则不立，关键在
于破得是否有理，所立是否得法。创新才是真正意义上的传承，因为即便是最伟大的学术传
统，倘若失去了自我反思与创新的能力，只能走向穷途与落没。

== 五

传统中医自有其精华独到之处，这是确然无疑的，关键在于怎样才能很好地传承下去，但现
状难以令人乐观。

所谓传承，就是将前人的成就继承下来，并传给后来者。是否值得传承，则取决于前人的成
就能否被证明为仍有其继续存在下去的价值。倘若仅是因为是传统的缘故，无问前人的思想
是否仍有其合理的一面，为继承而继承，那么这样的传承实际上就是盲从，而盲从则是学术
的天敌，因此，能否揭示前人的思想脉络，做到知根知底，去芜存精，是决定是否要传承的
前提。

然而，钱尘滚滚，物欲横流，在当今这个社会，能够静下心来以整理国故的人太少了。所谓
传承，已经沦落成某些人追名逐利的工具。在社会上，假传统的名义，自神其秘，故弄玄虚，
包治一切疑难杂症，世上的神医多出于中医之门；在学术界，言必称先贤曰如何如何，不过
是假先贤的成就，糊自己的嘴。名医满街走，大师头碰头。开张方子，动辄用药数十味，乱
枪打鸟而已。在中医药史上，我还没见过有哪个朝代曾出过如此多的名医与大师，更没见过
有哪个朝代的中医学会象当今这样落败如斯。身处中医了末之世，我真的很无语，感到很无
助，很苍凉。

熙熙攘攘，莫不为名来，为利往。作为中医中人，总得有人不计名利，以成功不必在我的心
态，去从事纯学术，使中医能够薪尽火传而不绝。知其不可为，仍执意为之，尽到自己的责
任而已。黄卷青灯，更深夜读十数年，最终完成了重构中医理论核心架构的夙愿。虽说某些
理论构思不尽周遮，尚须进一步推敲，但作为一种尝试，应该算是比较成功的。

== 六

本书系多年前的旧稿修改而成。原拟名为《气血学》，取以气血及其运行时系统为论述重心
之意。之所以更名为《解深密》，与本人的佛学经历有关。多年前，闲来无事，曾读过不少
佛藏典籍。依我的读后感，若仅论文字优美，行文晓暢，玄奘译《解深密经》算得上是上乘
之作，印象特别深刻。某日心念乍动，忽然领悟到此书所论都是那些深藏于现行中医理论背
后的道理，如改名为《解深密》，倒也很切题，既通俗，又古雅，且富有神秘感，令人莫测
高深，岂不更好些？

原稿在草拟过程中，曾得到上中医李鼎教授、吴祖德教授的鼓励与支持。当时，李鼎教授曾
提议，先把所研究的成果分篇整理出来，由他推荐到专业杂志上逐篇发表之后，再裒订成册
出版，而吴祖德教授则提议，不妨将整个理论体系思考成熟之后，直接整理成书出版。然而
生无定性，初稿略拟之后，尚不及细改，兴趣便迅速转移到其他领域中去了，终不了了之。
但此书毕竟凝聚了多年的心血，就这样半途而废心有不忍，于是，多年之后，又回过头来续
改旧稿。

原稿是由着性子写的，信马由缰，想怎么写就怎么写，写到哪里就写到哪里，乘兴而为，兴
尽则罢。因此，篇章结构散漫随意，所述内容广袤芜杂。修修改改，很难从根本上解决这些
问题，只能推倒重写。在重写时，首先注重原创性。当今这世道，追名逐利，文风日下，浮
夸日盛，注水文章，触目即是。我重写此书，既不为名，也不为利，犯不着这样做，因此，
对于那些非原创性的内容，除非出于论述上的必要，保留一些引文外，一律删除。也因为偏
重于原创性的，所论述的内容多是尝试性的，留给自己试用没什么不可以，但写成书，传行
于世，则有贻误世人之虞，因此，对那些实在太不成熟，拿不出手的内容，也一律删除；其
次偏重于基础理论及其基本框架。原稿将临床、诸家学术、基础理论等糅在一起写的，盘根
错节，要想逐一清厘清爽，殊非易事。因此，在重写时，将重心转移到基础理论及其核心框
架的构思上，剥离那些与此重心不甚相关的内容，并借鉴些编程中面向对象的思路，重构了
论述的基本框架及其篇章结构，从而使整个论述更为简洁，但缺点也很明显，那就是写得比
较抽象，且离临床有些远。

百密尚有一疏，何况本就无密可言呢？考虑到本书所涉及的范围太过宽泛，某些理论上的问
题太过艰深，因此，疏漏在所难免，决定先出个电子版在网上发表，收集一下网友们的反馈
意见，再作最后的润饰与修定。待有机缘，再考虑相应的出版事宜。

== 七

本书涉及到的知识面非常宽泛，除中医诸家之学等外，还旁及到历算、易学、哲学、瑜珈、
丹道、显密等领域。因此，最适合那些知识面比较宽泛的读者阅读。对于一般的读者，只要
有耐心，费些功夫，也能读得懂。在篇章结构上，采用层层递进的论述方式，每一卷章的论
述都以此前各卷章的论述为前提，因此，强烈建议读者在阅读时，最好先通读全书，了解一
下各章节的大致轮廓，然后依次逐章细细阅读。当然，倘若所读章节的内容自认为以前就已
经掌握的，那就不妨跳过读下去。

本书仅是本人所撰论著系列之一，为了尽量避免各论著之间所论内容上的冗复，本书仅就中
医学领域中的相关问题展开详细论述，至于书中涉及到的其他领域中的相关问题，仅仅点到
即止，不作深入，将具体的详细论述交由相应的论著来承担。倘若读者在阅读此书时，觉得
许多方面的论述语焉不详，话说半句，有心深入到相关的领域中去一探究竟，那就敬请关注
此后逐批整理的相关论著。

最后，谨向上中医李鼎教授、上针所吴祖德教授致以最真挈的感谢。

谨以此为序。

石清峡士

2009.9.20写于前山
