= 先从哲学谈起吧

所谓医学，顾名思义，就是以人体身心的生理、病理为研究对象，从而建立起来的防病、治
病乃至于保健的知识体系。医学之与哲学，本就分属于不同的领域，作为中医学的专业论著，
开篇却从哲学谈起，是否有些不着边际，扯得有些远？医学与哲学，各有分际，这个诚然，
之所以要从哲学谈起，是因为在全球化的时代，无论从哪种医学传统谈起，首先遭遇到的便
是为何会有多种医学传统并存于世的问题。

在中医界，中医家们的思想视野狭隘得很，仍然龟缩于中国之内。言必称传统，中医及其母
体，即中国传统文化，乃是其关注的焦点所在。然而，此一时，彼一时，在当今的中国，源
出于西方的现代医学“鸠占鹊巢”，成为了医学领域中的主流，中医昔日荣光不再，中西医
学论争因之而时伏时起，现代医学也就成了中医家们挥之不去的心结。除了这些之外，则无
论其他焉。因此，在多数中医学家看来，现代医学以及以中医为代表的传统医学共同构成了
医学领域的全貌。倘若睁眼看世界，问题那就要复杂得多了，除了中西医学之外，实际上尚
有多种医学传统流行于世，且就人类医学史上的历史影响而言，某些医学传统是决不逊于中
医的。在业已全球化的时代，多种医学传统并存于世的态势下，倘要进行无偏倚的中医学论
述，首先必须解释多种医学传统如何成为可能，以及中医怎样地实现自我定位等问题，而这
些问题却必须透过跨传统的哲学思考才能解答。

== 多种医学传统如何成为可能

人生在世，疾患如影之随形，成为人类最为切身的基本问题之一，是故，自人类诞生之日起，
如何防病、治病而深入思考的历程贯穿着整个人类的生存过程。任一民族，在历史上，基于
各自的诊疗经验积累，都曾有过自己的医学经验传统。随着人类思想视野的不断拓展，诸族
群文化之间的交流与融合，优胜与劣汰，犹如百川之纳海，最终形成了以中国、印度、阿拉
伯、欧洲等传统为主流的人类医学传统。因此，作为医学，首先是多医学传统如何成为可能
的问题，其次才是各医学传统如何形成及其定位问题。

无论各医学传统之间的理论形态有多么的不同，但作为医学，就必须以人体为核心的研究对
象，这一点是确然无疑的。虽说人体生理存在着个体性，甚或族群性的些许差异，但这些差
异可以忽略不计；任何切实的医学论述，必须置基于可观察到的生理、病理现象之上，这一
点也是确然无疑的，否则，岂不成了空口玄谈？这些生理、病理现象是通过感官系统观察到
的，而感官系统与生俱来，即便观察者之间存在着些许个体性的差异，也是无碍大局的。因
此，古代医家们在诊疗实践中所能观察到的基于人体之上的生理、病理等外在事实应该不会
有什么太大的差异。倘若仅以此为基础，加以归纳与总结，从而形成医学体系的话，那么，
各种医学传统之间，或因各有专攻而各有所侧重，或因各有各的经验积累而有高低之分，或
因思考问题有深浅之别等因素，而在理论形态上有所差异，这些是意料中的事，没什么好奇
怪的。倘就思考这些生理、病理等现象的基本思路而言，应该没有多大的区别，最终所形成
的知识体系的基本形态也应该是大同小异，差不离的。

然而，事实却远非如此。各医学传统之间的理论形态相去之远，出乎人们的想像，之所以会
这样，究其根本性的原因，就在于各传统的医学思考模式各不相同。换言之，正是因为各传
统在医学思考模式上的差异，在古人所能观察到的几近等同的经验事实的基础上，各循其思
而思，各遵其是而是，最终想出了彼此间理论形态迥异的医学知识传统。这便涉及到医学思
考的基本方式是如何会决定着医学的知识形态，其本身又是如何被赋予的问题。

作为医学知识体系，当然必须以可观察到的生理、病理现象等经验事实为基础，但这些经验
事实本身仅是些感官系统所观察到的现象集合而已。倘若仅仅停留在经验事实这一层次上，
无论怎样积累与总结，始终不过是现象碎片的累积与堆砌，不可能提升到知识体系这一高度
上来，因而是远远不够的，必须更进一步，透过所观察到的现象，揭示其然及其所以然，从
而将这些现象集合纳入到一致性的、可预见性的解释体系中去，如此方能称之为医学知识体
系。那么，人是如何揭示其然及其所以然的呢？这就必须通过思考。任何的医学知识体系，
说到底，都是经过思考而后形成的产物，因此，在医学知识体系形成的过程中，思考起着决
定性的作用。

应该说，那些感官可直接观察到的经验事实固然是差不离的，但在此基础上，该怎样去思考
所观察到的经验事实，则取决于医学思考所基的思惟模式。换言之，即便是针对完全相同的
经验集，倘若医学思考采用了不同的思惟模式，随之进行的思考过程以及经思考而后形成的
医学知识形态也会各不相同，大而言之，便会形成知识形态迥异的医学传统。医学思考的基
本方式决定着医学知识的基本形态。因此，多种医学传统如何成为可能的问题，说到底，就
是医学思考所基的思惟模式及其多样性是如何被赋予的问题。

所谓医学，本就是以人体为研究对象的，因此，那些基于人体的生理或病理现象可以通过医
学自身的观察活动直接得到，然而，这些现象仅能赋予医学思考以所思的基本素材，却无法
赋予医学该怎样去思考这些经验现象；就医学思考而言，在各医学传统中，只能以特定的思
惟模式去思考所观察到的经验事实，却无法解释为什么要以这样的方式去思考的问题。也就
是说，医学上的问题该以怎样的思惟方式而被思考着，并非医学自身所能赋予的，而是有待
于被赋予的，因而是前置性的。这就意味着，医学并非是能够自解释，而是有待于被解释的
知识体系。那么，医学思考所基的多样性的思惟模式又是如何被赋予的呢？

万物皆有法度，思考自不能例外。人为何而思？无非是想把万物的存在及其意义搞个明白。
所思者何也？无非是万物的存在及其意义而已。因此，思惟与存在同一不二。人该怎样地思
考所面对的世界，取决于万物的存在及其意义以怎样的方式而被人理解着。那么，人又该怎
样理解万物的存在及其意义的呢？这就转入了哲学领域。

所谓学有专攻，哲学就是专以思惟与存在为研究对象而发展起来的学科。人该怎样地思考万
物的存在及其意义，取决于哲学反思所能得出的基本结论。哲学通过赋予人以怎样地思考所
面对的世界，从而成为一切知识体系得以形成的前置性基础，成为了“万学之学”；其他学
科则以哲学所赋予的思惟法则去思考特定对象的存在及其意义，从而发展出基于该研究对象
的知识系列。这些学科固然以所研究的对象而立，但该怎样的方式去思考所研究的对象的意
义，却有待于哲学反思来赋予。在这里，有一点需要说明一下，哲学对具体学科的影响主要
体现在理解事物的存在及其意义的基本方式上，而不是那些“纯思”所臆构出的宏大体系。
倘若不明就里，将那些哲学家费尽心思想出来的哲学体系套用到具体对象的研究上，那就要
闹笑话了，因为，任何基于特定对象之上的思考，都必须置基于所观察到的经验事实，否则，
所构建出的知识体系岂不成了无稽之谈？

作为万学之一，医学又岂能例外？所不同的只是，医学唯以人体为核心研究对象。任何基于
人体之上的生理、病理等现象，这些都是诊治过程中所能直接观察到的，因而源自于医学活
动本身，但是，该怎样地思考这些现象的意义，却有待于哲学所赋予的思惟方式。这就意味
着，医学以怎样的知识形态而被建构着，超越于医学活动本身所能观察到的经验现象，取决
于哲学赋予医学以怎样的思考方式，哲学因之而能够从深层次上决定着医学知识体系的表现
形态。

因此，医学只能作为哲学思想之下的产物而存在着。倘若离开了哲学的支撑，医学将永远停
留原始经验的层次之上，经验积累再丰富，也不可能发展出基于这些经验之上的高度一致性
的知识体系。强大的医学传统必然以强大的哲学思想为基础。诊疗经验可以通过自身的实践
加以积累，但就医学体系而言，知识体系赖以形成的医学思考的基本方式，因无法通过自身
的实践而获取，显得尤为重要。倘若舍哲学而论医学，纵然论得再精深，也只能是知其然而
不知其所以然，即我们可以将医学的知识形态讲得一清二楚，却无法说清楚医学为什么会以
这样的知识形态而被构建着。

提起哲学，虽然那些唯西哲是从的人未必会承认这一点，在当今这世上，并不存在着所谓普
世性的哲学，哲学仅以特定的传统形态而存在着。当然，现代语义上的哲学，作为外来语，
原来仅指西方传统意义上的哲学。倘若以此为基准，则在其他传统文化中并不存在着相同知
识形态的哲学系统。所谓西方之外无哲学，此言诚然。倘若将哲学定义为反思事物存在及其
意义的思想体系，那么，除西方之外，尚有中国、印度、阿拉伯三大哲学传统并存于世，西
方哲学传统仅是人类四大哲学文化传统之一罢了。四大哲学思想传统各有其解读万物存在及
其意义的独特思路，西方哲学系统于此中并不具有超然的地位。

既然哲学总是以特定的传统形态而存在着，人类所构建出的一切知识体系也就只能以特定传
统所赋予的思考万物存在及其意义的方式而被建构着，这就意味着人类的知识体系只能以多
样性的知识形态而存在着，从而形成了四大文化传统并存于世的文化现象。作为哲学文化传
统的产物，各传统中的医学循着各自传统所赋予的思考人体生命现象的意义取向，最终发展
出了各自的医学传统，从而形成了与所在传统的哲学文化思想在深层次上保持一致的四大医
学传统。离开了所在的哲学传统，我们就不可能理解该医学传统为何会逞现出迥异于其他传
统的知识形态。

在西方哲学传统中，以主体—对象为基本框架，事物作为独立的认知对象，其存在及其意义
体现于该物之所“是”（to be / being）上，呈现出形质化与还原论的思惟趣向，按尼采
的说法，这就是所谓的“透视主义（Perspectivism）”。与之相应，西方医学传统的核心
思路就是，以人体为独立的研究对象，追问人体生命现象之所“是”及其所以“是”，从构
成论与还原论的角度，不断深入，从器官到细胞，从分子至DNA，穷极究竟，从而发展出强
大的现代医学体系。

在中国哲学传统中，万物莫不存在于生生之流中，因此，事物的存在及其意义只能体现于天
地化生万物这一宏大背景之中。于是，立天人为基本架构，阴阳五行为天地生生之道的概括
表达，并以此作为理解事物的存在及其意义的基本方式。与之相应，中医认为人体生命现象
本就是天地所生之物，与生共俱地随同于天地之变化而变化，因而提出必须从天地之道的高
度来理解当下生命现象的存在及其意义，以阴阳五行理论来论述人体生理与病理的意义所在。

在印度哲学传统中，以梵我一如为基本框架，以解脱为根本宗旨，将事物的存在及其意义置
基于“即”（Sat）之上，所论述的世界观构建于瑜珈理论之上。与之相应，古印度医学，
即阿育吠陀（Ayurveda），就与瑜珈理论密切相关。倘若缺乏对瑜珈体系的深刻理解，就不
可能登堂入奥，理解阿育吠陀的精义所在。

与中、西、印凡事穷其究竟不同，阿拉伯人擅于以调和的方式进行思考，对万物的认知往往
停留于所观察到的经验事实之上，缺乏深入追问，抽象思考的理论冲动，与之相应，阿拉伯
医学传统虽遥接古希腊医学之余绪，凭借长期的经验积累，医技水平曾长期领先于西方，成
为西方医学的学习对象，却最终没能发展出如现代医学意义上那样的医学理论体系。

== 现代医学与传统医学之争

在古代，由于地缘时空上的范限，四大医学传统拥有相对独立的发展空间。各传统之间，各
走各路，各按自身的内在思路而并行发展着。其间，虽因跨传统间的文化交流，不可避免地
挟带着外来医学思想对所在传统的冲击，因有足够的回缓空间以消融外来传统的影响，将之
融纳入本土医学传统之中，因而，这些冲击不会威胁到所在医学传统的生存，甚或可资借鉴，
有助于提高所在传统的医技水平，因此，与外来医学传统之间的论争仅仅停留于最低的烈度
之上。

时至近现代，局势骤然一变。源出于古希腊医学传统的现代医学，昂仗科学所释放出的巨大
威力，迅速发展成超越于其他医学传统之上的最强大的医学知识体系，并借着西方文明主导
全球化历史进程之便，乘势迅捷地向世界范围内传播，已成功地确立为当今世界医学领域中
的知识标准。面对现代医学的强力冲击，其他医学传统无奈技不如人，既没有那个能力正面
应对挑战，又缺乏足够的回缓空间，从而主客易位，迅速地被边缘化，甚或连生存都难以为
继，从而触发了传统与现代医学之间的激烈论争。在中国，即体现为中西医学之争。

或许有人会说，既然现代医学在医技上的强势地位威胁到了传统医学的生存，那么，传统医
学何不审权度势，择取现代医学之长以完善自身，从而化解所面临的生存危机呢？乍听之下，
似乎言之在理，但做起来就远非那么回事了。

派生于西方哲学文化传统的现代医学，与源出于其他文化传统的传统医学，在医学形态上，
本就属于不同的知识类型。倘若为了补己之短而引入现代医学知识体系，那么，所引入的现
代医学知识因无法见容于所在传统的医学形态，成为了所在传统中的异己性的存在，不伦不
类，使得传统医学在理论形态上失去前后一致性。倘若迁就于传统医学，那现代医学在所在
传统的知识体系中将难有无容身之地，所谓引入，不过是徒费心力而已；倘若迁就于现代医
学，那必将否定传统医学本身的知识形态，这岂是传统医学所能接受的？

因攸关自身的生死存亡，面对现代医学的冲击，且在匆促之间，无以迴缓，为了能够生存，
又难免夹杂些民族意气，传统医学不得已奋起抗争，从而触发了传统医学之于现代医学间的
论战，激烈的程度是可想而知的。在论战中，传统医学与现代医学，各是所是，循着各自的
医学思考，去论证对方的存在价值，结果便是，横看竖看，所看到的尽是些弊端与不足。例
如，中医以整体论者自居，指责现代医学只会头痛医头，不求其本；现代医学则基于科学实
证，反讽中医理论，什么阴阳五行，气血经脉，都是些虚妄无稽，经不起检验的玄谈。因此，
所谓论战，犹如鸡同鸭讲，没有什么语言交集，徒增意气而已。最终只能在医技水平及知识
形态的效验上见真章，现代医学日夜精进，气势如虹，传统医学哪里抵得过？曾赖疗效以自
持的领域不断地被现代医学所蚕食，传统医学只能且战且退，不断走向边缘化，但最致命的，
并不是这些，而是来自于传统文化的生存危机。

作为传统文化之下的产物，传统医学医学思考及其所形成的知识形态的合法性必须通过所在
传统的哲学文化来赋予。一旦失去了传统文化的支撑，所在传统的医学体系必将失去自我解
释的思想基础。否定了传统文化，实际上也就否定了传统医学的存在依据。然而，在西方科
学主义思潮已经深透到整个社会的方方面面，无处不在，以是否符合科学的原则为基准，衡
量一切知识体系之真与伪的今天，传统文明已经丧失了文明对话者的地位，不幸被沦为西方
文化所解释、改造的对象，体现在医学领域，传统医学倘若不能从科学上寻找出自身存在的
依据，也就失去了令他人信服的基础，其结果只能是坐以待毙；可是，倘若以科学的规范去
重构传统医学的知识形态，支离破碎且不说，传统医学赖以生存的思想基础也被解构掉了，
皮既不存，毛将焉附？其结果只能是自找死路。就象中医，科学化这么多年了，结局如何，
大家都知道。是等死，或是找死？都是死路一条，之所以会这样，根源出自传统文化的生存
危机上。或者说，所谓传统医学的生存危机，究其实质，不过是在西方文明的冲击之下，传
统文明的生存危机在医学领域中的反映罢了。

然而，一百多年过去了，传统医学虽说生存唯艰着，风风雨雨，却能做到衰而不亡，败而不
绝，甚或呈现出某种复兴，出现逆向传播的趋向，如中医、阿育吠陀等在所在国家出现了复
兴的苗头，对西方国家的影响也日见扩大，这又是为什么呢？

从浅处讲，鉴于生命现象的复杂性，即便强大如现代医学，也不可避免地存在着这样那样难
以解决的问题；传统医学再怎么不济，毕竟凝集了数千年才智卓绝之士的心血，能历经无数
的临床检验而不绝，总会有些独到之处。生命诚可贵，有办法总比没办法好，作为替补，传
统医学的存在价值仍然不能被取代，从而形成以现代医学为主流，传统医学吃在两头的格局。
所谓吃在两头，通俗地说，就是专治那些现代医学根本就查不清、道不明的，或者效验不明
显，无有效治疗方案的，甚或无力承担高额费用的，套句IT界的时髦话，此即所谓的长尾效
应（Long Tail Effect）在医学领域的反映。

往深处讲，源出于西方的现代医学与传统医学一样，在人类医学领域中，都是特异性的存在。
古人不是说过，有所见，必有所蔽吗？现代医学纵然再强大，却始终无法摆脱其医学思考模
式本身所固有的内在缺陷；传统医学的不足与缺陷，那是明摆着的，但是特异性的医学思考
方式本身就足以证明它的存在价值。论战这么多年，现代医学都深入到分子与DNA了，但与
传统医学之间，却咫尺天涯，至今也没有找到可资相互理解的出路，这恰恰证明了传统医学
是特异于现代医学的医学存在，因而不可能被现代医学所取代。不可被取代，这不正体现了
传统医学的存在价值吗？！诚然，在医技、知识及其效验上，现代医学无疑要强大得多，但
这并不能说明现代医学理解生命现象存在及其意义的思路就能高人一等，就像在中世纪，西
方医学曾长期落后于东方，也并不能说明西方医学传统内在的思路就低人一等一样。

更深地讲，作为所在文化传统的所生物，任一医学传统的生命力深植于所在的文化传统之中。
当今医学领域中的强弱态势，实际上便是各文化传统之间的强弱态势在医学领域中的映象罢
了，因此，任何医学上的论争，最终都会涉及到文化传统上。一旦深入到文化传统的层面，
问题便骤然复杂起来了。在人类文明数千年发展史的宏大背景之下，百年弹指间，盛衰平常
事。器物一时之盛衰，文明一时之强弱，并不能说明多少问题。即便在近现代，西方文化固
然处于强势的地位，虽强势却不足以去征服；东方传统文明固然处于弱势的地位，虽弱势尚
不至于被征服。在可预见的时间尺度之内，且不论强弱态势如何，四大文化传统并存于世的
格局将会得以延续，人类文明终将何处去，仍是待定之天，远非如某些思想家所臆想的那样
简单。只要传统文明的生机一息尚存，传统医学便衰而不亡，败而不绝。在西方文明的弊端
与颓势渐显的今天，其他传统文明的存在价值也就被突显出来，在医学领域，传统医学出现
复兴，并向西方逆向传播的现象，这是理固必然的事。

== 在超越中走向未来

中国不是有句名言，人命关天吗？医学唯以治病救人为终极目的，本不应该有什么门户之见。
古人云：“救人一命，胜造七级浮屠”，在脆弱的生命面前，什么传统医学与现代医学之争，
都是些神马，能治好病才是关键，因此，在临床时，当以实效定取舍，该用什么就用什么，
择其善者而从之。然而，倘若仅以当下医技水平之高下来判定一种医学传统的存在意义，那
就非常短视了，因为传统之为传统的核心就在于独特的医学思考方式上，其存在的价值及其
发展的潜力并不在于医技水平一时之高下，而是在于这一医学思考方式本身的合理性。因此，
倘能敞开人类医学的思想视野，跳出狭隘的传统门户之见，以开放性的治学态度，回归到医
学之为医学本身的立场，那么，传统医学与现代医学之争所能揭示的只是这样一个事实，那
就是在人类医学领域，医学思考的基本方式及其形成的知识形态本就是多样性的，这就为人
类医学就其医学思考的基本范式及其医学知识形态之所缘自的反思敞开了全新的思惟视野。
如能以此为契机，以医者之为医者应有的胸襟与目光，打破既有理论形态上的深层束缚与偏
见，反思各医学传统的思想基础及其在人类医学领域中的价值定位，平心决择，博采众家之
长，以期实现医学思考方式的突破与超越，从而开创出能更全面地解读人体生命现象的存在
及其意义的医学知识形态，造福于人类的未来，则诚为医学之大幸，人类之大幸矣。

出于人类固有的思惟陋癖，人们在反思特定的医学思考方式及其知识形态的价值定位时，总
是习惯于以另一种特定的医学思考方式及其知识形态去反思、解释反思对象的意义与价值，
由于每一种医学思考的基本方式及其知识形态都是特异性的存在，彼此之间，本就不可通约，
所谓的反思，实际上成了解构与被解构的过程，除了证明某一基准的医学思考方式及其知识
形态正确不二之外，了无所得。体现于当今医学界，鉴于现代医学在当今医学领域中的强势
地位，人们已经习惯于从现代医学的视角去反思、评判其他传统医学体系，结果只能是除了
现代医学中的医学思考方式及其知识形态是科学的，正确不二的之外，其他医学传统中的医
学思考方式及其知识形态都是不科学的，或说是伪科学的，退一步说，也是原始、幼稚、不
成熟的，勉强算是前科学的。实际上，反过来也是一样，比如以中医的视角去反思现代医学，
同样横竖都是问题，近现代的中西医学论争可以充分说明这一点。

因此，倘要反思多样性的医学思考方式及其知识形态各自的存在意义与价值定位，首先必须
从既有的医学思考方式及其知识形态中超越而出，回归到多样性的医学思考方式及其知识形
态如何成为可能的源生性视角，才能无偏倚地提现并反思所要反思的问题，否则，就会不可
避免地陷入各是其所是，各非其所非的泥淖中无以自拔。换言之，跨传统性的医学反思，必
须以超越于各医学传统之上的医学思考方式为基础。鉴于医学之于哲学间的关系，这样的医
学思考方式唯有普适性的哲学系统才能赋予，也就是说，首先是哲学上的问题，其次才是医
学上的问题。

提起普适性哲学，这是一个迄今无解的哲学难题。自从西方文明对外扩张，开启全球化进程
以来，人类进入全球化的时代已经上百年了，但在哲学领域，思想形态上的进化远逊于全球
化的进程，仍然停留在四大思想传统鼎足而立的地缘格局中。所谓普适性的哲学基础，至今
仍隐伏于人类的思想视野之外。因此，跨传统间的医学反思与超越，在可预见的未来，很难
找出能根本性解决问题的出路，传统医学之于现代医学之间的论争仍将持续下去。本书仅以
重构中医理论的核心架构为基本目标，不想旁生枝节，去讨论这些恼人的哲学问题。在这里，
仅就各哲学传统所赋予的思考方式之于医学领域中的价值定位，谈一下我个人的看法。

首先必须说清楚的是，四大传统所提出的理解万物存在及其意义的基本模式在哲学上是完全
等价的，不存在高低之分，但尺有所短，寸有所长，缘此而形成的不同类型的思考模式在思
考人体生命现象时，所赋予的解决问题的效力却是不一样的。在印度哲学中，在梵我的大框
架下，深入任何特定事物所能得出的结论只能是一个幻（Maya），而终极实在却又不可说的。
作为医学，对人体各种生命现象内在本质的追问，最终必须落实到“什么”或“如何”上，
才会具有切实性的指导意义。幻则学无所稽，不可说则理无所据。况且，封闭性的能所框架
决定了对人体生命意义的解读视野只能内置于诸如瑜珈体系之上，难以实现真正意义上的理
论突破。阿拉伯人擅长调和，什么都有一定的道理，对事物偏重于感性认知，具有诗性化思
考的取向，实际上，阿拉伯人自己也认为，他们最伟大的成就是诗歌，而非别的什么。如以
这样的思惟模式去思考医学问题，往往满足于感官经验的积累与总结，难以穷极究竟，深入
追问生命现象背后的内在本质。

在四大传统中，唯有中国思想传统以“生”，欧洲哲学传统以“是”，这两种特异性的理解
万物存在及其意义的思考模式既能将人体生命现象的意义作为开放性的问题而思考着，又能
一以贯之，以穷极究竟。虽说在意义取向上，这两种思考模式上截然相反，有所谓相反相成，
相反性的意义取向反而能够赋予医学以不同的视角，以便更全面地反思生命现象的存在及其
意义，因此，彼此间等价互补。依据这样的思路，人类在医学思考方式上的突破，很可能出
自中西两大医学思考方式的整合与超越。果如其是，那么，中医理论系统只要能够挺过目前
所遭遇到的生存窘境，仍有其远大的未来。

== 还是以传统来解释传统吧

现代医学可以凭仗自身的强势地位，循着固有的内在思路，顾自向前发展着，勿须旁生枝节，
纠缠于其他问题，因为强势本身就足以说明现代医学的存在价值。身处劣势的中医则不然，
不仅要被迫应对日益膨胀的现代医学及其冲击，更为悲催的是，还得承受自身的生存基础，
即中国传统文化，因无力应对来自西方现代文明的全面挑战而惨遭解构的命运。在传统文化
惨遭解构，源出于西方的现代思想体系被确立为衡量一切真与伪的基准的情况下，作为劫后
余生者，为了求生存，中医被迫走上了以西格中的不归路，企图藉此找出能够继续生存下去
的理由与依据。

=== 无奈何以西格中

所谓以西格中，就是以现代文明中的思考方式及其知识形态来解释中医，此中，现代文明是
解释者，中医是被解释的对象。于是，阴阳五行被解释为朴素的唯物辨证法，整个中医知识
系统也被套上了科学的马甲，并试图以科学化的思路重整固有的知识系统，实现中医理论体
系的现代化转型与再生。这样做，可谓用心良苦，出发点无疑是好的，那么，其结果又如何
呢？

众所周知，现代意义上的哲学或科学都是从欧洲思想传统中派生出来的，而欧洲思想传统是
以“是”为核心基础的。所谓哲学，简单地说，就是研究“是”之为“是”的学科。无论是
形而上也好，辨证法也好，或是后来的现象学等，诸如此类，都是建立在“是”之为“是”
的理解与诠释之上的。所谓科学，词源为science，原意为知识，通俗地说，就是探讨特定
对象“是什么”而建立起来的知识系统，而中医则不然，秉承中国哲学的一贯思路，主张以
生成的角度去解读一切生命现象的内在意义。从本源上讲，“是”与“生”，彼此间的思惟
向度截然相反，存在着根本性的对立。比如，如以“是”，“这是”便成了理解事物最基本
的方式，这就意味着任一研究对象，如A，必须是独立性的，即A的一切属性必须出自A本身
的自我规定性，否则，一切基于“是”的断言都将失去意义。倘若A是非独立性的，而是被
他者，如B，所规定，这就会引起无穷倒退，一切基于A本身的断言都将无从谈起。如以
“生”则不然，事物不能自生，只能是被生成的，这就意味着任一研究对象都是非独立性的，
只能生存于他者赋予之中，如A的意义体现于B生A之中，换言之，一切基于A本身的断言都是
虚妄无稽的；如以“是”，则一切基于“是”的断言必将落实是“什么”上，这就意味着对
事物意义的理解必须是形式化的，倘若是反形式化的，如流变，那就难以用形式化的知识系
统来诠解了。回顾一下流变问题给古希腊哲学带来的困扰，就可充分说明这一点。如以
“生”则不然，生生不息，万物如流是题中应有之义，因此，事物的意义只能体现于事物的
变化之中。如以形式化的识度去诠释事物的意义，那还不是竹篮打水（^_^），……，套句
物理学术语，“是”与“生”,有点象波粒两重性，各自反映着各自的真实，却又无法拿捏
在一起诠解。

正因为中西文化的思想基础截然相反，造成中医理论系统之于现代科学形态之间，犹如圆凿
方枘，龃龉难入。所谓解释，只能是穿凿附会，削足适履，最终都会导致失真与迷失。什么
阴阳五行是神马辩证法，不妨去看看哲学大家如黑格尔等人的论著，辩证思惟之于阴阳五行，
相去不吝霄壤。什么中医也是科学，不妨去看看科学的思想基础及其思考方式，什么时候会
是中医这样子的？！循着科学化的路子，走了几十年，就科学而言，中医的思考方式及其理
论形态总是与之扞格难入，因此，时不时被科学中人指责为伪科学，这也是理之必然；就中
医而言，凡事都往科学上靠，必然会导致自身赖以生存的思想基础的迷失化与虚无化，以至
于即便是中医中人，能熟谙中医特有的思考方式去思考问题的人也日见稀少，其结局只能是
邯郸学步，一如网上曾传言的那样，现行的中医教育所培养的竟是中医的掘墓人！流弊之深，
莫此为甚！

=== 能继其往方能开其来

如果连自身的传承都难以为继，还谈什么将来？因为只有能传承才能有将来。中医之所以会
走到今天这一步，非所愿，实不得已也，最不得已的原因就在于传统文化话语权的沦丧。平
心而论，中国传统文化本是西方文化的对话者，但在言必称科学的今天，却不幸沦落为西方
文明所解释的对象。被解释者是没有话语权的，只能仰人鼻息，任人宰割。作为中国思想传
统的派生物，中医理论的思想基础及其合理性依据本就是中国思想传统所赋予的。传统文化
丧失了自我解释的能力，中医也就失去了安身立命的依据。因此，要想从根本上解决中医目
前的传承困境，首先必须打破科学化的百年迷思，迷途知反，回归传统。以传统解释传统，
重新赋予中医的医学思考方式及其理论形态的合法性。只有当中医不再成为现代文明所解释
的对象，而是能够自解释的理论系统时，中医才有希望从根本上解决生存与传承问题而得以
重生，涣发出强大的生命力。

从长远看，诚如改革家所鼓吹的那样，现代化仍是将来必走的路。然而，所谓的现代化，必
须发自中医自身的医学思考方式及其知识形态的自我突破与演进才有意义。换言之，只有回
归传统，才有可能实现基于自身传统的理论突破与超越，非此别无他途。至于突破与超越的
实现，则非经数代人的不懈努力不能成功。不积跬步无以致千里，作为当代中医中人，还是
让我们立足于当下，脚踏实地，从事中医传统理论形态的疏理与阐扬，使中医能够薪尽火传
而不绝，以俟后人的突破与超越吧！
