= 人之所有气与血

任何医学体系都必须构建于人体生理系统的解释之上，而解释系统又必须首先置基于可观察
到的经验事实之上。依据可观察到的基本事实，人体生理系统主要由臟腑、四肢、百骸等生
理器官构合而成，且称之为藏器系统，了解这些实体系统的生理结构及其功能是任何医学体
系所必备的基础。然而，作为医学，仅仅停留在经验事实的层面上是远远不够的，必须更进
一步，深入到这些经验事实背后，探析这些经验事实之所以形成的内在机制，构建出能够解
释这些经验事实的知识系统，才能做到知根知底，否则，仅知其然却不知其所以然，是无法
真正理解人体生理系统的。

经验事实依赖于生理感官系统的观察，观察到什么就什么，无关乎文化传统上的差异，但怎
样构建基于经验事实之上的解释系统，则取决于所在文化传统所赋予的世界观。即便基于完
全相同的经验事实，由于所处文化背景上的差异，所持的解释取向也就各不相同，这便派分
出了不同的医学传统。因此，在讨论中医生理解释系统之先，有必要介绍一下中国文化传统
中的世界观。

大凡深受现代生理学影响的人，往往心起疑惑，为何中医要将人体生理系统的核心基础建立
在看似云里雾里的气血及其运行系统之上，无他，这是中国传统文化所赋予的解释取向所决
定的。中国传统哲学认为，物之为物，固然有其形质上的规定性，但其所基的物质基础却是
不受任何形质范限的天地之气。气聚则物生，气散则物亡，一切形质上的意义都不过是天地
之气在聚散过程中所呈现出的外在表象，并不能反映万物内在的本质。倘要揭示万物的本质
及其意义所在，就必须深入到天地之气的变化法则中去。受此世界观的影响，正如《素问·
调经论》所说那样，“人之所有者，血与气耳”，气血聚则人生，气血和则人存，气血盈则
人强，气血亏则人衰，气血竭则人亡。因此，中医特以气血及其运行系统为生理系统的核心
基础，从而构建出具有独特理论形态的人体生理解释系统。

生身之先，精血凝集成形，化生臟腑百骸，而始有人身。人身既成之后，一方面，藏器系统
端赖气血周流，化生臟腑百骸经脉之气，煦濡推动于其中，才能各尽其形用，发挥其生理官
能。因此，气血及其运行时系统既是实体系统能够得以成形，也是实体系统能够各尽其形用
的不二基础。另一方面，气血的化生与运行又须仗赖藏器系统所主的生理功能，失去了藏器
系统的生理支持，气血及其运行不过是空中楼阁。因此，藏器系统既是气血及其运行时系统
物化与外化的表现形态，又是气血得以形成与运行的生理依托。藏器系统在人体生理系统中
的生理定位，必须通过各藏器在气血运行系统中的作用与地位来定义。

既以气血及其运行系统为人体生理系统的核心基础，揭示气血及其运行系统的基本框架及其
在生理系统的意义也就成为中医生理学的核心课题。为此，先贤们殚思竭虑，构建出了十分
独特而精深的理论体系。然而去圣久远，日久蔽深，即便那些素有研究的专业人士，能深入
其中而晓其大略的人也不多见。为此，依据本人多年治学的心得，从研习气血理论体系会遭
遇哪些问题入手，条分缕析，罗列如下论述提纲。在此后诸篇中，以《内经》的论述为基准，
旁及后世诸家之学，针对所列的提纲逐一详述。这样做，可以使得此后诸篇的论述，虽旁征
博引却杂而不乱，读者在阅读时，也有纲可循，便于循纲逐篇深入。

== 各类型气血运行时系统的基本属性

中医理论认为，人体之中存在着多种气血类型，即营气、卫气、神气、原气等。各类型气血
虽然各有各的系统特征，但就其基本属性而言却是一样的，无非是该类型的气血是如何化生
而来的，又怎样地循经而行，应时盛衰，具备怎样的生理功能等方面。其中，诸如化生于何
处、循行的系统架构及其所主的生理功能等方面是不会随时变化的，故可称之为静态属性，
而循行起止方位及应时盛衰沉浮等却始终处于动态性的变化中，故可称之为动态属性。

=== 怎样地化生而成

很显然，任何类型的气血都是其来有自，不可能凭空而来，必须通过特定的化生机制才能得
以生成。所谓气血运行时系统，顾名思义，就是以气血为主体的，因此，气血以怎样的机制
得以生成，涉及到气血运行时系统的主体如何成为可能的问题，是讨论该类型气血及其运行
时系统之先就必须予以解决的问题。

=== 怎样地循经而行

气血总是以循着经脉运行的方式存在着。在本书中，将气血循经而行所形成的系统命名为气
血运行时系统。运行时系统，原是编程学上的概念，在这里假以表达在气血循行过程中得以
形成的系统这一语义，它主要包括两个方面，即循行系统架构与应时起止法则。不同类型的
气血有着不同的运行时系统，特定气血类型的运行时系统框架体现着该类型气血运行的核心
特性。

==== 循行系统架构

气血既然以循经而行的方式而存在着的，这便涉及到是循行于经外或是循行于经中，怎样地
循经而行，循经而行所形成的系统是怎样的等方面的问题。所谓循行系统架构，就是指气血
在循经而行的过程中，顺着所循行的经脉依次贯连而形成的经脉循接系统的系统框架，是气
血循经而行基本法则的体现。

==== 应时起止法则

正如《素问·离合真邪论》中所说的那样，“经言气之盛衰，左右倾移……此皆营卫之倾移，
虚实之所生，非邪气从外入于经也”，气血在循经而行的过程中，并非以均态的，或说以平
铺的方式，而是以如海浪般涌动的方式进行着的，此即所谓“营卫之倾移”。如此，当气血
流经某经藏时，则该经藏中的气血充盈；已过或未至某经藏时，则该经藏中的气血亏虚。随
着气血循经流转，各经藏中的气血便会依次出现或盈或亏的动态更迭，此即所谓“虚实之所
生”；这些都是伴随着气血循流而形成的正常生理现象，故“非邪气从外入于经也”。

既然以倾移的方式而循行着，揭示气血循经而行的周期性特征也就具有切实的生理学意义。
所谓应时起止法则，就是指气血在周期性的循经而行的过程中，何时当始起于何经何藏，流
经于何经何藏，终止于何经何藏的规律。只有掌握了这一规律，才能切实把握气血循经而行
所形成的周期性的动态变化。

=== 怎样地淖浮沉泣

气血循经而行，各经藏中的气血出现动态的盛衰更迭，与此同时，作为循行的主体，气血本
身也会形成周期性的盛衰变化。体现在运行状态上，气血充盈则淖而浮，衰亏则泣而沉，直
接反映了气血本身所处的盛衰生理状态。因此，淖沉变化是描述气血运行时系统所处的运行
状态的重要指标之一。

== 各类型气血运行时系统的构合框架

既然并存着多类型的气血及其运行时系统，且又各循其道而行，那么，这些系统就必须藕合
成更高层次上的大系统，且称之为气血巨系统，并在该巨系统中实现藕合为一，才能做到并
行而不悖，否则，那岂不乱了套？从认识的角度，倘若我们仅能了解各类型气血及其运行时
系统，而不能从巨系统的系统架构出发，条分缕析各类型气血及其运行时系统在巨系统中的
意义定位，那么，我们对人体气血系统的认识注定是零碎的，散杂的。

然而，通览古今中医中人，甚至连各类型气血及其运行时系统尚且欠缺清晰的认识，看看那
些貌似高深，落到实处却百无一是的论述，就很能反映出中医界对气血理论的研究实况，能
够摸清既有的理论思路尚且不易，还谈什么巨系统？恐怕想都不曾想到过。现在有人提出要
构建巨系统的总体架构，该需要解决哪些问题呢？

=== 各类型气血系统的运行核心及其生理定位

所谓巨系统，本就是各大系统藕合而成，并非各大系统之外，另有一个什么里的气血系统，
因此，揭示各大气血运行系统的生理特征，是勾勒巨系统宏观框架的基础。跨类型分析巨系
统的生理特征，有两条主线索，一是巨系统中各类型气血不可能是凭空而来的，必有其所源
自。循着各类型气血依次生成的整体流程，便可以将各类型气血依次串联起来，从而勾勒出
巨系统气血化生流程的宏观性轮廓；二是各类型的气血必各有其运行的核心。找出各核心的
生理定位，便可勾勒出基于各类型气血运行核心之上的宏观框架。

各类型气血运行系统在生理系统中所起的作用体现在各自所主的生理功能，并协同维持起人
体正常的生理活动上，因此，厘清各类型气血运行时系统所主的生理功能，我们才能揭示各
类型气血系统在人体生理系统中所起的生理作用及其生理定位，从而勾勒出生理系统底层的
主控性系统架构。

=== 整合各类型气血系统而后成的巨系统框架

解决了各类型气血在巨系统中的生理定位问题，还必须更进一步，实现基于各类型气血运行
时系统的系统框架之上的融合与统一。在巨系统中，各类型气血各有各自的循行系统架构，
倘若能够整合为一，那么，当以怎样的方式进行整合，整合所成的巨系统架构又是怎样的呢？
只有解决了这个问题，我们才有可能深入理解各循行系统架构的意义所在以及彼此之间的相
互定位，以宏观的视角，揭示各类型气血运行时系统基于巨系统之上的内在统一性。
