= 法象日月而行之

既以气血及其运行时系统为人体生理系统的核心基础，揭示各类型气血运行时系统的运行特
性也就成为中医的核心课题之一。其中，各类型气血的循行系统架构是与生俱来，终生不移
的，虽然有些复杂，毕竟是固定的东西，至少在理论上，把握起来要相对容易些，更何况，
《内经》在这方面的论述还算详尽，有据可依。大凡中医中人，都能知其大略。气血的运行
时状态则不然，因始终是变化着的，而且，这种变化隐秘无形，从外部根本就不可能被察知，
既看不见，又摸不着，让人难以着手。因此，即便是《内经》，也没想出个完整的解决方案，
至于那些后世的医家，那就免谈了。那么，这是否就意味着没有法子可想了呢？

那就未必了。《内经》没有提出完整的解决方案，这不假，然而却提出了解决这一问题的核
心思路，有思路便有出路。从人与天地相参也这一原理出发，《内经》提出了气血之行法象
于天地日月之往来的理论构想。《灵枢·痈疽》中说：营卫之气“行有经纪，周有道理，与
天合同，不得休止”、“经脉留行不止，与天同度，与地合纪”、“夫血脉营卫，周流不休，
上应星宿，下应经数”，《灵枢·营气》中说：“常营无已，终而复始，是谓天地之纪”，
《灵枢·营卫生会》中说：“如是无已，与天地同纪”，《灵枢·脉度》中说：“气之不得无
行也，如水之流，如日月之行不休”。内在气血的运行变化，因“不形见于外”，故然是幽
冥难知的，但是，天地日月之往来却昭然在目，何不以天地日月之往来去模拟体内气血的运
行变化呢？这是很自然的思路，问题在于应该怎样地模拟上。

且就体内气血的运行时状态而言，不外乎应时起止与淖浮沉泣两大变量，那么，天地中的日
月又如何呢？同样也存在着两大变量，一是各日时日月在十二宫分野上的巡行起止，一是在
四时中的盈亏寒温状态变化。倘若气血之行法象于日月的设想果真能够成立，两大变量之间
最有可能的同步关系应该是气血之应时起止同步于日月之巡行终始，气血之淖浮沉泣同步于
日月之盈亏寒温。实际上，《内经》也就是这样想的。依据这样的同步关联，通过观察四时
日月之往来，怎样演绎气血中两大状态变量的变化法则呢？

== 以日月之巡行终始演绎气血之应时起止

日月巡行于十二宫分野之上，气血循行于十二经范围之中，彼此天地悬隔，霄壤各异，那么，
该以怎样的思路，构建出能够以日月之行演绎气血之行的理论模型呢？倘若避开演绎过程中
的具体性问题，仅概略以论之，要做到这一点并不太难，大致可分为以下几个方面的问题。

=== 所法对象的定位问题

就气血之行所能法象的对象而言，有日与月之分，这两者的视运动特性也各不相同；就气血
本身而言，也存在着不同的类型，不同类型的气血也有着不同的运行特性。因此，假如气血
之行法象于日月，那么，不同类型的气血之行所法象的日月对象也应各不相同。一般而言，
如营卫等单一性的气血类型，如论其所法象的日月对象，只取其中之一即可，那么，当以何
者法象于日，何者法象于月呢？神气与营卫不同，是综合性的气血类型，包涵着气分与血分
两大部分，那就要同时法象于日月两者，那么，当以何者法象于日，何者法象于月呢？这显
然是必须优先解决的问题。

=== 循行框架的映射问题

气血循经脉以行，日月循十二宫以行。因此，如假日月之所行以演绎气血之所行，就必须将
该类型气血的循行框架依次映射到十二宫分野上，从而构建出气血之所行之于日月之所行的
映射模型。由于各类型气血运行的系统框架各不相同，原本就十分复杂，怎样将各类型十分
复杂的系统框架映射到简洁的十二宫之上，这就要涉及到许多映射处理上的细节问题。

=== 模拟演绎的基本思路

各类型气血之所行之于日月之所行的映射模型既定之后，接下来就可以依据日月之所行模拟
演绎各类型气血之所行了。首先，将气血循经依次而行的动态过程比拟为日月东西而行的视
运动过程，然后，再依据日月基于十二宫之上的周期性视运动的运行法则，通过经藏之于十
二宫的映射模型，转化为气血基于经藏之上的周期性的应时起止法则。这便是假日月之所行
模拟演绎各类型气血之所行的核心思路。当然，倘想实际演绎各类型气血实时性的循行法则，
会所涉及到许多难以解决的具体问题，这里就不深谈了，容后续诸文逐一细细道来。

不知大家注意到没有，就日月视运动本身而言，自东而西，顺向而行，恒古不移。然而，由
于日行不及天，月行又不及日，出现日月视运动逐日之终始自西而东逆向偏移的周期性现象。
因此，如依日月周期性的运行取向而言，当以自西向东而行，虽曰逆，顺在其中焉，因为周
期性的行为取向本就是建立在视运动之上的，这便形成了独特的逆顺之常现象。倘若气血之
行果真法象于日月，那么，也会形成类似的逆顺特性，即气血逐周之终始依次更迭所形成的
周期性的行为取向与其真实的气血循经而行的实际走向相反，这便形成了诸如《营气》中所
谓逆顺之常的现象，奈何千百年来竟然无一人能够看得破，以致谬解误人至今，唉，这该叫
人怎么说呢？

提出一个伟大的理论设想固然不易，将理论设想转化为实际可行的解决方案同样会遇到不少
难题。《内经》虽然提出了气血之行法象于日月，故可假日月之所行演绎气血之所行的伟大
设想，并据此进行了简略的模拟演示，如《五十营》、《营气》等，却并没有进一步深入，
构建出能实时演绎气血之行的解决方案，这就给后人留下了十分艰涩的理论难题。自《内经》
之后，那些中医中人，甚至连《五十营》、《营气》等文的基本语义都理解不了，还能指望
些什么？回头再看后世诸家之学，子午流注说称得上是异数，居然深得《内经》精义，并能
推陈出新，提出了一套较完整的解决方案。流注学虽说信从者不少，却全是些不知所以然的
人，以至于被后人曲解而讹传于世，因此，在后续诸文中，对流注学进行拨乱反正是本卷论
述的重心之一。

== 以日月之寒温盈亏演绎气血之淖浮沉泣

假四时日月之行，模拟各日时中气血的应时起止法则，这个比较深奥，懂的人很少见。气血
之淖浮沉泣法象于日月之寒温盈亏的道理则不然，这很好理解，更何况，《内经》又说得很
明白，读过中医的人都知道，多说令人厌。

人与天地相参也，与日月相应也。故月满则海水西盛，人血气积；肌肉充，皮肤致，毛发坚，
腠理郄，烟垢著，当是之时，虽遇贼风，其入浅不深。至其月郭空，则海水东盛，人气血虚，
其卫气去，形独居，肌肉减，皮肤纵，腠理开，毛发残，膲理薄，烟垢落。 ——《灵枢·岁露
论》

天温日明，则人血淖液而卫气浮，故血易泻，气易行；天寒日阴，则人血凝泣而卫气沉。月
始生，则血气始精，卫气始行；月郭满，则血气实，肌肉坚；月郭空，则肌肉减，经络虚，
卫气去，形独居。是以因天时而调气血也。 ——《素问·八正神明论》

天温月明，则气血充淖而浮；天寒月晦，则气血凝泣而沉。因此，气血本身基于淖浮沉泣的
状态变化同步于四时日月本身在寒温盈亏上的状态变化，因此，通过观察四时日月之寒温盈
亏，就可以推知体内气血之淖浮沉泣。

 
