= 流注学核心提纲

经藏气血在循经而行的过程中，究竟怎样应时起止，是《内经》留待后人解决的理论难题。
不过，从现存的文献上看，实际上古人就已深入思考过这一问题，并试构出了一整套的解决
方案，这就是后人所说的六十首法与夫妻经原穴法。提起此两法，尤其是六十首法，可谓是
中医学史上处境最为尴尬的学术，信从者奉之为圭臬，质疑者认为斥之为虚妄，但是，无论
是信从者或是质疑者，都是望文臆解，不知其所以然的，因此，无论是支持或是反对，究其
实际，不过是场学术闹剧罢了。之所以会形成如此不堪的局面，就在于自《内经》之后，天
人之学的精髓便已失传，无人能够深入晓会，而流注学自传世之时起，演绎原理便已失传殆
尽，以至于后之学者莫名所以，开口动手便错。

然而，后人的误解无损于此两法的历史价值。俗语说得好，外行凑热闹，内行看门道。能够
深入领会《内经》气血理论的核心思路及其缺憾，并提出创造性的解决方案的，古往今来独
此一家耳，因此，即便所提的方案未必尽美，价值却是不言而喻的。自《针经》传出时起，
迄今已有一千多年了。多年前，本人初见六十首时，也是一头雾水，虽日思夜想，却始终理
不出个头绪来。后来深入《内经》而略有心得，在不经意间，窥得此中的奥秘，不敢独享，
现将此两法所基的核心思路整理起来，传示于天下。

== 现传流注学的核心思路分析

且就此两法的核心宗旨而言，倒也简单，就是依据气血之行法象于日月的理论，以日月之行
为原型，演绎出经藏气血应时起止的规律，以解决《内经》遗留下来的理论难题。从此种意
义上讲，古往今来，能够称得上续《内经》之绝学的，唯此两家之法了，很牛吧？嘿嘿。那
么，流注学又是怎样地解决在演绎过程中必然会遭遇到的种种理论上的难题的呢？

=== 怎样地构建气血之行的法象模型

==== 怎样构建十二经应时依次出入之序

自《内经》时起，基于天干、五行、经藏之间的映射模型就被立为天人相应的标准范式。甲
胆乙肝，木也；丙小肠丁心，火也；戊胃己脾，土也；庚大肠辛肺，金也；壬膀胱癸肾，水
也。至于三焦、包络，依例不计在内。映射到天体上，以周天365.25°计，每干经各主
36.25°，遍历十干经，一周于天，天人一致。大概是因为实在想不出更好的解决方案，此
流注学只得依此范例为基础，去构建十经气血依次出入之序，干经范式也就成为演绎气血之
行的核心基石之一。

然而，气血之行所法象的对象，即日月之行，却是以十二宫为纪述单位的，因此，必须将干
经范式映射到十二宫中去，才有可能假日月之行去演绎气血之行，怎样映射也就成为必须解
决的关键问题之一。在古代术数中，干与支的映射是有一定惯例的。依据惯例，流注学将首
干甲定位到卯宫，而后乙在辰，丙在巳，依次循序映射，从而构建出干经之于十二宫的映射
模型。可是，天干仅以十计，十二宫却以十二计，以十干循序映射十二宫，最终必然出现尚
余两宫无所配的形情，倘若任其阙如，当年周日月之行入主此两宫时，因无所主之干经而无
法顺次模拟演绎，就会出现演绎上的断层，这怎么能行呢？要知道，循环灌注乃是流注立学
之本，那么，所余两宫应该如何处理呢？

首先是在十二宫中的定位问题，因为所余两宫位在十二宫分野上的不同定位，将直接影响到
此两宫的干经定性问题。在六十首法中，依次循序映射，将壬膀胱定位到亥宫之后，将癸肾
定位到寅宫，这样，所余两宫在子丑；而在原穴法，将癸肾直接定位到壬亥之后的子宫，这
样，所余两宫便在丑寅。

其次是干经映射上的定性问题。因为在演绎时必须以所在之宫的干经属性作为气血所注之经
的依据。倘若所余两宫既无所配之干经，所谓演绎，也就无从谈起。在六十首法中，由于子
丑两宫在壬之所主亥宫、癸之所主寅宫之间，在天干上仍隶属于壬癸分野之内，故仍以壬癸
配之；而在原穴法，由于丑寅两宫位于癸之所主子宫、甲之所主卯宫之间，已经独立于十干
分野之外，怎么办？原穴法为此提出了十分有意思的想法，将丑寅两宫配之以戊己。所余两
宫的天干定性大致如是，问题是如何定位其经藏属性呢？如果仍然墨守干经范式，那么，在
六十首法中就会出现壬膀胱与癸肾重复流注，在原穴法中出现戊己脾胃重复流注的现象，这
显然是不被允许的，因此，所余两宫的经藏定性问题只能从干经范式之外去解决。反观人体
经藏系统，总计才只有十二，除去十干经之外，可供选择的也只有三焦包络，因此，无论是
六十首法之于子丑两宫，或是原穴法之于丑寅两宫，都配之以三焦包络。

==== 怎样构建阴阳相及、气血并流模型

基于十二宫之上的干经映射模型既定之后，十二经藏气血依次出入之序及其天人模型也就确
定下来了。接下来，那就是阴阳相及、气血并流模型如何建构的问题了。然而，六十首法残
缺不全，原穴法也缺失解释性文献，已经很难找出流注学解决这一问题的思路了。倘想还原
出流注学的解决思路，依据仅存的文献，只能从六十首法原有两种的说法入手。

===== 外行脉经与内行血经两种六十首

据《针经》转述，贾氏认为，六十首法原有两种，即外行脉经六十首与内行血经六十首，后
者因故失传，那么，现传六十首法当为外行脉经六十首。从外行脉经与内行血经的提法中看，
后者既以血立论，那前者只能以气立论。气行于脉外，血行于脉内，两种六十首法很可能就
是依此而命名的。贾氏又说“阳日气先脉外，血后脉内；阴日血先脉外，气后脉内”，在现
传六十首法中，阳日以气立论，阴日以血立论，这与“阳日气先脉外”、“阴日血先脉外”
中“阳日气”、“阴日血”相同，而“XXX先脉外”又与气行速，行于脉外在语义上相通，
因此，据此可以佐证现传六十首法就是外行脉经六十首。

那么，失传的内行血经六十首是怎样的呢？依据“阳日……血后脉内；阴日……气后脉内”，
以及血行迟，行于脉中的说法，“XX后脉内”应该属于内行血经六十首部分。参照现传六十
首法中，阳日阳时气行阳经，阴日阴时血行阴经的演绎体例，“阳日……血后脉内；阴
日……气后脉内”应该是指阳日阴时血行于阴经、阴日阳时气行于阳经的流注规律，而这恰
恰是《针经》所缺如的。试想，气血之行应是逐日十二时遍历于阴阳十二经的，岂会阳日只
注阳时阳经、阴日只注阴时阴经？很显然，《针经》所载是残缺不全的，这也证明了贾氏所
说内行血经六十首法已经失传的说法。既云失传，是否就无迹可寻，不可窥知了呢？那倒未
必。

通过演绎，发现现传外行六十首法是以年周日视运动为法象原型的，依理而推，失传的内行
六十首法只能以月周月视运动为法象对象，当然，猜想是否能够成立，还有待于文献证明。
后来，本人在试着演绎原穴法时，总是有种似曾相识的感觉，于是将现传六十首法与之比较
一番，终于证实了心中的直觉，原穴法中的阳日阳时阳经、阴日阴时阴经部分就是在现传六
十首法的基础上发展而来的。而阳日阴时阴经、阴日阳时阳经的流注规律，也就是《针经》
所缺如的部分，就是以月周月视运动为法象原型演绎而成。更为重要的是，原穴法中的壬子
日阳时所主之时干，癸丑日阴时所主之时干移植于现传六十首，这就证明了原穴法之于六十
首存在着学术传承关系。据此推论，原穴中的壬子日阴时所主之时干，癸丑日阳时所主之时
干应该移植于内行六十首。为此，本人顺着现传六十首的思路，试着以月视运动为法象原型，
演绎三焦、包络之所主时干，结果与原穴法所载壬子日阴时所主之时干，癸丑日阳时所主之
时干完全一致，这就坐实了内行六十首是以月视运动为法象模型演绎而成的猜想。

===== 阴阳相及、气血并流的运行模型

既然知道了两种六十首法的演绎原理，流注学中的解决思路也就一览无余了，那就是各日之
中，所主之经与其表里相及之经相依并注，并以阳时气注阳经，阴时血注阴经，分开纪理。
其中，所主之经如为阳经，则以气先脉外论。如为阴经，则以血先脉外论；相及之经如为阳
经，则以气后脉内论。如为阴经，则以血后脉内论。如此，所主相及之经合而为一，便形成
了阴阳相及、气血并流的运行状态。

搞清楚演绎模型并不难，难在所以然上，为什么会采用这样的演绎模型呢？参照《内经》，
所谓X先脉外，似乎源于气行速，行之于脉外的说法。所谓X后脉内，似乎源于血行迟，行之
于脉内的说法。参验流注法，各日所主之经的应时起止法象于年周日之行，所及之经的应时
起止规律法象于月周月之行，参照日行速，月行迟，故以日之行演绎气之行，以月之行演绎
血之行，从而形成气血行于所主之经以X先脉外论，行于相及之经则以X后脉内论，倒也言之
在理。令我百思不得其解的是，为什么又以阴阳经而分立气血，阴经主血，阳经主气呢？至
少，从纯演绎的角度，这样做，实在看不出有什么必要。

==== 怎样构建经藏气血系统的法象模型

依据年周日月之行的周期性特征，倘要以年周日月之行为原型推演十二经气血之行，可供选
择的可行性解决方案并不多，实际上只有一种，也就是十二经周期性出入规律，即各日所主
之经应时起止规律法象于年周日之行，再以所及之经的应时出入法象于月周月之行。因此，
此两法中的演绎思路不过是意料中的事。令我感到惊奇的是，所及之经出行取法于月相变化
上。以日月交会所在之宫为基准，所及之经若为阴经，法象于望后月始晦，若为阳经，法象
于朔后月始明。以月相之明晦变化，推知所及之阴阳经气血所出之时，真可谓是匠心独运了。
今绘月相始明始晦定位图如下：

流注学核心提纲

=== 怎样地以日月之行演绎气血之行

==== 怎样构建年周日月之行的巡行模型

虽说都以年周日月之行为法象的对象，但从所基的日月之行模型上看，所立的回归点各不相
同，六十首在子宫，原穴法在寅宫，因此，年周日月之行的纪述模型也就各不相同。前章已
经谈过，回归点的设定必须依据所演绎的系统的核心特征而定。由于所演绎的经穴系统各不
相同，各设其回归点，本是情理中的事。虽说从理论也可找出各自所持的理由，但归根结底，
所演绎的不都是经藏气血系统呢？依据营卫协同模型，立水火为中轴而以子为回归点，六十
首法的做法没什么问题，原穴法立在寅宫就有些疑惑不定了。

==== 怎样设定经藏气血运行的法象周期

既以干经映射模型为演绎系统的核心架构，依据《内经》中以十干日法象于一年之数，流注
学以十干日为一个天人法象周期，也不失为言之有据。倘若能够抛开既有观念的束缚，直视
所要解决的问题，那么，年周日月之行是十分复杂的系统性行为，如想无损映射为十日之中
的气血循行法则，那几近是不可能的事。试想一下，以年周日月之行演绎十干日气血之行，
则各干日之中，气血循行阴阳十二经一周于身对应于日月之行一月之数，大凡三十周于天矣，
连大略也难以做到，怎么可能做得到全息模拟呢？这必然会导致模拟上的失真，难免有些削
足适履之嫌。不过，在现有的理论中，恐怕也找不出更好的解决方案了，凑合着用吧。

==== 怎样演绎各日时中的气血流注规律

虽说六十首以五输，原穴法以原穴，所基的经穴系统各不相同，但就演绎气血循经而行的思
路却是一致的，就是以各日所主之宫为基准，依据年周日月之行，以所主之宫所对应的月分
的日月运行状态去推知该日所主所及之经的初出时辰，再以阴阳经分列纪述，各以干经五行
相生之序，依次推及阴阳各时所循之经及其所注之穴。在实际的演绎过程中，因无法将四时
日月之行完整地转换为十日气血之行，所谓模拟演绎，也只能是示意性的。另外，依据本人
的演绎体会，各日时气血之所注实际上是以经为单位的，而穴法仅是出于演绎体例罢了，不
必拘泥的。

由于演绎是以干经映射模型为基础的，因此，演绎的体例也就受到该模型的限定。在该模型
中，无干经所配的两宫位因无法纳入干经模型而被另案处理，体现在各日时气血流出入的演
绎上，十干日阴阳时可以依据干经范例依次演绎，但是，倘若空缺两宫仍以此范例处理的话，
就会导致整个干经演绎体系的紊乱，只能以另案处理，因此，整个的演绎系统，如依演绎思
路上的差异，可以划分为两大部分，即十干日的循经流注规律与空缺两宫的循经流注规律分
列论述。

=== 十干日阴阳经应时流注的规律

==== 所主所及之经气血初出之时

所主所及之经气血初出之时的推定是以年周日月之行的运行状态为原型的。以各天干日所主
之宫为基准，转化为年周所主之月，依据年周日之行，推算出该月日视运动出入所在之宫，
以此所在之宫作为该日所主之经气初出之时；再以所在之宫为基准，所及之经如为阴经，推
算出月始晦所在之宫，如为阳经，则推算出月始明所在之宫，尔后以月之所在作为该日所及
之经血初出之时。比如，在原穴法中，甲日主卯宫，依以年周日之行，卯月日月交会于寅宫，
故甲日所主之甲胆经之气自寅时出行；乙肝与甲胆相表里，故被立为甲日所及之经。乙肝属
阴，出行之时法象于月始晦。以卯月日之行起止于寅宫为基准，月始晦于未宫，故未时立为
乙肝之经血始出之时。

如按某日某时某经气血出行的纪述体例，似乎存在着逆向的解释方法。如甲日寅时甲胆经气
血出行，也可以解释为寅月日月交会于卯宫，故卯宫所主之甲日甲胆经之气自寅时出行，似
更通顺些。但这样解释，因涉及到日月交会问题，会比较复杂，一时也想不出较为简明的论
述方式，因此，在此后的论述中，仍采用上面的解释体例。

==== 阴阳经依次循经流注的规律

推知各日所主相及之经气血出行之时后，倘要演绎各时气血循经穴而行的规律，必须掌握两
大要点，一则各干经所主之时以十二支来表示，各时所主之经藏以干经范式为基础；二则按
阳时主气行，流注各阳干经穴，阴时主血行，流注各阴干经穴，分开纪理，各依干经五行相
生的原则，依次推算各时所流之经、所注之穴。当然，倘要深入理解这一演绎体例之所以然，
如营卫本是循环灌注的，为何会是阳时气行，只注于阳经穴，阴时血行，只注于阴经穴呢？
诸如此类，有待进一步的思考，坦率地说，我也搞不懂。

如按阴阳分列纪理的算法，阴阳干依次相生，五步为一周。阴阳时依次缕列，六步为一周。
这样一来，干支各行，依次配应，就会出现阴阳干经既行一周之后，阴阳时尚须再行一步，
方为一周。如此，便会出现未支时没有相配应的干经的现象，倘若任其阙如，则违背各时各
干一一对应的演绎体例而前后不一，怎么办？流注学的解决思路是，干经按五行相生之序依
次运行五步之后，也再行一步，所得之干立为未支时所主之干，但这样一来，就会产生新的
问题，即所得之尾干与初干相同，古人谓之天干重见，如何定其所主之经穴呢？

倘若重见之时，所主之干仍按干经模型中的配应方式处理，就会形成该干所主之经首属各注
一次，出现重复流注的现象，这显然是不被允许的。倘若不配以所主之经，任其缺失，那各
日之中便会出现两个时辰无所注之经的现象，这也太荒谬了！因此，倘要解决重见之干的经
脉定性问题，也只能到干经范式之外去解决，或者说，可供选择的唯三焦、包络耳，于是便
出现了所谓天干重见，则气纳三焦、血纳包络的演绎体例。

==== 无所配两宫位的应时流注规律

在十干日之中，可以依据各日所主之干经，推知相及之经，演绎阴阳经各时的流经注穴法则，
但六十首法中的子丑两宫虽配以壬癸，原穴法中的丑寅两宫虽配以戊己，显然不能再按十干
日中壬癸、戊己两日的演绎法则进行演绎，因为这样做，就会导致与壬癸、戊己两日的流注
法则相重复而冲突，这是不能容忍的，可是，不管它吧，就会出现整个系统严重的演绎断层，
更不可能被接受。在此两难之中，该如何处理呢？

依据六十首的做法，既将子丑两宫配之以三焦、包络，那就不妨以两经五输配各时，待天干
重见时，再以气血入行来处理，粗略看来，这样做，既可解决各时所主经穴的问题，且不与
壬癸两日中的经穴体例相冲突，又与十干日中各日天干重见之时气血纳入三焦包络遥相呼应，
貌似形成以三焦包络为核心的十二经气血循环系统。不过，一经细想，问题也不少，例如，
不但各时所主之干与壬癸两日出现了重叠现象，而且与十干日中各时所主之干经的演绎体例
也格格不入，整个演绎系统因此而失去了前后一致性。到了原穴法，问题就更复杂了，大概
也是苦思无计，竟然将六十首中的解决方案径自移植过来，缘此而衍生出的问题，这里不想
再作评述了。

== 流注学核心思路的改进方案

以年周日月之行为原型演绎体内气血之行，依《内经》的思路，这一构想本身没什么大问题。
之所以会问题不断，主要有两大原因。一则，年周日月之行是极其复杂的系统性行为，以现
有的水平，很难找出能够无缝映象的模拟演绎方法；二则，自《内经》时起，中医基础理论
中的天人模型本身就存在着先天不足，难以胜任如此复杂的演绎工作。前者么，我也没这个
水平，不谈了。下面就谈谈后面这一原因所引起的问题及其改进方案。

在古代天区分野中，如以十干计，则每干宫各主36.53°，遍历十干，历行365.25°,一周于
天，这实际上是一种基于太阳历的划分方法；如以十二宫计，则每支宫各主30.44°，遍历
十二宫，亦历行365.25°,一周于天，这实际上是一种基于阴阳合历的划分方法。因此，这
两种天区分野所基的历法基础是不同的，切不可混在一谈的。在中医基础理论中，攸关天人
的论述都是以五行为基础的。由于五行之于十二宫难以构建出前后一致性的理论模型，后人
论述天人也多以干经映射模型为标准范式。流注学秉承这一传统，以干经映射模型为经藏气
血依次出入之序，这也是惯例使然。

然而，演绎气血之行却必须以四时日月之行为原型，而日月之行却又必须以十二宫为基准，
这就意味着倘想以四时日月之行演绎经藏气血之行，就必须将天干分野迁就到十二宫分野上
去，也就是说，每干宫也必须以30.44°计，这从历法上讲，将太阳历套进阴阳合历混着谈，
如何行得通？！只要不出什么岔子，能含糊过去也就算了，真正恼人的是天干仅以十计，十
二宫却以十二计，无论你怎么配，配来配去，七个瓶八个盖，总会有两宫无所配的演绎断层，
体现在十二宫之于所主日干上，就会出现尚余两宫无所主之日干的断层问题，体现在各日十
二时之于所主之时干，就会出现尚余两时无所主之时干的断层问题。当然，流注学为此提出
了各种补救方案，其中，又以三焦包络出力尤多，哪里出现了断层，哪里就拿出三焦、包络
来塘塞过去，三焦包络成了解决问题的万金油、百搭子、救火员。套句编程术语，干支配应
出现断层是个大Bug的话，那三焦包络就是修补这个Bug的大补丁。

之所以会出现如此紊乱的形情，病根就出在干经映射模型上。试想一下，就气血之行而言，
必有其特定的运行法则，依次遍历于十二经而为一周于身。三焦包络在整个十二经系统中，
如同其他十经一样，自有其特定的系统定位，而干经范式罔顾三焦包络的客观存在，仅以十
经立论，就凭这一点，就足以说明该范式并不适用于描述气血运行的基本法则；就气血之行
所法象的对象而言，日月往来必以十二宫为测纪标准，这与干经范式所基的太阳历本就龃龉
而难入，因此，倘要演绎气血之行，如能以十二经映射十二宫为基础，那是最合适不过的，
而流注学却以干经范式为核心基础，不出问题才怪呢。那么，有没有办法构建出十二经之于
十二宫的天人模型呢？

办法总是有的，那就是借鉴采用经藏气血系统的运行模型。假如干经模型中阴阳表里依次相
及的法则是正确的话，那么，十二经藏气血依次出入之序为自胆肝木始，次至小肠心火，次
至胃脾土，次至大肠肺金，次至膀胱肾水，次至三焦包络相火，如此遍行于十二经为一周。
再假如流注学将甲胆经定位于卯宫的初始定位是正确的话，那么，十二经之于十二宫的列行
定位依次为，胆卯、肝辰、小肠巳、心午、胃未、脾申、大肠酉、肺戍、膀胱亥、肾子、三
焦丑、包络寅，列图如下：

流注学核心提纲

从源承上看，这一列图可视为现传干经模型的有效扩展，故在底层上具有较好的向前兼容性。
或许有人说，一则以干立论，一则以支立论，变成了不同的东西，扩展之说从何而来？这些
都是死读书的人的想法。在干经模型中，天干主要的作用就在于通过干经映射确定经藏依次
出入之序。既然经藏依次出入之序是已知的，再去套用天干以为说，有必要吗？再者，从演
绎的角度，经藏在十二宫中的循行定位才是至关重要的参数，天干分野既不适用于十二宫，
留之何用？何不择其善者而从之，直接采用十二宫分野纪述之呢？

如依上述图式为准，则十二经映射十二宫，次序森然。在各日之间，以年周日月之行演绎各
日所主相及之经气血出行之时，根本就不可能出现演绎断层问题。在各日之中，所主相及之
经气血既出之后，依据六行与其所属经穴的对应关系，各按六行循环相生之序，依次循时运
行六步，所形成的十二时行及十二经的时经流注模型，同样不会出现演绎断层问题。因此，
所谓断层的解决方案也就没有存在的必要。至于具体怎么演绎，这里就不作详述了。依据自
《内经》之后的老传统以及现传流注学的演绎法则，论及天人之际，多以十干日立论，如依
此新图式，恐怕要以地支纪日，十二日为一周了。在崇古气息浓重的中医界，能认同的人或
许并不多。更为重要的是，无论演绎得怎么漂亮，到底对不对，无从实测证明，终究是心中
没底的，不演示也罢。

世传纳子法不是以十二时论十二经吗？依据年周日月躔度，照葫芦画瓢，也可以演绎出十二
经气血出行之时。例如，戍月日月交于卯宫，故卯宫胆经气血戍时出行；酉月日月交于辰宫，
故辰宫肝经气血酉时出行；仿此类推，小肠在申，心在未，胃在午，脾在巳，大肠在辰，肺
在卯，膀胱在寅，肾在丑，三焦在子，包络在亥。当然，这也是聊备一说，无从验证的。

== 客观评价流注学的学术成就

坦率地说，学术贵在探索，本就是成固欣然，败亦可喜，成功不必在我的事情。虽然，在现
传的流注学中内在着不少缺点，而且问题很严重，远不是什么成熟可行的解决方案，但这些
缺点在古人的学术视野中根本就是无解的，因为根子出在以五行为核心的天人框架以及天人
映射演绎上的复杂性，实在怪不得他们，因为即便到今天，同样谁也解决不了，何必去苛责
古人呢？然而，能够秉承《内经》中气血之行法象于日月的基本思路，以年周日月之行，去
试着演绎十二经气血的运行法则，以解决《内经》遗留下来的理论难题，单凭这种直面问题，
勇于探索的精神，就值得后人学习。回头再看那些所谓的大家们，甚至连《五十营》、《营
气》这样的经文都会理解错，这样的水平，真的令人汗颜。

要说反思，真正值得反思的问题是，自流注学传出之后，在明知不知其然及所以然的情况下，
强不知以为知，望文臆解，头头是道，自以为高明。实际上，不是在瞎吹，就是在瞎批。到
了近现代，有人以实验数据证明流注用之于临床的疗效是如何如何的好，以错误的理解与使
用方式居然能够取得特别好的疗效，真的让我感到很迷惑，唉，中医这江湖，还真的有些深
不见底。
