= 井荥歌诀六十首

世传《子午流注针经》（简称《针经》）是现传流注学的开山之作，书中所载的《井荥歌诀
六十首》是传世时间最早，传播最广，影响最大的流注学专著。后世所谓的流注学，其概念
就是源出于《针经》，原初专指《井荥歌诀六十首》（简称《歌诀》），到了后世，才被人
引伸，用以泛称一切按时流经注穴的理论。自明之后，为了区别于十二经配十二时之类以支
经映射为基础的流注理论，《井荥歌诀六十首》因以干经映射为演绎的基础，故被流注家别
称之为子午流注纳甲法，简称为纳甲法、纳干法。

== 怎样地构建气血之行的法象模型

=== 怎样构建十二经应时依次出入之序

在六十首中，干支分野各为一周天为基准，则始于甲卯，终于癸寅。再以干经定式依次适配
于十二宫，形成甲胆经在卯，乙肝经在辰，丙小肠在巳，丁心经在午，戊胃经在未，己脾经
在申，庚大肠在酉，辛肺经在戍，壬膀胱在亥，癸肾经在寅，这样便形成了壬亥、癸寅之间
子、丑两宫无所配的断层，倘若任之缺如，气血岂不断续而行了？如何说得过去！可又该怎
样地定性子、丑两宫的干经属性呢？

且经脉定性而言，为了避免与十干日所主经脉之间的重复，唯一性的解决方案就是配之以三
焦、包络。倘以十干经阴阳相及的序列规律，壬膀胱在亥为阳经，癸肾经在寅为阴经，那么，
子宫当配以阴经，故以包络主之；丑宫当配以阳经，故以三焦主之。难题出在此两经宫当配
以怎样的天干上。倘若略过不配，则与十干日中干经宫对应体例不符，失去了前后一致性。
考虑到此两经宫地处壬、癸两干分野之中，勉强可行的只能配之以壬癸。三焦为阳经，故配
之以壬，包络为阴经，故配之以癸。为区别起见，特以壬′、癸′标识之，见下图列示。

井荥歌诀六十首

这里强调一下，在上图中，只是将三焦、包络两经之所主附于两日之间，而决非寄归于两日
之中，这与后世所谓“三焦亦向壬中寄，包络同归入癸方”在语义是不同的，切不可混淆，
否则，是要出问题的！

=== 怎样构建阴阳相及、气血并流模型

依据十二经天人映射模型，每干经各序其位，彼此间是相对独立的，可《内经》却认为，经
藏气血之行是阴与阳相及，气与血并流的。既曰阴与阳相及，这就意味着表里经是交贯而行
的；既曰气与血并流，这就意味着气与血也是交贯而行的。那么，六十首又是如何处理这些
问题的呢？很显然，现传《歌诀》中所载的六十首并没有体现出表与里、气与血交贯而行的
特点，倘想译解六十首的原始思路，仅凭现存的文献，那就只能从贾氏所谓六十首法原有两
种的说法谈起了。

所谓《井荥歌诀六十首》，即依据十二经五输核计为六十穴，各撰歌诀一首以明其所治，合
计为六十首而得名。一般人论及六十首，就是专指现传《井荥歌诀六十首》所载内容，不疑
有他的，但按《针经》的转述，贾氏应该是现传六十首法的传出者及其最早的研习者，而贾
氏却认为六十首法原有两种，即有外行脉经六十首与内行血经六十首，后者因故失传了。由
此看来，六十首法传至贾氏时，原始文献已经散佚不全了，贾氏很可能是最后一位见过残存
原始文献的人，尽管所见的原始文献并不完整。因此，贾氏关于六十首法原有两种的说法，
是我们了解《井荥歌诀六十首》原貌的唯一线索，弥足珍贵。

贾氏云：凡六十首者，原有二种也，有外行脉经六十首，又有内行血经六十首，此法微妙，
古圣人隐之，恐世人晓会，只载一说，今世不传。愚自少岁，索隐井荥之法，始可著题。或
曰：因何名曰六十首也？答曰：谓气血一昼夜过六十俞穴也，各分头首，十日一终，运行十
干，皆以五行元建日时为头是也。 ——摘自《针经·三阳三阴流注总说》

贾氏云︰阳日气先脉外，血后脉内；阴日血先脉外，气后脉内。交贯而行于五脏五腑之中，
各注井荥俞经合五穴，共五十穴。惟三焦受十经血气，次传包络，又各注五穴，通前十二经，
共六十穴，才合得十六难内六十首也。越人言：三部九候，各有头首也。及《素问》言六十
首，今世不传。既言不传，其文不载六十首字也，故圣人留此六十首法，令后人穿凿也。余
以所过为原六穴，即便是阴阳二气出入门户也。则阳脉出行二十五度，阴脉入行二十五度，
则皆会此六穴中出入也。其五脏五腑收血化精合处，便是逐经原气也。其余精者，助其三焦，
受十经精气，则以养心包络，始十二经血气遍行也。 ——摘自《流注指微针赋》“详夫阴日
血引，值阳气流”条下注

《素》、《难》之六十首，并构建了“气血一昼夜过六十俞穴”，即后世所谓的养子法，以
附会解释之。然而，《素》、《难》六十首法虽已失传，既以三部九候立论，必是脉学无疑，
这与现传六十首法所论相去甚远，当属于不同的学术领域，因此，六十首法源出于《素》、
《难》六十首的说法，难以成立；至于贾氏所提出的“气血一昼夜过六十俞穴”法，与《井
荥歌诀六十首》所列的流注体例同样地格格不入，只能视为贾氏的猜想之作。依据贾氏的陈
述，我们可以得出这样的结论，六十首法传至贾氏时，不但原有两种已经失传其一，甚至就
连六十首法的立法原理也无从知晓了。事过境迁，不知凡几，到了今天，再来谈论六十首法
的演绎原理，并试图恢复内外六十首全貌，是不是一切都太迟了，只能是徒劳无望了呢？那
就言之过早了！

倘想恢复内行六十首，首先要搞清楚该六十首的大致轮廓。原始文献既云失传，自然难以查
考了。好在贾氏的论述尚在，为我们提供了难得的线索。从六十首原有两种，一曰外行脉经
六十首，二曰内行血经六十首。首先，既同曰六十首，在论述体例上，失传的内行六十首应
该与世传的外行六十首相仿佛，因此，真正的问题在于内行六十首实际的流注体例是怎样的，
它与外行六十首之间的相互定位是怎样的？且从命名差异上看，一曰外行脉经，二曰内行血
经，参考贾氏的说法，“阳日气先脉外，血后脉内；阴日血先脉外，气后脉内。交贯而行于
五脏五腑之中，各注井荥俞经合五穴，共五十穴。惟三焦受十经血气，次传包络，又各注五
穴，通前十二经，共六十穴”，以及世传外行脉经六十首的流注体系，阳经主气行，阴经主
血行，所谓“阳日气先脉外”、“阴日血先脉外”，实际上指的就是阳日阳时气行阳经，阴
日阴时血行阴经这一部分。以此类推，所谓内行血经六十首，无疑是指“阳日……血后脉内；
阴日……气后脉内”这一部分，也就是阳日阴时血行阴经，阴日阳时气行阳经的流注法则。
至于两者流经注穴的基本体例，如依贾氏所云，“交贯而行于五脏五腑之中，各注井荥俞经
合五穴，共五十穴。惟三焦受十经血气，次传包络，又各注五穴，通前十二经，共六十穴”，
完全是类通的。两者珠连壁合，才能共同构成六十首法的全貌。

外行脉经六十首：阳日气先脉外，阴日血先脉外 >>> 阳日阳时气行于阳经，阴日阴时血行
于阴经。

内行血经六十首：阳日血后脉内，阴日气后脉内 >>> 阳日阴时血行于阴经，阴日阳时气行
于阳经。

再看现传《井荥歌诀六十首》所载的六十首内容，仅论阳日阳时行阳经，阴日阴时行阴经的
流注法则，却没有论及阳日阴时、阴日阳时的流经注穴法则，傻想一下，昼夜往来必以十二
时，气血往来必以十二经，怎么会阳日气血仅行于阳时阳经，阴日仅行于阴时阴经呢？这明
显是有问题的，因此，六十首法原有两种，今失传其一，此言诚然。

通过以上分析，六十首解决阴阳相及、气血并流问题的基本思路是，阳经以气论，阴经以血
论，具体地说，阳日阳时气先脉外行于阳经，阴时血后脉内行于阴经；阴日阴时血先脉外行
于阴经，阳时气后脉内行于阳经，交贯而行于十二经五输之中。

=== 怎样构建经藏气血系统的法象模型

那么，内外行六十首又是如何演绎而成的呢？依据中医的基本思路，这无疑是天人相参而来
的，因此，天人如何相参是解决问题的关键。很显然，现传的文献谁也没有说清楚这一问题，
而要逆向还原六十首的天人真相，那最起码得有较完整的原始数据。依贾氏的说法，外行六
十首即为现传的六十首，这部分是完整的，而内行六十首却因故失传，那么，是否果如贾氏
所说，“只载一说，今世不传”，不曾留下一丝可资深入探索的任何线索呢？那就未必了。
古有所谓天不亡绝世之学，辗转探索多年，皇天不负有心人，终于在原穴法中找到了该六十
首的残存文献，从而为还原内行六十首铺平了道路。

本人在译解原穴法的过程中，无意中发现该法中壬子、癸丑两日之中的时干经演绎体例移植
于六十首，其中，壬子日阳时所主之干经以及癸丑日阴时所主之干经，与现传《井荥歌诀六
十首》中三焦、包络两经所主之时干体例完全相同，由此可以断定，这无疑移植于《井荥歌
诀六十首》所载六十首法。这便涉及到一个非常有趣的问题，那么，壬子日阴时所主之干经
以及癸丑日阳时所主之干经的演绎体例又是从何而来的呢？参考六十首原有两种的说法，唯
一可行的解释只能是源自于内经六十首，这样一来，《井荥歌诀六十首》中三焦、包络两经
在两种六十首法中的时干体例得以残存下来。

有了这残存的文献，那就好说了。在最低的限度上，可以“管窥”一下内行血经六十首，如
果分析得法，假梯上楼，可以进行逆向还原内行六十首，重现六十首法全貌。

首先，既然壬子、癸丑两日移植于六十首，那么，原穴法之于六十首，无疑存在着学术上的
传承关联。且看原穴法，各日阴阳十二时，气血遍行于阴阳十二经，在总体上反映了六十首
的大致全貌。更进一步说，原穴法中的阳日阳时、阴日阴时所主之干经的演绎体例之于外行
六十首，原穴法中的阳日阴时、阴日阳时所主之干经的演绎体例之于内行六十首，彼此之间
理应存在着可转换的对传承应关系，因此，只要我们破译了原穴法在阴阳时中的气血流注法
则，那就可以反向译解六十首了，尤其是内行六十首。

那么，原穴法的演绎法则又是如何形成的呢？暂且撇开经穴体例、五门十变之类所引起的特
殊处理外，仅就其基本的演绎原理而言，原穴法是依据年周日月之行为理论原型演绎而成的，
独特之处就在于将年周日之行的回归点设在寅宫，其中，各日所主之经气血出行的时间法象
于年周日之行，所及之经气血出行的时间则法象于月初望后。六十首同样是依据年周日月之
行为理论原型演绎而成的，只是将年周日之行的回归点设在子宫。至于各日之中的气血运行
法则，则仿照原穴法进行演绎，所得的结果是，各日所主之经的气血运行法则一如现传的外
行六十首，至相及之经在十干日中的流注法则，当然无从较验，真正令人吃惊的是，在三焦
包络两经所主的日时中，其时干体例竟然与原穴法壬子、癸丑两日所载完全一致！或许有会
说，这可能是撞巧吗？当然，撞巧的可能性也不能说一点也没有，只是如此复杂的演绎系统，
其间只要有一丁点儿的差参，都会被无限放大，出现彼此完全一致的可能性是微乎其微的，
几近不存在的。

以原穴法为参照，通过彼此间的较验分析，六十首法的演绎思想也就清晰起来了，即外行六
十首的演绎以年周日之行为法象原型，其要点是各日所主之经的气血出行时间取法于日躔度；
内行六十首的演绎以各月月周月之行为法象原型，其要点是各日相及之经的气血出行时间取
法于月初望后。

外行脉经六十首 >>> 以年周日之行为法象模型 >>> 各日所主之经气血循经注穴的规律

内行血经六十首 >>> 以月周月之行为法象模型 >>> 各日相及之经气血循经注穴的规律

更进一步说，六十首为什么要这样做呢？这当然是受到《内经》的影响。气血之行法象于日
月，这是《内经》的基本观念，但如何法象于日月仍然是一个问题。依据十二经依次出入之
序，参合年周日之行，演绎各日所主之经的出入法度，这是最直观的想法。如以此为基准，
那么，相及之经所能法象的只能是月周月之行了，问题是如何依据月周月之行演绎阴阳相及
之经的出入法度，这显然有些棘手。六十首的创立者之所以会提出这样的解决方案，依我的
猜想，大概是这样想的，这还不简单，月周月相的望朔变化不正好体现了阴阳出入的天然法
度么？朔后，月始明，阳气始行，故相及之经如是阳经，当以此为气血初出之时；望后，月
始晦，阴气始行，故相及之经如是阴经，当以此为气血初出之时。以月相之始明始晦，演绎
相及之阴阳经气血初出之时，这样的构想，说句大实话，决非如我等平庸之辈所能梦见的。
贾氏谓“此法微妙”，诚不我欺也。

那么，为什么将以年周日之行为原型演绎而成的部分称之为外行脉经，以月周月之行为原型
演绎而成的部分称之为内行血经呢？参考“X先脉外”、“X后脉内”之类的说法，所谓外行
脉经、内行血经，无疑是取自气行速，行之于脉外，血行迟，行之于经中之意。再看日月之
行，日行速而月行迟，因此，以年周日之行演绎气之行，将所得的结果称为外行脉经六十首；
以月周月之行演绎血之行，将所得的结果称为内行血经六十首。

当然，这些都我自己想想的，古人究竟是怎么想的，那只有天知道了。

== 怎样地以日月之行演绎气血之行

=== 怎样构建年周日月之行的巡行模型

依据本书的图解论证，经藏气血依次出入之序，本就是建立在营卫协同模型之上的，而在营
卫协同模型中，以水火交为其中轴，因此，倘若立水火交为整个经藏气血系统的核心，那是
最恰当不过的。然而，这些论证都出于本人的孤独发明，古人不会深入到这一层。不过，以
水火交济为万物运化之核心，乃是古以有之的想法，《类经图翼·五行统论》曾就此作出详
细阐释：“然而变虽无穷，总不外乎阴阳，阴阳之用，总不离乎水火，所以天地之间，无往
而非水火之用。欲以一言而蔽五行之理者，曰乾坤付正性于坎离，坎离为乾坤之用耳”，
参考六十首法中，丙日有“火原在子，火入水乡”，壬日有“水原在午，水入火乡，故壬丙
子午相交也”之论，六十首法也是认同这一思想的。水火之正位在十二宫中当为子午，因此，
六十首法立子午为中轴，子宫为回归点的年周日月之行模型为演绎原型，也就在情理之中。
当然，也不排除古人这样做时，并没有想得太多，仅是出于尊重历算惯例而已。

既立子宫为回归点，那么，子月日月交会于丑宫，月始明于子宫，始晦于午宫；丑月日月交
会于子宫，月始明于亥宫，始晦于巳宫；寅月日月交会于亥宫，月始明于戍宫，始晦于辰宫；
卯月日月交会于戍宫，月始明酉子宫，始晦于卯宫；辰月日月交会于酉宫，月始明于申宫，
始晦于寅宫；巳月日月交会于申宫，月始明于未宫，始晦于丑宫；午月日月交会未宫，月始
明于午宫，始晦于子宫；未月日月交会于午宫，月始明于巳宫，始晦于亥宫；申月日月交会
于巳宫，月始明于辰宫，始晦于戍宫；酉月日月交会于辰宫，月始明于卯宫，始晦于酉宫；
戍月日月交会于卯宫，月始明于寅宫，始晦于申宫；亥月日月交会于寅宫，月始明于丑宫，
始晦于未宫，现列图如下：

井荥歌诀六十首

通过分析年周日月之行以子午为中轴，以及“故壬丙子午相交也”的说法，令人想起子午流
注这一提法的其所来自。依据现存文献，这一提法首见于《针经》书名，至于这一提法是閰
明广编《针经》时所自创的，或是其来有自，以前便有的，《针经》并没有说明。尤其是子
午的含义究竟是什么，《针经》也没有作出解释，自徐凤《论子午流注法》中提出“何以子
午言之？曰：子时一刻，乃一阳之生；至午时一刻，乃一阴之生，故以子午分之而得乎中
也”后，信从者甚多，成为通用的解释。然而，徐氏所论，不过是汉易十二辟卦之类的滥觞，
与六十首的演绎原理了不相涉，谈不上有什么切实的意义。就《针经》所载内容上看，最直
观的解释就是“壬丙子午相交也”，取意于造化藉乎水火，论其要在子午。倘若取意于日月
之行的法象模型，联系到原穴法与六十首不同，立寅申为中轴，那么，取名为子午流注，就
有了与原穴法相区隔之意，非精于演绎者不能为之了。从《针论》所述上看，贾氏、何若愚、
閰明文等辈任谁都没有这样的水平，子午流注的说法只能是古人传承下来的。

=== 怎样设定经藏气血运行的法象周期

日月之行只能以年周，因为这是无法更改的，那么，如何设定气血之行的法象周期呢？六十
首沿用约定俗成的做法，以十干日为经藏气血运行的总体周期。因此，以年周日月之行为原
型演绎十干日经藏气血之行，这便是六十首法最基本的演绎思路。

=== 怎样演绎各日时中的气血流注规律

倘若以年周日月之行为原型演绎十干日经藏气血之行，这就意味着经藏气血历行十干日相当
于日月历行十二月，核计每一干日被视为类同于一月之数。如此，经藏气血在各干日中的流
注法则可以通过模拟年周日月之行在相应月分中的运行法则得来。具体地说，以十二经之于
十二宫的映射模型为基础，各日所主之经气血初出之时可以依据所在之宫的日月躔度而定，
至于相及之经气血初出之时，则可依据月相之始明始晦而定。所主相及之经气血初出之时既
定之后，各按阴阳干经依次相生之法，出溜注行入之序，依时流注各干经所主之五输完毕，
如为阴经以血纳包络论，如为阳经以气纳三焦论，如是一日十二时之中，气血遍行于阴阳十
二经一周于身。演绎总纲如是，但有三点尚须进一步说明。

==== 五门十变，引气血出行

在六十首中，提出了诸如“甲与己合，胆引气行”、“乙与庚合，肝引血行”之类的经藏气
血引行法则，无疑是受《难经·六十三难》中“十变言，五脏六腑荣合，皆以井为始”影响
之下的产物。所谓十变及其五脏六腑荣合，就是指甲胆与己脾、乙肝与庚大肠、丙小肠与辛
肺、丁心与壬膀胱、戊胃与癸肾合等之间刚柔相成之事。然而，天干以十计，经脉却有十二，
如依五门十变，气血引行的法则，必然会遭遇到三焦、包络二经无所合的尴尬现象，怎么办
呢？六十首的做法是，将此两经作另案处理，以“三焦包络相表里”为说，将两经自相配合。
当然，这种两经相表里而自相配合的做法，与“甲与己合”、“乙与庚合”之类相去甚远，
只能算是不得已之下的变通之法、权宜之计吧。

==== 原穴体例及其所主之时

在演绎时，阴阳经气血流注，各按干经依次相生之序，交贯而行五经五输。依此流注体例，
阴经仅以五输立论，当然不会有什么问题，但阳经尚有原穴，该如何处理呢？倘若如五输般
独立开穴，那整个演绎系统就乱了套，怎么办呢？六十首的做法是将阳经原穴并入开俞穴之
时，这很可能是受《难经》以俞为原的影响。至于“木原在寅”、“火原在子”之类的说辞，
恕我寡陋，虽阅遍历数诸书，却始终找不到相应的理论依据。依我的猜想，也许其中并没有
太深奥的想法，很可能就是将原穴定时于开俞穴之时，如甲日开俞穴于寅时，丙日开俞穴于
子时，故有“木原在寅”、“火原在子”之类的说法。

==== 天干重见纳入三焦包络

按照六十首的演绎体例，阴阳干合阴阳时，一一对应，各行六步，到了末支时，必然出现尾
干与初干相重复的现象，即古人所谓天干重见，又该如何处理呢？六十首的做法是，凡遇天
干重见，以气血纳入三焦包络两经处理。

== 十干日阴阳经应时流注的规律

依据贾氏六十首原有两种，今失传其一的说法，在原初，两种六十首很可能是分开列述的，
这是自有他的道理在。本文则主张将两者合在一起，以先论外行六十首，次论内行六十首之
序，列述于各日之中，以便于逐日相互较验，似乎更好些。在现传六十首中，干支时并在一
起，其形式与甲子时相仿佛，从而造成了诸多不必要的误解。因此，本文一改旧例，将干支
时分开纪理，以十二时纪时，以天干定各时所主的经脉。

甲日 甲胆经居于卯宫。卯月日月交会于戍宫，月始明于酉，始晦于卯。所主之经为甲胆经，
故甲与己合，胆经引气出行于戍时；所及之经为乙肝经，属阴经，法象于月始晦，故乙与庚
合，乙肝经引血出行于卯时。

戍时 甲胆经气出行，故配以胆经井穴窍阴

子时 丙小肠为所溜，故配以小肠荥穴前谷。

寅时 戊胃经为所注，故配以胃经俞穴陷谷。

            并过胆经原穴丘墟。胆为甲木，故曰木原在寅

辰时 庚大肠为所行，故配以大肠经穴阳溪。

午时 壬膀胱为所入，故配以膀胱合穴委中。

申时 甲干重见，气纳三焦。

 

卯时 乙肝经血出行，故配以肝经井穴大敦。

巳时 丁心经为所溜，故配以心经荥穴少府。

未时 戊脾经为所注，故配以脾经俞穴太白。

酉时 辛肺经为所行，故配以肺经经穴经渠。

亥时 癸肾经为所合，故配以肾经合穴阴谷。

丑时 乙干重见，血纳包络。

 

乙日 乙肝经居于辰宫。辰月日月交会于酉宫，月始明于申，始晦于寅。所主之经为乙肝经，
故乙与庚合，肝经引血引出于酉时；所及之经为甲胆经，属阳经，法象于月始明，故甲与己
合，胆经引气出行于申时。//卯酉，相切之意？

      酉时 乙肝经血出行，故配以肝经井穴大敦。

          亥时 丁心经为所溜，故配以心经荥穴少府。

          丑时 己脾经为所注，故配以脾经俞穴太白。

          卯时 辛肺经为所行，故配以肺经经穴经渠。

          巳时 癸肾经为所合，故配以肾经合穴阴谷。

未时 乙干重见，血纳包络。

 

      申时 甲胆经气出行，故配以胆经井穴窍阴。

戍时 丙小肠为所溜，故配以小肠荥穴前谷。

      子时 戊胃经为所注，故配以胃经俞穴陷谷。

并过胆经原穴丘墟。胆为甲木，故木原在子。

          寅时 庚大肠为所经，故配以大肠经穴阳溪。

          辰时 壬膀胱为所合，故配以膀胱合穴委中。

          午时 甲干重见，气纳三焦。

 

丙日 丙小肠居于巳宫。巳月日月交会于申宫，月始明于未宫，始晦于丑宫。所主之经为丙
小肠经，故丙与辛合，小肠经引气出行于申时；所及之经为丁心经，属阴经，法象于月始晦，
故丁与壬合，丁心经引血出行于丑时。

      申时 丙小肠气出行，故配以小肠井穴少泽。

      戍时 戊胃经为所溜，故配以胃经荥穴内庭。

      子时 庚大肠为所注，故配以大肠俞穴三间。

            并过小肠原穴腕骨。小肠为火，故火原在子。

      寅时 壬膀胱为所经，故配以膀胱经穴昆仑。

      辰时 甲胆经为所入，故配以胆经合穴阳陵泉。

      午时 丙干重见，气纳三焦。

 

      丑时 丁心经血出行，故配以心经井穴少冲。

      卯时 己脾经为所溜，故配以脾经荥穴大都。

      巳时 辛肺经为所注，故配以肺经俞穴太渊。

      未时 癸肾经为所经，故配以肾经经穴复溜。

      酉时 乙肝经为所入，故配以肝经合穴曲泉。

      亥时 丁干重见，血纳包络。

 

丁日 丁心经居于午宫。午月日月交会未宫，月始明于午宫，始晦于子宫。所主之经为丁心
经，故丁与壬合，心经引血引出于未时；所及之经为丙小肠经，属阳经，法象于月始明，故
丙与辛合，小肠经引气出行于午时。

      未时 丁心经血出行，故配以心经井穴少冲。

      酉时 己脾经为所溜，故配以脾经荥穴大都。

      亥时 辛肺经为所注，故配以肺经俞穴太渊。

      丑时 癸肾经为所经，故配以肾经经穴复溜。

      卯时 乙肝经为所入，故配以肝经合穴曲泉。

      巳时 丁干重见，血纳包络。

 

      午时 丙小肠气出行，故配以小肠井穴少泽。

      申时 戊胃经为所溜，故配以胃经荥穴内庭。

      戍时 庚大肠为所注，故配以大肠俞穴三间。

            并过小肠原穴腕骨。小肠为火，故火原在戍。

      子时 壬膀胱为所经，故配以膀胱经穴昆仑。

      寅时 甲胆经为所入，故配以胆经合穴阳陵泉。

      辰时 丙干重见，气纳三焦。

 

戊日 戊胃经居于未宫。未月日月交会于午宫，月始明于巳宫，始晦于亥宫。所主之经为戊
胃经，故戊与癸合，戊胃经引气出行于午时；所及之经为己脾经，属阴经，法象于月始晦，
故己与甲合，己脾经引血出行于亥时。

      午时 戊胃经气出行，故配以胃经井穴厉兑。

      申时 庚大肠为所溜，故配以大肠荥穴二间。

      戍时 壬膀胱为所注，故配以膀胱俞穴束骨。

            并过胃经原穴冲阳。胃经为土，故土原在戍。

      子时 甲胆经为所经，故配以胆经经穴阳辅。

      寅时 丙小肠为所入，故配以小肠合穴小海。

      辰时 戊干重见，气纳三焦。

 

      亥时 己脾经血出行，故配以脾经井穴隐白。

      丑时 辛肺经为所溜，故配以肺经荥穴鱼际。

      卯时 癸肾经为所注，故配以肾经俞穴太溪。

      巳时 乙肝经为所经，故配以肝经经穴中封。

      未时 丁心经为所入，故配以心经合穴少海。

      酉时 己干重见，血纳包络。

 

己日 己脾经居于申宫。申月日月交会于巳宫，月始明于辰宫，始晦于戍宫。所主之经为己
脾经，故己与甲合，己脾经引血引出于巳时；所及之经为戊胃经，属阳经，法象于月始明，
故戊与癸合，戊胃经引气出行于辰时。

      巳时 己脾经血出行，故配以脾经井穴隐白。

      未时 辛肺经为所溜，故配以肺经荥穴鱼际。

      酉时 癸肾经为所注，故配以肾经俞穴太溪。

      亥时 乙肝经为所经，故配以肝经经穴中封。

      丑时 丁心经为所入，故配以心经合穴少海。

      卯时 己干重见，血纳包络。

 

      辰时 戊胃经气出行，故配以胃经井穴厉兑。

      午时 庚大肠为所溜，故配以大肠荥穴二间。

      申时 壬膀胱为所注，故配以膀胱俞穴束骨。

             并过胃经原穴冲阳。胃经为土，故土原在申。

      戍时 甲胆经为所经，故配以胆经经穴阳辅。

      子时 丙小肠为所入，故配以小肠合穴小海。

      寅时 戊干重见，气纳三焦。

 

庚日 庚大肠居于酉宫。酉月日月交会于辰宫，月始明于卯宫，始晦于酉宫。所主之经为庚
大肠，故庚与乙合，庚大肠引气出行于辰时；所及之经为辛肺经，属阴经，法象于月始晦，
故辛与丙合，辛肺经引血出行于酉时。

辰时 庚大肠气出行，故配以大肠井穴商阳。

午时 壬膀胱为所溜，故配以膀胱荥穴通谷。

申时 甲胆经为所注，故配以胆经俞穴临泣。

       并过大肠原穴合谷。大肠为金，故金原在申。

戍时 丙小肠为所经，故配以小肠经穴阳谷。

子时 戊胃经为所入，故配以胃经合穴三里。

寅时 庚干重见，气纳三焦。

 

酉时 辛肺经血出行，故配以肺经井穴少商。

亥时 癸肾经为所溜，故配以肾经荥穴然谷。

丑时 乙肝经为所注，故配以肝经俞穴太冲。

卯时 丁心经为所经，故配以心经经穴灵道。

巳时 己脾经为所入，故配以脾经合穴阴陵泉。

未时 辛干重见，血纳包络。

 

辛日 辛肺经居于戍宫。戍月日月交会于卯宫，月始明于寅宫，始晦于申宫。所主之经为辛
肺经，故辛与丙合，辛肺经引血出行于卯时；所及之经为大肠经，属阳经，法象于月始明，
故庚与乙合，庚大肠经引气出行于寅时。

      卯时 辛肺经血出行，故配以肺经井穴少商。

      巳时 癸肾经为所溜，故配以肾经荥穴然谷。

未时 乙肝经为所注，故配以肝经俞穴太冲。

酉时 丁心经为所经，故配以心经经穴灵道。

亥时 己脾经为所入，故配以脾经合穴阴陵泉。

丑时 辛干重见，血纳包络。

 

寅时 庚大肠气出行，故配以大肠井穴商阳。

辰时 壬膀胱为所溜，故配以膀胱荥穴通谷。

午时 甲胆经为所注，故配以胆经俞穴临泣。

       并过大肠原穴合谷。大肠为金，故金原在午。

申时 丙小肠为所经，故配以小肠经穴阳谷。

戍时 戊胃经为所入，故配以胃经合穴三里。

子时 庚干重见，气纳三焦。

 

壬日 壬膀胱居于亥宫。亥月日月交会于寅宫，月始明于丑宫，始晦于未宫。所主之经为壬
膀胱经，故壬与丁合，壬膀胱经引气出行于寅时；所及之经为癸肾经，属阴经，法象于月始
晦，故癸与戊合，癸肾经引血出行于未时。

      寅时 壬膀胱气出行，故配以膀胱井穴至阴。

          辰时 甲胆经为所溜，故配以胆经荥穴侠溪。

          午时 丙小肠为所注，故配以小肠俞穴后溪。

                 并过膀胱经原穴京骨。膀胱为水，故水原在午。

          申时 戊胃经为所经，故配以胃经经穴解溪。

          戍时 庚大肠为所入，故配以大肠合穴曲池。

          子时 壬干重见，气纳三焦。

 

          未时 癸肾经血出行，故配以肾经井穴涌泉。

          酉时 乙肝经为所溜，故配以肝经荥穴神门。

          亥时 丁心经为所注，故配以心经俞穴行间。

          丑时 己脾经为所经，故配以脾经经穴商丘。

          卯时 辛肺经为所入，故配以肺经合穴尺泽。

          巳时 癸干重见，血纳包络。

 

三焦、包络两经因在于不在干经范式之内，这就产生了三方面的问题。首先，且就十干日而
言，此两经本不属于十干日之内，而干经与十二宫相适配的结果，却又被定位于壬日、癸日
之间，该怎么办呢？六十首以另案处理，采用了附注的方式将此两经附于壬日、癸日之间。
又，三焦配以壬′，包络配以癸′，与天干壬癸实际分野之序不合，故在具体列述时，将
壬′三焦附于壬日之后，癸′包络附于癸日之前。但这样做，容易引起不知缘由的人误会，
因此，本篇改回实际演绎之序。其次，在演绎时，倘若仍采用如同于十干日中的时干经演绎
体例，必然出现壬′三焦与壬日、癸′包络与癸日中各时所主之干经雷同的现象，导致所主
之干经重复流注，这是不能被允许的。迫不得已之下，只能以自注本经五输处理。再者，既
以自注本经五输，各时所主之干也就失去了切实的意义，可是，倘若因之弃而不论，又与十
干日演绎体例不协调，怎么办？为虚应体例，六十首仍按贯例配以各时所主之干。为区别起
见，本篇将虚应之干以′标识之。五输既注之后，虚应之干重见，六十首以气入行、血入行
处理。

特别强调一下，此二经所主二十四时中的各时及其所主之干与原穴法壬子、癸丑两日是完全
一致的，藉此可以证明本篇所主张的还原两种六十首的思路是完全可行的。

 

包络 癸′包络居于子宫。子月日月交会于丑宫，月始明于子宫，始晦于午宫。所主之经为
癸′包络，故与三焦合，癸′包络引血出行于丑时；所及之经为壬′三焦，属阳经，法象于
月始明，故与包络合，壬′三焦引气出行于子时。

丑时 癸′为所出，故配以包络井穴中冲。

      卯时 乙′为所溜，故配以包络荥穴劳宫。

      巳时 丁′为所注，故配以包络俞穴太溪。

      未时 己′为所经，故配以包络经穴间使。

      酉时 辛′为所入，故配以包络合穴曲泽。

      亥时 癸′干重见，血入行（为《井荥歌诀六十首》所缺，今仿三焦经补入）。

 

子时 壬′为所出，故配以三焦井穴关冲。

      寅时 甲′为所溜，故配以三焦荥穴液门。

      辰时 丙′为所注，故配以三焦俞穴中渚。

并过三焦原穴阳池，故三焦原在辰。

      午时 戊′为所经，故配以三焦经穴支沟。

      申时 庚′为所入，故配以三焦合穴天井。

      戍时 壬′干重见，气入行。

 

三焦 壬′三焦居于丑宫。丑月日月交会于子宫，月始明于亥宫，始晦于巳宫。所主之经为
壬′三焦经，故与包络合，壬′三焦经引气出行于子时；所及之继癸′包络经，属阴经，法
象于月始晦，故与三焦合，癸′包络引血出行于巳时。

子时 壬′为所出，故配以三焦井穴关冲。

      寅时 甲′为所溜，故配以三焦荥穴液门。

      辰时 丙′为所注，故配以三焦俞穴中渚。

并过三焦原穴阳池，故三焦原在辰。

      午时 戊′为所经，故配以三焦经穴支沟。

      申时 庚′为所入，故配以三焦合穴天井。

      戍时 壬′干重见，气入行。

 

巳时 癸′为所出，故配以包络井穴中冲。

      未时 乙′为所溜，故配以包络荥穴劳宫。

      酉时 丁′为所注，故配以包络俞穴太溪。

      亥时 己′为所经，故配以包络经穴间使。

      丑时 辛′为所入，故配以包络合穴曲泽。

      卯时 癸′干重见，血入行。

 

癸日 癸肾经居于寅宫。寅月日月交会于亥宫，月始明于戍宫，始晦于辰宫；所主之经为癸
肾经，故癸与戊合，癸肾经引血出行于亥时；所及之经为膀胱经，属阳经，法象于月始明，
故壬与丁合，壬膀胱经引气出行于戍时。

          亥时 癸肾经血出行，故配以肾经井穴涌泉。

          丑时 乙肝经为所溜，故配以肝经荥穴神门。

          卯时 丁心经为所注，故配以心经俞穴行间。

          巳时 己脾经为所经，故配以脾经经穴商丘。

          未时 辛肺经为所入，故配以肺经合穴尺泽。

          酉时 癸干重见，血纳包络。

 

      戍时 壬膀胱气出行，故配以膀胱井穴至阴。

          子时 甲胆经为所溜，故配以胆经荥穴侠溪。

          寅时 丙小肠为所注，故配以小肠俞穴后溪。

                 并过膀胱经原穴京骨。膀胱为水，故水原在寅。

          辰时 戊胃经为所经，故配以胃经经穴解溪。

          午时 庚大肠为所入，故配以大肠合穴曲池。

          申时 壬干重见，气纳三焦。

 

    内外六十法的演绎过程就谈到这里了。今依据内外六十首在各日时中流注五输穴的法则，
    绘制详解图示如下：

井荥歌诀六十首

== 三焦包络引起的问题及其解决方案

=== 两经流注体例的解释方案

我们先看一下十二经气血流注体例的宏观特征，在十干日中，气血交贯而行，各行五经五输
之后，天干重见，气血纳入三焦包络，到了三焦包络所主之日时，则各循本经依时流注两经
五输之后，气血入行整个系统，这在系统结构上便形成了以三焦包络为出入核心的十二经流
注循环。这是系统特征之所以形成，并非出自于经藏气血系统本身的运行法则，而是演绎的
理论基础出现了问题，即干经模式之于十二宫分野难以适配，不得已而采取的解决方案。三
焦包络本不在干经范式之内，属于局外者，却最终成了解决局中问题的关键核心，也因为如
此，才使得三焦包络两经的流注体例在整个流注系统中与众不同，格外醒目，这就需要提出
更进一步的解释，从而使得两经的流注体例合理化。这样的做法，不客气地说，这是为了遮
人耳目，因此，无论怎么贴切，终究只是附会之说。后者学者哪知个中曲折，看似在理，便
竞相附和，那就徒为识者所笑了。

==== 三焦之于原气

从《针经》的相关论述上看，《歌诀》应该传自六十首原始文献，因此，《歌诀》中提出的
解释体现了创立者的基本思路。在《歌诀》中，特将气纳三焦体例谓之还原化本（出现在甲
壬两日之尾）。还原之原，当为生气之原的意思；化本之本，当为十二经之根本的意思。在
三焦所主之日时，又特意申说，“三焦者，是十二经之根本，生气之原，主宣通荣卫，经历
五脏六腑”，前后呼应，看似浑然一体。从而所持的论据上看，这样的解释方案，无疑是受
到《难经》三焦原气说的影响而提出的。然而，在六十首中，三焦之与包络，焦不离孟，孟
不离焦，解释仅以三焦立论，而罔及包络，这显然有些问题，因此，贾氏又作进一步的伸说，
“其五脏五腑收血化精合处，便是逐经原气也。其余精者，助其三焦，受十经精气，则以养
心包络，始十二经血气遍行也”（见何氏针赋“详夫阴日血引，值阳气流”条下注引），把
包络也概括进来，当然，这种说法与《难经》三焦原气说是有出入的。

==== 气血之父母说

《针经·三焦包络二经流注说》中说，“十经血气，皆出于井，入于合，各注井荥俞经合无
休矣。或问：脉有十二经，又因何只言十经，其余二经不言者，何故？答曰：其二经者，三
焦是阳气之父，心包是阴血之母也。此二经尊重，不系五行所摄，主受纳十经血气养育，故
只言十经。阴阳二脉逐日各注井荥俞经合五时辰毕，则归其本”。以三焦包络为气血之父母，
这一说法无疑出自阎明广，以前是没有的。阎明广之所以要另立新说，很可能是因为三焦原
气说只论三焦，不论包络，无法完整解释两经的流注体例。大概也因为如此，自气血之父母
说传世之后，广受流注学界的一致赞同，成为后世流注学广为引用的标准说辞。

=== 两经流注体例的修改方案

到了明代，徐凤认为天干重见，气血纳入三焦包络的流注体例存在着“还元化本之理，气并
所纳之穴，俱隐而不具”，也就是只言气血所纳之经，却没说所纳之穴的问题，擅自取消两
经自注本经五输体例，将两经之五输作为气血所纳之穴分配到各日还原化本之时，两经之俞
原寄宿到壬癸两日之中，此即所谓“此二经虽寄于壬癸，亦分派于十干”。这一修改方案影
响极大，成为明清流注学的主流思想。其间，有人提出将两经之俞原寄宿到壬癸两日之中的
做法并不妥当，主张应寄宿到丙丁两日中去，从而触发了三焦包络当寄于何日的争论。

在六十首天人模型中，三焦包络两经定位于壬亥、癸寅两宫之间的子丑两宫，各有所主，是
取消不得的，一取消，便会出现子丑两宫的演绎断层，这如何可以？因此，徐凤这样做，无
疑是在添乱，断然不可的。既然徐凤的做法无法成立，所谓两经寄宿日时的问题及其所引发
的争论也就失去了意义与价值。

==== 三焦亦向壬中寄，包络同归入癸方

徐凤将两经之俞原寄宿到壬癸两日的做法概括为“三焦亦向壬中寄，包络同归入癸方”。为
什么要这样寄，徐凤并没有进一步说明，依我的猜想，很可能是想当然。两经之所主位于壬
癸二日之间，而后人又常将此误解为壬日壬子时之与癸日癸亥时之间，因此，若论两经俞原
的寄宿，不暇多想，就很自然地想到寄宿于壬癸两日之中。

==== 三焦阳腑须归丙，包络从阴丁火旁

张景岳对此不以为然，他在《类经图翼·十二经纳甲歌》中说，“旧云：三焦亦向壬中寄，
包络同归入癸方。虽三焦为决渎，犹可言壬；而包络附心主，安得云癸？且二脏表里，皆相
火也，今改正之”，改为“三焦阳腑须归丙，包络从阴丁火旁”。这种观点，相信的人不少，
如陈修园、李学川等，李学川甚至修改了徐氏《定穴诀》，将两经之俞原改寄到丙丁两日中。
不过，只须细想一下，这样的质疑恐怕是站不住脚的，因为反过来也可以这样说，虽包络附
心主，犹可言丁；而三焦为决渎，安得云丙？且二脏表里，皆相火也，丙丁乃君火之位，相
凌君位，岂有此理？！搞笑一下，嘿嘿。

== 甲子数、无开穴以及补穴法

自《歌诀》传世以来，最致命的误解恐怕就是将六十首中的干支时列述体例误解为甲子数了。

所谓甲子数，就是十干与十二支循序依次相配，必经六十配次，复归于甲与子相合，故又被
称之为六十甲子数。在古代，甲子数常被用来纪时，并成为古代最通用的纪时方式。在《歌
诀》中，各日之中，以某干某支时，某经为某输为论述格式。其中，某干某支时这一纪述方
式，如甲戍时、乙丑时等，一眼看去，与甲子时的表述方式完全一样，因此，自《歌诀》传
行于后世之后，流注学家一直将某干某支时理解为甲子时，深信不疑。据《针经·三阴三阳
流注总论》中的转说，“贾氏云……或曰：因何名曰六十首也？答曰：谓气血一昼夜过六十
俞穴也，各分头首，十日一终，运行十干，皆以五子元建日时为头是也”，所谓五子元建日
时，就是甲子数的纪时方式，由此可见，贾氏就是将某干某支时理解为甲子时的。自《针经》
之后，“要求日下井荥，用五子建元日时取之”，成了无人质疑的标准范式。到了近代，又
有好事者据此而绘制诸图，依图而立种种演绎之法，天下滔滔，莫不如是。

既然是甲子时，按甲子序列，对《歌诀》中的流注体例进行整理与编排，以便实际运用，这
是很自然的想法。不曾想，无论是《歌诀》所载的六十首法，或是徐凤的修正方案，一经编
排，却是乱象丛生。且以《歌诀》所载为例，十干日及三焦、包络两经之所主，各行六个干
支时，前后总计七十有二，这与甲子时六十数有较大的出入，倘若干支时为甲子时，为何会
出现这么大的出入呢？依《歌诀》行文体例，各日之中所行的六个干支时只能隶属于所在之
日，不可更移的，如按甲子序列一经编排，那原有的隶属序列便荡然无存。更为荒谬的是，
甚至出现了时而开双穴，时而开单穴，时而无开穴的现象，时穴映射错乱不堪。尤其是无开
穴，或称之闭穴现象，这会造成届时无穴可取的尴尬局面。于是，又有好事者，著名如郑魁
山、单玉堂等针家，费尽心思，创建各种增补开穴的方法，以图解决无开穴的问题。

假如干支时确为甲子时的话，那《歌诀》所载的日时经穴序列，名为有序，实为乱序。体现
在临床，岂不是正如《针灸聚英·卷二·子午流注穴开阖》所说，“今人泥其图而不详其说，
妄言今日某日某时其穴开，凡百病皆针灸此开穴；明日某日某时其穴开，凡百病针灸明日开
穴，误人多矣！今去其图，直录其说，使人知某病宜针灸某经某穴，当用某日某时开方针，
如东垣治前阴臊臭，刺肝经行间，用乙丑时矣；又刺少冲，则宜丁未时矣。岂东垣治一病而
有首尾越四十三时刺两穴哉？”。

想当初，我就曾为依甲子时编排所引起的种种问题困惑不已，肯定是哪里出问题了。彷徨无
计之下，才回想起贾氏、阎明广、徐凤等，可以说史上一切流注学家，居然没一个是懂《歌
诀》演绎原理的，因此，要想搞清楚某干某支时，某经为某输的原义，那就得破译《歌诀》
的演绎原理。辗转多年，摸索出演绎模型之后，才领悟到干支时是干支分开纪理的，某支时
表示时辰，某干表示该时所主之干，并以此作为演绎该时所主之经的依据，并不是什么甲子
时。例如甲戍时，戍时表示所在之时，甲表示戍时所主之干，甲为胆，故戍时气行胆经。只
是没有旁证，心中没底，后来偶遇原穴法所传图表，发现该图表就是独以十二时来表示所在
之时的，这就从侧面证实了我心中的猜想，心意遂决。为了避免因表示形式类同而混淆为甲
子数，本篇在演绎过程，特以十二时纪时，将各时及其所主之干经分开纪理。

有人会说，假如果真是干支分开纪理的，岂不会造成《歌诀》阳日阴时、阴日阳时，前后通
计七十二时无开穴？无他，这是因六十首原有两种，今失传其一所造成的。本篇既然恢复了
六十首全貌，各日之中，十二时各行十二经穴，森然有序，这样的问题当然也就不复存在了。

== 后世诸家变法之弊

依据《歌诀》所传及其研究心得，后世的流注家创立了两种有别于现传六十首的流注新系统，
即养子法与徐氏法，最终演变成两大流注学派，在流注学传承史上的影响很大。令人尴尬的
是，这两大流注系统都是在“子午流注之法无以考”的形情下创立的。俗话说，不知所以然，
开口动手便错。这些创立者甚至连《歌诀》的演绎原理都没搞清楚，就敢独出己意，另立新
解，着实孟浪了些。所谓的新解，最终也只能是臆解，并没有多少学术价值。

=== 养子法

养子法，全称养子时刻注穴法，为贾氏所创，名称取自何氏《流注指微针赋》中“养子时刻，
注穴必须依”句，经阎明广详为阐释而流传至今。

据《针经》转述，贾氏之所以创作该法，其根本动机就是因六十首原有二种，因故失传其一，
于是，“索隐井荥之法”，以图译解内行血经六十首，恢复六十首的全貌，最终得出的结论
是，“因何名曰六十首也？谓气血一昼夜过六十俞穴也，各分头首，十日一终，运行十干，
皆以五行元建日时为头是也”。其后，《指微针赋》概括为“养子时刻，注穴必须依”，阎
明广又详为注释，“养子时刻注穴者，谓逐时干旺气注脏腑井荥之法也。每一时辰，相生养
子五度，各注井荥俞经合五穴。昼夜十二时，气血行过六十俞穴也。每一穴血气分得一刻六
十分六厘六毫六丝六忽六杪，此是一穴之数也。六十穴共成百刻，要求日下井荥，用五子建
元日时取之。设令甲日甲戌时，胆统气初出窍阴穴为井木，流至小肠为荥火，气过前谷穴注
至胃为俞土，气过陷谷穴又并过本原丘墟穴。但是六腑各有一原穴，则不系属井荥相生之法，
即是阴阳二气出入门户也。行之大肠为经金，气过阳溪穴，所入膀胱为合水，气入委中穴而
终。此是甲戌时木火土金水相生五度一时辰流注五穴毕也。他皆仿此”。至于三焦包络两经，
《三焦心包络二经流注说》也有说明，“此二经亦各注井、荥、俞、经、合五穴，方知十二
经遍行也。三焦经∶关冲(阳井)，液门(荥)，中渚(俞)，阳池(原)，支沟(经)，天井(合)。
每日遇阳干合处，注此六穴。如甲日甲戌时，至甲申时，为阳干合也；心包经∶中冲(阴井)，
劳宫(荥)，大陵(俞)，间使(经)，曲泽(合)。每日遇阴干合处，注此五穴。假令甲日甲戌时，
胆气初出为井，己巳时脾出血为井，阴阳并行。阳日，气先血后，阴日，气后血先。己巳时
至己卯时为阴干合也。余干日辰皆根据此”。

由此可见，所谓养子法，就是以《歌诀》所传六十首为基础，再以各时辰之中相生养子各注
井荥俞经合五穴，演绎而成。想当初，贾氏创立养子法，无非是想译解失传的内行六十首。
那么，贾氏的想法能否成立呢？既云六十首原有两种，可以猜测这两种六十首应该存在着某
种内在的关联。因此，倘要译解内行六十首，那就得首先译解现传六十首的演绎原理。贾氏
连这点都做不到，如何窥得六十首的基本思路，还谈什么译解内行六十首？再者，既分为内
行六十首、外行六十首两种，这说明这两者应该是并列的关系，而非基于的关系。贾氏基于
外行六十首去译解内行六十首，本就犯了方向性的错误。

=== 徐氏法

明代徐凤是流注学史上颇为著名的人物，撰有《针灸大全》一书。在该书中，《论子午流注
之法》、《子午流注逐日按时定穴诀》、《流注图》等图文，针对《歌诀》所传之六十首提
出了修改意见，在后世流注学的发展影响很大，可谓后来者居上，成了明清时期流注学的主
流思想。可惜，名气大，并不意味着道理多，是否改之在理那就另一回事了。

==== 五输穴及其五行属性

徐凤受《难经》中“六十四难”与“六十六难”等的影响，提出各日之中所注的五经五输，
应该按“阴井木而阳井金，阴荥火而阳荥水，阴俞土而阳俞木，阴经金而阳经火，阴合水而
阳合土”的规则，各定其五行属性。至于各经原穴，则应该按“阳经有原，遇俞穴并过之；
阴经无原，以俞穴即代之”的规则处理。从演绎的角度，这样的修改方案，非但没必要，有
画蛇添足之嫌，反而使原有的论述格式，即某干某支时，某经为某输，前后失去了内在的一
致性，给后学者徒增困扰，这又何必呢？

==== 三焦包络的流注法则

改动最大的，当属三焦包络部分。徐凤认为，各日之中，“还元化本之理，气并所纳之穴，
俱隐而不具”，因此，取消三焦包络两经在所主之日自注本经五输体例，依据重见之干的阴
阳属性，分别按我生他、他生我的法则，定位其所纳之穴，“如甲日……重见甲申时，气纳
三焦荥穴，属水，甲属木，是以水生木，谓甲合还元化本。又如乙日……重见乙未时，血纳
包络荥穴，属火，乙属木，是以木生火也。余皆根据此”，将两经之五输依序分配到各日天
干重见之时。至于两经之俞原，则分别寄宿于壬癸两日开俞穴之时，此即所谓“三焦乃阳气
之父，包络乃阴血之母。此二经虽寄于壬癸，亦分派于十干”。 这样改，究竟对不对，前
面已经谈过了。

令人感到疑惑的是，徐凤既然明知“右子午流注之法无以考焉”，无以考知六十首的内在思
路，却还要仅凭一己之见，随臆修改。以一个外行者的目光，去评判异常深刻的内行之事，
所谓修改，只能是篡改，越改越错。
