= 夫妻相合原穴法

所谓夫妻相合原穴法，后简称为原穴法，是指元·王国瑞《扁鹊神应针灸玉龙经》（简称
《玉龙经》）所载《时日配合穴法图》（后简称《穴法图》）中的流经注穴理论，因该法
以各日时中夫妻经原穴配合运用为显著特征，故后人通称之为十二经夫妻相合逐日按时开
原穴法。此法自王国瑞传出之后，似未见有其他针家转述，可见史上流传不广，沿用者不
多。近世，流注学兴起，除少数专业研究者偶或提及，仅作研究参考外，知道此法的人也
极少。

想当初，本人从上针所吴祖德教授那里得闻此法，想一探究竟时，却发现除了那《穴法图》，
几无可资深入的原始文献，竟然是赤条条的，一下子懵了。反复摸索许久，只觉得壬子、癸
丑两日很另类，也有些眼熟，找来《井荥歌诀六十首》，一较验，发现壬子日各阳时所主之
干经与三焦所主之各时天干，癸丑日阴时所主之干经与包络所主之各时天干居然是完全一致
的，心中豁然一亮，难不成原穴法就是从六十首演变而来的？于是，以各日所主之经的原穴
（如甲日甲胆经原穴、乙日乙肝经原穴等）所出之时为依据，与《歌诀》所传各日俞原（如
甲日甲胆经原穴、乙日己脾经俞穴等）所主之时进行较验，发现两者所持的原穴体例虽不相
同，但所主之时却是一样的，这就坐实了心中的猜想，因为在两大各有传承且如此复杂的演
绎巨系统中，出现如此一致的形情，撞巧的概率实在是太低了，唯一可能的解释是，原穴法
是基于六十首发展而来的。

反观天人之际，昼夜之行必以十二时，气血之行必以十二经，因此，若论天人，十二时行十
二经，这无疑是最恰当不过的时经模型。再看《歌诀》所传六十首，阳日仅论六阳时，阴日
仅论六阴时，仅得其半，这显然是有问题的。回想起贾氏曾云六十首原有两种，因故失传其
一，若此话当真，所失传的部分无疑是阳日六阴时、阴日六阳时的流注法则。既云失传，在
现传六十首中是难觅踪影了。再看《穴法图》，各日之中，十二时流注十二经，秩序井然。
假如原穴法果真是从六十首法变化而来的，那么，原穴法中阳日阴时、阴日阳时这一部分无
疑继承于失传的六十首。比照原穴法各日所主之经的原穴开穴之时与六十首中各日俞原开穴
之时相一致的原则，以及所传六十首的流注体例，我们可以依据原穴法中阳日阴时、阴日阳
时的流注法则，逆向还原出失传六十首的大致轮廓。到底对不对，可以通过壬子日六阴时、
癸丑日六阳时所主之时干来较验，若是一致的，那肯定八九不离十。

另一方面，原穴法仅剩《穴法图》，缺乏相关的解释性文献，突兀兀，赤条条的，叫人如何
窥得其门径。倘若原穴法是从六十首变化而来，那贾氏所说的一些论点同样适用于原穴法，
这就为我们深入理解原穴法的立论原理提供了可资借鉴的线索。

本人曾遍检流注学文献，原穴法很可能是唯一完整地保存了流注学思想全貌的流注学文献，
学术价值是可想而知的。可叹世人论及流注学时，只知道《井荥歌诀六十首》如何如何，但
那只是残篇，而保存完整的原穴法反而默默无闻，几成绝响，很无语，也很感慨。唉，在不
识货的人眼里，即便是和氏璧，也不过是块石头罢了，嘿 嘿……

== 怎样地构建气血之行的法象模型

=== 怎样构建十二经应时依次出入之序

初读《玉龙经·流注》时，见《十二经原穴》、《夫妇配合原穴》中将三焦阳池、包络内关
配以戊己，这既与六十首不同，且仅以我之所见，历史上也似乎没有出现过类似的观点，感
到尤不可解。演绎《穴法图》之后，才发现此中的奥妙。

在六十首中，将三焦、包络两经定位于壬膀胱亥宫与癸肾经寅宫之间的子丑两宫，这样做的
缺点也是很明显的。首先，壬膀胱与癸肾经所主之宫悬隔两个宫位，这与前面表里经顺次相
及的列序不相一致，太扎眼了。这还不算，更尴尬的是，三焦、包络两经所主的子丑两宫并
不隶属于壬癸两日，或者说，根本就不隶属于十干日序列之内，而在实际施用中，日期以十
干日为基准，各时辰只能是日中之时，因此，时辰只能依日期而立，日期只能依十干日而立。
由于三焦、包络两之所主并不属于十干日序列之内，从日时演绎的视角，两穴所主之各时各
穴是看不见，摸不着的，因而是不可用的，有跟没有一样，这哪能行？为此，原穴法进行了
改正，将癸肾经的定位前移到子宫，这样便将断层后移至丑寅两宫，仍以三焦、包络两经配
之，从而形成了甲胆经在卯，乙肝经在辰，丙小肠在巳，丁心经在午，戊胃经在未，己脾经
在申，庚大肠在酉，辛肺经在戍，壬膀胱在亥，癸肾经在子，三焦经在丑、包络经在寅的十
二经应时出入之序。

那么，这样改，究竟有什么好处呢？最明显的，消除了壬亥、癸寅之间的悬隔，实现十干之
于十二宫对应模式的前后一致性，更玄妙的是，可以将三焦、包络之所主配之以戊己，从而
解决两经所主之经穴在时日应用上的问题。为了便于说明，特引入帝出章卦序，合以干支，
则震巽为木，主甲乙，居卯辰；离为火，主丙丁，居巳午；坤为土，主戊己，居未申；兑乾
为金，主庚辛，居酉戍；坎为水，主壬癸，居亥子。三焦包络居丑寅两宫，所对应的卦象无
疑是艮。艮亦为土，以天干论之，则为戊己，这就是原穴法为什么要将三焦、包络两经定性
为戊己的由来。依据传统易学，常将艮土寄居中央，以应四时四方。三焦、包络既居于丑寅
艮，可仿照易例，将两经各时所主之经穴分寄于十干日之中，这样，日时应用上的问题也就
给解决了。

夫妻相合原穴法

依据医易演绎模型，将三焦、包络定位到艮卦，这是确然不移的，因此，在干经分野定位上，
原穴法要比六十首法高明很多。只是，古人是不知道这些道理的，如何会想到这样做呢？这
一点也不奇怪，艮居丑寅，位于癸、甲之间，乃是古代历数之学的常识，如二十四山图之类。
原穴法既将断层后移至丑寅，后续的处理都是自然而然的事。由此可以断定，三焦、包络两
经的天干定性及其运用，必曾受到后世历数之学的影响，至少《内》、《难》中是没有这套
东西的。

综上所述，将三焦、包络配以戊己，包涵着极为精妙的理论构思，非知根知底者难以领会，
就凭王国瑞那点水平如何能理解此中的奥妙？据此猜测，《十二经原穴》、《夫妇配合原穴》
及其后的《时日配合穴法图》是王国瑞从其他原始文献中照搬收录的。至于《手指诀》、
《司天诀》两图，包焦居于壬癸之间，这显然是以六十首立论的，图注“须明逆顺”、“要
识迎随”无疑出自《标幽赋》。将此两图附于《时日配合穴法图》章目之下，如同《序》一
样，难逃张冠李戴之嫌，由此可以断定，这是王国瑞自己添进去的，并非出自原穴法原始文
献。

当然，这样做也是有缺点的，那就是与天干分野的实际范围有出入，因为依照天干分野，遍
历十干，当历行365度，一周于天，这也就是六十首将癸定位于寅宫的原由。如依原穴法中
的做法，将癸定位于子宫，遍历十干，仅行304余度，出现60余度的分野断层。没得办法啦，
有所得必有所失，事难两全。

=== 怎样构建阴阳相及、气血并流模型

经演绎发现，在各日之中，所主之经与相及之经分开纪理，各按阴时行阴经，阳时行阳经，
循着干经相生之序，流注各经原穴，天干重见，纳入三焦、包络两经原穴。鉴于原穴法之于
六十首的传承关系，假如贾氏所言不虚，也应适用于原穴法，因此，原穴法中的阴阳相及、
气血并流模型与六十首相仿佛，阳日，所主之经气先脉外，相及之经血后脉内；阴日，所主
之经血先脉外，相及之经气后脉内。气血交贯而行，依次流注五脏五腑原穴完毕，纳入三焦、
包络两经原穴。

=== 怎样构建经藏气血系统的法象模型

各日之中，既将所主、相及之经分开纪理，各按相生之序依次流注各经原穴，整个演绎过程
都是自然而然的，真正的难点在于所主、相及之经气血出行之时是如何确定下来的。其中，
所主之经气血初出之时法象于年周日之行，只要略懂些天文历算，一望即知。至于相及之经
气血初出之时法象于何者演绎而来，我还真的花费了不少心思。后来因研究日月交会法则，
仰观月相变化，才豁然而解，原来这是法象于月相始明始晦的方位而来的。至此，原穴法的
法象原型真相大白，即各日所主之经气血之行法象于年周日之行，相及之经气血之行法象于
月相变化。

== 怎样地以日月之行演绎气血之行

=== 怎样构建年周日月之行的法象原型

本人将原穴法中各日阴阳经的出行时辰进行天学还原之后，所得到的结果的确有些出乎我的
意料，所法象的年周日月之行原型居然是以寅宫为回归点的，寅月日月交会于卯宫，月始明
于寅宫，始晦于申宫；卯月日月交会于寅宫，月始明于丑宫，始晦于未宫；辰月日月交会于
丑宫，月始明于子宫，始晦于午宫；巳月日月交会于子宫，月始明于亥宫，始晦于巳宫；午
月日月交会于亥宫，月始明于戍宫，始晦于辰宫；未月日月交会于戍宫，月始明于酉宫，始
晦于卯宫；申月日月交会酉宫，月始明于申宫，始晦于寅宫；酉月日月交会于申宫，月始明
于未宫，始晦于丑宫；戍月日月交会于未宫，月始明于午宫，始晦于子宫；亥月日月交会于
午宫，月始明于巳宫，始晦于亥宫；子月日月交会于巳宫，月始明于辰宫，始晦于戍宫；丑
月日月交会于辰宫，月始明于卯宫，始晦于酉宫，现列图如下：

夫妻相合原穴法

真正难解的是为何要以寅宫为回归点呢？因为按照古代天文惯例，演绎年周日月之行，一般
以子半为回归点，而另立寅宫为回归点，这种做法显得很另类，至少我没有见过。那么，原
穴法为何要这样做呢？苦想了许久，认为这存在着两种可能：

其一，在六十首中，各日所主之经的原穴都是以各日俞穴所开之时并过之。原穴法本就是从
六十首法发展而来的，既然专以十二经原穴立论，那就不妨参照六十首原穴寄开体例，以各
日俞穴流注之时作为各日所主、相及之经气血出行原穴之时，尔后比照干经相生体例，依次
演绎各经原穴的流注法则。虽说所持的原穴系统各不相同，但演绎的基本法则是相通的，照
瓢画葫芦，也没什么不可以，至少这种可能性是不能排除的。如是这样，那就并非如我等所
想像的那样深奥复杂了。

其二，六十首中云，“三焦者，是十二经之根本，生气之原，主宣通营卫，经历五脏六腑”，
这源自《难经》三焦原气说。原穴法既传承自六十首，必然会受到三焦原气说的影响，参照
《难经》中“原者，三焦之尊号也，故所止辄为原”之类的论述，原穴法的创立者很可能据
此而得出这样的结论，六十首主论十二经五输，故以水火交为核心，而本法专论十二经原穴
开阖，那就必须以三焦原气之行为核心。三焦者，少阳相火也，在运气学中，少阳相火对化
于寅申，正化于寅，对化于申。因此，在构建演绎原穴开阖的法象模型时，就必须以寅申为
中轴，寅宫为回归点。果如是，这说明创立者是费了不少心血的。联想起六十首的演绎，因
以子午为中轴，子宫为回归点，而被称之为子午流注，那么，原穴法既以寅申为中轴，寅宫
为回归点，是否就可以称之为寅申流注呢？应该是说得通的。

=== 怎样设定经藏气血运行的法象周期

从表面上看，与六十首一样，原穴法也是以十干日为法象周期的，而实际上却有细微差别。
在六十首中，三焦包络寄放于壬、癸两日之间，故仍隶属于十干日的范围之内，而在原穴法
中，却将此两经寄放于癸甲之间，因此，两经所主之壬子、癸丑两日超出了十干日的范围之
外，倘若也计算在内，那就以十二日为一个法象周期了。当然了，依据壬子、癸丑两日所主
之经穴分寄于十干日之中，并没有独立的日期与之对应，只能算作虚应时日，实际上，仍是
以十干日为法象周期的。

=== 怎样演绎各日时中的气血流注规律

这部分的演绎思路与六十首差不离，即各天干日以该干所主之宫为基准，依据该宫所主之月
日月之行的起止方位，推知该日所主相及之经气血的出行时辰，其中，所主之经初出之时法
象于年周日月交会之所，相及之经初出之时法象于月相变化，如是阳经，取象于月始明；如
为阴经，取象于月始晦。所主所及之经初出之时既定之后，各按干经相生的原理，依次演绎
各时所主之经及其原穴完毕之后，天干重见，气血纳入三焦、包络两经并注此两经之原穴。
这里想着重讨论一下十二经原穴以及夫妻经相合的问题。

==== 十二经原穴问题

与六十首以十二经五输为主要的演绎对象不同，所谓原穴法，顾名思义，就是专以十二经原
穴为经穴学基础的流注理论，因此，捋清十二经原穴理论的发展脉络，是理解原穴法的入手
功夫。

十二经原穴这一概念首见于《内经》，《灵枢·九针十二原》与《灵枢·本输》等篇中。《九
针十二原》中说：“五藏有六府，六府有十二原，十二原出于四关，四关主治五藏。五藏有
疾，当取之十二原。十二原者，五藏之所以禀三百六十五节气味也。五藏有疾也，应出十二
原，而原各有所出，明知其原，睹其应，而知五藏之害矣。阳中之少阴，肺也，其原出于太
渊，太渊二。阳中之太阳，心也，其原出于大陵，大陵二。阴中之少阳，肝也，其原出于太
冲，太冲二。阴中之至阴，脾也，其原出于太白，太白二。阴中之太阴，肾也，其原出于太
溪，太溪二。膏之原，出于鸠尾，鸠尾一。肓之原，出于脖胦，脖胦一。凡此十二原者，主
治五藏六府之有疾者也”，阳经无原，阴经以俞穴为原，故肺原在太渊，脾原在太白，肾原
在太溪，肝原在太冲，心（实为心包）原在大陵，左右各一，总计为十。另有膏之原鸠尾，
肓之原脖胦（即气海也），前后通计为十二原。《本输》则与此不同，主张阴经无原穴，阳
穴则另立所过为原穴，胆经之原在丘墟，小肠经之原在腕骨，胃经之原在冲阳，大肠经之原
在合谷，膀胱经之原在京骨，三焦经之原在阳池。至于原穴在五输中的应时定位问题，《灵
枢·顺气一日分为四时》中说：“诸原安合，以致六输？原独不应五时，以经合之，以应其
数”，即将原穴归入到经穴之中，以应五时之数。由此可见，《九针十二原》中的原穴观之
与《本输》中的五输原穴，存在着较大的出入，《内经》并没有形成完整的前后高度一致的
十二经原穴体系。

首先提出完整的十二经原穴系统的，应该是《难经》。《六十六难》中说：“经言：肺之原，
出于太渊；心之原，出于大陵；肝之原，出于太冲；脾之原，出于太白；肾之原，出于太溪；
少阴之原，出于兑骨；胆之原，出于丘墟；胃之原，出于冲阳；三焦之原，出于阳池；膀胱
之原，出于京骨；大肠之原，出于合谷；小肠之原，出于腕骨”，其中，阴经之原出自《九
针十二原》，阳经之原出自《本输》，由此可见，《难经》所主张的十二经原穴，实际上是
将《九针十二原》与《本输》两篇中的观点整合在一起。真正独特的是，《难经》对原穴的
解释，“十二经皆以俞为原者，何也？然。五脏俞者，三焦之所行，气之所留止也；三焦所
行之俞为原者，何也？然。齐下肾间动气者，人之生命也，十二经之根本也，故名曰原。三
焦者，原气之别使也，主通行三气，经历于五脏六腑。原者，三焦之尊号也，故所止辄为原。
五脏六腑之有病者，皆取其原也”、“腑者阳也，三焦行于诸阳，故置一俞名曰原。腑有六
者，亦与三焦共一气也”。以“三焦者，原气之别使也”为依据，以“三焦所行之俞为原”，
这种说法《内经》中是没有的。如依《内经》，无论是《九针十二原》，或是《本输》，原
穴都是从属于五输系统的。《难经》则不然，原穴以三焦原气说为依据，而原气以齐下肾间
为核心，假三焦经历于五脏六腑，散布于四肢原穴，这是一个自内而外，及于四肢的过程。
很显然，这与五输系统向身而行的走向截然相反。假如两者所言属实，理应视为不同的气血
系统，那为何要套用《内经》中的原穴理论来说事呢？这个，恐怕没人能够说得清。

孙思邈《备急千金要方·卷第二十九·三阴三阳流注第二》中，秉持《本输》所过为源的观点，
通过增补阴经过穴的方法，建立了独特的十二经原穴系统。肺经立列缺为源，包络立内关为
源，心经立通里为源，脾经立公孙为源，肝经立中封为源，肾经立水泉为源。肝经中封本为
经穴，既被改立为源穴，于是另立中郄为经穴。按照《明堂三人图第一》中“今一依甄权等
新撰为定”的说法，这一原穴系统也是有所本的，并非孙氏所创。《外台秘要方·第三十九
卷·五藏六腑变化流注出入傍通》中说：“谨按《铜人经》、《甲乙经》、《九墟经》并无
五藏所过为原穴。唯《千金》、《外台秘要集》有之，今列穴名於左∶中俕即中都、内关、
公孙、列缺、水原（即水泉）”，《十二身流注五藏六腑明堂·肝人》又说：“肝
人……《甲乙经》肝出於大敦，大敦者木也……流於行间，行间者火也……注於太冲，太冲
者土也……行於中封，中封者金也……入於曲泉，曲泉者水也”，王焘虽沿用《千金方》原
穴体例，但对肝经进行了调整，改立中郄穴(亦名中都)立为原穴，并将中封改回为经穴。通
里、公孙、列缺、内关皆为络穴，中郄、水泉皆为郄穴，后世或有针家鉴于《内经》五输之
原，无一络穴或郄穴，讥其原、络不分。不过，倘若以“所过为源”，只要是“所过”，又
何必在乎是络穴或郄穴呢？从阴经增设所过为源的思路上看，这一原穴系统可被视为基于
《本输》之上的扩展形式。

以《内经》为诸家之根源，《难经》、《千金方》等为《内经》之发挥，合计为三大原穴体
系，这便是史上相关十二经原穴体系的大致概况。就影响而言，《内》、《难》的影响是不
用说的，后世针家凡论十二经原穴，多以《内》、《难》为依据。至于《千金》所载的原穴
系统，除了《外台》，采用的人很少见，影响就要小得多了。如论对十二经原穴的解释，除
了上述经典所论之外，别出心裁，足以成一家之言，且对后世有较大影响者，那就是流注学
了。

在六十首中，以三焦为“十二经之根本，生气之原，主宣通荣卫，经历五脏六腑”，这无疑
受到《难经》三焦原气说的影响而提出的，可是，十二经原穴体例却并不采纳《难经》以俞
为原的做法，而是依准于《本输》。原穴法传承自六十首，在演绎上以三焦为核心，在原穴
上采用《本输》的扩展形式，即《外台》中的原穴体例，大肠经原穴为合谷，肺经原穴为列
缺，包络经原穴为内关，三焦经原穴为阳池，脾经原穴为公孙，胃经原穴为冲阳，心经原穴
为通里，小肠经原穴为腕骨，肝经原穴为中都，胆经原穴为丘墟，膀胱经原穴为京骨，肾经
原穴为水泉。由于缺乏原始文献，当初的想法已经无从窥知。不过，依据所采取的解决方案，
原穴法之与六十首，在基本思路上差不离，可见此中的传承关联。因此，流注学中的原穴体
例是秉承《本输》这一传统的，在解释上却采纳《难经》中的三焦原气说。

夫妻相合原穴法

==== 夫妻经原穴问题

依据《歌诀》所载，各日皆以某干与某干合，某经引气血出行为篇纲，如“甲日，甲与己合，
胆引气行”、“乙日，乙与庚合，肝引血行”等，五门十变之说仅用于各日所主之经气血出
行体例上，并不推及于各时之中。原穴法则走得更远，将五门十变之说推及于各日各时之中，
这也是后人谓之十二经夫妻相合逐日按时开原穴法的由来。十变说是以天干为基础的，依据
干经映射模型，便可推得五藏五腑及其原穴的十变关系。至于三焦、包络，本不在十干范围
之内，于是仿照六十首，将两经自相配合。三焦为戊，包络为己，故戊与己合，三焦阳池与
包络内关两经原穴自相配合。

夫妻相合原穴法

既然各日各时之中都以十变，那所得的夫妻经原穴之间的关系又如何处理呢？由于原始文献
的缺失，原初的意图与用法已无可稽考。从演绎的角度，十变说只能以各时所主之干及其经
穴为基础，尔后方能依据十变，推及其所合的夫经或妻经原穴，例如，某时气注甲胆经原穴，
依据甲与己合，推得该时所合之经穴为己脾经原穴，这便形成了能合与所合的关系。因此，
在实际使用时，也应有所区别，以该时所主之经穴为主，以所合之经穴为配。

== 十干日阴阳经应时流注的规律

甲日 甲日所主之宫在卯。卯月日月交会于寅宫，月始明于丑宫，始晦于未宫。故甲日所主
之甲胆经于寅时引气出行，所及之经为乙肝经，属阴经，法象于月始晦，于未时引血出行。

            寅时 甲胆经为所出，故以丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         辰时 丙小肠为所溜，故以腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

         午时 戊胃经为所注，故以冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

         申时 庚大肠为所经，故以合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

         戍时 壬膀胱这所入，故以京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         子时 甲干重见，气纳三焦，故戊三焦阳池为主穴。戊与己合，故以己包络内关为
         配穴。

 

         未时 乙肝经为所出，故以中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         酉时 丁心经为所溜，故以通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

         亥时 己脾经为所注，故以公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

       丑时 辛肺经为所经，故以列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         卯时 癸肾经为所入，故以水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         巳时 乙干重见，血纳包络，故以己包络内关为主穴。己与戊合，故以戊三焦阳池
         为配穴。

 

乙日 乙日所主之宫在辰。辰月日月交会于丑宫，月始明于子宫，始晦于午宫。故乙日所主
之乙肝经于丑时引血出行，所及之经为甲胆经，属阳经，法象于月始明，于子时引气出行。

       丑时 乙肝经为所出，故以中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         卯时 丁心经为所溜，故以通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

         巳时 己脾经为所注，故以公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

         未时 辛肺经为所经，故以列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         酉时 癸肾经为所入，故以水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         亥时 乙干重见，血纳包络，故以己包络内关为主穴。己与戊合，故以戊三焦阳池
         为配穴。

 

       子时 甲胆经为所出，故以丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         寅时 丙小肠为所溜，故以腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

         辰时 戊胃经为所注，故以冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

         午时 庚大肠为所经，故以合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

       申时 壬膀胱为所入，故以京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         戍时 甲干重见，气纳三焦，故以戊三焦阳池为主穴。戊与己合，故以己包络内关
         为配穴。

丙日 丙日所主之宫在巳。巳月日月交会于子宫，月始明于亥宫，始晦于巳宫。故丙日所主
之丙小肠于子时引气出行，所及之经为丁心经经，属阴经，法象于月始晦，于巳时引血出行。

       子时 丙小肠为所出，故以腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

寅时 戊胃经为所溜，故以冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

       辰时 庚大肠为所注，故以合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

         午时 壬膀胱为所经，故以京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         申时 甲胆经为所入，故以丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         戍时 丙干重见，气纳三焦，故以戊三焦阳池为主穴。戊与己合，故以己包络内关
         为配穴。

      

         巳时 丁心经为所出，故以通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

未时 己脾经为所溜，故以公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

         酉时 辛肺经为所注，故以列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         亥时 癸肾经为所经，故以水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         丑时 乙肝经为所入，故以中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         卯时 丁干重见，血纳包络，故以己包络内关为主穴。己与戊合，故以戊三焦阳池
         为配穴。

        

丁日 丁日所主之宫在午。午月日月交会于亥宫，月始明于戍宫，始晦于辰宫。故丁日所主
之丁心经于亥时引血出行，所及之经为丙小肠，属阳经，法象于月始明，于戍时引气出行。

       亥时 丁心经为所出，故以通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

丑时 己脾经为所溜，故以公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

         卯时 辛肺经为所注，故以列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         巳时 癸肾经为所经，故以水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         未时 乙肝经为所入，故以中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         酉时 丁干重见，血纳包络，故以己包络内关为主穴。己与戊合，故以戊三焦阳池
         为配穴。

 

         戍时 丙小肠为所出，故以腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

子时 戊胃经为所溜，故以冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

         寅时 庚大肠为所注，故以合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

         辰时 壬膀胱为所经，故以京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         午时 甲胆经为所入，故以丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         申时 丙干重见，气纳三焦，故以戊三焦阳池为主穴。戊与己合，故以己包络内关
         为配穴。

       

戊日 戊日所主之宫在未。未月日月交会于戍宫，月始明于酉宫，始晦于卯宫。故戊日所主
之戊胃经于戍时引气出行，所及之经为己脾经，属阴经，法象于月始晦，于卯时引血出行。

       戍时 戊胃经为所出，故以冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

子时 庚大肠为所溜，故以合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

寅时 壬膀胱为所注，故以京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         辰时 甲胆经为所经，故以丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         午时 丙小肠为所入，故以腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

         申时 戊干重见，气纳三焦，故以戊三焦阳池为主穴。戊与己合，故以己包络内关
         为配穴。

       

         卯时 己脾经为所出，故以公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

巳时 辛肺经为所溜，故以列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         未时 癸肾经为所注，故以水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         酉时 乙肝经为所经，故以中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         亥时 丁心经为所入，故以通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

         丑时 己干重见，血纳包络，故以己包络内关为主穴。己与戊合，故以戊三焦阳池
         为配穴。

     

己日 己日所主之宫在申。申月日月交会酉宫，月始明于申宫，始晦于寅宫。故己日所主之
己脾经于酉时引血出行，所及之经为戊胃经，属阳经，法象于月始明，于申时引气出行。

       酉时 己脾经为所出，故以公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

         亥时 辛肺经为所溜，故以列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         丑时 癸肾经为所注，故以水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         卯时 乙肝经为所经，故以中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         巳时 丁心经为所入，故以通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

         未时 己干重见，血纳包络，故以己包络内关为主穴。己与戊合，故以戊三焦阳池
         为配穴。

 

申时 戊胃经为所出，故以冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

戍时 庚大肠为所溜，故以合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

         子时 壬膀胱为所注，故以京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         寅时 甲胆经为所经，故以丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         辰时 丙小肠为所入，故以腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

         午时 戊干重见，气纳三焦，故以戊三焦阳池为主穴。戊与己合，故以己包络内关
         为配穴。

   

庚日 庚日所主之宫在酉。酉月日月交会于申宫，月始明于未宫，始晦于丑宫。故庚日所主
之庚大肠于申时引气出行，所及之经为辛肺经，属阴经，法象于月始晦，于丑时引血出行。

         申时 庚大肠为所出，故以合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

         戍时 壬膀胱为所溜，故以京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         子时 戊胃经为所注，故以冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

         寅时 丙小肠为所经，故以腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

         辰时 甲胆经为所入，故以丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         午时 庚干重见，气纳三焦，故以戊三焦阳池为主穴。戊与己合，故以己包络内关
         为配穴。

    

         丑时 辛肺经为所出，故以列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         卯时 癸肾经为所溜，故以水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         巳时 乙肝经为所注，故以中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         未时 丁心经为所经，故以通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

         酉时 己脾经为所入，故以公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

         亥时 辛干重见，血纳包络，故以己包络内关为主穴。己与戊合，故以戊三焦阳池
         为配穴。

 

辛日 辛日所主之宫在戍。戍月日月交会于未宫，月始明于午宫，始晦于子宫。故辛日所主
之辛肺经于未时引血出行，所及之经为庚大肠经，属阳经，法象于月始明，于午时引气出行。

未时 辛肺经为所出，故以列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

酉时 癸肾经为所溜，故以水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

亥时 乙肝经为所注，故以中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         丑时 丁心经为所经，故以通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

         卯时 己脾经为所入，故以公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

         巳时 辛干重见，血纳包络，故以己包络内关为主穴。己与戊合，故以戊三焦阳池
         为配穴。

 

午时 庚大肠为所出，故以合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

申时 壬膀胱为所溜，故以京骨为主穴。壬与丁合，故以丁心经通里为配穴；

             戍时 甲胆经为所注，故以丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         子时 丙小肠为所经，故以腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

         寅时 戊胃经为所入，故以冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

         辰时 庚干重见，气纳三焦，故以戊三焦阳池为主穴。戊与己合，故以己包络内关
         为配穴。

 

壬日 壬日所主之宫在亥。亥月日月交会于午宫，月始明于巳宫，始晦于亥宫，故壬日所主
之壬膀胱经于午时引气出行，所及之经为癸肾经，属阴经，法象于月始晦，于亥时引血出行。

       午时 壬膀胱为所出，故以京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         申时 甲胆经为所溜，故以丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         戍时 丙小肠为所注，故以腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

         子时 戊胃经为所经，故以冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

         寅时 庚大肠为所入，故以合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

         辰时 壬干重见，气纳三焦，故以戊三焦阳池为主穴。戊与己合，故以己包络内关
         为配穴。

 

         亥时 癸肾经为所出，故以水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         丑时 乙肝经为所溜，故以中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         卯时 丁心经为所注，故以通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

         巳时 己脾经为所经，故以公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

         未时 辛肺经为所入，故以列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         酉时 癸干重见，血纳包络，故以己包络内关为主穴。己与戊合，故以戊三焦阳池
         为配穴。

 

癸日 癸日所主之宫在子。子月日月交会于巳宫，月始明于辰宫，始晦于戍宫。故癸日所主
之癸肾经于巳时引血出行，所及之经为壬膀胱经，属阳经，法象于月始明，于辰时引气出行。

       巳时 癸肾经为所出，故以水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         未时 辛肺经为所溜，故以列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         酉时 乙肝经为所注，故以中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         亥时 丁心经为所经，故以通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

         丑时 己脾经为所入，故以公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

         卯时 癸干重见，血纳包络，故以己包络内关为主穴。己与戊合，故以戊三焦阳池
         为配穴。

 

       辰时 壬膀胱为所出，故以京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         午时 甲胆经为所溜，故以丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         申时 丙小肠为所注，故以腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

         戍时 戊胃经为所经，故以冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

         子时 庚大肠为所入，故以合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

         寅时 壬干重见，气纳三焦，故以戊三焦阳池为主穴。戊与己合，故以己包络内关
         为配穴。

 

十干日演绎完毕之后，顺次进入丑寅两宫。在原穴法中，立丑寅两宫所主之经为三焦、包络，
并配之以戊己，这无疑是伟大的创见，但这样做，也不是说没有代价的，那就是使得两经所
主之日时的演绎走进了死胡同。

在六十首中，子丑两宫在壬癸两日之间，若论真实的天干分野，当属壬癸两日之中，因而立
壬癸为所主之干，仿照壬癸两日中各时所主之干的演绎体例加以演绎，这样的解决方案虽说
有些牵强，但总算有个可以凑合的说法。到了原穴法，由于丑寅两宫本就不在干经分野之内，
如此，连仿照演绎的对象都找不到了。有人说了，不是将两经定位为戊己吗？为何不仿照戊
己两日演绎处理呢？将两经定位为戊己不假，但此戊己不同于彼戊己，一则定位于丑寅，一
则定位于未申，两者悬隔敌对，并不象六十首中子丑两宫位居于壬癸分野之间，如何仿照得
来？那么，独立演绎又如何呢？我们知道，流注学既以干经映射模型为演绎基础的，除此之
外，别无蹊径。要独立演绎，不是不可以，但总得有所依凭。现在，理无可依，法无可据，
如何演绎得来？如果置之不理，那就出现了丑寅两宫的演绎断层，这个BUG实在太大了，如
何说得过去？

大概也是左思右想，走投无路，原穴法无奈之下，采用了不是办法的办法，将六十首中子丑
两宫所主的时干体例移植到丑寅两宫中去，并另立壬子、癸丑两日以映射之。所谓壬子日、
癸丑日，无疑出自六十首法中三焦、包络所主之壬子时、癸丑时，那么，为什么非要另立为
壬子日、癸丑日呢？在流注法中，三焦、包络本就不属于任一个天干日期的，因此，在六十
首中，此两经虽居于壬、癸两日之间，却并不居于壬、癸两日之中；在原穴法中，此两经居
于丑寅两宫，并配以戊己，却并不在戊己两日之中。然而，按原穴法干支映射模型，各支各
占一日，此两经必须有虚应日时以映射之，否则，前后就失去了一致性了，怎么办？这大概
就是原穴法据六十首三焦、包络所主之壬子时、癸丑时，而另立虚应日期，即壬子日、癸丑
日以映射丑寅两宫所主之日时的由来。后人不明就里，误认壬子日、癸丑日为甲子日时，那
就贻笑方家了。

然而，问题却并没有到此结束。六十首以五输立论，三焦、包络两经之所主可以用两经之五
输虚应演绎各时所开之穴，但到了原穴法，这样做就行不通了，因为原穴法专以原穴立论，
倘若也象六十首那样，仅以三焦、包络两经之经穴论之，那么，丑寅两宫所主之二日二十四
时中，只有两穴可用，也就是凡阳时皆仅以三焦原穴，凡阴时皆仅以包络原穴主之，这太荒
谬了。为此，原穴法改依各时所主之干，开各经之原穴，所得结果如下：

壬子日 子时 壬′为所出，故以壬膀胱京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         寅时 甲′为所溜，故以甲胆经丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         辰时 丙′为所注，故以丙小肠腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

         午时 戊′为所经，故以戊胃经冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

         申时 庚′为所入，故以庚大肠合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

         戍时 壬′干重见，气纳三焦，故以三焦经阳池为主穴。戊与己合，故以己包络内
         关为配穴；

 

         巳时 癸′为所出，故以癸肾经水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         未时 乙′为所溜，故以乙肝经中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         酉时 丁′为所注，故以丁心经通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

         亥时 己′为所经，故以己脾经公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

         丑时 辛′为所入，故以辛肺经列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         卯时 癸′干重见，血纳包络，故以包络经内关为主穴。己与戊合，故以戊三焦阳
         池为配穴；

 

癸丑日 丑时 癸′为所出，故以癸肾经水泉为主穴。癸与戊合，故以戊胃经冲阳为配穴；

         卯时 乙′为所溜，故以乙肝经中都为主穴。乙与庚合，故以庚大肠合谷为配穴；

         巳时 丁′为所注，故以丁心经通里为主穴。丁与壬合，故以壬膀胱京骨为配穴；

         未时 己′为所经，故以己脾经公孙为主穴。己与甲合，故以甲胆经丘墟为配穴；

         酉时 辛′为所入，故以辛肺经列缺为主穴。辛与丙合，故以丙小肠腕骨为配穴；

         亥时 癸′干重见，血纳包络，故以包络经内关为主穴，己与戊合，故以戊三焦阳
         池为配穴；

 

  子时 壬′为所出，故以壬膀胱京骨为主穴。壬与丁合，故以丁心经通里为配穴；

         寅时 甲′为所溜，故以甲胆经丘墟为主穴。甲与己合，故以己脾经公孙为配穴；

         辰时 丙′为所注，故以丙小肠腕骨为主穴。丙与辛合，故以辛肺经列缺为配穴；

         午时 戊′为所经，故以戊胃经冲阳为主穴。戊与癸合，故以癸肾经水泉为配穴；

         申时 庚′为所入，故以庚大肠合谷为主穴。庚与乙合，故以乙肝经中都为配穴；

         戍时 壬′干重见，气纳三焦，故以三焦经阳池为主穴，戊与己合，故以己包络内
         关为配穴；

 

世传《穴法图》之后，附有解释条文，“令有壬子、癸丑二日在外不同此，二日计二十四日
图，逐日配合刺切要：阳日阳时针阴穴，阴日阴时针阳穴；阳日阴时针阳穴，阴日阳时针阴
穴”。此条文无疑是解释壬子、癸丑两日所主之时穴的用法，这究竟包涵着哪些涵义呢？

文中“令有”之令与另同音，令有疑为另有。所谓“令有壬子、癸丑二日在外不同此”，就
是在十干日之外，另有壬子、癸丑二日中的流注法则与如上所述不同，其中的道理，上面已
经分析过了。文中“二日”日即壬子、癸丑二日，“二十四日”疑为笔误，当为二十四时。
所谓“二日计二十四日图”，就是指壬子、癸丑二日二十四时流注图表。所谓“逐日配合刺
切要”，讲的是这两日二十四时流注法则的实际用法，即必须与十干日配合使用。

如前所述，在十干日中，各日所主之时穴只能隶属于所主之日，不可越次。但壬子日、癸丑
日与此不同，只是虚应日期，并不象十干日那样有独立的所主之日，那这两日总计二十四时
注穴又该如何使用呢？依据壬子、癸丑两日所主之经为三焦、包络，所主之宫为丑寅艮宫。
依据古代易数理论，艮为中央土，在干为戊己，分寄于四方以应四时，因此，若论这两日总
计二十四时注穴的用法，也应分寄于十干日之中，逐日配合使用，这就是要强调“逐日配合
刺切要”的由来。

真正的问题在于怎么个“逐日配合”法，依据解释条文，那就是“阳日阳时针阴穴，阴日阴
时针阳穴；阳日阴时针阳穴，阴日阳时针阴穴”。所谓阴日、阳日，只能以十干日立论，其
中，阳干日如甲日、丙日等为阳日，阴干日如乙日、丁日等为阴日。所谓阴时、阳时，以十
二时辰立论，其中，阳支时如子时、午时、戍时等为阳时，阴支时如丑时、卯时、未时等为
阴时。原文说得有点绕，简单地说，就是各日之中，阳时针取其阴经穴，阴时针取其阳经穴。

在十干日中，阳时以阳经穴为主，阴时以阴经穴为主，这是必然之则，为何这壬子、癸丑两
日要花样另出，反其道而行之呢？我曾为之困惑了很长一段时间，猜想，这样的使用方法倘
若能够成立，只有在壬子、癸丑两日在演绎时出现阴阳颠倒的形情下才有可能。从演绎的角
度，如将包络三焦所主之宫从壬癸两日之间的子丑平移至癸日之后的丑寅，就会出现两经所
主之宫阴阳属性相颠倒的形情，怎么办呢？依据条文解释，给出的解决方案就是倒着用。假
如猜想属实，这反映了创立者应急变通的基本思路。既然壬子、癸丑两日移植于六十首，不
妨再看一下六十首本身的处理方法。在六十首中，在演绎时虽然将包络、三焦两经定位于子
丑，但从十干日分野的大框架上看，子丑两宫隶属于壬癸两日之中，于是，在实际的日期定
位中，特将三焦所主之法前移到壬日之后，包络所主之法后移到癸日之前，这样，也会出现
两经在实际的日期定位与演绎定位在阴阳属性上刚好相颠倒，怎么办呢？假如解释条文也是
移植于六十首，那就反映了六十首创立者的变通思路，不是刚好倒了过个了吗？那就倒着用
呗！当然了，所有这些都是猜想的，古人真实的想法如何，只有鬼知道。在实际的使用过程
中，阳时究竟怎样针取其阴穴，阴时究竟怎样针取其阳穴，仍然涉及到许多难解的问题。反
正没有相应的解释条文，凭空分析没意思，罢了。

治学是十分严谨的事。倘若遇到一时难以解决的问题，应该多闻阙疑，说明原由，以待高明，
而不是师心自用，自以为是。再看原穴法，在演绎三焦、包络所主之丑寅两宫的流注法则时，
由于遇到了一时难以解决的问题，便拿六十首中三焦、包络的流注法则来搪塞了事，这样的
做法，实在不敢苟同，然而，却在将错就错中，保全了六十首三焦包络两经所主日时的时干
对应模型，成为内行血经六十首唯一残存于世的原始数据，说它价抵万金也不为过。想当初，
本人就是于此中窥得端倪，想出还原内行六十首的基本思路的。

原穴法本就流传不广，对此法有过关注的医家，屈指数来，也就那么几位。令人尴尬的是，
这些医家居然都将“二日计二十四日”之“二日”注释为十干日中的阴日与阳日。原条文说
得很明白，语意也很直截，却犯这样低级的理解错误，让人感到很无语，不说也罢。夫妻相
合原穴法


== 从《流注·序》谈开去

按《玉龙经·流注》编次，篇首为王国瑞所撰之《序》，《时日配合穴法图》附之于篇后，
因此，一般都将《序》视为原穴法的解释文献，这样的观点是否靠得住呢？

天有十干，地支十二。以干加支，常遗其二。二一合化，五运六气。是以甲、乙、丙、 丁、
戊、己、庚、辛，一而不重壬癸，壬、癸乃重其位。阴阳不质，五行质气。气质既形，胎生
墓死。所以甲犹草木，原因壬癸。气行于天，质具于地。质气之分，阴质阳气。故阳主变化，
阴主专静而莫自制。是以阳府示原，阴藏隐秘。然夫自子至巳，六阳化合；自午至亥，六阴
变化。惟壬得一，癸二从之，为阴阳动静之枢纽，气数欲兆之时。故气运一周，一会于壬癸，
交接挥持，莫为其纪。故子午流注针诀，甲始于戌，而壬癸为终，壬子、癸丑为终始之地。
一顺一逆，一纵一横，一起一止，一变一互，一合一化，一君一臣，一佐一使，一生 一克
，一母一子，一夫一妇，交神合气，变化无穷。所以一岁总六十穴，月、日、时，刻，一刻
备六十穴，岁明月日如之，其何以然哉？日月三十日则一会；于河图，一穴（作者注：原文
笔误，当为一六。在河图，一六居北方）居北而括万极，此皇极先天之数所由起，五行五气
所由化合，子午流注针法之心要也，神之变化渊乎哉！ ———《玉龙经·流注·序》

通览全文，核心的宗旨就是依据《针经》中的载述，加上自己的理解，解释壬子、癸丑干支
相合的形成机制。所谓“所以甲犹草木，原因壬癸”，这出自于《五行造化歌》中“甲犹草
木芽初出，乙屈知同离上生。原因壬癸为胎气，翻成十干五行亨”；所谓“子午流注针诀，
甲始于戌，而壬癸为终，壬子、癸丑为终始之地”，这是出自《井荥歌诀六十首》中的流注
体例。其他都是些附会之文，没必要多费笔墨，在这里，仅谈一下所谓“皇极先天之数”。
“皇极先天之数”的概念源出于邵氏易，所谓“先天”，即“出于自然”的意思，“皇极”，
按邵伯温的说法，即至大至中的意思，按邵雍的说法，约是牺皇垂范之则的意思，在这里，
可视为修饰性的赞辞，因此，所谓“皇极先天之数”，实际上就是取其自然之数的意思。至
于先天象数之学，桥归桥，路归路，与原穴法了不相涉。后世的注释家们，不明就里，一见
序云“皇极先天之数”，便说原穴法的形成受到宋代邵康节干支象数之学的直接影响，这是
望文生训。

从源承上讲，原穴法当然是从六十首发展而来的，但是，在各日之中，逐时流经注穴的演绎
方法却各有各的玩法，无法简单套用解释。然而，在《玉龙经·流注》中，无论是序文，或
是《手指诀》、《司天诀》之类，给人的直观印象是，王国瑞套用《井荥歌诀六十首》的流
注体例来解释原穴法，至少，将他们混编在一起这一做法本身就存在着误导读者的思考取向
的嫌疑。针家皆云原穴法为王国瑞所创用，依据常识，作为创立者，对自己所创立的东西必
然是知根知底的，为什么会做出如此不着调的事情来？

我们再看王国瑞对十二经原穴的定义。王国瑞在《注解<标幽赋>》中“十二经络十二原，是
为枢要；一日刺六十六穴之法，方见幽微；一时取十二经之原，始知要妙”条下注释说，
“甲光明，走乙肝；乙蠡沟，走甲胆；丙腕骨（当为支正），走丁心；丁通里，走丙小肠；
戊丰隆，走巳脾；巳公孙，走戊胃；庚偏历，走辛肺；辛列缺，走庚大肠；壬飞扬，走癸肾；
癸大钟，走壬膀胱；三焦与包络相为表里，此为十二原穴……一日刺六十六穴之法，用甲、
丙、戊、庚、壬五穴，每时相配乙、丁、己、辛、癸。一时十穴，五六三十，两手两足相对，
共计六十穴。一时平取十二经之原，亦可遍经而已矣”，大家瞧见没有？王国瑞在注释中所
主张的十二经之原与原穴法中的十二经之原大不相类，而且“每时相配”主张以表里经立论，
也与原穴法主张以夫妻经立论大不相类。这样的十二经之原，为我平生所仅见。针家或谓王
国瑞所述，犯了络原不分之弊，但王国瑞既然这样做，总得有所本吧？那其所本究竟是什么
呢？很迷茫！

纵观《玉龙经》，除了《注解<标幽赋>》条下对十二经之原的解释以及《流注》目下的相关
图文，居然找不出其他与原穴法看似相关的论述。假如王国瑞就是原穴法的创立者，或出于
古人普遍存在的保守心态，通篇不论原穴法的立法原理及其使用方法，秘不示人倒也罢了，
为什么要故意背离或误导之呢？前有《注解<标幽赋>》对十二经之原的注释与原穴法中的原
穴观大不相类，后有序文以《井荥歌诀六十首》套解原穴法，不也奇也哉，怪也哉？苦思良
久之后，我认为只有一种可能，那就是《时日配合穴法图》及其附文是王国瑞不知从哪里抄
入转录的，他自己也没搞懂这是咋回事，所以才会做出如此前后不着调的事来。

因此，所谓王国瑞创立原穴法，是后世医家依据现存的文献，原穴法首见于《玉龙经》而提
出的想当然的观点，实际上是不靠谱的。“纸上得来终觉浅，绝知此事要躬行”。做学问，
必须做到自己知根知底的地步，才能提示历史的真面目。不过，话又说回来，假如没了王国
瑞，原穴法很可能会就此失传，流注学也就成了无人能破的千古之谜。从这个意义上讲，王
国瑞仍然功不可没。
