= 黃帝內經

== 牛人

* http://blog.sina.com.cn/u/1294992875[石清峡士]
* http://blog.sina.com.cn/nimdazjh[学医者小红]
* http://www.jianshu.com/u/d533aad63383[MC钟]
* http://blog.sina.com.cn/guanshanlaoren[冠山老人]
* http://guanshanlaoren.1.blog.163.com/[冠山老人]

* http://blog.sina.com.cn/menwaiqihuang[二郎中]
* http://blog.sina.com.cn/u/1906123920[aaagj]

* http://blog.sina.com.cn/zhongyixiuzheng[中医修正]
* http://blog.sina.com.cn/u/2764794934[拄其间]

== 概念

=== 气

=== 经

=== 脉

=== 络


== 后天

五穀入于胃也，其糟粕津液宗氣，分為三隧。故宗氣積於胸中，出於喉嚨，以貫心脈，而行
呼吸焉。營氣者，泌其津液，注之於脈，化以為血，以榮四末，內注五藏六府，以應刻數焉。
節氣者，出其悍氣之慓疾，而先行於四末分肉皮膚之間，而不休者也。

黃帝曰：余聞腸胃受穀，上焦出氣，以溫分肉，而養骨節，通腠理。中焦出氣如露，上注谿
谷，而滲孫脈，津液和調，變化而赤為血。血和則孫脈先滿溢，乃注于絡脈，皆盈，乃注于
經脈，陰陽已張，因息乃行。

帝曰：脾與胃以膜相連耳，而能為之行其津液，何也。歧伯曰：足太陰者三陰也，其脈貫胃
屬脾絡嗌，故太陰為之行氣於三陰。陽明者，表也，五藏六府之海也，亦為之行氣於三陽。
藏府各因其經而受氣於陽明，故為胃行其津液。四支不得稟水穀氣，日以益衰，陰道不利，
筋骨肌肉無氣以生，故不用焉。

黃帝曰：營衛之行奈何？伯高曰：穀始入于胃，其精微者，先出於胃之兩焦，以溉五藏，別
出兩行，營衛之道。其大氣之搏而不行者，積於胸中，命曰氣海，出於肺，循咽喉，故呼則
出，吸則入。


== 问题

=== 脉

脉的方向和营气的方向有什么关系？

==== 循行

《营气》
《邪客》

=== 神气

循行灌注如何转化生成十二经气血,然后从末端返回

=== 营气

宗气与营气的循行完全一样吗？

==== 循行

《营气》

=== 卫气

==== 循行

同时散行还是依次循行？

白天在阴分过不过五脏？


=== 五输

其著於輸之脈者，閉塞不通，津液不下，孔竅干壅，此邪氣之從外入內，從上下也。

=== 其他

==== 清浊

黃帝曰：願聞人氣之清濁。歧伯曰：受穀者濁，受氣者清。清者注陰，濁者注陽。濁而清者，
上出於咽，清而濁者，則下行。清濁相干，命曰亂氣。

肉之大會為谷，肉之小會為谿，肉分之閒，谿谷之會，以行榮衛，以會大氣。

阳受气于四末

== 十二經脈

經脈者，所以行血氣而營陰陽、濡筋骨，利關節者也；

夫脈者，血之府也，

夫十二經脈者，皆絡三百六十五節，

雷公曰：願卒聞經脈之始生。黃帝曰：經脈者，所以能決死生、處百病、調虛實，不可不通。

夫十二經脈者，人之所以生，病之所以成，人之所以治，病之所以起，學之所始，工之所止
也。麤之所易，上之所難也。

雷公曰：何以知經脈之與絡脈異也？黃帝曰：經脈者，常不可見也，其虛實也，以氣口知之。
脈之見者，皆絡脈也。

夫十二經脈者，內屬於府藏，外絡於肢節，

胃之所出氣血者，經隧也。而隧者，五藏六府之大絡也，

何謂脈？歧伯曰：壅遏營氣，令無所避，是謂脈。

**肺手太陰之脈**，起於中焦，下絡大腸，還循胃口，上膈屬肺，從肺系橫出腋下，下循臑
內，行少陰心主之前，下肘中，循臂內上骨下廉，入寸口，上魚，循魚際，出大指之端；其
支者，從腕後直出次指內廉出其端。

**大腸手陽明之脈**，起於大指次指之端，循指上廉，出合谷兩骨之間，上入兩筋之中，循
臂上廉，入肘外廉，上臑外前廉，上肩，出髃骨之前廉，上出於柱骨之會上，下入缺盆，絡
肺，下膈，屬大腸。其支者，從缺盆上頸，貫頰，入下齒中，還出挾口，交人中，左之右，
右之左，上挾鼻孔。

**胃足陽明之脈**，起於鼻之交頞中，旁納太陽之脈，下循鼻外，入上齒中，還出挾口環唇，
下交承漿，卻循頤後下廉，出大迎，循頰車，上耳前，過客主人，循髮際，至額顱；其支者，
從大迎前下人迎，循喉嚨，入缺盆，下膈，屬胃，絡脾；其直者，從缺盆下乳內廉，下挾臍，
入氣沖中；其支者，起於胃口，下循腹裏，下至氣沖中而合，以下髀關，抵伏兔，下膝臏中，
下循脛外廉，下足跗，入中指內間；其支者，下廉三寸而別下入中趾外間；其支者，別跗上，
入大趾間出其端。

**脾足太陰之脈**，起於大趾之端，循趾內側白肉際，過核骨後，上內踝前廉，上踹內，循
脛骨後，交出厥陰之前，上膝股內前廉，入腹，屬脾，絡胃，上膈，挾咽，連舌本，散舌下；
其支者，復從胃，別上膈、注心中。

**心手少陰之脈**，起於心中，出屬心系，下膈，絡小腸；其支者，從心系，上挾咽，系目
系；其直者，復從心系卻上肺，下出腋下，下循臑內後廉，行太陰心主之後，下肘內，循臂
內後廉，抵掌後銳骨之端，入掌內後廉，循小指之內，出其端。

**小腸手太陽之脈**，起於小指之端，循手外側，上腕，出踝中，直上循臂骨下廉，出肘內
側兩筋之間，上循臑外後廉，出肩解，繞肩胛，交肩上，入缺盆，絡心，循咽，下膈，抵胃，
屬小腸；其支者，從缺盆循頸上頰，至目銳眥，卻入耳中；其支者，別頰上䪼，抵鼻，至目
內眥，斜絡於顴。

**膀胱足太陽之脈**，起於目內眥，上額，交巔；其支者，從巔至耳上角；其直者，從巔入
絡腦，還出別下項，循肩髆內，挾脊，抵腰中，入循膂，絡腎，屬膀胱；其支者，從腰中下
挾脊，貫臀，入膕中；其支者，從髆內左右，別下，貫胛，挾脊內，過髀樞，循髀外，從後
廉，下合膕中，以下貫踹內，出外踝之後，循京骨，至小趾外側。

**腎足少陰之脈**，起於小趾之下，邪走足心，出於然谷之下，循內踝之後，別入跟中，以
上踹內，出膕內廉，上股內後廉，貫脊，屬腎，絡膀胱；其直者，從腎上貫肝膈，入肺中，
循喉嚨，挾舌本；其支者，從肺出絡心，注胸中。

**心主手厥陰心包絡之脈**，起於胸中，出屬心包絡，下膈，歷絡三焦；其支者，循胸出脅，
下腋三寸，上抵腋下，循臑內，行太陰、少陰之間，入肘中，下臂，行兩筋之間，入掌中，
循中指，出其端；其支者，別掌中，循小指次指，出其端。

**三焦手少陽之脈**，起於小指次指之端，上出兩指之間，循手表腕，出臂外兩骨之間，上
貫肘，循臑外，上肩，而交出足少陽之後，入缺盆，布膻中，散落心包，下膈，循屬三焦；
其支者，從膻中上出缺盆，上項系耳後，直上出耳上角，以屈下頰至䪼，其支者，從耳後入
耳中，出走耳前，過客主人前，交頰，至目銳眥。

**膽足少陽之脈**，起於目銳眥，上抵頭角下耳後，循頸行手少陽之前，至肩上卻交出手少
陽之後，入缺盆；其支者，從耳後入耳中，出走耳前，至目銳眥後；其支者，別銳眥，下大
迎，合於手少陽，抵於䪼下，加頰車，下頸，合缺盆，以下胸中，貫膈，絡肝，屬膽，循脅
裏，出氣沖，繞毛際，橫入髀厭中；其直者，從缺盆下腋，循胸，過季脅下合髀厭中，以下
循髀陽，出膝外廉，下外輔骨之前，直下抵絕骨之端，下出外踝之前，循足跗上，入小趾次
趾之間；其支者，別跗上，入大指之間，循大指歧骨內，出其端，還貫爪甲，出三毛。

**肝足厥陰之脈**，起於大趾叢毛之際，上循足跗上廉，去內踝一寸，上踝八寸，交出太陰
之後，上膕內廉，循股陰，入毛中，過陰器，抵小腹，挾胃，屬肝，絡膽，上貫膈，布脅肋，
循喉嚨之後，上入頏顙，連目系，上出額，與督脈會於巔；其支者，從目系下頰裏，環唇內；
其支者，復從肝，別貫膈，上注肺。

== 十二原

五藏有六府，六府有十二原，十二原出於四關，四關主治五藏。五藏有疾，當取之十二原。
十二原者，五藏之所以稟三百六十五節氣味也。五藏有疾也，應出十二原。十二原各有所
出。明知其原，睹其應，而知五藏之害矣。

* 陽中之少陰，肺也，其原出於太淵，太淵二。
* 陽中之太陽，心也，其原出於大陵，大陵二。
* 陰中之少陽，肝也，其原出於太沖，太沖二。
* 陰中之至陰，脾也，其原出於太白，太白二。
* 陰中之太陰，腎也，其原出於太溪，太溪二。
* 膏之原，出於鳩尾，鳩尾一。
* 肓之原，出於脖胦，脖胦一。

凡此十二原者，主治五藏六府之有疾者也。

== 奇經八脈

=== 任脈

任脈者，起於中極之下，以上毛際循腹裏上關元至咽喉，上頤循面入目。

沖脈任脈皆起於胞中，上循背裏，為經絡之海，其浮而外者，循腹右上行，會於咽喉，別而
絡唇口，血氣盛則充膚熱肉，血獨盛者澹滲皮膚，生毫毛。今婦人之生有餘於氣，不足於血
以其數脫血也，沖任之脈，不榮口唇，故鬚不生焉。

任脈為病，男子內結七疝，女子帶下瘕聚。

缺盆之中，任脈也，名曰天突。

任脈之別，名曰尾翳。下鳩尾，散於腹。實則腹皮痛，虛則痒搔。取之所別也。

=== 督脈

督脈者，起於少腹以下骨中央，女子入繫廷孔，其孔，溺孔之端也，其絡循陰器合篡閒繞篡
後，別繞臀至少陰，與巨陽中絡者合，少陰上股內後廉，貫脊屬腎，與太陽起於目內眥，上
額交巔，上入絡腦，還出別下項循肩髆，內俠脊抵腰中入循膂絡腎。其男子循莖下至篡，與
女子等。其少腹直上者貫齊中央，上貫心入喉，上頤環脣，上繫兩目之下中央。

足厥陰…其支別者，上額，循巔，下項中，循脊入骶，是督脈也；

督脈之別，名曰長強。挾膂上項，散頭上，下當肩胛左右，別走太陽，入貫膂。實則脊強，
虛則頭重，高搖之，挾脊之有過者。取之所別也。

督脈為病，脊強反折。

此生病從少腹上衝心，而痛不得前後，為衝疝，其女子不孕，癃痔遺溺嗌乾。督脈生病治督
脈，治在骨上，甚者在齊下營，其上氣有音者，治其喉，中央在缺盆中者，其病上衝喉者治
其漸，漸者上俠頤也。

七次脈，頸中央之脈，督脈也，名曰風府。

督脈氣所發者二十八穴；項中央二，髮際後中八，面中三，大椎以下至尻尾及傍十五穴，至
骶下凡二十一節，脊椎法也。

陽明者，五藏六府之海，主閏宗筋，宗筋主束骨而利機關也。衝脈者經脈之海也，主滲灌谿
谷，與陽明合於宗筋，陰陽揔宗筋之會，會於氣街，而陽明為之長，皆屬於帶脈，而絡於督
脈。

=== 衝脈

黃帝曰：足少陰何因而動？歧伯曰：沖脈者，十二經之海也，與少陰之大絡，起於腎下，出
於氣街，循陰股內廉，邪入膕中，循脛骨內廉，并少陰之經，下入內踝之後。入足下，其別
者，邪入踝，出屬附上，入大指之間，注諸絡，以溫足脛，此脈之常動者也。

衝脈起於關元，隨腹直上，

衝脈者，起於氣街，並少陰之經，俠齊上行，至胸中而散。

沖脈任脈皆起於胞中，上循背裏，為經絡之海，其浮而外者，循腹右上行，會於咽喉，別而
絡唇口，血氣盛則充膚熱肉，血獨盛者澹滲皮膚，生毫毛。今婦人之生有餘於氣，不足於血
以其數脫血也，沖任之脈，不榮口唇，故鬚不生焉。

歧伯曰︰不然，夫衝脈者，五藏六府之海也，五藏六府皆稟焉。其上者，出於頏顙。滲諸陽，
灌諸精。其下者，注少陰之大絡，出於氣街，循陰股內廉，入膕中，伏行鴬骨內，下至內踝
之後屬而別。其下者，並於少陰之經，滲三陰，其前者，伏行出跗屬，下循跗，入大指間，
滲諸絡而溫肌肉。故別絡結則跗上不動，不動則厥，厥則寒矣。

=== 帶脈

足少陰之正，至膕中，別走太陽而合，上至腎，當十四椎出屬帶脈；

陽明者，五藏六府之海，主閏宗筋，宗筋主束骨而利機關也。衝脈者經脈之海也，主滲灌谿
谷，與陽明合於宗筋，陰陽揔宗筋之會，會於氣街，而陽明為之長，皆屬於帶脈，而絡於督
脈。

《難經‧二十八難》：「帶脈者，起于季脇，回身一週。」

=== 蹻脈

足太陽有通項入于腦者正屬目本，名曰眼系。…在項中兩筋間，入腦乃別陰蹻、陽蹻，陰陽
相交…交于目銳眥。

《難經‧二十八難》：「陽蹻脈者，起于跟中，循外踝上行，入風池。」

（陰）蹻脈者，少陰之別，起於然骨之後。上內踝之上，直上循陰股，入陰，上循胸裏，入
缺盆，上出人迎之前，入頄，屬目內眥，合於太陽、陽蹻而上行，氣并相還，則為濡，目氣
不榮，則目不合。

《難經‧二十八難》：「陰蹻脈者，亦起于跟中，循內踝上行，至咽喉，交貫衝脈。」

=== 維脈

陽維之脈，脈與太陽合臑上間，去地一尺所。

《難經‧二十難》「陽維起于諸陽會也。」

刺飛陽之脈，在內踝上五寸，少陰之前，與陰維之會。

《難經‧二十八難》：「陰維起于諸陰交也。」

== 十二經筋

**足太陽之筋**，起於足小趾，上結于踝，邪上結于膝，其下循足外側，結于踵，上循跟，
結於膕；其別者，結于腨外，上膕中內廉，與膕中并上結于臀，上挾脊上項；其支者，別入
結于舌本；其直者，結于枕骨，上頭，下顏，結于鼻；其支者，為目上網，下結于頄；其支
者，從腋后外廉結于肩髃；其支者，入腋下，上出缺盆，上結於完骨；其支者，出缺盆，邪
上出于頄。其病小趾支跟腫痛，膕攣，脊反折，項筋急，肩不舉，腋支缺盆中紐痛，不可左
右搖。治在燔鍼劫刺，以知為數，以痛為輸，名曰仲春痺也。

**足少陽之筋**，起於小指次指，上結外踝，上循脛外廉，結於膝外廉；其支者，別起外輔
骨，上走髀，前者結於伏兔之上，後者，結於尻；其直者，上乘䏚季脅，上走腋前廉，繫於
膺乳，結於缺盆；直者，上出腋，貫缺盆，出太陽之前，循耳後，上額角，交巔上，下走頷，
上結於頄；支者，結於目眥為外維。其病小指次指支轉筋，引膝外轉筋，膝不可屈伸，膕筋
急，前引髀，後引尻，即上乘䏚季脅痛，上引缺盆、膺乳、頸維筋急。從左之右，右目不開，
上過右角，并蹻脈而行，左絡於右，故傷左角，右足不用，命曰維筋相交。治在燔鍼劫刺，
以知為數，以痛為輸，名曰孟春痺也。

**足陽明之筋**，起於中三指，結於跗上，邪外上加於輔骨，上結於膝外廉，直上結於髀樞，
上循脅屬脊；其直者，上循骭，結於膝；其支者，結於外輔骨，合少陽；其直者，上循伏兔，
上結於髀，聚於陰器，上腹而布，至缺盆而結，上頸，上挾口，合于頄，下結於鼻，上合於
太陽。太陽為目上網，陽明為目下網；其支者，從頰結於耳前。其病足中指支脛轉筋，腳跳
堅，伏兔轉筋，髀前踵，㿉疝，腹筋急，引缺盆及頰，卒口僻；急者，目不合，熱則筋縱，
目不開，頰筋有寒，則急，引頰移口，有熱則筋弛縱，緩不勝收，故僻。治之以馬膏，膏其
急者；以白酒和桂，以塗其緩者，以桑鉤鉤之，即以生桑炭置之坎中，高下以坐等。以膏熨
急頰，且飲美酒，敢美炙肉，不飲酒者，自強也，為之三拊而已。治在燔鍼劫刺，以知為數，
以痛為輸，名曰季春痺也。

**足太陰之筋**，起於大指之端內側，上結於內踝；其直者，絡於膝內輔骨，上循陰股，結
於髀，聚於陰器，上腹結於臍，循腹裏，結於肋，散於胸中；其內者，著於脊。其病足大指
支內踝痛，轉筋痛，膝內輔骨痛，陰股引髀而痛，陰器紐痛，上引臍兩脅痛，引膺中脊內痛。
治在燔鍼劫刺，以知為數，以痛為輸，命曰孟秋痺也。

**足少陰之筋**，起於小指之下，并足太陰之筋，邪走內踝之下，結於踵，與太陽之筋合，
而上結於內輔之下，并太陰之筋，而上循陰股，結於陰器，循脊內挾膂上至項，結於枕骨，
與足太陽之筋合。其病足下轉筋，及所過而結者皆痛及轉筋。病在此者，主癎瘈及痙，在外
者不能挽，在內者不能仰。故陽病者，腰反折不能俛，陰病者，不能仰。治在燔鍼劫刺，以
知為數，以痛為輸。在內者熨引飲藥，此筋折紐，紐發數甚者死不治，名曰仲秋痺也。

**足厥陰之筋**，起於大指之上，上結於內踝之前，上循脛，上結內輔之下，上循陰股，結
於陰器，絡諸筋。其病足大指支內踝之前痛，內輔痛，陰股痛轉筋，陰器不用，傷於內則不
起，傷於寒則陰縮入，傷於熱則縱挺不收，治在行水清陰氣；其病轉筋者，治在燔鍼劫刺，
以知為數，以痛為輸，命曰季秋痺也。

**手太陽之筋**，起於小指之上，結於腕，上循臂內廉，結於肘內銳骨之後，彈之應小指之
上，入結於腋下；其支者，後走腋後廉，上繞肩胛，循頸出走太陽之前，結於耳後完骨；其
支者，入耳中；直者，出耳上，下結於頷，上屬目外眥。其病小指支肘內銳骨後廉痛，循臂
陰，入腋下，腋下痛，腋後廉痛，繞肩胛引頸而痛，應耳中鳴痛引頷，目瞑良久乃得視，頸
筋急，則為筋瘻頸腫，寒熱在頸者。治在燔鍼劫刺之，以知為數，以痛為輸。其為腫者，復
而銳之。本支者，上曲牙，循耳前屬目外眥，上頷結於角，其痛當所過者支轉筋。治在燔鍼
劫刺，以知為數，以痛為輸，名曰仲夏痺也。

**手少陽之筋**，起於小指次指之端，結於腕，中循臂，結於肘，上繞臑外廉、上肩、走頸，
合手太陽；其支者，當曲頰入繫舌本；其支者，上曲牙，循耳前，屬目外眥，上乘頷，結於
角。其病當所過者，即支轉筋，舌卷。治在燔鍼劫刺，以知為數，以痛為輸，名曰季夏痺也。

**手陽明之筋**，起於大指次指之端，結於腕，上循臂，上結於肘外，上臑，結於髃；其支
者，繞肩胛，挾脊；直者，從肩髃上頸；其支者，上頰，結於頄；直者，上出手太陽之前，
上左角，絡頭，下右頷。其病當所過者，支痛及轉筋，肩不舉，頸不可左右視。治在燔鍼劫
刺，以知為數，以痛為輸，名曰孟夏痺也。

**手太陰之筋**，起於大指之上，循指上行，結於魚後，行寸口外側，上循臂，結肘中，上
臑內廉，入腋下，出缺盆，結肩前髃，上結缺盆，下結胸裏，散貫賁，合賁下抵季脅。其病
當所過者，支轉筋，痛甚成息賁，脅急吐血。治在燔鍼劫刺，以知為數，以痛為輸。名曰仲
冬痺也。

**手心主之筋**，起於中指，與太陰之筋並行，結於肘內廉，上臂陰，結腋下，下散前後挾
脅；其支者，入腋，散胸中，結於臂。其病當所過者，支轉筋前及胸痛息賁。治在燔鍼劫刺，
以知為數，以痛為輸，名曰孟冬痺也。

**手少陰之筋**，起於小指之內側，結於銳骨，上結肘內廉，上入腋，交太陰，挾乳裏，結
於胸中，循臂下繫於臍。其病內急心承伏梁，下為肘網。其病當所過者，支轉筋，筋痛。治
在燔鍼劫刺，以知為數，以痛為輸。其成伏梁唾血膿者，死不治。經筋之病，寒則反折筋急，
熱則筋弛縱不收，陰痿不用。陽急則反折，陰急則俛不伸。焠刺者，刺寒急也，熱則筋縱不
收，無用燔鍼，名曰季冬痺也。

足之陽明，手之太陽，筋急則口目為僻，眥急不能卒視，治皆如右方也。

== 十二經別

**足太陽之正**，別入于膕中，其一道下尻五寸，別入于肛，屬於膀胱，散之腎，循膂，當
心入散；直者，從膂上出於項，復屬於太陽，此為一經也。**足少陰之正**，至膕中，別走
太陽而合，上至腎，當十四椎出屬帶脈；直者，系舌本，復出於項，合於太陽，此為一合。
成以諸陰之別，皆為正也。

**足少陽之正**，繞髀入毛際，合於厥陰，別者入季脅之間，循胸裏屬膽，散之上肝，貫心
以上挾咽，出頤頜中，散於面，繫目系，合少陽於外眥也。**足厥陰之正**，別跗上，上至
毛際，合於少陽，與別俱行，此為二合也。

**足陽明之正**，上至脾，入于腹裏屬胃，散之脾，上通於心，上循咽出於口，上頞䪼，還
繫目系，合於陽明也。**足太陰之正**，上至髀，合於陽明，與別俱行，上結於咽，貫舌中，
此為三合也。

**手太陽之正**，指地，別於肩解，入腋走心，系小腸也。**手少陰之正**，別入于淵腋兩
筋之間，屬於心，上走喉嚨，出於面，合目內眥，此為四合也。

**手少陽之正**，指天，別於巔，入缺盆，下走三焦，散於胸中也。**手心主之正**，別下
淵腋三寸，入胸中，別屬三焦，出循喉嚨，出耳後，合少陽完骨之下，此為五合也。

**手陽明之正**，從手循膺乳，別於肩髃，入柱骨，下走大腸，屬於肺，上循喉嚨，出缺盆，
合於陽明也。**手太陰之正**，別入淵腋少陰之前，入走肺，散之大陽，上出缺盆，循喉嚨，
復合陽明，此六合也。

== 十五大絡

* **手太陰之別**，名曰列缺。起於腕上分間，并太陰之經，直入掌中，散入于魚際。其病
實則手銳掌熱；虛則欠㰦，小便遺數。取之去腕寸半。別走陽明也。
* **手少陰之別**，名曰通裏。去腕一寸半，別而上行，循經入于心中，系舌本，屬目系。
其實則支膈，虛則不能言。取之掌後一寸，別走太陽也。
* **手心主之別**，名曰內關。去腕二寸，出於兩筋之間，循經以上，系於心包絡。心系實
則心痛，虛則為頭強。取之兩筋間也。
* **手太陽之別**，名曰支正。上腕五寸，內注少陰；其別者，上走肘，絡肩髃。實則節弛
肘廢；虛則生肬，小者如指痂疥。取之所別也。
* **手陽明之別**，名曰偏歷。去腕三寸，別入太陰；其別者，上循臂，乘肩髃，上曲頰傷
齒；其別者，入耳，合於宗脈。實則齲聾；虛則齒寒痺隔。取之所別也。
* **手少陽之別**，名曰外關。去腕二寸，外繞臂，注胸中，合心主。病實則肘攣，虛則不
收。取之所別也。
* **足太陽之別**，名曰飛揚。去踝七寸，別走少陰。實則鼽窒，頭背痛；虛則鼽衄。取之
所別也。
* **足少陽之別**，名曰光明，去踝五寸，別走厥陰，下絡足跗。實則厥，虛則痿躄，坐不
能起。取之所別也。
* **足陽明之別**，名曰豐隆。去踝八寸。別走太陰；其別者，循脛骨外廉，上絡頭項，合
諸經之氣，下絡喉嗌。其病氣逆則喉痺瘁瘖。實則狂巔，虛則足不收，脛枯。取之所別也。
* **足太陰之別**，名曰公孫。去本節之後一寸，別走陽明；其別者，入絡腸胃，厥氣上逆
則霍亂，實則腸中切痛；虛則鼓脹。取之所別也。
* **足少陰之別**，名曰大鍾。當踝後繞跟，別走太陽；其別者，并經上走於心包下，外貫
腰脊。其病氣逆則煩悶，實則閉癃，虛則腰痛。取之所別者也。
* **足厥陰之別**，名曰蠡溝。去內踝五寸，別走少陽；其別者，經脛上睪，結於莖。其病
氣逆則睪腫卒疝。實則挺長，虛則暴癢。取之所別也。
* **任脈之別**，名曰尾翳。下鳩尾，散於腹。實則腹皮痛，虛則痒搔。取之所別也。
* **督脈之別**，名曰長強。挾膂上項，散頭上，下當肩胛左右，別走太陽，入貫膂。實則
脊強，虛則頭重，高搖之，挾脊之有過者。取之所別也。
* **脾之大絡**，名曰大包。出淵腋下三寸，布胸脅。實則身盡痛，虛則百節盡皆縱。此脈
若罷絡之血者，皆取之脾之大絡脈也。
* **胃之大絡**，名曰虛里，貫鬲絡肺，出於左乳下，其動應衣，脈宗氣也。盛喘數絕者，
則病在中；結而橫，有積矣；絕不至曰死。乳之下其動應衣，宗氣泄也。

== 五輸

肺出於少商，少商者，手大指端內側也，為井木；溜于魚際，魚際者，手魚也，為滎；注于
太淵，太淵魚後一寸陷者中也，為俞；行於經渠，經渠寸口中也，動而不居為經；入于尺澤，
尺澤肘中之動脈也，為合。手太陰經也。

心出於中沖，中沖，手中指之端也，為井木；流於勞宮，勞宮掌中中指本節之內間也，為滎；
注于大陵，大陵掌後兩骨之間方下者也，為俞；行於間使，間使之道，兩筋之間，三寸之中
也，有過則至，無過則止，為經；入于曲澤，曲澤，肘內廉下陷者之中也，屈而得之，為合。
手少陰也。

肝出于大敦，大敦者，足大趾之端，及三毛之中也，為井木；溜于行間，行間足大趾間也，
為滎；注于太沖，太沖行間上二寸陷者之中也，為俞；行于中封，中封內踝之前一寸半，陷
者之中，使逆則宛，使和則通，搖足而得之，為經；入于曲泉，曲泉輔骨之下，大筋之上也，
屈膝而得之，為合。足厥陰也。

脾出于隱白，隱白者，足大趾之端內側也，為井木；溜于大都，大都本節之後下陷者之中也，
為滎；注于太白，太白腕骨之下也，為俞；行于商丘，商丘內踝之下陷者之中也，為經；入
于陰之陵泉，陰之陵泉，輔骨之下陷者之中也，伸而得之，為合。足太陰也。

腎出于湧泉，湧泉者足心也，為井木；溜于然谷，然谷，然骨之下者也，為滎；注于太溪，
太溪內踝之後跟骨之上陷中者也，為俞；行于復溜，復溜，上內踝二寸，動而不休，為經；
入于陰谷，陰谷，輔骨之後，大筋之下，小筋之上也，按之應手，屈膝而得之，為合。足少
陰經也。

膀胱出于至陰，至陰者，足小趾之端也，為井金；溜于通谷，通谷，本節之前外側也，為滎；
注于束骨，束骨，本節之後陷者中也，為俞；過于京骨，京骨，足外側大骨之下，為原；行
于昆侖，昆侖，在外踝之後，跟骨之上，為經；入于委中，委中，膕中央，為合，委而取之。
足太陽也。

膽出于竅陰，竅陰者，足小趾次趾之端也，為井金；溜于俠溪，俠溪，足小趾次趾之間也，
為滎；注于臨泣，臨泣，上行一寸半，陷者中也，為俞；過于丘墟，丘墟，外踝之前下陷者
中也，為原。行于陽輔，陽輔外踝之上輔骨之前及絕骨之端也，為經；入于陽之陵泉，陽之
陵泉，在膝外陷者中也，為合，伸而得之。足少陽也。

胃出于厲兌，厲兌者，足大趾內次趾之端也，為井金；溜于內庭，內庭，次趾外間也，為滎；
注于陷谷，陷谷者，上中指內間上行二寸陷者中也，為俞；過于沖陽，沖陽，足跗上五寸陷
者中也，為原，搖足而得之；行于解溪，解溪，上沖陽一寸半陷者中也，為經；入于下陵，
下陵，膝下三寸胻骨外三里也，為合；復下三里三寸，為巨虛上廉，復下上廉三寸，為巨虛
下廉也；大腸屬上，小腸屬下，足陽明胃脈也。大腸小腸，皆屬于胃，是足陽明也。

三焦者，上合手少陽，出于關衝，關衝者，手小指次指之端也，為井金；溜于液門，液門，
小指次指之間也，為滎；注于中渚，中渚，本節之後陷者中也，為俞；過于陽池，陽池，在
腕上陷者之中也，為原；行于支溝，支溝，上腕三寸兩骨之間陷者中也，為經；入于天井，
天井，在肘外大骨之上陷者中也，為合，屈肘而得之；三焦下腧在於足大趾之前，少陽之後，
出于膕中外廉，名曰委陽，是太陽絡也，手少陽經也。三焦者，足少陽太陰之所將太陽之別
也，上踝五寸，別入貫腨腸，出于委陽，並太陽之正，入絡膀胱，約下焦，實則閉癃，虛則
遺溺，遺溺則補之，閉癃則寫之。

手太陽小腸者，上合手太陽，出于少澤，少澤，小指之端也，為井金；溜于前谷，前谷，在
手外廉本節前陷者中也，為滎；注于後溪，後溪者，在手外側本節之後也，為俞；過于腕骨，
腕骨，在手外側腕骨之前，為原；行于陽谷，陽谷，在銳骨之下陷者中也，為經；入于小海，
小海，在肘內大骨之外，去端半寸，陷者中也，伸臂而得之，為合。手太陽經也。

大腸上合手陽明，出于商陽，商陽，大指次指之端也，為井金；溜于本節之前二間，為滎；
注于本節之後三間，為俞；過于合谷，合谷，在大指岐骨之間，為原；行于陽溪，陽溪，在
兩筋間陷者中也，為經；入于曲池，在肘外輔骨陷者中，屈臂而得之，為合。手陽明也。

== 標本根結

* 足太陽之本，在跟以上五寸中，標在兩絡命門。命門者，目也。
* 足少陽之本，在竅陰之間，標在窗籠之前。窗籠者，耳也。
* 足少陰之本，在內踝下上三寸中，標在背輸與舌下兩脈也。
* 足厥陰之本，在行間上五寸所，標在背腧也。
* 足陽明之本，在厲兌，標在人迎，頰挾頏顙也。
* 足太陰之本，在中封前上四寸之中，標在背腧與舌本也。
* 手太陽之本，在外踝之後，標在命門之上一寸也。
* 手少陽之本，在小指次指之間上二寸，標在耳後上角下外眥也。
* 手陽明之本，在肘骨中，上至別陽，標在顏下合鉗上也。
* 手太陰之本，在寸口之中，標在腋內動也。
* 手少陰之本，在銳骨之端，標在背腧也。
* 手心主之本，在掌後兩筋之間二寸中，標在腋下下三寸也。

//

* 太陽根于至陰，結于命門。命門者，目也。
* 陽明根于厲兌，結于顙大。顙大者，鉗耳也。
* 少陽根于竅陰，結于窗籠。窗籠者，耳中也。
* 太陰根于隱白，結于太倉。
* 少陰根于湧泉，結于廉泉。
* 厥陰根于大敦，結于玉英，絡于膻中。

//

* 足太陽根于至陰，溜于京骨，注于昆侖，入于天柱、飛揚也。
* 足少陽根于竅陰，溜于丘墟，注于陽輔，入于天容、光明也。
* 足陽明根于厲兌，溜于沖陽，注于下陵，入于人迎，豐隆也。
* 手太陽根于少澤，溜于陽谷，注于小海，入于天窗，支正也。
* 手少陽根于關沖，溜于陽池，注于支溝，入于天牖、外關也。
* 手陽明根于商陽，溜于合谷，注于陽谿，入于扶突、偏歷也。

== 病理

故天之邪氣，感則害人五藏；水穀之寒熱，感則害於六府；地之濕氣，感則害皮肉筋脈。

== 真氣

真氣者，所受於天，與穀氣并而充身也。

正氣者，正風也，從一方來，非實風，又非虛風也。邪氣者，虛風之賊傷人也，其中人也深，
不能自去。正風者，其中人也淺，合而自去，其氣來柔弱，不能勝真氣，故自去。

== 穀

黃帝問于歧伯曰：人焉受氣？陰陽焉會？何氣為營？何氣為衛？營安從生？衛于焉會？老壯
不同氣，陰陽異位，願聞其會。歧伯答曰：人受氣于穀，穀入于胃，以傳與肺，五藏六府，
皆以受氣，其清者為營，濁者為衛，營在脈中，衛在脈外，營週不休，五十而復大會，陰陽
相貫，如環無端，衛氣行于陰二十五度，行于陽二十五度，分為晝夜，故氣至陽而起，至陰
而止。故曰日中而陽隴，為重陽，夜半而陰隴為重陰，故太陰主內，太陽主外，各行二十五
度分為晝夜。夜半為陰隴，夜半後而為陰衰，平旦陰盡而陽受氣矣。日中而陽隴，日西而陽
衰，日入陽盡而陰受氣矣。夜半而大會，萬民皆臥，命曰合陰，平旦陰盡而陽受氣，如是無
已，與天地同紀。

五穀入于胃也，其糟粕津液宗氣，分為三隧。故宗氣積於胸中，出於喉嚨，以貫心脈，而行
呼吸焉。營氣者，泌其津液，注之於脈，化以為血，以榮四末，內注五藏六府，以應刻數焉。
節氣者，出其悍氣之慓疾，而先行於四末分肉皮膚之間，而不休者也。

黃帝曰：余聞腸胃受穀，上焦出氣，以溫分肉，而養骨節，通腠理。中焦出氣如露，上注谿
谷，而滲孫脈，津液和調，變化而赤為血。血和則孫脈先滿溢，乃注于絡脈，皆盈，乃注于
經脈，陰陽已張，因息乃行。

黃帝曰：願聞營衛之所行，皆何道從來？歧伯答曰：營出于中焦，衛出于下焦。黃帝曰：願
聞三焦之所出。歧伯答曰：上焦出於胃上口，並咽以上，貫膈，而布胸中，走腋，循太陰之
分而行，還至陽明，上至舌，下足陽明，常與營俱行于陽二十五度，行于陰亦二十五度一周
也。故五十度而復太會于手太陰矣。

黃帝曰：願聞中焦之所出。歧伯答曰：中焦亦並胃中，出上焦之後，此所受氣者，泌糟粕，
蒸津液，化其精微，上注于肺脈乃化而為血，以奉生身，莫貴於此，故獨得行於經隧，命曰
營氣。

黃帝曰：願聞下焦之所出。歧伯答曰：下焦者，別回腸，注于膀胱，而滲入焉；故水穀者，
常并居于胃中，成糟粕，而俱下于大腸而成下焦，滲而俱下。濟泌別汁，循下焦而滲入膀胱
焉。

帝曰：脾與胃以膜相連耳，而能為之行其津液，何也。歧伯曰：足太陰者三陰也，其脈貫胃
屬脾絡嗌，故太陰為之行氣於三陰。陽明者，表也，五藏六府之海也，亦為之行氣於三陽。
藏府各因其經而受氣於陽明，故為胃行其津液。四支不得稟水穀氣，日以益衰，陰道不利，
筋骨肌肉無氣以生，故不用焉。

帝曰：榮衛之氣，亦令人痺乎。歧伯曰：榮者水穀之精氣也，和調於五藏，灑陳於六府，乃
能入於脈也；故循脈上下，貫五藏絡六府也。衛者水穀之悍氣也，其氣慓疾滑利，不能入於
脈也；故循皮膚之中，分肉之閒，熏於肓膜，散於胸腹，逆其氣則病，從其氣則愈。

言水穀皆入于胃，其精氣上注于肺，濁溜于腸胃，

黃帝曰：余聞人有精、氣、津、液、血、脈，余意以為一氣耳，今乃辨為六名，余不知其所
以然。歧伯曰：兩神相搏，合而成形，常先身生，是謂精。何謂氣？歧伯曰：上焦開發，宣
五穀味，熏膚、充身、澤毛，若霧露之溉，是謂氣。何謂津？歧伯曰：腠理發泄，汗出溱溱，
是謂津。何謂液？歧伯曰：穀入氣滿，淖澤注于骨，骨屬屈伸，泄澤補益腦髓，皮膚潤澤，
是謂液。何謂血？歧伯曰：中焦受氣，取汁變化而赤，是謂血。何謂脈？歧伯曰：壅遏營氣，
令無所避，是謂脈。

水穀皆入于口，其味有五，各注其海。津液各走其道，故三焦出氣，以溫肌肉，充皮膚，為
其津，其流而不行者為液。

五穀之津液，和合而為膏者，內滲入于骨空，補益腦髓，而下流於陰股。

黃帝曰：願聞人氣之清濁。歧伯曰：受穀者濁，受氣者清。清者注陰，濁者注陽。濁而清者，
上出於咽，清而濁者，則下行。

黃帝曰：夫陰清而陽濁，濁者有清，清者有濁，清濁別之奈何？歧伯曰：氣之大別，清者上
注于肺，濁者下走于胃。胃之清氣，上出于口；肺之濁氣，下注于經，內積于海。

黃帝曰：諸陽皆濁，何陽濁甚乎？歧伯曰：手太陽獨受陽之濁，手太陰獨受陰之清；其清者
上走空竅，其濁者下行諸經。諸陰皆清，足太陰獨受其濁。

黃帝曰：治之奈何？歧伯曰：清者其氣滑，濁者其氣澀，此氣之常也。故刺陰者，深而留之；
刺陽者，淺而疾之；清濁相干者，以數調之也。

五藏者，所以藏精神血氣魂魄者也；六府者，所以化水穀而行津液者也。

黃帝曰：營衛之行奈何？伯高曰：穀始入于胃，其精微者，先出於胃之兩焦，以溉五藏，別
出兩行，營衛之道。其大氣之搏而不行者，積於胸中，命曰氣海，出於肺，循咽喉，故呼則
出，吸則入。天地之精氣，其大數常出三入一，故穀不入，半日則氣衰，一日則氣少矣。

== 衛氣

衛氣者，所以溫分肉，充皮膚，肥腠理，司開闔者也；

衛氣和則分肉解利，皮膚調柔，腠理致密矣；

其浮氣之不循經者，為衛氣；

衛氣者，出其悍氣之慓疾，而先行於四末分肉皮膚之間，而不休者也。晝日行於陽，夜行於
陰，常從足少陰之分間，行於五藏六府，

水氣舍於皮膚之內，與衛氣并居。衛氣者，晝日行於陽，夜行於陰，此氣得陽而外出，得陰
而內薄，內外相薄，是以日作。

衛氣有所凝而不行，故其肉有不仁也。

其不痛不仁者，病久入深，榮衛之行濇，經絡時踈，故不通，皮膚不營，故為不仁。

衛氣不行，則為不仁。

衛者水穀之悍氣也，其氣慓疾滑利，不能入於脈也；故循皮膚之中，分肉之閒，熏於肓膜，
散於胸腹，逆其氣則病，從其氣則愈。

陽受氣於上焦，以溫皮膚分肉之閒。

上焦不通利，則皮膚緻密腠理閉塞，玄府不通，衛氣不得泄越，故外熱。

衛氣之在身也，常然並脈，循分肉，行有逆順，陰陽相隨，乃得天和，五藏更始，四時循序，
五穀乃化。

黃帝曰：足之陽明，何因而動？歧伯曰：胃氣上注于肺，其悍氣上沖頭者，循咽，上走空竅，
循眼系，入絡腦，出顑，下客主人，循牙車，合陽明，并下人迎，此胃氣別走於陽明者也。
故陰陽上下，其動也若一。

黃帝問於歧伯曰：願聞衛氣之行，出入之合，何如？歧伯曰：歲有十二月，日有十二辰，子
午為經，卯酉為緯。天周二十八宿，而一面七星，四七二十八星。房昴為緯，虛張為經。是
故房至畢為陽，昴至心為陰。陽主晝，陰主夜。故衛氣之行，一日一夜五十周於身，晝日行
於陽二十五周，夜行於陰二十五周，周於五藏。

是故平旦陰盡，陽氣出於目，目張則氣上行於頭，循項下足太陽，循背下至小趾之端。其散
者，別於目銳眥，下手太陽，下至手小指之間外側。其散者，別於目銳眥，下足少陽，注小
趾次趾之間。以上循手少陽之分側，下至小指之間。別者以上至耳前，合於頷脈，注足陽明
以下行，至跗上，入五趾之間。其散者，從耳下下手陽明，入大指之間，入掌中。其至於足
也，入足心，出內踝，下行陰分，復合於目，故為一周。

== 營氣

黃帝曰：願聞中焦之所出。歧伯答曰：中焦亦並胃中，出上焦之後，此所受氣者，泌糟粕，
蒸津液，化其精微，上注于肺脈乃化而為血，以奉生身，莫貴於此，故獨得行於經隧，命曰
營氣。

其精氣之行於經者，為營氣。

黃帝曰：營氣之道，內穀為寶。穀入于胃，乃傳之肺，流溢於中，布散於外，精專者，行於
經隧，常營無已，終而復始，是謂天地之紀。

皮膚之內，腸胃之外，此榮氣之所舍也。

* 故氣從太陰出注手陽明，上行注足陽明，下行至跗上，注大指間，與太陰合；
* 上行抵髀，從脾注心中；
* 循手少陰，出腋下臂，注小指，合手太陽；
* 上行乘腋，出䪼內，注目內眥，上巔，下項，合足太陽；
* 循脊，下尻，下行注小指之端，循足心，注足少陰；
* 上行注腎，從腎注心外，散於胸中；
* 循心主脈，出腋，下臂，出兩筋之間，入掌中，出中指之端，還注小指次指之端，合手少
陽；
* 上行注膻中，散於三焦，從三焦注膽，出脅，注足少陽；
* 下行至跗上，復從跗注大指間，合足厥陰；
* 上行至肝，從肝上注肺，上循喉嚨，入頏顙之竅，究於畜門。
* 其支別者，上額，循巔，下項中，循脊入骶，是督脈也；
* 絡陰器，上過毛中，入臍中，上循腹裏，入缺盆，下注肺中，復出太陰。

此營氣之所行也，逆順之常也。

== 十二官

* 心者，君主之官也，神明出焉。
* 肺者，相傅之官，治節出焉。
* 肝者，將軍之官，謀慮出焉。
* 膽者，中正之官，決斷出焉。
* 膻中者，臣使之官，喜樂出焉。
* 脾胃者，倉廩之官，五味出焉。
* 大腸者，傳道之官，變化出焉。
* 小腸者，受盛之官，化物出焉。
* 腎者，作強之官，伎巧出焉。
* 三焦者，決瀆之官，水道出焉。
* 膀胱者，州都之官，津液藏焉，氣化則能出矣。

== 皮部

黃帝問曰：余聞皮有分部，脈有經紀，筋有結絡，骨有度量，其所生病各異，別其分部左右
上下陰陽所在病之始終，願聞其道。歧伯對曰：欲知皮部以經脈為紀者，諸經皆然。

* 陽明之陽，名曰害蜚，上下同法，視其部中有浮絡者，皆陽明之絡也，其色多青則痛，多
黑則痺，黃赤則熱，多白則寒，五色皆見，則寒熱也，絡盛則入客於經，陽主外，陰主內。
* 少陽之陽，名曰樞持，上下同法，視其部中有浮絡者，皆少陽之絡也，絡盛則入客於經，
故在陽者主內，在陰者主出以滲於內，諸經皆然。
* 太陽之陽，名曰關樞，上下同法，視其部中有浮絡者，皆太陽之絡也，絡盛則入客於經。
* 少陰之陰，名曰樞儒，上下同法，視其部中有浮絡者，皆少陰之絡也，絡盛則入客於經，
其入經也，從陽部注於經，其出者，從陰內注於骨。
* 心主之陰，名曰害肩，上下同法，視其部中有浮絡者，皆心主之絡也，絡盛則入客於經。
* 太陰之陰，名曰關蟄，上下同法，視其部中有浮絡者，皆太陰之絡也，絡盛則入客於經。

凡十二經絡脈者皮之部也。

是故百病之始生也，必先於皮毛，邪中之則腠理開，開則入客於絡脈，留而不去，傳入於經，
留而不去，傳入於府，廩於腸胃。邪之始入於皮也，泝然起毫毛，開腠理。其入於絡也，則
絡脈盛色變。其入客於經也，則感虛乃陷下。其留於筋骨之間，寒多則筋攣骨痛，熱多則筋
弛骨消，肉爍䐃破，毛直而敗。帝曰：夫子言皮之十二部，其生病皆何如。歧伯曰：皮者，
脈之部也。邪客於皮則腠理開，開則邪入客於絡脈，絡脈滿則注於經脈，經脈滿則入舍於府
藏也，故皮者有分部，不與，而生大病也。帝曰：善。

黃帝曰：病形何如，取之奈何？伯高曰：夫百病變化，不可勝數，然皮有部，肉有柱，血氣
有輸，骨有屬。黃帝曰：願聞其故。伯高曰：皮之部，輸於四末；肉之柱，有臂脛諸陽分肉
之間，與足少陰分間；血氣之輸，輸於諸絡，氣血留居，則盛而起，筋部無陰無陽，無左無
右，候病所在；骨之屬者，骨空之所以受益而益腦髓者也。

== 九鍼

=== 九鍼形制

九鍼之名，各不同形。

* 一曰鑱鍼，長一寸六分；
* 二曰員鍼，長一寸六分；
* 三曰鍉鍼，長三寸半；
* 四曰鋒鍼，長一寸六分；
* 五曰鈹鍼，長四寸，廣二分半；
* 六曰員利鍼，長一寸六分；
* 七曰毫鍼，長三寸六分；
* 八曰長鍼，長七寸；九曰大鍼，長四寸。

//

* 鑱鍼者，頭大末銳，去寫陽氣；
* 員鍼者，鍼如卵形，揩摩分間，不得傷肌肉，以寫分氣；
* 鍉鍼者，鋒如黍粟之銳，主按脈勿陷，以致其氣；
* 鋒鍼者，刃三隅以發痼疾，鈹鍼者，末如劍鋒，以取大膿；
* 員利鍼者，大如釐，且員且銳，中身微大，以取暴氣；
* 毫鍼者，尖如蚊虻喙，靜以徐往，微以久留之而養，以取痛痺；
* 長鍼者，鋒利身薄，可以取遠痺；
* 大鍼者，尖如梃，其鋒微員，以寫機關之水也。

九鍼畢矣。

黃帝曰：鍼之長短有數乎？歧伯曰：

* 一曰鑱鍼者，取法於巾鍼，去末寸半，卒銳之，長一寸六分，主熱在頭身也。
* 二曰員鍼，取法於絮鍼，筩其身而卵其鋒，長一寸六分，主治分間氣。
* 三曰鍉鍼，取法於黍粟之銳，長三寸半，主按脈取氣，令邪出。
* 四曰鋒鍼，取法於絮鍼，筩其身，鋒其末，長一寸六分，主癰熱出血。
* 五曰鈹鍼，取法於劍鋒，廣二分半，長四寸，主大癰膿，兩熱爭者也。
* 六曰員利鍼，取法於釐鍼，微大其末，反小其身，令可深內也，長一寸六分。主取癰痺者
也。
* 七曰毫鍼，取注于毫毛，長一寸六分，主寒熱痛痺在絡者也。
* 八曰長鍼，取法於綦鍼，長七寸，主取深邪遠痺者也。
* 九曰大鍼，取法於鋒鍼，其鋒微員，長四寸，主取大氣不出關節者也。

鍼形畢矣，此九鍼大小長短法也。

=== 九鍼之治

* 病在皮膚無常處者，取以鑱鍼於病所，膚白勿取。
* 病在分肉間，取以圓鍼於病所。
* 病在經絡痼痺者，取以鋒鍼。
* 病在脈，氣少，當補之者，取以鍉鍼於井滎分俞。
* 病為大膿者，取以鈹鍼。病痺氣暴發者，取以圓利鍼。
* 病痺氣痛而不去者，取以毫鍼。
* 病在中者，取以長鍼。
* 病水腫不能通關節者，取以大鍼。
* 病在五藏固居者，取以鋒鍼，寫於井滎分俞，取以四時。

=== 九鍼之應

黃帝曰：余聞九鍼於夫子，眾多博大矣，余猶不能寤，敢問九鍼焉生，何因而有名？歧伯曰：
九鍼者，天地之大數也，始於一而終於九。故曰：一以法天，二以法地，三以法人，四以法
時，五以法音，六以法律，七以法星，八以法風，九以法野。

黃帝曰：以鍼應九之數，奈何？歧伯曰：夫聖人之起天地之數也，一而九之，故以立九野。
九而九之，九九八十一，以起黃鍾數焉，以鍼應數也。

* 一者，天也。天者，陽也。五藏之應天者肺，肺者，五藏六府之蓋也，皮者，肺之合也，
人之陽也。故為之治鍼，必以大其頭而銳其末，令無得深入而陽氣出。
* 二者，地也。人之所以應土者，肉也。故為之治鍼，必筩其身而員其末，令無得傷肉分，
傷則氣得竭。
* 三者，人也。人之所以成生者，血脈也。故為之治鍼，必大其身而員其末，令可以按脈物
陷，以致其氣，令邪氣獨出。
* 四者，時也。時者，四時八風之客於經絡之中，為瘤病者也。故為之治鍼，必筩其身而鋒
其末，令可以寫熱出血，而痼病竭。
* 五者，音也。音者，冬夏之分，分於子午，陰與陽別，寒與熱爭，兩氣相搏，合為癰膿者
也。故為之治鍼，必令其末如劍鋒，可以取大膿。
* 六者，律也。律者，調陰陽四時而合十二經脈，虛邪客於經絡而為暴痺者也。故為之治鍼，
必令尖如釐，且員其銳，中身微大，以取暴氣。
令尖如蚊虻喙，靜以徐往，微以久留，正氣因之，真邪俱往，出鍼而養者也。
* 八者，風也。風者，人之股肱八節也。八正之虛風，八風傷人，內舍於骨解腰脊節腠理之
間為深痺也。故為之治鍼，必長其身，鋒其末，可以取深邪遠痺。
* 九者，野也。野者，人之節解皮膚之間也。淫邪流溢於身，如風水之狀，而留不能過於機
關大節者也。故為之治鍼，令尖如挺，其鋒微員，以取大氣之不能過於關節者也。

= 刺法

=== 九刺

凡刺有九，以應九變。

* 一曰俞刺，俞刺者，刺諸經滎俞藏俞也；
* 二曰遠道刺，遠道刺者，病在上，取之下，刺府俞也；
* 三曰經刺，經刺者，刺大經之結絡經分也；
* 四曰絡刺，絡刺者，刺小絡之血脈也；
* 五曰分刺，分刺者，刺分肉之間也；
* 六曰大寫刺，大寫刺者，刺大膿以鈹鍼也；
* 七曰毛刺，毛刺者，刺浮痺皮膚也；
* 八曰巨刺，巨刺者，左取右，右取左；
* 九曰焠刺，焠刺者，刺燔鍼則取痺也。

=== 十二刺

凡刺有十二節，以應十二經。

* 一曰偶刺，偶刺者，以手直心若背，直痛所，一刺前，一刺後，以治心痺。刺此者，傍鍼
 之也。
* 二曰報刺，報刺者，刺痛無常處也。上下行者，直內無拔鍼，以左手隨病所按之，乃出鍼，
復刺之也。
* 三曰恢刺，恢刺者，直刺傍之，舉之前後，恢筋急，以治筋痺也。
* 四曰齊刺，齊刺者，直入一，傍入二，以治寒氣小深者；或曰三刺，三刺者，治痺氣小深
者也。
* 五曰揚刺，揚刺者，正內一，傍內四，而浮之，以治寒氣之搏大者也。
* 六曰直鍼刺，直鍼刺者，引皮乃刺之，以治寒氣之淺者也。
* 七曰輸鍼，輸刺者，直入直出，稀發鍼而深之，以治氣盛而熱者也。
* 八曰短刺，短刺者，刺骨痺，稍搖而深之，致鍼骨所，以上下摩骨也。
* 九曰浮刺，浮刺者，傍入而浮之，以治肌急而寒者也。
* 十曰陰刺，陰刺者，左右率刺之，以治寒厥；中寒厥，足踝後少陰也。
* 十一曰傍鍼刺，傍鍼刺者，直刺傍刺各一，以治留痺久居者也。
* 十二曰贊刺，贊刺者，直入直出，數發鍼而淺之，出血是謂治癰腫也。

=== 三刺

所謂三刺，則穀氣出者。先淺刺絕皮，以出陽邪，再刺則陰邪出者，少益深絕皮，致肌肉，
未入分肉間也；已入分肉之間，則穀氣出。故刺法曰：始刺淺之，以逐邪氣，而來血氣，後
刺深之，以致陰氣之邪，最後刺極深之，以下穀氣。此之謂也。

=== 五刺

凡刺有五，以應五藏。

* 一曰半刺，半刺者，淺內而疾發鍼，無鍼傷肉，如拔毛狀，以取皮氣，此肺之應也。
* 二曰豹文刺，豹文刺者，左右前後鍼之，中脈為故，以取經絡之血者，此心之應也。
* 三曰關刺，關刺者，直刺左右盡筋上，以取筋痺，慎無出血，此肝之應也；或曰淵刺；一
曰豈刺。
* 四曰合谷刺，合谷刺者，左右雞足，鍼於分肉之間，以取肌痺，此脾之應也。
* 五曰輸刺，輸刺者，直入直出，深內之至骨，以取骨痺，此腎之應也。

== 四關

手足關節

== 四海

黃帝問于歧伯曰：余聞刺法於夫子，夫子之所言，不離於營衛血氣。夫十二經脈者，內屬於
府藏，外絡於肢節，夫子乃合之於四海乎。歧伯答曰：人亦有四海，十二經水。經水者，皆
注于海，海有東西南北，命曰四海。黃帝曰：以人應之奈何？歧伯曰：人有髓海，有血海，
有氣海，有水榖之海，凡此四者，以應四海也。

黃帝曰：定之奈何？歧伯曰：胃者水穀之海，其輸上在氣街，下至三里；衝脈者，為十二經
之海，其輸上在於大杼，下出於巨虛之上下廉；膻中者，為氣之海，其輸上在於柱骨之上下，
前在於人迎，腦為髓之海，其輸上在於其蓋，下在風府。

黃帝曰：四海之逆順奈何？歧伯曰：氣海有餘者，氣滿胸中，悗息面赤；氣海不足，則氣少
不足以言。血海有餘，則常想其身大，怫然不知其所病；血海不足，亦常想其身小，狹然不
知其所病。水谷之海有餘，則腹滿；水榖之海不足，則飢不受榖食。髓海有餘，則輕勁多力，
自過其度；髓海不足，則腦轉耳鳴，脛痠眩冒，目無所見，懈怠安臥。

胃者水穀之海，六府之大源也。

陽明者，表也，五藏六府之海也，

陽明者，胃脈也，胃者六府之海，

陽明者，五藏六府之海，主閏宗筋，宗筋主束骨而利機關也。

足陽明，五藏六府之海也，其脈大，血多氣盛，熱壯，刺此者不深勿散，不留不寫也。

六府者，胃為之海

胃者，五藏六府之海也，水穀皆入于胃，五藏六府，皆稟氣於胃。

胃者，水谷氣血之海也。

胃為五藏六府之海，

衝脈者經脈之海也，主滲灌谿谷，與陽明合於宗筋，陰陽揔宗筋之會，會於氣街，而陽明為
之長，皆屬於帶脈，而絡於督脈。

夫沖脈者，五藏六府之海也，五藏六府皆稟焉。

沖脈者，十二經之海也，

沖脈任脈皆起於胞中，上循背裏，為經絡之海，

其大氣之搏而不行者，積於胸中，命曰氣海，

== 四街

四街者，氣之徑路也。

請言氣街，胸氣有街，腹氣有街，頭氣有街，脛氣有街。故氣在頭者，止之於腦；氣在胸者，
止之膺與背腧；氣在腹者，止之背腧，與沖脈於臍左右之動脈者；氣在脛者，止之於氣街，
與承山踝上以下。

== 八虛

黃帝問於歧伯曰：人有八虛，各何以候？歧伯答曰：以候五藏。黃帝曰：候之奈何？歧伯曰：

* 肺心有邪，其氣留於兩肘；
* 肝有邪，其氣流於兩腋；
* 脾有邪，其氣留於兩髀；
* 腎有邪，其氣留於兩膕。

凡此八虛者，皆機關之室，真氣之所過，血絡之所遊。邪氣惡血，固不得住留。住留則傷筋
絡骨節；機關不得屈伸，故痀攣也。

== 疑问

今天看到两段经文，有点意思：

動輸:

黃帝曰：足之陽明，何因而動？歧伯曰：胃氣上注于肺，其悍氣上沖頭者，循咽，上走空竅，循眼系，入絡腦，出顑，下客主人，循牙車，合陽明，并下人迎，此胃氣別走於陽明者也。故陰陽上下，其動也若一。故陽病而陽脈小者，為逆；陰病而陰脈大者，為逆。故陰陽俱靜俱動，若引繩相傾者病。

黃帝曰：足少陰何因而動？歧伯曰：沖脈者，十二經之海也，與少陰之大絡，起於腎下，出於氣街，循陰股內廉，邪入膕中，循脛骨內廉，并少陰之經，下入內踝之後。入足下，其別者，邪入踝，出屬附上，入大指之間，注諸絡，以溫足脛，此脈之常動者也。

逆順肥瘦:

黃帝曰：少陰之脈獨下行，何也？歧伯曰：不然，夫沖脈者，五藏六府之海也，五藏六府皆稟焉。其上者，出于頏顙，滲諸陽，灌諸精；其下者，注少陰之大絡，出于氣街，循陰股內廉入膕中，伏行骭骨內，下至內踝之後屬而別。其下者，並于少陰之經，滲三陰；其前者，伏行出跗屬，下循跗，入大指間，滲諸絡而溫肌肉。故別絡結則附上不動，不動則厥，厥則寒矣。黃帝曰：何以明之？歧伯曰：以言導之，切而驗之，其非必動，然後仍可明逆順之行也。黃帝曰：窘乎哉！聖人之為道也。明于日月，微于毫釐，其非夫子，孰能道之也。

第一是循行，有一条少阴之大络起于肾下，还有从气街循阴股内廉邪入膕中，以及别走跗上入大趾间，常规的循行都没看到，比较特殊。最后一个可能和足阳明合在一起了。

第二是”此脈之常動者也“指的是太溪还是冲阳，还是两者都有？既然说的是足少阴之动，应该说的是太溪，但这条别络会影响到冲阳的跳动。不知道我理解的对不对。

第三是气口候阴，人迎候阳，还有寸口主中，人迎主外。那么太溪脉和冲阳脉候的是什么？人迎和冲阳都是足阳明脉，又有何不同？内经中对于冲阳脉涉及比较少，好像伤寒论对冲阳脉（趺阳脉）还算比较看重的吧。

第四：能不能说寸口候的是营气，而人迎候的是卫气？那么少阴脉（太溪）候的是冲脉，是所有的经气，是不是比寸口人迎更能说明人本身的气的状态？

我就随便想想，大家也随便说说吧。

=== 脹論

營氣循脈，衛氣逆為脈脹；衛氣並脈循分為膚脹。

衛氣之在身也，常然並脈，循分肉，行有逆順，陰陽相隨，乃得天和，五藏更始，四時循序，五穀乃化。然後厥氣在下，營衛留止，寒氣逆上，真邪相攻，兩氣相搏，乃合為脹也。

恐則氣下，... 恐則精卻，卻則上焦閉，閉則氣還，還則下焦脹，故氣不行矣。

有病膺腫頸痛胸滿腹脹此為何病，何以得之。歧伯曰：名厥逆。帝曰：治之柰何。...須其氣并，乃可治也。...其氣并而治之，可使全也。

黃帝曰：膚脹何以候之？歧伯曰：膚脹者，寒氣客於皮膚之間，鼕鼕然不堅，腹大，身盡腫，皮厚，按其腹，窅而不起，腹色不變，此其候也。

黃帝曰：積之始生，至其已成，奈何？歧伯曰：積之始生，得寒乃生，厥乃成積也，黃帝曰：其成積奈何？歧伯曰：厥氣生足悗，悗生脛寒，脛寒則血脈凝澀，血脈凝澀則寒氣上入于腸胃，入于腸胃則䐜脹，䐜脹則腸外之汁沫迫聚不得散，日以成積。卒然多食飲，則腸滿，起居不節，用力過度，則絡脈傷，陽絡傷則血外溢，血外溢則衄血，陰絡傷則血內溢，血內溢則後血。腸胃之絡傷則血溢於腸外，腸外有寒，汁沫與血相搏，則併合凝聚不得散，而積成矣。卒然中外於寒，若內傷於憂怒，則氣上逆，氣上逆則六俞不通，溫氣不行，凝血蘊裏而不散，津液澀滲，著而不去，而積皆成矣。


== 逆順

脈行之逆順，奈何？歧伯曰：手之三陰，從藏走手；手之三陽，從手走頭；足之三陽，從頭走足；足之三陰，從足走腹。

黃帝問于伯高曰：余聞氣有逆順，脈有盛衰，刺有大約，可得聞乎？伯高曰：氣之逆順者，所以應天地陰陽四時五行也；脈之盛衰者，所以候血氣之虛實有餘不足；刺之大約者，必明知病之可刺，與其未可刺，與其已不可刺也。

== 问题

我读到内经中心可能跟三个窍有关，分别是目、舌和耳。首先要看看“窍”是什么意思。

《说文解字》：空也。就是孔。

=== 目

夫心者，五藏之專精也，目者，其竅也。

“其窍也”中的“其”指的是心，还是五藏呢？中文中两种都可能，有歧义。

其推断过程大概是这样的：

. 五藏六府之精氣，皆上注于目而為之精。
. 夫心者，五藏之專精也，目者，其竅也。
. 五藏六府，心為之主，目為之候。（其实这句可以表明目是五脏六腑之候，而非心之候）
. 目者，心使也。心者，神之舍也。

其实是说眼睛是五脏六腑的外候，通过眼睛可以判断出人之五脏六腑和人之神的情况，而不
仅仅是心的外候。

== 舌

五氣入鼻，藏於心肺，上使五色脩明，音聲能彰。

== 耳


十二經脈，三百六十五絡，其血氣皆上于面而走空竅。其精陽氣上走於目而為睛。其別氣走於耳而為聽。其宗氣上出於鼻而為臭。其濁氣出於胃，走唇舌而為味。

夫心者，五藏之專精也，目者，其竅也

五藏常內閱於上七竅也。故肺氣通於鼻，肺和則鼻能知臭香矣；心氣通於舌，心和則舌能知五味矣；肝氣通於目，肝和則目能辨五色矣；脾氣通於口，脾和則口能知五穀矣；腎氣通於耳，腎和則耳能聞五音矣。五藏不和，則七竅不通；

黃帝曰：人之哀而泣涕出者，何氣使然？歧伯曰：心者，五藏六府之主也；目者，宗脈之所聚也，上液之道也；口鼻者，氣之門戶也。故悲哀愁憂則心動，心動則五藏六府皆搖，搖則宗脈感，宗脈感則液道開，液道開，故泣涕出焉。液者，所以灌精濡空竅者也，故上液之道開則泣，泣不止則液竭；液竭則精不灌，精不灌則目無所見矣，故命曰奪精。補天柱經俠頸。

氣上注于肺，其悍氣上沖頭者，循咽，上走空竅，循眼系，入絡腦，出顑，下客主人，循牙車，合陽明，并下人迎，此胃氣別走於陽明者也。

其氣九州九竅五藏十二節，皆通乎天氣。

陽不勝其陰，則五藏氣爭，九竅不通。是以聖人陳陰陽，筋脈和同，骨髓堅固，氣血皆從。如是，則內外調和，邪不能害，耳目聰明，氣立如故。

清陽出上竅，濁陰出下竅

陰味出下竅，陽氣出上竅。

陽氣者，煩勞則張，精絕辟積，於夏使人煎厥。目盲不可以視，耳閉不可以聽，

耳者，宗脈之所聚也，

兩神相搏，合而成形，常先身生，是謂精。何謂氣？歧伯曰：上焦開發，宣五穀味，熏膚、充身、澤毛，若霧露之溉，是謂氣。

精脫者，耳聾；氣脫者，目不明；

氣海不足，則氣少不足以言。

髓海不足，則腦轉耳鳴，脛痠眩冒，目無所見，懈怠安臥。

五藏六府，心為之主，耳為之聽，目為之候，肺為之相，肝為之將，脾為之衛，腎為之主外。

黃帝曰：願聞五官。歧伯曰：鼻者，肺之官也；目者，肝之官也；口唇者，脾之官也；舌者，心之官也；耳者，腎之官也。

黃帝曰：以官何候？歧伯曰：以候五藏。

手少陰之上，血氣盛則眉美以長，耳色美，血氣皆少則耳焦惡色。

高耳者，腎高；耳後陷者，腎下。耳堅者，腎堅；耳薄不堅者，腎脆。耳好前居牙車者，腎端正；耳偏高者，腎偏傾也。

五常政大論，其藏心，其主舌……其藏腎，腎其畏濕，其主二陰，

五藏六府，心為之主，耳為之聽，目為之候，肺為之相，肝為之將，脾為之衛，腎為之主外。故五藏六府之津液，盡上滲於目，

因視目之五色，以知五藏，而決死生。

五藏六府之精氣，皆上注于目而為之精。目者，五藏六府之精也，營衛魂魄之所常營也，神氣之所生也。目者，心使也。心者，神之舍也，


=== 节

所言節者，神氣之所遊行出入也
節之交三百六十五會者，絡脈之滲灌諸節者也。
血和則孫脈先滿溢，乃注于絡脈，皆盈，乃注于經脈
夫十二經脈者，皆絡三百六十五節，節有病，必被經脈，
十二原者，五藏之所以稟三百六十五節氣味也。
皮毛焦，則津液去皮節；津液去皮節者，則爪枯毛折；

看起来"节"是连接络脉和经脉的点，不知道对不对。

節之交，三百六十五會，知其要者，一言而終，不知其要，流散無窮。所言節者，神氣之所遊行出入也。非皮肉筋骨也。

十二原者，五藏之所以稟三百六十五節氣味也。

節之交三百六十五會者，絡脈之滲灌諸節者也。

夫十二經脈者，皆絡三百六十五節，節有病，必被經脈，

人九竅三百六十五絡應野。

九鍼通九竅，除三百六十五節氣，

九者，野也。野者，人之節解皮膚之間也。

中焦出氣如露，上注谿谷，而滲孫脈，津液和調，變化而赤為血。血和則孫脈先滿溢，乃注于絡脈，皆盈，乃注于經脈，陰陽已張，因息乃行。

手太陰氣絕，則皮毛焦。太陰者，行氣溫於皮毛者也。故氣不榮，則皮毛焦；皮毛焦，則津液去皮節；津液去皮節者，則爪枯毛折；毛折者，則毛先死。丙篤丁死，火勝金也。


五氣入鼻，藏於心肺，上使五色脩明，音聲能彰。
所以察其目者，五藏使五色循明。循明則聲章。聲章者，則言聲與平生異也。


血者，神氣也，
黃帝曰：何者為神？歧伯曰：血氣已和，營衛已通，五藏已成，神氣舍心，魂魄畢具，乃成為人。
百歲，五藏皆虛，神氣皆去，形骸獨居而終矣。

=== 邪

内经中的邪昰指外邪，风寒暑湿燥火，但根据上下文具体的指代不同。邪之中人分阳邪和阴邪，分别中阳经和阴经，并且部位是身半以上和身半以下，

关于邪的描述散落在内经各处，给我们展示了邪有哪些，什么时候、从什么地方、在什么情况下、如何中人，中人了以后人体有什么反应，又是怎么影响气血运行和皮肉筋骨脉，沿者什么路线一步一步从皮到络到经再到脏腑，然后又有什么样的外候，又该如何去治疗，应遵循什么原则，等等等等。

而这一篇基本上包含了所有这些内容的概要，但其中很多东西都要去查阅其他篇章才能了解。

所谓知己知彼，百战不殆。如果掌握了关于邪的这些问题，知道了它的来源、发展和结果，可以说人体治病的战争我们已经打胜了一半，这是知彼。知己就是了解人体自身，脏腑经络血脉、精神意志等等等等，具体的内容可以慢慢学，我们更要关注的我觉得昰内经的体系，先整体再局部，逐步深入细化，最后装到自己脑子里的就是自己构造的一个人体运行模型，自己造的东西要修理还不是十拿九稳的事情

腠理开而中于邪，

賊風邪氣之中人也，不得以時，然必因其開也，其入深，其內極病，其病人也，卒暴。因其閉也，其入淺以留，其病也，徐以遲。

黃帝曰：有寒溫和適，腠理不開，然有卒病者，其故何也？少師答曰：帝弗知邪入乎。雖平居其腠理開閉緩急，其故常有時也。

黃帝曰：夫子言賊風邪氣之傷人也，令人病焉，今有其不離屏蔽，不出室穴之中，卒然病者，非不離賊風邪氣，其故何也？歧伯曰：此皆嘗有所傷於濕氣，藏於血脈之中，分肉之間，久留而不去。若有所墮墜，惡血在內而不去，卒然喜怒不節，飲食不適，寒溫不時，腠理閉而不通。其開而遇風寒，則血氣凝結，與故邪相襲，則為寒痺。其有熱則汗出，汗出則受風，雖不遇賊風邪氣，必有因加而發焉。

風雨寒熱不得虛，邪不能獨傷人。

=== 根结

所謂五十營者，五藏皆受氣，持其脈口，數其至也。五十動而不一代者，五藏皆受氣。

夫脈者，血之府也，代則氣衰

人一呼脈再動，一吸脈亦再動，呼吸定息脈五動，閏以太息，命曰平人。

故人一呼脈再動，氣行三寸，一吸，脈亦再動，氣行三寸，呼吸定息，氣行六寸；十息，氣行六尺，日行二分。二百七十息，氣行十六丈二尺，氣行交通於中，一周於身，下水二刻，日行二十五分。

那么五十动就是十息，气行六尺。

故人一呼脈再動，氣行三寸，一吸，脈亦再動，氣行三寸，呼吸定息，氣行六寸；十息，氣行六尺，日行二分。二百七十息，氣行十六丈二尺，氣行交通於中，一周於身，下水二刻，日行二十五分。

人一呼脈再動，一吸脈亦再動，呼吸定息脈五動，閏以太息，命曰平人。平人者，不病也。常以不病調病人，醫不病，故為病人平息以調之為法。

歧伯曰：五藏者，皆稟氣於胃，胃者，五藏之本也，藏氣者，不能自致於手太陰，必因於胃氣，乃至於手太陰也，故五藏各以其時，自為而至於手太陰也。

夫脈者，血之府也，長則氣治，短則氣病，數則煩心，大則病進，上盛則氣高，下盛則氣脹，代則氣衰，細則氣少，濇則心痛，渾渾革至如涌泉，病進而色弊，緜緜其去如弦絕，死。

長夏胃微耎弱曰平，弱多胃少曰脾病，但代无胃曰死，耎弱有石曰冬病，弱甚曰今病。藏真濡於脾，脾藏肌肉之也。

脈應象：肝脈絃，心脈鉤，脾脈代，肺脈毛，腎脈石，是謂五藏之脈。

其脈代而鉤者，病在絡脈。

留而不去，則傳舍於絡脈，在絡之時，痛於肌肉，故痛之時息，大經乃代，

== 寿夭刚柔

刺有三变，刺营、刺卫、刺寒痹之留经，生病的表现分别是寒热少气、血上下行，气痛时来时去、怫忾贲响、风寒客于肠胃之中，留而不去、时痛而皮不仁。相应的刺法是出血、出气和使内热。

为什么这里只提出了留经的寒痹？风寒湿杂合而为痹，

刺卫在刺节真邪论里面列出了五种刺卫的方法。

== 官针

九刺基本上是刺的部位，十二刺是一些病的刺法，五刺则是前两者的结合，以应五藏。不明白的是这样的分类依据是什么。

三刺什么时候用呢？

故用针者，不知年之所加，气之盛衰，虚实之所起，不可以为工也。天时、人和、地利

== 本神

肝者，罢极之本，魂之居也

肝藏魂，

肝藏血，血舍魂，肝气虚则恐，实则怒。

肝悲哀动中则伤魂，魂伤则狂忘不精，不精则不正，当人阴缩而挛筋，两胁骨不举，毛悴色夭死于秋。

五藏者，合神气魂魄而藏之；

志意者，所以御精神，收魂魄，适寒温，和喜怒者也。

志意和则精神专直，魂魄不散，悔怒不起，五藏不受邪矣；

五藏者，所以藏精神血气魂魄者也；
五藏者，所以藏精神魂魄者也；

黄帝曰：何者为神？歧伯曰：血气已和，营卫已通，五藏已成，神气舍心，魂魄毕具，乃成为人。

心藏神，肺藏魄，肝藏魂，脾藏意，肾藏精志也。

故神劳则魂魄散，志意乱。

血、脈、營、氣、精神，此五藏之所藏也。

志：怒喜思忆恐

=== 经脉

是故春气在经脉，夏气在孙络，长夏气在肌肉，秋气在皮肤，冬气在骨髓中。帝曰：余愿闻其故。歧伯曰：春者，天气始开，地气始泄，冻解冰释，水行经通，故人气在脉。夏者，经满气溢，入孙络受血，皮肤充实。长夏者，经络皆盛，内溢肌中。秋者，天气始收，腠理闭塞，皮肤引急。冬者盖藏，血气在中，内著骨髓，通于五藏。是故邪气者，常随四时之气血而入客也，至其变化不可为度，然必从其经气，辟除其邪，除其邪，则乱气不生。

帝曰：逆四时而生乱气，柰何。歧伯曰：春刺络脉，血气外溢，令人少气。春刺肌肉，血气环逆，令人上气。春刺筋骨，血气内著，令人腹胀。夏刺经脉，血气乃竭，令人解㑊。夏刺肌肉，血气内却，令人善恐。夏刺筋骨，血气上逆，令人善怒。秋刺经脉，血气上逆，令人善忘。秋刺络脉，气不外行，令人卧不欲动。秋刺筋骨，血气内散，令人寒栗。冬刺经脉，血气皆脱，令人目不明。冬刺络脉，内气外泄，留为大痹。冬刺肌肉，阳气竭绝，令人善忘。凡此四时刺者大逆之病，不可不从也，反之则生乱气相淫病焉。故刺不知四时之经，病之所生，以从为逆，正气内乱，与精相薄，必审九候，正气不乱，精气不转。

春取络脉诸荥大经分肉之间，甚者深取之，间者浅取之。夏取诸俞孙络肌肉皮肤之上。秋取诸合，馀如春法。冬取诸井诸俞之分，欲深而留之。此四时之序，气之所处，病之所舍，藏之所宜。

帝问于歧伯曰：夫四时之气，各不同形，百病之起，皆有所生，灸刺之道，何者为定？歧伯答曰：四时之气，各有所在，灸刺之道，得气穴为定。故春取经、血脉、分肉之间，甚者，深刺之，间者，浅刺之；夏取盛经孙络，取分间绝皮肤；秋取经俞。邪在府，取之合；冬取井荥，必深以留之

春取络脉，夏取分腠，秋取气口，冬取经输。凡此四时，各以时为齐。络脉治皮肤，分腠治肌肉，气口治筋脉，经输治骨髓。

气绝，脉终

酒者，熟谷之液也。其气悍以清，
酒者，水谷之精，熟谷之液也，其气慓悍，其入于胃中，则胃胀，气上逆，满于胸中，肝浮胆横，
歧伯曰：酒入于胃，则络脉满而经脉虚；脾主为胃行其津液者也，阴气虚，则阳气入，
飲酒者，衛氣先行皮膚，先充絡脈，絡脈先盛。故衛氣已平，營氣乃滿，而經脈大盛。

看起来是这样的，酒乃水谷之精、熟谷之液，其气慓悍。入胃之后，化为卫气，先行皮肤、充络脉，这时候络满而经虚。过一会，阳气从络入经，经脉大盛。

卫气应该不是直接入络入经，因为卫行脉外，是不是化而为营？如何而化的呢？

那营有没有可能化为卫呢？

阳气衰，不能渗营其经络，




黄帝曰：余闻肠胃受谷，上焦出气，以温分肉，而养骨节，通腠理。中焦出气如露，上注溪谷，而渗孙脉，津液和调，变化而赤为血。血和则孙脉先满溢，乃注于络脉，皆盈，乃注于经脉，

諸絡脈皆不能經大節之間，必行絕道而出入，復合於皮中，其會皆見於外。故諸刺絡脈者，必刺其結上甚血者。雖無結，急取之，以寫其邪而出其血。

经脉：脉的方向，《营气》营气方向，邪客：

血气之输，输于诸络，气血留居，则盛而起，

一经上实下虚而不通者，此必有横络盛加于大经，令之不通，

=== 经别

从经别的走向来看，基本上符合向心性，而阳经之正大都过心，阴经之正大都过咽喉，

=== 五十营

营气路线是从手太阴起走十二经到足厥阴，然后走督任，再回到手太阴，总共十四经，总长八丈一尺，左右两边应该是同步进行的。再看五十营，二百七十息，气行十六丈二尺，一周于身，走了全部二十八脉，才能算一周，和营气一周不同。所以我认为五十营中所指的“人气”并不是营气。

五十营，首先一个问题是这里的人气指的是营气吗？

根结篇中也提到了五十营，五藏皆受气，营卫生会也有五藏六腑皆以受气，这两个地方的气又指的是什么？

接下来的营卫生会篇，“上焦出于胃上口，并咽以上，贯膈，而布胸中，走腋，循太阴之分而行，还至阳明，上至舌，下足阳明，常与营俱行于阳二十五度，行于阴亦二十五度一周也。故五十度而复太会于手太阴矣。”明显说的不是营气,因为有一句“常与营俱行”，那这个上焦所出指的又是什么呢？

决气篇里说“上焦开发，宣五谷味，熏肤，充身，泽毛，若雾露之溉，是谓气”，痈疽篇里说“余闻肠胃受谷，上焦出气，以温分肉，而养骨节，通腠理”。跟上面描述的应该是一个东西，也就是气。这个气是宗气吗？

故宗气积于胸中，出于喉咙，以贯心脉，而行呼吸焉。
宗气留于海，其下者，注于气街，其上者，走于息道。故厥在于足，宗气不下，脉中之血，凝而留止，
黄帝曰：营卫之行奈何？伯高曰：谷始入于胃，其精微者，先出于胃之两焦，以溉五藏，别出两行，营卫之道。其大气之搏而不行者，积于胸中，命曰气海，出于肺，循咽喉，故呼则出，吸则入。
有所结，中于肉，宗气归之，（同一段中还有好几处“气归之”的说法，我认为同样是指宗气）

可以说，宗气也是到处都有的，并不仅限于胸中。

谷入于胃，胃气上注于肺。
人受气于谷，谷入于胃，以传与肺，五藏六府，皆以受气，其清者为营，浊者为卫，
中焦亦并胃中，出上焦之后，此所受气者，泌糟粕，蒸津液，化其精微，上注于肺脉乃化而为血，以奉生身，莫贵于此，故独得行于经隧，命曰营气。
黄帝曰：营卫之行奈何？伯高曰：谷始入于胃，其精微者，先出于胃之两焦，以溉五藏，别出两行，营卫之道。其大气之搏而不行者，积于胸中，命曰气海，出于肺，循咽喉，故呼则出，吸则入。
用针之类，在于调气，气积于胃，以通营卫，各行其道。

由此可见，宗气也可称为胃气，由肺布散全身。而营气是中焦受宗气之后泌糟粕、蒸津液、化其精微出来的产物。

再回头来看五十营，和呼吸紧密相关的就是宗气，所以我觉得五十营说的可能是宗气。


关于五十营中的气行，先不管它是什么气，人体上下左右前后二十八脉，一昼夜漏下百刻，气行所有经脉五十周，总共十六丈二尺，也就是下水二刻一周，也就是左右各一刻。

这就涉及到一个问题，人体左右是对称的，那这里的气的运行是抽象的一种概念，还是有具体的规律？如果是抽象的，那映射到具体的气时，比如营卫宗气，其运行规律还是不是一样呢？

如果是具体的某种气，那它的运行就要分左右，按照某种规律或在左或在右的某条经脉上，就像现在师父给的四时顺气图中的卫气。是营气？卫气？宗气？神气？正气？真气？原气？还是别的什么气呢？其运行规律具体如何？

拿营气来说，我原本的看法是左右同时运行的，也就是左右各十四脉（任督共享）同时同步运行，一昼夜百刻五十周，和上面比一个是十四脉，一个是二十八脉，差一倍，这下就想不清楚了。

这篇里面问题多多，大家什么看法？



=== 营卫生会

食气入胃，散精于肝，淫气于筋。淫气入胃，浊气归心，淫精于脉。脉气流经，经气归于肺，肺朝百脉，输精于皮毛。毛脉合精，行气于腑。腑精神明，留于四脏，气归于椎衡。权衡以平，气口成寸，以决死生。饮入于胃，游溢精气，上输于脾。脾气散精，上归于肺，通调水道，下输膀胱。水精四布，五经并行，合于四时五脏阴阳，揆度以为常也。

夫五味入口，藏于胃，脾为之行其精气，津液在脾，

上焦者，在心下，下膈，在胃上口，主内而不出。
肺手太阴之脉，起于中焦，下络大肠，还循胃口，上膈属肺，
胃足阳明之脉，循喉咙，入缺盆，下膈，属胃，络脾；其支者，起于胃口，下循腹里，下至气冲中而合，
足阳明之正，上至脾，入于腹里属胃，散之脾，上通于心，上循咽出于口，
咽门重十两，广一寸半。至胃长一尺六寸，

=== 寒热病

==== 如何定义

《風論》風之傷人也，或為寒熱，……風氣藏於皮膚之閒，內不得通，外不得泄；風者，善行而數變，腠理開則洒然寒，閉則熱而悶，其寒也，則衰食飲，其熱也，則消肌肉，故使人怢慄而不能食，名曰寒熱。
《風論》風寒客於脈而不去，名曰癘風，或名曰寒熱。
《壽夭剛柔》營之生病也，寒熱少氣，血上下行。
《脈要精微論》帝曰：病成而變何謂。歧伯曰：風成為寒熱，……
《陰陽別論》三陽為病，發寒熱，下為癰腫，及為痿厥腨㾓；其傳為索澤，其傳為頹疝。
《寒熱》黃帝問于歧伯曰：寒熱瘰癧在於頸腋者，皆何氣使生？歧伯曰：此皆鼠瘻寒熱之毒氣也，留於脈而不去者也。

《玉機真藏論》是故風者百病之長也，今風寒客於人，使人毫毛畢直，皮膚閉而為熱，當是之時，可汗而發也；或痺不仁腫痛，當是之時，可湯熨及火灸刺而去之。弗治，病入舍於肺，名曰肺痺，發欬上氣。弗治，肺即傳而行之肝，病名曰肝痺，一名曰厥，脇痛出食，當是之時，可按若刺耳。弗治，肝傳之脾，病名曰脾風，發癉，腹中熱，煩心出黃，當此之時，可按可藥可浴。弗治，脾傳之腎，病名曰疝瘕，少腹冤熱而痛，出白，一名曰蠱，當此之時，可按可藥。弗治，腎傳之心，病筋脈相引而急，病名曰瘛，當此之時，可灸可藥。弗治，滿十日，法當死。腎因傳之心，心即復反傳而行之肺，發寒熱，法當三歲死，此病之次也。

《五變》黃帝問於少俞曰：余聞百疾之始期也，必生於風雨寒暑，循毫毛而入腠理，或復還，或留止，或為風腫汗出，或為消癉，或為寒熱，或為留痺，或為積聚。奇邪淫溢，不可勝數，願聞其故。夫同時得病，或病此，或病彼，意者天之為人生風乎，何其異也？少俞曰：夫天之生風者，非以私百姓也，其行公平正直，犯者得之，避者得無殆，非求人而人自犯之。

寒热病是由风伤人引起的，会恶寒发热，让人食欲不振、肌肉销铄，如果不治疗，会一步步从皮肉骨发展到五臟，最后不治而死。

==== 为何得病：

《五變》黃帝曰：人之善病寒熱者，何以候之？少俞答曰：小骨弱肉者，善病寒熱。黃帝曰：何以候骨之小大，肉之堅脆，色之不一也？少俞答曰：顴骨者，骨之本也。顴大則骨大，顴小則骨小。皮膚薄而其肉無䐃，其臂懦懦然，其地色殆然，不與其天同色，污然獨異，此其候也。然後臂薄者，其髓不滿，故善病寒熱也。

除了外因风邪之外，人本身的问题（肤薄无肉、髓不满）也是很重要的原因，当然最终还是因为人的五臟六腑精气不足而引起的。

==== 如何诊断：

《邪客》黃帝曰：持鍼縱舍奈何？歧伯曰：必先明知十二經脈之本末，皮膚之寒熱，脈之盛衰滑澀。其脈滑而盛者，病日進；虛而細者，久以持；大以澀者，為痛痺。陰陽如一者，病難治。其本末尚熱者，病尚在；其熱以衰者，其病亦去矣。持其尺，察其肉之堅脆，大小滑澀，寒溫燥濕。因視目之五色，以知五藏，而決死生。視其血脈，察其色，以知其寒熱痛痺。

《經絡論》帝曰：絡之陰陽，亦應其經乎。歧伯曰：陰絡之色應其經，陽絡之色變無常，隨四時而行也。寒多則凝泣，凝泣則青黑，熱多則淖澤，淖澤則黃赤，此皆常色，謂之無病。五色具見者，謂之寒熱。
《皮部論》陽明之陽，名曰害蜚，上下同法，視其部中有浮絡者，皆陽明之絡也，其色多青則痛，多黑則痺，黃赤則熱，多白則寒，五色皆見，則寒熱也，絡盛則入客於經，陽主外，陰主內。
《經脈》凡診絡脈……其有赤、有黑、有青者，寒熱氣也。
《論疾診尺》診血脈者，……多赤、多黑、多青皆見者，寒熱。

浅层的寒热病主要是看络脉的颜色，如果赤、黑、青等各种颜色都有，就有寒热病。

《論疾診尺》尺膚滑，其淖澤者，風也。尺肉弱者，解併，安臥脫肉者，寒熱，不治。尺膚滑而澤脂者，風也。尺膚澀者，風痺也。尺膚麤如枯魚之鱗者，水泆飲也。尺膚熱甚，脈盛躁者，病溫也，其脈甚而滑者，病且出也。尺膚寒，其脈小者，泄、少氣。尺膚炬然，先熱後寒者，寒熱也；尺膚先寒，久大之而熱者，亦寒熱也。

《五藏生成》白脈之至也喘而浮，上虛下實。驚，有積氣在胸中，喘而虛名曰肺痺寒熱，得之醉而使內也。
《邪氣藏府病形》肺脈急甚，為癲疾；微急，為肺寒熱，怠惰，咳唾血，引腰背胸，若鼻息肉不通。
《邪氣藏府病形》脾脈……小甚為寒熱；微小為消癉。
《脈要精微論》沈細數散者，寒熱也；
《平人氣象論》寸口脈沈而弱，曰寒熱及疝瘕少腹痛。
《平人氣象論》寸口脈沈而喘，曰寒熱。

如果是五臟六腑的寒热病，主要以脉来定。

==== 如何断生死：

《五禁》黃帝曰：余聞刺有五逆。歧伯曰：病與脈相逆，命曰五逆。
《五禁》黃帝曰：何謂五逆？……寒熱奪形，脈堅搏，是謂五逆也。

有逆则难治。

《論疾診尺》診寒熱，赤脈上下至瞳子，見一脈一歲死；見一脈半，一歲半死；見二脈，二歲死；見二脈半，二歲半死；見三脈，三歲死。
《寒熱》黃帝曰：決其生死奈何？歧伯曰：反其目視之，其中有赤脈，上下貫瞳子，見一脈，一歲死；見一脈半，一歲半死；見二脈，二歲死；見二脈半，二歲半死；見三脈，三歲而死。見赤脈不下貫瞳子，可治也。
《三部九候論》是故寒熱病者，以平旦死。

就是说如果眼睛上下都有血丝到达黑睛，人可能很快就死了，是不是说太阳和阳明有点要脱的意思。如果没有到黑睛，还有得救。如果死的话，多在平旦死。

==== 治法：

《九鍼論》七曰毫鍼，取注于毫毛，長一寸六分，主寒熱痛痺在絡者也。
《經脈》凡刺寒熱者，皆多血絡，必間日而一取之，血盡而止，乃調其虛實

浅层寒热病的大原则是先刺络，再调虚实。

《寒熱病》皮寒熱者，不可附席，毛髮焦，鼻槁臘。不得汗，取三陽之絡，以補手太陰。
《寒熱病》肌寒熱者，肌痛，毛髮焦而唇槁臘。不得汗，取三陽于下，以去其血者，補足太陰，以出其汗。
《寒熱病》骨寒熱者，病無所安，汗注不休。齒未槁，取其少陰于陰股之絡；齒已槁，死不治。骨厥亦然。骨痺，舉節不用而痛，汗注、煩心。取三陰之經，補之。

这些就是具体运用。

《五邪》邪在肺，則病皮膚痛，寒熱，上氣喘，汗出，欬動肩背。取之膺中外喻，背三節五藏之傍，以手疾按之，快然，乃刺之。取之缺盆中以越之。
《長刺節論》陰刺，入一傍四處。治寒熱。深專者，刺大藏，迫藏刺背，背俞也。刺之迫藏，藏會，腹中寒熱去而止，與刺之要，發鍼而淺出血。
《骨空論》鼠瘻寒熱，還刺寒府，寒府在附膝外解營。取膝上外者使之拜，取足心者使之跪。
《寒熱》黃帝曰：去之（寒熱瘰癧）奈何？歧伯曰：請從其本引其末，可使衰去，而絕其寒熱。審按其道以予之，徐往徐來以去之，其小如麥者，一刺知，三刺而已。

五臟六腑寒热病的一些刺法，以救五臟为主。

《骨空論》灸寒熱之法，先灸項大椎，以年為壯數，次灸橛骨，以年為壯數，視背俞陷者灸之，舉臂肩上陷者灸之，兩季脇之間灸之，外踝上絕骨之端灸之，足小指次指間灸之，腨下陷脈灸之，外踝後灸之，缺盆骨上切之堅痛如筋者灸之，膺中陷骨間灸之，掌束骨下灸之，齊下關元三寸灸之，毛際動脈灸之，膝下三寸分閒灸之，足陽明跗上動脈灸之，巔上一灸之，犬所囓之處灸之三壯，即以犬傷病法灸之，凡當灸二十九處。

还有灸法。

因为在别的地方多次见到寒热，就把相关的总结一下，请大家指正。

=== 病本

我有种感觉，这里的标本说的不是原发病（本病）和后发症状（标病），可能跟六气标本有关。

《標本病傳論》黃帝問曰：病有標本，刺有逆從，柰何。歧伯對曰：凡刺之方，必別陰陽，前後相應，逆從得施，標本相移。故曰：有其在標而求之於標，有其在本而求之於本，有其在本而求之於標，有其在標而求之於本，故治有取標而得者，有取本而得者，有逆取而得者，有從取而得者。故知逆與從，正行無問，知標本者，萬舉萬當，不知標本，是謂妄行。

《至真要大論》是故百病之起，有生於本者，有生於摽者，有生於中氣者，有取本而得者，有取摽而得者，有取中氣而得者，有取摽本而得者，有逆取而得者，有從取而得者。逆，正順也。若順，逆也。故曰：知摽與本，用之不殆，明知逆順，正行無問。此之謂也。不知是者，不足以言診，足以亂經。


《標本病傳論》夫陰陽逆從，標本之為道也，小而大，言一而知百病之害，少而多，淺而博，可以言一而知百也。以淺而知深，察近而知遠，言標與本，易而勿及，治反為逆，治得為從。

《至真要大論》夫標本之道，要而博，小而大，可以言一而知百病之害，言摽與本，易而勿損，察本與摽，氣可令調，明知勝復，為萬民式，天之道畢矣。

大家看看上面四段文字，标本病传论和至真要大论说的是一回事，用词都非常接近，所以我觉得这三篇的标本指的应该是六气标本，我对六气标本还没什么理解，大家可以从这方面考虑一下，看看是不是说得通、有没有道理。

=== 决气

这篇可以看出精、气、津、液、血、脉都属于广义的气，精是先天之气，气是后天之气，包括宗气和营气卫气，但津液血脉就比较难理解。我就说说对津液自己的理解。

《五癃津液別》歧伯曰：水穀皆入于口，其味有五，各注其海。津液各走其道，故三焦出氣，以溫肌肉，充皮膚，為其津，其流而不行者為液。
《決氣》何謂津？歧伯曰：腠理發泄，汗出溱溱，是謂津。

津随着气散布到肌肉皮肤中，温肌肉、充皮肤，有可能跟着气继续走。当腠理大开时，以汗的形式发泄出来。

《五癃津液別》歧伯曰：水穀皆入于口，其味有五，各注其海。津液各走其道，故三焦出氣，以溫肌肉，充皮膚，為其津，其流而不行者為液。
《決氣》何謂液？歧伯曰：穀入氣滿，淖澤注于骨，骨屬屈伸，泄澤補益腦髓，皮膚潤澤，是謂液。
《五癃津液別》五穀之津液，和合而為膏者，內滲入于骨空，補益腦髓，而下流於陰股。（我觉得这里主要是液）
《口問》液者，所以灌精濡空竅者也，

而液，流而不行，是说液（也随着气）走到骨空、脑、空窍、皮肤之后，益髓䃼脑、濡养空窍、润泽皮肤，就不再动了。

《營衛生會》黃帝曰：願聞中焦之所出。歧伯答曰：中焦亦並胃中，出上焦之後，此所受氣者，泌糟粕，蒸津液，化其精微，上注于肺脈乃化而為血，以奉生身，莫貴於此，故獨得行於經隧，命曰營氣。
《邪客》營氣者，泌其津液，注之於脈，化以為血，以榮四末，內注五藏六府，以應刻數焉。
《癰疽》中焦出氣如露，上注谿谷，而滲孫脈，津液和調，變化而赤為血。血和則孫脈先滿溢，乃注于絡脈，皆盈，乃注于經脈，

这里是说血的生成过程，营气上注溪谷、渗入孙脉之后，调和津液而变化为血，再回注孙脉、络脉最后到经脉，内注五臟六腑。是不是可以这么理解，津液在中焦蒸泌出来之后，随营气（或者就是营气或其组成部分）出孙脉，温肌肉、充皮肤，然后化为血，再回经脉和五臟六腑，这么一个过程。而进入骨、脑和空窍中的那一部分和卫气应该有关系，具体如何还不清楚，还请师兄师姐们指教。

但内经中又说，脾为胃行津液，膀胱为津液之府，那有没有可能津液只是在中焦蒸泌出来，没有随营气走，而是从胃到脾到膀胱（飲入於胃，遊溢精氣，上輸於脾。脾氣散精，上歸於肺，通調水道，下輸膀胱。水精四布），然后跟着卫气，外至皮肤，内至骨空，再和营气调和而化血，通过经脉回五臟六腑。似乎这个解法更顺一些，还需要更多经文支持。

==== 血

《邪客》營氣者，泌其津液，注之於脈，化以為血，以榮四末，內注五藏六府，以應刻數焉。

《癰疽》中焦出氣如露，上注谿谷，而滲孫脈，津液和調，變化而赤為血。血和則孫脈先滿溢，乃注于絡脈，皆盈，乃注于經脈，

《營衛生會》黃帝曰：願聞中焦之所出。歧伯答曰：中焦亦並胃中，出上焦之後，此所受氣者，泌糟粕，蒸津液，化其精微，上注于肺脈乃化而為血，以奉生身，莫貴於此，故獨得行於經隧，命曰營氣。

《決氣》何謂血？歧伯曰：中焦受氣，取汁變化而赤，是謂血。

==== 脉

《五藏別論》歧伯對曰：腦髓骨脈膽女子胞，此六者地氣之所生也，皆藏於陰而象於地，故藏而不寫，名曰奇恆之府。

《脈要精微論》脈者，血之府也，長則氣治，短則氣病，數則煩心，大則病進，上盛則氣高，下盛則氣脹，代則氣衰，細則氣少，濇則心痛，渾渾革至如涌泉，病進而色弊，緜緜其去如弦絕，死。

《陽明脈解》陽明主肉，其脈血氣盛，邪客之則熱，熱甚則惡火。

《決氣》何謂脈？歧伯曰：壅遏營氣，令無所避，是謂脈。


=== 五阅五使

我的习惯是以经解经，尽量把相关的东西整理到一起，能更好地理解一篇中相关的东西，尤其是概念。所以大部分都是原文的引用，和少量自己的理解，因为发现把这些相关内容放到一起之后，好多东西就已经明白了，不需要再多解释。还请师兄师姐们海涵，多多指教。

《五閱五使》黃帝問於歧伯曰：余聞刺有五官五閱，以觀五氣。五氣者，五藏之使也，五時之副也。願聞其五使當安出？歧伯曰：五官者，五藏之閱也。黃帝曰：願聞其所出，令可為常。歧伯曰：脈出於氣口，色見於明堂，
《五閱五使》黃帝曰：願聞五官。歧伯曰：鼻者，肺之官也；目者，肝之官也；口唇者，脾之官也；舌者，心之官也；耳者，腎之官也。
《五閱五使》黃帝曰：以官何候？歧伯曰：以候五藏。故肺病者，喘息鼻張；肝病者，眥青；脾病者，唇黃；心病者，舌捲短，顴赤；腎病者，顴與顏黑。

五气为五藏之使，出于气口；五官乃五藏之阅，以观五气、候五藏，其色见于明堂。

《邪氣藏府病形》十二經脈，三百六十五絡，其血氣皆上于面而走空竅。其精陽氣上走於目而為睛。其別氣走於耳而為聽。其宗氣上出於鼻而為臭。其濁氣出於胃，走唇舌而為味。
《脈度》五藏常內閱於上七竅也。故肺氣通於鼻，肺和則鼻能知臭香矣；心氣通於舌，心和則舌能知五味矣；肝氣通於目，肝和則目能辨五色矣；脾氣通於口，脾和則口能知五穀矣；腎氣通於耳，腎和則耳能聞五音矣。五藏不和，則七竅不通；

五藏六府和十二经脉之血气，上于面而通七窍，这就是为什么五官及其色可以候五藏。

其中，最重要的是目，察其色以决生死，如下：

《脈要精微論》夫精明五色者，氣之華也。
《解精微論》夫心者，五藏之專精也，目者，其竅也，華色者，其榮也，是以人有德也，則氣和於目，有亡，憂知於色。
《小鍼解》睹其色，察其目，知其散復，一其形，聽其動靜者，言上工知相五色於目。
《小鍼解》所以察其目者，五藏使五色循明。
《四時氣》睹其色，察其以，知其散復者，視其目色，以知病之存亡也。
《邪客》因視目之五色，以知五藏，而決死生。
《脈要精微論》切脈動靜而視精明，察五色，觀五藏有餘不足，六府強弱，形之盛衰，以此參伍決死生之分。
《五藏生成》凡相五色之奇脈，面黃目青，面黃目赤，面黃目白，面黃目黑者，皆不死也。面青目赤，面赤目白，面青目黑，面黑目白，面赤目青，皆死也。

当然了，除了最重要的五官，整个头面部也很重要。

《五閱五使》黃帝曰：五脈安出，五色安見，其常色殆者如何？歧伯曰：五官不辨，闕庭不張，小其明堂，蕃蔽不見，又埤其牆，牆下無基，垂角去外。如是者，雖平常殆，況加疾哉。
《五閱五使》黃帝曰：五色之見於明堂，以觀五藏之氣，左右高下，各有形乎？歧伯曰：藏府之在中也，各以次舍，左右上下，各如其度也。
《五色》黃帝曰：明堂骨高以起，平以直，五藏次於中央，六府挾其兩側，首面上於闕庭，王宮在於下極，五藏安於胸中，真色以致，病色不見，明堂潤澤以清，五官惡得無辨乎？
《五色》黃帝曰：五色之見也，各出其色部。部骨陷者，必不免於病矣。其色部乘襲者，雖病甚，不死矣。
《五色》雷公曰：以色言食之間甚，奈何？黃帝曰：……色從外部走內部者，其病從外走內；其色從內走外者，其病從內走外。……
《五色》雷公曰：病小愈而卒死者，何以知之？黃帝曰：赤色出兩顴，大如拇指者，病雖小愈，必卒死。黑色出於庭，大如拇指，必不病而卒死。
《五色》雷公再拜曰：善哉！其死有期乎？黃帝曰：察色以言其時。……庭者，首面也；……五藏六府肢節之部也，各有部分。……
……（五色篇中还有很多，就不一一列举了）
《五藏生成》五藏之氣，故色見青如草茲者死，……此五色之見死也。青如翠羽者生，……，此五色之見生也。


色脉合参也可决生死：

《移精變氣論》帝曰：善。余欲臨病人，觀死生，決嫌疑，欲知其要，如日月光，可得聞乎。歧伯曰：色脈者，上帝之所貴也，先師之所傳也。……色以應日，脈以應月，常求其要，則其要也。夫色之變化，以應四時之脈，此上帝之所貴，以合於神明也，所以遠死而近生。
《邪氣藏府病形》見其色，知其病，命曰明。按其脈，知其病，命曰神。……夫色脈與尺之相應也，……色脈形肉，不得相失也。故知一則為工，知二則為神，知三則神且明矣。
《邪氣藏府病形》見其色而不得其脈，反得其相勝之脈，則死矣；得其相生之脈，則病已矣。

除诊病之外，头面（或者说大一点，形）与色常用于看人夭寿、易得之病、气血盛衰，甚至人之性格等等，属于广义上的望诊。

《壽夭剛柔》此天之生命，所以立形定氣而視壽夭者，必明乎此立形定氣，而後以臨病人，決生死。
《壽夭剛柔》黃帝曰：余聞壽夭，無以度之。伯高答曰：牆基卑，高不及其地者，不滿三十而死。其有因加疾者，不及二十而死也。
《天年》黃帝曰：人之壽百歲而死，何以致之？歧伯曰：使道隧以長，基牆高以方，通調營衛，三部三里起，骨高肉滿，百歲乃得終。
《天年》黃帝曰：其不能終壽而死者，何如？歧伯曰：其五藏皆不堅，使道不長，空外以張，喘息暴疾；又卑基牆薄，脈少血，其肉不石，數中風寒，血氣虛，脈不通，真邪相攻，亂而相引，故中壽而盡也。
《五色》雷公問於黃帝曰：五色獨決於明堂乎？小子未知其所謂也。黃帝曰：明堂者，鼻也；闕者，眉間也；庭者，顏也；蕃者，頰側也；蔽者，耳門也。其間欲方大，去之十步，皆見於外，如是者壽，必中百歲。


=== 逆顺肥瘦

这篇主要告诉我们圣人为道，必有法度，然后这道才能传。而刺道之法度，要看人之气血如何。

黃帝曰：願聞自然奈何？歧伯曰：臨深決水，不用功力，而水可竭也。循掘決沖，而經可通也。此言氣之滑澀，血之清濁，行之逆順也。
黃帝曰：臨深決水，奈何？歧伯曰：血清氣濁，疾寫之則氣竭焉。黃帝曰：循掘決沖，奈何？歧伯曰：血濁氣澀，疾寫之，則經可通也。

这里是打比方，举了两个例子，说明血气清浊滑涩之不同在疾泻之后的结果也会有不同。

黃帝曰：願聞人之黑白、肥瘦、小長，各有數乎？

各种人的气血多少、清浊、滑涩都是有规律的，针刺的时候要根据气血状况，决定该如何刺，才能做到既治病又不伤气或者引邪入深。

《根結》氣滑即出疾，其氣澀則出遲，氣悍則鍼小而入淺，氣澀則鍼大而入深，深則欲留，淺則欲疾。
《終始》補須一方實，深取之，稀按其痏，以極出其邪氣。一方虛，淺刺之，以養其脈，疾按其痏，無使邪氣得入。邪氣來也緊而疾，穀氣來也徐而和。脈實者深刺之，以泄其氣；脈虛者，淺刺之，使精氣無寫出，以養其脈，獨出其邪氣。
《經水》黃帝曰：夫經水之應經脈也，其遠近淺深，水血之多少，各不同，合而以刺之奈何？歧伯答曰：足陽明，五藏六府之海也，其脈大，血多氣盛，熱壯，刺此者不深勿散，不留不寫也。……手之陰陽，其受氣之道近，其氣之來疾，其刺深者，皆無過二分，其留，皆無過一呼。其少長、大小、肥瘦，以心擦之，命曰法天之常，……，刺而過此者，則脫氣。
《陰陽清濁》黃帝曰：治之奈何？歧伯曰：清者其氣滑，濁者其氣澀，此氣之常也。故刺陰者，深而留之；刺陽者，淺而疾之；清濁相干者，以數調之也。
《血絡論》血氣俱盛而陰氣多者，其血滑，刺之則射；陽氣蓄積，久留而不寫者，其血黑以濁，故不能射。
《邪氣藏府病形》黃帝曰：病之六變者，刺之奈何？歧伯答曰：……是故刺急者，深內而久留之；刺緩者，淺內而疾發鍼，以去其熱；刺大者，微寫其氣，無出其血；刺滑者，疾發鍼而淺內之，以寫其陽氣而去其熱；刺澀者，必中其脈，隨其逆順而久留之，……諸小者，陰陽形氣俱不足，勿取以鍼而調以甘藥也。

而黑白、肥瘦、少长、大小的气血状况在本篇、《衛氣失常》、《陰陽二十五人》都有描述，就不一一列举。

当然本篇只是说明了针刺需要考虑人的气血状况，临床中还要根据具体的疾病性质、病位还有时间等等，才能决定用什么针、扎多深、怎么扎、留不留针、留多长等一些具体的操作。


《陰陽清濁》黃帝曰：治之奈何？歧伯曰：清者其氣滑，濁者其氣澀，此氣之常也。故刺陰者，深而留之；刺陽者，淺而疾之；清濁相干者，以數調之也。

《衛氣失常》黃帝曰：三者之氣血多少何如？伯高曰：膏者，多氣，多氣者，熱，熱者耐寒。肉者，多血則充形，充形則平。脂者，其血清，氣滑少，故不能大。此別於眾人者也。

《邪氣藏府病形》黃帝曰：病之六變者，刺之奈何？歧伯答曰：諸急者多寒；緩者多熱；大者多氣少血；小者血氣皆少；滑者陽氣盛，微有熱；澀者多血、少氣，微有寒。是故刺急者，深內而久留之；刺緩者，淺內而疾發鍼，以去其熱；刺大者，微寫其氣，無出其血；刺滑者，疾發鍼而淺內之，以寫其陽氣而去其熱；刺澀者，必中其脈，隨其逆順而久留之，必先按而循之，已發鍼，已按其疝，無令其血出，以和其脈；諸小者，陰陽形氣俱不足，勿取以鍼而調以甘藥也。

== 血络论

什么是奇邪呢？为什么会出现血络？

《根結》奇邪離經，不可勝數，
《繆刺論》今邪客於皮毛，入舍於孫絡，留而不去，閉塞不通，不得入於經，流溢於大絡，而生奇病也。夫邪客大絡者，左注右，右注左，上下左右，與經相干，而布於四末，其氣無常處，不入於經俞，命曰繆刺。
《三部九候論》帝曰：其可治者奈何。歧伯曰：經病者治其經，孫絡病者治其孫絡血，血病身有痛者，治其經絡。其病者在奇邪，奇邪之脈則繆刺之。留瘦不移，節而刺之。上實下虛，切而從之，索其結絡脈，刺出其血，以見通之。
《氣穴論》帝曰：余已知氣穴之處，遊鍼之居，願聞孫絡谿谷，亦有所應乎。歧伯曰：孫絡三百六十五穴會，亦以應一歲，以溢奇邪，以通榮衛，榮衛稽留，衛散榮溢，氣竭血著，外為發熱，內為少氣，疾寫無怠，以通榮衛，見而寫之，無問所會。
《皮部論》故百病之始生也，必先於皮毛，邪中之則腠理開，開則入客於絡脈，留而不去，傳入於經，留而不去，傳入於府，廩於腸胃。邪之始入於皮也，泝然起毫毛，開腠理。其入於絡也，則絡脈盛色變。其入客於經也，則感虛乃陷下。其留於筋骨之間，寒多則筋攣骨痛，熱多則筋弛骨消，肉爍䐃破，毛直而敗。
《血絡論》黃帝曰：願聞其奇邪而不在經者。歧伯曰：血絡是也。

邪客于络，如果没能赶出去，又闭塞不通，不得入于经，所以气无常处，流溢大络，布于四末，叫做奇邪，而成血络。

《邪客》凡此八虛者，皆機關之室，真氣之所過，血絡之所遊。
《繆刺論》夫邪客大絡者，左注右，右注左，上下左右，與經相干，而布於四末，其氣無常處，不入於經俞，命曰繆刺。

所以血络多见于四肢部位。

《脈度》經脈為裏，支而橫者為絡，絡之別者為孫，盛而血者疾誅之，盛者寫之，虛者飲藥以補之。
《血絡論》黃帝曰：相之奈何？歧伯曰：血脈者，盛堅橫以赤，上下無常處，小者如鍼，大者如筋，則而寫之萬全也，故無失數矣。失數而反，各如其度。

血络是何模样，如上所述。

《調經論》帝曰：刺留血，柰何。歧伯曰：視其血絡，刺出其血，無令惡血得入於經，以成其疾。
《經脈》黃帝曰：諸絡脈皆不能經大節之間，必行絕道而出入，復合於皮中，其會皆見於外。故諸刺絡脈者，必刺其結上甚血者。雖無結，急取之，以寫其邪而出其血。……刺寒熱者，皆多血絡，必間日而一取之，血盡而止，乃調其虛實。
《官鍼》四曰絡刺，絡刺者，刺小絡之血脈也；
《官鍼》豹文刺，豹文刺者，左右前後鍼之，中脈為故，以取經絡之血者，此心之應也。

此为刺法总则，刺血的目的是“无令恶血得入于经，以成其疾”。

而由于气血状况不同，刺之后可能出现一些情形，或仆，或血射，或血黑浊，或血清，或肿，或面脱色，或面色不变而烦，或出血多而不虚，等等等等，医者要有预判。

=== 五变

《本藏》衛氣者，所以溫分肉，充皮膚，肥腠理，司開闔者也；……衛氣和則分肉解利，皮膚調柔，腠理致密矣；
三焦膀胱者，腠理毫毛其應。

《百病始生》是故虛邪之中人也，始於皮膚，皮膚緩則腠理開，開則邪從毛髮入，

《歲露論》故每至於風府則腠理開，腠理開則邪氣入，

==== 风病汗出

《生氣通天論》故風者，百病之始也，清靜則肉腠閉拒，雖有大風苛毒，弗之能害，此因時之序也。

《評熱病論》歧伯曰：汗出而身熱者，風也，汗出而煩滿不解者，厥也，病名曰風厥。帝曰：願卒聞之。歧伯曰：巨陽主氣，故先受邪，少陰與其為表裏也，得熱則上從之，從之則厥也。

《風論》曰：五藏風之形狀不同者何，願聞其診及其病能。歧伯曰：肺風之狀，多汗惡風…；心風之狀，多汗惡風，…；肝風之狀，多汗惡風，…；脾風之狀，多汗惡風，…；腎風之狀，多汗惡風，…；胃風之狀，頸多汗惡風，…；首風之狀頭面多汗惡風…；漏風之狀，或多汗，常不可單衣，食則汗出，甚則身汗，喘息惡風，衣常濡，…；泄風之狀，多汗，汗出泄衣上，…

《病能論》帝曰：善。有病身熱解墯，汗出如浴，惡風少氣，此為何病。歧伯曰：病名曰酒風。

《骨空論》黃帝問曰：余聞風者百病之始也，以鍼治之，柰何。歧伯對曰：風從外入，令人振寒，汗出頭痛，身重惡寒，治在風府，調其陰陽，不足則補，有餘則寫。

《水熱穴論》勇而勞甚則腎汗出，腎汗出逢於風，內不得入於藏府，外不得越於皮膚，客於玄府，行於皮裏，傳為胕腫，本之於腎，名曰風水。


==== 消瘅

《師傳》歧伯曰：夫中熱消癉，則便寒；
《刺節真邪》黃帝曰：余聞刺有五邪，何謂五邪？歧伯曰：病……有熱者……，是謂五邪。黃帝曰：刺五邪奈何？歧伯曰：凡刺五邪之方，不過五章，癉熱消滅，腫聚散亡，寒痺益溫，小者益陽；大者必去，請道其方。
《五變》少俞答曰：此人薄皮膚，而目堅固以深者，長沖直腸，其心剛，剛則多怒，怒則氣上逆，胸中蓄積，血氣逆留，髖皮充肌，血脈不行，轉而為熱，熱則消肌膚，故為消癉。
《瘧論》其但熱而不寒者，陰氣先絕，陽氣獨發，則少氣煩冤，手足熱而欲嘔，名曰癉瘧。
《瘧論》帝曰：癉瘧何如。歧伯曰：癉瘧者，肺素有熱氣盛於身，厥逆上衝，中氣實而不外泄，因有所用力，腠理開，風寒舍於皮膚之內、分肉之閒而發，發則陽氣盛，陽氣盛而不衰，則病矣。其氣不及於陰，故但熱而不寒，氣內藏於心，而外舍於分肉之閒，令人消爍脫肉，故命曰癉瘧。
《玉機真藏論》肝傳之脾，病名曰脾風，發癉，腹中熱，煩心出黃，
《氣厥論》心移熱於肺，傳為鬲消。
《脈要精微論》癉成為消中，
《風論》風氣與陽明入胃循脈而上至目內眥，其人肥則風氣不得外泄，則為熱中而目黃；

从以上可以看出，瘅是指内热，因内热而消肌肤为消瘅。 瘅，《说文解字》劳病也。意思应该不同。

《奇病論》帝曰：有病口甘者，病名為何，何以得之。歧伯曰：此五氣之溢也，名曰脾癉。夫五味入口，藏於胃，脾為之行其精氣，津液在脾，故令人口甘也；此肥美之所發也，此人必數食甘美而多肥也，肥者令人內熱，甘者令人中滿，故其氣上溢，轉為消渴。治之以蘭，除陳氣也。
《通評虛實論》凡治消癉仆擊，偏枯痿厥，氣滿發逆，肥貴人，則高梁之疾也。
《腹中論》夫熱中消中者皆富貴人也，

一个主要成因是数食甘美而多肥，高梁之疾也，富贵病也。

《五變》黃帝曰：人之善病消癉者，何以候之？少俞答曰：五藏皆柔弱者，善病消癉。
《本藏》心脆則善病消癉熱中。……肺脆則苦病消痺，易傷。……肝脆則善病消痺，易傷。……脾脆則善病消痺，易傷。……腎脆，則善病消癉，易傷。
《本藏》𩩲骬弱小以薄者，心脆。肩背薄者，肺脆。脅骨弱者，肝脆。唇大而不堅者，脾脆。耳薄不堅者，腎脆。
《根結》夫王公大人，血食之君，身體柔脆，肌肉軟弱，……

当然了，吃得好是外因，多怒而血气逆留是内因，五藏脆是本因，所以易得消瘅。

《邪氣藏府病形》心脈……微小為消癉；肺脈……；肝脈……；脾脈……；腎脈……微小為消癉。
《通評虛實論》帝曰：消癉虛實何如。歧伯曰：脈實大，病久可治；脈懸小堅，病久不可治。

五藏消瘅之脉象都为微小，据实虚不同而言病久可治不可治。

本篇前几段以树木作比喻，说明人有病，是因为骨节、皮肤、腠理等等让邪有机可乘，并且根据人本身骨节、皮肤、腠理、肉和藏府之坚脆缓急大小等等不同，容易生的病也有所不同。

《五變》黃帝曰：余聞病形，已知之矣！願聞其時。少俞答曰：先立其年，以知其時。時高則起，時下則殆，雖不陷下，當年有沖道，其病必起，是謂因形而生病，五變之紀也。

我觉得这就涉及到五运六气了，具体如何，还有待学习。

《五運行大論》先立其年，以知其氣，左右應見，然後乃可以言死生之逆順。
《五常政大論》故曰：不知年之所加，氣之同異，不足以言生化，此之謂也。
《六元正紀大論》歧伯曰：先立其年以明其氣，金木水火土運行之數，寒暑燥濕風火臨御之化，則天道可見，民氣可調，陰陽卷舒，近而無惑，數之可數者，請遂言之。
《氣交變大論》帝曰：夫子之言五氣之變，四時之應，可謂悉矣。
《六元正紀大論》謹候其時，病可與期，失時反歲，五氣不行，生化收藏，政無恒也。

=== 本藏

《本神》歧伯答曰：天之在我者德也，地之在我者氣也。德流氣薄而生者也。

天地之大德曰生，而人之血气精神就是供奉这个天地之生，周流濡养人之性和命。

《經水》五藏者，合神氣魂魄而藏之；六府者，受穀而行之，受氣而揚之；
《本藏》五藏者，所以藏精神血氣魂魄者也；六府者，所以化水穀而行津液者也。
《衛氣》帝曰：五藏者，所以藏精神魂魄者也；六府者，所以受水谷而行化物者也。

经脉行血，卫气行气，志意御精神、收魂魄。五藏藏精神血气魂魄，六府化水谷而行气血津液。

举个例子，人就是一台电脑，五藏是硬盘，六府是内存，志意是操作系统，卫气是应用软件，血是数据文件，经脉就是各种线路。

《調經論》夫心藏神，肺藏氣，肝藏血，脾藏肉，腎藏志，而此成形，志意通內連骨髓，而成身形五藏，五藏之道，皆出於經隧以行血氣，
《天年》歧伯曰：血氣已和，營衛已通，五藏已成，神氣舍心，魂魄畢具，乃成為人。
《本藏》此人之所以具受於天也，無愚智賢不肖，無以相倚也。

所有这些都具备了，并且运行良好，才成为人。

黄帝问了歧伯一个问题，有三种人，一种百病不生而尽天寿，一种受邪但没什么大事，一种小心呵护还老是生病，这是为什么？

歧伯说了五藏有小大、高下、堅脆、端正、偏傾，六府有小大、長短、厚薄、結直、緩急。五藏此二十五变，常使人病，而各有其外应。

黄帝认为答非所问，又问了一遍。歧伯总结了一下，五藏皆堅者，無病；五藏皆小者，少病，苦憔心，大愁擾；五藏皆脆者，不離於病。

最后论述了藏府之合与其应，视其外应，以知其内藏，则知其所病矣。

== 禁服

=== 服

这里的服字是什么意思呢？

《八正神明論》黃帝問曰：用鍼之服，必有法則焉，今何法何則。歧伯對曰：法天則地，合以天光。
《官能》用鍼之服，必有法則，上視天光，下司八正，以辟奇邪，而觀百姓，審於虛實，無犯其邪。是得天之靈，遇歲之虛，救而不勝，反受其殃，故曰必知天忌，乃言鍼意。

这两篇是同一个用法，为名词，王冰和马莳的注解是“事也”，康熙字典“又事也。《詩·大雅》昭哉嗣服。《傳》服，事也。”是不是就是说用针这件事。

《病傳》黃帝曰：此乃所謂守一勿失，萬物畢者也。今余已聞陰陽之要，虛實之理，傾移之過，可治之屬，願聞病之變化，淫傳絕敗而不可治者，可得聞乎？歧伯曰：要乎哉問也，昭乎其如日醒，窘乎其如夜瞑，能被而服之，神與俱成，畢將服之，神自得之，生神之理，可著於竹帛，不可傳於子孫。
《禁服》雷公問於黃帝曰：細子得受業，通于九鍼六十篇，旦暮勤服之，近者編絕，久者簡垢，然尚諷誦弗置，未盡解於意矣。

这两句的服是动词，似乎是实行、践行或者思考的意思，在康熙字典里这两个意思都有。

标题中的服是什么意思？我觉得也是“事”的意思，大概就是说“禁传之事”。

=== 方

《禁服》外揣言渾束為一，未知所謂也。夫大則無外，小則無內，大小無極，高下無度，束之奈何？

雷公这里问的和《外揣》篇中黄帝问的类似，如何把大小无极、高下无度的九针浑束为一呢？黄帝让他斋宿三日，歃血受盟而传其方、授其书。

方又是什么意思？

内经中很多篇章中都有“愿闻其方”，大概是规律、道理、具体或者详细情况这个意思，《外揣》篇中说“非道，何可小大深淺，雜合而為一乎。”而康熙字典有一个解释“又道也。《易·恆卦》君子以立不易方。《註》方，猶道也。《禮·樂記》樂行而民鄕方。《註》方，猶道也。”那么字义和文义能合到一起。所以本篇中的传方传的就是九针之道：

《禁服》凡刺之理，經脈為始，營其所行，知其度量，內刺五藏，外刺六府，審察衛氣，為百病母，調其虛實，虛實乃止，寫其血絡，血盡不殆矣。
《終始》凡刺之道，畢於終始，明知終始，五藏為紀，陰陽定矣。陰者主藏，陽者主府，陽受氣於四末，陰受氣於五藏，故寫者迎之，補者隨之，知迎知隨，氣可令和，和氣之方，必通陰陽。五藏為陰，六府為陽，傳之後世，以血為盟。

这些说的都是类似的东西。



《六節藏象論》帝曰：善。余聞氣合而有形，因變以正名。天地之運，陰陽之化，其於萬物，孰少孰多，可得聞乎。歧伯曰：悉哉問也，天至廣不可度，地至大不可量，大神靈問，請陳其方。……天食人以五氣，地食人以五味。五氣入鼻，藏於心肺，上使五色脩明，音聲能彰。五味入口，藏於腸胃，味有所藏，以養五氣，氣和而生津液相成，神乃自生。
《三部九候論》黃帝問曰：余聞九鍼於夫子，眾多博大，不可勝數。余願聞要道，以屬子孫，傳之後世，著之骨髓，藏之肝肺，歃血而受，不敢妄泄，令合天道，必有終始，上應天光星辰歷紀，下副四時五行，貴賤更互，冬陰夏陽，以人應之奈何，願聞其方。歧伯對曰：……故人有三部，部有三候，以決死生，以處百病，以調虛實，而除邪疾。
《寶命全形論》帝曰：人生有形，不離陰陽，天地合氣，別為九野，分為四時，月有小大，日有短長，萬物並至，不可勝量，虛實呿吟，敢問其方。歧伯曰：……
《鍼解》帝曰：余聞九鍼，上應天地四時陰陽，願聞其方，令可傳於後世以為常也。
《標本病傳論》黃帝問曰：病有標本，刺有逆從，柰何。歧伯對曰：凡刺之方，必別陰陽，前後相應，逆從得施，標本相移。
《天元紀大論》故物生謂之化，物極謂之變，陰陽不測謂之神，神用無方謂之聖。
《壽夭剛柔》黃帝問於少師曰：余聞人之生也，有剛有柔，有弱有強，有短有長，有陰有陽，願聞其方。少師答曰：陰中有陰，陽中有陽，審知陰陽，刺之有方。
《口問》黃帝曰：願聞口傳。歧伯答曰：夫百病之始生也，皆生於風雨寒暑，陰陽喜怒，飲食居處，大驚卒恐。則血氣分離，陰陽破敗，經絡厥絕，脈道不通，陰陽相逆，衛氣稽留，經脈虛空，血氣不次，乃失其常。論不在經者，請道其方。
《本藏》凡此二十五者，各不同，或善或惡，或吉或凶，請言其方。
《百病始生》三部之氣所傷異類，願聞其會，歧伯曰：三部之氣各不同或起於陰或起於陽請言其方，喜怒不節則傷藏，藏傷則病起於陰也，清濕襲虛，則病起於下，風雨襲虛，則病起於上，是謂三部，至於其淫泆，不可勝數。
《行鍼》凡此六者，各不同形，願聞其方。
《憂恚無言》黃帝問於少師曰：人之卒然憂恚，而言無音者，何道之塞？何氣出行？使音不彰？願聞其方。
《邪客》黃帝問於歧伯曰：余願聞持鍼之數，內鍼之理，縱舍之意，扞皮開腠理，奈何？脈之屈折，出入之處，焉至而出，焉至而止，焉至而徐，焉至而疾，焉至而入，六府之輸於身者，余願盡聞，少序別離之處，離而入陰，別而入陽，此何道而從行，願盡聞其方。歧伯曰：帝之所問，鍼道畢矣。
《刺節真邪》歧伯曰：凡刺五邪之方，不過五章，癉熱消滅，腫聚散亡，寒痺益溫，小者益陽；大者必去，請道其方。



=== 约

《禁服》士之才力，或有厚薄，智慮褊淺，不能博大深奧，自強於學若細子。細子恐其散於後世，絕於子孫，敢問約之奈何？
《禁服》雷公曰：此皆細子之所以通，未知其所約也。黃帝曰：夫約方者，猶約囊也，囊滿而弗約，則輸泄，方成弗約，則神與弗俱。雷公曰：願為下材者，勿滿而約之。黃帝曰：未滿而知約之以為工，不可以為天下師。

约又是什么意思呢？说文解字“纏束也。”就是拿绳子束起来。

《逆順》黃帝問于伯高曰：……刺有大約，可得聞乎？伯高曰：……刺之大約者，必明知病之可刺，與其未可刺，與其已不可刺也。
《陰陽二十五人》黃帝曰：二十五人者，刺之有約乎？歧伯曰：……審察其形氣有餘不足而調之，可以知逆順矣。黃帝曰：刺其諸陰陽奈何？歧伯曰：……故曰：氣有餘於上者，導而下之，氣不足於上者，推而休之，其稽留不至者，因而迎之，必明於經隧，乃能持之，寒與熱爭者，導而行之，其宛陳血不結者，則而予之，必先明知二十五人則血氣之所在，左右上下，刺約畢也。
《五常政大論》有毒無毒，服有約乎。歧伯曰：病有久新，方有大小，有毒無毒，固宜常制矣。
《至真要大論》帝曰：氣有多少，病有盛衰，治有緩急，方有大小，願聞其約柰何。歧伯曰：氣有高下，病有遠近，證有中外，治有輕重，適其至所為故也。

是不是可以认为是一种准则，有所约束的准则。

雷公听了

== 背腧

=== 定位

《血氣形志》欲知背俞，先度其兩乳間，中折之，更以他草度去半已，即以兩隅相拄也，乃舉以度其背，令其一隅居上，齊脊大椎，兩隅在下，當其下隅者，肺之俞也。得下一度，心之俞也。復下一度，左角肝之俞也，右角脾之俞也。復下一度，腎之俞也。是謂五藏之俞，灸刺之度也。

《背腧》黃帝問于歧伯曰：願聞五藏之腧，出於背者。歧伯曰：背中大腧，在杼骨之端，肺腧在三焦之間，心腧在五焦之間，膈腧在七焦之間，肝腧在九焦之間，脾腧在十一焦之間，腎腧在十四焦之間。皆挾脊相去三寸所，則欲得而驗之，按其處，應在中而痛解，乃其輸也。

但更重要的是在附近找反应点：

《背腧》皆挾脊相去三寸所，則欲得而驗之，按其處，應在中而痛解，乃其輸也。
《五邪》邪在肺……取之膺中外喻，背三節五藏之傍，以手疾按之，快然，乃刺之。
《癩狂病》厥逆腹脹滿，腸鳴，胸滿不得息，取之下胸二脅，咳而動手者，與背輸，以手按之，立快者是也。
《舉痛論》寒氣客於背俞之脈……，按之則熱氣至，熱氣至則痛止矣。

=== 意义

《衛氣》足少陰之本，在內踝下上三寸中，標在背輸與舌下兩脈也。
《衛氣》足厥陰之本，在行間上五寸所，標在背腧也。
《衛氣》足太陰之本，在中封前上四寸之中，標在背腧與舌本也。
《衛氣》手少陰之本，在銳骨之端，標在背腧也。
《衛氣》氣在胸者，止之膺與背腧；氣在腹者，止之背腧，與沖脈於臍左右之動脈者；

=== 适应证

《刺瘧》瘧脈滿大，急刺背俞，用中鍼傍伍胠俞各一，適肥瘦出其血也。
《刺瘧》瘧脈滿大，急刺背俞，用五胠俞背俞各一，適行至於血也。
《終始》膺俞中膺，背俞中背，肩膊虛者，取之上。
《長刺節論》陰刺，入一傍四處。治寒熱。深專者，刺大藏，迫藏刺背，背俞也。刺之迫藏，藏會，腹中寒熱去而止，與刺之要，發鍼而淺出血。
《骨空論》灸寒熱之法，先灸項大椎，以年為壯數，次灸橛骨，以年為壯數，視背俞陷者灸之，……凡當灸二十九處。
《五邪》邪在肺，則病皮膚痛，寒熱，上氣喘，汗出，欬動肩背。取之膺中外喻，背三節五藏之傍，以手疾按之，快然，乃刺之。取之缺盆中以越之。
《癩狂病》厥逆腹脹滿，腸鳴，胸滿不得息，取之下胸二脅，咳而動手者，與背輸，以手按之，立快者是也。
《舉痛論》寒氣客於背俞之脈則脈泣，脈泣則血虛，血虛則痛，其俞注於心，故相引而痛，按之則熱氣至，熱氣至則痛止矣。

《水熱穴論》帝曰：夫子言治熱病五十九俞，余論其意，未能領別其處，願聞其處，因聞其意。歧伯曰：頭上五行行五者，以越諸陽之熱逆也。……五藏俞傍五此十者，以寫五藏之熱也。凡此五十九穴者，皆熱之左右也。

看起来很多是热证，不知道对不对。

=== 死证

《寒熱病》五藏，身有五部：伏兔一；腓二，腓者腨也；背三，五藏之輸四；項五。此五部有癰疽者死。

== 卫气

=== 五藏六府

==== 定义

《五藏別論》所謂五藏者，藏精氣而不寫也，故滿而不能實。六府者，傳化物而不藏，故實而不能滿也。
《金匱真言論》肝心脾肺腎五藏，皆為陰。膽胃大腸小腸膀胱三焦六府，皆為陽。

《五藏別論》夫胃大腸小腸三焦膀胱，此五者，天氣之所生也，其氣象天故寫而不藏，此受五藏濁氣，名曰傳化之府，此不能久留輸寫者也。
《五藏別論》歧伯對曰：腦髓骨脈膽女子胞，此六者地氣之所生也，皆藏於陰而象於地，故藏而不寫，名曰奇恆之府。

==== 功能

《衛氣》黃帝曰：五藏者，所以藏精神魂魄者也；六府者，所以受水谷而行化物者也。其氣內干五藏，而外絡肢節。
《經水》五藏者，合神氣魂魄而藏之；六府者，受穀而行之，受氣而揚之；經脈者，受血而營之。
《本藏》五藏者，所以藏精神血氣魂魄者也；六府者，所以化水穀而行津液者也。
《天年》歧伯曰：五藏堅固，血脈和調，肌肉解利，皮膚致密，營衛之行，不失其常，呼吸微徐，氣以度行，六府化穀，津液布揚，各如其常，故能長久。

==== 营卫经脉

《衛氣》其浮氣之不循經者，為衛氣；其精氣之行於經者，為營氣。陰陽相隨，外內相貫，如環之無端。
《邪客》伯高曰：五穀入于胃也，其糟粕津液宗氣，分為三隧。故宗氣積於胸中，出於喉嚨，以貫心脈，而行呼吸焉。營氣者，泌其津液，注之於脈，化以為血，以榮四末，內注五藏六府，以應刻數焉。衛氣者，出其悍氣之慓疾，而先行於四末分肉皮膚之間，而不休者也。晝日行於陽，夜行於陰，常從足少陰之分間，行於五藏六府，
《痺論》帝曰：榮衛之氣，亦令人痺乎。歧伯曰：榮者水穀之精氣也，和調於五藏，灑陳於六府，乃能入於脈也；故循脈上下，貫五藏絡六府也。衛者水穀之悍氣也，其氣慓疾滑利，不能入於脈也；故循皮膚之中，分肉之閒，熏於肓膜，散於胸腹，逆其氣則病，從其氣則愈。
《營衛生會》歧伯答曰：人受氣于穀，穀入于胃，以傳與肺，五藏六府，皆以受氣，其清者為營，濁者為衛，營在脈中，衛在脈外，營週不休，五十而復大會，陰陽相貫，如環無端，衛氣行于陰二十五度，行于陽二十五度，分為晝夜，故氣至陽而起，至陰而止。

《脈度》歧伯答曰：氣之不得無行也，如水之流，如日月之行不休，故陰脈榮其藏，陽脈榮其府，如環之無端，莫知其紀，終而復始，其流溢之氣，內溉藏府，外濡腠理。
《海論》夫十二經脈者，內屬於府藏，外絡於肢節，
《玉版》歧伯曰：人之所受氣者，谷也。谷之所注者，胃也。胃者，水谷氣血之海也。海之所行云氣者，天下也。胃之所出氣血者，經隧也。而隧者，五藏六府之大絡也，迎而奪之而已矣。

==== 六府之化物

六府所行之化物是什么呢？

《經水》六府者，受穀而行之，受氣而揚之；
《本藏》六府者，所以化水穀而行津液者也。
《天年》歧伯曰：……六府化穀，津液布揚，……

《天元紀大論》故物生謂之化，物極謂之變，陰陽不測謂之神，神用無方謂之聖。
《六微旨大論》歧伯曰：夫物之生從於化，物之極由乎變，變化之相薄，成敗之所由也。

《本輸》大腸者，傳道之府。小腸者，受盛之府。膽者中精之府。胃者五穀之府。膀胱者津液之府也。三焦者，中瀆之府也，水道出焉，屬膀胱，是孤之府也，是六府之所與合者。
《刺法論》胃為倉廩之官，五味出焉，可刺胃之源。大腸者，傳道之官，變化出焉，可刺大腸之源。小腸者，受盛之官，化物出焉，可刺小腸之源。三焦者，決瀆之官，水道出焉，刺三焦之源。膀胱者，州都之官，津液藏焉，氣化則能出矣，刺膀胱之源。

可以看出，其化物主要是津液，由水谷气而生，而营卫也许是津液的不同存在状态。

== 痛

《論勇》少俞曰：夫忍痛與不忍痛者，皮膚之薄厚，肌肉之堅脆，緩急之分也，非勇怯之謂也。
《論痛》少俞曰：人之骨強、筋弱、肉緩、皮膚厚者，耐痛，其于鍼石之痛火焫亦然。
《論痛》黃帝曰：其耐火焫者，何以知之？少俞答曰：加以黑色而美骨者，耐火焫。黃帝曰：其不耐鍼石之痛者，何以知之？少俞曰：堅肉薄皮者，不耐鍼石之痛，於火焫亦然。

内经里说得很清楚了，骨強、筋弱、肉緩、皮膚厚的人耐痛，但这是为什么呢？还有一个大问题是：人为什么会痛？

《陰陽應象大論》寒傷形，熱傷氣。氣傷痛，形傷腫。

也就说气伤了会痛，气伤仅仅是不足吗？有余会不会也会痛？还待仔细研究。

《五閱五使》曰：善。五色獨決於明堂乎？歧伯曰：五官已辨，闕庭必張，乃立明堂，明堂廣大，蕃蔽見外，方壁高基，引垂居外，五色乃治，平搏廣大，壽中百歲，見此者，刺之必已，如是之人者，血氣有餘，肌肉堅致，故可苦以鍼。

=== 毒药

《異法方宜論》故邪不能傷其形體，其病生於內，其治宜毒藥，
《移精變氣論》今世治病，毒藥治其內，鍼石治其外，或愈或不愈，何也。
《湯液醪醴論》歧伯曰：當今之世，必齊毒藥攻其中，鑱石鍼艾治其外也。

毒药治内，针石治外。

《五常政大論》能毒者以厚藥，不勝毒者以薄藥，此之謂也。
《論痛》腸胃之厚薄堅脆亦不等，其於毒藥何如？
《論痛》黃帝曰：人之勝毒，何以知之？少俞曰：胃厚、色黑、大骨及肥者，皆勝毒；故其瘦而薄胃者，皆不勝毒也。
《本藏》脾應肉，肉䐃堅大者，胃厚；肉䐃么者，胃薄。

为何胃厚、色黑、大骨及肥者胜毒，不解。

=== 病难已易已

《平人氣象論》脈從陰陽，病易已；脈逆陰陽，病難已。脈得四時之順，曰病无他；脈反四時及不閒藏，曰難已。
《玉機真藏論》色澤以浮，謂之易已；……形氣相失，謂之難治；色夭不澤，謂之難已；……病熱脈靜，泄而脈大，脫血而脈實，病在中脈實堅，病在外，脈不實堅者，皆難治。
《五色》脈之浮沉及人迎與寸口氣小大等者，病難已；病之在藏，沉而大者，易已，小為逆；病在府，浮而大者，其病易已。
《論疾診尺》人病，其寸口之脈，與人迎之脈小大等，及其浮沉等者，病難已也。

逆则难已，顺则易已。

《刺瘧》足太陽之瘧，令人腰痛頭重，寒從背起，先寒後熱，熇熇暍暍然，熱止汗出，難已，刺郄中出血。……足少陰之瘧，令人嘔吐甚，多寒熱，熱多寒少；欲閉戶牖而處，其病難已。
《衛氣》痛可移者，易已也；積不痛，難已也。
《論疾診尺》嬰兒病……大便赤瓣飧泄，脈小者，手足寒，難已；
《痺論》諸痺不已，亦益內也，其風氣勝者，其人易已也。帝曰：痺，其時有死者，或疼久者，或易已者，其故何也。歧伯曰：其入藏者死，其留連筋骨閒者疼久，其留皮膚閒者易已。

阴病难已，阳病易已。阴胜难已，阳胜易已。

《論痛》少俞曰：同時而傷，其身多熱者，易已；多寒者，難已。

具体看看身热身寒的不同。

《衛氣失常》黃帝曰：身之寒溫何如？伯高曰：膏者，其肉淖而麤理者，身寒，細理者，身熱。脂者，其肉堅，細理者熱，麤理者寒。
《脈要精微論》陽氣有餘，為身熱无汗，陰氣有餘，為多汗身寒，陰陽有餘，則无汗而寒。
《刺節真邪》歧伯曰：是陽氣有餘，而陰氣不足，陰氣不足則內熱，陽氣有餘則外熱，內熱相搏，熱於懷炭，外畏綿帛近，不可近身，又不可近席。
《逆調論》黃帝問曰：人身非常溫也，非常熱也，為之熱而煩滿者何也。歧伯對曰：陰氣少而陽氣勝，故熱而煩滿也。
《逆調論》帝曰：人身非衣寒也，中非有寒氣也，寒從中生者何。歧伯曰：是人多痺氣也，陽氣少，陰氣多，故身寒如從水中出。
《陰陽應象大論》歧伯曰：陽勝則身熱，腠理閉，喘麤為之俛仰，汗不出而熱，齒乾以煩冤腹滿，死，能冬不能夏。陰勝則身寒汗出，身常清，數慄而寒，寒則厥，厥則腹滿，死，能夏不能冬。此陰陽更勝之變，病之形能也。
《瘧論》陰虛而陽盛，陽盛則熱矣，衰則氣復反入，入則陽虛，陽虛則寒矣，

基本上是阳气有余则热，阴气有余则寒。所以身多热易已，多寒难已。


《脈解》太陽所謂腫腰脽痛者，正月太陽寅，寅，太陽也，正月陽氣出在上，而陰氣盛，陽未得自次也，故腫腰脽痛也。
少陽所謂心脇痛者，言少陽盛也，盛者心之所表也。九月陽氣盡而陰氣盛，故心脇痛也，
所謂胸痛少氣者，水氣在藏府也，水者，陰氣也，陰氣在中，故胸痛少氣也。
所謂客孫脈則頭痛鼻鼽腹腫者，陽明并於上，上者，則其孫絡太陰也，故頭痛鼻鼽腹腫也。
少陰所謂腰痛者，少陰者，腎也，十月萬物陽氣皆傷，故腰痛也；
所謂腰脊痛不可以俛仰者，三月一振榮華萬物，一俛而不仰也。

《調經論》帝曰：風雨之傷人柰何。歧伯曰：風雨之傷人也，先客於皮膚，傳入於孫脈，孫脈滿則傳入於絡脈，絡脈滿則輸於大經脈，血氣與邪并客於分腠之閒，其脈堅大，故曰實。實者外堅充滿，不可按之，按之則痛。帝曰：寒濕之傷人柰何。歧伯曰：寒濕之中人也，皮膚不收，肌肉堅緊，榮血泣，衛氣去，故曰虛。虛者聶辟氣不足，按之則氣足以溫之，故快然而不痛。

《繆刺論》邪客於五藏之閒，其病也，脈引而痛，
《舉痛論》帝曰：願聞人之五藏卒痛，何氣使然。歧伯對曰：經脈流行不止，環周不休，寒氣入經而稽遲，泣而不行，客於脈外則血少，客於脈中則氣不通，故卒然而痛。
《舉痛論》寒氣客於脈外，則脈寒，脈寒則縮踡，縮踡則脈絀急，則外引小絡，故卒然而痛，得炅則痛立止，因重中於寒，則痛久矣。
寒氣客於經脈之中，與炅氣相薄，則脈滿，滿則痛而不可按也。
寒氣稽留，炅氣從上，則脈充大而血氣亂，故痛甚不可按也。
寒氣客於腸胃之閒，膜原之下，血不得散，小絡急引故痛，按之則血氣散，故按之痛止。
寒氣客於背俞之脈則脈泣，脈泣則血虛，血虛則痛，其俞注於心，故相引而痛，按之則熱氣至，熱氣至則痛止矣。
寒氣客於五藏，厥逆上泄，陰氣竭，陽氣未入，故卒然痛死不知人，氣復反，則生矣。
寒氣客於腸胃，厥逆上出，故痛而嘔也。
氣客於小腸，小腸不得成聚，故後泄腹痛矣。
熱氣留於小腸，腸中痛，癉熱焦渴，則堅乾不得出，故痛而閉不通矣。


《終始》刺諸痛者，其脈皆實。
病痛者，陰也，痛而以手按之不得者，陰也，深刺之。

《周痺》風寒濕氣，客於外分肉之間，迫切而為沫，沫得寒則聚，聚則排分肉而分裂也，分裂則痛，痛則神歸之，神歸之則熱，熱則痛解，痛解則厥，厥則他痺發，發則如是。
《五癃津液別》天暑衣厚則腠理開，故汗出，寒留於分肉之間，聚沫則為痛。

《壽夭剛柔》病有形而不痛者，陽之類也；無形而痛者，陰之類也。無形而痛者，其陽完而陰傷之也。急治其陰，無攻其陽。有形而不痛者，其陰完而陽傷之也。急治其陽，無攻其陰。
《壽夭剛柔》黃帝曰：營衛寒痺之為病奈何？伯高答曰：營之生病也，寒熱少氣，血上下行。衛之生病也，氣痛時來時去，怫愾賁響，風寒客於腸胃之中。寒痺之為病也，留而不去，時痛而皮不仁。

《異法方宜論》故邪不能傷其形體，其病生於內，其治宜毒藥，
《移精變氣論》今世治病，毒藥治其內，鍼石治其外，或愈或不愈，何也。
《湯液醪醴論》歧伯曰：當今之世，必齊毒藥攻其中，鑱石鍼艾治其外也。

《五常政大論》能毒者以厚藥，不勝毒者以薄藥，此之謂也。
《論痛》腸胃之厚薄堅脆亦不等，其於毒藥何如？
《論痛》黃帝曰：人之勝毒，何以知之？少俞曰：胃厚、色黑、大骨及肥者，皆勝毒；故其瘦而薄胃者，皆不勝毒也。
《本藏》脾應肉，肉䐃堅大者，胃厚；肉䐃么者，胃薄。

== 天年

=== 基和楯

《經脈》黃帝曰：人始生，先成精，精成而腦髓生，骨為幹，脈為營，筋為剛，肉為牆，皮膚堅而毛髮長，穀入于胃，脈道以通，血氣乃行。
《天年》黃帝曰：何者為神？歧伯曰：血氣已和，營衛已通，五藏已成，神氣舍心，魂魄畢具，乃成為人。

《天年》黃帝問于歧伯曰：願聞人之始生，何氣築為基，何立而為楯，……歧伯曰：以母為基，以父為楯；

本篇说的是天年，其中包括了先天和后天，我觉得精为先天，气血为后天，所以这里先天精气为母为基，后天气血为父为楯，而成人，得神而生，失神而死。

=== 寿与不寿

如何能长寿呢？

《天年》黃帝曰：人之壽夭各不同，或夭壽，或卒死，或病久，願聞其道。歧伯曰：五藏堅固，血脈和調，肌肉解利，皮膚致密，營衛之行，不失其常，呼吸微徐，氣以度行，六府化穀，津液布揚，各如其常，故能長久。

有的人度百岁而去，是什么原因？

《天年》黃帝曰：人之壽百歲而死，何以致之？歧伯曰：使道隧以長，基牆高以方，通調營衛，三部三里起，骨高肉滿，百歲乃得終。
《五閱五使》曰：善。五色獨決於明堂乎？歧伯曰：五官已辨，闕庭必張，乃立明堂，明堂廣大，蕃蔽見外，方壁高基，引垂居外，五色乃治，平搏廣大，壽中百歲，見此者，刺之必已，如是之人者，血氣有餘，肌肉堅致，故可苦以鍼。
《五色》雷公問於黃帝曰：五色獨決於明堂乎？小子未知其所謂也。黃帝曰：明堂者，鼻也；闕者，眉間也；庭者，顏也；蕃者，頰側也；蔽者，耳門也。其間欲方大，去之十步，皆見於外，如是者壽，必中百歲。
《本藏》帝曰：……願聞人之有不可病者，至盡天壽，……願聞其故。歧伯曰：五藏六府，邪之舍也，請言其故。……五藏皆堅者，無病；

而有的人不能终寿而死，为什么呢？

《天年》黃帝曰：其不能終壽而死者，何如？歧伯曰：其五藏皆不堅，使道不長，空外以張，喘息暴疾；又卑基牆薄，脈少血，其肉不石，數中風寒，血氣虛，脈不通，真邪相攻，亂而相引，故中壽而盡也。

寿与不寿以及是否能尽天年，有先天后天两方面原因，五藏是否坚固、使道长短、墙基高卑这些是先天因素，还有血脉、肌肉、皮肤、气血运行等后天因素。先天估计只有真人和至人才能改变，所以大多数人只能向圣人和贤人这个方向努力：

《上古天真論》上古之人，其知道者，法於陰陽，和於術數，食飲有節，起居有常，不妄作勞，故能形與神俱，而盡終其天年，度百歲乃去。
《上古天真論》夫上古聖人之教下也，皆謂之虛邪賊風，避之有時，恬惔虛无，真氣從之，精神內守，病安從來。是以志閑而少欲，心安而不懼，形勞而不倦，氣從以順，各從其欲，皆得所願。故美其食，任其服，樂其俗，高下不相慕，其民故曰朴。是以嗜欲不能勞其目，淫邪不能惑其心，愚智賢不肖不懼於物，故合於道。所以能年皆度百歲，而動作不衰者，以其德全不危也。
《上古天真論》其次有聖人者，處天地之和，從八風之理，適嗜欲於世俗之間，无恚嗔之心，行不欲離於世，被服章，舉不欲觀於俗，外不勞形於事，內无思想之患，以恬愉為務，以自得為功，形體不敝，精神不散，亦可以百數。

=== 气之盛衰

《上古天真論》女子七歲，腎氣盛，齒更髮長；
《上古天真論》丈夫八歲，腎氣實，髮長齒更；
《天年》人生十歲，五藏始定，血氣已通，其氣在下，故好走；
《上古天真論》二七而天癸至，任脈通，太衝脈盛，月事以時下，故有子；
《上古天真論》二八，腎氣盛，天癸至，精氣溢寫，陰陽和，故能有子；

《天年》二十歲，血氣始盛肌肉方長，故好趨；
《上古天真論》三七，腎氣平均，故真牙生而長極；
《上古天真論》三八，腎氣平均，筋骨勁強，故真牙生而長極；
《上古天真論》四七，筋骨堅，髮長極，身體盛壯；

《天年》三十歲，五藏大定，肌肉堅固，血脈盛滿，故好步；
《上古天真論》四八，筋骨隆盛，肌肉滿壯；
《上古天真論》五七，陽明脈衰，面始焦，髮始墮；

《天年》四十歲，五藏六府十二經脈，皆大盛以平定，腠理始疏，滎貨頹落，髮頗斑白，平盛不搖，故好坐；
《陰陽應象大論》年四十，而陰氣自半也，起居衰矣。
《上古天真論》五八，腎氣衰，髮墮齒槁；
《上古天真論》六七，三陽脈衰於上，面皆焦，髮始白；
《上古天真論》六八，陽氣衰竭於上，面焦，髮鬢頒白；
《上古天真論》七七，任脈虛，太衝脈衰少，天癸竭，地道不通，故形壞而無子也。

《天年》五十歲，肝氣始衰，肝葉始薄，膽汁始減，目始不明；
《陰陽應象大論》年五十，體重，耳目不聰明矣。
《上古天真論》七八，肝氣衰，筋不能動，天癸竭，精少，腎藏衰，形體皆極；

《天年》六十歲，心氣始衰，若憂悲，血氣懈惰，故好臥；
《陰陽應象大論》年六十，陰痿，氣大衰，九竅不利，下虛上實，涕泣俱出矣。
《上古天真論》八八，則齒髮去，腎者主水，受五藏六府之精而藏之，故五藏盛，乃能寫。今五藏皆衰，筋骨解墮，天癸盡矣。故髮鬢白，身體重，行步不正，而無子耳。

《天年》七十歲，脾氣虛，皮膚枯；
《天年》八十歲，肺氣衰，魄離，故言善誤；
《天年》九十歲，腎氣焦，四藏經脈空虛；
《天年》百歲，五藏皆虛，神氣皆去，形骸獨居而終矣。

=== 其他

《刺禁論》鬲肓之上，中有父母，七節之傍，中有小心，從之有福，逆之有咎。
《陰陽類論》雷公曰：臣悉盡意，受傳經脈，頌得從容之道，以合從容，不知陰陽，不知雌雄。帝曰：三陽為父，二陽為衛，一陽為紀。三陰為母，二陰為雌，一陰為獨使。

== 逆顺

=== 气之逆顺


《逆順》氣之逆順者，所以應天地陰陽四時五行也；

气的逆顺是指什么呢？

《陰陽應象大論》天有四時五行，以生長收藏，以生寒暑燥濕風。人有五藏，化五氣，以生喜怒悲憂恐。
《四氣調神大論》夫四時陰陽者，萬物之根本也。所以聖人春夏養陽，秋冬養陰，以從其根，故與萬物沈浮於生長之門。逆其根，則伐其本，壞其真矣。
《四氣調神大論》故陰陽四時者，萬物之終始也，死生之本也，逆之則災害生，從之則苛疾不起，是謂得道。……從陰陽則生，逆之則死，從之則治，逆之則亂。反順為逆，是謂內格。
《順氣一日分為四時》黃帝曰：願聞四時之氣。歧伯曰：春生，夏長，秋收，冬藏，是氣之常也，人亦應之，以一日分為四時，朝則為春，日中為夏，日入為秋，夜半為冬。

这是大象，春养生，夏养长，秋养收，冬养藏。

《八正神明論》四時者，所以分春秋冬夏之氣所在，以時調之也，
《本輸》黃帝問於歧伯曰：凡刺之道，必通十二經絡之所終始，絡脈之所別處，五俞之所留，六府之所與合，四時之所出入，五藏之所溜處，闊數之度，淺深之狀，高下所至。
《本輸》春取絡脈諸滎大經分肉之間，甚者深取之，間者淺取之。夏取諸俞孫絡肌肉皮膚之上。秋取諸合，餘如春法。冬取諸井諸俞之分，欲深而留之。此四時之序，氣之所處，病之所舍，藏之所宜。
《四時氣》黃帝問于歧伯曰：夫四時之氣，各不同形，百病之起，皆有所生，灸刺之道，何者為定？歧伯答曰：四時之氣，各有所在，灸刺之道，得氣穴為定。故春取經、血脈、分肉之間，甚者，深刺之，間者，淺刺之；夏取盛經孫絡，取分間絕皮膚；秋取經俞。邪在府，取之合；冬取井滎，必深以留之。

这是气在四时中的深浅定位。

《五亂》黃帝曰：經脈十二者，別為五行，分為四時，何失而亂？何得而治？歧伯曰：五行有序，四時有分，相順則治，相逆則亂。
《五亂》黃帝曰：何謂相順？歧伯曰：經脈十二者，以應十二月。十二月者，分為四時。四時者，春秋冬夏，其氣各異，營衛相隨，陰陽已知，清濁不相干，如是則順之而治。
《五亂》黃帝曰：何為逆而亂，歧伯曰：清氣在陰，濁氣在陽，營氣順脈，衛氣逆行，清濁相干

更为具体的脉气逆顺。

气之逆顺具有不同维度上的逆顺，一个是时间维度，一个是空间维度。

=== 脉之盛衰

《逆順》脈之盛衰者，所以候血氣之虛實有餘不足；

这也是定位（以及定性），如果说上面说的四时是 Z 轴，那么这一部分定位就是 X 和 Y 轴，根据脉的盛衰，看血气的虚实有余不足，再确定刺的部位。

=== 刺之大约

《逆順》刺之大約者，必明知病之可刺，與其未可刺，與其已不可刺也。

要知道刺的时机，时之可刺，时之未到以及时之已过。

《逆順》黃帝曰：候之奈何？伯高曰：兵法曰無迎逢逢之氣，無擊堂堂之陣。刺法曰：無刺熇熇之熱，無刺漉漉之汗，無刺渾渾之脈，無刺病與脈相逆者。
《瘧論》歧伯曰；經言無刺熇熇之熱，無刺渾渾之脈，無刺漉漉之汗，故為其病逆未可治也。

言当其时不可刺，我觉得就是下文中的其形盛之时也。

《逆順》黃帝曰：候其可刺奈何？伯高曰：上工，刺其未生者也；其次，刺其未盛者也；其次，刺其已衰者也。

刺邪之未生、未盛、已衰者，乃上工也。就是时之可刺。

《逆順》下工，刺其方襲者也；與其形之盛者也；與其病之與脈相逆者也。

而下工，刺邪来时、盛时以及病脉相逆时。

《逆順》故曰：方其盛也，勿敢毀傷，刺其已衰，事必大昌。

刺的时机总结。

《陰陽應象大論》故曰：病之始起也，可刺而已；其盛，可待衰而已。故因其輕而揚之，因其重而減之，因其衰而彰之。
《瘧論》故經言曰：方其盛時必毀，因其衰也，事必大昌。此之謂也。
《瘧論》夫瘧之未發也，陰未并陽，陽未并陰，因而調之，真氣得安，邪氣乃亡，故工不能治其已發，為其氣逆也。
《刺瘧》瘧者，其發各不同時，察其病形，以知其何脈之病也。先其發時如食頃而刺之，一刺則衰，二刺則知，三刺則已，……
《離合真邪》帝曰：候氣奈何。歧伯曰；夫邪去絡入於經也，舍於血脈之中，其寒溫未相得，如涌波之起也，時來時去，故不常在。故曰：方其來也，必按而止之，止而取之，無逢其衝而寫之。真氣者，經氣也，經氣太虛，故曰：其來不可逢，此之謂也。故曰：候邪不審，大氣已過，寫之則真氣脫，脫則不復，邪氣復至，而病益蓄，故曰：其往不可追，此之謂也。不可挂以髮者，待邪之至時而發鍼寫矣，若先若後者，血氣已盡，其病不可下，故曰：知其可取如發機，不知其取如扣椎，故曰：知機道者不可挂以髮，不知機者扣之不發，此之謂也。
《衛氣行》謹候其時，病可與期，失時反候者，百病不治。故曰：刺實者，刺其來也，刺虛者，刺其去也。此言氣存亡之時，以候虛實而刺之，是故謹候氣之所在而刺之，是謂逢時。
《五禁》黃帝問於歧伯曰：余聞刺有五禁，何謂五禁？歧伯曰：禁其不可刺也。黃帝曰：余聞刺有五奪。歧伯曰：無寫其不可奪者也。黃帝曰：余聞刺有五過。歧伯曰：補寫無過其度。黃帝曰：余聞刺有五逆。歧伯曰：病與脈相逆，命曰五逆。（还有更为具体的阐述）


=== 其他

《藏氣法時論》黃帝問曰：合人形以法四時五行而治，何如而從，何如而逆，得失之意，願聞其事。歧伯對曰：五行者，金木水火土也，更貴更賤，以知死生，以決成敗，而定五藏之氣，間甚之時，死生之期也。

《離合真邪》因不知合之四時五行，因加相勝，釋邪攻正，絕人長命。

《移精變氣論》上古使僦貸季，理色脈而通神明，合之金木水火土四時八風六合，不離其常，變化相移，以觀其妙，以知其要，欲知其要，則色脈是矣。色以應日，脈以應月，常求其要，則其要也。夫色之變化，以應四時之脈，此上帝之所貴，以合於神明也，所以遠死而近生。生道以長，命曰聖王。中古之治病，至而治之，湯液十日，以去八風五痺之病，十日不已，治以草蘇草荄之枝，本末為助，標本已得，邪氣乃服。暮世之治病也則不然，治不本四時，不知日月，不審逆從，病形已成，乃欲微鍼治其外，湯液治其內，粗工兇兇，以為可攻，故病未已，新病復起。

《論疾診尺》故曰：冬傷於寒，春生病熱；春傷於風，夏生飧泄腸僻，夏傷於暑，秋生痎瘧；秋傷於濕，冬生咳嗽。是謂四時之序也。

== 五味

《至真要大論》帝曰：善。五味陰陽之用何如。歧伯曰：辛甘發散為陽，酸苦涌泄為陰，鹹味涌泄為陰，淡味滲泄為陽。六者，或收，或散，或緩，或急，或燥，或潤，或耎，或堅，以所利而行之，調其氣，使其平也。

《九鍼論》五味：酸入肝，辛入肺，苦入心，甘入脾，鹹入腎，淡入胃，是謂五味。

《五常政大論》穀肉果菜，食養盡之，無使過之，傷其正也。
《生氣通天論》陰之所生，本在五味，陰之五宮，傷在五味。

《五藏生成》故心欲苦，肺欲辛，肝欲酸，脾欲甘，腎欲鹹，此五味之所合也。
五禁：肝病禁辛，心病禁咸，脾病禁酸，腎病禁甘，肺病禁苦。


《五色》腎乘心，心先病，腎為應，色皆如是。

我要整理的东西很多，但大多都是原文，而且也没写完，就先说一下对其中后三段的理解。这二段整理一下就是：

肝病者，青色宜酸，宜食麻犬肉李韭；
心病者，赤色宜苦，宜食麥羊肉杏薤；
脾病者，黃色宜甘，宜食糠米飯，牛肉棗葵；
肺病者，白色宜辛，宜食黃黍雞肉桃蔥。
腎病者，黑色宜咸，宜食大豆黃卷豬肉栗藿；

肝色青，宜食甘，糠米飯、牛肉、棗、葵皆甘。
心色赤，宜食酸，犬肉、麻、李、韭皆酸。
脾黃色，宜食咸，大豆、豬肉、栗、藿皆咸。
肺白色，宜食苦，麥、羊肉、杏、薤皆苦。
腎色黑，宜食辛，黃黍、雞肉、桃、蔥皆辛。

这两段类似又很矛盾。

《藏氣法時論》
肝欲散，急食辛以散之，用辛補之，酸寫之。
心欲耎，急食鹹以耎之，用鹹補之，甘寫之。
脾欲緩，急食甘以緩之，用苦寫之，甘補之。
肺欲收，急食酸以收之，用酸補之，辛寫之。
腎欲堅，急食苦以堅之，用苦補之，鹹寫之。

这段中的泻和上述第一段基本类似。

《藏氣法時論》
肝色青，宜食甘，粳米、牛肉、棗、葵皆甘。
心色赤，宜食酸，小豆、犬肉、李、韭皆酸。
脾色黃，宜食鹹，大豆、豕肉、栗、藿皆鹹。
肺色白，宜食苦，麥、羊肉、杏、薤皆苦。
腎色黑，宜食辛，黃黍、雞肉、桃、蔥皆辛。

辛散，酸收，甘緩，苦堅，鹹耎。毒藥攻邪，五穀為養，五果為助，五畜為益，五菜為充，氣味合而服之，以補精益氣。此五者。有辛酸甘苦鹹，各有所利，或散或收，或緩或急，或堅或耎，四時五藏，病隨五味所宜也。

《藏氣法時論》
肝苦急，急食甘以緩之。
心苦緩，急食酸以收之。
脾苦濕，急食甘以緩之。（错？应为咸？）
肺苦氣上逆，急食苦以泄之。
腎苦燥，急食辛以潤之

这两段跟上面第二种说法一样。

所以看起来说的不是同一回事。一个是欲，一个是苦，看着意思像是不足和太过。

不足的话，应该补其本身，也就是：
肝不足，补肝（辛）
心不足，补心（咸）
脾不足，补脾（甘）
肺不足，补肺（酸）
肾不足，补肾（苦）

太过的话，应该补其所胜，泻其本身。
肝太过，补脾（甘）
心太过，补肺（酸）
脾太过，补肾（苦）
肺太过，补肝（辛）
肾太过，补心（咸）

== 贼风

《賊風》帝曰：夫子言賊風邪氣之傷人也，令人病焉，今有其不離屏蔽，不出室穴之中，卒然病者，非不離賊風邪氣，其故何也？
《賊風》黃帝曰：今夫子之所言者，皆病人之所自知也。其毋所遇邪氣，又毋怵惕之所志，卒然而病者，其故何也？唯有因鬼神之事乎？

《本藏》有其不離屏蔽室內，無怵惕之恐，然猶不免於病，何也？願聞其故。
《本藏》帝曰：善。然非余之所問也，願聞……其有不離屏蔽室內，又無怵惕之恐，然不免於病者，何也？願聞其故。歧伯曰：……五藏皆脆者，不離於病。……

本藏和贼风两篇解释得一样，我觉得说的不是一回事。本藏说的可能是一种长期这样仍生病的，贼风说的可能是某一次的情况。但最后的原因是一样的，五藏脆弱就很容易受外感或内伤，有点风吹草动就发病了。

本篇中的卒然发病，是因为身故邪留而未发，五藏六府又伤，病发是早晚的事，非鬼神之事也。

《賊風》黃帝曰：其祝而已者，其故何也？歧伯曰：先巫者，因知百病之勝，先知其病之所從生者，可祝而已也。

巫者了解生百病的外部因素，又知道生病的内因，所以祝由可以治好病。但也不是一定能治好，跟病人的具体情况也有很大关系。

《移精變氣論》歧伯對曰：往古人居禽獸之閒，動作以避寒，陰居以避暑，內無眷慕之累，外無伸官之形，此恬憺之世，邪不能深入也。故毒藥不能治其內，鍼石不能治其外，故可移精祝由而已。
《移精變氣論》當今之世不然，憂患緣其內，苦形傷其外，又失四時之從，逆寒暑之宜，賊風數至，虛邪朝夕，內至五藏骨髓，外傷空竅肌膚，所以小病必甚，大病必死，故祝由不能已也。


== 玉版

《陰陽應象大論》故天有精，地有形，天有八紀，地有五里，故能為萬物之父母。

《本輸》陰尺動脈，在五裏，五俞之禁也。

《小鍼解》奪陰者死，言取尺之五裏五往者也。

《氣穴論》大禁二十五，在天府下五寸，

== 五禁

说文解字：
甲：一曰人頭宐爲甲，甲象人頭。
乙：乙承甲，象人頸。
丙：丙承乙，象人肩。
丁：丁承丙，象人心。
戊：戊承丁，象人脅。
己：己承戊，象人腹。
庚：庚承己，象人齊。
辛：辛承庚，象人股。
壬：壬承辛，象人脛。
癸：癸承壬，象人足。

也就是从造字开始，天干就有其特殊意义，比如时间、方位、象之于人等等。

干支记日有天干有地支，这里说的某某日自乘是什么意思呢？戊己日自乘四季，是不是说四季之月中的戊己日？那么其他的就是孟仲春的甲乙日、孟仲夏的丙丁日、孟仲秋的庚辛日、孟仲冬的壬癸日，各有十二天。

在这些日子里，不能针刺相应的部位，至于为什么，不清楚。

== 动输

《玉機真藏論》歧伯曰：五藏者，皆稟氣於胃，胃者，五藏之本也，藏氣者，不能自致於手太陰，必因於胃氣，乃至於手太陰也，故五藏各以其時，自為而至於手太陰也。故邪氣勝者，精氣衰也，故病甚者，胃氣不能與之俱至於手太陰，故真藏之氣獨見，獨見者病勝藏也，故曰死。

《動輸》胃為五藏六府之海，其清氣上注于肺，肺氣從太陰而行之，其行也，以息往來，故人一呼，脈再動，一吸脈亦再動，呼吸不已，故動而不止。
《動輸》胃氣上注于肺，
《口問》歧伯曰：穀入于胃，胃氣上注于肺。
《小鍼解》氣在中者，言水穀皆入于胃，其精氣上注于肺，濁溜于腸胃，言寒溫不適，飲食不節，而病生于腸胃，故命曰濁氣在中也。

《陰陽清濁》黃帝曰：夫陰清而陽濁，濁者有清，清者有濁，清濁別之奈何？歧伯曰：氣之大別，清者上注于肺，濁者下走于胃。胃之清氣，上出于口；肺之濁氣，下注于經，內積于海。

《邪客》故宗氣積於胸中，出於喉嚨，以貫心脈，而行呼吸焉。營氣者，泌其津液，注之於脈，化以為血，以榮四末，內注五藏六府，以應刻數焉。

=== 寸口

《動輸》黃帝曰：氣之過於寸口也，上十焉息，下八焉伏，何道從還？不知其極。歧伯曰：氣之離藏也，卒然如弓弩之發，如水之下岸，上於魚以及衰，其餘氣衰散以逆上，故其行微。

从字面意思上看，是说（营）气顺着手太阴肺脉，上至鱼际之后开始衰落，并逆（脉）而上。因其衰，其行微，所以入寸口只得八分。也就是说（营）气在手太阴肺脉运行过程中有一个逆行的阶段，形成寸脉为八分，顺行而形成尺脉为一寸。

这一运行过程在《邪客》中这样描述：

《邪客》歧伯曰：手太陰之脈，出於大指之端，內屈，循白肉際，至本節之後太淵，留以澹，外屈，上於本節下，內屈，與陰諸絡會於魚際，數脈並注，其氣滑利，伏行壅骨之下，外屈，出於寸口而行，

《經脈》肺手太陰之脈，下肘中，循臂內上骨下廉，入寸口，上魚，循魚際，出大指之端；
《本輸》肺……溜于魚際，魚際者，手魚也，為滎；注于太淵，太淵魚後一寸陷者中也，為俞；行於經渠，經渠寸口中也，動而不居為經；

结合穴位来说，其顺序可能是尺泽、经渠、鱼际、太渊、少商。

=== 人迎寸口

《至真要大論》帝曰：夫子言察陰陽所在而調之，論言人迎與寸口相應，若引繩小大齊等，命曰平，
《禁服》雷公曰：願聞為工。黃帝曰：寸口主中，人迎主外，兩者相應，俱往俱來，若引繩大小齊等。春夏人迎微大，秋冬寸口微大，如是者，名曰平人。
《動輸》故陰陽上下，其動也若一。故陽病而陽脈小者，為逆；陰病而陰脈大者，為逆。故陰陽俱靜俱動，若引繩相傾者病。
《終始》持其脈口人迎，以知陰陽有餘不足，平與不平，天道畢矣。所謂平人者不病，不病者，脈口人迎應四時也，上下相應而俱往來也，六經之脈不結動也，本末之寒溫之相守司也。形肉血氣必相稱也，是謂平人。
《四時氣》氣口候陰，人迎候陽也。

可以看出，寸口主中候阴，人迎主外候阳。《动输》前面提到寸口是营气在手太阴肺脉中形成的，那么它直接代表的是营气的运行状况，而深一层代表的是五藏六府的具体情况。而相应的，人迎直接代表的是卫气的运行状况，是人体的功能状况。两者引绳相等是为平人，两者引绳相倾就是有病了。

《動輸》黃帝曰：足之陽明，何因而動？歧伯曰：胃氣上注于肺，其悍氣上沖頭者，循咽，上走空竅，循眼系，入絡腦，出顑，下客主人，循牙車，合陽明，并下人迎，此胃氣別走於陽明者也。

这就说明了为什么人迎何以候卫气，是因为卫气分出一条路到足阳明脉而过人迎，从而形成人迎脉，以候卫气。

举个不恰当的例子，人体是个大工厂，五藏六府是固定资产，营气和卫气是现金流，营气是生产相关的现金流，而卫气是银行存款的现金流。寸口脉就是生产报表，人迎脉就是银行账单。

== 阴阳二十五人

《陰陽二十五人》……願聞二十五人之形，血氣之所生，別而以候，從外知內，何如？……歧伯曰：先立五形金木水火土，別其五色，異其五形之人，而二十五人具矣。……

就是说如何通过外候而辨别二十五人，歧伯说先立五形，别五色，二十五人具矣。

木：上足厥阴佗佗然、大左足少阳上遺遺然、左右足少阳下隨隨然、鈦右足少阳上推推然、判左足少阳下枯枯然
火：上手少阴核核然、质左手太阳上肌肌然、少右手太阳下慆慆然、右右手太阳上鮫鮫然、质判左手太阳下頤頤然
土：上足太阴敦敦然、大左足阳明上婉婉然、加左足阳明下坎坎然、少右足阳明上樞樞然、左右足阳明下兀兀然
金：上手太阴敦敦然、釱左手阳明上廉廉然、右左手阳明下脫脫然、左右手阳明上監監然、少右手阳明下嚴嚴然
水：上足少阴汗汗然、大右足太阳上頰頰然、少左足太阳下紆紆然、众右足太阳下潔潔然、桎左足太阳上安安然


角：少、上、正、太    右釱上大判
徵：少、上、正、太    右少质上判
宫：少、上、正、太    少上大加左
商：少、上、正、判    右少釱上左
羽：少、上、正、太    众桎上大少

== 行针

《行鍼》重陽之人，其神易動，其氣易往也，心肺之藏氣有餘，陽氣滑盛而揚，故神動而氣先行。（神動而氣先鍼行）

阳气滑盛，神易动而气易往，是不是这样的人不用针病也能很快好呢？比如用导引或者按摩之类的。

《行鍼》重陽之人，頗有陰者，其陰陽之離合難，故其神不能先行也。陰陽和調，而血氣淖澤滑利，故鍼入而氣出，疾而相逢也。（氣與鍼相逢）

《逆順肥瘦》黃帝曰：刺壯士真骨者，奈何？歧伯曰：刺壯士真骨，堅肉緩節，監監然，此人重則氣澀血濁，刺此者，深而留之，多益其數；勁則氣滑血清，刺此者，淺而疾之。
《陰陽清濁》黃帝曰：治之奈何？歧伯曰：清者其氣滑，濁者其氣澀，此氣之常也。故刺陰者，深而留之；刺陽者，淺而疾之；清濁相干者，以數調之也。
《根結》氣滑即出疾，其氣澀則出遲，氣悍則鍼小而入淺，氣澀則鍼大而入深，深則欲留，淺則欲疾。以此觀之，刺布衣者，深以留之，刺大人者，微以徐之，此皆因氣慓悍滑利也。

基本上浅刺疾出就够了。

《行鍼》其陰氣多而陽氣少，陰氣沉而陽氣浮者內藏，故鍼已出，氣乃隨其後，故獨行也。（鍼已出而氣獨行者）
《行鍼》此人之多陰而少陽，其氣沉而氣往難，故數刺乃知也。（數刺乃知）

相应地，要深刺久留并多刺几针。这两者是不是只是一个程度上的差别。

《行鍼》其氣逆與其數刺病益甚者，非陰陽之氣，浮沉之勢也。此皆麤之所敗，工之所失，其形氣無過焉。

发针后出现气逆或者病更重，不是病人形气本身的问题，是误治。

气逆的表现有哪些呢？

《通評虛實論》黃帝問曰：何謂虛實。歧伯對曰：邪氣盛則實，精氣奪則虛。帝曰：虛實何如。歧伯曰：氣虛者肺虛也，氣逆者足寒也，非其時則生，當其時則死。餘藏皆如此。
《通評虛實論》歧伯曰：絡氣不足，經氣有餘者，脈口熱而尺寒也，秋冬為逆，春夏為從，治主病者。帝曰：經虛絡滿何如。歧伯曰：經虛絡滿者，尺熱滿脈口寒濇也，此春夏死秋冬生也。
《通評虛實論》帝曰：何謂從則生，逆則死。歧伯曰：所謂從者，手足溫也。所謂逆者，手足寒也。
《逆調論》帝曰：人有逆氣不得臥而息有音者，有不得臥而息無音者，有起居如故而息有音者，有得臥行而喘者，有不得臥不能行而喘者，有不得臥臥而喘者，皆何藏使然，願聞其故。
《舉痛論》歧伯曰：怒則氣逆，甚則嘔血及飱泄，故氣上矣。
《五亂》黃帝曰：何為逆而亂，歧伯曰：清氣在陰，濁氣在陽，營氣順脈，衛氣逆行，清濁相干，亂於胸中，是謂大悗。故氣亂於心，則煩心密嘿，俛首靜伏；亂於肺，則俛仰喘喝，接手以呼；亂於腸胃，是為霍亂；亂於臂脛，則為四厥；亂於頭，則為厥逆，頭重眩仆。

这些以及更多的是病理性的气逆，不知道误治后会不会出现这样的情况。

《九鍼十二原》刺之害中而不去，則精泄；害中而去，則致氣。精泄則病益甚而恇，致氣則生為癰瘍。
《寒熱病》凡刺之害，中而不去則精泄；不中而去則致氣。精泄則病甚而慪，致氣則生為癰疽也。

《九鍼十二原》夫氣之在脈也，邪氣在上，濁氣在中，清氣在下。故鍼陷脈則邪氣出，鍼中脈則濁氣出，鍼太深則邪氣反沉、病益。故曰：皮肉筋脈，各有所處。病各有所宜。各不同形，各以任其所宜，無實無虛。損不足而益有餘，是謂甚病。病益甚，取五脈者死，取三脈者恇；奪陰者死，奪陽者狂，鍼害畢矣。

《官鍼》疾淺鍼深，內傷良肉，皮膚為癰；病深鍼淺，病氣不寫，支為大膿。病小鍼大，氣寫太甚，疾必為害；病大鍼小，氣不泄寫，亦復為敗。失鍼之宜。大者寫，小者不移。

《刺要論》黃帝問曰：願聞刺要。歧伯對曰：病有浮沈，刺有淺深，各至其理，無過其道；過之則內傷，不及則生外壅，壅則邪從之。淺深不得，反為大賊，內動五藏後生大病。故曰：病有在毫毛腠理者，有在皮膚者，有在肌肉者，有在脈者，有在筋者，有在骨者，有在髓者。是故刺毫毛腠理，無傷皮，皮傷則內動肺，肺動則秋病溫瘧，泝泝然寒慄；刺皮，無傷肉，肉傷則內動脾，脾動則七十二日四季之月，病腹脹煩，不嗜食；刺肉，無傷脈，脈傷則內動心，心動則夏病心痛；刺脈，無傷筋，筋傷則內動肝，肝動則春病熱而筋弛；刺筋無傷骨，骨傷則內動腎，腎動則冬病脹腰痛；刺骨，無傷髓，髓傷則銷鑠，胻酸，體解㑊然不去矣。

《四時刺逆從論》帝曰：逆四時而生亂氣，柰何。歧伯曰：春刺絡脈，血氣外溢，令人少氣。春刺肌肉，血氣環逆，令人上氣。春刺筋骨，血氣內著，令人腹脹。夏刺經脈，血氣乃竭，令人解㑊。夏刺肌肉，血氣內卻，令人善恐。夏刺筋骨，血氣上逆，令人善怒。秋刺經脈，血氣上逆，令人善忘。秋刺絡脈，氣不外行，令人臥不欲動。秋刺筋骨，血氣內散，令人寒慄。冬刺經脈，血氣皆脫，令人目不明。冬刺絡脈，內氣外泄，留為大痺。冬刺肌肉，陽氣竭絕，令人善忘。凡此四時刺者大逆之病，不可不從也，反之則生亂氣相淫病焉。

《邪氣藏府病形》黃帝曰：刺之有道乎？歧伯答曰：刺此者，必中氣穴，無中肉節。中氣穴，則鍼游於巷；中肉節，即皮膚痛；補寫反，則病益篤。中筋則筋緩，邪氣不出，與其真相搏亂而不去，反還內著。用鍼不審，以順為逆也。

《根結》故曰：刺不知逆順，真邪相搏。滿而補之，則陰陽四溢，腸胃充郭，肝肺內䐜，陰陽相錯。虛而寫之，則經脈空虛，血氣竭枯，腸胃㒤辟，皮膚薄著，毛腠夭膲，予之死期。

这些基本上就属于误治了。

== 上膈下膈

《官能》膈有上下，知其氣所在。

《上膈》黃帝曰：氣為上膈者，食飲入而還出，……蟲為下膈。下膈者，食晬時乃出，……

这里的“还”我觉得应该念 xuan，通“旋”，立刻、马上意思。《康熙字典》里有解释：又速也，卽也。

=== 食则呕与食不下

经过搜索，发现内经中出现了很多“食则呕”和“食不下”，有时候单独出现，有时候同时出现。

食则呕、食饮入则还出、下嗌还出，这些都比较好理解，就是入口以后或下到胃或者没下到胃，马上就呕吐。

食不下就不好理解了，是不能从哪里下到哪里呢？如果说不能下到胃，那就只能吐出来，跟食则呕没什么差别了。所以可能还有别的意思。

《五藏別論》所以然者，水穀入口，則胃實而腸虛；食下，則腸實而胃虛。

这段说明食下是指食饮从胃下到肠中，那么食不下就是食饮从胃不能下到肠中，也就是说食饮入口下胃，不能下到肠中，最终只能再吐出来，中间要过一段时间。

而食则呕基本是食饮入口立即、马上就呕吐。

而这正好是上膈和下膈的区别。

=== 两者都有

《四時氣》飲食不下，膈塞不通，邪在胃脘，在上脘，則刺抑而下之，在下脘，則散而去之
《風論》胃風之狀，頸多汗惡風，食飲不下，鬲塞不通，腹善滿，失衣則䐜脹，食寒則泄，診形瘦而腹大；
《邪氣藏府病形》胃病者，腹䐜脹，胃脘當心而痛，上肢兩脅，膈咽不通，食飲不下，取之三里也。
《陰陽別論》一陽發病，少氣善欬善泄；其傳為心掣，其傳為隔。

《六元正紀大論》木鬱之發，……故民病胃脘當心而痛，上支兩脇，鬲咽不通，食飲不下，甚則耳鳴眩轉，目不識人，善暴僵仆。
《至真要大論》歲厥陰在泉，風淫所勝，則地氣不明，平野昧，草迺早秀，民病洒洒振寒，善伸數欠，心痛支滿，兩脇裏急，飲食不下，鬲咽不通，食則嘔，腹脹善噫，得後與氣，則快然如衰，身體皆重。
《至真要大論》厥陰司天，風淫所勝，則太虛埃昏，雲物以擾，寒生春氣，流水不冰，民病胃脘當心而痛，上支兩脅，鬲咽不通，飲食不下，舌本強，食則嘔，冷泄腹脹溏泄瘕水閉，蟄蟲不去，病本于脾。

我认为其中鬲咽不通或者膈塞不通为上膈，饮食不下为下膈。

=== 上膈

《經脈》脾足太陰之脈，……是動則病舌本強，食則嘔，胃脘痛，腹脹，善噫，得後與氣，則快然如衰，身體皆重。
《脈解》太陰所謂病脹者，太陰子也，十一月萬物氣皆藏於中，故曰病脹；所謂上走心為噫者，陰盛而上走於陽明，陽明絡屬心，故曰上走心為噫也；所謂食則嘔者，物盛滿而上溢，故嘔也；
《邪氣藏府病形》脾脈急甚為瘈瘲；微急為膈中，食飲入而還出，後沃沫。
《厥論》太陰之厥，則腹滿䐜脹後不利不欲食，食則嘔不得臥；
《邪氣藏府病形》腎脈……緩甚為折脊；微緩為洞，洞者，食不化，下嗌還出。
《根結》太陰為開，……故開折，則倉廩無所輸，膈洞。膈洞者，取之太陰，視有餘不足，故開折者，氣不足而生病也。
《玉機真藏論》是故風者百病之長也，今風寒客於人，……弗治，肺即傳而行之肝，病名曰肝痺，一名曰厥，脇痛出食，當是之時，可按若刺耳。
《本藏》肺小則藏安，無脅下之病；肝大則逼胃迫咽，迫咽則苦膈中，且脅下痛。
《五藏生成》心煩頭痛病在鬲中，過在手巨陽，少陰。
《本藏》肉䐃多少裏累者，胃結，胃結者，上管約不利也。

上膈也就是胃上管约不利，是足太阴脉的是动病。

《氣交變大論》歲木太過，風氣流行，脾土受邪。民病飱泄食減，體重煩冤，腸鳴腹支滿，上應歲星。甚則忽忽善怒，眩冒巔疾，化氣不政，生氣獨治，雲物飛動，草木不寧，甚而搖落，反脇痛而吐甚，衝陽絕者，死不治，上應太白星。
《至真要大論》厥陰之勝，耳鳴頭眩，憒憒欲吐，胃鬲如寒，大風數舉，倮蟲不滋，胠脇氣并，化而為熱，小便黃赤，胃脘當心而痛，上支兩脇，腸鳴飱泄，少腹痛，注下赤白，甚則嘔吐，鬲咽不通。
《至真要大論》厥陰之復，少腹堅滿，裏急暴痛，偃木飛沙，倮蟲不榮，厥心痛，汗發嘔吐，飲食不入，入而復出，筋骨掉眩，清厥，甚則入脾，食痺而吐。衝陽絕，死不治。
《至真要大論》陽明之復，……，甚則心痛否滿，腹脹而泄，嘔苦欬噦煩心，病在鬲中頭痛，甚則入肝，驚駭筋攣。太衝絕，死不治。
《至真要大論》少陰在泉，……，主勝則厥氣上行，心痛發熱，鬲中眾痺皆作，發於胠脇魄汗不藏，四逆而起。

五运六气我还不太懂，看起来基本上是木克土。

=== 下膈

《上膈》下膈者，食晬時乃出，
《經脈》脾足太陰之脈，……是主脾所生病者，舌本痛，體不能動搖，食不下，煩心，心下急痛，溏瘕泄，水閉，黃疸，不能臥，強立，股膝內腫厥，足大趾不用。
《陰陽別論》二陽結謂之消，三陽結謂之隔，三陰結謂之水，一陰一陽結謂之喉痺。
《評熱病論》諸水病者，故不得臥，臥則驚，驚則欬甚也。腹中鳴者，病本於胃也。薄脾則煩不能食，食不下者，胃脘隔也。
《邪氣藏府病形》心脈急甚者為瘈瘲；徵急，為心痛引背，食不下。
《本藏》肉膕不稱身者，胃下，胃下者，下管約不利。

下膈就是下管约不利，是足太阴脉的所生病。

其实我觉得下膈不一定是一天一夜才吐，有可能朝食暮吐、暮食朝吐，或者吃完饭几个小时就吐，应该是看人的卫气如何，太不足了可能得一天，有点不足可能几个小时。

《氣交變大論》歲火不及，寒乃大行，……復則埃鬱大雨且至，黑氣迺辱，病鶩溏腹滿，食飲不下，寒中腸鳴，泄注腹痛，暴攣痿痺，足不任身，上應鎮星辰星，玄穀不成。
《氣交變大論》歲土不及，風迺大行，化氣不令，草木茂榮，飄揚而甚，秀而不實，上應歲星，民病飱泄霍亂，體重腹痛，筋骨繇復，肌肉瞤酸，善怒，歲氣舉事，蟄蟲早附，咸病寒中，上應歲星鎮星，其穀黅。
《本病論》太陰不退位，而取寒暑不時，埃昏布作，溫令不去，民病四支少力，食飲不下，泄注淋滿，足脛寒，陰痿閉塞，失溺小便數。
《本病論》陽明不退位，即春生清冷，草木晚榮，寒熱閒作，民病嘔吐暴注，食飲不下，大便乾燥，四肢不舉，目瞑掉眩。
《至真要大論》太陰在泉，……主勝則寒氣逆滿，食飲不下，甚則為疝。

这里说的虫有点像营卫之气的感觉。而痈是比较严重的结果，其他轻点的症状得看具体情况取穴，比如太阴、阳明、厥阴、少阴等等。


摘抄不全，有的不好判断是上膈还是下膈，大家有疑问可以讨论一下。


《玉版》黃帝曰：病之生時，有喜怒不測，飲食不節，陰氣不足，陽氣有餘，營氣不行，乃發為癰疽。陰陽不通，兩熱相搏，乃化為濃，小鍼能取之乎？

《太陰陽明論》故犯賊風虛邪者，陽受之；食飲不節起居不時者，陰受之。陽受之，則入六府，陰受之，則入五藏。入六府，則身熱不時臥，上為喘呼；入五藏則䐜滿閉塞，下為飱泄，久為腸澼。故喉主天氣，咽主地氣。

《調經論》帝曰：善。陰之生實柰何。歧伯曰：喜怒不節，則陰氣上逆，上逆則下虛，下虛則陽氣走之，故曰實矣。帝曰：陰之生虛柰何。歧伯曰：喜則氣下，悲則氣消，消則脈虛空，因寒飲食，寒氣熏滿，則血泣氣去，故曰虛矣。

《小鍼解》濁氣在中者，言水穀皆入于胃，其精氣上注于肺，濁溜于腸胃，言寒溫不適，飲食不節，而病生于腸胃，故命曰濁氣在中也。

《百病始生》黃帝曰：積之始生，至其已成，奈何？歧伯曰：積之始生，得寒乃生，厥乃成積也，黃帝曰：其成積奈何？歧伯曰：厥氣生足悗，悗生脛寒，脛寒則血脈凝澀，血脈凝澀則寒氣上入于腸胃，入于腸胃則䐜脹，䐜脹則腸外之汁沫迫聚不得散，日以成積。卒然多食飲，則腸滿，起居不節，用力過度，則絡脈傷，陽絡傷則血外溢，血外溢則衄血，陰絡傷則血內溢，血內溢則後血。腸胃之絡傷則血溢於腸外，腸外有寒，汁沫與血相搏，則併合凝聚不得散，而積成矣。卒然中外於寒，若內傷於憂怒，則氣上逆，氣上逆則六俞不通，溫氣不行，凝血蘊裏而不散，津液澀滲，著而不去，而積皆成矣。

《痺論》凡痺之類，逢寒則蟲，逢熱則縱。

《口問》黃帝曰：人之涎下者，何氣使然？歧伯曰：飲食者，皆入于胃，胃中有熱則蟲動，蟲動則胃緩，胃緩則廉泉開，故涎下，補足少陰。

《五癃津液別》中熱則胃中消穀，消穀則蟲上下作。腸胃充郭，故胃緩，胃緩則氣逆，故唾出。

《五味論》黃帝曰：甘走肉，多食之。令人悗心，何也？少俞曰：甘入于胃，其氣弱小，不能上至於上焦，而與谷留於胃中者，令人柔潤者也，胃柔則緩，緩則蟲動，蟲動則令人悗心。其氣外通於肉，故甘走肉。

《生氣通天論》營氣不從，逆於肉理，乃生癰腫。

《腹中論》帝曰：病有少腹盛，上下左右皆有根，此為何病，可治不歧伯曰：病名曰伏梁。帝曰：伏梁何因而得之。歧伯曰：裹大膿血，居腸胃之外，不可治，治之，每切按之致死。帝曰：何以然。歧伯曰：此下則因陰必下膿血，上則迫胃脘生鬲，俠胃脘內癰。此久病也難治。居齊上為逆，居齊下為從，勿動亟奪，論在刺法中。帝曰：人有身體髀股䯒皆腫，環齊而痛，是為何病。歧伯曰：病名伏梁，此風根也。其氣溢於大腸而著於肓，肓之原在齊下，故環齊而痛也。不可動之，動之為水溺濇之病。

《病能論》黃帝問曰：人病胃脘癰者，診當何如。歧伯對曰：診此者，當候胃脈，其脈當沈細，沈細者氣逆，逆者，人迎甚盛，甚盛則熱，人迎者胃脈也，逆而盛，則熱聚於胃口而不行，故胃脘為癰也。

《脈度》六府不合則留為癰

《五變》黃帝曰：人之善病腸中積聚者，何以候之？少俞答曰：皮膚薄而不澤，肉不堅而淖澤。如此，則腸胃惡，惡則邪氣留止，積聚乃傷脾胃之間，寒溫不次，邪氣稍至。蓄積留止，大聚乃起。

== 五态之人

《通天》这篇讲的是五态之人，应该在《阴阳二十五人》之前，因为《陰陽二十五人》中提到“其態又不合於眾者五，余已知之矣。”说的就是《通天》中的五态之人。

其中提到众人：

《骨度》黃帝曰：願聞眾人之度。人長七尺五寸者，其骨節之大小長短各幾何？
《衛氣失常》黃帝曰：三者之氣血多少何如？伯高曰：膏者，多氣，多氣者，熱，熱者耐寒。肉者，多血則充形，充形則平。脂者，其血清，氣滑少，故不能大。此別於眾人者也。
《衛氣失常》黃帝曰：眾人奈何？伯高曰：眾人皮肉脂膏，不能相加也，血與氣，不能相多，故其形不小不大，各自稱其身，命曰眾人。

众人我觉得就是一般人，大众，大部分人。

《通天》眾人之屬，不知五態之人者，故五五二十五人，而五態之人不與焉。五態之人，尤不合於眾者也。
《通天》凡五人者，其態不同，其筋骨氣血各不等。

众人可分为二十五人，而五态之人与众人相差太多，筋骨气血不等。

我觉得阴阳二十五人说的是人的先天分类，可以认为是人的先天体质，或者说是基因，基本上不太可能大变的。而本篇的五态之人说的是后天分类，是根据人的气血状况来分类，在一定程度上可以通过调养治疗来改变。

也就是说阴阳二十五人中，都会有太阴之人、少阴之人、太阳之人、少阳之人以及阴阳平和之人，就看气血偏得多少了。

先后天在一定范围之内是可以互相影响和改变的，比如体形、气质等等。

= 官能

我感觉《官能》这篇像是一个总结，将针灸的道、法、术高度凝炼，把这篇相关的内容扩展开来去了解、掌握、融会贯通，那么对于针灸就可以得于心、应于手了。

道：……刺道畢矣。说的是大道理。
法：……鍼論畢矣。说的是大原则。
术：是故工之用鍼也，……用鍼之要，無忘其神。说的是如何补泻。

明道、守法、施术、用器，针灸是难也不难，是不难也难。首先要看自己之能是否符合官能，再看自己是否努力。

== 诊尺

《陰陽應象大論》善診者，察色按脈，先別陰陽；審清濁，而知部分；視喘息，聽音聲，而知所苦；觀權衡規矩，而知病所主。按尺寸，觀浮沈滑濇，而知病所生；以治無過，以診則不失矣。
《方盛衰論》是以診有大方，……按脈動靜，循尺滑濇，寒溫之意，視其大小，……
《邪客》黃帝曰：持鍼縱舍奈何？歧伯曰：必先明知十二經脈之本末，皮膚之寒熱，脈之盛衰滑澀。……持其尺，察其肉之堅脆，大小滑澀，寒溫燥濕。因視目之五色，以知五藏，而決死生。視其血脈，察其色，以知其寒熱痛痺。
《論疾診尺》黃帝問于歧伯曰：余欲無視色持脈，獨調其尺，以言其病，從外知內，為之奈何？歧伯曰：審其尺之緩急小大滑澀，肉之堅脆，而病形定矣。
《邪氣藏府病形》夫色脈與尺之相應也，如桴鼓影響之相應也，不得相失也，此亦本末根葉之出候也，故根死則葉枯矣。色脈形肉，不得相失也。故知一則為工，知二則為神，知三則神且明矣。
《小鍼解》睹其色，察其目，知其散復，一其形，聽其動靜者，言上工知相五色於目，有知調尺寸小大緩急滑澀以言所病也。

从中可以看出，“尺”是和色、脉相对应的另一种诊断方法，以外知内，从而知病所生、定病形矣。这三者都是外候，都是疾病的外在表现，是医者观察、诊断疾病的窗口。内经中色脉相对比较多，尺肤比较少一点。

《脈要精微論》尺內兩傍，則季脅也，尺外以候腎，尺裏以候腹中。附上左，外以候肝，內以候鬲；右，外以候胃，內以候脾。上附上右，外以候肺，內以候胸中；左，外以候心，內以候膻中。前以候前，後以候後。上竟上者，胸喉中事也；下竟下者，少腹腰股膝脛足中事也。

这是人候在尺肤的对应关系。

《通評虛實論》帝曰：何謂重實。歧伯曰：所謂重實者，言大熱病，氣熱脈滿，是謂重實。帝曰：經絡俱實何如，何以治之。歧伯曰：經絡皆實，是寸脈急而尺緩也，皆當治之，……
《通評虛實論》帝曰：絡氣不足，經氣有餘，何如。歧伯曰：絡氣不足，經氣有餘者，脈口熱而尺寒也，秋冬為逆，春夏為從，治主病者。
《通評虛實論》帝曰：經虛絡滿何如。歧伯曰：經虛絡滿者，尺熱滿脈口寒濇也，此春夏死秋冬生也。帝曰：治此者奈何。歧伯曰：絡滿經虛，灸陰刺陽；經滿絡虛，刺陰灸陽。
《通評虛實論》帝曰：何謂重虛。歧伯曰：脈氣上虛尺虛，是謂重虛。帝曰：何以治之。歧伯曰：所謂氣虛者，言無常也。尺虛者，行步恇然。脈虛者，不象陰也。如此者，滑則生，濇則死也。
《通評虛實論》帝曰：其形盡滿何如。歧伯曰：其形盡滿者，脈急大堅，尺濇而不應也，

这里可以看出，尺候的主要是外，是形。

《論疾診尺》尺膚滑，其淖澤者，風也。尺肉弱者，解併，安臥脫肉者，寒熱，不治。尺膚滑而澤脂者，風也。尺膚澀者，風痺也。尺膚麤如枯魚之鱗者，水泆飲也。尺膚熱甚，脈盛躁者，病溫也，其脈甚而滑者，病且出也。尺膚寒，其脈小者，泄、少氣。尺膚炬然，先熱後寒者，寒熱也；尺膚先寒，久大之而熱者，亦寒熱也。
《論疾診尺》肘所獨熱者，腰以上熱；手所獨熱者，腰以下熱。肘前獨熱者，膺前熱；肘後獨熱者，肩背熱。臂中獨熱者，腰腹熱；肘後麤以下三四寸熱者，腸中有蟲。掌中熱者，腹中熱；掌中寒者，腹中寒。魚上白肉有青血脈者，胃中有寒。
《論疾診尺》尺炬然熱，人迎大者，當奪血；尺堅大，脈小甚，少氣，免有加，立死。
《平人氣象論》人一呼脈三動，一吸脈三動而躁，尺熱曰病溫，尺不熱脈滑曰病風，脈濇曰痺。
《平人氣象論》臂多青脈，曰脫血。尺脈緩濇，謂之解㑊，安臥脈盛，謂之脫血。尺濇脈滑，謂之多汗。尺寒脈細，謂之後泄。脈尺麤常熱者，謂之熱中。
《奇病論》帝曰：人有尺脈數甚，筋急而見，此為何病。歧伯曰：此所謂疹筋，是人腹必急，白色黑色見，則病甚。

这些是更多的以尺肤诊断的例子。

《論疾診尺》黃帝問于歧伯曰：余欲無視色持脈，獨調其尺，以言其病，從外知內，為之奈何？歧伯曰：審其尺之緩急小大滑澀，肉之堅脆，而病形定矣。

黄帝想知道如何只看尺肤来诊病。

《邪氣藏府病形》歧伯答曰：脈急者，尺之皮膚亦急；脈緩者，尺之皮膚亦緩；脈小者，尺之皮膚亦減而少氣；脈大者，尺之皮膚亦賁而起；脈滑者，尺之皮膚亦滑；脈澀者，尺之皮膚亦澀。凡此變者，有微有甚。

其中的缓急小大滑涩如上所述。而肉之坚脆前面已经列出，此处就不一一列出了。

但是经云：

《邪氣藏府病形》故善調尺者，不待於寸，善調脈者，不待於色。能參合而行之者，可以為上工，上工十全九。行二者，為中工，中工十全七。行一者，為下工，下工十全六。

这里的“待”有依靠的意思，大概是说，善于调尺，（常常可以）不看寸口，善于调脉，（常常可以）不察色。这也是黄帝这样问的一个原因吧。但要成为十全九的上工，必须要三者合参。


总结一下，内经中说寸口、气口、或者简称“脉”，指的就是寸关尺之寸口脉。而“尺”就是尺肤，而非寸关尺之尺脉。

== 刺节真邪

《本藏》五藏者，所以參天地，副陰陽，而運四時，化五節者也；

《五禁》黃帝曰：何謂五禁，願聞其不可刺之時。歧伯曰：甲乙日自乘，無刺實，無發蒙於耳內。丙丁日自乘，無振埃於肩喉廉泉。戊己日自乘四季，無刺腹，去爪寫水。庚辛日自乘，無刺關節於股膝。壬癸日自乘，無刺足脛，是謂五禁。

=== 振埃

《腹中論》帝曰：善。有病膺腫頸痛胸滿腹脹此為何病，何以得之。歧伯曰：名厥逆。帝曰：治之柰何。歧伯曰：灸之則瘖，石之則狂，須其氣并，乃可治也。帝曰：何以然。歧伯曰：陽氣重上，有餘於上，灸之則陽氣入陰，入則瘖，石之則陽氣虛，虛則狂，須其氣并而治之，可使全也。

《六元正紀大論》太陽，太商，太陰，庚辰，庚戌，其運涼，其化霧露蕭飋，其變肅殺凋零，其病燥背瞀胸滿。

《至真要大論》歲少陰在泉，熱淫所勝，則焰浮川澤，陰處反明，民病腹中常鳴，氣上衝胸，喘不能久立，寒熱皮膚痛，目瞑齒痛䪼腫，惡寒發熱如瘧，少腹中痛腹大，蟄蟲不藏。

少陽司天，客勝則丹胗外發，及為丹熛瘡瘍，嘔逆喉痺，頭痛嗌腫，耳聾血溢，內為瘛瘲，主勝則胸滿欬仰息，甚而有血，手熱。

陽明在泉，客勝則清氣動下，少腹堅滿而數便寫，主勝則腰重腹痛，少腹生寒下為鶩溏，則寒厥於腸，上衝胸中，甚則喘不能久立。

《經脈》肺手太陰之脈，……是動則病肺脹滿，膨脹而喘咳，缺盆中痛，甚則交兩手而瞀，此為臂厥。是主肺所生病者，咳上氣，喘渴，煩心，胸滿，臑臂內前廉痛厥，掌中熱。

肝足厥陰之脈，……是動則病腰痛不可以俛仰，丈夫㿉疝，婦人少腹腫，甚則嗌乾，面塵，脫色。是肝所生病者，胸滿，嘔逆，飧泄，狐疝，遺溺，閉癃。

《寒熱病》陽迎頭痛，胸滿不得息，取之人迎。

《癩狂病》厥逆腹脹滿，腸鳴，胸滿不得息，取之下胸二脅，咳而動手者，與背輸，以手按之，立快者是也。

《熱病》氣滿胸中喘息，取足太陰大趾之端，去爪甲如薤葉，寒則留之，熱則疾之，氣下乃止。

《厥病》厥心痛，與背相控，善瘈，如從後觸其心，傴僂者，腎心痛也，先取京骨、崑崙，發狂不已，取然谷。厥心痛，腹脹胸滿，心尤痛甚，胃心痛也，取之大都、大白。

《雜病》厥胸滿面腫，唇漯漯然，暴言難，甚則不能言，取足陽明。

《論勇》黃帝曰：怯士之得酒，怒不避勇士者，何藏使然？少俞曰：酒者，水谷之精，熟谷之液也，其氣慓悍，其入于胃中，則胃脹，氣上逆，滿於胸中，肝浮膽橫，當是之時，固比于勇士，氣衰則悔。與勇士同類，不知避之，名曰酒悖也。

《衛氣失常》黃帝曰：衛氣之留於腹中，搐積不行，菀蘊不得常所，使人支脅胃中滿，喘呼逆息者，何以去之？伯高曰：其氣積於胸中者，上取之，積於腹中者，下取之，上下皆滿者，旁取之。

《本藏》肺小，則少飲，不病喘喝；肺大則多飲，善病胸痺、喉痺、逆氣。肺高，則上氣，肩息咳；

《五常政大論》堅成之紀，……其病喘喝胸憑仰息，……邪傷肺也。

《本神》肺藏氣，氣舍魄，肺氣虛，則鼻塞不利少氣，實則喘喝胸盈仰息。

《五亂》黃帝曰：何為逆而亂，歧伯曰：清氣在陰，濁氣在陽，營氣順脈，衛氣逆行，清濁相干，亂於胸中，是謂大悗。……亂於肺，則俛仰喘喝，接手以呼；

《刺熱》肺熱病者，先淅然厥，起毫毛惡風寒，舌上黃身熱。熱爭，則喘欬，痛走胸膺背，不得大息，頭痛不堪，汗出而寒，丙丁甚，庚辛大汗，氣逆則丙丁死，刺手太陰陽明，出血如大豆，立已。

《刺禁論》刺缺盆中內陷，氣泄令人喘欬逆。……刺膺中陷中肺，為喘逆仰息。

《氣穴論》背胸邪繫陰陽左右。如此其病前後痛濇，胸脇痛而不得息不得臥，上氣短氣偏痛，脈滿起斜出尻脈，絡胸脇支心貫鬲，上肩加天突，斜下肩交十椎下。

《繆刺論》邪客於足少陽之絡，令人脇痛不得息，欬而汗出，刺足小指次指爪甲上，與肉交者各一痏，不得息立已，汗出立止，欬者溫衣飲食一日已，左刺右，右刺左，病立已，不已，復刺如法。

《歲露論》故月滿則海水西盛，人血氣積，肌肉充，皮膚致，毛髮堅，腠理郗，煙垢著，當是之時，雖遇賊風，其入淺不深。至其月郭空，則海水東盛，人氣血虛，其衛氣去，形獨居，肌肉減，皮膚縱，腠理開，毛髮殘，膠理薄，煙垢落，當是之時，遇賊風則其入深，其病人也，卒暴。

《玉機真藏論》歧伯曰：秋脈者肺也，西方金也，萬物之所以收成也，……帝曰：秋脈太過與不及，其病皆何如。歧伯曰：太過則令人逆氣而背痛，慍慍然；其不及，則令人喘，呼吸少氣而欬，上氣見血，下聞病音。

《藏氣法時論》肺主秋，手太陰陽明主治，其日庚辛，肺苦氣上逆，急食苦以泄之。

《奇病論》帝曰：有癃者，一日數十溲，此不足也；身熱如炭，頸膺如格，人迎躁盛，喘息氣逆，此有餘也，太陰脈微細如髮者，此不足也。其病安在，名為何病。歧伯曰：病在太陰，其盛在胃頗在肺，病名曰厥，死不治。此所謂得五有餘二不足也。帝曰：何謂五有餘，二不足。歧伯曰：所謂五有餘者五病之氣有餘也；二不足者，亦病氣之不足也。

《氣交變大論》歲火太過，炎暑流行，金肺受邪。民病瘧，少氣欬喘，血溢血泄注下，嗌燥耳聾，中熱肩背熱，上應熒惑星。甚則胸中痛脇支滿脇痛，膺背肩胛間痛，兩臂內痛，身熱骨痛，而為浸淫。收氣不行，長氣獨明，雨水霜寒，上應辰星。上臨少陰少陽，火燔焫，冰泉涸，物焦槁，病反譫妄狂越，欬喘息鳴，下甚血溢泄不已，太淵絕者，死不治，上應熒惑星。

歲金太過，燥氣流行，肝木受邪。民病兩脇下少腹痛，目赤痛眥瘍耳無所聞。肅殺而甚，則體重煩冤，胸痛引背，兩脇滿且痛引少腹，上應太白星。甚則喘欬逆氣，肩背痛，尻陰股膝髀腨䯒足皆病，上應熒惑星。收氣峻，生氣下，草木斂，蒼乾凋隕，病反暴痛，胠脇不可反側，欬逆甚而血溢，太衝絕者，死不治，上應太白星。

《邪氣藏府病形》黃帝曰：邪之中人藏奈何？……形寒寒飲則傷肺，以其兩寒相感，中外皆傷，故氣逆而上行。

《四時氣》腹中常鳴，氣上衝胸，喘不能久立。邪在大腸，刺肓之原，巨虛上廉、三里。

《雜病》氣逆上，刺膺中陷者，與下胸動脈。

《海論》黃帝曰：四海之逆順奈何？歧伯曰：氣海有餘者，氣滿胸中，悗息面赤；氣海不足，則氣少不足以言。

《六節藏象論》肺者，氣之本，

《五藏生成》諸氣者皆屬於肺，

=== 发蒙

《四氣調神大論》天氣，清淨光明者也，藏德不止，故不下也。天明則日月不明，邪害空竅，陽氣者閉塞，地氣者冒明，雲霧不精，

《生氣通天論》黃帝曰：夫自古通天者生之本，本於陰陽天地之間，六合之內，其氣九州九竅五藏十二節，皆通乎天氣。其生五，其氣三，數犯此者，則邪氣傷人，此壽命之本也。蒼天之氣清淨，則志意治，順之則陽氣固，雖有賊邪，弗能害也，此因時之序。故聖人傳精神，服天氣，而通神明。失之則內閉九竅，外壅肌肉，衛氣散解，此謂自傷，氣之削也。

《生氣通天論》歧伯曰：陰者，藏精而起亟也，陽者，衛外而為固也。陰不勝其陽，則脈流薄疾，并乃狂。陽不勝其陰，則五藏氣爭，九竅不通。是以聖人陳陰陽，筋脈和同，骨髓堅固，氣血皆從。如是，則內外調和，邪不能害，耳目聰明，氣立如故。

《陰陽應象大論》故清陽出上竅，濁陰出下竅；清陽發腠理，濁陰走五藏；清陽實四支，濁陰歸六府。

陰味出下竅，陽氣出上竅。

年六十，陰痿，氣大衰，九竅不利，下虛上實，涕泣俱出矣。

天氣通於肺，地氣通於嗌，風氣通於肝，雷氣通於心，谷氣通於脾，雨氣通於腎。六經為川，腸胃為海，九竅為水注之氣。以天地為之陰陽，陽之汗，以天地之雨名之；陽之氣，以天地之疾風名之。暴氣象雷，逆氣象陽。故治不法天之紀，不用地之理，則災害至矣。

《六節藏象論》夫自古通天者，生之本，本於陰陽。其氣九州九竅，皆通乎天氣。故其生五，其氣三，三而成天，三而成地，三而成人，三而三之，合則為九，九分為九野，九野為九藏，故形藏四，神藏五，合為九藏以應之也。

《移精變氣論》當今之世不然，憂患緣其內，苦形傷其外，又失四時之從，逆寒暑之宜，賊風數至，虛邪朝夕，內至五藏骨髓，外傷空竅肌膚，所以小病必甚，大病必死，故祝由不能已也。

《玉機真藏論》帝曰：夫子言脾為孤藏，中央土以灌四傍，其太過與不及，其病皆何如。歧伯曰：太過，則令人四支不舉；其不及，則令人九竅不通，名曰重強。

《通評虛實論》黃帝曰：黃疸暴痛，癲疾厥狂，久逆之所生也。五藏不平，六府閉塞之所生也。頭痛耳鳴，九竅不利，腸胃之所生也。

《著至教論》曰：夫三陽天為業，上下無常，合而病至，偏害陰陽。雷公曰：三陽莫當，請聞其解。帝曰：三陽獨至者，是三陽并至，并至如風雨，上為巔疾，下為漏病。外無期，內無正，不中經紀，診無上下，以書別。雷公曰：臣治踈愈，說意而已。帝曰：三陽者，至陽也，積并則為驚，病起疾風，至如礔礰，九竅皆塞，陽氣滂溢，乾嗌喉塞，并於陰，則上下無常，薄為腸澼。此謂三陽直心，坐不得起，臥者便身全，三陽之病。且以知天下何以別陰陽，應四時，合之五行。

《陰陽類論》二陽一陰，陽明主病，不勝一陰，耎而動，九竅皆沈。

《邪氣藏府病形》歧伯答曰：十二經脈，三百六十五絡，其血氣皆上于面而走空竅。其精陽氣上走於目而為睛。其別氣走於耳而為聽。其宗氣上出於鼻而為臭。其濁氣出於胃，走唇舌而為味。其氣之津液，皆上燻于面，而皮又厚，其肉堅，故天氣甚寒，不能勝之也。

《通評虛實論》五藏不平，六府閉塞之所生也。
《脈度》五藏常內閱於上七竅也。……五藏不和，則七竅不通；六府不合則留為癰。故邪在府則陽脈不和，陽脈不和則氣留之，氣留之則陽氣盛矣。陽氣太盛，則陰不利，陰脈不利則血留之，血留之則陰氣盛矣。陰氣太盛則陽氣不能榮也，故曰關。陽氣太盛，則陰氣弗能榮也，故曰格。陰陽俱盛，不得相榮，故曰關格。關格者，不得盡期而死也。

《口問》凡此十二邪者，皆奇邪之走空竅者也。故邪之所在，皆為不足。故上氣不足，腦為之不滿，耳為之苦鳴，頭為之苦傾，目為之眩。中氣不足，溲便為之變，腸為之苦鳴。下氣不足，則乃為痿厥心悗。補足外踝下留之。

目眩頭傾，補足外踝下留之；

黃帝曰：人之耳中鳴者，何氣使然？歧伯曰：耳者，宗脈之所聚也，故胃中空則宗脈虛，虛則下溜，脈有所竭者，故耳鳴，補客主人，手大指爪甲上與肉交者也。

液者，所以灌精濡空竅者也，故上液之道開則泣，泣不止則液竭；液竭則精不灌，精不灌則目無所見矣，故命曰奪精。補天柱經俠頸。

《陰陽清濁》黃帝曰：諸陽皆濁，何陽濁甚乎？歧伯曰：手太陽獨受陽之濁，手太陰獨受陰之清；其清者上走空竅，其濁者下行諸經。諸陰皆清，足太陰獨受其濁。


《動輸》黃帝曰：足之陽明，何因而動？歧伯曰：胃氣上注于肺，其悍氣上沖頭者，循咽，上走空竅，循眼系，入絡腦，出顑，下客主人，循牙車，合陽明，并下人迎，此胃氣別走於陽明者也。

《百病始生》其著於輸之脈者，閉塞不通，津液不下，孔竅干壅，

《九鍼論》七者，星也。星者，人之七竅，邪之所客於經，而為痛痺，合於經絡者也。故為之治鍼，令尖如蚊虻喙，靜以徐往，微以久留，正氣因之，真邪俱往，出鍼而養者也。

=== 去爪

《氣交變大論》木不及，……其眚東，其藏肝，其病內舍胠脇，外在關節。

《六元正紀大論》凡此太陰司天之政，……初之氣，地氣遷，寒迺去，春氣正，風迺來，……民病血溢，筋絡拘強，關節不利，身重筋痿。……終之氣，寒大舉，……感於寒則病人關節禁固腰脽痛，

凡此少陰司天之政，……初之氣，地氣遷，燥將去，寒迺始，蟄復藏，水迺冰，霜復降，風迺至，陽氣鬱，民反周密，關節禁固腰脽痛，炎暑將起，中外瘡瘍。

水鬱之發，……故民病寒客心痛，腰脽痛，大關節不利，屈伸不便，善厥逆，痞堅腹滿。

《至真要大論》厥陰在泉，客勝則大關節不利，內為痙強拘瘛，外為不便，主勝則筋骨繇併，腰腹時痛。少陰在泉，客勝則腰痛尻股膝髀腨䯒足病，……太陽在泉，寒復內餘，則腰尻痛屈伸不利，股脛足膝中痛。

《邪客》腎有邪，其氣留於兩膕。凡此八虛者，皆機關之室，真氣之所過，血絡之所遊。邪氣惡血，固不得住留。住留則傷筋絡骨節；機關不得屈伸，故痀攣也。

《九鍼論》九者，野也。野者，人之節解皮膚之間也。淫邪流溢於身，如風水之狀，而留不能過於機關大節者也。




=== 解惑

《大惑論》目者，心使也。心者，神之舍也，故神精亂而不轉。卒然見非常處精神魂魄，散不相得，故曰惑也。
《大惑論》黃帝曰：余疑其然。余每之東苑，未曾不惑，去之則復，余唯獨為東苑勞神乎？何其異也？歧伯曰：不然也。心有所喜，神有所惡，卒然相感，則精氣亂，視誤，故惑，神移乃復。是故間者為迷，甚者為惑。

=== 彻衣

《瘧論》歧伯對曰：瘧之始發也，先起於毫毛，伸欠乃作，寒慄鼓頷，腰脊俱痛，寒去則內外皆熱，頭痛如破，渴欲冷飲。……陽盛則外熱；陰虛則內熱，外內皆熱，則喘而渴；故欲冷飲也。

《瘧論》歧伯曰：此先傷於風而後傷於寒，故先熱而後寒也，亦以時作，名曰溫瘧。其但熱而不寒者，陰氣先絕，陽氣獨發，則少氣煩冤，手足熱而欲嘔，名曰癉瘧。

帝曰：癉瘧何如。歧伯曰：癉瘧者，肺素有熱氣盛於身，厥逆上衝，中氣實而不外泄，因有所用力，腠理開，風寒舍於皮膚之內、分肉之閒而發，發則陽氣盛，陽氣盛而不衰，則病矣。其氣不及於陰，故但熱而不寒，氣內藏於心，而外舍於分肉之閒，令人消爍脫肉，故命曰癉瘧。


《刺瘧》溫瘧汗不出，為五十九刺。

《調經論》帝曰：經言陽虛則外寒，陰虛則內熱，陽盛則外熱，陰盛則內寒，余已聞之矣，不知其所由然也。歧伯曰：陽受氣於上焦，以溫皮膚分肉之閒。令寒氣在外，則上焦不通，上焦不通，則寒氣獨留於外，故寒慄。帝曰：陰虛生內熱柰何。歧伯曰：有所勞倦，形氣衰少，穀氣不盛，上焦不行，下脘不通，胃氣熱，熱氣熏胸中，故內熱。帝曰：陽盛生外熱柰何。歧伯曰：上焦不通利，則皮膚緻密腠理閉塞，玄府不通，衛氣不得泄越，故外熱。

《刺節真邪》陰氣不足則內熱，陽氣有餘則外熱，

《玉版》黃帝曰：病之生時，有喜怒不測，飲食不節，陰氣不足，陽氣有餘，營氣不行，乃發為癰疽。陰陽不通，兩熱相搏，乃化為濃，小鍼能取之乎？

《脈要精微論》麤大者，陰不足陽有餘，為熱中也。
濇者陽氣有餘也，滑者陰氣有餘也。陽氣有餘，為身熱无汗，陰氣有餘，為多汗身寒，陰陽有餘，則无汗而寒。

《逆調論》帝曰：人有四支熱，逢逄風寒，如灸如火者，何也。歧伯曰：是人者，陰氣虛，陽氣盛，四支者陽也，兩陽相得而陰氣虛少，少水不能滅盛火，而陽獨治，獨治者不能生長也，獨勝而止耳，逢風而如灸如火者，是人當肉爍也。

黃帝問曰：人身非常溫也，非常熱也，為之熱而煩滿者何也。歧伯對曰：陰氣少而陽氣勝，故熱而煩滿也。

《五邪》五邪:	邪在脾胃，則病肌肉痛，陽氣有餘，陰氣不足，則熱中善飢；陽氣不足，陰氣有餘，則寒中腸鳴、腹痛；陰陽俱有餘，若俱不足，則有寒有熱，皆調于三里。

《熱病》熱病三日，而氣口靜、人迎躁者，取之諸陽，五十九刺，以寫其熱，而出其汗，實其陰，以補其不足者。

《經脈別論》太陽藏獨至，厥喘虛氣逆，是陰不足陽有餘也，表裏當俱寫，取之下俞。陽明藏獨至，是陽氣重并也，當寫陽補陰，取之下俞。

《寒熱病》皮寒熱者，不可附席，毛髮焦，鼻槁臘。不得汗，取三陽之絡，以補手太陰。肌寒熱者，肌痛，毛髮焦而唇槁臘。不得汗，取三陽于下，以去其血者，補足太陰，以出其汗。

《陰陽應象大論》帝曰：法陰陽柰何。歧伯曰：陽勝則身熱，腠理閉，喘麤為之俛仰，汗不出而熱，齒乾以煩冤腹滿，死，能冬不能夏。陰勝則身寒汗出，身常清，數慄而寒，寒則厥，厥則腹滿，死，能夏不能冬。此陰陽更勝之變，病之形能也。

《雜病》嗌乾，口中熱如膠，取足少陰。

《脈解》厥陰……所謂甚則嗌乾熱中者，陰陽相薄而熱，故嗌乾也。

《水熱穴論》帝曰：夫子言治熱病五十九俞，余論其意，未能領別其處，願聞其處，因聞其意。歧伯曰：頭上五行行五者，以越諸陽之熱逆也。大杼膺俞缺盆背俞此八者，以寫胸中之熱也。氣街三里巨虛上下廉此八者，以寫胃中之熱也。雲門髃骨委中髓空此八者，以寫四支之熱也。五藏俞傍五此十者，以寫五藏之熱也。凡此五十九穴者，皆熱之左右也。帝曰：人傷於寒而傳為熱，何也。歧伯曰：夫寒盛，則生熱也。

《熱病》所謂五十九刺者，兩手外內側各三，凡十二痏。五指間各一，凡八痏，足亦如是。頭入髮一寸傍三分各三，凡六痏。更入髮三寸邊五，凡十痏。耳前後口下者各一，項中一，凡六痏。巔上一，聰會一，髮際一，廉泉一，風池二，天柱二。

=== 其他

《痿論》心氣熱，則下脈厥而上，上則下脈虛，虛則生脈痿，樞折挈，脛縱而不任地也；


胫：胫气街，冲脉

== 五禁和五节刺

《五禁》黃帝曰：何謂五禁，願聞其不可刺之時。歧伯曰：
甲乙日自乘，無刺頭，無發蒙於耳內。
丙丁日自乘，無振埃於肩喉廉泉。
戊己日自乘四季，無刺腹去爪寫水。
庚辛日自乘，無刺關節於股膝。
壬癸日自乘，無刺足脛，是謂五禁。

先不管自乘是什么意思，五禁里面有日子，有部位，还有刺法。日子和部位是对应的，和刺法看起来是五行相克关系，也就是说振埃是治金，发蒙是治土，去爪是治水，这三个可以和五节刺直接联系起来，那是不是可以推断出，刺关节是治木，对应的还是去爪。刺足胫很难说是不是治火或者解惑。彻衣没有对应。

从五节刺来看，振埃给出的例子看起来跟肺有很大关系，这个比较明显。

《本藏》肺小，則少飲，不病喘喝；肺大則多飲，善病胸痺、喉痺、逆氣。肺高，則上氣，肩息咳；
《本神》肺藏氣，氣舍魄，肺氣虛，則鼻塞不利少氣，實則喘喝胸盈仰息。
《五亂》黃帝曰：何為逆而亂，歧伯曰：清氣在陰，濁氣在陽，營氣順脈，衛氣逆行，清濁相干，亂於胸中，是謂大悗。……亂於肺，則俛仰喘喝，接手以呼；
《藏氣法時論》肺主秋，手太陰陽明主治，其日庚辛，肺苦氣上逆，急食苦以泄之。
《邪氣藏府病形》黃帝曰：邪之中人藏奈何？……形寒寒飲則傷肺，以其兩寒相感，中外皆傷，故氣逆而上行。
《六節藏象論》肺者，氣之本，
《五藏生成》諸氣者皆屬於肺，


发蒙是说耳无所闻、目无所见，是不是可以认为是人体所有的感官都有问题了？说到土，有几条跟脾胃有点关联：

《玉機真藏論》帝曰：夫子言脾為孤藏，中央土以灌四傍，其太過與不及，其病皆何如。歧伯曰：太過，則令人四支不舉；其不及，則令人九竅不通，名曰重強。
《通評虛實論》黃帝曰：黃疸暴痛，癲疾厥狂，久逆之所生也。五藏不平，六府閉塞之所生也。頭痛耳鳴，九竅不利，腸胃之所生也。
《脈度》五藏常內閱於上七竅也。……五藏不和，則七竅不通；
《陰陽類論》二陽一陰，陽明主病，不勝一陰，耎而動，九竅皆沈。
《寒熱病》暴襲氣蒙，耳目不明，取天牖。

是不是说和胃相关性比较大，所以说刺府俞、去府病，包括手足阳经。

去爪和肝、肾有关。

《氣交變大論》木不及，……其眚東，其藏肝，其病內舍胠脇，外在關節。
《官鍼》病水腫不能通關節者，取以大鍼。
《九鍼論》九者，野也。野者，人之節解皮膚之間也。淫邪流溢於身，如風水之狀，而留不能過於機關大節者也。故為之治鍼，令尖如挺，其鋒微員，以取大氣之不能過於關節者也。
《九鍼論》九曰大鍼，取法於鋒鍼，其鋒微員，長四寸，主取大氣不出關節者也。

解惑和心有关。

《大惑論》目者，心使也。心者，神之舍也，故神精亂而不轉。卒然見非常處精神魂魄，散不相得，故曰惑也。
《大惑論》黃帝曰：余疑其然。余每之東苑，未曾不惑，去之則復，余唯獨為東苑勞神乎？何其異也？歧伯曰：不然也。心有所喜，神有所惡，卒然相感，則精氣亂，視誤，故惑，神移乃復。是故間者為迷，甚者為惑。

彻衣是不是就是热病的五十九俞：

《瘧論》歧伯曰：此先傷於風而後傷於寒，故先熱而後寒也，亦以時作，名曰溫瘧。其但熱而不寒者，陰氣先絕，陽氣獨發，則少氣煩冤，手足熱而欲嘔，名曰癉瘧。
《瘧論》帝曰：癉瘧何如。歧伯曰：癉瘧者，肺素有熱氣盛於身，厥逆上衝，中氣實而不外泄，因有所用力，腠理開，風寒舍於皮膚之內、分肉之閒而發，發則陽氣盛，陽氣盛而不衰，則病矣。其氣不及於陰，故但熱而不寒，氣內藏於心，而外舍於分肉之閒，令人消爍脫肉，故命曰癉瘧。
《調經論》帝曰：經言陽虛則外寒，陰虛則內熱，陽盛則外熱，陰盛則內寒，余已聞之矣，不知其所由然也。歧伯曰：陽受氣於上焦，以溫皮膚分肉之閒。……
帝曰：陰虛生內熱柰何。歧伯曰：有所勞倦，形氣衰少，穀氣不盛，上焦不行，下脘不通，胃氣熱，熱氣熏胸中，故內熱。
帝曰：陽盛生外熱柰何。歧伯曰：上焦不通利，則皮膚緻密腠理閉塞，玄府不通，衛氣不得泄越，故外熱。
《熱病》熱病三日，而氣口靜、人迎躁者，取之諸陽，五十九刺，以寫其熱，而出其汗，實其陰，以補其不足者。
《寒熱病》皮寒熱者，不可附席，毛髮焦，鼻槁臘。不得汗，取三陽之絡，以補手太陰。肌寒熱者，肌痛，毛髮焦而唇槁臘。不得汗，取三陽于下，以去其血者，補足太陰，以出其汗。
《水熱穴論》帝曰：夫子言治熱病五十九俞，余論其意，未能領別其處，願聞其處，因聞其意。歧伯曰：頭上五行行五者，以越諸陽之熱逆也。大杼膺俞缺盆背俞此八者，以寫胸中之熱也。氣街三里巨虛上下廉此八者，以寫胃中之熱也。雲門髃骨委中髓空此八者，以寫四支之熱也。五藏俞傍五此十者，以寫五藏之熱也。凡此五十九穴者，皆熱之左右也。

基本是就是先去热，再䃼阴。

再结合下文：

日自乘者，言其日之所直也。

日干支运气同化：六十甲子日中，天干和地支在五行属性上一致的天日，命名为日干支运气同化。也就是自乘。


在运气学中，天干以五数为周期而化合为：甲己为土、乙庚为金、丙辛为水、丁壬为木、戊癸为火；地支以六数为周期化合为：子午为君火、丑未为土、寅申为相火、卯酉为金、辰戌为水、巳亥为木。

古人观察天道是以观测者为中心的视运动，并以观测者所在地为地平坐标（按地支分为十二等分）而定方位，于是就有了地平五方的天干地支五行属性是：东方甲乙、寅卯为木，南方丙丁、巳午为火，西方庚辛、申酉为金，北方壬癸、亥子为水，中央戊己、丑未辰戌为土的规定。

古人并以地平方位来定天道的运动行程（天道的圆周运动没有方向性。或以天上的二十八宿定日月行程。），当天道运行到地平坐标的五方正位时的特殊点位（指子、午、卯、酉、丑未辰戌的五方正位），就称其为天符（天为司天，符为符合。同为天道层次。）、岁会。如：戊午、戊子、戊寅、戊申年，丙戌、丙辰年，丁亥、丁巳年，乙卯、乙酉年，己丑、己未年，此十二年的运与气五行属性相同就是天符年。而岁会则要求岁运的五行属性要与岁支对应的地平五方正位五行属性相同（但运气的岁支五行属性并不受地平五方五行属性的影响），如丁卯、戊午、乙酉、丙子、甲辰、甲戌、己丑、己未八年，即天地会之意，是天地两个层面的结合。戊午、己未、己丑、乙酉四年既是天符年，又是岁会年，则称为太乙天符年。同天符、同岁会同此道理，而以在泉为主。

== 阴阳别论之二十五阳

高帆师兄那天发了朋友圈说了二十五阳的理解，在这里我也说说我的理解，和高师兄的解释很相近。

《陰陽別論》脈有陰陽，知陽者知陰，知陰者知陽。凡陽有五，五五二十五陽。
《陰陽別論》所謂陰者，真藏也，見則為敗，敗必死也；所謂陽者，胃脘之陽也。

这里说的是脉之阴阳，阴指的是真藏脉，见则必死。

《平人氣象論》平人之常氣稟於胃，胃者，平人之常氣也，人无胃氣曰逆，逆者死。……但弦无胃曰死，……但鉤无胃曰死，……但代无胃曰死，……但毛无胃曰死，……但石无胃曰死，
《平人氣象論》肝見庚辛死，心見壬癸死，脾見甲乙死，肺見丙丁死，腎見戊己死，是謂真藏見皆死。
《平人氣象論》所謂無胃氣者，但得真藏脈不得胃氣也。
《玉機真藏論》……真藏脈見，乃予之期日……真藏見，乃予之期日。……真藏來見，期一歲死，見其真藏，乃予之期日。……諸真藏脈見者，皆死，不治也。……故真藏之氣獨見，獨見者病勝藏也，故曰死。
《三部九候論》必先知經脈，然後知病脈，真藏脈見者，勝死。

阳指的是胃脘之阳，和阴结合起来理解，也就是说，脉无胃气曰真藏脉，为阴，有阴无阳；脉有胃气为阳，有阴有阳。

先不说二十五阳，先理解一下这个阴阳的区别。

《陰陽別論》別於陽者，知病處也；別於陰者，知死生之期。……別於陽者，知病忌時；別於陰者，知死生之期。
《玉機真藏論》故曰：別於陽者，知病從來；別於陰者，知死生之期。言知至其所困而死。

真藏脉来可以知死生之期，有胃气之脉可以知病处、知病忌时、知病从来。

《病能論》所謂揆者，方切求之也，言切求其脈理也，度者得其病處，以四時度之也。
《欬論》五藏各以其時受病，非其時，各傳以與之。人與天地相參，故五藏各以治，時感於寒，則受病，微則為欬，甚者為泄為痛。乘秋則肺先受邪，乘春則肝先受之，乘夏則心先受之，乘至陰則脾先受之，乘冬則腎先受之。
《玉機真藏論》然其卒發者，不必治於傳，或其傳化有不以次，不以次入者，憂恐悲喜怒，令不得以其次，故令人有大病矣。因而喜大虛則腎氣乘矣，怒則肝氣乘矣，悲則肺氣乘矣，恐則脾氣乘矣，憂則心氣乘矣，此其道也。故病有五，五五二十五變，及其傳化。傳，乘之名也。

病有五，指的是五藏；二十五变，每个藏病都可能有五藏（包括本藏）乘之，所以有二十五变。

《平人氣象論》春胃微弦曰平，弦多胃少曰肝病，但弦无胃曰死，胃而有毛曰秋病，毛甚曰今病。……夏胃微鉤曰平，鉤多胃少曰心病，但鉤无胃曰死，胃而有石曰冬病，石甚曰今病。……長夏胃微耎弱曰平，弱多胃少曰脾病，但代无胃曰死，耎弱有石曰冬病，弱甚曰今病。……秋胃微毛曰平，毛多胃少曰肺病，但毛无胃曰死，毛而有弦曰春病，弦甚曰今病。……冬胃微石曰平，石多胃少曰腎病，但石无胃曰死，石而有鉤曰夏病，鉤甚曰今病。

这就是稍微具体的阐述，不过不全。

《邪氣藏府病形》歧伯答曰：夫色脈與尺之相應也，如桴鼓影響之相應也，不得相失也，……
黃帝曰：願卒聞之。歧伯答曰：色青者，其脈弦也，赤者，其脈鉤也，黃者，其脈代也，白者，其脈毛，黑者，其脈石。見其色而不得其脈，反得其相勝之脈，則死矣；得其相生之脈，則病已矣。
黃帝問於歧伯曰：五藏之所生，變化之病形何如？
歧伯答曰：先定其五色五脈之應，其病乃可別也。
黃帝曰：色脈已定，別之奈何？
歧伯說：調其脈之緩、急、小、大、滑、澀，而病變定矣。
黃帝曰：請問脈之緩、急，小、大，滑、澀之病形何如？
歧伯曰：臣請言五藏之病變也。……

然后是更为具体的阐述，五藏之脉以及相应之病。

《順氣一日分為四時》黃帝曰：善，余聞刺有五變，以主五輸。願聞其數。歧伯曰：人有五藏，五藏有五變。五變有五輸，故五五二十五輸，以應五時。
黃帝曰：願聞五變。肝……心……脾……肺……腎……是為五變。
黃帝曰：以主五輸奈何？藏主冬，冬刺井；色主春，春刺滎；時主夏，夏刺輸；音主長夏，長夏刺經；味主秋，秋刺合。是謂五變，以主五輸。
黃帝曰：何謂藏主冬，時主夏，音主長夏，味主秋，色主春。願聞其故。歧伯曰：病在藏者，取之井；病變於色者，取之滎；病時間時甚者，取之輸；病變於音者，取之經；經滿而血者，病在胃；及以飲食不節得病者，取之於合，故命曰味主合。是謂五變也。

这就是相应的治法了。

《病能論》帝曰：有病厥者，診右脈沈而緊，左脈浮而遲，不然病主安在。歧伯曰：冬診之右脈固當沈緊，此應四時，左脈浮而遲，此逆四時。在左當主病在腎，頗關在肺，當腰痛也。帝曰：何以言之。歧伯曰：少陰脈貫腎絡肺，今得肺脈，腎為之病，故腎為腰痛之病也。
《五色》腎乘心，心先病，腎為應，色皆如是。

这是两个例子，前一个肺乘肾，后一个肾乘心。

这样看来，二十五阳指的就有胃气之脉的二十五变。当然五色五音的变化也是类似的，主要是色脉和尺。


《陰陽應象大論》善診者，察色按脈，先別陰陽；審清濁，而知部分；視喘息，聽音聲，而知所苦；觀權衡規矩，而知病所主。按尺寸，觀浮沈滑濇，而知病所生；以治無過，以診則不失矣。
《移精變氣論》帝曰：善。余欲臨病人，觀死生，決嫌疑，欲知其要，如日月光，可得聞乎。歧伯曰：色脈者，上帝之所貴也，先師之所傳也。上古使僦貸季，理色脈而通神明，合之金木水火土四時八風六合，不離其常，變化相移，以觀其妙，以知其要，欲知其要，則色脈是矣。色以應日，脈以應月，常求其要，則其要也。夫色之變化，以應四時之脈，此上帝之所貴，以合於神明也，所以遠死而近生。
《移精變氣論》帝曰：願聞要道。歧伯曰：治之要極，無失色脈，用之不惑，治之大則。逆從到行，標本不得，亡神失國。去故就新，乃得真人。
《玉機真藏論》黃帝曰：凡治病，察其形氣色澤，脈之盛衰，病之新故，乃治之無後其時。

=== 色脉决死生

《五藏生成》五藏之氣，故色見青如草茲者死，黃如枳實者死，黑如尚炱者死，赤如衃血者死，白如枯骨者死，此五色之見死也。
《五藏生成》凡相五色之奇脈，……面青目赤，面赤目白，面青目黑，面黑目白，面赤目青，皆死也。
《脈要精微論》黃帝問曰：診法何如。歧伯對曰：診法常以平旦，陰氣未動，陽氣未散，飲食未進，經脈未盛，絡脈調勻，氣血未亂，故乃可診有過之脈。切脈動靜而視精明，察五色，觀五藏有餘不足，六府強弱，形之盛衰，以此參伍決死生之分。
《脈要精微論》夫脈者，血之府也，長則氣治，短則氣病，數則煩心，大則病進，上盛則氣高，下盛則氣脹，代則氣衰，細則氣少，濇則心痛，渾渾革至如涌泉，病進而色弊，緜緜其去如弦絕，死。夫精明五色者，氣之華也。赤欲如白裹朱，不欲如赭；白欲如鵝羽，不欲如鹽；青欲如蒼璧之澤，不欲如藍；黃欲如羅裹雄黃，不欲如黃土；黑欲如重漆色，不欲如地蒼。五色精微象見矣，其壽不久也。
《脈要精微論》帝曰：脈其四時動柰何，知病之所在柰何，知病之所變奈何，知病乍在內柰何，知病乍在外奈何，請問此五者，可得聞乎。……陰陽有時，與脈為期，期而相失，知脈所分，分之有期，故知死時。微妙在脈，不可不察，察之有紀，從陰陽始，始之有經，從五行生，生之有度，四時為宜，補寫勿失，與天地如一，得一之情，以知死生。是故聲合五音，色合五行，脈合陰陽，
《平人氣象論》人一呼脈四動以上曰死，脈絕不至曰死，乍踈乍數曰死。
《玉機真藏論》黃帝曰：五藏相通，移皆有次，五藏有病，則各傳其所勝。不治，法三月若六月，若三日若六日，傳五藏而當死，是順傳所勝之次。故曰：別於陽者，知病從來；別於陰者，知死生之期。言知至其所困而死。
《三部九候論》五藏已敗，其色必夭，夭必死矣。帝曰：以候奈何。
《三部九候論》九候之相應也，上下若一，不得相失。一候後則病，二候後則病甚，三候後則病危。所謂後者，應不俱也。察其府藏，以知死生之期。
《三部九候論》必先知經脈，然後知病脈，真藏脈見者，勝死。
《藏氣法時論》黃帝問曰：合人形以法四時五行而治，何如而從，何如而逆，得失之意，願聞其事。歧伯對曰：五行者，金木水火土也，更貴更賤，以知死生，以決成敗，而定五藏之氣，間甚之時，死生之期也。
《經脈別論》食氣入胃，散精於肝，淫氣於筋。淫氣入胃，濁氣歸心，淫精於脈。脈氣流經，經氣歸於肺，肺朝百脈，輸精於皮毛。毛脈合精，行氣於腑。腑精神明，留於四臟，氣歸於椎衡。權衡以平，氣口成寸，以決死生。
《邪氣藏府病形》黃帝曰：願卒聞之。歧伯答曰：色青者，其脈弦也，赤者，其脈鉤也，黃者，其脈代也，白者，其脈毛，黑者，其脈石。見其色而不得其脈，反得其相勝之脈，則死矣；得其相生之脈，則病已矣。
《五色》雷公曰：其不辨者，可得聞乎？黃帝曰：五色之見也，各出其色部。部骨陷者，必不免於病矣。其色部乘襲者，雖病甚，不死矣。
《五色》雷公曰：人不病卒死，何以知之？黃帝曰：大氣入于藏府者，不病而卒死矣。雷公曰：病小愈而卒死者，何以知之？黃帝曰：赤色出兩顴，大如拇指者，病雖小愈，必卒死。黑色出於庭，大如拇指，必不病而卒死。
《邪客》因視目之五色，以知五藏，而決死生。

=== 知死生之期

《玉機真藏論》藏受氣於其所生，傳之於其所勝，氣舍於其所生，死於其所不勝。病之且死，必先傳行至其所不勝，病乃死。此言氣之逆行也，故死。……一日一夜五分之，此所以占死生之早暮也。
《藏氣法時論》夫邪氣之客於身也，以勝相加，至其所生而愈，至其所不勝而甚，至於所生而持，自得其位而起。必先定五藏之脈，乃可言間甚之時，死生之期也。
《五色》雷公再拜曰：善哉！其死有期乎？黃帝曰：察色以言其時。

=== 其他

《陰陽應象大論》善診者，察色按脈，先別陰陽；審清濁，而知部分；視喘息，聽音聲，而知所苦；觀權衡規矩，而知病所主。按尺寸，觀浮沈滑濇，而知病所生；以治無過，以診則不失矣。

《玉機真藏論》黃帝曰：五藏相通，移皆有次，五藏有病，則各傳其所勝。不治，法三月若六月，若三日若六日，傳五藏而當死，是順傳所勝之次。故曰：別於陽者，知病從來；別於陰者，知死生之期。言知至其所困而死。

《小鍼解》睹其色，察其目，知其散復，一其形，聽其動靜者，言上工知相五色於目。有知調尺寸小大緩急滑澀以言所病也。知其邪正者，知論虛邪與正邪之風也。

《四時氣》睹其色，察其以，知其散復者，視其目色，以知病之存亡也。一其形，聽其動靜者，持氣口人迎以視其脈，堅且盛且滑者，病日進，脈軟者，病將下，諸經實者，病三日已。氣口候陰，人迎候陽也。

《五閱五使》黃帝問於歧伯曰：余聞刺有五官五閱，以觀五氣。五氣者，五藏之使也，五時之副也。願聞其五使當安出？歧伯曰：五官者，五藏之閱也。黃帝曰：願聞其所出，令可為常。歧伯曰：脈出於氣口，色見於明堂，五色更出，以應五時，各如其常，經氣入藏，必當治理。

《邪氣藏府病形》黃帝問於歧伯曰：余聞之，見其色，知其病，命曰明。按其脈，知其病，命曰神。問其病，知其處，命曰工。余願聞見而知之，按而得之，問而極之，為之奈何？
《邪氣藏府病形》歧伯答曰：夫色脈與尺之相應也，如桴鼓影響之相應也，不得相失也，此亦本末根葉之出候也，故根死則葉枯矣。色脈形肉，不得相失也。故知一則為工，知二則為神，知三則神且明矣。
《邪氣藏府病形》黃帝曰：願卒聞之。歧伯答曰：色青者，其脈弦也，赤者，其脈鉤也，黃者，其脈代也，白者，其脈毛，黑者，其脈石。見其色而不得其脈，反得其相勝之脈，則死矣；得其相生之脈，則病已矣。
《邪氣藏府病形》黃帝問於歧伯曰：五藏之所生，變化之病形何如？
歧伯答曰：先定其五色五脈之應，其病乃可別也。
黃帝曰：色脈已定，別之奈何？
歧伯說：調其脈之緩、急、小、大、滑、澀，而病變定矣。
黃帝曰：請問脈之緩、急，小、大，滑、澀之病形何如？
歧伯曰：臣請言五藏之病變也。

《經脈》黃帝曰：經脈者，所以能決死生、處百病、調虛實，不可不通。
《經脈》五陰氣俱絕，則目系轉，轉則目運；目運者，為志先死；志先死，則遠一日半死矣。六陽氣絕，則陰與陽相離，離則腠理發泄，絕汗乃出，故旦占夕死，夕占旦死。

《五色》雷公曰：其不辨者，可得聞乎？黃帝曰：五色之見也，各出其色部。部骨陷者，必不免於病矣。其色部乘襲者，雖病甚，不死矣。
《五色》雷公曰：人不病卒死，何以知之？黃帝曰：大氣入于藏府者，不病而卒死矣。雷公曰：病小愈而卒死者，何以知之？黃帝曰：赤色出兩顴，大如拇指者，病雖小愈，必卒死。黑色出於庭，大如拇指，必不病而卒死。
《五色》雷公再拜曰：善哉！其死有期乎？黃帝曰：察色以言其時。
《五色》五色各見其部，察其浮沉，以知淺深；察其澤夭，以觀成敗；察其散搏，以知遠近；視色上下，以知病處；積神於心，以知往今。故相氣不微，不知是非，屬意勿去，乃知新故。色明不麤，沉天為甚，不明不澤，其病不甚。其色散，駒駒然，未有聚；其病散而氣痛，聚未成也。
《五色》腎乘心，心先病，腎為應，色皆如是。

《邪客》因視目之五色，以知五藏，而決死生。

大骨枯槀，大肉陷下，胸中氣滿，喘息不便，其氣動形，期六月死，真藏脈見，乃予之期日。
大骨枯槀，大肉陷下，胸中氣滿，喘息不便，內痛引肩項，期一月死，真藏見，乃予之期日。
大骨枯槀，大肉陷下，胸中氣滿，喘息不便，內痛引肩項，身熱脫肉破䐃，真藏見，十月之內死。
大骨枯槀，大肉陷下，肩髓內消，動作益衰，真藏來見，期一歲死，見其真藏，乃予之期日。
大骨枯槀，大肉陷下，胸中氣滿，腹內痛，心中不便，肩項身熱，破䐃脫肉，目匡陷，真藏見，目不見人，立死，其見人者，至其所不勝之時則死。

《病能論》所謂揆者，方切求之也，言切求其脈理也，度者得其病處，以四時度之也。
《五色》視色上下，以知病處；

知病处：

《陰陽類論》雷公曰：臣悉盡意，受傳經脈，頌得從容之道，以合從容，不知陰陽，不知雌雄。帝曰：三陽為父，二陽為衛，一陽為紀。三陰為母，二陰為雌，一陰為獨使。二陽一陰，陽明主病，不勝一陰，耎而動，九竅皆沈。三陽一陰，太陽脈勝，一陰不能止，內亂五藏，外為驚駭。二陰二陽，病在肺，少陰脈沈，勝肺傷脾，外傷四支。二陰二陽皆交至，病在腎，罵詈妄行，巔疾為狂。二陰一陽，病出於腎，陰氣客遊於心，脘下空竅，堤閉塞不通，四支別離。一陰一陽代絕，此陰氣至心，上下無常，出入不知，喉咽乾燥，病在土脾。二陽三陰，至陰皆在，陰不過陽，陽氣不能止陰，陰陽並絕，浮為血瘕，沈為膿胕。陰陽皆壯，下至陰陽，上合昭昭，下合冥冥，診決死生之期，遂合歲首。

《根結》故曰：下工不可不慎也，必審五藏變化之病，五脈之應，經絡之實虛，皮之柔麤，而後取之也。

《順氣一日分為四時》黃帝曰：善，余聞刺有五變，以主五輸。願聞其數。歧伯曰：人有五藏，五藏有五變。五變有五輸，故五五二十五輸，以應五時。
黃帝曰：願聞五變。
黃帝曰：何謂藏主冬，時主夏，音主長夏，味主秋，色主春。願聞其故。歧伯曰：病在藏者，取之井；病變於色者，取之滎；病時間時甚者，取之輸；病變於音者，取之經；經滿而血者，病在胃；及以飲食不節得病者，取之於合，故命曰味主合。是謂五變也。

《五色》雷公曰：以色言食之間甚，奈何？黃帝曰：其色麤以明，沉夭者為甚，其色上行者，病益甚；其色下行，如雲徹散者，病方已。五色各有藏部，有外部有內部也。色從外部走內部者，其病從外走內；其色從內走外者，其病從內走外。病生於內者，先治其陰，後治其陽，反者益甚。其病生於陽者，先治其外，後治其內，反者益甚。其脈滑大，以代而長者，病從外來，目有所見，志有所惡，此陽氣之並也，可變而已。
