= 黃帝內經

== 十二經脈

**肺手太陰之脈**，起於中焦，下絡大腸，還循胃口，上膈屬肺，從肺系橫出腋下，下循臑
內，行少陰心主之前，下肘中，循臂內上骨下廉，入寸口，上魚，循魚際，出大指之端；其
支者，從腕後直出次指內廉出其端。

**大腸手陽明之脈**，起於大指次指之端，循指上廉，出合谷兩骨之間，上入兩筋之中，循
臂上廉，入肘外廉，上臑外前廉，上肩，出髃骨之前廉，上出於柱骨之會上，下入缺盆，絡
肺，下膈，屬大腸。其支者，從缺盆上頸，貫頰，入下齒中，還出挾口，交人中，左之右，
右之左，上挾鼻孔。

**胃足陽明之脈**，起於鼻之交頞中，旁納太陽之脈，下循鼻外，入上齒中，還出挾口環唇，
下交承漿，卻循頤後下廉，出大迎，循頰車，上耳前，過客主人，循髮際，至額顱；其支者，
從大迎前下人迎，循喉嚨，入缺盆，下膈，屬胃，絡脾；其直者，從缺盆下乳內廉，下挾臍，
入氣沖中；其支者，起於胃口，下循腹裏，下至氣沖中而合，以下髀關，抵伏兔，下膝臏中，
下循脛外廉，下足跗，入中指內間；其支者，下廉三寸而別下入中趾外間；其支者，別跗上，
入大趾間出其端。

**脾足太陰之脈**，起於大趾之端，循趾內側白肉際，過核骨後，上內踝前廉，上踹內，循
脛骨後，交出厥陰之前，上膝股內前廉，入腹，屬脾，絡胃，上膈，挾咽，連吞本，散舌下；
其支者，復從胃，別上膈、注心中。

**心手少陰之脈**，起於心中，出屬心系，下膈，絡小腸；其支者，從心系，上挾咽，系目
系；其直者，復從心系卻上肺，下出腋下，下循臑內後廉，行太陰心主之後，下肘內，循臂
內後廉，抵掌後銳骨之端，入掌內後廉，循小指之內，出其端。

**小腸手太陽之脈**，起於小指之端，循手外側，上腕，出踝中，直上循臂骨下廉，出肘內
側兩筋之間，上循臑外後廉，出肩解，繞肩胛，交肩上，入缺盆，絡心，循咽，下膈，抵胃，
屬小腸；其支者，從缺盆循頸上頰，至目銳眥，卻入耳中；其支者，別頰上?，抵鼻，至目
內眥，斜絡於顴。

**膀胱足太陽之脈**，起於目內眥，上額，交巔；其支者，從巔至耳上角；其直者，從巔入
絡腦，還出別下項，循肩髆內，挾脊，抵腰中，入循膂，絡腎，屬膀胱；其支者，從腰中下
挾脊，貫臀，入膕中；其支者，從髆內左右，別下，貫胛，挾脊內，過髀樞，循髀外，從後
廉，下合膕中，以下貫踹內，出外踝之後，循京骨，至小趾外側。

**腎足少陰之脈**，起於小趾之下，邪走足心，出於然谷之下，循內踝之後，別入跟中，以
上踹內，出膕內廉，上股內後廉，貫脊，屬腎，絡膀胱；其直者，從腎上貫肝膈，入肺中，
循喉嚨，挾舌本；其支者，從肺出絡心，注胸中。

**心主手厥陰心包絡之脈**，起於胸中，出屬心包絡，下膈，歷絡三焦；其支者，循胸出脅，
下腋三寸，上抵腋下，循臑內，行太陰、少陰之間，入肘中，下臂，行兩筋之間，入掌中，
循中指，出其端；其支者，別掌中，循小指次指，出其端。

**三焦手少陽之脈**，起於小指次指之端，上出兩指之間，循手表腕，出臂外兩骨之間，上
貫肘，循臑外，上肩，而交出足少陽之後，入缺盆，布膻中，散落心包，下膈，循屬三焦；
其支者，從膻中上出缺盆，上項系耳後，直上出耳上角，以屈下頰至?，其支者，從耳後入
耳中，出走耳前，過客主人前，交頰，至目銳眥。

**膽足少陽之脈**，起於目銳眥，上抵頭角下耳後，循頸行手少陽之前，至肩上卻交出手少
陽之後，入缺盆；其支者，從耳後入耳中，出走耳前，至目銳眥後；其支者，別銳眥，下大
迎，合於手少陽，抵於?下，加頰車，下頸，合缺盆，以下胸中，貫膈，絡肝，屬膽，循脅
裏，出氣沖，繞毛際，橫入髀厭中；其直者，從缺盆下腋，循胸，過季脅下合髀厭中，以下
循髀陽，出膝外廉，下外輔骨之前，直下抵絕骨之端，下出外踝之前，循足跗上，入小趾次
趾之間；其支者，別跗上，入大指之間，循大指歧骨內，出其端，還貫爪甲，出三毛。

**肝足厥陰之脈**，起於大趾叢毛之際，上循足跗上廉，去內踝一寸，上踝八寸，交出太陰
之後，上膕內廉，循股陰，入毛中，過陰器，抵小腹，挾胃，屬肝，絡膽，上貫膈，布脅肋，
循喉嚨之後，上入頏顙，連目系，上出額，與督脈會於巔；其支者，從目系下頰裏，環唇內；
其支者，復從肝，別貫膈，上注肺。

== 十二原

五藏有六府，六府有十二原，十二原出於四關，四關主治五藏。五藏有疾，當取之十二原。
十二原者，五藏之所以稟三百六十五節氣味也。五藏有疾也，應出十二原。十二原各有所
出。明知其原，睹其應，而知五藏之害矣。

* 陽中之少陰，肺也，其原出於太淵，太淵二。
* 陽中之太陽，心也，其原出於大陵，大陵二。
* 陰中之少陽，肝也，其原出於太沖，太沖二。
* 陰中之至陰，脾也，其原出於太白，太白二。
* 陰中之太陰，腎也，其原出於太溪，太溪二。
* 膏之原，出於鳩尾，鳩尾一。
* 肓之原，出於脖胦，脖胦一。

凡此十二原者，主治五藏六府之有疾者也。

== 奇經八脈

=== 任脈

任脈者，起於中極之下，以上毛際循腹裏上關元至咽喉，上頤循面入目。

沖脈任脈皆起於胞中，上循背裏，為經絡之海，其浮而外者，循腹右上行，會於咽喉，別而
絡唇口，血氣盛則充膚熱肉，血獨盛者澹滲皮膚，生毫毛。今婦人之生有餘於氣，不足於血
以其數脫血也，沖任之脈，不榮口唇，故鬚不生焉。

任脈為病，男子內結七疝，女子帶下瘕聚。

缺盆之中，任脈也，名曰天突。

任脈之別，名曰尾翳。下鳩尾，散於腹。實則腹皮痛，虛則痒搔。取之所別也。

=== 督脈

督脈者，起於少腹以下骨中央，女子入繫廷孔，其孔，溺孔之端也，其絡循陰器合篡閒繞篡
後，別繞臀至少陰，與巨陽中絡者合，少陰上股內後廉，貫脊屬腎，與太陽起於目內眥，上
額交巔，上入絡腦，還出別下項循肩髆，內俠脊抵腰中入循膂絡腎。其男子循莖下至篡，與
女子等。其少腹直上者貫齊中央，上貫心入喉，上頤環脣，上繫兩目之下中央。

其支別者，上額，循巔，下項中，循脊入骶，是督脈也；

督脈之別，名曰長強。挾膂上項，散頭上，下當肩胛左右，別走太陽，入貫膂。實則脊強，
虛則頭重，高搖之，挾脊之有過者。取之所別也。

督脈為病，脊強反折。

此生病從少腹上衝心，而痛不得前後，為衝疝，其女子不孕，癃痔遺溺嗌乾。督脈生病治督
脈，治在骨上，甚者在齊下營，其上氣有音者，治其喉，中央在缺盆中者，其病上衝喉者治
其漸，漸者上俠頤也。

七次脈，頸中央之脈，督脈也，名曰風府。

督脈氣所發者二十八穴；項中央二，髮際後中八，面中三，大椎以下至尻尾及傍十五穴，至
骶下凡二十一節，脊椎法也。

陽明者，五藏六府之海，主閏宗筋，宗筋主束骨而利機關也。衝脈者經脈之海也，主滲灌谿
谷，與陽明合於宗筋，陰陽揔宗筋之會，會於氣街，而陽明為之長，皆屬於帶脈，而絡於督
脈。

=== 衝脈

衝脈者，起於氣街，並少陰之經，俠齊上行，至胸中而散。

衝脈任脈皆起於胞中，上循背裏，為經絡之海，其浮而外者，循腹右上行，會於咽喉，別而
絡唇口

沖脈任脈皆起於胞中，上循背裏，為經絡之海，其浮而外者，循腹右上行，會於咽喉，別而
絡唇口，血氣盛則充膚熱肉，血獨盛者澹滲皮膚，生毫毛。今婦人之生有餘於氣，不足於血
以其數脫血也，沖任之脈，不榮口唇，故鬚不生焉。

衝脈為病，逆氣裏急。

黃帝曰：足少陰何因而動？歧伯曰：沖脈者，十二經之海也，與少陰之大絡，起於腎下，出
於氣街，循陰股內廉，邪入膕中，循脛骨內廉，并少陰之經，下入內踝之後。入足下，其別
者，邪入踝，出屬附上，入大指之間，注諸絡，以溫足脛，此脈之常動者也。


=== 帶脈

足少陰之正，至膕中，別走太陽而合，上至腎，當十四椎出屬帶脈；

陽明者，五藏六府之海，主閏宗筋，宗筋主束骨而利機關也。衝脈者經脈之海也，主滲灌谿
谷，與陽明合於宗筋，陰陽揔宗筋之會，會於氣街，而陽明為之長，皆屬於帶脈，而絡於督
脈。

=== 蹻脈

蹻脈者，少陰之別，起於然骨之後。上內踝之上，直上循陰股，入陰，上循胸裏，入缺盆，
上出人迎之前，入頄，屬目內眥，合於太陽，陽蹻而上行，氣并相還，則為濡，目氣不榮，
則目不合。

=== 維脈

== 十二經筋

**足太陽之筋**，起於足小趾，上結于踝，邪上結于膝，其下循足外側，結于踵，上循跟，
結於膕；其別者，結于腨外，上膕中內廉，與膕中并上結于臀，上挾脊上項；其支者，別入
結于舌本；其直者，結于枕骨，上頭，下顏，結于鼻；其支者，為目上網，下結于頄；其支
者，從腋后外廉結于肩髃；其支者，入腋下，上出缺盆，上結於完骨；其支者，出缺盆，邪
上出于頄。其病小趾支跟腫痛，膕攣，脊反折，項筋急，肩不舉，腋支缺盆中紐痛，不可左
右搖。治在燔鍼劫刺，以知為數，以痛為輸，名曰仲春痺也。

**足少陽之筋**，起於小指次指，上結外踝，上循脛外廉，結於膝外廉；其支者，別起外輔
骨，上走髀，前者結於伏兔之上，後者，結於尻；其直者，上乘?季脅，上走腋前廉，繫於
膺乳，結於缺盆；直者，上出腋，貫缺盆，出太陽之前，循耳後，上額角，交巔上，下走頷，
上結於頄；支者，結於目眥為外維。其病小指次指支轉筋，引膝外轉筋，膝不可屈伸，膕筋
急，前引髀，後引尻，即上乘?季脅痛，上引缺盆、膺乳、頸維筋急。從左之右，右目不開，
上過右角，并蹻脈而行，左絡於右，故傷左角，右足不用，命曰維筋相交。治在燔鍼劫刺，
以知為數，以痛為輸，名曰孟春痺也。

**足陽明之筋**，起於中三指，結於跗上，邪外上加於輔骨，上結於膝外廉，直上結於髀樞，
上循脅屬脊；其直者，上循骭，結於膝；其支者，結於外輔骨，合少陽；其直者，上循伏兔，
上結於髀，聚於陰器，上腹而布，至缺盆而結，上頸，上挾口，合于頄，下結於鼻，上合於
太陽。太陽為目上網，陽明為目下網；其支者，從頰結於耳前。其病足中指支脛轉筋，腳跳
堅，伏兔轉筋，髀前踵，?疝，腹筋急，引缺盆及頰，卒口僻；急者，目不合，熱則筋縱，
目不開，頰筋有寒，則急，引頰移口，有熱則筋弛縱，緩不勝收，故僻。治之以馬膏，膏其
急者；以白酒和桂，以塗其緩者，以桑鉤鉤之，即以生桑炭置之坎中，高下以坐等。以膏熨
急頰，且飲美酒，敢美炙肉，不飲酒者，自強也，為之三拊而已。治在燔鍼劫刺，以知為數，
以痛為輸，名曰季春痺也。

**足太陰之筋**，起於大指之端內側，上結於內踝；其直者，絡於膝內輔骨，上循陰股，結
於髀，聚於陰器，上腹結於臍，循腹裏，結於肋，散於胸中；其內者，著於脊。其病足大指
支內踝痛，轉筋痛，膝內輔骨痛，陰股引髀而痛，陰器紐痛，上引臍兩脅痛，引膺中脊內痛。
治在燔鍼劫刺，以知為數，以痛為輸，命曰孟秋痺也。

**足少陰之筋**，起於小指之下，并足太陰之筋，邪走內踝之下，結於踵，與太陽之筋合，
而上結於內輔之下，并太陰之筋，而上循陰股，結於陰器，循脊內挾膂上至項，結於枕骨，
與足太陽之筋合。其病足下轉筋，及所過而結者皆痛及轉筋。病在此者，主癎瘈及痙，在外
者不能挽，在內者不能仰。故陽病者，腰反折不能俛，陰病者，不能仰。治在燔鍼劫刺，以
知為數，以痛為輸。在內者熨引飲藥，此筋折紐，紐發數甚者死不治，名曰仲秋痺也。

**足厥陰之筋**，起於大指之上，上結於內踝之前，上循脛，上結內輔之下，上循陰股，結
於陰器，絡諸筋。其病足大指支內踝之前痛，內輔痛，陰股痛轉筋，陰器不用，傷於內則不
起，傷於寒則陰縮入，傷於熱則縱挺不收，治在行水清陰氣；其病轉筋者，治在燔鍼劫刺，
以知為數，以痛為輸，命曰季秋痺也。

**手太陽之筋**，起於小指之上，結於腕，上循臂內廉，結於肘內銳骨之後，彈之應小指之
上，入結於腋下；其支者，後走腋後廉，上繞肩胛，循頸出走太陽之前，結於耳後完骨；其
支者，入耳中；直者，出耳上，下結於頷，上屬目外眥。其病小指支肘內銳骨後廉痛，循臂
陰，入腋下，腋下痛，腋後廉痛，繞肩胛引頸而痛，應耳中鳴痛引頷，目瞑良久乃得視，頸
筋急，則為筋瘻頸腫，寒熱在頸者。治在燔鍼劫刺之，以知為數，以痛為輸。其為腫者，復
而銳之。本支者，上曲牙，循耳前屬目外眥，上頷結於角，其痛當所過者支轉筋。治在燔鍼
劫刺，以知為數，以痛為輸，名曰仲夏痺也。

**手少陽之筋**，起於小指次指之端，結於腕，中循臂，結於肘，上繞臑外廉、上肩、走頸，
合手太陽；其支者，當曲頰入繫舌本；其支者，上曲牙，循耳前，屬目外眥，上乘頷，結於
角。其病當所過者，即支轉筋，舌卷。治在燔鍼劫刺，以知為數，以痛為輸，名曰季夏痺也。

**手陽明之筋**，起於大指次指之端，結於腕，上循臂，上結於肘外，上臑，結於髃；其支
者，繞肩胛，挾脊；直者，從肩髃上頸；其支者，上頰，結於頄；直者，上出手太陽之前，
上左角，絡頭，下右頷。其病當所過者，支痛及轉筋，肩不舉，頸不可左右視。治在燔鍼劫
刺，以知為數，以痛為輸，名曰孟夏痺也。

**手太陰之筋**，起於大指之上，循指上行，結於魚後，行寸口外側，上循臂，結肘中，上
臑內廉，入腋下，出缺盆，結肩前髃，上結缺盆，下結胸裏，散貫賁，合賁下抵季脅。其病
當所過者，支轉筋，痛甚成息賁，脅急吐血。治在燔鍼劫刺，以知為數，以痛為輸。名曰仲
冬痺也。

**手心主之筋**，起於中指，與太陰之筋並行，結於肘內廉，上臂陰，結腋下，下散前後挾
脅；其支者，入腋，散胸中，結於臂。其病當所過者，支轉筋前及胸痛息賁。治在燔鍼劫刺，
以知為數，以痛為輸，名曰孟冬痺也。

**手少陰之筋**，起於小指之內側，結於銳骨，上結肘內廉，上入腋，交太陰，挾乳裏，結
於胸中，循臂下繫於臍。其病內急心承伏梁，下為肘網。其病當所過者，支轉筋，筋痛。治
在燔鍼劫刺，以知為數，以痛為輸。其成伏梁唾血膿者，死不治。經筋之病，寒則反折筋急，
熱則筋弛縱不收，陰痿不用。陽急則反折，陰急則俛不伸。焠刺者，刺寒急也，熱則筋縱不
收，無用燔鍼，名曰季冬痺也。

足之陽明，手之太陽，筋急則口目為僻，眥急不能卒視，治皆如右方也。

== 十二經別

**足太陽之正**，別入于膕中，其一道下尻五寸，別入于肛，屬於膀胱，散之腎，循膂，當
心入散；直者，從膂上出於項，復屬於太陽，此為一經也。**足少陰之正**，至膕中，別走
太陽而合，上至腎，當十四椎出屬帶脈；直者，系舌本，復出於項，合於太陽，此為一合。
成以諸陰之別，皆為正也。

**足少陽之正**，繞髀入毛際，合於厥陰，別者入季脅之間，循胸裏屬膽，散之上肝，貫心
以上挾咽，出頤頜中，散於面，繫目系，合少陽於外眥也。**足厥陰之正**，別跗上，上至
毛際，合於少陽，與別俱行，此為二合也。

**足陽明之正**，上至脾，入于腹裏屬胃，散之脾，上通於心，上循咽出於口，上頞?，還
繫目系，合於陽明也。**足太陰之正**，上至髀，合於陽明，與別俱行，上結於咽，貫舌中，
此為三合也。

**手太陽之正**，指地，別於肩解，入腋走心，系小腸也。**手少陰之正**，別入于淵腋兩
筋之間，屬於心，上走喉嚨，出於面，合目內眥，此為四合也。

**手少陽之正**，指天，別於巔，入缺盆，下走三焦，散於胸中也。**手心主之正**，別下
淵腋三寸，入胸中，別屬三焦，出循喉嚨，出耳後，合少陽完骨之下，此為五合也。

**手陽明之正**，從手循膺乳，別於肩髃，入柱骨，下走大腸，屬於肺，上循喉嚨，出缺盆，
合於陽明也。**手太陰之正**，別入淵腋少陰之前，入走肺，散之大陽，上出缺盆，循喉嚨，
復合陽明，此六合也。

== 十五大絡

* **手太陰之別**，名曰列缺。起於腕上分間，并太陰之經，直入掌中，散入于魚際。其病
實則手銳掌熱；虛則欠?，小便遺數。取之去腕寸半。別走陽明也。
* **手少陰之別**，名曰通裏。去腕一寸半，別而上行，循經入于心中，系舌本，屬目系。
其實則支膈，虛則不能言。取之掌後一寸，別走太陽也。
* **手心主之別**，名曰內關。去腕二寸，出於兩筋之間，循經以上，系於心包絡。心系實
則心痛，虛則為頭強。取之兩筋間也。
* **手太陽之別**，名曰支正。上腕五寸，內注少陰；其別者，上走肘，絡肩髃。實則節弛
肘廢；虛則生肬，小者如指痂疥。取之所別也。
* **手陽明之別**，名曰偏歷。去腕三寸，別入太陰；其別者，上循臂，乘肩髃，上曲頰傷
齒；其別者，入耳，合於宗脈。實則齲聾；虛則齒寒痺隔。取之所別也。
* **手少陽之別**，名曰外關。去腕二寸，外繞臂，注胸中，合心主。病實則肘攣，虛則不
收。取之所別也。
* **足太陽之別**，名曰飛揚。去踝七寸，別走少陰。實則鼽窒，頭背痛；虛則鼽衄。取之
所別也。
* **足少陽之別**，名曰光明，去踝五寸，別走厥陰，下絡足跗。實則厥，虛則痿躄，坐不
能起。取之所別也。
* **足陽明之別**，名曰豐隆。去踝八寸。別走太陰；其別者，循脛骨外廉，上絡頭項，合
諸經之氣，下絡喉嗌。其病氣逆則喉痺瘁瘖。實則狂巔，虛則足不收，脛枯。取之所別也。
* **足太陰之別**，名曰公孫。去本節之後一寸，別走陽明；其別者，入絡腸胃，厥氣上逆
則霍亂，實則腸中切痛；虛則鼓脹。取之所別也。
* **足少陰之別**，名曰大鍾。當踝後繞跟，別走太陽；其別者，并經上走於心包下，外貫
腰脊。其病氣逆則煩悶，實則閉癃，虛則腰痛。取之所別者也。
* **足厥陰之別**，名曰蠡溝。去內踝五寸，別走少陽；其別者，經脛上睪，結於莖。其病
氣逆則睪腫卒疝。實則挺長，虛則暴癢。取之所別也。
* **任脈之別**，名曰尾翳。下鳩尾，散於腹。實則腹皮痛，虛則痒搔。取之所別也。
* **督脈之別**，名曰長強。挾膂上項，散頭上，下當肩胛左右，別走太陽，入貫膂。實則
脊強，虛則頭重，高搖之，挾脊之有過者。取之所別也。
* **脾之大絡**，名曰大包。出淵腋下三寸，布胸脅。實則身盡痛，虛則百節盡皆縱。此脈
若罷絡之血者，皆取之脾之大絡脈也。

== 五輸

肺出於少商，少商者，手大指端內側也，為井木；溜于魚際，魚際者，手魚也，為滎；注于
太淵，太淵魚後一寸陷者中也，為俞；行於經渠，經渠寸口中也，動而不居為經；入于尺澤，
尺澤肘中之動脈也，為合。手太陰經也。

心出於中沖，中沖，手中指之端也，為井木；流於勞宮，勞宮掌中中指本節之內間也，為滎；
注于大陵，大陵掌後兩骨之間方下者也，為俞；行於間使，間使之道，兩筋之間，三寸之中
也，有過則至，無過則止，為經；入于曲澤，曲澤，肘內廉下陷者之中也，屈而得之，為合。
手少陰也。

肝出于大敦，大敦者，足大趾之端，及三毛之中也，為井木；溜于行間，行間足大趾間也，
為滎；注于太沖，太沖行間上二寸陷者之中也，為俞；行于中封，中封內踝之前一寸半，陷
者之中，使逆則宛，使和則通，搖足而得之，為經；入于曲泉，曲泉輔骨之下，大筋之上也，
屈膝而得之，為合。足厥陰也。

脾出于隱白，隱白者，足大趾之端內側也，為井木；溜于大都，大都本節之後下陷者之中也，
為滎；注于太白，太白腕骨之下也，為俞；行于商丘，商丘內踝之下陷者之中也，為經；入
于陰之陵泉，陰之陵泉，輔骨之下陷者之中也，伸而得之，為合。足太陰也。

腎出于湧泉，湧泉者足心也，為井木；溜于然谷，然谷，然骨之下者也，為滎；注于太溪，
太溪內踝之後跟骨之上陷中者也，為俞；行于復溜，復溜，上內踝二寸，動而不休，為經；
入于陰谷，陰谷，輔骨之後，大筋之下，小筋之上也，按之應手，屈膝而得之，為合。足少
陰經也。

膀胱出于至陰，至陰者，足小趾之端也，為井金；溜于通谷，通谷，本節之前外側也，為滎；
注于束骨，束骨，本節之後陷者中也，為俞；過于京骨，京骨，足外側大骨之下，為原；行
于昆侖，昆侖，在外踝之後，跟骨之上，為經；入于委中，委中，膕中央，為合，委而取之。
足太陽也。

膽出于竅陰，竅陰者，足小趾次趾之端也，為井金；溜于俠溪，俠溪，足小趾次趾之間也，
為滎；注于臨泣，臨泣，上行一寸半，陷者中也，為俞；過于丘墟，丘墟，外踝之前下陷者
中也，為原。行于陽輔，陽輔外踝之上輔骨之前及絕骨之端也，為經；入于陽之陵泉，陽之
陵泉，在膝外陷者中也，為合，伸而得之。足少陽也。

胃出于厲兌，厲兌者，足大趾內次趾之端也，為井金；溜于內庭，內庭，次趾外間也，為滎；
注于陷谷，陷谷者，上中指內間上行二寸陷者中也，為俞；過于沖陽，沖陽，足跗上五寸陷
者中也，為原，搖足而得之；行于解溪，解溪，上沖陽一寸半陷者中也，為經；入于下陵，
下陵，膝下三寸胻骨外三里也，為合；復下三里三寸，為巨虛上廉，復下上廉三寸，為巨虛
下廉也；大腸屬上，小腸屬下，足陽明胃脈也。大腸小腸，皆屬于胃，是足陽明也。

三焦者，上合手少陽，出于關衝，關衝者，手小指次指之端也，為井金；溜于液門，液門，
小指次指之間也，為滎；注于中渚，中渚，本節之後陷者中也，為俞；過于陽池，陽池，在
腕上陷者之中也，為原；行于支溝，支溝，上腕三寸兩骨之間陷者中也，為經；入于天井，
天井，在肘外大骨之上陷者中也，為合，屈肘而得之；三焦下腧在於足大趾之前，少陽之後，
出于膕中外廉，名曰委陽，是太陽絡也，手少陽經也。三焦者，足少陽太陰之所將太陽之別
也，上踝五寸，別入貫腨腸，出于委陽，並太陽之正，入絡膀胱，約下焦，實則閉癃，虛則
遺溺，遺溺則補之，閉癃則寫之。

手太陽小腸者，上合手太陽，出于少澤，少澤，小指之端也，為井金；溜于前谷，前谷，在
手外廉本節前陷者中也，為滎；注于後溪，後溪者，在手外側本節之後也，為俞；過于腕骨，
腕骨，在手外側腕骨之前，為原；行于陽谷，陽谷，在銳骨之下陷者中也，為經；入于小海，
小海，在肘內大骨之外，去端半寸，陷者中也，伸臂而得之，為合。手太陽經也。

大腸上合手陽明，出于商陽，商陽，大指次指之端也，為井金；溜于本節之前二間，為滎；
注于本節之後三間，為俞；過于合谷，合谷，在大指岐骨之間，為原；行于陽溪，陽溪，在
兩筋間陷者中也，為經；入于曲池，在肘外輔骨陷者中，屈臂而得之，為合。手陽明也。

== 標本根結

* 足太陽之本，在限以上五寸中，標在兩絡命門。命門者，目也。
* 足少陽之本，在竅陰之間，標在窗籠之前。窗籠者，耳也。
* 足少陰之本，在內踝下上三寸中，標在背輸與舌下兩脈也。
* 足厥陰之本，在行間上五寸所，標在背腧也。
* 足陽明之本，在厲兌，標在人迎，頰挾頏顙也。
* 足太陰之本，在中封前上四寸之中，標在背腧與舌本也。
* 手太陽之本，在外踝之後，標在命門之上一寸也。
* 手少陽之本，在小指次指之間上二寸，標在耳後上角下外眥也。
* 手陽明之本，在肘骨中，上至別陽，標在顏下合鉗上也。
* 手太陰之本，在寸口之中，標在腋內動也。
* 手少陰之本，在銳骨之端，標在背腧也。
* 手心主之本，在掌後兩筋之間二寸中，標在腋下下三寸也。

//

* 太陽根于至陰，結于命門。命門者，目也。
* 陽明根于厲兌，結于顙大。顙大者，鉗耳也。
* 少陽根于竅陰，結于窗籠。窗籠者，耳中也。
* 太陰根于隱白，結于太倉。
* 少陰根于湧泉，結于廉泉。
* 厥陰根于大敦，結于玉英，絡于膻中。

//

* 足太陽根于至陰，溜于京骨，注于昆侖，入于天柱、飛揚也。
* 足少陽根于竅陰，溜于丘墟，注于陽輔，入于天容、光明也。
* 足陽明根于厲兌，溜于沖陽，注于下陵，入于人迎，豐隆也。
* 手太陽根于少澤，溜于陽谷，注于小海，入于天窗，支正也。
* 手少陽根于關沖，溜于陽池，注于支溝，入于天牖、外關也。
* 手陽明根于商陽，溜于合谷，注于陽谿，入于扶突、偏歷也。

== 衛氣

黃帝問於歧伯曰：願聞衛氣之行，出入之合，何如？歧伯曰：歲有十二月，日有十二辰，子
午為經，卯酉為緯。天周二十八宿，而一面七星，四七二十八星。房昴為緯，虛張為經。是
故房至畢為陽，昴至心為陰。陽主晝，陰主夜。故衛氣之行，一日一夜五十周於身，晝日行
於陽二十五周，夜行於陰二十五周，周於五藏。

是故平旦陰盡，陽氣出於目，目張則氣上行於頭，循項下足太陽，循背下至小趾之端。其散
者，別於目銳眥，下手太陽，下至手小指之間外側。其散者，別於目銳眥，下足少陽，注小
趾次趾之間。以上循手少陽之分側，下至小指之間。別者以上至耳前，合於頷脈，注足陽明
以下行，至跗上，入五趾之間。其散者，從耳下下手陽明，入大指之間，入掌中。其至於足
也，入足心，出內踝，下行陰分，復合於目，故為一周。

== 營氣

黃帝曰：營氣之道，內穀為寶。穀入于胃，乃傳之肺，流溢於中，布散於外，精專者，行於
經隧，常營無已，終而復始，是謂天地之紀。

* 故氣從太陰出注手陽明，上行注足陽明，下行至跗上，注大指間，與太陰合；
* 上行抵髀，從脾注心中；
* 循手少陰，出腋下臂，注小指，合手太陽；
* 上行乘腋，出䪼內，注目內眥，上巔，下項，合足太陽；
* 循脊，下尻，下行注小指之端，循足心，注足少陰；
* 上行注腎，從腎注心外，散於胸中；
* 循心主脈，出腋，下臂，出兩筋之間，入掌中，出中指之端，還注小指次指之端，合手少
陽；
* 上行注膻中，散於三焦，從三焦注膽，出脅，注足少陽；
* 下行至跗上，復從跗注大指間，合足厥陰；
* 上行至肝，從肝上注肺，上循喉嚨，入頏顙之竅，究於畜門。
* 其支別者，上額，循巔，下項中，循脊入骶，是督脈也；
* 絡陰器，上過毛中，入臍中，上循腹裏，入缺盆，下注肺中，復出太陰。

此營氣之所行也，逆順之常也。

== 十二官

* 心者，君主之官也，神明出焉。
* 肺者，相傅之官，治節出焉。
* 肝者，將軍之官，謀慮出焉。
* 膽者，中正之官，決斷出焉。
* 膻中者，臣使之官，喜樂出焉。
* 脾胃者，倉廩之官，五味出焉。
* 大腸者，傳道之官，變化出焉。
* 小腸者，受盛之官，化物出焉。
* 腎者，作強之官，伎巧出焉。
* 三焦者，決瀆之官，水道出焉。
* 膀胱者，州都之官，津液藏焉，氣化則能出矣。

== 皮部

黃帝問曰：余聞皮有分部，脈有經紀，筋有結絡，骨有度量，其所生病各異，別其分部左右
上下陰陽所在病之始終，願聞其道。歧伯對曰：欲知皮部以經脈為紀者，諸經皆然。

* 陽明之陽，名曰害蜚，上下同法，視其部中有浮絡者，皆陽明之絡也，其色多青則痛，多
黑則痺，黃赤則熱，多白則寒，五色皆見，則寒熱也，絡盛則入客於經，陽主外，陰主內。
* 少陽之陽，名曰樞持，上下同法，視其部中有浮絡者，皆少陽之絡也，絡盛則入客於經，
故在陽者主內，在陰者主出以滲於內，諸經皆然。
* 太陽之陽，名曰關樞，上下同法，視其部中有浮絡者，皆太陽之絡也，絡盛則入客於經。
* 少陰之陰，名曰樞儒，上下同法，視其部中有浮絡者，皆少陰之絡也，絡盛則入客於經，
其入經也，從陽部注於經，其出者，從陰內注於骨。
* 心主之陰，名曰害肩，上下同法，視其部中有浮絡者，皆心主之絡也，絡盛則入客於經。
* 太陰之陰，名曰關蟄，上下同法，視其部中有浮絡者，皆太陰之絡也，絡盛則入客於經。

凡十二經絡脈者皮之部也。

是故百病之始生也，必先於皮毛，邪中之則腠理開，開則入客於絡脈，留而不去，傳入於經，
留而不去，傳入於府，廩於腸胃。邪之始入於皮也，泝然起毫毛，開腠理。其入於絡也，則
絡脈盛色變。其入客於經也，則感虛乃陷下。其留於筋骨之間，寒多則筋攣骨痛，熱多則筋
弛骨消，肉爍䐃破，毛直而敗。帝曰：夫子言皮之十二部，其生病皆何如。歧伯曰：皮者，
脈之部也。邪客於皮則腠理開，開則邪入客於絡脈，絡脈滿則注於經脈，經脈滿則入舍於府
藏也，故皮者有分部，不與，而生大病也。帝曰：善。

黃帝曰：病形何如，取之奈何？伯高曰：夫百病變化，不可勝數，然皮有部，肉有柱，血氣
有輸，骨有屬。黃帝曰：願聞其故。伯高曰：皮之部，輸於四末；肉之柱，有臂脛諸陽分肉
之間，與足少陰分間；血氣之輸，輸於諸絡，氣血留居，則盛而起，筋部無陰無陽，無左無
右，候病所在；骨之屬者，骨空之所以受益而益腦髓者也。

== 九鍼

=== 九鍼形制

九鍼之名，各不同形。

* 一曰鑱鍼，長一寸六分；
* 二曰員鍼，長一寸六分；
* 三曰鍉鍼，長三寸半；
* 四曰鋒鍼，長一寸六分；
* 五曰鈹鍼，長四寸，廣二分半；
* 六曰員利鍼，長一寸六分；
* 七曰毫鍼，長三寸六分；
* 八曰長鍼，長七寸；九曰大鍼，長四寸。

//

* 鑱鍼者，頭大末銳，去寫陽氣；
* 員鍼者，鍼如卵形，揩摩分間，不得傷肌肉，以寫分氣；
* 鍉鍼者，鋒如黍粟之銳，主按脈勿陷，以致其氣；
* 鋒鍼者，刃三隅以發痼疾，鈹鍼者，末如劍鋒，以取大膿；
* 員利鍼者，大如釐，且員且銳，中身微大，以取暴氣；
* 毫鍼者，尖如蚊虻喙，靜以徐往，微以久留之而養，以取痛痺；
* 長鍼者，鋒利身薄，可以取遠痺；
* 大鍼者，尖如梃，其鋒微員，以寫機關之水也。

九鍼畢矣。

黃帝曰：鍼之長短有數乎？歧伯曰：

* 一曰鑱鍼者，取法於巾鍼，去末寸半，卒銳之，長一寸六分，主熱在頭身也。
* 二曰員鍼，取法於絮鍼，筩其身而卵其鋒，長一寸六分，主治分間氣。
* 三曰鍉鍼，取法於黍粟之銳，長三寸半，主按脈取氣，令邪出。
* 四曰鋒鍼，取法於絮鍼，筩其身，鋒其末，長一寸六分，主癰熱出血。
* 五曰鈹鍼，取法於劍鋒，廣二分半，長四寸，主大癰膿，兩熱爭者也。
* 六曰員利鍼，取法於釐鍼，微大其末，反小其身，令可深內也，長一寸六分。主取癰痺者
也。
* 七曰毫鍼，取注于毫毛，長一寸六分，主寒熱痛痺在絡者也。
* 八曰長鍼，取法於綦鍼，長七寸，主取深邪遠痺者也。
* 九曰大鍼，取法於鋒鍼，其鋒微員，長四寸，主取大氣不出關節者也。

鍼形畢矣，此九鍼大小長短法也。

=== 九鍼之治

* 病在皮膚無常處者，取以鑱鍼於病所，膚白勿取。
* 病在分肉間，取以圓鍼於病所。
* 病在經絡痼痺者，取以鋒鍼。
* 病在脈，氣少，當補之者，取以鍉鍼於井滎分俞。
* 病為大膿者，取以鈹鍼。病痺氣暴發者，取以圓利鍼。
* 病痺氣痛而不去者，取以毫鍼。
* 病在中者，取以長鍼。
* 病水腫不能通關節者，取以大鍼。
* 病在五藏固居者，取以鋒鍼，寫於井滎分俞，取以四時。

=== 九鍼之應

黃帝曰：余聞九鍼於夫子，眾多博大矣，余猶不能寤，敢問九鍼焉生，何因而有名？歧伯曰：
九鍼者，天地之大數也，始於一而終於九。故曰：一以法天，二以法地，三以法人，四以法
時，五以法音，六以法律，七以法星，八以法風，九以法野。

黃帝曰：以鍼應九之數，奈何？歧伯曰：夫聖人之起天地之數也，一而九之，故以立九野。
九而九之，九九八十一，以起黃鍾數焉，以鍼應數也。

* 一者，天也。天者，陽也。五藏之應天者肺，肺者，五藏六府之蓋也，皮者，肺之合也，
人之陽也。故為之治鍼，必以大其頭而銳其末，令無得深入而陽氣出。
* 二者，地也。人之所以應土者，肉也。故為之治鍼，必筩其身而員其末，令無得傷肉分，
傷則氣得竭。
* 三者，人也。人之所以成生者，血脈也。故為之治鍼，必大其身而員其末，令可以按脈物
陷，以致其氣，令邪氣獨出。
* 四者，時也。時者，四時八風之客於經絡之中，為瘤病者也。故為之治鍼，必筩其身而鋒
其末，令可以寫熱出血，而痼病竭。
* 五者，音也。音者，冬夏之分，分於子午，陰與陽別，寒與熱爭，兩氣相搏，合為癰膿者
也。故為之治鍼，必令其末如劍鋒，可以取大膿。
* 六者，律也。律者，調陰陽四時而合十二經脈，虛邪客於經絡而為暴痺者也。故為之治鍼，
必令尖如釐，且員其銳，中身微大，以取暴氣。
令尖如蚊虻喙，靜以徐往，微以久留，正氣因之，真邪俱往，出鍼而養者也。
* 八者，風也。風者，人之股肱八節也。八正之虛風，八風傷人，內舍於骨解腰脊節腠理之
間為深痺也。故為之治鍼，必長其身，鋒其末，可以取深邪遠痺。
* 九者，野也。野者，人之節解皮膚之間也。淫邪流溢於身，如風水之狀，而留不能過於機
關大節者也。故為之治鍼，令尖如挺，其鋒微員，以取大氣之不能過於關節者也。

= 刺法

=== 九刺

凡刺有九，以應九變。

* 一曰俞刺，俞刺者，刺諸經滎俞藏俞也；
* 二曰遠道刺，遠道刺者，病在上，取之下，刺府俞也；
* 三曰經刺，經刺者，刺大經之結絡經分也；
* 四曰絡刺，絡刺者，刺小絡之血脈也；
* 五曰分刺，分刺者，刺分肉之間也；
* 六曰大寫刺，大寫刺者，刺大膿以鈹鍼也；
* 七曰毛刺，毛刺者，刺浮痺皮膚也；
* 八曰巨刺，巨刺者，左取右，右取左；
* 九曰焠刺，焠刺者，刺燔鍼則取痺也。

=== 十二刺

凡刺有十二節，以應十二經。

* 一曰偶刺，偶刺者，以手直心若背，直痛所，一刺前，一刺後，以治心痺。刺此者，傍鍼
 之也。
* 二曰報刺，報刺者，刺痛無常處也。上下行者，直內無拔鍼，以左手隨病所按之，乃出鍼，
復刺之也。
* 三曰恢刺，恢刺者，直刺傍之，舉之前後，恢筋急，以治筋痺也。
* 四曰齊刺，齊刺者，直入一，傍入二，以治寒氣小深者；或曰三刺，三刺者，治痺氣小深
者也。
* 五曰揚刺，揚刺者，正內一，傍內四，而浮之，以治寒氣之搏大者也。
* 六曰直鍼刺，直鍼刺者，引皮乃刺之，以治寒氣之淺者也。
* 七曰輸鍼，輸刺者，直入直出，稀發鍼而深之，以治氣盛而熱者也。
* 八曰短刺，短刺者，刺骨痺，稍搖而深之，致鍼骨所，以上下摩骨也。
* 九曰浮刺，浮刺者，傍入而浮之，以治肌急而寒者也。
* 十曰陰刺，陰刺者，左右率刺之，以治寒厥；中寒厥，足踝後少陰也。
* 十一曰傍鍼刺，傍鍼刺者，直刺傍刺各一，以治留痺久居者也。
* 十二曰贊刺，贊刺者，直入直出，數發鍼而淺之，出血是謂治癰腫也。

=== 三刺

所謂三刺，則穀氣出者。先淺刺絕皮，以出陽邪，再刺則陰邪出者，少益深絕皮，致肌肉，
未入分肉間也；已入分肉之間，則穀氣出。故刺法曰：始刺淺之，以逐邪氣，而來血氣，後
刺深之，以致陰氣之邪，最後刺極深之，以下穀氣。此之謂也。

=== 五刺

凡刺有五，以應五藏。

* 一曰半刺，半刺者，淺內而疾發鍼，無鍼傷肉，如拔毛狀，以取皮氣，此肺之應也。
* 二曰豹文刺，豹文刺者，左右前後鍼之，中脈為故，以取經絡之血者，此心之應也。
* 三曰關刺，關刺者，直刺左右盡筋上，以取筋痺，慎無出血，此肝之應也；或曰淵刺；一
曰豈刺。
* 四曰合谷刺，合谷刺者，左右雞足，鍼於分肉之間，以取肌痺，此脾之應也。
* 五曰輸刺，輸刺者，直入直出，深內之至骨，以取骨痺，此腎之應也。

== 四關

手足關節

== 四海

黃帝問于歧伯曰：余聞刺法於夫子，夫子之所言，不離於營衛血氣。夫十二經脈者，內屬於
府藏，外絡於肢節，夫子乃合之於四海乎。歧伯答曰：人亦有四海，十二經水。經水者，皆
注于海，海有東西南北，命曰四海。黃帝曰：以人應之奈何？歧伯曰：人有髓海，有血海，
有氣海，有水榖之海，凡此四者，以應四海也。

黃帝曰：定之奈何？歧伯曰：胃者水穀之海，其輸上在氣街，下至三里；衝脈者，為十二經
之海，其輸上在於大杼，下出於巨虛之上下廉；膻中者，為氣之海，其輸上在於柱骨之上下，
前在於人迎，腦為髓之海，其輸上在於其蓋，下在風府。

黃帝曰：四海之逆順奈何？歧伯曰：氣海有餘者，氣滿胸中，悗息面赤；氣海不足，則氣少
不足以言。血海有餘，則常想其身大，怫然不知其所病；血海不足，亦常想其身小，狹然不
知其所病。水谷之海有餘，則腹滿；水榖之海不足，則飢不受榖食。髓海有餘，則輕勁多力，
自過其度；髓海不足，則腦轉耳鳴，脛痠眩冒，目無所見，懈怠安臥。

胃者水穀之海，六府之大源也。

陽明者，表也，五藏六府之海也，

陽明者，胃脈也，胃者六府之海，

陽明者，五藏六府之海，主閏宗筋，宗筋主束骨而利機關也。

足陽明，五藏六府之海也，其脈大，血多氣盛，熱壯，刺此者不深勿散，不留不寫也。

六府者，胃為之海

胃者，五藏六府之海也，水穀皆入于胃，五藏六府，皆稟氣於胃。

胃者，水谷氣血之海也。

胃為五藏六府之海，

衝脈者經脈之海也，主滲灌谿谷，與陽明合於宗筋，陰陽揔宗筋之會，會於氣街，而陽明為
之長，皆屬於帶脈，而絡於督脈。

夫沖脈者，五藏六府之海也，五藏六府皆稟焉。

沖脈者，十二經之海也，

沖脈任脈皆起於胞中，上循背裏，為經絡之海，

其大氣之搏而不行者，積於胸中，命曰氣海，

== 四街

四街者，氣之徑路也。

請言氣街，胸氣有街，腹氣有街，頭氣有街，脛氣有街。故氣在頭者，止之於腦；氣在胸者，
止之膺與背腧；氣在腹者，止之背腧，與沖脈於臍左右之動脈者；氣在脛者，止之於氣街，
與承山踝上以下。

== 八虛

黃帝問於歧伯曰：人有八虛，各何以候？歧伯答曰：以候五藏。黃帝曰：候之奈何？歧伯曰：

* 肺心有邪，其氣留於兩肘；
* 肝有邪，其氣流於兩腋；
* 脾有邪，其氣留於兩髀；
* 腎有邪，其氣留於兩膕。

凡此八虛者，皆機關之室，真氣之所過，血絡之所遊。邪氣惡血，固不得住留。住留則傷筋
絡骨節；機關不得屈伸，故痀攣也。

