= 癰疽第八十一

黃帝曰：余聞腸胃受穀，上焦出氣，以溫分肉，而養骨節，通腠理。中焦出氣如露，上注谿谷，而滲孫脈，津液和調，變化而赤爲血，血和則孫脈先滿，溢乃注於絡脈，皆盈，乃注於經脈。陰陽已張，因息乃行，行有經紀，周有道理，與天合同，不得休止。切而調之，從虛去實，瀉則不足，疾則氣減，留則先後。從實去虛，補則有餘，血氣已調，形氣乃持。余已知血氣之平與不平，未知癰疽之所從生，成敗之時，死生之期，有遠近，何以度之，可得聞乎？

歧伯曰：經脈留行不止，與天同度，與地合紀。故天宿失度，曰月薄蝕，地經失紀，水道流溢，草萓不成，五穀不殖，徑路不通，民不往來，巷聚邑居，則別離異處，血氣猶然，請言其故。夫血脈營衛，周流不休，上應星宿，下應經數。寒邪客於經絡之中則血泣，血泣則不通，不通則衛氣歸之，不得復反，故癰腫。寒氣化爲熱，熱勝則腐肉，肉腐則爲膿。膿不瀉則爛筋，筋爛則伤骨，骨伤則髓消，不當骨空，不得泄瀉，血枯空虛，則筋骨肌肉不相榮，經脈敗漏，熏於五藏，藏傷故死矣。

黃帝曰：願盡聞癰疽之形，與忌日名。

歧伯曰：癰發於嗌中，名曰：猛疽。猛疽不治，化爲膿，膿不瀉，塞咽，半日死。其化爲膿者，瀉則合豕膏冷食，三曰而已。

發於頭，名曰夭疽，其癰大以赤黑，不急治則熱氣下入淵腋，前傷任脈，內熏肝肺。熏肝肺，十餘曰而死矣。

陽留大發，消腦留項，名曰腦爍，其色不樂，項痛而如刺以鍼。煩心者，死不可治。

發於肩及臑，名曰疵癰，其狀赤黑，急治之，此令人汗出至足，不害五藏。癰發四五日，逞焫之。

發於腋下赤堅者，名曰米疽，治之以砭石，欲細而長，疏砭之，塗以豕膏，六曰已，勿裹之。其癰堅而不潰者，为馬刀挾癭，急治之。

發於胸，名曰井疽，其狀如大豆，一二三四日起，不早治，下入腹，不治，七曰死矣。

發於膺，名曰甘疽，色青，其狀如穀實𦸈𧁾（瓜蔞），常苦寒熱，急治之，去其寒熱，十歲死，死後出膿。

發於脅，名曰敗疵，敗疵者，女子之病也，灸之，其病大癰膿，治之，其中乃有生肉，大如赤小豆，剉䔖𧄍草根各一升，以水一斗六升煮之，竭爲取三升，則强飲厚衣，坐於釜上，令汗出足已。

發於股脛，名曰股脛疽，其狀不甚變，而癰膿搏骨，不急治，三十日死矣。

發於尻，名曰銳疽，其狀赤堅大，急治之，不治，三十曰死矣 。

發於股陰，名曰赤施，不急治，六十日死，在兩股之內，不治十日而當死。

發於膝，名曰疵癰，其狀大，癰色不變，寒熱，如堅石，勿石，石之者死，須其柔，乃石之者生。

諸癰疽發於節而相應者，不可治也。發於陽者，百日死；發於陰者，三十日死。

發於脛，名曰兔嚙，其狀赤至骨，急治之，不治害人也。

發於內踝，名曰走緩，其狀癰也，色不變，數石其輸，而止其寒熱，不死。

發於足上下，名曰四淫，其狀大癰，急治之，百日死。

發於足傍，名曰厲癰，其狀不大，初如小指，發，急治之，去其黑者，不消輙益，不治，百日死。

發於足趾，名曰脫癰，其狀赤黑，死不治；不赤黑，不死。不衰，急斬之，不則死矣。

黃帝曰：夫子言癰疽，何以別之？

歧伯曰：營衛稽留於經脈之中，則血泣而不行，不行則衛氣從之而不通，壅而不得行，故熱。大熱不止，熱勝則肉腐，肉腐則爲膿。然不能陷，骨髓不爲燋枯，五藏不爲傷，故命曰癰。

黃帝曰：何爲疽？

歧伯曰：熱氣淳盛，下陷肌膚，筋髓枯，內連五藏，血氣竭，當其癰下，筋骨良肉皆無餘，故命曰疽。疽者，上之皮夭以堅，上如牛領之皮。癰者，其皮上薄以澤。此其候也。
