= 五腧穴——总论篇 
王非
2015-6-10 00:00

include::王非.adoc[]

立新师父曾经讲过，把《灵枢》经的开篇《九针十二原》读懂了、读透了，后面的篇章就不
用读了，其实是说整本书的精华、主旨都包括在内。其中有这样一段话：“黄帝曰：愿闻五
脏六腑所出之处。岐伯曰：五脏五俞，五五二十五俞，六腑六俞，六六三十六俞，经脉十二，
络脉十五，凡二十七气，以上下。所出为井，所溜为荥，所注为俞，所行为经，所入为合，
二十七气所行，皆在五俞也。”此中所讲的正是五腧穴。

另外师父还强调过这样一句话*“卫气者，出其悍气之慓疾，而先行于四末分肉皮肤之间，
而不休息也。”*《灵枢·邪客》综上所言，我们都知道五腧穴的重要性，《灵枢》开篇就提
到了，而且是十二经脉、十五络脉，这二十七气的上下出入之所在。这五腧穴也正好就分布
在四末，就是四肢肘、膝关节之下，是卫气先行之所在。

既然五腧穴如此重要，那么接下来，我就和大家一起重新在《内经》中，复习整理这五腧穴。

== 【五腧穴在痹证中的作用】

“帝曰：以针治之奈何？岐伯曰：五脏有俞，六腑有合，循脉之分，各有所发，各随其过，
则病瘳(chōu，病愈)也。”《素问·痹论》

发生痹证的风寒湿邪进入人体的途径就是通过俞穴，排出风寒湿邪的途径也要靠俞穴。

*根据师父上下游的理论，又结合卫气运行的特点，凡是痹症都可考虑配合五脏的俞穴。*

五脏的配合“合穴”::
* 肝俞太冲，
* 心俞大陵，
* 脾俞太白、
* 肺俞太渊、
* 肾俞太谿。

六腑合穴::
* 胃之合三里，
* 胆之合阳陵泉，
* 大肠之合曲池，
* 小肠之合小海，
* 三焦之合委阳，
* 膀胱之合委中。

== 【五腧穴的应用与季节相关】

“帝曰：秋取经俞何也？岐伯曰：秋者金始治，肺将收敛，金将胜火，阳气在合，阴气初胜，
湿气及体阴气未盛，未能深入，故取俞以泻阴邪，取合以虚阳邪，阳气始衰，故取于合。”
《素问·水热穴论》

阴经的五腧穴与季节相配

井（木）春 荥（火）初夏 俞（土）长夏 经（金）秋 合（水）冬随着季节的交替，人体内
的阴阳也在转换，为了更好的配合自然界的季节转换，*五腧穴可以按照承前启后的原则取
用*：

* 秋天：俞穴   合穴
* 冬天：经穴   井穴
* 春天：合穴   荥穴
* 初夏：井穴   俞穴
* 长夏：荥穴   经穴

== 【五腧穴在治疗咳嗽中的应用】

“帝曰：治之奈何？岐伯曰：治脏者治其俞，治腑者治其合，浮肿者治其经。帝曰：善。”
《素问·咳论》治疗五脏的咳嗽。要取俞穴；治疗六腑的咳嗽，要取合穴；凡是由于咳嗽而
致浮肿的，要取经穴。

小编按：看了王非师兄为大家整理的五腧穴——总论篇，想必大家很想知道每条经脉五腧穴的
相关知识吧？别着急，下一期我们将请王非师兄为大家详细的谈谈肺经上的五腧穴，敬请期
待哦！
