= 肝的五输穴
王非
2015-7-22 00:00

include::王非.adoc[]

* 肝出于大敦，大敦者，足大趾之端，及三毛之中也，为井木；
* 溜于行间，行间足大趾间也，为荥；
* 注于太冲，太冲行间上二寸陷者之中也，为俞；
* 行于中封，中封内踝之前一寸半，陷者之中，使逆则宛，使和则通，摇足而得之，为经；
* 入于曲泉，曲泉辅骨之下，大筋之上也，屈膝而得之，为合。足厥阴经也。

== 【大敦】

=== 原文定位

. 足大趾之端，及三毛之中也。《灵枢·本枢》
. 邪客于足厥阴之络，令人卒疝暴痛。刺足大指爪甲上与肉交者，各一痏，男子立已，女子
有顷已，左取右，右取左。《素问·缪刺论》
. 肝足厥阴之脉，起于大趾丛毛之际。《灵枢·经脉》

=== 国标定位

在足趾，大趾末节外侧（靠第二趾一侧）趾甲根角侧后方0.1寸（约三毫米处）。

我们看到这两个定位是不太相同的，原文中提到两个地方，一个是足大趾“之端”，一个是
“三毛之中”“大趾丛毛际”，一个是“足大指爪甲上与肉交者”。这三个描述给我们圈定
了一个大致的范围就是足大趾背侧长毛的地方以及足大趾顶端与指甲交接的地方。师父教导
我们把经络立体看，所以穴位也应当是个区域，也应当是个立体的。

== 功效

治疗“邪客于足厥阴之络，令人卒疝暴痛”。邪客于足厥阴之络：足厥阴蠡沟之络，其别者，
循胫上睾，结于茎，故病卒疝暴痛也。疝痛者，阴之病也。

疝::
心腹气痛。
+
疝,腹痛也。从疒,山声。——《说文》
+
腹痛不得大小便,病名曰疝。——《素问·长俠节论》

== 【行间】

=== 定位

足大趾间也。

=== 功能
. 厥心痛，色苍苍如死状，终日不得太息，肝心痛也，取之行间、太冲。《灵枢·厥病》
+
厥心痛，面色青色，像死人一样，整天不能做深长的呼吸。这是肝心痛。治疗应取用行间、
太冲两穴刺之。

. 邪在肝，则两胁中痛，寒中，恶血在内，行善掣节，时脚肿。取之行间，以引胁下，补三
里以温胃中，取血脉以散恶血；取耳间青脉，以去其掣。《灵枢·五邪》
+
邪在肝脏，就会发生两胁里疼痛，中焦虚寒，瘀血在里边，胫节经常肿大，容易发生抽引痉
挛，治疗可取行间穴，以引胁下之气下行，补三里穴，以温中焦，刺本经血络以散恶血，又
取耳间青脉，以消除它的抽引症状。

== 【太冲】

=== 定位

行间上二寸陷者之中。

=== 功能

. 原穴：阴中之少阳，肝也，其原出于太冲。《灵枢·九针十二原》
. 厥心痛，色苍苍如死状，终日不得太息，肝心痛也，取之行间、太冲。 《灵枢·厥病》
. 肝痹者，夜卧则惊，多饮，数小便，上为引如怀。
+
肝痹的症状，是夜间睡眠多惊，好饮水，小便次数多，上引少腹，膨满的情况象怀孕时一样。

=== 治疗

肝俞、太冲。

== 【中封】

=== 定位

“中封内踝之前一寸半，陷者之中，使逆则宛，使和则通，摇足而得之。”宛,屈草自覆
也。——《说文》

此穴的取穴当是一边摇足一边定位，就是被动活动踝关节的时候取穴。

=== 功能

肝咳之状，咳则左胁痛，甚者不得转侧，转则两脚下满。《灵枢·咳论》

肝咳的证状，咳嗽的时候，左胁痛，严重了，不能行走，如行走，两脚就会肿的。

== 【曲泉】

=== 定位

曲泉辅骨之下，大筋之上也，屈膝而得之。

请大家注意取穴的体位----屈膝。

=== 功效

病注下血，取曲泉。《灵枢·厥病》

患泄下血的，治疗可取曲泉穴刺之。
