= 浅谈九针
穆超
2015-11-3 10:00

include::穆超.adoc[]

== 开栏寄语

吕蒙正在《寒窑赋》中曰：“时也，运也”。在中华民族再次崛起的新时代，中华文化的复
兴，也迎来了祖国医学复兴之机，而失传了千年的古九针在这一时代亦应运还原！让世人赞
叹的是，立新七针创始人陈立新师父，毫不保留地将自己参悟到的针理、针法传授于后学之
辈。俗语曰：“师父领进门，修行靠个人”，师弟穆超虽然只跟师学习了九天，经过一年多
立新七针的运用，凭借自身的聪慧、超凡的悟性、扎实的临床功底，掌握了立新七针的精髓，
更因其与生俱有的社会责任感和悲悯心，愿引领更多人学习内经，提高医技，帮助病患。用
《灵枢微言》与大家进行交流学习。今日《灵枢微言》积于跬步，相信明日必凌于高峰。

祖国医学博大精深，护佑着中华民族的繁衍生息数千年，像一颗璀璨的明珠，闪耀在东方，
照亮了全球。我们睿智的华夏先哲们留给炎黄子孙一部受用无穷的中医经典——《黄帝内经》，
经典浩瀚如海，里藏明珠无数，历代医家擢取一二便各领风骚数百年！近年来，更是百花齐
放，百家争鸣，各种针法层出不穷，虽各有所长，但终不究竟。尤其西学东渐，各种解剖理
论大行其道，让我等中医学子心有不甘，想我泱泱大国五千年，竟被二三百年的西学所打败？
立志重回经典，怎奈文章晦涩难懂，参考注解，眼花缭乱，有的言之凿凿，却与临床不符，
有的前后矛盾，避重就轻。不免抚文轻叹，大有入宝山而空回之憾！直至跟随恩师陈立新先
生，方恍然有悟，恩师将十数年之体悟倾囊相授，犹如醍醐灌顶，自此方有宝藏之钥，泛海
之舟。今把最近跟师所悟略述一二，敬请斧正！

自看灵枢以来，开篇就有莫大疑问，篇名九针十二原，何为九针？缘何为九？十二原又是什
么东东？又有何为？为何放置卷首？临床又有何用？（此处下回分解）后面又有“欲以微针
通其经脉”，“小针之要，易陈而难入”，“凡刺之要，官针最妙”，前有九针，微针、小
针、官针又是什么样的针？是九针之一？还是另有所指？这一连九问，是不是大家有点蒙圈？
诸位莫急，且听不才一一道来！

== 何为九针？

“九针之名，各不同形：一曰镵针，长一寸六分；二曰员针，长一寸六分；三曰鍉针，长三
寸半；四曰锋针，长一寸六分；五曰铍针，长四寸，广二分半；六曰员利针，长一寸六分；
七曰毫针，长三寸六分；八曰长针，长七寸；九曰大针，长四寸。”

看到这里我们明白了，九针就是九种大小尺寸不同的针具！有人说了，这不废话吗？顾名思
义，九针就是九种针具嘛！这点语文常识还是有的！那为何偏偏是九不是八呢？

== 缘何为九？

其实不光是你，就连黄帝也有此疑问！此话怎讲，有据为证！

《灵枢·九针论第七十八》黄帝曰：余闻九针于夫子，众多博大矣，余犹不能寤，敢问九针
焉生，何因而有名？

黄帝问了，九针是怎么来的？为什么是九?黄帝一问，岐伯答了。

岐伯曰：九针者，天地之大数也，始于一而终于九。故曰：一以法天，二以法地，三以法人，
四以法时，五以法音，六以法律，七以法星，八以法风，九以法野。

岐伯说了，为什么用九呢？因为九是天地之间最大的数！看看古人对针是多么的重视，和皇
帝一样尊贵（皇帝是九五之尊）！为什么对针重视，因为针是救人用的，著名医家窦汉卿要
求医者做到“目无外视，手如握虎，心无内慕，如待贵人”。扯得有点远，言归正传!

黄帝是比较较真的人，可能嫌岐伯回答得太简单，所以又问：“以针应九之数，奈何？”

岐伯又答：“夫圣人之起天地之数也，一而九之，故以立九野。九而九之，九九八十一，以
起黄钟数焉，以针应数也。”

岐伯说古代圣人发明了天地的数理，从一到九为基本数，所以据此建立了九州的分野。若将
九与九相乘，九九八十一，便创立了黄钟之数，九针正与此数相应。

为什么非要与黄钟之数对应呢，这里要给大家科普一下：古时以黄钟定五音中的宫音，应于
土（土能生金，土生万物）。用竹制成，管状，长九寸，而古时定寸乃是以九粒黍排列的纵
长度为准，所以黄钟长为八十一黍，故黄钟数即八十一。

看到这里，大家就知道古人对针是多么的推崇，又是多么的严谨！那既然这么推崇九针，又
为何出来个微针、小针、官针呢？且听我细细道来！

== 微针之微

“黄帝问于岐伯曰：余子万民，养百姓而收其租税。余哀其不给，而属有疾病。余欲勿使被
毒药，无用砭石，欲以微针通其经脉，调其血气，营其逆顺出入之会。”

九针十二原开篇就说要以微针通其经脉，这和标题不搭边呀，微是微小的微吗?还是精微的
微？这时候有人就开始搬出厚厚的康熙字典，抑或是权威的说文解字，查的不亦乐乎！

莫急莫急，再往下看，咦，有了，“刺之微，在速迟”，我相信这句话稍微有点语文常识的
都知道啥意思了吧，前后贯通，恍然大悟，微针之微在这里是形容词，微针实指微妙、精微
的九针针法！

看到这里，有人就说了，你说微针不是指微小的针，那“小针之要，易陈而难入”的小针就
是微小的针了吧（有人更是理解成毫针），对于您这样的想法我真是想和您拥抱一下，因为
您和我当初想的是一样一样地，不过现在不同的是我有明师指点，略有小悟，不再断章取义，
听我详解小针之小！

== 小针之小

《灵枢·玉版第六十》黄帝曰：余以小针为细物也，夫子乃言上合之于天，下合之于地，中
合之于人，余以为过针之意矣，愿闻其故。岐伯曰：何物大于天乎？夫大于针者，惟五兵者
焉。五兵者，死之备也，非生之具。且夫人者，天地之镇也，其不可不参乎？夫治民者，亦
惟针焉。夫针之与五兵，其孰小乎？

看到这句话，我想大家已经很明白了，小针之小是与五兵之大相对而言，五兵顾名思义就是
古代的五种兵器，有说五兵者，戈、殳、戟、酋矛、夷矛，也有云五兵者，谓矛、戟、弓、
剑，戈。关于五兵到底是哪五兵与本文没有太大关系，就像孔乙己回字的五种写法一样没有
意义，不必纠结。

且看这段话的言外之意，“五兵者，死之备也，非生之具”。古人再次推崇九针是生之具，
是济世救人的，“夫治民者，亦惟针焉”！

所以本章最后黄帝说了“善乎方，明哉道，请著之玉版，以为重宝，传之后世，以为刺禁，
令民勿敢犯也。”（顺便科普一下，玉版是指古代用以刻字的玉片，亦泛指珍贵的典籍。）
黄帝不仅把九针刻在玉版上，还制定了严格的官方标准，再看官针之官。

== 官针之官

《灵枢·官针第七》凡刺之要，官针最妙。

此处之官，有两层意思，一是官方制定的标准九针，二是管理，分管之意，为什么这样解释？

因为后面说了“九针之宜，各有所为，长短大小，各有所施也，不得其用，病弗能移。疾浅
针深，内伤良肉，皮肤为痈；病深针浅，病气不泻，支为大脓。病小针大，气泻太甚，疾必
为害；病大针小，气不泄泻，亦复为败。失针之宜，大者泻，小者不移，已言其过，请言其
所施。病在皮肤无常处者，取以镵针于病所，肤白勿取。病在分肉间，取以员针于病所。病
在经络痼痹者，取以锋针。病在脉，气少，当补之者，取以鍉针于井荥分俞。病为大脓者，
取以铍针。病痹气暴发者，取以员利针。病痹气痛而不去者，取以毫针。病在中者，取以长
针。病水肿不能通关节者，取以大针。病在五脏固居者，取以锋针，泻于井荥分俞，取以四
时。

这句话大体意思就是说这九种针都是国家任命、官方认可的，每种针负责的都不一样（“九
针之宜，各有所为”），不同的病用不同的针，如果是脉的病就用鍉针，筋的病就用员利针
等等。就像交警管交通，刑警管治安，法警管执行！

看到这里，细心的读者可能已经感觉到古人的用心良苦了，古人虽然惜字如金，但又怕今人
有误，总是前面设疑，后面详解！就怕后人断章取义，不求甚解！纵观内经，确有山穷水复
疑无路，柳暗花明又一村之妙！但是这样就能看懂内经了吗？其实不然，没有明师（这里是
明白的明哦）指点，缺少临床上的反复印证，更没有世事练达的通明，我想自己的解读恐怕
也有风马牛不相及的尴尬吧！
