= 小议十二原
穆超
2015-12-1 18:00

include::穆超.adoc[]

灵枢开篇把十二原和九针并列放在篇首标题中说明其重要性！那么，十二原的重要性表现在
哪里呢？为什么叫十二“原”？十二原的具体位置？临床当中又是如何应用的呢？

== 十二原之原

“原”字的本义是“源泉”，如《左传·昭公九年》：“木水之有本原。”也就是说：木有
本，水有源。从这个本义又引申为开始、起源，如《管子·水地》：“地者，万物之本原。”

在上古根本没有“源”字。一个“原”字既表示“水源”，又表示“平原”。到了后世，人
们才在“原”字的左边加了“三点水”，形成了左形（水）右声（原）的 “源”字，而本
来的“原”只代表“平原”等等。这样就使“原”、“源”分工明确了。在这里的原既有源
泉、本原之说，又有原气之意，并不单指十二经脉之原穴（因为还有膏之原，肓之原，为什
么提出这两个原，按下不表，下回分解）虽然灵枢第一篇只提到了五脏的原和膏肓的原，但
是标题中的十二原应该包括六腑的十二原，不然不会有“凡此十二原者，主治五脏六腑之有
疾者也”！古人也是想的周到，怕后人断章取义，所以紧接着在《灵枢·本输第二》中提出
了六腑的十二原！


== 十二原的具体位置

阳中之少阴，肺也，其原出于太渊，太渊二。阳中之太阳，心也，其原出于大陵，大陵二。
阴中之少阳，肝也，其原出于太冲，太冲二。阴中之至阴，脾也，其原出于太白，太白二。
阴中之太阴，肾也，其原出于太溪，太溪二。膏之原，出于鸠尾，鸠尾一。肓之原，出于脖
胦，脖胦一。

看到这里，细心的读者就会发现心的原穴取得是心包经的大陵穴，为什么呢？因为心无腧
（阴经以腧为原）穴之缘故。在《灵枢·邪客篇》中黄帝曰：手少阴之脉独无腧，何也？岐
伯曰：少阴，心脉也。心者，五脏六腑之大主也，精神之所舍也，其脏坚固，邪弗能容也。
容之则心伤，心伤则神去，神去则死矣。故诸邪之在于心者，皆在于心之包络。包络者，心
主之脉也，故独无俞焉。

这段话的意思就是心是五脏六腑之大主，是藏神的重要位置，是不能受邪的，只能心包代为
受过！就像现在国外的有些重要人物都有几个替身一样，你懂的！

现在十二原的具体位置已经非常清晰了，那么十二原的重要作用又是什么呢，在临床中的意
义何在，这才是我们医者真正关心的!


== 十二原的存在意义和临床作用

为什么十二原这么重要？

第一，十二原可以断病。

“五脏有疾也，应出十二原，十二原各有所出，明知其原，睹其应，而知五脏之害矣”！

十二原为什么能够反映出五脏的疾病呢？

因为“十二原者，五脏之所以禀三百六十五节气味也”！

“五脏有六腑”，是说五脏之气全部来源于六腑中的饮食营养。这里的“有”是用其本义，
即手中持肉，肉在古人心目中是最高级的营养，故“有”又有营养来源的涵义。“六腑有十
二原”，是说六腑又以十二个原穴为原，也就是六腑之所以能够消化吸收饮食营养，其原动
力又来源于十二个原穴。如此一来，十二个原穴在生理上的重要性显而易见。

十二原穴之所以能够提供原动力，成为六腑之源，完全是因为它源于骨髓，而出于四关。
“关”与“节”本来都可以代指骨关节，但是“关”往往特指较大的骨关节，“四关”则是
特指两个手腕关节和两个脚踝关节。手腕关节和脚踝关节又是四肢末端最大和最主要的关节，
《灵枢·动输第六十二》又说“夫四末阴阳之会者，此气之大络也”。又是阴阳交会的地方，
为全身脉气之根，则四关其实就是骨髓发生神气最主要的通道，于是也就相当于生命的源泉，
此所以古人把四关部位的腧穴统称为“原”。探寻生命之原，本来就是医学的终极目的。故
在《内经》作者看来，一旦明晰了生命之原的奥秘，就等于掌握了根本，一切关于疾病和健
康的问题就都可以迎刃而解了，所以他们对生命之原更是孜孜以求，费尽了心机。

实际上，正是由于“原”就是《内经》全部生理学、病理学和治疗学的核心，所以才会作为
第一等重要的问题在开宗明义的第一篇文章中讲述。那么当五脏出现问题时十二原又是如何
表现的呢？比如在临床中经常看到肾气大虚的患者太溪穴是凹陷的，肝阳上亢的患者会在太
冲穴出现压痛甚至条索等等。

第二，十二原可以治五脏之病！

“五脏有疾，当取之十二原，……凡此十二原者，主治五脏六腑之有疾者也”。

五脏出现问题时他的临床症状又有什么表现呢？在《灵枢·经脉第十》中对于五脏有疾的具
体表现有了详细论述。

* “是主肺所生病者，咳，上气喘渴，烦心胸满，臑臂内前廉痛厥，掌中热。气盛有余，则肩
背痛风寒，汗出中风，小便数而欠。气虚则肩背痛寒，少气不足以息，溺色变”。
* “是主脾所生病者，舌本痛，体不能动摇，食不下，烦心，心下急痛，溏、瘕、泄、水闭，
黄疸，不能卧，强立股膝内肿厥，足大趾不用”。
* “是主心所生病者，目黄胁痛，臑臂内后廉痛厥，掌中热痛”。
* “是主肾所生病者，口热舌干，咽肿上气，嗌于及痛，烦心心痛，黄疸肠澼，脊股内后廉
痛，痿厥嗜卧，足下热而痛”。
* “是主肝所生病者，胸满呕逆飧泄，狐疝遗溺闭癃”。

对于上述临床表现我们都可以取相应脏腑的原穴予以治疗，并且古人对于五脏气绝在皮肉筋
骨脉上的具体表现描述的更为详细！

* “手太阴气绝则皮毛焦。太阴者行气温于皮毛者也，故气不荣则皮毛焦；皮毛焦则津液去
皮节；津液去皮节者，则爪枯毛折；毛折者则毛先死。丙笃丁死，火胜金也。
* ”手少阴气绝，则脉不通；脉不通则血不流；血不流，则发色不泽，故其面黑如漆柴者，
血先死，壬笃癸死，水胜火也。
* 足太阴气绝者则脉不荣肌肉，唇舌者肌肉之本也，脉不荣则肌肉软；肌肉软则舌萎人中满；
人中满则唇反；唇反者肉先死，甲笃乙死，木胜土也。
* 足少阴气绝则骨枯。少阴者冬脉也，伏行而濡骨髓者也，故骨不濡则肉不能著也；骨肉不
相亲则肉软却；肉软却故齿长而垢发无泽；发无泽者骨先死，戊笃己死，土胜水也。
* 足厥阴气绝则筋绝。厥阴者肝脉也，肝者筋之合也，筋者聚于阴气，而脉络于舌本也，故
脉弗荣则筋急；筋急则引舌与卵，故唇青舌卷卵缩则筋先死，庚笃辛死，金胜木也。

当然，在患者有了上述症状时仅仅取用原穴治疗是远远不够的，不然内经就不会长篇大论详
述各种病机和治疗原理了，但十二原的提出在五脏有疾的诊断和治疗上有了提纲挈领的重要
意义，让我们在临床治疗上不再迷失方向！
