= 膏肓之谜
穆超
2015-12-15 18:00

include::穆超.adoc[]

《灵枢•九针十二原》中提到膏之原在鸠尾，肓之原在脖胦，引起了我深深的思考！十二原
出于四关，其他十原都在四关很好理解，那膏、肓之原在任脉上和四关有何关联？膏肓的提
出到底对五脏有疾有何治疗意义？我想，对于这些问题的解答首先我们要知道膏肓到底是什
么?

== 膏肓是什么？

膏肓到底是什么？度娘一搜，有些头大！历代医家众说纷纭，莫衷一是！说得最多的解释为
心尖脂肪为膏，心脏与隔膜之间为肓。到底谁说得对，咱们暂且不去理会。因为师父说过解
读《黄帝内经》的九个原则之一“不拘泥于前人之见”，我们最好还是从原文里找寻答案！

在内经中“膏”字一共出现了十次，有八次从字义上皆与本文所探讨不符，比如，“身无膏
泽”、“膏梁菽藿之味”、“白如豕膏者生”等等。当然一次是膏之原，还有一次膏的出现
引起了我的关注，《灵枢•五癃津液别》：“五谷之津液和合而为膏者，内渗入于骨空，补
益脑髓，而下流于阴股。”从这句话中我们不难理解膏实为五谷精华之所化！所以在《春秋
•元命苞》（一部旷世奇书，值得一读）中说到“膏者，神之液”。

在内经中“肓”字一共出现了七次，“其气溢于大肠而着于肓”、“故循皮肤之中，分肉之
间，熏于肓膜，散于胸腹”、“膈肓之上，中有父母”、“针不陷肓，则气不行”！从这些
字里行间我们可以得出肓指的是膜，现在解剖学中我们可以了解到五脏六腑都是挂在膜上，
皮肉筋骨脉都有膜！能够贯通五脏六腑、连通全身上下的只有三焦系统，三焦主气所生病，
所以才有“针不陷肓，则气不行”之说!

咱们再看一个有意思的现象，在背部足太阳膀胱经两条线上的穴位排布：肺藏魄，肺腧——魄
户，心藏神，心腧——神堂，肝藏魂，肝腧——魂门，脾藏意，脾腧——意舍，肾藏志，肾腧——志
室，三焦腧——肓门！当然还有一个更重要的：厥阴腧——膏肓！这个对应直接关系到膏之原、
肓之原的定位问题！

== 膏之原、肓之原

大家都知道心主神明，为五脏六腑之大主，厥阴心包代心受过。《灵枢·邪客篇》：心者，
五脏六腑之大主也，精神之所舍也，其脏坚固，邪弗能容也。容之则心伤，心伤则神去，神
去则死矣。故诸邪之在于心者，皆在于心之包络。如果心包不能抵御病邪，让其长驱直入，
直逼神明之府，我想这就是《左传·成公十年》中所说的病入膏肓了吧，身无膏泽，双目无
神，形肉已夺！所以保护好君王所居之地至关重要。那么君王除了常住紫禁城外，还有外出
散心时的行宫，所以膏之原为鸠尾（又名神府），肓之原为脖胦（又名神阙）。

对于脖胦到底是肚脐还是气海穴历代医家也有争论！在这里赘述一下我的观点。咱们先从字
面上去理解，脖，脖子，脚脖子，手脖子，脖必是连通上下之处，其特点必是两头略粗，中
间偏细（今时之人，大腹便便居多，竟然不易形容，真是汗颜），胦，中央，瓜秧，肚脐又
是婴儿连接母体之秧，人之初生，正是瓜熟蒂落之时！

再有《素问·腹中论篇》：“其气溢于大肠而著于肓，肓之原在脐下，故环脐而痛也”。这
里“肓之原在脐下”是说肓膜的根本点集结于肚脐之内（这里是以仰卧的姿势看，肚脐内部
即为“脐下”。），不然不会“环”脐而痛。另外在《灵枢·四时气》：“气盛则厥逆，上
冲肠胃，熏肝，散于肓，结于脐。故取之肓原以散之……”。此处“散于肓，结于脐”这句
话也进一步说明“肓”之根本点集结在肚脐，所以窃以为肓之原当为肚脐（神阙）！那么膏
肓和四关是什么关系呢？

== 膏肓与四关

在<<02-小议十二原.adoc#,《小议十二原》>>中我提到四关是骨髓发生神气最主要的通道，
那么四关的骨髓神气怎么来的呢？通过膏肓而来，前面说到膏由五谷精微所化，实为提供心
火燃烧之柴薪，在火热作用下所处为液态，在心火燃烧后气化蒸发的部分通过肓膜通达四末！
那么膏肓之原的提出有什么临床意义呢？

== 膏、肓之原的临床价值

说到其临床价值，我们要借用师父解读内经的原则之一：旁征博引一切经得起推敲的观点。
这里我们引用一下西医的临床解剖，通过解剖发现，鸠尾穴正对横膈膜的中心，肚脐又在腹
膜之中央！再看内经中如何谈及横膈膜及腹膜的重要性！

* 《素问·刺禁论篇》：“鬲肓之上，中有父母，七节之傍，中有小心，从之有福，逆之有
  咎。”
+
（这里主要说的是横膈膜）
* 《素问·腹中论篇》：“其气溢于大肠而著于肓，肓之原在脐下，故环脐而痛也。”
* 《素问·痹论篇》：“卫者，水谷之悍气也，其气慓疾滑利，不能入于脉也，故循皮肤之
中，分肉之间，熏于肓膜，散于胸腹，逆其气则病，从其气则愈，不与风寒湿气合，故不为
痹。”
* 《灵枢·四时气》：“腹中常鸣，气上冲胸，喘不能久立，邪在大肠，刺肓之原、巨虚上
廉、三里。小腹控睪，引腰脊，上冲心，邪在小肠者，连睪系，属于脊，贯肝肺，络心系。
气盛则厥逆，上冲肠胃，熏肝，散于肓，结于脐。故取之肓原以散之，刺太阴以予之，取厥
阴以下之，取巨虚下廉以去之，按其所过之经以调之。”
* 《灵枢·胀论》：“岐伯对曰：此言陷于肉、肓而中气穴者也。不中气穴，则气内闭，针
不陷肓，则气不行；上越中肉，则卫气相乱，阴阳相逐。”
* 《素问·举痛论》：“寒气客于小肠膜原之间……”
* 《灵枢·百病始生》：“虚邪之中人也……或著于肠胃之募原……”
* 《灵枢·岁露论》：“内抟于五脏，横连募原。”（古人募通膜）

从以上内经原文可以看出膏（横膈膜）以鸠尾为中心开天辟地，分隔清浊，肓（腹膜）以脖
胦为中心通连三焦，化生万物。因此，膏肓就犹如一个T字，象天平一样对称平衡（双天枢
就是一对砝码），是以在《素问·经脉别论篇》中又称之为“权衡”。“府精神明，留于四
脏，气归于权衡。权衡以平，气口成寸，以决死生。”权衡失职，则容易病入膏肓，命不久
矣！可见古人诚不欺我！
