= 上守神
穆超
2015-12-29 18:00

include::穆超.adoc[]

《灵枢•九针十二原》作为灵枢经开篇明义的第一篇自有很多提纲挈领的精要，上守神便是
灵枢经的精华所在！上守神，守得是谁之神？神具体指的是什么?如何去守？编者以为首先
守得是医者之神！

== 医者之神

作为医者，“夫大医之体，欲得澄神内视，望之俨然，宽裕汪汪，不皎不昧，省病诊疾，至
意深心，详察形候，纤毫勿失，处判针药，无得参差，虽曰病宜速救，要须临事不惑，唯当
审谛覃思，不得于性命之上，率而自逞俊快，邀射名誉，甚不仁矣。又到病家，纵绮罗满目，
勿左右顾盼；丝竹凑耳，无得似有所娱；珍羞迭荐，食如无味；醽醁（línglù）兼陈，看
有若无。”真正能做到《大医精诚》所言，才能真正让患者生起无量信心！治病之时又需神
在秋毫，属意病者！目无外视，手如握虎；心无内慕，如待贵人。凡刺之法，先必本于神，
只有这样才能知其往来，达到如汤泼雪，效如桴鼓！

尤其遇到特殊情况之时，医者能否守住自身之神至关重要，比如患者晕针之时，轻者头晕目
眩，面色苍白，恶心欲吐，多汗心慌，四肢发凉。甚或神志昏迷，仆倒在地，唇甲青紫，浑
身抽搐，两眼上翻。此时家属已慌，自己倘若惊慌失神，不能镇定自如，有条不紊救治病人，
恐怕关门之日不远矣！正如《素问•疏五过论》中所说：“医不能严，不能动神，外为柔弱，
乱至失常，病不能移，则医事不行，此治之四过也。”除了医者在治病之时的镇定自若以外，
医者本身的精气神也至关重要！试想一下，当患者怀着最后的希望找到你，却看到一个两眼
无神、满脸菜色、萎靡不振，面容冷漠的医生时，其心里的失望可想而知！所以一个医者自
身的修为是至关重要的！

一个好的中医应该上知天文下知地理，中通人事，一个连待人接物，处事之道都做不好的中
医到底能取得多大的成就呢？我在跟同行讨论的时候经常说的一句话就是：一个名中医和一
个普通的中医医师开出同一个药方，患者吃了效果大多是不一样的！这也就是安慰剂有的时
候（大多是心因性疾病）能起效的原因吧！当然这已经超出守神的范畴，应该是治神的一部
分了，此是后话，按下不表！

== 病家之神

《灵枢•小针解》：上守神者，守人之血气有余不足可补泻也。从这句话中说明上守神主要
是讲守病家之神！病家之神有轻重强弱之分。根据病家之神的强弱可以准确判断病家病情程
度、愈后如何！当患者如《素问•汤液醪醴论》所说“帝曰：形弊血尽而功不立者何？岐伯
曰：神不使也。帝曰：何谓神不使？岐伯曰：针石，道也。精神不进，志意不治，故病不可
愈。今精坏神去，荣卫不可复收。何者？嗜欲无穷，而忧患不止，精气弛坏，荣泣卫除，故
神去之而病不愈也。”又或当患者出现“衣被不敛，言语善恶，不避亲疏者，此神明之乱
也。”《素问•脉要精微论》对于这样的病人如果你不在大医院上班抑或自己不是名家大医，
还是请患者另寻高明方为上策！那么这里的神具体指的是什么呢？

== 何者为神

* 《灵枢•小针解》：“神者，正气也。＂
* 《灵枢·营卫生会》：“营卫者精气也，血者神气也。”
* 《灵枢·平人绝谷》：“故神者，水谷之精气也。”
* 《素问·八正神明论》：“血气者，人之神。”

从这些话中可以得出这里的“神”是广义之说，“神”其实指的是人的气血。气血强弱与否
直接决定一个人的精神、魂魄和志意，而心藏神，肺藏魄，脾藏意，肝藏魂，肾藏精，“是
故用针者，察观病人之态，以知精神魂魄之存亡得失之意，五者以伤，针不可以治之也。”
那么对于这种情况怎么办呢？“诸小者，阴阳形气俱不足，勿取于针，而调以甘药也。”

== 如何去守

“守”的本义是官吏的职责、职守，在这里“守”还有保护，卫护的意思。“上守神”也就
是说真正高明的医生（本文称作上工或上医）在治病之时要善于关注、保护、调养病家的气
血，而不是像一个“粗工”只关注病人的形体或者疼痛的部位（粗守形），盲目的头痛医头、
脚疼医脚，丝毫不关注病家的气血强弱与否，不能以通为用，把病人扎成“刺猬”的奇怪针
法随处可见。就连一个木工甚或一个不懂医理的普通老百姓都知道“钉多木烂”，况于人乎！
如何去守呢？去守哪里？编者以为重点要守“节”！为什么呢？“所言节者，神气之所游行
出入也”，因为节是神气出入的地方，那么节有多少呢？“节之交，三百六十五会”，这么
多节都要去守吗？嘿嘿！那和粗工有何两样，其实我们只守重大，重要的节就可以了，比如，
“夫四末阴阳之会者，此气之大络也”，“肺心有邪，其气留于两肘”，等等，守住这些重
要的节我们就能“一夫当关万夫莫开”了。

看到这里我想大家都明白了，所谓“上守神”，也就是说，上工的职责非常明确，针刺的目
的就是为了调治气血，打通病家容易发生瘀堵的“节”，以通为用，让气血周流，恢复人体
本身的阴阳和合、阴升阳降。当然，在这里还是要提醒大家一句，虽说“神就是气血”，但
是并不意味着“神”就是普通的气和血。当一个存着必死之心又或心如死灰的人即使有着充
盈的气和血，你又怎么能扭转乾坤呢？内经有云“病不许治者，病必不治，治之无功矣”。
所以古人在造字时“病”字里面为“丙”，意指丙丁火者，心也。真正的病为心之病，心之
欲望无尽，则生种种奇病怪病，今之治病难也，既要疗身之疾，又要祛心之病！所以才有了
古人“上工十全九”之感慨！

