= 针之道
穆超
2016-1-19 18:00

include::穆超.adoc[]

**导读：**往者为逆，来者为顺，明知逆顺，正行无问。迎而夺之，恶得无虚，追而济之，
恶得无实，迎之随之，以意和之，针道毕矣。

《九针十二原》作为《灵枢经》开宗明义的第一篇首先就是确立整个灵枢经的基调和意义。
编者以为主要是以下三点：

. 第一：高调推出九针，希望传于后世，可以终而不灭，久而不绝，易用难忘！
. 第二：提出十二原，确立医学的终极目标就是解决众生疾苦，探寻生命之原！
. 第三：确立解决问题的方法和准则！也就是今天和大家探讨的针之道！

当然在整个灵枢经中几乎全是关于针刺的描述，因为篇幅有限，不想大家看的厌烦，咱们只
是把《九针十二原》中是如何提纲挈领的叙述针之道的帮大家归纳出来！

== 针刺的时机

“粗守关，上守机，机之动，不离其空，空中之机，清静而微，其来不可逢，其往不可追。
知机之道者，不可挂以发，不知机道，扣之不发，知其往来，要与之期，粗之暗乎，妙哉工
独有之。”

这段话告诉我们一个好的医生应该善于把握病家的病机，找寻疾病背后的真相，而不是被病
名所迷惑，盲目的头疼医头，应该通过对患者整体气血的旺衰、经气运行逆顺的把控，在合
适的时机，进行准确的针刺。

== 针刺的目的

“往者为逆，来者为顺，明知逆顺，正行无问。迎而夺之，恶得无虚，追而济之，恶得无实，
迎之随之，以意和之，针道毕矣。”

这句话告诫医家针刺的目的就是为了一个“和”字，通过补虚泄实，以通为用，不贪天之功，
不一味的补或泄，见好就收，达到身心和，志意和，阴阳和！

== 针刺的手法与技巧

“持针之道，坚者为宝。正指直刺，无针左右，神在秋毫，属意病者，审视血脉者，刺之无
殆。方刺之时，必在悬阳，及与两卫，神属勿去，知病存亡。血脉者在俞横居，视之独澄，
切之独坚。”

“睹其色，察其目，知其散复；一其形，听其动静，知其邪正，右主推之，左持而御之，气
至而去之。”

对这两句话的理解有异议的地方就是“坚者为宝”的解释。很多医家解释“坚者为宝”指的
是刺手要坚定有力或者针具应该刚硬不易弯曲！编者以为另有深意，纵观整部内经，与
“坚”字相连的不外乎“肉”“脉”等字，比如“肉之坚脆”、“脉大而坚”，后面又有一
句“血脉者在俞横居，视之独澄，切之独坚。”所以联系上下文可以得出这两段文字实则指
的是针刺的手法和经验技巧。他告诉我们针刺的时候，我们要非常注意比较坚硬的结节、条
索和暴起的血络，这些都是我们需要关注或者直接解决的，临床中我们看到这样的阳性点是
非常高兴的，就像破案时我们在犯罪现场找到罪犯留下的蛛丝马迹一样，对于这样的蛛丝马
迹我们会像宝贝一样重视的！而对于犯罪现场找不到任何蛛丝马迹的刑事案件警察们都是非
常头疼的！所以对于和疾病有关的条索或者筋节我们要“正指直刺，无针左右”，对于“在
俞横居”的血脉我们要“刺之无殆”！

在操作过程中，必须聚精会神于针下的感觉，明察秋毫。同时还要凝神注意病者神态的变化，
并细心观察病人血脉的虚实，惟有这样去进行针刺，才不致发生不良的后果。

“右主推之，左持而御之”是指针刺的手法和要求，一个“推”字用的妙极，不仅告诉我们
进针不是飞针，更不是靠寸劲，而是慢慢的挤进去，既告诉我们进针的手法，又告诫我们要
宁慢勿快！并且针刺时要两手配合，一阴一阳，“左手重而多按，欲令气散；右手轻而徐入，
不痛之因。”（《标幽赋》）。

写到这里，既感叹古人用字之巧，又感动古人用心之苦！想到自己以前扎针时单手进针、貌
似插秧还自以为潇洒自如的手法，不禁汗颜！唉，简直羞死宝宝了！

== 针具的选择

“九针之名，各不同形：一曰镵针，长一寸六分；二曰员针，长一寸六分；三曰鍉针，长三
寸半；四曰锋针，长一寸六分；五曰铍针，长四寸，广二分半；六曰员利针，长一寸六分；
七曰毫针，长三寸六分；八曰长针，长七寸；九曰大针，长四寸。镵针者，头大末锐，去泻
阳气。员针者，针如卵形，揩摩分间，不得伤肌肉者，以泻分气。鍉针者，锋如黍粟之锐，
主按脉勿陷，以致其气。锋针者，刃三隅，以发痼疾。铍针者，末如剑锋，以取大脓。员利
针者，大如氂，且员且锐，中身微大，以取暴气。毫针者，尖如蚊虻喙，静以徐往，微以久
留之而养，以取痛痹。长针者，锋利身薄，可以取远痹。大针者，尖如梃，其锋微员，以泻
机关之水也。九针毕矣。”

这段话告诉我们古人在治疗过程中对于针具的选择是非常重视的，因古人知道“针各有所宜，
各不同形”，只有选择合适的针具才能在治疗中事半功倍，才能各任其所，而这才是真正的
“为刺之要”。

== 针刺的深浅

“夫气之在脉也，邪气在上，浊气在中，清气在下。故针陷脉则邪气出，针中脉则浊气出，
针太深则邪气反沉、病益。故曰：皮肉筋脉，各有所处，病各有所宜。各不同形，各以任其
所宜，无实无虚”。

这段话主要提醒医家注意针刺的深浅，如果“疾浅针深，皮肤为痈；病深针浅，病气不泻，
支为大脓”。从这里我们也就不难理解临床中为什么病人容易反复，也不难理解把病人扎起
个大包的尴尬了！

== 有效的标准

“刺之而气不至，无问其数。刺之而气至，乃去之，勿复针。气至而有效，效之信，若风之
吹云，明乎若见苍天，刺之道毕矣。”

这句话主要是讲气至与否直接决定针刺的效果！那么这个气至指的是针灸的针感吗？是出现
酸麻沉胀的反应吗?绝对不是！至于到底是什么，我们会在以后的篇章重点论述！

== 针刺的禁忌

“五脏之气已绝于内，而用针者反实其外，是谓重竭，重竭必死，其死也静，治之者，辄反
其气，取腋与膺；五脏之气已绝于外，而用针者反实其内，是谓逆厥，逆厥则必死，其死也
躁，治之者，反取四末。”

针灸的禁忌很多在此不一一论述，而编者把这个禁忌单独放在开宗明义的第一篇，只是因为
这个禁忌直接关乎病人瞬间的生死存亡！不可不察！慎之又慎！

如果上述这些要领和注意事项都做得很好，就可以如书所言“夫善用针者，取其疾也，犹拔
刺也，犹雪污也，犹解结也，犹决闭也。疾虽久，犹可毕也。”如果还是解决不了病人的痛
苦这说明“言不可治者，未得其术也。”那就需要好好研究灵枢经后面的章节，从分论中去
找寻答案，把整个针之道细化整合，真正的做到效若桴鼓、风之吹云！

