= 本输之意
穆超
2016-2-2 18:00

include::穆超.adoc[]

*导读：*凡刺之道，必通十二经络之所终始，络脉之所别处，五俞之所留，六腑之所与合，
四时之所出入，五脏之所溜处，阔数之度，浅深之状，高下所至。愿闻其解。

《九针十二原》作为开宗明义的第一篇从理论上阐述了用九针去探究人体生理、病理及生命
本源的针灸之道，而《本输第二》则是这一理论体系的具体实践内容。
 
== 何为本输

本，根本、本原之意；输，输送，输注，本输一是指人体五脏六腑经气本原输注的地方，当
然也有最根本的腧穴之意！

《九针十二原》中我们知道人体有三百六十五个腧穴（节之交，三百六十五会），这些腧穴
都是神气之所游行出入的地方，从理论上讲不管针刺哪个腧穴都会对人体产生影响，但是这
么多腧穴对于很多医者来讲还是有些“不知其要”以至于“流散无穷”。所以古人用心良苦，
深知医家之难，把重点的腧穴进行概括归纳，这就是本输！本输的提出既是对三百六十五个
腧穴的高度概括，又是对十二原的有效补充！从此我们在临床治疗中不再大海捞针，遍山寻
贼！那么这些重要的腧穴都是有哪些呢？《本输第二》篇首就给出了答案！

“黄帝问于岐伯曰：凡刺之道，必通十二经络之所终始，络脉之所别处，五俞之所留，六腑
之所与合，四时之所出入，五脏之所溜处，阔数之度，浅深之状，高下所至。愿闻其解。”

从这句话我们可以知道通往针刺大道的第一步就必须掌握十二经络的终始，络脉的别处，五
俞之所留，六腑之所与合，四时之所出入，五脏之所溜处，而这些是针刺最根本的技术，也
是本输的意义所在！

== 十二经络的终始

十二经络的终始是最基本也是很重要的本输，细心的读者会发现所谓的终始就是后面提到的
根结和标本！

“奇邪离经，不可胜数，不知根结，五脏六腑，折关败枢，开合而走，阴阳大失，不可复取。
九针之玄，要在终始；故能知终始，一言而毕，不知终始，针道咸绝。”（《根结第五》）
“能知六经标本者，可以无惑于天下。”（《卫气第五十二》）。

从这些话语中不难看出终始的重要性！但是如果大家就简单的以为终始只是一条经络的起止
点那就太小看古人的智慧了，其实终始还包括经络堵塞或病变的起始症状和最终后果！这就
是后面文章提到的“是动则病”和“其终也”。

“膀胱足太阳之脉，起于目内眦，······循京骨，至小趾外侧。是动则病冲头痛，目似脱，
项如拔，脊痛腰似折，髀不可以曲，腘如结，踹如裂，是为踝厥。”

“太阳之脉，其终也，戴眼反折瘈瘲，其色白，绝皮乃绝汗，绝汗则终矣。”

写到这里不由得明白古人为什么总是说“终始”而不是“始终”，古人把“终”放在前面其
实就是告诫后人要重视和分辨病人的危重表现，不要盲目救治，从而给自己和病人徒增痛苦
和烦恼！为人处世也是一样，孔子在《大学》中讲到：“物有本末，事有终始，知所先后，
则近道矣。” 也就是说不管是做事情还是治病救人一定要先考虑到事情的最坏结果，或者
能够准确的判断病人的危重程度，从而十二分的警醒自己做人处事、治病救人不光要有始有
终，还要审时度势，分清轻重缓急，如果做到了就离（针）道不远了！

== 络脉之所别处

此处指的是十五络穴，有书为证。《经脉第十》：

* 手太阴之别，名曰列缺，···
* 手少阴之别，名曰通里，···
* 手心主之别，名曰内关，···
* 手太阳之别，名曰支正，上腕五寸，内注少阴；其别者，上走肘，络肩髃。实则节弛肘废；
虚则生肬，小者如指痂疥。取之所别也。
* 手阳明之别，名曰偏历，···取之所别也。
* 手少阳之别，名曰外关，去腕二寸，外绕臂，注胸中，合心主。病实则肘挛，虚则不收，
取之所别也。
* 足太阳之别，名曰飞扬。去踝七寸，别走少阴。实则鼽窒头背痛；虚则鼽衄，取之所别也。
* 足少阳之别，名曰光明，去踝五寸，别走厥阴，下络足跗。实则厥，虚则痿躄，坐不能起，
取之所别也。
* 足阳明之别，名曰丰隆，去踝八寸，别走太阴；其别者，循胫骨外廉，上络头项，合诸经
之气，下络喉嗌。其病气逆则喉痹瘁瘖，实则狂巅，虚则足不收胫枯，取之所别也。
* 足太阴之别，名曰公孙。去本节之后一寸，别走阳明；其别者，入络肠胃，厥气上逆则霍
乱，实则肠中切痛；虚则鼓胀。取之所别也。
* 足少阴之别，名曰大钟，当踝后绕跟，别走太阳；其别者，并经上走于心包，下外贯腰脊。
其病气逆则烦闷，实则闭癃，虚则腰痛，取之所别者也。
* 足厥阴之别，名曰蠡沟，去内踝五寸，别走少阳；其别者，经胫上睾，结于茎。其病气逆
则睾肿卒疝，实则挺长，虚则暴痒，取之所别也。
* 任脉之别，名曰尾翳，下鸠尾，散于腹。实则腹皮痛，虚则痒搔，取之所别也。
* 督脉之别，名曰长强，挟膂上项，散头上，下当肩胛左右，别走太阳，入贯膂。实则脊强，
虚则头重，高摇之，挟脊之有过者，取之所别也。
* 脾之大络，名曰大包。出渊腋下三寸，布胸胁。实则身尽痛，虚则百节尽皆纵，此脉若罗
络之血者，皆取之脾之大络脉也。

凡此十五络者，实则必见，虚则必下，视之不见，求之上下，人经不同，络脉亦所别也。

这段话既写出了络脉所别之地，更详细描述了络脉出现问题时的具体症状！
 
== 五俞之所留

显而易见这里指的是我们临床中常用的五输穴，在《九针十二原》中：

“黄帝曰：愿闻五脏六腑所出之处。岐伯曰：五脏五俞，五五二十五俞，六腑六俞，六六三
十六俞，经脉十二，络脉十五，凡二十七气，以上下，所出为井，所溜为荥，所注为俞，所
行为经，所入为合，二十七气所行，皆在五俞也。”

从这段话我们可以知道五输穴是五脏六腑经气所停留的地方，通过针刺五输穴可以有效治疗
五脏六腑引起的功能性疾病！他的重要性不言而喻，历代医家多有论述，在此不再赘言！

== 六腑之所与合

这里指的是下合穴，在《邪气脏腑病形第四》中：

“黄帝曰：合各有名乎？岐伯答曰：胃合于三里，大肠合入于巨虚上廉，小肠合入于巨虚下
廉，三焦合入于委阳，膀胱合入于委中央，胆合入于阳陵泉。···

黄帝曰：愿闻六腑之病。岐伯答曰：面热者足阳明病，鱼络血者手阳明病，两跗之上脉竖陷
者，足阳明病，此胃脉也。

* 大肠病者，肠中切痛，而鸣濯濯。冬日重感于寒即泄，当脐而痛，不能久立，与胃同候，
取巨虚上廉。
* 胃病者，腹䐜胀，胃脘当心而痛，上支两胁，膈咽不通，食饮不下，取之三里也。
* 小肠病者，小腹痛，腰脊控睪而痛，时窘之后，当耳前热，若寒甚，若独肩上热甚，及手
小指次指之间热，若脉陷者，此其候也。手太阳病也，取之巨虚下廉。
* 三焦病者，腹气满，小腹尤坚，不得小便，窘急，溢则水，留即为胀。候在足太阳之外大
络，大络在太阳少阳之间，亦见于脉，取委阳。
* 膀胱病者，小腹偏肿而痛，以手按之，即欲小便而不得，肩上热若脉陷，及足小趾外廉及
胫踝后皆热，若脉陷，取委中央。
* 胆病者，善太息，口苦，呕宿汁，心下淡淡，恐人将捕之，嗌中吤吤然，数唾，在足少阳
之本末，亦视其脉之陷下者灸之，其寒热者取阳陵泉。”

这段话明确告诉医家下合穴的名称和主治范围。由此可见古人的体贴入微！细心地令人发指，
更进一步体现了古代医家对生命的重视！

== 四时之所出入　

“春取络脉诸荥大经分肉之间，甚者深取之，间者浅取之。夏取诸俞孙络肌肉皮肤之上。秋
取诸合，余如春法。冬取诸井诸俞之分，欲深而留之。此四时之序，气之所处，病之所舍，
脏之所宜。”

这段话主要告诉我们治病时要和于四时，根据季节的变化选取一些腧穴作为治疗的重点！

== 五脏之所溜处

初看到这里的时候，百思不得其解，所溜为荥，难道指的是五条阴经的荥穴，那样的话不是
重复了吗？直到看到下面一段话才恍然大悟！

《邪客第七十一》“黄帝问于岐伯曰：人有八虚，各何以候？岐伯答曰：以候五脏。黄帝曰：
候之奈何？岐伯曰：肺心有邪，其气留于两肘；肝有邪，其气流于两腋；脾有邪，其气留于
两髀；肾有邪，其气留于两腘。凡此八虚者，皆机关之室，真气之所过，血络之所游。邪气
恶血，固不得住留。住留则伤筋络骨节机关，不得屈伸，故痀挛也。”

原来五脏之所留为八大关节！所以我们经常在肘膝关节针刺或放血以去全身之邪，而髀腋之
处又被冠以八把半锁（民间绝技）之白虎锁、还魂锁，常常用于急危重症病人的急救，可见
一夫当关万夫莫开，重中之重，不得不察！
 
== 天部之所集结

缺盆之中，任脉也，名曰天突。一次，任脉侧之动脉足阳明也，名曰人迎；二次脉，手阳明
也，名曰扶突；三次脉，手太阳也，名曰天窗；四次脉，足少阳也，名曰天容；五次脉，手
少阳也，名曰天牖；六次脉，足太阳也，名曰天柱；七次脉，颈中央之脉，督脉也，名曰风
府。腋内动脉手太阴也，名曰天府。腋下三寸手心主也，名曰天池。

上述穴位皆在心肺以上接近头项，心为君主，又称天子，肺法象天幕，头项又为一身之最高，
即为天部，这些穴位大都以天字冠名（也叫天牖五部），又在入髓海的必经之路，可见在临
床上的重要意义！

总之《本输第二》集合了古人认为非常重要的一些腧穴，有标本，有根结，有五输穴，有络
穴，有下合穴，有天牖五部，更提出了我们临床上要重点检查的八大关节，且要和于四时辨
证施治！但这也仅仅是针道最基础的入门功夫，为学日益，你我共勉！夜已深，意犹未尽，
世界晚安！
