= 千古一“绝”
穆超
2016-3-1 18:00

include::穆超.adoc[]

*导读：*何为五脏之气？内指的是什么？外指的是什么？什么情况才是绝于内？什么情况才
是绝于外？如何正确判断是绝于内还是绝于外？为什么取腋与膺？为什么要反取四末？历代
医家众说纷纭，莫衷一是！有的含糊其辞，一带而过；有的前后矛盾，不能自圆其说；有的
言之凿凿，却与临床不符，以致这千古一“绝”终成医家之谜！

《灵枢·九针十二原》提出九针的针道体系，为大道，为天，所以《灵枢·九针十二原》法天，
《灵枢·本输》指出了针道的具体方向和要点，是脚踏实地的具体标示，所以《灵枢·本输》
法地，《灵枢·小针解》则是实现针道的具体方法和技巧！所有针道技法无不靠人来具体实
施和展现，所以《灵枢·小针解》法人！通过文章可以看到《小针解》通篇都是对《九针十
二原》的详细注解，小针指的是九针（详看我的第一篇文章<<01-浅谈九针.adoc#,《浅谈九
针》>>），里面的大部分内容在文章<<05-针之道.adoc#,《针之道》>>中已经说的非常详细
了，不再赘述！今天我们就里面很小的一段话，也是困扰大多数医家的一段话，进行探讨论
述！

== 请看原文

五脏之气已绝于内，而用针者反实其外，是谓重竭，重竭必死，其死也静，治之者，辄反其
气，取腋与膺；五脏之气已绝于外，而用针者反实其内，是谓逆厥，逆厥则必死，其死也躁，
治之者，反取四末。 《灵枢·九针十二原》

所谓五脏之气已绝于内者，脉口气内绝不至，反取其外之病处与阳经之合，有留针以致阳气，
阳气至则内重竭，重竭则死矣，其死也无气以动，故静。所谓五脏之气已绝于外者，脉口气
外绝不至，反取其四末之输，有留针以致其阴气，阴气至则阳气反入，入则逆，逆则死矣，
其死也阴气有余，故躁。《灵枢·小针解》

== 整合一下

我们把上述两段话整合一下！

“所谓五脏之气已绝于内者，脉口气内绝不至，而用针者反实其外，反取其外之病处与阳经
之合，有留针以致阳气，阳气至则内重竭，重竭则死矣，其死也无气以动，故静。治之者，
辄反其气，取腋与膺；所谓五脏之气已绝于外者，脉口气外绝不至，而用针者反实其内，有
留针以致其阴气，阴气至则阳气反入，入则逆，是谓逆厥，逆则死矣，其死也阴气有余，故
躁。治之者，反取四末。”

看到这里，问题来了！何为五脏之气？内指的是什么？外指的是什么？什么情况才是绝于内？
什么情况才是绝于外？如何正确判断是绝于内还是绝于外？为什么取腋与膺？为什么要反取
四末？历代医家众说纷纭，莫衷一是！有的含糊其辞，一带而过；有的前后矛盾，不能自圆
其说；有的言之凿凿，却与临床不符，以致这千古一“绝”终成医家之谜！读到此处，我也
是百思不得其解，思之再三，忽一日想起师妹刘凌燕的一个病例，又联系上下文及临床所感，
才恍然大悟！

== 引经据典

黄帝曰：气独行五脏，不容六腑，何也？岐伯答曰：气之不得无行也，如水之流，如日月之
行不休，故阴脉荣其脏，阳脉荣其腑，如环之无端，莫知其纪，终而复始，其流溢之气，内
溉脏腑，外濡腠理。《灵枢·脉度第十七》

黄帝问于少师曰：余闻人之生也，有刚有柔，有弱有强，有短有长，有阴有阳，愿闻其方。
少师答曰：阴中有阴，阳中有阳，审知阴阳，刺之有方。得病所始，刺之有理。谨度病端，
与时相应。内合于五脏六腑，外合于筋骨皮肤。是故内有阴阳，外亦有阴阳。在内者，五脏
为阴，六腑为阳，在外者，筋骨为阴，皮肤为阳。故曰，病在阴之阴者，刺阴之荥俞，病在
阳之阳者，刺阳之合，病在阳之阴者，刺阴之经，病在阴之阳者，刺络脉。《灵枢·寿夭刚
柔第六》


== 内外之别

看到这两段话，我们就明白五脏之气实为一身之正气，内指的是五脏六腑，外指的是筋骨皮
肤！

所谓五脏之气已绝于内指的是五脏已伤，“是故五脏，主藏精者也，不可伤，伤则失守而阴
虚，阴虚则无气，无气则死矣”（《灵枢·本神第八》），“脏先病而形乃应”，五脏有疾
则皮肉筋骨失常，如果医家错以为只是单纯的皮肉筋骨之病，而“反取其外之病处与阳经之
合”（病在阳之阳者，刺阳之合），在病变的皮肉筋骨和阳经的合穴上留针，以使阳气隆盛，
从而阴气大虚（重竭），阴虚则无气，无气则死矣！

所谓五脏之气已绝于外指的是皮肉筋骨大坏，出现皮焦肉痿，筋弛骨枯！而“用针者反实其
内，有留针以致其阴气，阴气至则阳气反入，入则逆，是谓逆厥，逆则死矣，其死也阴气有
余，故躁。”阴气者，静则神藏，躁则消亡。（《素问·痹论》）

== 如何判断

如何判断五脏之气已绝呢？通过脉口气的强弱来断！“太阴主内，太阳主外”，“少气者，
脉口人迎俱少而不称尺寸也。”（《灵枢·终始第九》），当寸口脉的寸部摸不到脉或者脉
细而微则表示五脏之气已绝于内，当寸口脉的尺部摸不到脉或者脉细而微则表示五脏之气已
绝于外！

== 治之奈何

当五脏之气已绝的时候如何治疗呢？

“五脏之气已绝于内，······取腋与膺；五脏之气已绝于外，······治之者，反取四末。”
《灵枢·九针十二原》

有人问了为什么绝于内要取腋与膺，绝于外要取四末？其实腋下我们主要是弹拨极泉穴，而
极泉穴为心经之首穴，心属火，膺我们主要是取肾经在胸部的穴位（气逆上，刺膺中陷者），
而肾属水，“水火者，阴阳之征兆也”《素问·阴阳应象大论》！为什么取四末呢？“夫四
末阴阳之会者，此气之大络也。······四末解则气从合，相输如环。”（《灵枢·动输第六
十二》）！从这几句话我们知道之所以取腋与膺和四末，只是为了沟通表里，调和阴阳，使
气从合，从而达到气血运行的如环无端！

== 举例说明

去年首期中级班结束后，我的师妹刘凌燕赴藏区义诊，接诊一个女性患者，30多岁，因其家
中至亲之人去世，悲痛欲绝，以致晕厥一日一夜，接诊时已四肢冰冷，脸色皓白，因人命关
天，师妹在七针同学微信群中求助，众同学纷纷支招相助，有言针刺百会人中者，有云十宣
放血者，然一一试之皆不效，后按黄炳群师兄建议弹拨腋下极泉，患者当即醒来！今日思之，
恰如古人所言，此患者“因悲哀动中者，竭绝而失生。”《素问·本神》，“气因于中，阳
气衰，不能渗营其经络，阳气日损，阴气独在，故手足为之寒也。”《素问·厥论》，表现
为手足冰冷！当为五脏之气已绝于内，所以取其腋下，当即醒转，可见古人诚不欺我！

== 自我感悟

其实除了战斗在临床第一线，抢救急危重症病人的医生们以外，大多数针灸医生还是极少碰
见五脏之气已绝的病人！那么老祖宗提出这段话的意义何在呢？学生以为，有以下三点：

. 第一：提醒医家准确判断患者的危重状况，以免贻误病机，伤人性命！
. 第二：对内外科疾病的区分提供依据标准，让医家能够准确识别是单纯的筋骨疾病还是复
杂的脏腑杂症！
. 第三：对内外科疾病的治疗指明了方向，并提供了详实的治疗思路！（重中之重哦，嘿嘿）

写到这里，已近尾声，此篇文章费时最久，六易其稿，也只是坐井观天、管中窥豹！不由再
次感叹内经的浩瀚如海，古人的智慧精绝，有道是人身难得，大道难闻，中土难生！作为炎
黄子孙，华夏儿女，我想说，我骄傲，我自豪！因为，只有中国才有《黄帝内经》！
