= 你中“邪”了吗
穆超
2016-3-15 02:13

*导读：*故智者之养生也，必顺四时而适寒暑，和喜怒而安居处，节阴阳而调刚柔。如是则
僻邪不至，长生久视。

人这一生难矣！与天斗，与地斗，与人斗，还要内防七情之伤，外御六淫之害！所以佛家说
人有四谛八苦，道家老子又云：吾有大患，及吾有身；及吾无身，吾有何患！那么我们的人
身最怕什么呢？在内经《灵枢·邪气脏腑病形第四》中给出了答案!人就怕中“邪”！

== 邪是什么

“五气更立，各有所先，非其位则邪，当其位则正。”《素问·五运行大论篇第六十七》

“帝曰：何谓邪乎？岐伯曰：夫物之生从于化，物之极由乎变，变化之相薄，成败之所由也。
故气有往复，用有迟速，四者之有，而化而变，风之来也。”《素问·六微旨大论篇第六十
八》

从这两段文字可以知道，所谓广义之“邪”是指不按套路来的五气，狭义之邪当指风邪！因
为《素问·生气通天论篇第三》：“风者，百病之始也。”那么邪气一般会侵害哪些地方呢？

== 邪中于阳

《灵枢·邪气脏腑病形第四》：“黄帝问于岐伯曰：邪气之中人也奈何？岐伯答曰：邪气之
中人高也。黄帝曰：高下有度乎？岐伯曰：身半以上者，邪中之也；身半已下者，湿中之也。
故曰：邪之中人也，无有常，中于阴则溜于腑，中于阳则溜于经。黄帝曰：阴之与阳也，异
名同类，上下相会，经络之相贯，如环无端。邪之中人，或中于阴，或中于阳，上下左右，
无有恒常，其故何也？岐伯曰：诸阳之会，皆在于面。中人也方乘虚时，及新用力，若饮食
汗出腠理开，而中于邪。中于面则下阳明，中于项则下太阳，中于颊则下少阳，其中于膺背
两胁亦中其经。”

这段文字的意思是指风邪一般伤人的上半身，湿邪一般伤人的下半身，当趁人虚弱或者大力
汗出腠理大开之际侵入人体，若邪气中面则伤阳明经脉，若中脖项，则伤太阳经脉，若中面
颊，则伤少阳经脉！

== 邪中于阴

《灵枢·邪气脏腑病形第四》：“黄帝曰：其中于阴奈何？岐伯答曰：中于阴者，常从臂胻
始。夫臂与胻，其阴皮薄，其肉淖泽，故俱受于风，独伤其阴。黄帝曰：此故伤其脏乎？岐
伯答曰：身之中于风也，不必动脏。故邪入于阴经，则其脏气实，邪气入而不能客，故还之
于腑。故中阳则溜于经，中阴则溜于腑。”这段话告诉我们当邪气入阴的时候，会伤及六腑！

== 邪中于脏

《灵枢·邪气脏腑病形第四》：“黄帝曰：邪之中人脏奈何？岐伯曰：愁忧恐惧则伤心。形
寒寒饮则伤肺，以其两寒相感，中外皆伤，故气逆而上行。有所堕坠，恶血留内，若有所大
怒，气上而不下，积于胁下，则伤肝。有所击仆，若醉入房，汗出当风，则伤脾。有所用力
举重，若入房过度，汗出浴水，则伤肾。黄帝曰：五脏之中风奈何？岐伯曰：阴阳俱感，邪
乃得往。黄帝曰：善哉。”

《灵枢·百病始生第六十六》：“岐伯曰：风雨寒热，不得虚邪，不能独伤人。卒然逢疾风
暴雨而不病者，盖无虚故邪不能独伤人，此必因虚邪之风，与其身形，两虚相得，乃客其形，
两实相逢，众人肉坚，其中于虚邪也，因于天时，与其身形，参以虚实，大病乃成，气有定
舍，因处为名，上下中外，分为三员。”

我们知道因为脏气实，五脏一般不会受邪气所伤，就怕内受七情所伤，外有六淫或不良习惯
所害，内外俱伤，就会导致邪气入侵五脏！

== 入侵次第

《素问·皮部论篇第五十六》：“是故百病之始生也，必先于皮毛，邪中之则腠理开，开则
入客于络脉，留而不去，传入于经，留而不去，传入于腑，廪于肠胃。邪之始入于皮也，溯
然起毫毛，开腠理；其入于络也，则络脉盛色变；其入客于经也，则感虚乃陷下，其留于筋
骨之间。寒多则筋挛骨痛；热多则筋弛骨消，肉烁月囷破,毛直而败。帝曰：夫子言皮之十
二部，其生病皆何如？岐伯曰：皮者，脉之部也，邪客于皮则腠理开，开则邪入客于络脉，
络脉满则注于经脉，经脉满则入舍于腑脏也。故皮者有分部，不与而生大病也。帝曰：善。”

《素问·缪刺论篇第六十三》：“岐伯对曰：夫邪之客于形也，必先舍于皮毛，留而不去，
入舍于孙脉，留而不去，入舍于络脉，留而不去，入舍于经脉，内连五脏，散于肠胃，阴阳
俱感，五脏乃伤，此邪之从皮毛而入，极于五脏之次也。如此则治其经焉。今邪客于皮毛，
入舍于孙络，留而不去，闭塞不通，不得入于经，流溢于大络，而生奇病也。夫邪客大络者，
左注右，右注左，上下左右与经相干，而布于四末，其气无常处，不入于经俞，命曰缪刺。”

从这两段文字可以知道邪气的入侵是有次第的，邪气——皮毛——孙络——络脉——大络——经脈——六
腑——五脏！

== 治之奈何

《灵枢·邪气脏腑病形第四》：“黄帝曰：余闻五脏六腑之气，荥输所入为合，令何道从入，
入安连过，愿闻其故。岐伯答曰：此阳脉之别入于内，属于府者也。黄帝曰：荥输与合，各
有名乎？岐伯曰：荥输治外经，合治内府。黄帝曰：治内府奈何？岐伯曰：取之于合。黄帝
曰：合各有名乎？岐伯答曰：胃合于三里，大肠合入于巨虚上廉，小肠合入于巨虚下廉，三
焦合入于委阳，膀胱合入于委中央，胆合入于阳陵泉。黄帝曰：取之奈何？岐伯答曰：取之
三里者，低跗；取之巨虚者，举足；取之委阳者，屈伸而索之；委中者，屈而取之；阳陵泉
者，正竖膝予之齐下至委阳之阳取之；取诸外经者，揄申而从之。”

“故中阳则溜于经，中阴则溜于腑。”当邪气中于阳时会传于经，因为荥输治外经，所以中
于阳我们可以取病变经络的荥穴和输穴。当邪气中于阴时会溜于腑，因为合治内府，所以中
于阴我们可以取病变内府的下合穴。

《灵枢·五邪第二十》：“邪在肺，则病皮肤痛，寒热，上气喘，汗出，咳动肩背。取之膺
中外腧，背三节五脏之傍，以手疾按之，快然，乃刺之，取之缺盆中以越之。邪在肝，则两
胁中痛，寒中，恶血在内，行善掣，节时脚肿。取之行间以引胁下，补三里以温胃中，取血
脉以散恶血，取耳间青脉，以去其掣。邪在脾胃，则病肌肉痛，阳气有余，阴气不足，则热
中善饥；阳气不足，阴气有余，则寒中肠鸣腹痛。阴阳俱有余，若俱不足，则有寒有热。皆
调于三里。邪在肾，则病骨痛阴痹。阴痹者，按之而不得，腹胀腰痛，大便难，肩背颈项痛，
时眩。取之涌泉、昆仑，视有血者尽取之。邪在心，则病心痛喜悲，时眩仆，视有余不足而
调之其输也。”

这段话详细的告诉我们当邪入五脏的时候，患者的具体表现和治疗方法，医家不可不知！

== 防邪攻略

《素问·上古天真论篇第一》：“夫上古圣人之教下也，皆谓之虚邪贼风，避之有时，恬惔
虚无，真气从之，精神内守，病安从来。”

《素问·生气通天论篇第三》：“故风者，百病之始也，清静则肉腠闭拒，虽有大风苛毒，
弗之能害，此因时之序也。”

《素问·移精变气论篇第十三》：“岐伯对曰：往古人居禽兽之间，动作以避寒，阴居以避
暑，内无眷暮之累，外无伸宦之形，此恬淡之世，邪不能深入也。”

《灵枢·本神第八》：“故智者之养生也，必顺四时而适寒暑，和喜怒而安居处，节阴阳而
调刚柔。如是则僻邪不至，长生久视。”

从以上篇章可以看出只要我们顺应四时，控制情绪，减少欲望，生活规律，做到精神内守，
恬淡虚无，就可以防止邪气入侵！各位看官，您明白了吗？

现在的时间是凌晨两点的一十三分半，愿所有的生命自由呼吸！
