= 我们能活多久
穆超
2016-4-12 18:00

include::穆超.adoc[]

*导读：*其实养生的根本就是养“心”，因为心主神明，主明则下安，以此养生则寿，主不
明则十二官危，以此养生则殃。

长生和爱情一样一直是人类永恒的话题，庄子的《逍遥游》中“藐姑射之山，有神人居焉；
肌肤若冰雪，绰约若处子；不食五谷，吸风饮露；乘云气，御飞龙，而游乎四海之外；其神
凝，使物不疵疠而年谷熟。”对仙人的描写更是让人们对长生不老有了遐想和孜孜不倦的追
求，那我们到底能活多久呢？其实内经中古人已经给出了答案！

== 请看原文

黄帝问于伯高曰：余闻形有缓急，气有盛衰，骨有大小，肉有坚脆，皮有厚薄，其以立寿夭
奈何？伯高答曰：形与气相任则寿，不相任则夭。皮与肉相果则寿，不相果则夭。血气经络
胜形则寿，不胜形则夭。

黄帝曰：何谓形之缓急？……此天之生命，所以立形定气而视寿夭者，必明乎此立形定气，
而后以临病人，决死生。

黄帝曰：余闻寿夭，无以度之。伯高答曰：墙基卑，高不及其地者，不满三十而死。其有因
加疾者，不及二十而死也。

黄帝曰：形气之相胜，以立寿夭奈何？伯高答曰：平人而气胜形者寿；病而形肉脱，气胜形
者死，形胜气者危矣。《灵枢·寿夭刚柔第六》

== 相形之术

上面这段话其实就是古人告诉我们怎么样通过一个人的外形和气血来判断一个人的寿命长短！

黄帝问伯高：怎么通过一个人的胖瘦（缓急）、气血的强弱、身高（骨的大小）、肌肉的强
弱、皮肤的厚薄来判断一个人的寿命长短呢？伯高回答：如果这个人外在的躯体形骸（形）
与内在的精气神（气）相对等的话，这个人一定会长寿。反之，如果某人形体瘦小枯干而精
力旺盛，或某人形体高大魁梧而精神萎靡，皆非长寿之兆。这是古人对人寿命长短粗略的判
断，那么下面就是详细的论述了！

伯高又说了：皮与肉相果则寿，“果”，充实、饱满之意。也就是说皮肤弹性好，肌肉饱满
的人会长寿，而“皮与肉不相果”则正好相反，是形容皮肤松弛、粗糙、肌肉不饱满的状况。
我们知道，皮肤弹性、肌肉的坚脆是反映一个人营养状况最显著的标志，而人的营养状况又
是维持其身体健康的基本条件，尤其在古代，底层民众往往食不果腹，故在当时，营养状况
是影响人们健康水平以及寿夭的又一重要因素。

伯高继续分析：血气经络胜形则寿，不胜形则夭。“血气”是指精神体力，这里的“经络”
是指我们可以肉眼可见的浅表静脉。一个精力充沛、矫健敏捷的人，其四肢的浅表静脉往往
暴露凸出于肌肉皮肤之上，这就叫“血气经络胜形”，这样的人是长寿的。反之，一个少气
懒言、体虚倦怠的人，其四肢的浅表静脉必然萎缩下陷，这就叫“血气经络不胜形”，这样
的人很容易短命！

黄帝还嫌伯高讲的不细。 又问：具体从外形上怎么判断呢？伯高不厌其烦：形充而皮肤缓
者则寿，形充而皮肤急者则夭。充：长也，高也。故“形充”是指身体发育成熟的成年人。
“缓急”者，肥瘦之意（估计长得着急就是因此而来，嘿嘿)。“皮肤缓”是指皮肤滑腻丰
满，说明营养状况良好，故寿。“皮肤急”是指皮肤紧，说明气血濡养不够，缺乏弹性，故
夭。

伯高继续解释：形充而脉坚大者顺也，形充而脉小以弱者气衰，衰则危矣。成年人脉搏坚强
有力说明心脏功能良好，往往能够长寿。相反，成年人脉搏微弱迟缓甚至间歇停顿者，说明
心脏功能弱，谓之“气衰”，是以断其“危”。

伯高越说越高兴：如果一个人颧骨不突起者肯定骨小，骨小之人精髓必不足，而肾主骨生髓，
所以骨小者先天不足，往往短寿。如果一个人肌肉饱满，纹理清晰，轮廓分明，表示其人肉
坚，故能长寿。反之肉脆则夭。作为一个医生必须要了解这些常识，通过对病人的形体和精
气神的状况来决定是否予以治疗，并且能够判断预后如何！在当今医患关系紧张的形势下，
掌握上述判定寿夭的各种条件并进行深思熟虑地分析，可以有效的规避医疗风险，对于医患
双方都是十分必要的。

黄帝又问：到底活多大岁数算“寿”？活多大岁数算“夭”呢？有什么标准吗？伯高回答：
如果一个人的鼻子矮瘪，鼻孔外露，鼻梁骨塌陷（墙基卑）就预示其人短命，很可能活不到
三十。甚至，如果再有其他的毛病很可能不及二十而死，这句话其实还有一个意思，就是说
一个人能够活到三十岁，就不能算“夭”了，只有活不到三十岁的人才算得上“夭”。

在现实生活中大多数人或多或少都存在“形与气不相任”的问题，也就是说或者气胜形，或
者形胜气。那么“气胜形者寿”，“形胜气者夭”，当然对于“形肉脱”的情况除外，“形
肉脱”是指不但全身肌肉萎缩，而且其皮下脂肪组织亦消耗殆尽，乃成皮包骨状态。一个人
若因患病而迅速消瘦以至于呈现皮包骨状态，无论形胜气还是气胜形，都已经无可救药了。

上面这些文字是古人通过外在形体和内在气血的相任与否来粗略判断一个人的健康状况，虽
然对于长短之期还不能精准预测，但是行走江湖能够自保还是足够用了！而学会下面的相面
之术才能够登上大雅之堂！

== 相面之术

帝曰：善。五色独决于明堂乎？岐伯曰：五官已辨，阙庭必张，乃立明堂，明堂广大，蕃蔽
见外，方壁高基，引垂居外，五色乃治，平搏广大，寿中百岁……岐伯曰：五官不辨，阙庭
不张，小其明堂，蕃蔽不见，又埤其墙，墙下无基，垂角去外。如是者，虽平常殆，况加疾
哉。《灵枢·五阅五使第三十七》

雷公问于黄帝曰：五色独决于明堂乎？小子未知其所谓也。黄帝曰：明堂者，鼻也；阙者，
眉间也；庭者，颜也；蕃者，颊侧也；蔽者，耳门也。其间欲方大，去之十步，皆见于外，
如是者寿，必中百岁。《灵枢·五色第四十九》黄帝曰：人之寿百岁而死，何以致之？岐伯
曰：使道隧以长，基墙高以方，通调营卫，三部三里起，骨高肉满，百岁乃得终。

黄帝曰：其不能终寿而死者，何如？岐伯曰：其五脏皆不坚，使道不长，空外以张，喘息暴
疾；又卑基墙薄，脉少血，其肉不石，数中风寒，血气虚，脉不通，真邪相攻，乱而相引，
故中寿而尽也。《灵枢·天年第五十四》

上面这几段文字告诉我们长寿的面相特点：五官端正，十步以外，清晰可辨，尤其是鼻高挺
阔，耳大肉厚，眉阔骨高，五色平和！别小瞧这短短的几行字，却是古人经验的集结，奠定
了后世面相学的基石！现在剖析开来仍然具有极大的指导意义，五官端正者心必端正，人们
常说相由心生，心存善念者五官必正，人若向善，天必佑之，福虽未至，祸已远离！鼻为明
堂，面相学中谓财帛宫，主管一生之福禄，鼻高挺阔鼻翼丰满之人必富贵满门（看看成龙的
鼻子就知道了），一生衣食无忧，想不长寿都难！眉阔之人必心胸开阔（双眉之间主心脑），
心胸豁达之人必有君子坦荡之风，知天命而不惑，能耳顺而从心所欲，所以寿延百岁！反之
中寿而尽也！

== 长寿秘诀

是以圣人为无为之事，乐恬惔之能，从欲快志于虚无之守，故寿命无穷，与天地终，此圣人
之治身也。《素问·阴阳应象大论篇第五》

故主明则下安，以此养生则寿，殁世不殆，以为天下则大昌。主不明则十二官危，使道闭塞
而不通，形乃大伤，以此养生则殃，以为天下者，其宗大危，戒之戒之。《素问·灵兰秘典
论篇第八》

岐伯对曰：上古之人，其知道者，法于阴阳，和于术数，食饮有节，起居有常，不妄作劳，
故能形与神俱，而尽终其天年，度百岁乃去……夫上古圣人之教下也，皆谓之虚邪贼风，避
之有时，恬惔虚无，真气从之，精神内守，病安从来……所以能年皆度百岁而动作不衰者，
以其德全不危也。

黄帝曰：余闻上古有真人者，提挈天地，把握阴阳，呼吸精气，独立守神，肌肉若一，故能
寿敝天地，无有终时，此其道生。

中古之时，有至人者，淳德全道，和于阴阳，调于四时，去世离俗，积精全神，游行天地之
间，视听八达之外，此盖益其寿命而强者也，亦归于真人。其次有圣人者，处天地之和，从
八风之理，适嗜欲于世俗之间，无恚嗔之心，行不欲离于世，被服章，举不欲观于俗，外不
劳形于事，内无思想之患，以恬愉为务，以自得为功，形体不敝，精神不散，亦可以百数。

其次有贤人者，法则天地，象似日月，辩列星辰，逆从阴阳，分别四时，将从上古合同于道，
亦可使益寿而有极时。《素问·上古天真论篇第一》

从上面这几段文字我们知道其实养生的根本就是养“心”，因为心主神明，主明则下安，以
此养生则寿，主不明则十二官危，以此养生则殃。只有心地善良，清心寡欲，效法圣贤，真
正做到《朱子家训》所言“读书志在圣贤，非徒科第；为官心存家国，岂计身家！”只有这
样的长生才是我们最需要的，混吃等死的久活，不要也罢！
