= 众说纷纭的人迎寸口
穆超
2016-5-10 00:00

**导读：**“通其荥输，乃可传于大数。”此处的荥输，应该指的是五输穴（井、荥、输、
经、合），而不仅仅是荥穴和输穴！因为临床中的疾病千变万化，单靠荥输两个穴位是无法
通调外经的。只有把五输穴完全弄明白了，才能实施“虚则补之，实则泻之”等原则（“大
数”）。


在《灵枢·终始第九》中有一段文字：“人迎一盛，病在足少阳，一盛而躁，病在手少阳。
人迎二盛，病在足太阳，二盛而躁，病在手太阳。人迎三盛，病在足阳明，三盛而躁，病在
手阳明。人迎四盛，且大且数，名曰溢阳，溢阳为外格。脉口一盛，病在足厥阴，厥阴一盛
而躁，在手心主。脉口二盛，病在足少阴，二盛而躁，在手少阴。脉口三盛，病在足太阴，
三盛而躁，在手太阴。脉口四盛，且大且数者，名曰溢阴，溢阴为内关，内关不通死不治。
人迎与太阴脉口俱盛四倍以上，名曰关格，关格者与之短期。”

而在其他篇章中也有类似的论述，《素问·六节藏象论篇第九》：“故人迎一盛病在少阳、
二盛病在太阳、三盛病在阳明、四盛已上为格阳。寸口一盛病在厥阴、二盛病在少阴、三盛
病在太阴、四盛已上为关阴。人迎与寸口俱盛四倍以上为关格，关格之脉赢，不能极于天地
之精气，则死矣。”

《灵枢·禁服第四十八》：“人迎大一倍于寸口，病在足少阳，一倍而躁，在手少阳。人
迎二倍，病在足太阳，二倍而躁，病在手太阳。人迎三倍，病在足阳明，三倍而躁，病
在手阳明。”

其他类似的说法在内经中不下四五处，有说“脉口”“气口”，有言“寸口”，实为异名同
处，故依常言以“寸口”代之！

== 到底在哪

人迎寸口的说法在内经中出现多次，且以大量篇幅论述，说明人迎寸口在临床中有一定的实
用价值，但是人迎寸口具体在哪？历代医家众说纷纭，比较有代表性的莫过于“左人迎，右
寸口”理论，此论出自于王叔和《脉经》中的《两手六脉所主五脏六腑阴阳逆顺第七》：
“脉法赞云：肝心出左，脾肺出右，肾与命门，俱出尺部，魂魄谷神，皆见寸口，左主司官，
右主司府，左大顺男，右大顺女。关前一分，人命之主，左为人迎，右为气口。神门决断，
两在关后，人无二脉，病死不愈。诸经损减，各随其部，察按阴阳，谁与先后，阴病治官，
阳病治府，奇邪所舍，如何捕取，审而知之，针入病愈。”此论述在临床中也有大量应用，
据说效果也不错。

== 那么在内经中是如何定位的呢？

《灵枢·本输第二》：“任脉之侧动脉足阳明也，名曰人迎。”《灵枢·寒热病第二十一》：
“颈侧之动脉人迎。人迎，足阳明也，在婴筋之前。婴筋之后，手阳明也，名曰扶突。”
“人迎”即喉结旁与胸锁乳突肌之间的颈动脉搏动处（平环状软骨的颈动脉搏动处为人
迎脉）。

== 寸口，又称气口。

《灵枢·经脉第十》：“经脉者常不可见也，其虚实也以气口知之。”《灵枢·经脉第十》
所说：“手太阴之脉……入寸口，上鱼，循鱼际”，也就是手腕内侧手太阴肺经循行所
过的脉动处。“寸口”即桡骨茎突尺侧的桡动脉搏动处。

== 倍、盛之意

《灵枢·禁服第四十八》中用的“倍”，《灵枢·终始第九》中用的是“盛”，
“倍”“盛”两个字其实是一个意思，代表人迎与寸口的力度大小！说到这里，有的人
就说了，颈动脉的搏动一定大于桡动脉啊！还用比较吗？呵呵，其实古人摸的不是脉管
的宽度而是力度，只要仔细摸一定能够知道里面的区别！

== 盛、倍的比较

到底什么是一盛，怎么样才是二盛、三盛呢？如何操作呢？以摸病人的左侧脉为例！医家左
手摸其寸口脉，右手摸人迎脉，取最强脉位的脉度来比较盛、倍！如何判断呢？一盛：人迎
与寸口能感觉出区别；三盛：人迎与寸口力度相差极大；二盛：介于一盛与三盛之间！

== 如何应用

《灵枢·终始第九》：“人迎一盛，泻足少阳而补足厥阴，二泻一补，日一取之，必切而
验之，躁取之上，气和乃止。人迎二盛，泻足太阳补足少阴，二泻一补，二日一取之，
必切而验之，躁取之上，气和乃止。人迎三盛，泻足阳明而补足太阴，二泻一补，日二
取之，必切而验之，躁取之上，气和乃止。脉口一盛，泻足厥阴而补足少阳，二补一泻，
日一取之，必切而验之，躁取之上，气和乃止。脉口二盛，泻足少阴而补足太阳，二补
一泻，二日一取之，必切而验之，躁取之上，气和乃止。脉口三盛，泻足太阴而补足阳
明，二补一泻，日二取之，必切而验之，躁取之上，气和乃止。所以日二取之者，太、
阳主胃，大富于谷气，故可日二取之也。”

*从这段经文中我们可以得出几个结论：*

. 补泻的穴位数为三个（单侧），即：阴经一个，阳经二个。
. 因为太阴、阳明“大富于谷气”，它们是多气多血之经，所以一天扎两次，厥阴、少阳一
日一次，太阳、少阴两日一次！

== 如何取穴

《灵枢·邪气脏腑病形第四》：“黄帝曰：余闻五脏六腑之气，荥输所入为合，令何道从
入，入安连过，愿闻其故。岐伯答曰：此阳脉之别入于内，属于府者也。黄帝曰：荥输
与合，各有名乎？岐伯曰：荥输治外经，合治内府。”《灵枢·寿夭刚柔第六》：“故曰，
病在阴之阴者，刺阴之荥输；病在阳之阳者，刺阳之合；病在阳之阴者，刺阴之经；病
在阴之阳者，刺络脉。”《灵枢·禁服第四十八》：“通其荥输，乃可传于大数。大数曰：
盛则徒泻之，虚则徒补之，紧则灸刺，且饮药，陷下则徒灸之，不盛不虚，以经取之。”
“通其荥输，乃可传于大数。”

此处的荥输，应该指的是五输穴（井、荥、输、经、合），而不仅仅是荥穴和输穴！因为临
床中的疾病千变万化，单靠荥输两个穴位是无法通调外经的。只有把五输穴完全弄明白了，
才能实施“虚则补之，实则泻之”等原则（“大数”），所以，调人迎寸口是通过选用适当
的五输穴来进行补泻的！

== 先后顺序

《灵枢·终始第九》：“阴盛而阳虚，先补其阳，后泻其阴而和之。阴虚而阳盛，先补其
阴，后泻其阳而和之。”

这句话告诉我们：当阴盛阳虚的时候，先补阳后泻阴；当阴虚而阳盛的时候，先补其阴后泻
阳！所以，调人迎寸口脉时的先后顺序是：先补后泻。

写到这里，其实感觉有些无味，因为在应用七针的过程当中我曾验证过病人治疗前后的脉象
变化！当你辨证准确，针具选用得当，手法精准细腻，不管是患者的自我感觉还是脉象都会
朝着好的方向变化！此篇文章当为喜欢脉法和喜读内经之同道抛砖引玉之作，不当之处还望
海涵为盼！
