= 生死之脉
穆超
2016-5-24 00:00

include::穆超.adoc[]

《灵枢·经脉第十》开篇就讲：“经脉者，所以能决死生、处百病、调虚实，不可不通。”
把经脉的重要性与人之生老病死紧密联系在一起。所谓世间之事，除了生死，其他都是小事！
由此可见经脉之重要性！不仅如此，古人害怕后人不够重视，接着在《灵枢·经别第十一》
中又一再进行补充强调：“夫十二经脉者，人之所以生，病之所以成，人之所以治，病之所
以起，学之所始，工之所止也。粗之所易，上之所难也。”所以又有了后世医家经常说的一
句话“学医不明经络，开口动手便错！”那么经脉为什么这么重要呢？在内经里面又是如何
阐述这种重要性的呢？

== 法于阴阳的经脉

黄帝曰：余闻天为阳，地为阴，日为阳，月为阴，其合之于人，奈何？岐伯曰：腰以上为天，
腰以下为地，故天为阳，地为阴，故足之十二经脉，以应十二月，月生于水，故在下者为阴；
手之十指，以应十日，日主火，故在上者为阳。……且夫阴阳者，有名而无形，故数之可十，
离之可百，散之可千，推之可万，此之谓也。《灵枢·阴阳系日月第四十一》

这段话告诉我们人身经脉之大阴阳以腰为分界，腰以上为天，为阳，合十天干，腰以下为地，
为阴，合十二地支！这种阴阳的分法就诞生了一种针刺的方法，就是按月生死为痏数的刺法！
如《素问·缪刺论篇第六十三》曰：“邪客于臂掌之间，不可得屈。刺其踝后，先以指按之
痛，乃刺之。以月死生为数，月生一日一痏，二日二痏，十五日十五痏，十六日十四痏。”
月相由朔而望、由缺到圆谓之“生”，针刺逐日增加痏数，至十五日而止；反之，从望到晦，
由圆到缺谓之“死”，应逐日减少痏数。遵循“月生无泄，月满无补，月廓空无治”之说！

== 上合于天的经脉

岐伯对曰：夫圣人之起度数，必应于天地，故天有宿度，地有经水，人有经脉。《素问·离
合真邪论篇第二十七》

黄帝曰：余愿闻五十营奈何？岐伯答曰：天周二十八宿，宿三十六分；人气行一周，千八分，
日行二十八宿。人经脉上下左右前后二十八脉，周身十六丈二尺，以应二十八宿，漏水下百
刻，以分昼夜。故人一呼脉再动，气行三寸，呼吸定息，气行六寸；十息，气行六尺，日行
二分。二百七十息，气行十六丈二尺，气行交通于中，一周于身，下水二刻，日行二十五分。
五百四十息，气行再周于身，下水四刻，日行四十分。二千七百息，气行十周于身，下水二
十刻，日行五宿二十分。一万三千五百息，气行五十营于身，水下百刻，日行二十八宿，漏
水皆尽脉终矣。所谓交通者，并行一数也。故五十营备，得尽天地之寿矣，凡行八百一十丈
也。《灵枢·五十营第十五》

从上面的文字可以知道经脉是上合于天之日月星辰！有了日月就有了太阳太阴之说，而经脉
之行又与二十八星宿之运行相辅相成！

== 下合于地的经脉

黄帝问于岐伯曰：余闻人之合于天道也，内有五脏，以应五音、五色、五时、五味、五位也；
外有六腑，以应六律。六律建阴阳诸经而合之十二月、十二辰、十二节、十二经水、十二时、
十二经脉者，此五脏六腑之所以应天道。《灵枢·经别第十一》

黄帝问于岐伯曰：经脉十二者，外合于十二经水，而内属于五脏六腑。夫十二经水者，其有
大小、深浅、广狭、远近各不同；五脏六腑之高下、小大、受谷之多少亦不等，相应奈何？
夫经水者，受水而行之；五脏者，合神气魂魄而藏之；六腑者，受谷而行之，受气而扬之；
经脉者，受血而营之。合而以治奈何？刺之深浅，灸之壮数，可得闻乎？《灵枢·经水第十
二》

从上面的文字可以知道经脉是下合于地之十二经水！因为经水有大小深浅广狭远近之不同，
才有了针刺深浅，灸之壮数，留针时间之不同！

== 和于术数的经脉

黄帝曰：愿闻脉度。岐伯答曰：手之六阳，从手至头，长五尺，五六三丈。手之六阴，从手
至胸中，三尺五寸，三六一丈八尺，五六三尺，合二丈一尺。足之六阳，从足上至头，八尺，
六八四丈八尺。足之六阴，从足至胸中，六尺五寸，六六三丈六尺，五六三尺，合三丈九尺。
蹻脉从足至目，七尺五寸，二七一丈四尺，二五一尺，合一丈五尺。督脉任脉，各四尺五寸，
二四八尺，二五一尺，合九尺。凡都合一十六丈二尺，此气之大经隧也。《灵枢·脉度第十
七》黄帝问于岐伯曰：愿闻卫气之行，出入之合，何如？岐伯曰：岁有十二月，日有十二辰，
子午为经，卯酉为纬。天周二十八宿，而一面七星，四七二十八星。房昴为纬，虚张为经。
是故房至毕为阳，昴至心为阴。阳主昼，阴主夜。故卫气之行，一日一夜五十周于身，昼日
行于阳二十五周，夜行于阴二十五周，周于五藏。《灵枢·卫气行第七十六》

这段文字告诉我们经脉的运行轨道也是和于术数的！我们来看：一十六丈二尺，1+6+2=9，
而九为天之大数！昼日行于阳二十五周，二十五是五的自身倍数，又是十以内的单数（阳数）
相得之和（1+3+5+7+9=25），故为天之常数！在针刺的技法上，也可以参照术数的理论来决
定留针的个数或者时间！如中焦为脾胃，又为中土，土为五，可以留针五支，又如也可以在
穴位上进行如下操作，胆为巽，巽为四，阳陵泉可以用四支毫针留养，等等，大家可以按先
后天八卦或者河图洛书自行发挥！

== 和于四时的经脉

黄帝曰：经脉十二者，别为五行，分为四时，何失而乱？何得而治？岐伯曰：五行有序，四
时有分，相顺则治，相逆则乱。黄帝曰：何谓相顺？岐伯曰：经脉十二者，以应十二月。十
二月者，分为四时。四时者，春秋冬夏，其气各异，营卫相随，阴阳已知，清浊不相干，如
是则顺之而治。《灵枢·五乱第三十四》

因为经脉的运行和于四时，所以在针刺的取穴上就有了侧重点，春取络脉诸荥大经分肉之间，
甚者深取之，间者浅取之。夏取诸俞孙络肌肉皮肤之上。秋取诸合，余如春法。冬取诸井诸
俞之分，欲深而留之。此四时之序，气之所处，病之所舍，脏之所宜。

*综上所述，人身之经脉皆法于阴阳、和于术数、法天则地、和于四时，只能相顺而治，相
逆则乱矣！*
