= 是动病与所生病
穆超
2016-6-7 00:00

《灵枢·经脉第十》是《灵枢经》最重要的篇章之一，说其重要，一是指在临床上有重要指
导意义，另一方面关于“是动病”与“所生病”的分歧也让这篇文章备受关注！

== 主要观点

“是动病”、“所生病”，是《灵枢·经脉第十》在叙述完每条经脉的循行起止后，关于疾
病的症候记载。历代医家对其有不同见解，主要观点如下。

第一，气血先后说。《难经·二十二难》云：“经言是动者，气也；所生病者，血也。邪在
气，气为是动；邪在血，血为所生病。气主煦之，血主濡之。气留而不行者，为气先病也；
血壅而不濡者，为血后病也。故先为是动，后所生病也。”即每一条经脉都分为气病和血病，
气病在先，血病在后；新病在气，久病在血。可知，“是动病”是气分病，“所生病”为血
分病。

第二，经络脏腑说。《校注十四经发挥》认为：“是动病”为经络病，“所生病”为脏腑病。
王冰也直接将“是动”解释为“脉动”，表示此经脉异常变动，则可以在本经循行所过之处
出现相应病症。因为“是动”病直接来源于脉诊病候，只言“动”而不言具体脉象，后人多
将“是动病”直接解释为经络病。相对而言，“所生病”则为脏腑病。

第三，内因外因说。《灵枢集注》云：“夫是动者，病因于外；所生者，病因于内。”即经
脉因受外邪侵犯所发生的病证称“是动病”，本脏腑发生疾病影响到本经的称“所生病”。

第四，本经他经说。《难经经释》云：“《经脉》篇是动诸病，乃本经之病；所生之病，则
以类推而旁及他经者。”即本经之病称“是动病”，影响至他经之病称“所生病”。

第五，穴动诊病说。《灵枢注证发微》认为“此篇‘是动’之义，正言各经之穴动则知其病
耳”，即根据各经腧穴的脉动变化诊断疾病及预后。“主×所生病者”是对“是动”后所列
病症的结语，表示经脉病涉及的内容。而“主×所生病者”之后所列病症，“或出本经，或
由合经”，是对该经病补充的另一组病症。

以上几种观点，从不同角度解释了“是动病”、“所生病”的含义，均有一定的理论价值。
那么“是动病”、“所生病”到底分别代表什么呢？我们还是从内经原文中找寻答案吧！

== 追根溯源

在《灵枢·经脉第十》篇章的中间有一句话：“脉之卒然动者，皆邪气居之，留于本末；不
动则热，不坚则陷且空，不与众同，是以知其何脉之动也。”

从这句话我们知道：经脉受邪从而卒然而动，除了经脉本身会有温度的变化或者脉管变得细
软甚至陷下而空之外，还会引起一系列的症状！也就是说“是动则病”指的是经脉本身受邪
所导致的疾病或者临床症状！

咱们再看“主×所生病者”这几个字，第一个“主”字非常关键，考“主”有主持、掌管之
义，在医书中常引申为“主治”的意思。如《灵枢·九针论第七十八》有：“一曰镵针
者，……主热在头身也。二曰员针，……主治分间气。三曰鍉针，……主按脉取气，令邪出。
四曰锋针，……主痈热出血。”“主”即“主治”之义。《阴阳十一脉灸经》也有“是……
脉主治其所产病”的记载，可以作为这一训释的佐证。因此，将“是主……所生病者”理解
为“此经脉主治某脏（或津、血等）所产生的病证”，是文通理顺的。所以，把“是动病”
释为该经发生异常变动所产生的病证，视“所生病”为该经脉腧穴所能主治的病证，可以是
本经之病，亦可以旁及他经，病证范围较“是动病”广，病候间不一定有病理上的联系。

== 临床意义

对于“是动病”、“所生病”，有什么不同的调理方法吗？我们再看原文“雷公曰：何以知
经脉之与络脉异也？黄帝曰：经脉者常不可见也，其虚实也以气口知之。脉之见者皆络脉也。
雷公曰：细子无以明其然也。黄帝曰：诸络脉皆不能经大节之间，必行绝道而出入，复合于
皮中，其会皆见于外。故诸刺络脉者，必刺其结上，甚血者虽无结，急取之以泻其邪而出其
血；留之发为痹也。”

这段话告诉我们经脉本身有了问题（是动病），我们可以采用刺血（络）的方法，也就是刺
营！

比如“肺手太阴之脉，……是动则病肺胀满，膨膨而喘咳，缺盆中痛，甚则交两手而瞀，此
为臂厥。”《灵枢·经脉第十》“肺热病者，……热争则喘咳，痛走胸膺背，不得大息，头
痛不堪，……刺手太阴阳明，出血如大豆，立已。”《素问·刺热篇第三十二》再如“膀胱
足太阳之脉，……是动则病冲头痛，目似脱，项如拔，脊痛，腰似折，髀不可以曲，腘如结，
踹（腨）如裂，是为踝厥。”《灵枢·经脉第十》“风痉身反折，先取足太阳及腘中及血络
出血。”《灵枢·热病第二十三》

那么对于“所生病”，在《灵枢·终始第九》中写到“凡刺之道，气调而止，……必先通十
二经脉之所生病。而后可得传于终始矣。”也就明确告诉我们对于十二经脉之“所生病”宜
用调气的方法，也就是通过调理卫气的方法才能有效的对症治疗。

其实不管是“是动病”还是“所生病”，我们在治疗时都要遵循内经的大原则，那就是“盛
则泻之，虚则补之，热则疾之，寒则留之，陷下则灸之，不盛不虚，以经取之”，疗效的大
小还是取决于医家对于患者疾病的正确判断和把控。
