= 沟通阴阳的络脉
穆超
2016-6-21 00:00

include::穆超.adoc[]

**导读：**十二别络就是联络阴阳、沟通表里的使者，他的提出也处处体现了阴阳分之为二、
合二为一的大道准则！
 
== 请看原文

* 手太阴之别，名曰列缺，起于腕上分间，并太阴之经直入掌中，散入于鱼际。其病实则手
锐掌热，虚则欠㰦，小便遗数，取之去腕半寸，别走阳明也。
* 手少阴之别，名曰通里，去腕一寸半，别而上行，循经入于心中，系舌本，属目系。其实
则支膈，虚则不能言，取之掌后一寸，别走太阳也。
* 手心主之别，名曰内关，去腕二寸，出于两筋之间，循经以上系于心，包络心系。实则心
痛，虚则为头强，取之两筋间也。
* 手太阳之别，名曰支正，上腕五寸，内注少阴；其别者，上走肘，络肩髃。实则节弛肘废，
虚则生肬，小者如指痂疥，取之所别也。
* 手阳明之别，名曰偏历，去腕三寸，别入太阴；其别者，上循臂，乘肩髃，上曲颊偏齿；
其别者，入耳合于宗脉。实则龋聋，虚则齿寒痹隔，取之所别也。
* 手少阳之别，名曰外关，去腕二寸，外绕臂，注胸中，合心主。病实则肘挛，虚则不收，
取之所别也。
* 足太阳之别，名曰飞扬，去踝七寸，别走少阴。实则鼽窒头背痛，虚则鼽衄，取之所别也。
* 足少阳之别，名曰光明，去踝五寸，别走厥阴，下络足跗。实则厥，虚则痿躄，坐不能起，
取之所别也。
* 足阳明之别，名曰丰隆，去踝八寸，别走太阴；其别者，循胫骨外廉，上络头项，合诸经
之气，下络喉嗌。其病气逆则喉痹瘁瘖，实则狂巅，虚则足不收胫枯，取之所别也。
* 足太阴之别，名曰公孙，去本节之后一寸，别走阳明；其别者，入络肠胃。厥气上逆则霍
乱，实则肠中切痛，虚则鼓胀，取之所别也。
* 足少阴之别，名曰大钟，当踝后绕跟，别走太阳；其别者，并经上走于心包，下外贯腰脊。
其病气逆则烦闷，实则闭癃，虚则腰痛，取之所别者也。
* 足厥阴之别，名曰蠡沟，去内踝五寸，别走少阳；其别者，径胫上睾，结于茎。其病气逆
则睾肿卒疝，实则挺长，虚则暴痒，取之所别也。
* 任脉之别，名曰尾翳，下鸠尾，散于腹。实则腹皮痛，虚则痒搔，取之所别也。
* 督脉之别，名曰长强，挟膂上项，散头上，下当肩胛左右，别走太阳，入贯膂。实则脊强，
虚则头重，高摇之，挟脊之有过者，取之所别也。
* 脾之大络，名曰大包，出渊腋下三寸，布胸胁。实则身尽痛，虚则百节尽皆纵，此脉若罗
络之血者，皆取之脾之大络脉也。

凡此十五络者，实则必见，虚则必下，视之不见，求之上下。人经不同，
络脉亦所别也。

== 小结一下

十二络脉皆从十二正经分别而出，分别之处，即为络穴，络穴均位于四肢的腕踝关节附近。
络脉走行有两个方向：

. 一是横向走行。十二正经上下纵行，表里经脉分布于四肢内外相对应的部位，阴经在内，
阳经在外，所以络脉横向直行即可进入互为表里的经脉，据此能加强表里两经在肢端上的联
系，所谓“支而横者为络”（《灵枢·脉度》）。
. 二是沿经而行。络脉在络穴再分出一条支络，与正经并行。如手太阴之络“起于腕上分间，
并太阴之经直入掌中，散入于鱼际。”手太阳之络“其别者，上走肘，络肩髃”。十二络脉
皆有两条别行之络，故又称十二别络。

== 临床意义

从古人对别络的记载上看，别络的循行与其主病是一致的。如手厥阴之络“循经以上系于心
包络心系”，能够治疗“实则心痛，虚则为头强”之症；足阳明之络“其别者，循胫骨外廉，
上络头项，合诸经之气，下络喉嗌”，能治“喉痹瘁瘖，实则狂巅，虚则足不收胫枯”等症。

另一方面，别络直走相表里的经脉，称为“一络通两经”，即络穴能够治疗表里两经的疾病，
如手太阴络穴列缺，既能治疗肺经的咳嗽气喘，又能治疗与之相表里经脉的疾病，如手阳明
经所循行之处的头痛、项强等症状！所以别络“一出一入”，入于内者表里相连，出于外者
沿经而行。其沿经而行者，“并行而不同路”；表里相连者，“交会而各代理”！

由此可见，十二别络就是联络阴阳、沟通表里的使者，他的提出也处处体现了阴阳分之为二、
合二为一的大道准则！

== 临床感悟

络脉及络穴的提出在临床中为我们指明了思考的方向，但只是一个方向或者思路而已。病情
的多变和复杂也不是单靠一招半式就能全部搞定的，如一个皮肤瘙痒的患者，如果我们非常
清晰的知道络穴的临床意义，我们可以根据患者痒的部位来选择合适的治疗方法，比如正好
是肝经所过，又是外阴瘙痒，我们就可以根据“足厥阴之别，名曰蠡沟，去内踝五寸，别走
少阳；其别者，径胫上睾，结于茎。其病气逆则睾肿卒疝。实则挺长，虚则暴痒”这段经文，
取之所别（蠡沟）也。很可能就解决大部分的问题。

但是仅仅这样就足够了吗？我想有的可以，但是更多的是解决不彻底，那怎么办呢？“诸痛
痒疮皆属于心”，“痒者，阳也”等等类似的条文如果能及时跳入你的脑海，我想对于疾病
的彻底扫尾是不是多了一些助力呢？内经各个篇章无处不是散落的珍珠，如果我们都能通读
并且很好的把与之相关的珍珠串在一起，我想对于疾病乃至整个生命的把控应该更有意义！

路漫漫其修远乎，一起加油吧!
