= 经别——不一样的正经
穆超
2016-7-5 00:00

include::穆超.adoc[]

**导读：**十二经别的循行特点，可用“离、合、出、入”来概括。每一对相为表里的经别
 组成一“合”，十二经别共组成“六合”。

== 请看原文

* 足太阳之正，别入于腘中，其一道下尻五寸，别入于肛，属于膀胱，散之肾，循膂当心入
散；直者，从膂上出于项，复属于太阳，此为一经也。
* 足少阴之正，至腘中，别走太阳而合，上至肾，当十四椎，出属带脉；直者，系舌本，复
出于项，合于太阳，此为一合。成以诸阴之别，皆为正也。
* 足少阳之正，绕髀入毛际，合于厥阴；别者，入季胁之间，循胸里属胆，散之上肝贯心，
以上挟咽，出颐颔中，散于面，系目系，合少阳于外眦也。
* 足厥阴之正，别跗上，上至毛际，合于少阳，与别俱行，此为二合也。
* 足阳明之正，上至髀，入于腹里，属胃，散之脾，上通于心，上循咽出于口，上頞䪼，还
系目系，合于阳明也。
* 足太阴之正，上至髀，合于阳明，与别俱行，上结于咽，贯舌中，此为三合也。
* 手太阳之正，指地，别于肩解，入腋走心，系小肠也。
* 手少阴之正，别入于渊腋两筋之间，属于心，上走喉咙，出于面，合目内眦，此为四合也。
* 手少阳之正，指天，别于巅，入缺盆，下走三焦，散于胸中也。
* 手心主之正，别下渊腋三寸，入胸中，别属三焦，出循喉咙，出耳后，合少阳完骨之下，
此为五合也。
* 手阳明之正，从手循膺乳，别于肩髃，入柱骨下，走大肠，属于肺，上循喉咙，出缺盆，
合于阳明也。
* 手太阴之正，别入渊腋少阴之前，入走肺，散之太阳，上出缺盆，循喉咙，复合阳明，此
六合也。

== 小结一下

经别，就是别行的正经。十二经别的循行，都是从十二经脉的四肢部分（多为肘、膝以上）
别出（称为“离”），走入体腔脏腑深部（称为“入”），然后浅出体表（称为“出”）而
上头面，阴经的经别合入阳经的经别而分别注入六阳经脉(称为“合”)。

所以，十二经别的循行特点，可用“离、合、出、入”来概括。每一对相为表里的经别组成
一“合”，十二经别共组成“六合”。

十二经别不仅加强了十二经脉的内外联系，更加强了经脉所属络的脏腑在体腔深部的联系，
补充了十二经脉在体内外循行的不足，扩大了经穴的主治范围。

**例如：**十二经别通过表里相合的六合作用，使得十二经脉中的阴经与头部发生了联系，
从而扩大了手足三阴经穴位的主治范围。手足三阴经穴位之所以能主治头面和五官疾病，与
阴经经别合于阳经而上头面的循行是分不开的。

== 临床意义

首先要知道经别是在别流注的正经，不是络脉，是正经的脉。也就是说经别和十二经脉有同
等的资格、权利、功能。经别主体是在脏腑、头、手足，使其相互联系活动。脏腑中也有经
别相合相助的关系。可以认为比起经脉奇经，经别对脏腑有直接作用。

经别主要流注径路在脏腑没有穴位的地方。当然经脉的经穴也有和脏腑的关联。从直接影响
的角度来看，经别更加大。在躯干以外，十二经脉的作用范围和经别非常不同。比如经脉的
阴经不到脸部，到颈部。经别六阴到脸面、颈项，再和六阳经别汇合到经脉的阳经。也就是
六阳的经脉在脸上得到六阴经别的气血。

**举例：**手厥阴心包经不到喉咙，用这个经的大陵、间使可以治疗喉咙，因为这经经别经
过喉咙。

== 临床感悟

经别到底在临床中如何运用呢？

我们其实只需关注经别“离、合、出、入”的部位就可以了。在这四个部位的针刺都可以起
到沟通内外、表里同调、平衡阴阳的作用！

还有一个更有意思的现象就是所有的经别都和心息息相关，这也体现了古人“心为君主之
官”、天人合一的思想！

十二经别分出之于下，合之于上，则为上下相合；表里两经有分有合，则为表里相合；阴经
阳经分而后合，则为阴阳相合！这些都表明十二经别的“六合”结构是一切生理活动的基础。
在此基础之上，六腑化谷，五脏藏精，经脉“行血气而营阴阳”，各种生理功能才能得以实
现。

如果经别“离、合、出、入”的功能丧失，面临的将是生命的解体和终结！也正因为如此，
古人才在《灵枢·经别》的开篇指出“夫十二经脉者，人之所以生，病之所以成，人之所以
治，病之所以起，学之所始，工之所止也，粗之所易，上之所难也。”如此重要的十二经脉
恰恰都是建立在十二经别的“六合”结构之上，十二经别的重要性不言而喻！
