= 内经与西游记
穆超
2016-7-19 00:00

include::穆超.adoc[]

看到这个标题你是不是有很强的好奇心？黄帝内经与西游记有什么关系呢？如果你能继续看
下来，这说明我的目的就达到了！嘿嘿，这就是所谓的标题党吧！看官不要着急，且听我慢
慢道来！

== 请看原文

黄帝曰：余愿闻五十营奈何？岐伯答曰：天周二十八宿，宿三十六分，人气行一周，千八分。
日行二十八宿，人经脉上下、左右、前后二十八脉，周身十六丈二尺，以应二十八宿，漏水
下百刻，以分昼夜。故人一呼，脉再动，气行三寸，一吸，脉亦再动，气行三寸，呼吸定息，
气行六寸。十息气行六尺，日行二分。二百七十息，气行十六丈二尺，气行交通于中，一周
于身，下水二刻，日行二十五分。五百四十息，气行再周于身，下水四刻，日行四十分。二
千七百息，气行十周于身，下水二十刻，日行五宿二十分。一万三千五百息，气行五十营于
身，水下百刻，日行二十八宿，漏水皆尽，脉终矣。所谓交通者，并行一数也，故五十营备，
得尽天地之寿矣，凡行八百一十丈也。《灵枢·五十营第十五》

== 三五之道

前面咱们提到古人对于术数的应用是非常推崇的，在古人的眼里，数字并非仅仅体现具体事
物的抽象那样简单。在他们看来，数中有术，数字背后隐藏了事物运动的规律和宇宙本体的
秘密！

而“三”和“五”就是术数的基数，三五结合被称为“三五之道”。《史记·天官书》曰：
“为天数者，必通三五。”

在《道德经》中老子又明确指出“道生一，一生二，二生三，三生万物。”“三”被认为是
万物化生的基始，而三之倍数六、九、十二、二十四等均被视为三的衍生和发展。六、九不
仅由三生成，而且六乃阴数，九乃阳数，因而六与九的倍数，六六三十六、九九八十一，都
被赋予了特殊的意义！

其实不仅“三”之数意义强大，对于“五”古人更是推崇！在《周易·系辞上》：“天数五，
地数五，五位相得而各有合。天数二十有五，地数三十，凡天地之数，五十有五，此所以成
变化而行鬼神也。”

五以及五的倍数更是常见于内经的很多篇章！如五脏、五色、五音、五官、五体、五志、五
乱，其倍数则有二十五阳、二十五变、二十五穴、二十五腧、阴阳二十五人、五十营、三百
六十五节等等！

看到这里，如果你的脑海里瞬间出现这么几个场景，那么恭喜你，你真的被我的标题引诱了！
比如《西游记》中唐僧有三个徒弟，加上白龙马他们一行五个人（当然有三个确切的讲不算
是人，嘿嘿），孙悟空的三根救命毫毛，猪八戒的三十六变，取经路上的九九八十一难！

画面再转，言归正传，三又指日、月、星这三个显著的天体，五又指金、木、水、火、土这
五个最明亮的星辰。古人认为“三五”之内包含了宇宙时空的至数，极具神秘性！而《灵枢·五
十营》这篇文章则把“三五之道”体现的淋漓尽致！

== 解说如下

“天周”指的是太阳经二十八宿环绕天体一周，这一周的长度为一千零八分。有人说了，这
也没有三和五啊？别着急，一除就有了，１００８÷２８＝３６，三十六是六六相乘之积。
咱们再看，二十八脉是周身一十六丈二尺，１６２÷２＝８１，八十一是九九相乘之积！

这两组数字相除之后为六六九九之数，到底有什么意义呢？其实在《素问·六节藏象论》里
我们可以找到答案：

“余闻天以六六之节，以成一岁，人以九九制会，计人亦有三百六十五节以为天地，久
矣。”

“人一呼，脉再动，气行三寸，一吸，脉亦再动，气行三寸，呼吸定息，气行六寸，十息，
气行六尺。”这也是“六六之节”。

一天之中，生命之气“一万三千五百息”“凡行八百一十丈”，这就是“九九制会”，而九
为最大的阳数，九九则为极数，所以“得尽天地之寿矣”。

== 戏说西游

古人对于术数的推崇和天人合一的思想其实随处可见，在四大名著《西游记》开篇第一回就
写到：

“那座山，正当顶上，有一块仙石。其石有三丈六尺五寸高，有二丈四尺围圆。三丈六
尺五寸高，按周天三百六十五度；二丈四尺围圆，按政历二十四气。上有九窍八孔，按九宫
八卦。”

除了天人合一的术数层面，在西游记里每个数字都有其很深的含义，比如唐僧的三个徒弟分
别代表佛家三毒“贪嗔痴”，他们五个人则分别代表佛家五毒“贪嗔痴慢疑”，猪八戒对财
色名食睡的“贪”、孙悟空对不顺他意动则拳棒相加的“嗔”，沙和尚的“痴”、小白龙的
傲“慢”、唐僧对悟空三打白骨精的“疑”，还有悟空的金箍棒重“一万三千五百斤”其实
就是指我们的呼吸一昼夜“一万三千五百息”！因为只有呼吸才能可长可短，能大能小，当
然还有另一层含义，就是指男人的生殖器，此义按下不表，而肾主纳气，开窍于耳，所以金
箍棒可藏于耳中！

所以不管《西游记》还是《黄帝内经》，都是古人对于后人修身修心的一个提醒和嘱托！

== 临床意义

当有人问我这期解读灵枢的哪一章节的时候，我说《灵枢·五十营》！他很着急，他说这篇
文章就是一些数字，就你的数学功底还是体育老师教的，对临床作用不大！是的，对于五十
营的意义只在《灵枢·根结第五》中有过概述：

“一日一夜五十营，以营五脏之精，不应数者，名曰狂生。所谓五十营者，五脏皆受气，持
其脉口，数其至也，五十动而不一代者，五脏皆受气；四十动一代者，一脏无气；三十动一
代者，二脏无气；二十动一代者，三脏无气；十动一代者，四脏无气；不满十动一代者，五
脏无气，予之短期，要在终始。所谓五十动而不一代者，以为常也，以知五脏之期。予之短
期者，乍数乍踈也。”

这段文字提示我们可以用五十营的理论用脉法来判断一个人脏腑的盛衰！那么，这篇文章的
意义仅限于此吗？是不是就像术数一样，在数字的背后隐藏高深的道理呢？其实看这篇文章
的时候很多人疑问重重，比如为什么是二十八脉？十二经脉加上奇经八脉远远超过二十八条
啊，其实古人这种削足适履的做法实在是用心良苦，为的就是让后人明白“天人合一”的道
理和“法天则地”的准则。我想这就是古人写这篇文章真正的意义吧！
