= 营气与经脉
穆超
2016-8-2 00:00

include::穆超.adoc[]

**导读：**这两种运行体系的不同既不互相矛盾又相互补充，既有古人对天地万物的敬畏，
又有古人对自身小天地的尊重和认可！我把这两种运行体系分成先天后天，营气经脉遵循
“天人合一、道法自然”的理论为先天体系，而一源三歧、标本根结、五输穴向心性运行遵
循“心为君主、以人为本”的理论为后天体系!

== 请看原文

黄帝曰：营气之道，内谷为宝。谷入于胃，乃传之肺，流溢于中，布散于外，精专者行于经
隧，常营无已，终而复始，是谓天地之纪。故气从太阴出，注手阳明，上行注足阳明，下行
至跗上，注大指间，与太阴合，上行抵髀。从脾注心中，循手少阴出腋下臂，注小指，合手
太阳，上行乘腋出䪼内，注目内眦，上巅下项，合足太阳，循脊下尻，下行注小指之端，循
足心注足少阴，上行注肾，从肾注心，外散于胸中。循心主脉出腋下臂，出两筋之间，入掌
中，出中指之端，还注小指次指之端，合手少阳，上行注膻中，散于三焦，从三焦注胆，出
胁注足少阳，下行至跗上，复从跗注大指间，合足厥阴，上行至肝，从肝上注肺，上循喉咙，
入颃颡之窍，究于畜门。其支别者，上额循巅下项中，循脊入骶，是督脉也，络阴器，上过
毛中，入脐中，上循腹里，入缺盆，下注肺中，复出太阴。此营气之所行也，逆顺之常也。
《灵枢·营气第十六》

== 为何为营

这篇文章写的是营气的运行路线及规律！为什么叫营气呢？本人认为有二层含义：

. 第一，围绕、环绕之义。因为本文开篇就讲“常营无已，终而复始”！所以一个“营”字
就清晰的表达出了营气的运行规律就是回环往复，生命不止，运行不息！另一方面也更加说
明古人用字之精准！

. 第二，营养、管理之义。在《灵枢·邪客第七十一》中说到：“营气者，泌其津液，注之
于脉，化以为血，以荣四末，内注五脏六腑，以应刻数焉。”所以营气对内负责五脏六腑、
对外负责四肢百骸的营养吃饭问题，责任非常之重大！
+
从这句话中我们还可以知道血液为营气所化，而脉为血之府，因行于经脉之中而被称为经气，
又因其回环流注“以荣四末”而被称为营气！

== 营气与经脉

将本篇的营气循行与《灵枢·经脉第十》所载的十二经脉进行对照，可以发现，两者在线路、
走向上差不多完全相同。据此可知，营气与经脉之气应该属于同一生理现象。营气注入十二
经脉之中，以阴升阳降、阴阳相贯的规律运行，与天地阴阳形成了同构的关系，所以称之
“常营无已，终而复始，是谓天地之纪。”纪，纲纪、纲领。《素问·阴阳应象大论》云：
“阴阳者，天地之道也，万物之纲纪。”“天地之纪”就是天地阴阳的运动规律。

本篇营气循行与《灵枢·经脉第十》的对照中其实还有一些小小的不同，那就是本篇的营气
循行多了一段任督二脉的循行：“其支别者，上额循巅下项中，循脊入骶，是督脉也，络阴
器，上过毛中，入脐中，上循腹里，入缺盆，下注肺中，复出太阴。”也就是说《灵枢·营
气第十六》将任督二脉纳入其中，构成了有别于《灵枢·经脉第十》的十四经脉循环体系。
在本篇中，督脉属阳从头下行，任脉属阴从毛际上行，呈现阴升阳降之势，从而与十二经脉
的走向一致，并且与天地阴阳“地气上为云，天气下为雨”的升降之势相符！

值得大家注意的是，这里督脉的起止和走向与《素问·骨空论》“督脉者，起于少腹以下骨
中央”所载之方向正好相反！《素问·骨空论》中督脉的走向与五输穴“所出为井，所溜为
荥，所注为输，所行为经，所入为合”在走向上极为相似（呈向心性排列），并且与《灵枢·根
结第五》的根结和根、溜、注、入在经气循行的方向相符合，还有《灵枢·卫气行》标本气
街的循行也是呈向心性排列！

为什么同一本内经会出现两种不同的运行体系呢？这两种体系的理论依据和意义何在？

== 意义何在

通过跟随陈立新师父学习和临床，结合自己的感悟，本人认为营气经脉的运行遵循阴升阳降、
阴阳相贯的升降之势取决于古人对于“天人合一”大道理论的尊崇！而冲任督“一源三歧”、
五输穴和标本根结等均呈向心性运行源于古人对生命的尊重和对“心为一身之主宰”这一理
论的认可！

大家都知道，中医与道家密不可分，也有人认为古中医是道家的一个分支，那么《道德经》
认为“道大，天大，地大，人亦大。域中有四大，而人居其一焉。人法地，地法天，天法道，
道法自然。”到了庄子的《逍遥游》“乘天地之正，而御六气之变，以游无穷者”更是表达
了古人对生命的尊重和对自由的向往，并且提出“性命双修、白日飞升”的大胆理想，在
《神仙传》《黄庭经》等道家书籍里可见一斑！

所以说这两种运行体系的不同既不互相矛盾又相互补充，既有古人对天地万物的敬畏，又有
古人对自身小天地的尊重和认可！我把这两种运行体系分成先天后天，营气经脉遵循“天人
合一、道法自然”的理论为先天体系，而一源三歧、标本根结、五输穴向心性运行遵循“心
为君主、以人为本”的理论为后天体系！

群经之首《易经》认为先天为体、后天为用。所以在临床中我们常用五输穴、标本根结气街
理论而屡出奇效！
