= 人体造血的机制二

http://blog.sina.com.cn/s/blog_727392820102x03p.html[原文地址]

现代研究表明在我们的血液中有制造红血球、白血球、血小板等各类血细胞的“造血干细
胞”，造血干细胞（hemapoietic stem cell, HSC）是存在于造血组织中的一群原始造血细
胞，它不是组织固定细胞，可存在于造血组织及血液中。造血干细胞在人胚胎2周时可出现
于卵黄囊，妊娠5个月后，骨髓开始造血，出生后骨髓成为干细胞的主要来源，在造血组织
中所占比例甚少。现代医学中，造血干细胞在骨髓移植和疾病治疗方面有重要作用。1988年
法国的Gluckman教授在国际上率先成功采用脐血造血干细胞移植，救治了一名贫血患儿，标
志着脐带血造血干细胞移植时代的开启。

造血干细胞的来源主要包括骨髓、外周血和脐带血。如今，“骨髓移植”已渐渐被“外周血
造血干细胞移植”代替。也就是说，现在捐赠骨髓已不再抽取骨髓，而只是“献血”了。
脐带血是胎儿娩出断脐后残留在脐带和胎盘中的血液，富含造血干细胞，可用于治疗急、慢
性白血病和某些恶性肿瘤等多种重大疾病。

造血干细胞具备终身无限增殖的能力，长期存活的造血干细胞（HSC）能够分化为所有类型
的血细胞：白细胞、红细胞和血小板。几十亿个循环流通的血细胞并不会在体内长期地存活，
因而必须得到持续补充。当这没有发生时，贫血、流血或危及生命的感染等严重性血液疾病
就会发生。HSC的一种特殊的性质是它们也能够“自我更新”形成更多的HSC。这种性质允许
仅几千个HSC产生一个人一生当中所需的所有血细胞。 科学家们长期以来希望找到一种方法
让身体产生健康的HSC以便治愈这些血液疾病。但是在此之前，还没有人做到这一点，这部
分是因为科学家们不能够设计出一种培育环境。仅在这种环境中，干细胞才能够转化为新的
可长期存活的细胞。

**这种造血的环境存在于中医认为的“络脉”之中，在营卫的“毛脉合精”作用下，络脉中
产生了血液，然后这些血液在毛细血管中会依照经脉的路径汇入五脏六腑**。

虽然现代科学目前还只是在探索造血的机制，但是最新的一些研究成果能够帮助我们更好得
理解古圣论述的伟大：

在2017年5月17日在线发表在Nature期刊上，论文标题为“Conversion of adult
endothelium to immunocompetent haematopoietic stem cells”的一项新的研究中，来自
美国威尔康奈尔医学院的研究人员开发出一种创新性方法：利用容易获得的__血管内皮细胞无
限制地供应健康的血细胞__。

几乎同时，St. Jude儿童研究医院的研究人员使用视频监控工具发现了促进血细胞发育的细
胞。这项发现为在实验室创造造血干细胞提供了线索，最终可能有助于改善骨髓移植现状。
“这项研究可能为干细胞生物学和血液发育学研究提供了新途径，也为实验室骨髓干细胞移
植提供了线索。”St. Jude儿童研究医院血液科助理研究员、论文通讯作者Wilson
Clements博士说道。这项研究于近日发表在Nature Cell Biology上。通过使用延时视频，
研究人员追踪到了透明的斑马鱼胚胎中神经嵴细胞的迁移。斑马鱼和人类具有几乎一样的血
液系统以及使血液系统发育的信号通路。受精20小时后，神经嵴细胞到达了发育中的动脉中，
24小时后迁移的细胞与__动脉中的内皮细胞接触__，然后__启动内皮细胞的基因__（如
runx1）指示它们转化为造血干细胞。

2017年8月16日在线发表在Nature期刊上，论文标题为“Polylox barcoding reveals
haematopoietic stem cell fates realized in vivo”的研究表明造血干细胞有两个大的
发育分枝：在一个分枝中，免疫系统的T细胞和B细胞产生（T细胞不产生抗体,而是直接起作
用.所以T细胞的免疫作用叫作“细胞免疫”.B细胞是通过产生抗体起作用.抗体存在于体液
里,所以B细胞的免疫作用叫作“体液免疫”）；在另一个分枝中，红细胞和多种其他的白细
胞如粒细胞和单核细胞会形成。

相关研究结果印证了内经论述，谷气精华（营卫）从手太阴肺出，然后进入络脉借助借助物
质原料合作“生成”两类细胞：

* 免疫系统的T细胞和B细胞具有中医论述的“卫气”的功能，它是在“卫气”的气机作用下
生成的，遗传了卫气的特性：彪悍，常行脉外。
* 而红细胞和多种其他的白细胞是组成血液的重要成分，它精专而行于经隧之中，是在“营
气”的气机作用下生成的。

它们内注于五脏六腑之中，外布四肢皮肤分肉。营卫这种造化生成就是内难论述的“人受气
于谷，谷入于胃，以传于肺，五脏六腑皆以受气（包含营卫），其清者为营（“诸阴皆清”，
营血注五脏，故而为清）浊者为卫（“诸阳皆浊”卫气注六腑，故而为浊），营行脉中，卫
行脉外”。

**这个过程被古圣以阴阳五行的术数语言描述出来，这就是子午流注。因此“黄帝问于岐伯
曰∶余闻刺法对夫子，夫子之所言，不离于营卫血气。”可以说不懂得子午流注的人，是不
能读懂内难论述的，不懂得气血生成运转机制的人，是不能成为合格医生的**。
