= 经脉的物质形态

http://blog.sina.com.cn/s/blog_727392820102wzug.html[原文地址]

关于经络实质的研究已有很长时间，各种假说也很多，但至今仍无一种能令大多数科学家都
认可的观点与理论．大量的实验证实循经感传和循经小分子物质迁移的速度在几毫米到几厘
米每秒或几厘米到几十厘米每分之间，而人体神经纤维的传导速度一般为数米至百余米每秒，
血管内血液循环的速度也是几十厘米每秒，而体液的信息传导速度是以小时与天数计的，所
以从经络的传导的速度来看它不是简单的神经传导，也不是动静脉中血液循环或淋巴系统中
的淋巴液循环．从经络的功能来看，它又是外联肢节内属脏腑遍布全身的，因此它应该是已
知生理结构中的未知功能，是基于人体的物质层面表现出来的而不是什么虚无缥缈之类，但
是由于现代西医观察人体的思路局限，无法将现有的人体组织结构按照中医角度去分类组合，
因此对于经脉视而不见也就不奇怪了。

那么经脉到底是什么？《十二经水》“黄帝问于岐伯曰：经脉十二者，外合于十二经水，而
内属于五脏六腑。夫十二经水者，其有大小、深浅、广狭、远近各不同；五脏六腑之高下、
大小、受谷之多少亦不等，相应奈何？夫经水者，受水而行之；五脏者，合神气魂魄而藏之；
六腑者，受谷而行之，受气而扬之；经脉者，受血而营之。合而以治”

何谓受水而行之？《素问·经脉别论》云“饮（水）入于胃,游溢精气,上输于脾,脾气散精,
上归于肺,通调水道（三焦者，决渎之官，水道出焉）,下输膀胱(膀胱者，州都之官，津液
藏焉，气化则能出矣),水精四布,五经并行”，经水就是人体内的组织液运行，它是依照十
二经路线的，这就是古人说的十二经水。

研究者任世平提出“经络（经脉和络脉）是由全身的肌肉组织，包括血管壁、器官壁、胶原
纤维、弹力纤维、结缔组织等所构成。在各种纤维细胞间隙中流淌的是体液，而体液的主要
成分是水，正是水利用水分子间隙在为机体循环带气、带养和运输代谢废物的。粘稠的体液
能流动吗？能！答案是肯定的。但要想使粘稠的体液流动起来，则必须要具备两个决定性的
生理条件，一个是温度，另一个就是推动体液运行的动力。这两个条件在解剖时，（只有新
鲜尸体上才能见到）否则你是一个也见不到的，因此，也难怪那些从解剖学认识生理的人，
会认为粘稠的体液是不能流动的。

“体液在流经肺脏时，他是在**肺泡壁内运行**的，由于肺泡壁那特殊的形态，流经此处的
体液，它必须要展开、超薄、成水帘型通过，水的这种运动形态，最容易把水分子间隙给拉
开。在流经肺的上部时，它首先把从体内带出的二氧化碳和部分热量，在肺的呼气压力作用
下释放出去，而后在肺的吸气压力作用下，再带上新鲜的空气缔合前进。那么活跃的气分子
又是怎样能够保持安静的待在水里的呢？原来水也是有膜的，只需适量的压力，水膜就能把
气牢固的封闭在水分子间隙中（生活当中，人们常见到的水泡，就是水膜包裹着一些气体形
成的）”

经水运行与经脉运行都有十二经路线。《灵枢经水》云“**经脉者，受血而营之**”，经脉
是因为**受血而营之**才呈露形象可见者，因此经脉是有形的，可以剖而视之（**若夫八尺
之士，皮肉在此，外可度量切循而得也，死可解部而视也，其脏之坚脆，腑之大小，谷之多
少，脉之长短，血之清浊，气之多少，十二经之多血少气，与其少血多气，与其皆多血气，
与其皆少血气，皆有大数**）。这已经被现代医学实验证明的。李瑞午等在新鲜猴尸体(死
亡半小时以内)肢体上的“太渊”穴位注射放射性核素，未见有循经迁移轨迹出现，但若同
时在腋动、静脉插管灌流生理盐水和少量肝素，数分钟后可见有循经迁移轨迹出现．这种在
动物尸体上看不到循经迁移，而恢复血管内液体流动后循经迁移又复现的现象说明核素循经
迁移轨迹的运动需要一定的推动力，而在生物活体中这个动力是来血液循环。

其他实验还发现，只有在无机盐类小分子示踪剂注入穴位内才会有循经线状迁移，且重复性
很强，而且所有实验过的高等脊椎动物均可出现这种线状迁移．但采用硫化锑胶体注入穴位
后，不会出现线状运行而进入淋巴结．这进一步说明循经迁移和血液循环有很大的关系但又
不是动静脉中的血液循环。

《人体组织液定向流动与经络》一文指出：血浆从平行的毛细血管渗透到组织间隙中会在组
织间隙中产生一种定向流动，这种流动的方向刚好和经络线走向一致，流动速度和循经感传
速度或放射性核素迁移速度处于同一数量级。因此我们认为，放射性核素循经迁移的机理是
由于穴位与经络线上平行于经络线排列的毛细血管与周围组织产生血浆．组织液的渗透与吸
收，从而在组织间隙中产生一个与经络方向一致的定向的组织液流动，这种流动的动力来源
于血浆在毛细血管与组织间隙中的渗透。

循经组织液定向流动模型解释了当今经络研究中众多其他理论无法解释的实验现象和结果．

. 首先，本模型计算出的组织液循经流动速度与循经感传及核素迁移速度相符合，它是一种
不回于血液循环、神经传导和淋巴回流的组织液定向流动．产生这种循经定向流动的解剖学
基础是穴位及经络线上毛细血管的定向平行排列，流动的动力来自血液循环中血浆与组织液
的交换与渗透
. 其次，在经络传导的过程中，感传阻滞现象是一种特殊的经络现象，与神经传导方式是截
然不同的．当在表皮加压力即相应的Po升高时，由模型计算出的速度u将会减小，所以循经
传导和核素迁移的速度会变慢，从而解释了循经感传受压阻滞的现象
. 第三，当血液循环停止时，就设有了循经核素迁移与循经感传现象这是因为没有血液循环
就设有血浆跨壁渗透，组织液流动自然就失去了动力如果用生理盐水代替血液循环时，跨壁
渗透恢复了，组织液的定向流动又会重新开始，所以核素循经迁移现象叉出现了，因此本模
型可以很好地从生理学机理上解释李瑞午等所观察到的实验现象．
. 第四，在循经输运的过程中物质迁移会逐渐被血液循环所吸收．从计算结果中可以看出，
从一根毛细血管中流出的物质可能会沿着组织液的定向流动轨迹迁移，到达另一根毛细血管
时而被吸收，所以物质迁移的过程也是在不停地扩散与被再吸收的过程，这与循经输运物质
迁移会逐渐被血液循环所吸收是相符合的．第五，循经的这种组织液定向流伴随血液循环与
毛细血管渗透而存在。

因此，经脉的真相就是组织液的巡经运动，这种运动推力来自毛细血管内血液流动。后天饮
食产生的营血卫气会随经脉运行，并在组织液中进行渗透滋养，“内联五脏六腑”。气口诊
脉所诊脉气就是气血的表现。
