= 卫出上焦还是下焦是必须搞清的问题

http://blog.sina.com.cn/s/blog_727392820102wzl2.html[原文地址]

营气与卫气是经络系统的一个重要组成部分,在《素问》与《灵枢》中都有不少论述。但对
《灵枢·营卫生会》中提到的卫气所出的问题,历代有关中医文献及注家,一直存在“卫气出
于下焦”和“卫气出于上焦”两种说法,

* 现今版《营卫生会》“黄帝曰：愿闻营卫之所行，皆何道从来？岐伯曰：**营出于中焦，
卫出于下焦**”，
* 而《针灸甲乙经》嘉靖本与明蓝格抄本均作“卫出于上焦”。
* 《太素·卷十二·营卫气别》亦作“卫出于上焦”。
* 《东医宝鉴·卷三·三焦腑》引《灵枢·营卫生会》文“上焦出于胃上口,……大会于手太
阴”一段,**末有“命曰卫气也”五字**。
* 《灵枢·痈疽》所云:“上焦出气,以温分肉,而养骨节,通滕理”。
* 《灵枢·平人绝谷篇》亦说:“上焦泄气,出其精微,漂悍滑疾……”“泄”即“出”之意。
* 《灵枢·邪客篇》说:“卫气者,出其悍气之漂疾”故而经文前后一致都说“卫出上焦”。
* 华佗 《中藏经》亦云“三焦者，人之三元之气也，号曰中清之腑。总领五脏六腑，荣卫
经络，内外左右上下之气也。三焦通，则内外左右上下皆通也。其于周身灌体，和内调外，
荣左卫右，导上宣下，莫大于此者也。又名玉海水道，上则曰三管，中则名霍乱，下则曰走
哺，名虽三，而归一，有其名，而无形者也，亦号曰孤独之腑。**而卫出于上，荣出于中**，
上者，络脉之系也；中者，经脉之系也；下者，水道之系也。亦又属膀胱之宗始，主通阴阳，
调虚实”。

近年来论证文章也可谓不少,然在习惯上“卫出下焦”之说似乎已成定论。真相到底如何其
实关系到对中医的根本认识，因为营卫即气血，不明气血真像何来治病？因此,很有必要加
以进一步的探讨和辨析。

《五味篇》“黄帝曰：愿闻谷气有五味，其入五脏，分别奈何？伯高曰：胃者，五脏六腑之
海也。水谷皆入于胃，五脏六腑，皆禀气于胃。五味各走其所喜．谷味酸．先走肝。谷味苦．
先走心。谷味甘．先走脾。谷味辛．先走肺。谷味咸．先走肾。谷气津液已行，营卫大通，
乃化糟粕，又次传下。黄帝曰∶营卫之行奈何？伯高曰∶谷始入于胃，其精微者，先出于胃
之两焦，以溉五脏，别出两行营卫之道。

这段话其实很重要，它解释了营卫的来源和运作秘密。营卫源于入于胃的水谷精微，此精微
并非我们认为的消化后的营养物质，它的真实面目是气：营气和卫气。**__营卫先于食物消
化而出__**！故“伯高曰∶**__谷__**始入于胃，其精微者，**__先出__**于胃之两焦”，
胃之两焦即上焦和中焦。就是说谷物才入胃，精微就已经从两焦中散出来了，而所谓消化吸
收，是要等“谷气津液已行，营卫大通”后“乃化糟粕，又次传下”的，按照现代研究是到
小肠时候的事情，故而气血不通的人连消化都受影响，所谓“虚不受补”也。**这个出来的
精微之谷气“有五味，其入五脏（及六腑）”故曰“ 五脏六腑，皆禀气于胃”**。

中医体系是基于阴阳分类的，脏腑分阴阳，因此这个谷气精微也分阴阳，**阳为卫气，阴为
营气，阳归阳，阴归阴，因此阳气入阳腑，阴气入阴脏。卫为气，营为血**，《决气篇》曰:
何谓气？上焦开发,宜五谷味,熏肤充身泽毛,若雾露之溉,是谓气。何谓血？岐伯曰：中焦受
气，取汁变化而赤，是谓血。这里明确了卫气对应“气”，营气对应“血”。上焦出卫气，
中焦出营血明也。

营卫都属谷气，《灵枢·营卫生会篇》云:“人受气于谷,谷入于胃,以传于肺,五脏六府,皆以
受气,其清者为营,浊者为卫,”。通常理解清为阳，浊为阴，对应营卫似乎应该清为卫，浊
为营，何以这里反称“其清者为营,浊者为卫”？清者水谷之精气也，浊者水谷之悍气也，
诸家以上下焦言清浊者皆非，内经是以**清者属阴**，其性精专，故化生血脉而周行于经隧
之中，是为营气。**浊者属阳**，其性疾滑利，故不循经络而直达肌表，充实于皮毛分肉之
间，是为卫气。这个阴清浊阳的标准是以营卫的受气归属来划分的，卫气归阳腑，阳腑受浊
谷，故而卫为浊气。营气归五脏，五脏受清气，故而营为清。在《灵枢阴阳清浊篇》中有
“黄帝曰∶愿闻人气之清浊。岐伯曰∶受谷者浊，受气者清。” 岐伯说受谷的是浊，就是
说物质态的谷是浊，非物质态气的是清，人体中受谷的是阳明胃，受气的是太阴肺。胃为地，
肺为天，以膈相分，因此云"清者注（手太）阴（肺），浊者注阳（足阳明胃）”。

《灵枢·五味论》指出:“上焦者,（阳经）受气而营**诸阳**者也。“**诸阳**”就是三阳，
三阳即六腑，胆小肠胃膀胱大肠也。《素问·调经论》也说:“阳（经）受气于上焦,温皮肤
分肉间”。三阳以太阳为首，《素问·热论篇》说:“巨阳者,诸阳之属（三阳都归属巨阳）
也……为诸阳主气也。” 因此太阳受阳浊最多。阴包含三阴，三阴即五脏（也可称为六脏，
只是心主为虚脏），以太阴为首， 因此太阴受阴清最多。因此可以理解《天元纪大论》中
为何云“阴阳之气各有多少,故曰三阴三阳也”，此阴阳之气就是营卫之气，中医的三阴三
阳以营卫之气的多少来划分的，非仅仅是哲学概念。因为卫气注阳，故而为浊，营气注阴，
故而为清，这是一种阴阳分类的概念。

《终始篇》云“凡刺之道，毕于终始，明乎终始，五脏为记，阴阳定矣。**阴者，主脏。阳
者，主腑。阳（卫）授气于四肢。阴（营）授气于五脏**”就是说要明白针刺之道，你就要
知道水谷精微中的卫气先熏肤充身泽毛，所谓“皮肤分肉间”也，**自四支而注入六腑**。
水谷精微中的营气取汁变化而生赤血**注入五脏，阳气入阳腑，阴气入阴脏**。此即所谓
“别出两行营卫之道”也。这一步谷气的宣发是十分迅速的，远远快于物质形态的消化吸收，
这也是汤液治病养生的原理所在。

然后“黄帝问：夫（手太）阴清而阳（足阳明）浊，浊者有清（谷气有上升），清者有浊
（肺气有下降），清浊别之奈何？”《灵枢阴阳清浊篇》 云“气之大别，清者上注于肺，
浊者下走于胃。”就是说气的大类分 以上升的为“清”，下降为“浊”。然后经文又云
“浊而清者上出于咽，清而浊者则下行”。如何理解？ 《灵枢》曰∶阳明之脉，上通于心，
上循咽出于口。就是说胃中谷气上升，为“胃之清气，上出于口”，《动输》云“胃为五脏
六腑之海，其清气上注于肺”。谷气上行，此即“浊（下）而清者上出于咽”，此所谓“海
之行云气者，天下也”。“清而浊者则下行”， “肺之浊气，下注于经，内积于海”，即
肺中的精气是输送到身体内，注十二经，积于经海冲脉，如同天下雨降落地面，故而曰“清
而浊者则下行”。

《动输》“胃气上注于肺，其悍气（卫气）上冲头者，循咽，上走空窍，循眼系，入络脑，
出顑，下客主人，循牙车，合阳明”这段话与《营卫生会》”上焦出于胃上口，并咽以上贯
膈而布胸中，走腋循太阴之分而行，还至阳明，上至舌，下足阳明”两者合参，即知此乃卫
气出上焦也，卫气即上行至头，同时也走肺。因为上焦出卫气，故而后云“常与荣俱行于阳
二十五度，行于阴亦二十五度，一周也，故五十度而复大会于手太阴矣”，而下焦段文字未
有行阴行阳之论。

至此我们看到一个历来被后世学医之人忽略的营卫运行现象：**__营卫会先出胃中而“浊者
注阳, 清者注阴”__**，因此《内经营气篇》云“黄帝曰：营（血）（卫）气之道，内谷为
宝。谷入于胃，乃传之肺，（营）流溢于（脉）中，（气）布散于（脉）外” 《营卫生会
篇》云“人受气于谷，谷入于胃，以传与肺，五脏六腑，皆以受（营卫之）气，其清者为营，
浊者为卫，营在脉中，卫在脉外”

那么阴阳营卫如何注脏腑呢？《内经营气篇》“精专者（乃营气），行于经隧（即经脉也），
常营无已，终而复始，是谓天地之纪，故气从太阴出注手阳明，上行注足阳明。。。。”
《营卫生会篇》“ 营周不休，五十度而复大会，阴阳（经）相贯，如环无端”，就是说营
卫气自阴经之首-太阴经（手太阴肺经）出而阴阳相贯而注，五十度而复大会也，注满三阴
三阳经。手太阴肺乃营卫气流注起点，故而《清浊篇》有云“诸阴皆（受）清（气），手太
阴独受阴之清（气）”。“营气者，泌其津液，注之于脉，化而为血，以营四末，内注五脏
六腑，以应刻数焉”即100刻数五十营周。

同时卫气走上窍，自阳经之首-太阳经（足太阳膀胱）出，故而经曰“ 是故平旦阴尽，阳气
出于目，目张则气上行于头…”，“卫气行于阴二十五度，行于阳二十五度，分为昼夜”，
手太阳也是太阳，故而《清浊篇》云“手太阳独受阳之浊” 小肠居胃之下，承受胃中水谷
而行消化吸收，故有此言也。营卫这种流注都自平旦寅时起。不管营卫，都是由三焦出，故
而《流注针经》云“惟三焦受十经血气”也。

至此我们可以总结营卫运行如下：

其一，《灵枢·营卫生会篇》云:“人受气于谷,谷入于胃,（先）以传于肺,五脏六府,皆以受
(营卫）气,其清者为营,浊者为卫”。此阶段， 卫气注阳腑，荣气注阴脏，《清浊篇》“浊
者注阳, 清者注阴”， 《内经营气篇》“黄帝曰：营（血）（卫）气之道，内谷为宝。谷
入于胃，乃传之肺，（营）流溢于（脉）中，（气）布散于（脉）外” 。即“营气者，泌
其津液，注之于脉，化而为血，以**营四末**”，“卫气者，出其悍气之慓疾，而先**行四
末**、分肉、皮肤之间而不休者”营卫注满阴阳腑脏。

其二，常以平旦为纪，谷气出手太阴肺，卫气上表出足太阳目，开始流转行于阴二十五度，
行于阳二十五度，流注各经，五十而大会。此即《营卫生会》中“故太阴主内，太阳主外，
各行二十五度，分为昼夜”也。
 
世人皆看到营卫其二的流注，却没看到营卫对脏腑的同期灌溉，尽管经文言之凿凿，奈何世
人不悟也。明白此理，你就能解开内经中气血论述的一系列难点。
