= 十二经流注与子什流注同时存在

http://blog.sina.com.cn/s/blog_727392820102x01g.html[原文地址]

世人只看到内经论述十二经流注的存在而没看到对于子午流注的论述亦存在。由于传抄错误，
世人认为“营出中焦，卫出下焦”，其实是“营出中焦，卫出上焦”。《营卫生会》云
“（卫出）上焦出于胃上口，①并咽以上，贯膈，而布胸中，走腋，**循太阴之分而行**，
②还至阳明，上至舌，下足阳明，**常与营俱行于阳二十五度，行于阴亦二十五度一周也**。
故五十度而复大会于手太阴矣”如果不认识道卫出上焦，你就无法理解这个“**常与营俱行
**”的是什么，也无法理解《难经》云“经言人受气于谷，谷入于胃，以传于肺，五脏六腑
皆以受气，其清者为营，浊者为卫，营行脉中，卫行脉外，营周不休，五十而复大会，阴阳
相贯，如环无端，故知**营卫相随**也”。

营卫相随而偕行，如人之夫妇，故《外经微言》云“夫阴阳者，人身之夫妇也；气血者，人
身之阴阳也。夫倡则妇随，气行则血赴，气主煦之，血主濡之”。营卫十二经脉流注，古圣
以此定义了顺逆概念，《顺逆篇》“黄帝曰：脉行之逆顺，奈何？岐伯曰：手之三阴，从脏
走手；手之三阳，从手走头；足之三阳，从头走足；足之三阴，从足走腹”更见《外经微
言》：

[cols="3*",options="header"]
|===
| 三阴三阳 | 顺 | 逆
| 足三阴 | 自足走腹，顺也 | 自腹走足，逆也
| 足三阳 | 自头走足，顺也 | 自足走头，逆也
| 手三阴 | 自藏走手，顺也 | 自手走藏，逆也
| 手三阳 | 自手走头，顺也 | 自头走手，逆也
|===

根据描述营气十二经脉流注顺序可以发现：手三阳经、足三阴经营气流注方向自手走头，自
足走腹，为顺行。手三阴经、足三阳经的方向为自藏走手，自头走足，亦为顺行。那逆行的
又是什么呢？近来不少研究者发现，逆行的是五输穴！而用五输穴治病的就是子午流注。

五输穴是十二经脉分布在肘膝关节以下的五类特定穴，即井、荥、输、经、合穴。五输穴从
四肢末端向肘膝方向向心排列根据五输穴由四肢末端向肘膝方向向心排列可列出下表：

[cols="3*",options="header"]
|===
| 三阴三阳 | 十二经流注 | 子午流注
| 足三阴 | 自足走腹，顺也 | 自足走腹，顺也
| 足三阳 | 自头走足，顺也 | 自足走头，逆也
| 手三阴 | 自藏走手，顺也 | 自手走藏，逆也
| 手三阳 | 自手走头，顺也 | 自手走头，顺也
|===

专家教授们苦思冥想也搞不明白为何如此，这是因为他们即不知道营卫有十二经偕行流注，
也不明白还有分行流注，注阴（脏）注阳（腑）的概念，而营卫分行流注就是子午流注。

对于这种顺逆运行现象，在《邪客篇》明确写道“手太阴之脉，出于大指之端，内屈循白肉
际，至本节之后太渊留以澹，外屈上于本节之下，内屈与阴诸络会于鱼际，数脉并注，其气
滑利，伏行壅骨之下，外屈出于寸口而行，上至于肘内廉，入于大筋之下，内屈上行 阴，
入腋下，内屈走肺，此顺行逆数之屈折也”，但是如果你没有子午流注的概念，不懂营卫气
血分注阴阳的内涵，那么你就读不懂这篇文章。何谓“顺行逆数之屈折”？手太阴，自藏走
手，顺也，自手走藏，逆也。何者逆行？营卫之子午流注也，五输之穴也。

《本输》云“肺出于少商，少商者，手大指端内侧也，为井木；溜于鱼际，鱼际者，手鱼也，
为荥；注于太渊，太渊鱼后一寸陷者中也，为俞；行于经渠，经渠寸口中也，动而不居为经；
入于尺泽，尺泽肘中之动脉也，为合。手太阴经” 岐伯论“肺”之五输就是向心排列。为
何是云“肺”而不言“手太阴出于少商”？古圣遣词造句非是无因，乃是深合自然。言肺者，
乃明五输之输于肺也。最后坠一“手太阴经”表明此五输亦在本经之内。

子午流注的这种顺逆流注体现在发掘出来的论述灸法的古籍《足臂十一脉灸经》中，专家们
发现了十一脉的向心排列，却不明白其意，由此搞出了一个“经脉早期理论，后来被更完善
十二经流注所取代，可推论内经是劳动人民不断积累修正而得”的谬论。

之所以是十一脉，研究者已经发现是心包代心脉而言，在《邪客篇》谈到“黄帝曰∶手少阴
之脉独无 何也？岐伯曰∶少阴心脉也，心者五脏六腑之大主也，精神之所舍也，其脏坚固，
邪弗能容也，容之则心伤，心伤则神去，神去则死矣。故诸邪之在于心者，皆在于心之包络，
包络者心主之脉也，故独无 焉。” 凡脏腑经络，有是脏则有是经，脏居于内，经行于外。
心脏坚固居内，邪弗能容，而经则不能无病，故少阴经病者，则治其经。之所以是向心排列，
是因为子午流注是针刺法和灸法的根本原理，必须尊从。

世人苦苦寻求子午流注的内涵，希望能从营卫的流注中找到依据，因为不明白营卫注阴阳脏
腑的现象存在，只注重于营卫十二经的流注，因而研究结果都是无法契合，由此愤而斥之子
午法乃无稽之谈。其实子午流注就是内经针经所论，扁鹊所传也。通过前篇博文，我们已经
知道营卫既有流注十二经脉中也有流注脏腑。十二经脉系十二地支，五脏六腑则拘于十干，
因此营卫的两种运行方式相结合就成了干支配合五输穴法，即后人所称“子午流注法”，世
人不理解营卫真相，自然就无法理解子午流注。只有从子午流注法才能真正解释清楚何谓
“营行脉内，卫行脉外”也。

总结一下，营卫气血出手太阴而偕行流注于十二经脉，在四末处开始营卫注阴注阳，此流注
规律依照子午流注法而行。按照阳注阳（腑），阴注阴（脏），其手三阳，足三阴的营卫流
注必须注入脏腑：三焦，大肠，小肠及脾，肾，肝，那么必然是要顺行。同理其手三阴，足
三阳的营卫流注必须注入脏腑：肺，心，心主及膀胱，胃，胆，那么必然是要逆行。

故而曰“用针之理.必知形气之所在.左右上下.阴阳表里.血气多少.**行之逆顺.出入之合
**.谋伐有过.知解结.知补虚泻实.上下气门.明通于四海.审其所在”“以微针通其经脉,调
其**血气**,荣其**逆顺出入之会**”
