= 如何理解营行脉内、卫行脉外

http://blog.sina.com.cn/s/blog_727392820102x0b5.html[原文地址]

通过前面系列篇章，我们应该知道营卫运行的两种情况：一者，营卫偕行自肺出行十二经，
肺象“天”，故谓“海之所行云气者，天下也”此时统称云气未分气血。二者，营卫分行注
阴注阳，**只有到这步才分出血与气**，各注腑脏，**才有脉内外之别**。此所谓“胃之所
出气血者，经隧也。经隧者五脏六腑之大络也。”

不管哪种运行，两者都需借助十二经，前者如同地球上大气的运行路径，后者如同雨落于地
汇成的十二水。天气降而为雨，有三百六十五溪谷为应，会三百六十五气穴，连三百六十五
络脉。《九针十二原篇》曰“节之交,三百六十五会。所谓节者，（血）神(卫)气之所游行
出入也。”小针解曰“节之交，三百六十五会者，络脉之渗灌诸节者也。”三百六十五气穴
中有脏俞六十，腑俞七十二。这些俞穴都集中在四肢末端，控制着头胸腹胫之气街运行，所
谓“四末绝则径通”也，其总管三百六十五气穴，它们的运行规律即子午流注所重点描述的。

《调经论》云“ 夫阴（经）与阳（经）皆有俞会（三百六十五气穴之会，主要是四末五输
穴）。阳注于阴，阴满之外，阴阳均平，以（气血）充其形，九候若一，命曰平人”。《外
台秘要明堂序》亦云“手足十二经,亦皆有俞。手足者,阴阳之交会,血气之流通,外营肢节,
内连脏腑” 即如《流注针经》所云“荣者血也，卫者气也，由肠胃受谷，化血气所为也。
上焦出气，以温分肉而养筋通腠理；中焦出气如露，上注溪谷而渗孙脉。津液和调，变化而
为血，血和则孙脉先满，乃注络脉，皆盈，乃注于经脉。阴阳以张，因息乃行，行有纪纲，
周有道理，与天协议，不得休止，切而调之”

这种“阴阳以张，因息乃行，行有纪纲，周有道理”的运行遵守“营行脉内，卫行脉外”的
规则。所谓“营行脉内，卫行脉外”其**脉内外的概念是营卫在分气行和血行的阶段才存在
的一个相对概念**。经云“经脉者，受血而营之”，“夫脉者，血之府也”因此只有受血的
称为脉内，另一个为脉外，换句话说受血在哪里，哪里就称为脉内，另一方面称为脉外或者
经。《琼瑶针经》云“**__谓之经者，以气血流行经常不息而言；谓之脉者，以血理分衮行
体而言也__**”

《灵枢·卫气篇》论述为“其浮气之不循经者为卫气,其精气之行于经者为营气,阴阳相随,外
内相贯”即云“浮气之不循经”“ 精气之行于经”，又言“阴阳相随”如何理解？相随怎
可能一循经，一不循经？其实所谓“相随”可以比作一对夫妇，妇坐马车内，夫骑马在外，
一同赶路。所谓“不循经”者，指夫骑马可以任意驰骋，随意挥洒，而“循经”者，指妇只
能坐车，循规蹈矩，正襟危坐，两者并不矛盾。经文云“外内相贯”即道出营卫其实互相贯
通。由于内难言辞精简，去今久远，后人很容易有理解上的困难，因此要真正理解脉内脉外
运行真意，只有从子午流注经文入手。《流注针经指微赋》清晰的阐述了“脉内脉外”的概
念：“夫欲用迎随之法者，要知经络逆顺浅深之分。**__诸阳__之经，行于脉外。__诸阳__之络, 行于
脉内。__诸阴__之经,行于脉内,__诸阴__之络，行于脉外**，仍各有所守之分”可见这是一个动态的概
念，是“各有所守之分”而定的，我们可以列表如下：

[cols="1,2,2,4",options="header"]
|===
| | 阳（卫行脉外）| 阴（营行脉内）| 子午流注
| 阳 | 阳经 | 阳络 | 气先脉外，血后脉内。气先至而后血行
| 阴 | 阴络 | 阴经 | 血先脉外，气后脉内。血先至而气后行
|===

《调经论》云“五脏之道，皆出于经隧，以行血气，血气不和，百病乃变化而生，是故守经
隧焉”所谓“经隧”不同于“经脉”，两者概念有异，诸家注经者对此皆无正解。**经隧者，
专指五输之穴也**，气血出自五输，子午流注乃其纲纪，我们来看以下例子：

阳日阳时：以甲戌时胆窍阴为例

《经脉》云“卫气先行皮肤，先充络脉，络脉先盛。故卫气已平，营气乃满，而经脉大盛”。
《素问·四时刺逆从论》曰 ：“经满气溢，（营）入孙络受血，皮肤充实”

甲戌时，卫气先充皮肤分肉溪谷间，气自胆经窍阴井穴出，注胆之络满后入胆经注胆腑，则
卫气已平。从细胞层面讲，人体造血干细胞生成免疫细胞，行脉外。

然后荣气随卫气之后注胆之络，和调津液（成血清），变化而赤为血。从细胞层面讲，人体
造血干细胞生成血细胞混合血清成为血液。

孙络（孙络和络脉）皆盈，血液充实皮肤，乃注胆腑，则荣气已平。《灵枢·邪客》“营气
者,泌其津液,注之于脉，化而为血，以荣四末，内注五脏六腑，以应刻数焉”这样阴阳气血
两平若一，阴平阳秘也。

此《子午流注针经》所谓“阳日气先脉外（阳经为脉外），血后脉内（阳络为脉内）”也。
《针经指南》又云“盖阳日气先行引血，后随气流注在脉外而行，此为夫有气，妇往从之
者”**阳为夫，阴为妇，阳日妇随夫在外**，所谓“随气流注在脉外”指血随气流入胆经，
阳经为脉外也。《阴阳大论》云“**清阳（气）实四肢,浊阴（血）归六腑**”

阴日阴时：我们以乙亥时肝大敦为例。

《灵枢·痈疽》曰 “中焦出气如露，上注溪谷，而渗孙脉，津液和调，变化而赤为血。血和
则孙脉先满溢，乃注入络脉，皆盈，乃注于经脉”

乙亥时，营气注溪谷，自肝大敦穴出井，而渗乙肝孙络，阴络为脉外，络脉内和调津液，变
化而赤为血，血和则孙脉先满溢，乃注入络脉，皆盈，乃入注乙肝脉内入肝脏，则荣气已平，
然后卫气注入肝之孙络，孙络皆盈，腠理充实乃注于肝经脉外，则卫气已平。《阴阳大论》
谓“**清阳（卫气）发腠理，浊阴（营血）走五脏**”。这样阴阳经脉俱盛，气血两平若一，
阴平阳秘也。

《金匮要略》云“所谓腠者,是三焦通会元真之处,为血气所注;理者,是皮肤脏腑之纹理也”。
《灵枢·决气》“腠理发泄,汗出溱溱”。“肾合三焦膀胧,三焦膀胧者,腠理毫毛其应”。腠
理既非专指组织纹理，更非结缔组织，而是对人体所有组织间隙和组织纹理的统称。腠本义
是指人体肉之所会，泛指人体组织的间隙。理则主要指的是机体组织的纹理和层次。皮肤分
肉均属腠理范畴。

此《子午流注针经》所谓“阴日血先脉外（阴络为脉外），气后脉内（阴经为脉内）”也。
《针经指南》又云“盖阴日血先行引气，后随血入脉中而行，此为妇有气，夫往从之者”
**阳为夫，阴为妇，阴日夫随妇归家**。所谓“随血入脉中而行”乃指卫气随血入肝经，阴经为
脉内也。

**简而言之：阳日气引血而行，以气为主，故曰脉外；阴日血引气而行，以血为主，故曰脉
内。其实血气须臾不可分。**

阳日注腑，三十六穴。阳日六腑值日者引气，则气先至而后血行

[cols="6*",options="header"]
|===
| 甲己 | 丙辛 | 戊癸 | 乙庚 | 丁壬 |
| 甲(胆） | 丙（小肠） | 戊（胃） | 庚（大肠） | 壬（膀胱） | 壬（三焦）
| 甲日戌时胆窍阴 | 丙日申时少泽当 | 戊日午时厉兑先 | 庚日辰时商阳居 | 壬日寅时起至阴 | 壬日子时起关冲
| 壬午膀胱委中寻 | 甲辰阳陵泉合长 | 丙寅小海穴安然 | 戊子时居三里宜 | 大肠庚戌曲池真 | 庚申天井合肘外
| 庚辰经注阳溪穴 | 壬寅经火昆仑上 | 甲子胆经阳辅是 | 丙戌小肠阳谷火 | 戊申时注解溪胃 | 戊午支沟经腕后
| 戊寅陷谷阳明俞 | 庚子时在三间俞 | 壬戌膀胱寻束骨 | 甲申临泣为俞木 | 丙午小肠后溪俞 | 丙辰中渚俞后寻
| 丙子时中前谷荥 | 戊戌内庭治胀康 | 庚申荥穴二间迁 | 壬午膀胱通谷之 | 甲辰胆脉侠溪荥 | 甲寅液门荥次陷
| 甲申时纳三焦水 | 丙午时受三焦木 | 戊辰气纳三焦脉 | 庚寅气纳三焦合 | 壬子气纳三焦寄 | 壬戌之时入三焦 
| 胆原丘墟 | 腕骨 | 冲阳 | 合谷 | 京骨 | 阳池
|===

阴日注脏，三十穴。阴日六脏值日者引血，则血先至而气后行

[cols="6*",options="header"]
|===
| 甲己 | 丙辛 | 戊癸 | 乙庚 | 丁壬 |
| 己（脾） | 辛（肺） | 癸（肾） | 乙（肝） | 丁（心） | 癸（心包）
| 己日巳时隐白始 | 辛日卯时少商本 | 癸日亥时井涌泉 | 乙日酉时肝大敦 | 丁日未时心少冲 | 中冲为井癸丑心
| 丁丑时合少海心 | 己亥脾合阴陵泉 | 辛未肺经合尺泽 | 癸巳肾宫阴合谷 | 乙卯肝经曲泉合 | 辛酉曲泽合肘里
| 乙亥中封内踝比 | 丁酉心经灵道引 | 己巳商丘内踝边 | 辛卯经渠是肺经 | 癸丑复溜肾水通 | 己未间使掌后经
| 癸酉太溪肾俞是 | 乙未太冲本肝俞 | 丁卯俞穴神门是 | 己丑太白脾俞穴 | 辛亥太渊掌后寻 | 丁巳大陵心俞寻
| 辛未时中鱼际取 | 癸巳然谷何须忖 | 乙丑行间穴必然 | 丁亥时荥少府心 | 己酉大都脾土逢 | 乙卯劳宫手掌荣
| 己卯血归包络止 | 辛丑血纳包络准 | 癸酉血纳包络连 | 乙未时归心包水 | 丁巳时受包络火 | 癸亥时血入心包 
|===

子午流注就是真正体现了何谓“阴阳以张，因息乃行，行有纪纲，周有道理”：

[cols="2,3,3,4",options="header"]
|===
| 五脏五腑根井 | 阳注五腑 | 阴注五脏 |
|  | 气先脉外血后脉外 | 血先脉内气后脉内 |
| 甲胆窍阴 | 甲丙戊庚壬 | .10+| 迎之五里，中道而止，五至而已，五往而脏之气尽矣，故五五二十五而竭其输矣，此所谓夺其天气者
| 乙肝大敦 | | 乙丁己辛癸
| 丙少泽当 | 甲丙戊庚壬 |
| 丁心少冲 | | 乙丁己辛癸 
| 戊厉兑先 | 甲丙戊庚壬 |
| 己隐白始 | | 乙丁己辛癸
| 庚商阳居 | 甲丙戊庚壬 |
| 辛少商本 | | 乙丁己辛癸
| 壬起至阴 | 甲丙戊庚壬 |
| 癸井涌泉 | | 乙丁己辛癸
|===

以上气血脉内外相贯，阴阳交替而行，营卫合得百刻之数，故曰“**一日取六十六穴之法，
方见幽微，一时取一十二经之原，始知要妙**。”参见博文<<20180129-针灸探秘11.adoc#,《针灸
探秘11-子午纳甲法与养子时刻法乃一体一用非两法也》>>。读书要能举一反三，既然有六
十六穴合得刻数，那么剩余气穴不在刻数之内的自然可各取时宜而刺之，然其行终难逃子午
流注也，例如点穴受伤者，子午流注治之可也。

中医现在的乱象丛生正是因为那些注释内经，自诩“内经新解”“中医修正”的人不明阴阳
真意而泛哲理化，不懂干支五行纲纪道理而鼓吹“中医数理化”，肆意穿凿附会，不徒误己
更是误人。
