= 人体造血的机制

http://blog.sina.com.cn/s/blog_727392820102wzwy.html[原文地址]

 现代医学研究到了分子水平，但是还是对人体如何造血的根本机制缺乏整体认识，而在
 《素问·经脉别论》里，古圣早已言之凿凿了，我们来看：

== 食气入胃，散精于肝，淫气于筋

精，食气之精华也。肝主筋，故胃散谷气于肝，则浸淫滋养于筋

== 食气入胃，浊气归心，淫精于脉

血为神气，乃阴为浊。心主血，血液循环都由心。《素问·五脏生成篇》“诸血者,皆属于心;诸
气者,皆属于肺。

如何淫精于脉？《灵枢·痈疽》曰 “中焦出气如露，上注溪谷，而渗孙脉，津液和调，变化
而赤为血。血和则孙脉先满溢，乃注入络脉，皆盈，乃注于经脉”，因此这个功能是需要通
过肺来进行的，而且是在“溪谷”。

《素问气穴论》“帝曰∶愿闻溪谷之会也。岐伯曰∶肉之大会为谷，肉之小会为溪，肉分之
间，**溪谷之会，以行荣卫**，以会大气” ，这个溪谷有荣卫俱行于此，这是造血的起始
地。

== 脉气流经

脉气指营气。所谓“脉”就是“受血而营”。所谓“受血而营”就是前篇讲到的：血浆从平
行的毛细血管，渗透到组织间隙中，会在组织间隙中产生一种定向流动，这种流动的方向刚
好和经络线走向一致。

所谓“谷入于胃，乃传之肺，精专者行于经隧”即受血后血在毛细血管的定向运行也，这里
讲了五十营的运转。

故知营气运行有两方面：**淫精于脉，脉气流经**

== 经气归于肺

肺主气，流经的营气都归于肺。心肺是相互合作的，不是说血不入肺，我们都知道血液由静
脉汇入肺中散入毛细血管交换氧气而为动脉血，进入心脏供应全身，但是从精气和血归属方
面来讲，气归肺，血归于心。

由于西医没有认识到气的一面，故而没能发现经脉现象。

经云“上注于肺脉，乃化而为血，以奉生身，莫贵于此，故独得行于经隧，命曰营气”《灵
枢营卫生会》云“中焦亦并胃中,出上焦之后,此所受气者,泌糟粕,蒸津液,化其精微,上注于
肺脉,乃化而为血也”，中医早就认识到静脉血需要在肺部交换氧气才能为血，然后心脏供
血全身。氧气即“大气”，其抟而不行者，称为“宗气”行呼吸。

== 肺朝百脉，输精于皮毛

一般都认为是倒装句为“百脉朝肺”，但并非此段经文意思。这里“朝”并非使动用法，非
使百脉来朝，而是主动词。《内经》称心为“君主”而肺为“相傅”，相傅即宰相，心为君，
百脉何以朝相而不朝君？其实这里“朝”古文通假“调” 肺作为相傅官而调百脉。

《素问·灵兰秘典论》说：“肺者，相傅之官，治节出焉。”所谓“节“即三百六十五节，
人身骨节三百六十五，有骨节而后有溪谷，有溪谷而后有穴俞，而溪谷与三百六十五气穴应
之，“ 溪谷三百六十五，穴会亦应一岁”也。

百脉是指三百六十五脉，《气穴论》云“孙络之脉别经者，其血盛而当泻者，亦三百六十五
脉”。结合下句实说肺输精气于三百六十五脉。可见肺乃周身气穴之主，五输穴统管诸穴。

所谓“阳有五，五五二十五”，此阳即相对于血而言指气，五即五行干支也，应人五脏六腑
也，脏腑各有五输，营卫分别注之，即五五二十五，经云“人有五脏，五脏有五变，五变有
五输，故五五二十五输”子午流注的理论根源于此也。

这个“精气”是指卫气，不是前面的“淫精于脉”的营气。卫气之输乃注皮毛分肉间，《太
素》“卫气者，出其悍气之慓疾，而先行四末、分肉、皮肤之间而不休者也”。分肉即溪谷，
可见营卫都注溪谷。

卫气有两种流注：

* 一种是上走空窍，即《动输》“胃气上注于肺，其悍气上冲头者，循咽，上走空窍，循眼
系，入络脑，出顑，下客主人，循牙车，合阳明”，
* 一种是走肺，输精于皮毛。因此《营卫生会》云“上焦出于胃上口，①并咽以上，贯膈，
而布胸中，走腋，循太阴之分而行。②还至阳明，上至舌，下足阳明”。

内经以酒来比喻卫气之行，酒乃五谷悍气，饮酒下胃，人立刻会感到酒气上头，然后周身皮
肤发红即是此理。

== 毛脉合精

毛指前面肺输精于皮毛，脉指淫精于脉。经云“营卫者，精气也”，因此这里毛脉指代营卫。
所谓**__“合精”即营气与卫气两精相合，相合之处在于孙络即所谓毛细血管__**。

经云“两精相博，谓之神”，所谓“神”即 “血者，神气也”，营卫相合才能够生血气，
这是人体造血的气机，所谓”人是铁，饭是钢，一日不吃饿得慌“。有此气机才能使得物质
层面的细胞凭借津液造血。

正所谓“清妙之合专易，重浊之凝竭难，故天先成而地后定”。故知，营卫相合才能生血，
营卫不合精，吃再多也是贫血。

== 行气于腑，府精神明，留于四脏

腑乃六腑，与后面脏相对。

营卫合精，乃味与气合。经曰“阴化形，阳化气”“形食味，精食气”五脏六腑为有形，受
五味供养。

“血脉营气精神，此五脏之所藏也”，《素问·调经论》“心藏神（心藏脉，脉舍神）,肺藏
气（气舍魄。气魄）,肝藏血（血舍魂，血魂）,脾藏营（营舍意）,肾藏精（精舍志）。五
脏所藏之精神气魂魄为无形，受气供养。

经云五脏藏精神气魂魄而不泄，六腑泄而不藏。六腑所泄者何？经云“**六腑者，受谷而行
之，受（谷）气而扬之**”。故而《五脏别论》云∶胃、大肠、小肠、三焦、膀胱，此五者，
天气之所生也。其气象天，故泻而不藏，此受五脏浊气（即行五味于五脏，五味乃浊气），
名曰传化之府，此不能久留，输泻者也（不是后人理解排泄残渣，这只是物质层面，还有气
的层面）。所谓五脏者，藏精气而不泻也，故满而不能实；六腑者，传化物而不藏，故实而
不能满”。

而此五腑能扬谷气是靠胆，“脑髓骨脉胆女子胞，此六者地气之所生也，皆藏于阴而象于地，
故藏而不泻，名曰奇恒之府”。《外经微言》云“胆司渗，凡十一脏之气得胆气渗之，则分
清化浊，有奇功焉”，此“清浊”即清阳浊阴，即阳气，谷浊。有胆之气，则能分气味也。
酒气乃悍气，过多则增加胆气分“清浊”的负担，故而“酒热之气，胆之所畏也，过多则渗
失所司，胆受损矣”

腑脏相合，气味行于六府而使其得以运作，**__六腑发扬气味，使其能够供养五脏及所藏之
精神气魂魄__**。

“四脏”即除经文下段食饮入胃所论脾之外的心肝肺肾，这里精神魂魄各留四脏。

《脏像论》云“血脉和利，精神乃居”。这里揭示了气味是如何先后作用于五脏六腑的，也
是汤液治病之为何要考虑五味以及性气。古人行文之简，遣词造句之工整，可见一斑。

== 气归于权衡

由此营卫注五脏六腑，阴平阳秘，气血平衡，权衡气血状况可在气口知之。《阴阳类论篇》
言，‘三阴者，六经之所主也’。三阴即太阴，太阴乃阴阳经之主。
