= 经脉——标本根结

导读：“九针之玄，要在终始（标本根结）。故能知终始，一言而毕，不知终始，针道咸
绝。”运用九针，其精要就在于标本根结，如果明了标本根结，则一句话就可以说清楚，若
不明标本根结，根本就谈不上什么道理，无论张口动手，从一开始就全部是错的。金属质感
分割线

《灵枢·卫气》有这么一段文字：“（营卫）阴阳相随，外内相贯，如环之无端。亭亭淳淳
乎，孰能窃之。然其分别阴阳，皆有标本虚实所离之处。能别阴阳十二经者，知病之所生。
候虚实之所在者，能得病之高下。知六腑之气街者，能知解结契绍于门户。能知虚实之坚软
者，知补泻之所在。能知六经标本者，可以无惑于天下。”意思是说营气和卫气的运行是阴
阳相随，外内相贯的，就如同亭和淳这两个字，很容易令人混淆不清。但是经脉都分了阴阳
的，都有各自的起点和终点，有气血虚实的不同，也有各自会合和分离的部位。所以我们如
果分辨掌握了阴阳十二经脉，就能知道病因。通过诊查经脉气血虚实的位置，便能了解病是
在上还是在下。通过了解六腑气机通行的部位，即能找到治疗疾病的关键途径。知道了疾病
虚实的程度和变化情况，就能够懂得如何进行补泻。明白六经标本所在的人，天下就没有什
么难治的病了。
 
“能知六经标本者，可以无惑于天下。”这是多么诱人的一种境界啊，能做一个医术横行天
下的医生，是多么的牛逼！由此看出，掌握六经的标和本，是相当的重要。
 
《灵枢·卫气》继续说到：“足太阳之本，在跟以上五寸中（至阴），标在两络命门，命门
者，目也。足少阳之本，在窍阴之间，标在窗笼之前，窗笼者，耳也。足少阴之本，在内踝
下上三寸中（涌泉），标在背腧与舌下两脉也。足厥阴之本，在行间上五寸所，标在背腧也。
足阳明之本，在厉兑，标在人迎颊挟颃颡也。足太阴之本，在中封前上四寸之中（隐白），
标在背腧与舌本也。手太阳之本，在外踝之后，标在命门之上一寸也。手少阳之本，在小指
次指之间上二寸，标在耳后上角下外眦也。手阳明之本，在肘骨中，上至别阳，标在颜下合
钳上也。手太阴之本，在寸口之中，标在腋内动也。手少阴之本，在锐骨之端，标在背腧也。
手心主之本，在掌后两筋之间二寸中，标在腋下下三寸也。凡候此者，下虚则厥，下盛则热，
上虚则眩，上盛则热痛。故实者绝而止之，虚者引而起之。”根据六经的标本，就可以知道
经脉的虚实变化，会引起哪些症状，就懂得用补泻的方法去调理。
 
《素问·至真要大论》：“帝曰：六气标本，所从不同奈何？岐伯曰：气有从本者，有从标
本者，有不从标本者也。帝曰：愿卒闻之。岐伯曰：少阳太阴从本，少阴太阳从本从标，阳
明厥阴，不从标本从乎中也。故从本者化生于本，从标本者有标本之化，从中者以中气为化
也。”

除了标本理论，内经还有一个很重要的根结理论。根即树根，即起始。结即缔结，即归结。
“根”和“结”是指十二经脉之气起始和归结的部位。“根”，是经气所起的根源处，为四
肢末端的井穴。“结”，是经气所归的结聚处，在头、胸、腹的一定部位和器官。
 
《灵枢·根结》说：“不知根结，五脏六腑，折关败枢，开合而走，阴阳大失，不可复取。
九针之玄，要在终始，故能知终始，一言而毕，不知终始，针道咸绝。”由此看来，标本和
根结（终始）对于针医而言，都是相当重要的。

《灵枢·根结》只讲了足六经的根与结，但本篇同时也记载了手足六阳经的根、溜、注、入，
其理论与根结理论有相同之处，与五输穴的理论更相似。“根”，是经脉之气的根源处，也
都是四肢末端的井穴；“溜”，本义指流水，与“流”互通，是经脉之气所流经之处，多为
各经脉的原穴；“注”，是经脉之气所灌注之处，多为五输穴的经穴或合穴；“入”，是经
脉之气所进入之处，共有两处，下部的“入”是各经之络穴，上部的“入”则为颈部各阳经
穴。
 
根结理论强调以四肢末端为出发点，着重于经络之气循行的根源与归结。这与十二经脉的起
止点不完全相同，与营气运行的流注方向也有差异，而与五输穴的排列先后一致。

根为四肢末端的井穴，溜为原穴，注多为经穴，下入为络穴，这些穴位均位于四肢肘膝关节
以下，卫行四末，是卫气运行的主要形式。
 
元代窦汉卿在《标幽赋》说：“更穷四根三结，依标本而刺无不痊。”并进一步指出，十二
经脉都是以四肢井穴为根，合称“四根”。以头、胸、腹三部为结，合称“三结”。他归纳
为“四根三结”：手三阴结于“胸”；足三阴结于“腹”；手足三阳结于“头”。在足六经
根结的基础上，使经络的根结理论更臻完善。
 
足六经根结表

《灵枢·根结》还有一段话至关重要：“用针之要，在于知调阴与阳。调阴与阳，精气乃光，
合形与气，使神内藏。故曰：上工平气，中工乱脉，下工绝气危生。”运用九针的要领，则
在于懂得调和阴阳。调和好了阴阳，精气就可以充足，形体与神气能相合，神气便能内藏而
密固，真正高明的医生，能够调理阴阳之气，使阴阳之气平衡。不懂阴阳之道的医生，由于
他们的无知，常常会扰乱患者经脉之气。而医术低劣的庸医，则会采用一些切割损毁的方法，
耗绝患者的精气而危害他们的生命。
 
“九针之玄，要在终始（标本根结）。故能知终始，一言而毕，不知终始，针道咸绝。”运
用九针，其精要就在于标本根结，如果明了标本根结，则一句话就可以说清楚，若不明标本
根结，根本就谈不上什么道理，无论张口动手，从一开始就全部是错的。
 
我们再来看看根结篇对于根结的描述:“太阳根于至阴，结于命门。命门者，目也。阳明根
于厉兑，结于颡大。颡大者，钳耳也。少阳根于窍阴，结于窗笼。窗笼者，耳中也。……太
阴根于隐白，结于太仓。少阴根于涌泉，结于廉泉。厥阴根于大敦，结于玉英，络于膻
中。”通过卫气篇和根结篇的对比，可以看出，经脉的根结与标本理论是一致的，经脉的根
与本都位于四肢，有些经脉的“本”就是它们的“根”，结与标都位于头、胸、腹、背。二
者特别突出了四肢部经脉的重要性。
 
标本和根结都非常重要，所谓标，指事物的表面；所谓本，指事物的根本。所谓根，指根本、
开始，经气始生始发之地。所谓结，指结聚、归结，为经气归结之所。人们常说治病要寻求
根本，因为只有解决“根本”问题才是彻底治愈疾病的真相。
 
总结一下标本根结，我们就会发现：“本”的部位不像“根”那样专指四肢末端的井穴，而
是位置有高有低，大体位于肘膝关节以下；“标”的部位则以脏腑背腧穴为重点。四肢部位
的经脉特别是肘膝关节以下的部分“根”和“本”，头面、胸、腹、背部位的经脉为“结”
和“标”。
 
为何经脉的“根”和“本”都在手足远端？《灵枢·邪客》里有答案：“卫气者，出其悍气
之慓疾，而先行于四末，分肉皮肤之间，而不休者也。”卫气是水谷之悍气，正常而健康的
人，他们的卫气是慓悍疾滑的，就可以先充实到四肢的远端。而卫气弱的人，就不能令远端
充实，就会出现手足冰凉、指甲苍白、指腹干瘪、干燥开裂等等状况。所以我们通过观察一
个人四肢末端的气血状态，就可以判断这个人气血的强弱。
 
在临床上，针刺四肢肘膝关节以下的腧穴，也比较容易取得疗效，主治病证的范围也比较广
泛，不仅能治局部的病，也能治远处部位的脏腑病、头面五官疾病等。就是因为卫气先行于
四末，而且悍气慓疾，调节的能量强大。
