= “规律医学”——写在2017国医节培训课前
陈立新
2017-02-24

3月17日，一群对内经医学怀有深厚感情的人，将聚到一起，这一天是中国的“国医节”，
这一次的主题是“规律医学”。

提到自然规律，所有人都知道，生老病死、风雨雷电、春夏秋冬、太阳从东边升起西边落下、
水往低处流等等都是自然规律。但提到人身上的规律，恐怕很多人就有点“日用而不知”了。

人身上的自然规律是什么？比如所有人都是一个脑袋俩眼睛、双手两腿、十个脚趾、十个手
指、都用脑袋思考、嘴巴说话、耳朵听音、眼睛视物、用脚走路、拿嘴吃饭、肛门排泄等等，
这些就是规律，因为所有人都这样。有没有不一样的？有，比如连体婴儿、天生没有四肢、
六个手指、十一个脚趾、三条腿之类的人，是有的，但地球上七十多亿人口里，有几个这样
的特殊呢？我们是研究普遍性的人类生命现象，不是钻牛角尖抬杠的，个例不能作为人类医
学的大道来遵行。

自然规律其实也是一种本能，比如一说请坐，所有人都无需思考，直接就屁股坐在凳子上了，
有没有人头朝下脚朝上反过来用脑袋坐凳子的呢？除非故意，否则是没有的。吃饭的时候，
正常人不可能端起碗来要寻找很久或思考半天才知道食物应该往嘴里塞进去，有没有人把饭
菜往肛门里塞的？没有，傻子都知道嘴才是食物的入口，这就是本能，也是所有人类必须遵
循的规律。

出于本能的行为，发挥可以超于常态，本能无需琢磨思考，所以不会消耗太多的心神，这是
一种令我非常渴望的境界。比如开车，所有新手都有一个学习摸索熟练的过程，最后才能成
为老司机。新手都会非常紧张、害怕，两眼直勾勾的盯着路面，两手死死地抓着方向盘，就
这样专注的程度，还是控制不了，时常出点大大小小的事故。慢慢的，新手变成了熟手，开
始放松驾驶，开车大多数时候都无需思考这一步做什么下一步该干啥，可以单手很随意地操
控汽车，甚至凭本能开车，但这个阶段，还没有达到人车合一，所以无论操控力还是应变能
力，都还很一般。真正到了高手的层次，是人车合一的，车身或路面细微的异常和变化，他
都能感觉得到，突发事故的时候，反应也是敏捷而冷静的，开车已经形同走路吃饭一样地忘
记了规矩，但一切又都在规矩之中，这样的司机，才是驾驶行业的真正高手。换句话说，新
手是“肌肉”在驾驶，熟手是“身体”在驾驶，而高手是“神”在驾驶，这就是区别。每个
行业都一样，在针灸这个行业，也是这样的规律，只不过，老司机常见，达神者罕见。

如果针灸医生能够以“神”来驾驭自己的医疗行为，那就是神医了。一说“神医”，那就不
得了啦，中国人最喜欢踏遍千山万水去追逐“神医”。可是很少有人明白，真正神医，一定
是明理至清透亮的，极其罕见，这样的人哪里是那么容易找到的，一般的俗人，是达不到神
这个层面的。深山老林或道观庙宇里藏着的，已经远离红尘，如果不是悟性超强慧根非凡之
人，往往只是“术”这个层面的老司机，也就是经验医学的收藏者。大多数所谓“神医”，
只是在个例或少数病案方面有经验的继承或积累，因而施展有些得心应手。实际上，只要是
经验医学，内心就一定有很多不明而为的地方，所以在不走运的时候也难免犯糊涂，倘若某
一日不慎犯蠢，多年苦心积累经营起来的声誉，立刻身败名裂。

在“神”这个层面之下，是本能。能够形成一种本能，也好啊，接触过针灸行业的人都知道，
通常情况下，针灸医生都需要向每个患者望闻问切触摸检查半天，然后思索良久，策略组穴，
最后才下针，这种状态不但效率很低，而且疗效大多时候还得不到保障。这就是用“身体”
在扎针的老司机，整天忙碌的累乏。如果能够养成一种本能，来了患者，一眼便知，伸手就
针，针出即效，疗效稳定，这样的境界，该多好啊，我相信这是所有医生的追求。

我曾经很长一段时间不知道本能应该如何练就或提升，一直在经验医学上打转，以为经验积
累到一定厚度，就一定可以得道。事实上我越走越累，因为经验越来越多，就越来越繁杂，
越来越被束缚。直至通过解读内经，渐渐的我才明白了，回归自然规律，就能够养成本能的
习惯，才能够真正地释放。作为人类医学，是为生命服务的，首先是要安全，其次有效，还
必须稳定，更要轻松快捷，如何能满足这几点？靠经验，是不靠谱的，经验是从已发生的事
件中获取的知识，通常是从多次实践中得到的知识或技能，无论多聪明智慧的人，在思想认
知方面总存在很大范围的局限性，所以经验永远是层出不穷、永无截止的，昨天赵家的经验
疗法占据江山，今天钱家的经验疗法开始兴旺，明天孙家的经验疗法登台亮相，后天李家的
经验疗法又总结出来了……有完没完？这就是经验医学的累赘，学者不断地四处学习，直至
掏空钱包，由于经验来之不易，往往经历若干代人传承，或消耗大量人力物力得来，所以经
验的价值往往被人们所高估。当我们把蒙蔽在我们心神上的那些尘垢扫去的时候，就会发现：
任何个人或家族或门派的经验，都远远无法与自然规律的价值相提并论。试想啊，普天下的
人，谁能不遵循自然规律而活着呢？？没有！即使有，那也是极个别的，可以忽略不计。所
以只要把自然规律研究搞明白了，置之于人类生命医学研究领域里去，那就会有90％以上的
安全性和成功率。

自然规律，不是人为的吃一堑长一智或千百次试验得出来的经验。经验虽然也有一些规律，
但那些规律是局限而狭隘的认知，还是属于知其然不知其所以然，任何经验医学，都有神奇
疗效的展现，比如手针、耳针、头皮针、对应针、奇穴针等等，你只要去了解一下，每个疗
法都有大量神奇得不可思议的病案，但共通点就是都存在很大的局限性，会受时间和空间的
变化而影响疗效，在通常情况下表现还好，在一定时间范围内的表现也还好，一旦环境时间
对象发生变化，或效或不效就由不得你了。而自然规律则是基于时间与空间这个概念上的一
种自然状态，具有自然性、客观性、反复性、必然性、稳定性、普遍性。自然规律这个层面
上的医学，闭着眼治病也是安全的，无论你面对男还是女，老还是少，达官贵人还是贫民百
姓，中国人还是外国人，无论是在东南西北中各地区，也无论是在地球这端还是地球另一端，
只要有自然规律存在的地方，你都会形成一种本能的医疗方法和措施，安全，疗效，稳定性，
都不是问题。这就不得了，仅仅想象就令人快乐无比，呵呵，这个牛吹得太神了是吧？事实
上这真不是吹牛神话，有人嘲讽也不奇怪，就犹如开车，新手和老司机，两种境界，新手如
何能理解老司机凭本能开车的境界？大多数人之所以无法理解内经思想，实在是我们的教育
出了问题，培养出来普遍的线性思维习惯，导致了很多人缺乏抽象思维，难以理解经脉经筋
到底是怎样的一种存在，更无法理解营卫气的状态，又怎可能判断这种境界的真假呢？

于是问题就来了，经脉经筋到底是什么？可以这么理解，内经的经脉就是血液循环，经筋就
是神经系统，但是这种理解是对的又是错的，经脉经筋既是血管神经，也不是血管神经。要
知道，人体治病，无论中医西医，都离不开在神经血管上做文章，但内经医学虽然以神经血
管为基础，实际上已经脱离了神经血管的束缚。我在几年前在广州北京学术讲座的时候，曾
经说过九针是一种思想，就是这个意思，很多人都认为针是扎肌肉神经的，其实内经医学的
针，根本不是用来刺肌肉神经血管骨骼脏器的，如果针刺这些组织，就一定存在安全隐患，
出医疗事故是迟早的事。内经医学的高大上，就在于内经属于一种三维甚至四维的空间立体
思维，与通常意义上的中医和西医，在思维和思想格局上是完全不同的，这才是我对《黄帝
内经》崇拜得五体投地的原因。

绝对不能在肌肉解剖的基础上去理解和运用内经医学里的那些理念，诸如经脉、经筋、精气
神、脏腑十二官、开合枢、四关、四街、四海、五输、八虚、标本根结、卫气行等等，如果
站在解剖学的角度去理解，是理解不了的，至少经脉经筋就无法理解，实实在在的就是这个
横七竖八的结构，怎么就有了三阴三阳十二经筋的呢？如果不研究学习内经医学那就无所谓，
如果内经医学离开了经脉经筋，针灸就根本无法运用了。事实上所有的疗法，无论中医西医，
取得的疗效都是在人体气血上做出来的文章，你可以不承认经脉经筋，可以叫做别的名称，
手段方法也可以花样百出，但你终究还是没有离开经脉经筋，没有脱离营气卫气。如果是以
内经思想为理论基础的针灸疗法，经脉和经筋绝对是非常重要的基础之一，事关生死，不可
不通，不可不知，就犹如我们出门去一个陌生地方的地图，有地图就比较一清二楚，没有地
图就是茫然的。

学针灸，别想在经验上走捷径，那将永远茫然，一定要把十二经脉和经筋的循行路线熟悉。
这是基础知识，很多针灸医生疗效做得不太好，其中很大部分原因就在于不明经脉经筋。你
可以扪心自问一下，你对经脉经筋了解有多少？对于很多人来说，困惑也正是在这里，要怎
样理解经脉经筋？我的观点是，我们可以借助现代医学的神经血管解剖学来作为辅助，这有
助于我们更好地理解运用经脉经筋，但仅仅有解剖的认知，是远远不够的，最重要的是回到
自然规律上去，充分地发挥内经医学“援物比类”的思维方式，远取诸物近取诸身，然后逐
渐地形成一种本能思维和行为习惯。

本能，就不需要苦心思虑、详尽安排、周密计划、总体策划，因为这些已经成为我们思想行
为的一种本能，我们只需随心所欲就可以了。这样的医疗行为，在现代医学看来，完全是天
方夜谭：医生治病要想不担惊受怕，不殚精竭虑，不劳命伤财，怎么可能呢？可是真的就有
这个可能，在内经医学里，一切都遵循自然规律来的，到了一定的境界以后，根本无需人为
的计划安排，大多数情况下治疗患者，都可以做到随心所欲，信手拈来。

遵循自然规律的医学，医生会成为最轻松的、也是最不像医生的医生。


按：明天，立新先生将对经脉上下游理论之应用作精彩阐述，敬请期待。若您对先生之言有
何感想、感悟、疑问，欢迎留言。若您想阅读更多先生的文章，可以在我们公众号回复关键
字“立新说”即可。
